create or replace TRIGGER OS_UPD_LIMGERAL
BEFORE INSERT OR UPDATE ON PESSOALIMCRED
FOR EACH ROW
DECLARE
V_DTINI DATE;
V_DTFIM DATE;
BEGIN
    IF :NEW.LIMCRED_ID = 996 AND NVL(:NEW.VLRLIMITE,0) > 0 THEN

        SELECT VIGINI,VIGFIM 
        INTO V_DTINI,V_DTFIM FROM U_ALTCONLIMITE
        WHERE U_ALTCONLIMITE.ESTAB = 1
        AND U_ALTCONLIMITE.ID = 996
        AND VIGINI IS NOT NULL AND VIGFIM IS NOT NULL;


        UPDATE PPESCLI
            SET VLRLIMCRED = :NEW.VLRLIMITE
        WHERE PPESCLI.CLIENTE = :NEW.NUMEROCM;

        IF V_DTINI IS NOT NULL AND V_DTFIM IS NOT NULL THEN
            UPDATE CONTAMOV
                SET DTVGINICIAL = V_DTINI,
                VENCTOLIMCRED = V_DTFIM
            WHERE CONTAMOV.NUMEROCM = :NEW.NUMEROCM;
        END IF;

    END IF;
END;