WITH COBRAR AS (
 
SELECT
 
DADOS1.ESTAB,
DADOS1.NUMEROCM,
DADOS1.SEQENDERECO,
DADOS1.ITEM,
DADOS1.SALDO
FROM(
    
SELECT
CASE
    -- REGAR DA CARÊNCIA
    WHEN TRUNC(CURRENT_DATE - DATADEP) >= NDIACARENCIA AND DTVIGENCIAINI IS NULL AND MAXDATA IS NULL THEN 'PODE COBRAR'
    WHEN TRUNC(CURRENT_DATE - DATADEP) < NDIACARENCIA AND DTVIGENCIAINI IS NULL AND MAXDATA IS NULL THEN 'NAO COBRAR'
    -- ESTAMOS ENTRE 1 E 15 DO MÊS ATUAL
    WHEN TO_NUMBER(TO_CHAR(SYSDATE, 'DD')) <= 15 THEN
        CASE
            WHEN MAXDATA IS NULL THEN 'PODE COBRAR'
            WHEN TRUNC(MAXDATA, 'MM') < TRUNC(SYSDATE, 'MM') THEN 'PODE COBRAR'
            WHEN TRUNC(MAXDATA, 'MM') = TRUNC(SYSDATE, 'MM')
                 AND TO_NUMBER(TO_CHAR(MAXDATA, 'DD')) <= 15 THEN 'NAO COBRAR'
            ELSE 'PODE COBRAR'
        END
 
    -- ESTAMOS APÓS O DIA 15 DO MÊS
    ELSE
        CASE
            WHEN MAXDATA IS NULL THEN 'PODE COBRAR'
            WHEN TRUNC(MAXDATA, 'MM') < TRUNC(SYSDATE, 'MM') THEN 'PODE COBRAR'
            WHEN TO_NUMBER(TO_CHAR(MAXDATA, 'DD')) <= 15 THEN 'PODE COBRAR'
            WHEN TRUNC(MAXDATA, 'MM') = TRUNC(SYSDATE, 'MM')
                 AND TO_NUMBER(TO_CHAR(MAXDATA, 'DD')) > 15 THEN 'NAO COBRAR'
            ELSE 'PODE COBRAR'
        END
END AS STATUS_COBRANCA,
DADOS.*
 
 
FROM(
 
SELECT
NFCAB.NOTA,
NFCAB.STATUS,
(NFCAB.NUMEROCM),
COALESCE(NFCAB.SEQENDERECO,0)SEQENDERECO,
CONTAMOV.NOME,
NFITEM.ITEM,
TABPRCSERV,
TABPRCSERVCAB.NDIACARENCIA,
TABPRCSERVCAB.DTVIGENCIAINI,
NFITEM.ROMANEIO,
NFITEMTXSERVICO.ESTAB,
NFITEMTXSERVICO.SEQNOTA,
NFITEMTXSERVICO.SEQNOTAITEM,
NFITEMTXSERVICO.SEQUENCIA,
NFITEMTXSERVICO.SERVICO,
NFITEMTXSERVICO.DATADEP,
(NFITEM.QUANTIDADE) AS QUANTIDADE,
PARTIDE.QTD,
(NFITEM.QUANTIDADE) - COALESCE(PARTIDE.QTD,0) AS SALDO,
MAX(NF.DTEMISSAO) AS MAXDATA,
EXTRACT(DAY FROM CURRENT_DATE) AS DIA,
SUM(NFITEMTXSERVICOPG.VLRPAGO) AS PAGO
FROM NFITEMTXSERVICO
 
LEFT JOIN TABPRCSERVCAB ON TABPRCSERVCAB.TABELA = NFITEMTXSERVICO.TABPRCSERV
 
INNER JOIN NFCAB ON
    NFCAB.ESTAB = NFITEMTXSERVICO.ESTAB
    AND NFCAB.SEQNOTA = NFITEMTXSERVICO.SEQNOTA
 
INNER JOIN NFITEM ON
    NFITEM.ESTAB = NFITEMTXSERVICO.ESTAB
    AND NFITEM.SEQNOTA = NFITEMTXSERVICO.SEQNOTA
    AND NFITEM.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
 
LEFT JOIN (
    SELECT
    ESTABORIGEM,
    SEQNOTAORIGEM,
    SEQNOTAITEMORIGEM,
    SUM(QUANTIDADE) QTD
    FROM NFITEMAPARTIRDE D
    GROUP BY
    ESTABORIGEM,SEQNOTAORIGEM,SEQNOTAITEMORIGEM
)PARTIDE ON
PARTIDE.ESTABORIGEM = NFITEMTXSERVICO.ESTAB
AND PARTIDE.SEQNOTAORIGEM = NFITEMTXSERVICO.SEQNOTA
AND PARTIDE.SEQNOTAITEMORIGEM = NFITEMTXSERVICO.SEQNOTAITEM
 
 
LEFT JOIN NFITEMTXSERVICOPG ON
    NFITEMTXSERVICOPG.ESTAB = NFITEMTXSERVICO.ESTAB
    AND NFITEMTXSERVICOPG.SEQNOTA = NFITEMTXSERVICO.SEQNOTA
    AND NFITEMTXSERVICOPG.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
    AND NFITEMTXSERVICOPG.SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA
 
LEFT JOIN NFCAB NF ON
    NF.ESTAB = NFITEMTXSERVICOPG.ESTABNOTADEV
    AND NF.SEQNOTA = NFITEMTXSERVICOPG.SEQNOTADEV
 
LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
 
WHERE
NFITEMTXSERVICO.SERVICO = 31
AND NFITEMTXSERVICO.SITUACAO = 'P'
--AND NFITEMTXSERVICO.ESTAB IN(7,10,17,33,36,65,83)
AND (
    -- REGRA 1: SE HOUVER DATA DE INÍCIO DE VIGÊNCIA
    (TABPRCSERVCAB.DTVIGENCIAINI IS NOT NULL AND NFITEMTXSERVICO.DATADEP >= TABPRCSERVCAB.DTVIGENCIAINI)
 
    OR
    -- TEM DATA DE INICIO, TEM SALDO, POREM O DEPOSITO ACONTECEU ANTES DA VIGENCIA INICIAL E VALIDANDO INICIO DA TABELA
    (TABPRCSERVCAB.DTVIGENCIAINI IS NOT NULL AND ((NFITEM.QUANTIDADE) - COALESCE(PARTIDE.QTD,0)) > 0 AND  NFITEMTXSERVICO.DATADEP <= TABPRCSERVCAB.DTVIGENCIAFIN AND CURRENT_DATE >= TABPRCSERVCAB.DTVIGENCIAINI)
    OR
 
    (TABPRCSERVCAB.DTVIGENCIAINI IS NULL )
 
)
AND NFITEM.ROMANEIO > 0  
AND (NFCAB.NOTA > 0 OR NFCAB.SERIE = 'NFG')
 
GROUP BY
NFCAB.NOTA,
NFCAB.STATUS,
NFITEM.ITEM,
TABPRCSERV,
TABPRCSERVCAB.NDIACARENCIA,
TABPRCSERVCAB.DTVIGENCIAINI,
NFITEM.ROMANEIO,
NFITEMTXSERVICO.ESTAB,
NFITEMTXSERVICO.SEQNOTA,
NFITEMTXSERVICO.SEQNOTAITEM,
NFITEMTXSERVICO.SEQUENCIA,
NFITEMTXSERVICO.SERVICO,
NFITEMTXSERVICO.DATADEP,
(NFITEM.QUANTIDADE),
PARTIDE.QTD,
CONTAMOV.NOME,
NFCAB.NUMEROCM,
NFITEMTXSERVICO.TABPRCSERV,
EXTRACT(DAY FROM CURRENT_DATE) ,
NFCAB.SEQENDERECO
 
)DADOS
 
WHERE
(
(ARREDONDAR(DADOS.SALDO,0) > 0)   
)
 
)DADOS1
WHERE
 
DADOS1.STATUS_COBRANCA = 'PODE COBRAR'
 
ORDER BY DADOS1.ESTAB, DADOS1.NUMEROCM
)
SELECT
 
COBRAR.*,
 
31 AS SERVICO
 
FROM COBRAR

 