WITH PROD AS (
    SELECT DISTINCT
        ITEMAGRO.NCM
    FROM ITEMAGRO
    JOIN ITEMGRUPO
      ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    WHERE ITEMGRUPO.DESCRICAO LIKE '%CEREAIS%'
       OR ITEMGRUPO.DESCRICAO LIKE '%FARELO%'
),
EVENTOS AS (
    SELECT CHAVE
    FROM U_NOTASSIEG_EVENTOS
    WHERE UPPER(XEVENTO) LIKE '%DESCONHE%'
       OR UPPER(XEVENTO) LIKE '%CANCEL%'
),
MOTIVO AS (
    SELECT CHAVEACESSO
    FROM U_MOTIVO_TRADING
    WHERE MOTIVO IN ('CNF - Nota Fiscal Cancelada','CNF - NF Divergente/Recusada')
),
ROBO AS (
    SELECT
        CHAVEACESSONFE,
        CASE WHEN CONTRATO = 0 THEN NULL ELSE CONTRATO END CONTRATO,
        CASE WHEN IDCARGA = 0 THEN NULL ELSE IDCARGA END IDCARGA,
        CASE WHEN NOTACONF = 0 THEN NULL ELSE NOTACONF END NOTACONF,
        CASE WHEN NOTAFILHA = 0 THEN NULL ELSE NOTAFILHA END NOTAFILHA,
        TIPOPESSOA
    FROM U_CONFENOTAROBO
)
SELECT
    U_FISCAL_IO_CONT_ID,
    F.CHAVEACESSO,
    F.DTEMISSAO AS DTEMISS,
    F.NUMERONOTA,
    F.SERIE,
    F.CNPJF,
    F.IEEMITENTE,
    F.ESTAB,
    F.CFOP,
    F.PLACA,
    F.NCM,
    F.ITEM,
    F.QUANTIDADE,
    F.UNIDADETRIBUTAVEL,
    F.VALORTOTAL,
    NVL(R.IDCARGA,F.ORDEMCARGA) AS ORDEMCARGA,
    F.LOCALESTOQUE,
    NVL(R.CONTRATO,F.CONTRATO) AS CONTRATO,
    CASE
        WHEN R.TIPOPESSOA = 'P' THEN 'S'
        WHEN R.TIPOPESSOA <> 'P' THEN 'N'
        WHEN R.TIPOPESSOA IS NULL THEN TO_CHAR(F.PRODUTOR)
    END PRODUTOR,
    CASE WHEN R.CHAVEACESSONFE IS NOT NULL THEN '100' ELSE TO_CHAR(F.STATUS) END STATUS,
    F.MENSAGEMERRO,
    F.DTPROCESSAMENTO,
    F.REPROCESSADO,
    F.SEQENDERECO,
    F.DIFVIASOFT,
    F.DIFAPP,
    F.ESTABCONTRATO,
    F.VALIDANCM,
    NVL(R.NOTACONF,F.NOTACONF) AS NOTACONF,
    F.TIPOBAIXA,
    F.CONTCONF,
    F.STATUS_NOTA,
    NVL(R.NOTAFILHA,F.NOTAREF) AS NOTAFILHA,
    F.CLASSIF_LOCAL,
    F.NUMEROCM,
    LPAD(EXTRACT(DAY FROM F.DTEMISSAO), 2, '0') ||
    LPAD(EXTRACT(MONTH FROM F.DTEMISSAO), 2, '0') ||
    EXTRACT(YEAR FROM F.DTEMISSAO) AS DTEMISSAO
FROM U_FISCAL_IO_CONT F
JOIN PROD
  ON PROD.NCM = F.NCM
JOIN U_TEMPRESA U
  ON U.ESTAB = F.ESTAB
LEFT JOIN ROBO R
  ON R.CHAVEACESSONFE = F.CHAVEACESSO
LEFT JOIN CONCEITOPESSOA P
  ON P.NUMEROCM = F.NUMEROCM
WHERE NVL(F.STATUS_NOTA,'100') <> '101'
  AND U.GRAOS = 'S'
  AND U.EXVENDA = 'S'
  AND NVL(P.CONCEITO,0) <> 98
  AND NOT EXISTS (
      SELECT 1
      FROM NFCAB N
      JOIN NFITEM I
        ON I.ESTAB = N.ESTAB
       AND I.SEQNOTA = N.SEQNOTA
      WHERE N.CHAVEACESSONFE = F.CHAVEACESSO
        AND I.CFOP NOT IN (5906,5907,5117,5116,5101,5102,6101,6102)
  )
  AND NOT EXISTS (
      SELECT 1
      FROM NFCABPRODUTOR NP
      WHERE NP.CHAVEACESSONFP = F.CHAVEACESSO
  )
  AND NOT EXISTS (
      SELECT 1
      FROM EVENTOS E
      WHERE E.CHAVE = F.CHAVEACESSO
  )
  AND NOT EXISTS (
      SELECT 1
      FROM MOTIVO M
      WHERE M.CHAVEACESSO = F.CHAVEACESSO
  )
