WITH PROD AS (
    SELECT DISTINCT
           ITEMAGRO.NCM
    FROM ITEMAGRO
    JOIN ITEMGRUPO
      ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    WHERE ITEMGRUPO.DESCRICAO LIKE '%CEREAIS%'
       OR ITEMGRUPO.DESCRICAO LIKE '%FARELO%'
),

EVENTOS AS (
    SELECT CHAVE
    FROM U_NOTASSIEG_EVENTOS
    WHERE UPPER(XEVENTO) LIKE '%DESCONHE%'
       OR UPPER(XEVENTO) = 'OPERACAO NAO REALIZADA'
       OR (
            UPPER(XEVENTO) LIKE '%CANCEL%'
            AND UPPER(XEVENTO) NOT LIKE 'CANCELAMENTO%AUTORIZADO%'
       )
),

MOTIVO AS (
    SELECT CHAVEACESSO
    FROM U_MOTIVO_TRADING
    WHERE MOTIVO IN (
        'CNF - Nota Fiscal Cancelada',
        'CNF - NF Divergente/Recusada'
    )
),

ROBO AS (
    SELECT
        CHAVEACESSONFE,
        CASE
            WHEN CONTRATO = 0 THEN NULL
            ELSE CONTRATO
        END AS CONTRATO,
        CASE
            WHEN IDCARGA = 0 THEN NULL
            ELSE IDCARGA
        END AS IDCARGA,
        CASE
            WHEN NOTACONF = 0 THEN NULL
            ELSE NOTACONF
        END AS NOTACONF,
        CASE
            WHEN NOTAFILHA = 0 THEN NULL
            ELSE NOTAFILHA
        END AS NOTAFILHA,
        TIPOPESSOA
    FROM U_CONFENOTAROBO
),

/*
    OTIMIZAÇÃO:
    Primeiro materializamos somente as chaves que podem chegar
    à consulta final da view.

    No cenário atual:
      ~29.606 registros em U_FISCAL_IO_CONT
      ~22.207 chaves relevantes
*/
CHAVES AS (
    SELECT /*+ MATERIALIZE */
           DISTINCT F.CHAVEACESSO
    FROM U_FISCAL_IO_CONT F
    JOIN U_TEMPRESA U
      ON U.ESTAB = F.ESTAB
    LEFT JOIN CONCEITOPESSOA P
      ON P.NUMEROCM = F.NUMEROCM
    WHERE NVL(F.STATUS_NOTA, '100') <> '101'
      AND U.GRAOS = 'S'
      AND U.EXVENDA = 'S'
      AND NVL(P.CONCEITO, 0) <> 98
),

/*
    Em vez de executar o NOT EXISTS NFCAB + NFITEM para
    cada linha de F, primeiro identificamos as CHAVES que
    possuem algum NFITEM com CFOP fora da lista permitida.

    A materialização permite que o Oracle faça:

        CHAVES
           ↓
        NFCAB relevante
           ↓
        NFITEM por IDX_NFITEM_CARGA

    No teste realizado:
        22.207 CHAVES
        19.331 NFCAB relevantes
        19.859 NFITEM acessados

    Em vez de FULL SCAN de ~5 milhões de NFITEM.
*/
CHAVES_COM_CFOP_INVALIDO AS (
    SELECT /*+ MATERIALIZE */
           DISTINCT N.CHAVEACESSONFE AS CHAVEACESSO
    FROM NFCAB N
    JOIN CHAVES C
      ON C.CHAVEACESSO = N.CHAVEACESSONFE
    JOIN NFITEM I
      ON I.ESTAB = N.ESTAB
     AND I.SEQNOTA = N.SEQNOTA
    WHERE I.CFOP NOT IN (
        5906,
        5907,
        5117,
        5116,
        5101,
        5102,
        6101,
        6102
    )
)

SELECT
    U_FISCAL_IO_CONT_ID,
    F.CHAVEACESSO,

    F.DTEMISSAO AS DTEMISS,

    F.NUMERONOTA,
    F.SERIE,
    F.CNPJF,

    CASE
        WHEN CIDADE.UF = 'MG'
            THEN LPAD(F.IEEMITENTE, 13, '0')
        ELSE F.IEEMITENTE
    END AS IEEMITENTE,

    F.ESTAB,
    F.CFOP,
    F.PLACA,
    F.NCM,
    F.ITEM,

    ROUND(F.QUANTIDADE, 2) AS QUANTIDADE,

    F.UNIDADETRIBUTAVEL,
    F.VALORTOTAL,

    NVL(R.IDCARGA, F.ORDEMCARGA) AS ORDEMCARGA,

    F.LOCALESTOQUE,

    NVL(R.CONTRATO, F.CONTRATO) AS CONTRATO,

    CASE
        WHEN R.TIPOPESSOA = 'P' THEN 'S'
        WHEN R.TIPOPESSOA <> 'P' THEN 'N'
        WHEN R.TIPOPESSOA IS NULL THEN TO_CHAR(F.PRODUTOR)
    END AS PRODUTOR,

    CASE
        WHEN R.CHAVEACESSONFE IS NOT NULL THEN '100'
        ELSE TO_CHAR(F.STATUS)
    END AS STATUS,

    F.MENSAGEMERRO,
    F.DTPROCESSAMENTO,
    F.REPROCESSADO,
    F.SEQENDERECO,
    F.DIFVIASOFT,
    F.DIFAPP,
    F.ESTABCONTRATO,
    F.VALIDANCM,

    NVL(R.NOTACONF, F.NOTACONF) AS NOTACONF,

    F.TIPOBAIXA,
    F.CONTCONF,
    F.STATUS_NOTA,

    NVL(R.NOTAFILHA, F.NOTAREF) AS NOTAFILHA,

    F.CLASSIF_LOCAL,
    F.NUMEROCM,

    LPAD(EXTRACT(DAY FROM F.DTEMISSAO), 2, '0') ||
    LPAD(EXTRACT(MONTH FROM F.DTEMISSAO), 2, '0') ||
    EXTRACT(YEAR FROM F.DTEMISSAO) AS DTEMISSAO,

    F.DATA_EMISSAO,

    NVL(CONTRATO.DTVENCTO, F.DTVENCTO_CTR) AS DTVENCTO_CTR,

    TO_CHAR(
        F.DT_INSERT,
        'DD/MM/YYYY HH24:MI:SS'
    ) AS DT_INSERCAO,

    T.MOTIVO AS OBS

FROM U_FISCAL_IO_CONT F

JOIN PROD
  ON PROD.NCM = F.NCM

JOIN U_TEMPRESA U
  ON U.ESTAB = F.ESTAB

LEFT JOIN ROBO R
  ON R.CHAVEACESSONFE = F.CHAVEACESSO

LEFT JOIN CONTRATO
  ON CONTRATO.ESTAB = F.ESTAB
 AND CONTRATO.CONTRATO = R.CONTRATO

LEFT JOIN CONCEITOPESSOA P
  ON P.NUMEROCM = F.NUMEROCM

JOIN FILIAL
  ON FILIAL.ESTAB = F.ESTAB

JOIN CIDADE
  ON CIDADE.CIDADE = FILIAL.CIDADE

LEFT JOIN U_MOTIVO_TRADING T
  ON T.CHAVEACESSO = F.CHAVEACESSO

WHERE NVL(F.STATUS_NOTA, '100') <> '101'

  AND U.GRAOS = 'S'

  AND U.EXVENDA = 'S'

  AND NVL(P.CONCEITO, 0) <> 98

  /*
      OTIMIZAÇÃO DO ANTIGO:

      AND NOT EXISTS (
          SELECT 1
          FROM NFCAB N
          JOIN NFITEM I
            ON I.ESTAB = N.ESTAB
           AND I.SEQNOTA = N.SEQNOTA
          WHERE N.CHAVEACESSONFE = F.CHAVEACESSO
            AND I.CFOP NOT IN (...)
      )

      Agora a consulta utiliza o conjunto de chaves
      previamente materializado.
  */
  AND NOT EXISTS (
      SELECT 1
      FROM CHAVES_COM_CFOP_INVALIDO X
      WHERE X.CHAVEACESSO = F.CHAVEACESSO
  )

  AND NOT EXISTS (
      SELECT 1
      FROM NFCABPRODUTOR NP
      WHERE NP.CHAVEACESSONFP = F.CHAVEACESSO
  )

  AND NOT EXISTS (
      SELECT 1
      FROM EVENTOS E
      WHERE E.CHAVE = F.CHAVEACESSO
  )

  AND NOT EXISTS (
      SELECT 1
      FROM MOTIVO M
      WHERE M.CHAVEACESSO = F.CHAVEACESSO
  );