SELECT DADOS.ESTAB as OSESTAB,
       DADOS.ITEM as OSPRODUTO,
	   CURRENT_DATE as DTPOSICAO,
	   DADOS.KGLT,
	   DADOS.MARGEM,
	   DADOS.CUSTOGERENCIAL,
	   DADOS.PRECOVENDA,
	   DADOS.CUSTOCMV,
       DADOS.CUSTOCOMPRA,
       SUM(DISPONIVEL)DISPONIVEL,
       SUM(PEDIDOTRANSF)PEDIDOTRANSF,
	   SUM(VENDAFUT) VENDAFUT,
	   SUM(COMPRAFUT)COMPRAFUT,
	   SUM(PEDIDOCOMP)PEDIDOCOMP,
	   SUM(PEDIDOVEND)PEDIDOVEND,
	   SUM(EMTERCEIRO)EMTERCEIRO,
	   SUM(DETERCEIRO)DETERCEIRO,
	   SUM(CONTABIL)CONTABIL,
	   SUM(EMTRANSITO)EMTRANSITO,
	   SUM(FISICO)FISICO,
       SUM(CARTEIRA)CARTEIRA

FROM(
SELECT 
    DADOS.ESTAB,
    COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
		
	LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB	
		
		
		
    WHERE 
	
	(((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S')))
	
	and ITEMSALDO.codigosaldo=1 
      
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 1
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
		
		 LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
		
    WHERE
	
	(((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S')))
	
	
	and ITEMSALDO.codigosaldo=16
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 16
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S')))
	and ITEMSALDO.codigosaldo=11
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 11
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)

-- WHERE  DADOS.ESTAB in (2,4,5,8,9,10,13,15,19,28,29,57)
--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
    LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S')))
	and ITEMSALDO.codigosaldo=6
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 6
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S')))
	and ITEMSALDO.codigosaldo=8 
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 8
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	
	and ITEMSALDO.codigosaldo=7 
      
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 7
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	and ITEMSALDO.codigosaldo=4
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 4
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	and ITEMSALDO.codigosaldo=13 
     
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 13
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	
	and ITEMSALDO.codigosaldo=5 
 
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 5
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as EMTRANSITO,
	0 as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	and ITEMSALDO.codigosaldo=20 
      
    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 20
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
UNION ALL

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) as FISICO,
    0 CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	and ITEMSALDO.codigosaldo=2 

    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 2
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)

union all

SELECT 
    DADOS.ESTAB,
    0 AS DISPONIVEL,
    0 as PEDIDOTRANSF,
	0 as VENDAFUT,
	0 as COMPRAFUT,
	0 as PEDIDOCOMP,
	0 as PEDIDOVEND,
	0 as EMTERCEIRO,
	0 as DETERCEIRO,
	0 as CONTABIL,
	0 as EMTRANSITO,
	0 as FISICO,
    COALESCE(ITEMSALDO.SALDOQUANTIDADE,0) AS CARTEIRA,
    ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
    
 ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
 PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
  ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
  
    DADOS.ITEM,
	itemagro.pesoliquido KGLT,
    --ITEMAGRO.DESCRICAO,
    --itemagro.unidade,
     -- u_gestoque.u_gestoque_id||'-'||u_gestoque.DESCRICAO GRUPO,
       --ITEMAGRO.GRUPO||'-'||ITEMGRUPO.descricao SUBGR,
       --ITEMMARCA.MARCA||'-'||ITEMMARCA.DESCRICAO AS MARCA,
       --ITEMAGROESTAB.LOCALIZACAO LOCAL,
      -- u_principioativo.u_principioativo_id||'-'||u_principioativo.nomeprincipio as PRINCIPIO,
       ITEMAGRO.ATIVO,

    EXTRACT(YEAR FROM DADOS.DATA) AS ANO,
    EXTRACT(MONTH FROM DADOS.DATA) AS MES

FROM (
  SELECT 
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    MAX(CAST('01/'||LPAD( coalesce(ITEMSALDO.MES,1),2,'0') || '/' || coalesce(ITEMSALDO.ANO,1) AS DATE)) AS DATA    from ITEMAGROESTAB
      LEFT JOIN ITEMSALDO 
        ON ITEMSALDO.ITEM=ITEMAGROESTAB.ITEM 
        AnD itemsaldo.estab = iTemAGROestab.eSTaB
     LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ITEMAGROESTAB.ESTAB
       
    WHERE 
    (((u_tempresa.insumos='S') and (u_tempresa.estoque='S'))
        or ((u_tempresa.insumos='N') and (u_tempresa.estoque='S'))) 
	and ITEMSALDO.codigosaldo=26

    GROUP BY ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM
) DADOS           
INNER JOIN ITEMAGROESTAB 
  ON ITEMAGROESTAB.ESTAB = DADOS.ESTAB 
  AND ITEMAGROESTAB.ITEM = DADOS.ITEM
LEFT JOIN ITEMSALDO 
  ON ITEMSALDO.ITEM = dados.ITEM 
  anD iTEMsaLDo.EstaB = dados.Estab
  anD itemsaldo.codigosaldo = 26
  AnD ITEMSALDO.ANo = EXTRACT(YEAR FROM DADOS.DATA)
  AnD ITEMSALDO.meS = EXTRACT(moNtH FROM DADOS.DATA)
  
INNER JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = DADOS.ITEM
  AND ITEMAGRO.ATIVO='S'
  
LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM

LEFT JOIN u_principioativo ON u_principioativo.u_principioativo_id = itemagro_u.u_principioativo_id
  
INNER JOIN ITEMGRUPO 
  ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
  
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

INNER JOIN ITEMGRUPO_U 
  ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO

INNER JOIN u_gestoque 
  ON u_gestoque.u_gestoque_id = itemgrupo_u.u_gestoque_id
  AND u_gestoque.u_gestoque_id IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)


--and dados.item=35163
)DADOS


WHERE  DADOS.DISPONIVEL <> 0
  OR DADOS.VENDAFUT <> 0
  OR DADOS.FISICO <> 0
  OR DADOS.COMPRAFUT <> 0
  OR DADOS.PEDIDOCOMP <> 0
  OR DADOS.PEDIDOVEND <> 0
  OR DADOS.EMTERCEIRO <> 0
  OR DADOS.DETERCEIRO <> 0
  OR DADOS.CONTABIL <> 0
  OR DADOS.EMTRANSITO <> 0
  OR DADOS.PEDIDOTRANSF <> 0
  OR DADOS.CARTEIRA <> 0


GROUP BY DADOS.ESTAB,
       DADOS.ITEM,
	   DADOS.KGLT,
	   DADOS.MARGEM,
	   DADOS.CUSTOGERENCIAL,
	   DADOS.PRECOVENDA,
	   DADOS.CUSTOCMV,DADOS.CUSTOCOMPRA
	   
