WITH BASE_SALDO AS (
    SELECT
    I.ESTAB,
    I.ITEM,
    I.LOCAL,
    I.CODIGOSALDO,
    I.ANO,
    I.MES,
    ROW_NUMBER() OVER (
            PARTITION BY I.ESTAB, I.LOCAL, I.ITEM, I.CODIGOSALDO
            ORDER BY I.ANO DESC, I.MES DESC
        ) AS RN
    FROM ITEMSALDO I
    INNER JOIN FILIAL ON FILIAL.ESTAB = I.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    WHERE I.CODIGOSALDO IN (1,2,16,11,6,8,7,4,13,5,20,26) 
    AND ( 
        (( U_TEMPRESA.INSUMOS = 'S') AND (U_TEMPRESA.ESTOQUE = 'S' ))
        OR 
        (( U_TEMPRESA.INSUMOS = 'N') AND (U_TEMPRESA.ESTOQUE = 'S')) 
   )
    /*
    1	DISPONIVEL
    2	FISICO
    4	EM TERCEIROS
    5	CONTABIL/PROPRIO
    6	COMPRA FUTURA
    7	PEDIDO DE VENDA
    8	PEDIDO DE COMPRA
    11	VENDA FUTURA
    13	DE TERCEIROS
    16	PEDIDO TRANSFERENCIA
    20	EM TRANSITO
    26	PEDIDO RES/CARTEIRA
    */
),
ESTOQUE AS (
SELECT
B.ESTAB,
B.ITEM,
SUM(CASE WHEN B.CODIGOSALDO = 1 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS DISPONIVEL,
SUM(CASE WHEN B.CODIGOSALDO = 2 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS FISICO,
SUM(CASE WHEN B.CODIGOSALDO = 4 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS EMTERCEIRO,
SUM(CASE WHEN B.CODIGOSALDO = 5 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS CONTABIL,
SUM(CASE WHEN B.CODIGOSALDO = 6 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS COMPRAFUT,
SUM(CASE WHEN B.CODIGOSALDO = 7 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS PEDIDOVEND,
SUM(CASE WHEN B.CODIGOSALDO = 8 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS PEDIDOCOMP,
SUM(CASE WHEN B.CODIGOSALDO = 11 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS VENDAFUT,
SUM(CASE WHEN B.CODIGOSALDO = 13 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS DETERCEIRO,
SUM(CASE WHEN B.CODIGOSALDO = 16 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS PEDIDOTRANSF,
SUM(CASE WHEN B.CODIGOSALDO = 20 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS EMTRANSITO,
SUM(CASE WHEN B.CODIGOSALDO = 26 THEN ITEMSALDO.SALDOQUANTIDADE ELSE 0 END) AS CARTEIRA
FROM BASE_SALDO B

INNER JOIN ITEMSALDO ON
    ITEMSALDO.ESTAB = B.ESTAB
    AND ITEMSALDO.ITEM = B.ITEM
    AND ITEMSALDO.LOCAL = B.LOCAL
    AND ITEMSALDO.CODIGOSALDO = B.CODIGOSALDO
    AND ITEMSALDO.ANO = B.ANO
    AND ITEMSALDO.MES = B.MES

WHERE
B.RN = 1
AND ITEMSALDO.SALDOQUANTIDADE <> 0
GROUP BY
B.ESTAB,B.ITEM
)
SELECT
ITEMAGROESTAB.ESTAB AS OSESTAB,
ITEMAGROESTAB.ITEM AS OSPRODUTO,
CURRENT_DATE as DTPOSICAO,
ITEMAGRO.PESOLIQUIDO AS KGLT,
ITEMAGROESTAB.MARGEMLUCRO AS MARGEM,
ARREDONDAR(ITEMAGROESTAB.CUSTOGERENCIAL,2) AS CUSTOGERENCIAL,
ARREDONDAR(ITEMAGROESTAB.PRECOVENDA,2) AS PRECOVENDA,
PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3,CURRENT_DATE,NULL)CUSTOCMV,
PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,1,CURRENT_DATE,NULL)CUSTOCOMPRA,
ESTOQUE.DISPONIVEL AS DISPONIVEL,
ESTOQUE.FISICO AS FISICO,
ESTOQUE.EMTERCEIRO AS EMTERCEIRO,
ESTOQUE.CONTABIL AS CONTABIL,
ESTOQUE.COMPRAFUT AS COMPRAFUT,
ESTOQUE.PEDIDOVEND AS PEDIDOVEND,
ESTOQUE.PEDIDOCOMP AS PEDIDOCOMP,
ESTOQUE.VENDAFUT AS VENDAFUT,
ESTOQUE.DETERCEIRO AS DETERCEIRO,
ESTOQUE.PEDIDOTRANSF AS PEDIDOTRANSF,
ESTOQUE.EMTRANSITO AS EMTRANSITO,
ESTOQUE.CARTEIRA AS CARTEIRA
FROM ITEMAGROESTAB 

INNER JOIN ESTOQUE ON
    ESTOQUE.ESTAB = ITEMAGROESTAB.ESTAB
    AND ESTOQUE.ITEM = ITEMAGROESTAB.ITEM

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM AND ITEMAGRO.ATIVO='S'
INNER JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
INNER JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO=ITEMGRUPO.GRUPO
INNER JOIN U_GESTOQUE ON 
    U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
    AND U_GESTOQUE.U_GESTOQUE_ID IN (1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17)
