SELECT DADOS.OSRTV,
       DADOS.EMPRESA,
       DADOS.COD_RTV,
        CASE        WHEN  DADOS.DATA BETWEEN '01/06/2019' AND '31/05/2020' THEN '1920'
             WHEN  DADOS.DATA BETWEEN '01/06/2020' AND '30/06/2021' THEN '2021'
             WHEN  DADOS.DATA BETWEEN '01/07/2021' AND '30/06/2022' THEN '2122'
             WHEN  DADOS.DATA BETWEEN '01/07/2022' AND '30/06/2023' THEN '2223' 
			WHEN  DADOS.DATA BETWEEN '01/07/2023' AND '30/06/2024' THEN '2324'
			WHEN  DADOS.DATA BETWEEN '01/07/2024' AND '30/06/2025' THEN '2425'      
            WHEN  DADOS.DATA BETWEEN '01/07/2025' AND '30/06/2026' THEN '2526' 
            WHEN  DADOS.DATA BETWEEN '01/07/2026' AND '30/06/2027' THEN '2627' 
            WHEN  DADOS.DATA BETWEEN '01/07/2027' AND '30/06/2028' THEN '2728' 
            WHEN  DADOS.DATA BETWEEN '01/07/2028' AND '30/06/2029' THEN '2829' 
            
             END OSSAFRA,

       --DADOS.DESC_RTV,
       --DADOS.ESTABFUNC,
       --DADOS.MATFUNC,
       DADOS.DATA,
       SUM(DADOS.VLRLIQMENSAL)VLR_BRTMENSAL,
       SUM(DADOS.VLRCOMMENSAL)VLR_COMMENSAL,
        COALESCE(SUM(DADOS.VLRCOMAPU),0)VLR_COMAPU,
        SUM(DADOS.VLRLIQMENSAL)*1.6 VLR_ENCARGOS,
        0 VLR_COMPF,
        'S' RECCOM

FROM(

SELECT 
CASE WHEN REPRESENT = 9886 THEN '9884#'|| CAST(EMPRESA AS VARCHAR (100))ELSE
CAST(REPRESENT AS VARCHAR (100))||'#'|| CAST(EMPRESA AS VARCHAR (100)) END OSRTV,
 EMPRESA,
 CASE WHEN REPRESENT = 9886 THEN 9884 ELSE REPRESENT END AS COD_RTV,
 CASE WHEN REPRESENT = 9886 THEN 'DOUGLAS ALBERTO PAULO SOARES' ELSE DESCRICAO END DESC_RTV,
 CONTAMOVFUNCIONARIO.LOCALTRABALHO ESTABFUNC,
 --CONTAMOV.MATFUNCIONARIO AS MATFUNC,
 179 MATFUNC,
 VIASOFTRH.RHCALCBASE.DATA,
 --VIASOFTRH.RHCALCBASE.PROVENTOS,
 VIASOFTRH.RHCALCBASE.PROVENTOS -
  
  COALESCE((SELECT SUM(VALOR)
   FROM VIASOFTRH.RHCALCULO
   WHERE ESTAB = VIASOFTRH.RHCALCBASE.ESTAB
     AND IDEMPREGADO = VIASOFTRH.RHCALCBASE.IDEMPREGADO
     AND DATA = VIASOFTRH.RHCALCBASE.DATA
     AND IDPROCESSO = VIASOFTRH.RHCALCBASE.IDPROCESSO
     AND IDEVENTO IN (121, 
                      2001,
                      2032)),0) AS VLRLIQMENSAL,
 COALESCE((SELECT SUM(VALOR)
   FROM VIASOFTRH.RHCALCULO
   WHERE ESTAB = VIASOFTRH.RHCALCBASE.ESTAB
     AND IDEMPREGADO = VIASOFTRH.RHCALCBASE.IDEMPREGADO
     AND DATA = VIASOFTRH.RHCALCBASE.DATA
     AND IDPROCESSO = VIASOFTRH.RHCALCBASE.IDPROCESSO
     AND IDEVENTO IN (121,
                      2001,
                      2032)),0) AS VLRCOMMENSAL,
                      VLRCOMAPU
                      
     
          
FROM PREPRESE
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM=PREPRESE.REPRESENT

INNER JOIN CONTAMOVFUNCIONARIO ON CONTAMOVFUNCIONARIO.NUMEROCM=CONTAMOV.NUMEROCM

INNER JOIN VIASOFTRH.RHEMPREGADO ON VIASOFTRH.RHEMPREGADO.FORNECEDORFIN = CONTAMOV.NUMEROCM
                                   
INNER JOIN VIASOFTRH.RHCALCBASE ON VIASOFTRH.RHCALCBASE.ESTAB = VIASOFTRH.RHEMPREGADO.ESTAB
AND VIASOFTRH.RHCALCBASE.IDEMPREGADO = VIASOFTRH.RHEMPREGADO.IDEMPREGADO
AND VIASOFTRH.RHCALCBASE.IDPROCESSO = 1 

LEFT JOIN (SELECT COMISACDOC.NUMEROCM,COMISAC.PREVISAOPAGTO,SUM(COMISACDOC.COMISVALOR)VLRCOMAPU FROM COMISAC
INNER JOIN COMISACDOC ON COMISACDOC.ESTAB=COMISAC.ESTAB
                  AND COMISACDOC.SEQACERTO=COMISAC.SEQACERTO
                  
 GROUP BY COMISACDOC.NUMEROCM,COMISAC.PREVISAOPAGTO ) COMISAP
 ON EXTRACT(YEAR FROM VIASOFTRH.RHCALCBASE.DATA) = EXTRACT(YEAR FROM COMISAP.PREVISAOPAGTO)
 AND   EXTRACT(MONTH FROM VIASOFTRH.RHCALCBASE.DATA) = EXTRACT(MONTH FROM COMISAP.PREVISAOPAGTO)
 AND COMISAP.NUMEROCM = 9884

WHERE CONTAMOV.MATFUNCIONARIO IS NOT NULL 
AND VIASOFTRH.RHCALCBASE.DATA >= '01/01/2020'
AND REPRESENT IN (9884,9886) 
ORDER BY VIASOFTRH.RHCALCBASE.DATA

)DADOS

GROUP BY DADOS.OSRTV,
       DADOS.EMPRESA,
       DADOS.COD_RTV,
       --DADOS.DESC_RTV,
       DADOS.DATA
       

UNION ALL

SELECT DADOS.OSRTV,
       DADOS.EMPRESA,
       DADOS.COD_RTV,
           CASE        WHEN  DADOS.DATA BETWEEN '01/06/2019' AND '31/05/2020' THEN '1920'
             WHEN  DADOS.DATA BETWEEN '01/06/2020' AND '30/06/2021' THEN '2021'
             WHEN  DADOS.DATA BETWEEN '01/07/2021' AND '30/06/2022' THEN '2122'
             WHEN  DADOS.DATA BETWEEN '01/07/2022' AND '30/06/2023' THEN '2223' 
			WHEN  DADOS.DATA BETWEEN '01/07/2023' AND '30/06/2024' THEN '2324'
			WHEN  DADOS.DATA BETWEEN '01/07/2024' AND '30/06/2025' THEN '2425'      
            WHEN  DADOS.DATA BETWEEN '01/07/2025' AND '30/06/2026' THEN '2526' 
            WHEN  DADOS.DATA BETWEEN '01/07/2026' AND '30/06/2027' THEN '2627' 
            WHEN  DADOS.DATA BETWEEN '01/07/2027' AND '30/06/2028' THEN '2728' 
            WHEN  DADOS.DATA BETWEEN '01/07/2028' AND '30/06/2029' THEN '2829' 
            
             END OSSAFRA,

       --DADOS.DESC_RTV,
       --DADOS.ESTABFUNC,
       --DADOS.MATFUNC,
       DADOS.DATA,
       SUM(DADOS.VLRLIQMENSAL)VLR_BRTMENSAL,
       SUM(DADOS.VLRCOMMENSAL)VLR_COMMENSAL,
        COALESCE(SUM(DADOS.VLRCOMAPU),0)VLR_COMAPU,
       SUM(DADOS.VLRLIQMENSAL)*1.6 VLR_ENCARGOS,
        0 VLR_COMPF,
        CASE WHEN DADOS.COD_RTV IN (2179,7648,9270) THEN 'N' ELSE 'S' END RECCOM

FROM(
SELECT 
CASE WHEN REPRESENT = 9886 THEN '9884#'|| CAST(EMPRESA AS VARCHAR (100))ELSE
CAST(REPRESENT AS VARCHAR (100))||'#'|| CAST(EMPRESA AS VARCHAR (100)) END OSRTV,
 EMPRESA,
 CASE WHEN REPRESENT = 9886 THEN 9884 ELSE REPRESENT END AS COD_RTV,
 CASE WHEN REPRESENT = 9886 THEN 'DOUGLAS ALBERTO PAULO SOARES' ELSE DESCRICAO END DESC_RTV,
 CONTAMOVFUNCIONARIO.LOCALTRABALHO ESTABFUNC,
 --CONTAMOV.MATFUNCIONARIO AS MATFUNC,
 179 MATFUNC,
 VIASOFTRH.RHCALCBASE.DATA,
 --VIASOFTRH.RHCALCBASE.PROVENTOS,
 VIASOFTRH.RHCALCBASE.PROVENTOS -
  
  COALESCE((SELECT SUM(VALOR)
   FROM VIASOFTRH.RHCALCULO
   WHERE ESTAB = VIASOFTRH.RHCALCBASE.ESTAB
     AND IDEMPREGADO = VIASOFTRH.RHCALCBASE.IDEMPREGADO
     AND DATA = VIASOFTRH.RHCALCBASE.DATA
     AND IDPROCESSO = VIASOFTRH.RHCALCBASE.IDPROCESSO
     AND IDEVENTO IN (121, 
                      2001,
                      2032)),0) AS VLRLIQMENSAL,

 COALESCE((SELECT SUM(VALOR)
   FROM VIASOFTRH.RHCALCULO
   WHERE ESTAB = VIASOFTRH.RHCALCBASE.ESTAB
     AND IDEMPREGADO = VIASOFTRH.RHCALCBASE.IDEMPREGADO
     AND DATA = VIASOFTRH.RHCALCBASE.DATA
     AND IDPROCESSO = VIASOFTRH.RHCALCBASE.IDPROCESSO
     AND IDEVENTO IN (121,
                      2001,
                      2032)),0) AS VLRCOMMENSAL  ,
                      
                      VLRCOMAPU
FROM PREPRESE
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM=PREPRESE.REPRESENT

INNER JOIN CONTAMOVFUNCIONARIO ON CONTAMOVFUNCIONARIO.NUMEROCM=CONTAMOV.NUMEROCM

INNER JOIN VIASOFTRH.RHPESSOA ON RHPESSOA.CPF=CONTAMOV.CNPJF

INNER JOIN VIASOFTRH.RHEMPREGADO ON VIASOFTRH.RHEMPREGADO.IDPESS =  VIASOFTRH.RHPESSOA.IDPESS
                                     

INNER JOIN VIASOFTRH.RHCALCBASE ON VIASOFTRH.RHCALCBASE.ESTAB = VIASOFTRH.RHEMPREGADO.ESTAB
AND VIASOFTRH.RHCALCBASE.IDEMPREGADO = VIASOFTRH.RHEMPREGADO.IDEMPREGADO
AND VIASOFTRH.RHCALCBASE.IDPROCESSO = 1 

LEFT JOIN (SELECT COMISACDOC.NUMEROCM,COMISAC.PREVISAOPAGTO,SUM(COMISACDOC.COMISVALOR)VLRCOMAPU FROM COMISAC
INNER JOIN COMISACDOC ON COMISACDOC.ESTAB=COMISAC.ESTAB
                  AND COMISACDOC.SEQACERTO=COMISAC.SEQACERTO
                  
 GROUP BY COMISACDOC.NUMEROCM,COMISAC.PREVISAOPAGTO ) COMISAP
 ON EXTRACT(YEAR FROM VIASOFTRH.RHCALCBASE.DATA) = EXTRACT(YEAR FROM COMISAP.PREVISAOPAGTO)
 AND   EXTRACT(MONTH FROM VIASOFTRH.RHCALCBASE.DATA) = EXTRACT(MONTH FROM COMISAP.PREVISAOPAGTO)
 AND COMISAP.NUMEROCM = REPRESENT

WHERE 
--CONTAMOV.MATFUNCIONARIO IS NOT NULL 
 VIASOFTRH.RHCALCBASE.DATA >= '01/01/2020'
AND REPRESENT NOT IN (9884,9886) 
ORDER BY VIASOFTRH.RHCALCBASE.DATA)DADOS

GROUP BY DADOS.OSRTV,
       DADOS.EMPRESA,
       DADOS.COD_RTV,
       --DADOS.DESC_RTV,
       DADOS.DATA
  