WITH NOTAS_DEVOL AS (
    SELECT
      NFITEMAPARTIRDE.ESTABORIGEM,
      NFITEMAPARTIRDE.SEQNOTAORIGEM,
      NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        SUM(NFITEM_DESTI.QUANTIDADE) AS QTD
    FROM NFITEMAPARTIRDE
    
    INNER JOIN NFITEM NFITEM_DESTI
        ON NFITEM_DESTI.ESTAB = NFITEMAPARTIRDE.ESTAB
        AND NFITEM_DESTI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
        AND NFITEM_DESTI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
        
    INNER JOIN NFCAB
        ON NFCAB.ESTAB = NFITEM_DESTI.ESTAB
        AND NFCAB.SEQNOTA = NFITEM_DESTI.SEQNOTA
        
    INNER JOIN NFCFG
        ON NFCFG.NOTACONF = NFCAB.NOTACONF
        
     LEFT JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP ON u_tipoop.u_tipoop_id = nfcfg_u.u_tipoop_id 
    
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    
    WHERE COALESCE(NFCAB.STATUS,'-') <> 'C'
    and u_tipoop.tipoop in ('DF-C')

      GROUP BY
     NFITEMAPARTIRDE.ESTABORIGEM,
      NFITEMAPARTIRDE.SEQNOTAORIGEM,
      NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
),

NOTAS_BX AS (
    SELECT
      NFITEMAPARTIRDE.ESTABORIGEM,
      NFITEMAPARTIRDE.SEQNOTAORIGEM,
      NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        SUM(NFITEM_DESTI.QUANTIDADE) AS QTD
    FROM NFITEMAPARTIRDE
    
    INNER JOIN NFITEM NFITEM_DESTI
        ON NFITEM_DESTI.ESTAB = NFITEMAPARTIRDE.ESTAB
        AND NFITEM_DESTI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
        AND NFITEM_DESTI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
        
    INNER JOIN NFCAB
        ON NFCAB.ESTAB = NFITEM_DESTI.ESTAB
        AND NFCAB.SEQNOTA = NFITEM_DESTI.SEQNOTA
        
    INNER JOIN NFCFG
        ON NFCFG.NOTACONF = NFCAB.NOTACONF
        
    INNER JOIN NATOPERACAO
        ON NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
        
     LEFT JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP ON u_tipoop.u_tipoop_id = nfcfg_u.u_tipoop_id 
    
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    
    WHERE COALESCE(NFCAB.STATUS,'-') <> 'C'
    and u_tipoop.tipoop in ('EF')

      GROUP BY
     NFITEMAPARTIRDE.ESTABORIGEM,
      NFITEMAPARTIRDE.SEQNOTAORIGEM,
      NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
),

PEDIDOS AS (
    SELECT
    P.ESTABNOTA,
    P.SEQNOTA,
    P.SEQNOTAITEM,
    MIN(P.SERIE || '-' || P.NUMERO) AS PED
    FROM PEDITEMNFITEM P
    WHERE P.SERIE = 'PC'
    GROUP BY
        P.ESTABNOTA,
        P.SEQNOTA,
        P.SEQNOTAITEM
    
),

NOTAS AS (
    SELECT
    NFCAB.ESTAB as OSESTAB,
    NFCAB.SEQNOTA,
    NFITEM.SEQNOTAITEM,
    NFCAB.NUMEROCM,
    NFCAB.DTEMISSAO,
    NFCAB.PRAZOPAGTO AS DTPAGTO,
    NFITEM.ITEM as OSPRODUTO,
    PED AS OSPEDIDO,
    NFCAB.NUMEROCM||'#'||coalesce(NFCAB.SEQENDERECO,0) as OSPESSOA,
    NFITEM.QUANTIDADE  as QUANTIDADE,
    COALESCE(NOTAS_BX.QTD,0) AS QTDBAIXADO,
    NFITEM.QUANTIDADE  - COALESCE(NOTAS_BX.QTD,0) - COALESCE(NOTAS_DEVOL.QTD,0) AS SALDO
    FROM NFCAB
    
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
        
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID
    
    LEFT JOIN NOTAS_BX ON
        NFITEM.ESTAB = NOTAS_BX.ESTABORIGEM
        AND NFITEM.SEQNOTA = NOTAS_BX.SEQNOTAORIGEM
        AND NFITEM.SEQNOTAITEM = NOTAS_BX.SEQNOTAITEMORIGEM
        
    LEFT JOIN NOTAS_DEVOL ON
        NFITEM.ESTAB = NOTAS_DEVOL.ESTABORIGEM
        AND NFITEM.SEQNOTA = NOTAS_DEVOL.SEQNOTAORIGEM
        AND NFITEM.SEQNOTAITEM = NOTAS_DEVOL.SEQNOTAITEMORIGEM
        
    LEFT JOIN PEDIDOS ON
        NFITEM.ESTAB = PEDIDOS.ESTABNOTA
        AND NFITEM.SEQNOTA = PEDIDOS.SEQNOTA
        AND NFITEM.SEQNOTAITEM = PEDIDOS.SEQNOTAITEM
    
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = NFCAB.ESTAB
    
    WHERE
    COALESCE(NFCAB.STATUS,'X') <> 'C'
    AND U_TIPOOP.TIPOOP IN ('CF')
    AND U_TEMPRESA.INSUMOS = 'S' --AND EXVENDA = 'S'
    AND (NFITEM.QUANTIDADE  - COALESCE(NOTAS_BX.QTD,0) - COALESCE(NOTAS_DEVOL.QTD,0)) > 0
)

SELECT
*
FROM NOTAS
