WITH BASE AS (
    SELECT /*+
        LEADING(M NFCAB U_TEMPRESA NFCFG NATO NFITEM)
        INDEX(M)                    -- Forçar uso de índice em ESTAB+ITEM+CODIGOSALDO
        USE_NL(NFCAB)               -- NL pois M já vem filtrado (poucos registros)
        INDEX(NFCAB)                -- Índice em NFCAB por ESTAB+SEQNOTA
        USE_HASH(U_TEMPRESA)
        USE_HASH(NFCFG)
        USE_HASH(NATO)
        USE_HASH(NFITEM)
        NO_MERGE                    -- Preservar materialização do CTE
    */
    M.ESTAB,
    M.ITEM,
    M.DOC,
    M.SEQ,
    NFCAB.IDCTB,
    NFITEM.SEQNOTAITEM,
    NFCFG.ENTRADASAIDA,
    NATO.NATUREZADAOPERACAO,
    NATO.TIPODCTO,
    M.DATAMOVIM,
    M.HORAMOVIM,
    NFITEM.VALORTOTAL,
    ARREDONDAR(NFITEM.CUSTOCMV*M.QUANTIDADE,2) AS CUSTO_NOTA,
    M.QUANTIDADE,
    SUM(CASE
        WHEN M.SOMADIMINUI = 'D' THEN M.QUANTIDADE *-1 ELSE M.QUANTIDADE
    END)
    OVER (
        PARTITION BY M.ESTAB, M.ITEM
        ORDER BY M.ESTAB,M.ITEM,M.DATAMOVIM,
        TO_DATE(
                SUBSTR(M.HORAMOVIM,1,6) ||
                LPAD(
                    LEAST(
                        TO_NUMBER(SUBSTR(M.HORAMOVIM,7,2)),
                        59
                    ),
                    2,
                    '0'
                ),
                'HH24:MI:SS'
            )
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )  AS SALDO_QTD
    FROM MOVITEMAGRO M
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = M.ESTAB
        AND NFCAB.SEQNOTA = M.SEQ
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = M.ESTAB
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NATO ON 
        NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
        AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
        AND NFITEM.ITEM = M.ITEM
        AND NFITEM.QUANTIDADE = M.QUANTIDADE
        
    WHERE
    M.CODIGOSALDO = 5
    AND U_TEMPRESA.OUTROS = 'N'
    --AND M.ESTAB = 19
    --AND M.ITEM IN (66476) 
   -- AND IDCTB = '7341783'
),
DEVOL AS (
    SELECT
    *
    FROM BASE
    WHERE
    BASE.SALDO_QTD = 0 AND BASE.TIPODCTO = 'D' AND BASE.DATAMOVIM >= :DTBASE --AND BASE.DIF <> 0
),
DEVOL_SOMA AS (
    SELECT
        ESTAB,
        DOC,
        IDCTB,
        SEQ,
        DATAMOVIM,
        TIPODCTO,
        ENTRADASAIDA,
        NATUREZADAOPERACAO,
        SUM(QUANTIDADE) AS QUANTIDADE,
        SUM(VALORTOTAL) AS VALORTOTAL,
        SUM(CUSTO_NOTA) AS CUSTO_NOTA
    FROM BASE
    WHERE EXISTS (
        SELECT 1 FROM DEVOL
        WHERE DEVOL.ESTAB = BASE.ESTAB
        AND DEVOL.DOC = BASE.DOC
        AND DEVOL.IDCTB = BASE.IDCTB
    )
    --AND IDCTB = '7341783'
    GROUP BY ESTAB,DOC,IDCTB,SEQ,DATAMOVIM,TIPODCTO,ENTRADASAIDA,NATUREZADAOPERACAO
),
CTB AS (
    SELECT
    LANCOCAB.IDORIGEM,
    SUM(CASE 
        WHEN (LANCON.CENCUSCRED IS NOT NULL AND LANCON.DEBITO = 0) THEN LANCON.VALOR
        ELSE LANCON.VALOR * -1
    END) VLRCTB
    FROM VIASOFTCTB.LANCOCAB LANCOCAB
    INNER JOIN VIASOFTCTB.LANCON LANCON ON
        LANCON.ESTAB = LANCOCAB.ESTAB
        AND LANCON.LANCTO = LANCOCAB.LANCTO
    WHERE EXISTS (SELECT 1 FROM DEVOL WHERE DEVOL.IDCTB = LANCOCAB.IDORIGEM)
    AND(
        (LANCON.CENCUSCRED IS NOT NULL AND LANCON.DEBITO = 0)
        OR
        (LANCON.DEBITO <> 0 AND LANCON.CREDITO <> 0)
    )
    GROUP BY LANCOCAB.IDORIGEM
),
IMP AS (
    SELECT /*+ USE_NL(N DEVOL) INDEX(N IDX_FK_NFCAB_NFITEMIMPOSTO) */
        N.ESTAB,
        N.SEQNOTA,
        --N.SEQNOTAITEM,
        NVL(SUM(VALORIMPOSTO),0) AS VALORIMPOSTO,
        NVL(SUM(VALORDESONERACAO),0) AS VALORDESONERACAO,
        NVL(SUM(N.VALORTRIBISENTAS), 0) AS VALORTRIBISENTAS
    FROM NFITEMIMPOSTO N
    INNER JOIN DEVOL ON
        DEVOL.ESTAB = N.ESTAB
        AND DEVOL.SEQ = N.SEQNOTA
    GROUP BY N.ESTAB,N.SEQNOTA--,N.SEQNOTAITEM
),
DADOS AS (
    SELECT
        DEVOL_SOMA.ESTAB,
        DEVOL_SOMA.DOC,
        DEVOL_SOMA.SEQ,
        DEVOL_SOMA.IDCTB,
        DEVOL_SOMA.DATAMOVIM,
        --DEVOL_SOMA.HORAMOVIM,
        DEVOL_SOMA.ENTRADASAIDA,
        DEVOL_SOMA.NATUREZADAOPERACAO,
        DEVOL_SOMA.TIPODCTO,
        DEVOL_SOMA.QUANTIDADE,
        DEVOL_SOMA.CUSTO_NOTA,
        DEVOL_SOMA.VALORTOTAL,
        IMP.VALORTRIBISENTAS,
        (DEVOL_SOMA.VALORTOTAL) - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0) - NVL(IMP.VALORTRIBISENTAS,0) AS VALORTOTAL_LIQ,
        (DEVOL_SOMA.CUSTO_NOTA) - (DEVOL_SOMA.VALORTOTAL - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0)) as DIF
    FROM DEVOL_SOMA 
    LEFT JOIN IMP ON
        IMP.ESTAB = DEVOL_SOMA.ESTAB
        AND IMP.SEQNOTA = DEVOL_SOMA.SEQ
    --WHERE
    --(DEVOL_SOMA.CUSTO_NOTA - (DEVOL_SOMA.VALORTOTAL - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0))) <> 0
)
SELECT 
D.ESTAB,
--D.ITEM,
D.DOC,
D.SEQ,
D.IDCTB,
TO_CHAR(D.DATAMOVIM,'DD/MM/YYYY') AS DATAMOVIM,
D.VALORTOTAL,
D.CUSTO_NOTA,
ARREDONDAR(CASE
    WHEN D.ENTRADASAIDA = 'E' AND D.TIPODCTO <> 'D' THEN PCUSTO(D.ESTAB, NFITEM.ITEM, 2, D.DATAMOVIM, NULL, NULL)
    WHEN D.TIPODCTO = 'D' AND D.NATUREZADAOPERACAO = 'DC' THEN PCUSTO(D.ESTAB, NFITEM.ITEM, 2, NFI.DTEMISSAO, NULL, NULL)
    ELSE PCUSTO(D.ESTAB, NFITEM.ITEM, 3, D.DATAMOVIM, NULL, NULL)
END,2) AS CUSTO_MEDIO,
DEVOL.QUANTIDADE AS QTD_DC,
D.DIF,
--
D.VALORTOTAL_LIQ,
CTB.VLRCTB AS VLRCTB_LIQ ,
CTB.VLRCTB - VALORTRIBISENTAS - D.CUSTO_NOTA AS DIF_LIQ,
DEVOL.ITEM
FROM DADOS D

LEFT JOIN CTB ON CTB.IDORIGEM = D.IDCTB

INNER JOIN DEVOL ON
    DEVOL.ESTAB = D.ESTAB
    AND DEVOL.SEQ = D.SEQ
    AND DEVOL.DOC = D.DOC
    AND DEVOL.IDCTB = D.IDCTB
    
INNER JOIN NFITEM ON
    NFITEM.ESTAB = D.ESTAB
    AND NFITEM.SEQNOTA = D.SEQ
    AND NFITEM.ITEM = DEVOL.ITEM
    
LEFT JOIN NFITEMAPARTIRDE PARTIRDE ON
    PARTIRDE.ESTABORIGEM = NFITEM.ESTABORIGEM
    AND PARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTAORIGEM
    AND PARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEMORIGEM
    AND PARTIRDE.ESTAB = NFITEM.ESTAB
    AND PARTIRDE.SEQNOTA = NFITEM.SEQNOTA
    AND PARTIRDE.SEQNOTAITEM = NFITEM.SEQNOTAITEM

LEFT JOIN NFITEM NFI ON
    NFI.ESTAB = PARTIRDE.ESTABORIGEM
    AND NFI.SEQNOTA = PARTIRDE.SEQNOTAORIGEM
    AND NFI.SEQNOTAITEM = PARTIRDE.SEQNOTAITEMORIGEM
    AND NFI.ITEM = DEVOL.ITEM
    
    WHERE
CTB.VLRCTB - NVL(VALORTRIBISENTAS,0) - D.CUSTO_NOTA <> 0