SELECT
DADOS1.ESTAB,
DADOS1.NM_ITEM,
DADOS1.ITEM,
SUM(DADOS1.SALDOAENTSC)SALDOAENTKG,
SUM(DADOS1.SALDOAENTVLR)SALDOAENTVLR,
arredondar( DIVIDE(SUM(DADOS1.SALDOAENTVLR), SUM(DADOS1.SALDOAENTSC)) ,2) as CUSTOUNITMED_MEDIA,
--arredondar(SUM(DADOS1.SALDOAENTVLR)/SUM(DADOS1.SALDOAENTSC),2) as CUSTOUNITMED_MEDIA,
SUM(DADOS1.CONTABIL)ESTOQUE_CONTABIL,
SUM(DADOS1.CUSTO_CONTABIL)CUSTO_CONTABIL



FROM(

SELECT DADOS.ESTAB,
        DADOS.NM_ITEM,
        DADOS.ITEM,
       SUM(ARREDONDAR((DADOS.SALDOAENT),2))SALDOAENTSC,
       SUM(ARREDONDAR((DADOS.SALDOAENT),2)*(DADOS.VALORUNITARIO))SALDOAENTVLR,
       0 contabil,
       0 CUSTO_CONTABIL
        
FROM(

SELECT NFCAB.ESTAB,
        
      NFCAB.ESTAB||'-'||PEMPRESA.NOME AS NM_EMPRESA,

NFCAB.SEQNOTA, NFCAB.NUMEROCM,       
       NFCAB.NOTA, NFCAB.SERIE,
       
     NFCAB.NUMEROCM ||'-'|| CONTAMOV.NOME AS NM_PESSOA,
       
  NFCAB.NOTA ||'-'||NFCAB.SERIE AS DOCTO,
       
      NFCAB.DTEMISSAO, 
       NFCAB.NOTACONF, NFCFG.DESCRICAO, ITEMAGRO.GRUPO,
       NFITEM.ITEM,
      NFITEM.ITEM||'-'||ITEMAGRO.DESCRICAO AS NM_ITEM,
                                                          
      
       NFCAB.NUMEROCM AS CD_PESSOA, CONTAMOV.NOME AS NOME_PESSOA, 
       NFITEM.ITEM AS CD_ITEM, ITEMAGRO.DESCRICAO AS NOME_ITEM,
          ARREDONDAR(NFITEM.QUANTIDADE, NFCFG.CASASDECQTD) AS QUANTIDADE,
          nfitem.valorunitario,
       ARREDONDAR(NFITEM.VALORTOTAL - ((NFCAB.VALORPRODBRUTO - NFCAB.VALORPROD) * DIVIDE(NFITEM.VALORTOTAL, NFCAB.VALORPRODBRUTO )), 4) AS VALORTOTAL,
       ARREDONDAR(NVLF0((SELECT SUM(NFITEMAPARTIRDE.QUANTIDADE)               
             FROM NFITEMAPARTIRDE
             INNER JOIN NFCAB NFCAB_D
              ON  (NFITEMAPARTIRDE.ESTAB = NFCAB_D.ESTAB)
              AND (NFITEMAPARTIRDE.SEQNOTA = NFCAB_D.SEQNOTA)
             WHERE (NFITEMAPARTIRDE.ESTABORIGEM = NFITEM.ESTAB)
               AND (NFITEMAPARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA)
               AND (NFITEMAPARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
                  AND NFCAB_D.DTEMISSAO BETWEEN '01/01/2000' AND :DTFIM
              )), NFCFG.CASASDECQTD) AS QDTENTREGUE,
              
                ARREDONDAR(NFITEM.QUANTIDADE, NFCFG.CASASDECQTD) -  ARREDONDAR(NVLF0((SELECT SUM(NFITEMAPARTIRDE.QUANTIDADE)               
             FROM NFITEMAPARTIRDE
             INNER JOIN NFCAB NFCAB_D
              ON  (NFITEMAPARTIRDE.ESTAB = NFCAB_D.ESTAB)
              AND (NFITEMAPARTIRDE.SEQNOTA = NFCAB_D.SEQNOTA)
             WHERE (NFITEMAPARTIRDE.ESTABORIGEM = NFITEM.ESTAB)
               AND (NFITEMAPARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA)
               AND (NFITEMAPARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
                AND NFCAB_D.DTEMISSAO BETWEEN '01/01/2000' AND :DTFIM
              )), NFCFG.CASASDECQTD) SALDOAENT
FROM NFITEM
  INNER JOIN NFCAB
    ON (NFCAB.ESTAB = NFITEM.ESTAB)
   AND (NFCAB.SEQNOTA = NFITEM.SEQNOTA)
   
  INNER JOIN CONFAGROE
    ON (CONFAGROE.ESTAB = NFCAB.ESTAB) 
  INNER JOIN CONTAMOV
    ON (CONTAMOV.NUMEROCM = NFCAB.NUMEROCM)
  INNER JOIN NFCFG
    ON (NFCFG.NOTACONF = NFCAB.NOTACONF)
  INNER JOIN ITEMAGRO
    ON (ITEMAGRO.ITEM = NFITEM.ITEM)
  INNER JOIN PEMPRESA
    ON (PEMPRESA.EMPRESA = NFCAB.ESTAB)
WHERE 
  NFCAB.DTENTSAI BETWEEN '01/01/2000' AND :DTFIM
     
<#if ESTAB?has_content>
    AND  NFCAB.ESTAB IN (:ESTAB)
</#if>
 
  <#if ITEM?has_content>
 and ITEMAGRO.ITEM IN (:ITEM)
</#if>

      
and NFCAB.NOTACONF in (200,201,234,334,414,1038))DADOS


GROUP BY

DADOS.ESTAB,
DADOS.NM_ITEM,
DADOS.ITEM

UNION ALL

SELECT
FILIAL.ESTAB,
ITEMAGRO.ITEM||'-'||ITEMAGRO.DESCRICAO AS NM_ITEM,
itemagro.item,
0 SALDOAENTSC,
0 SALDOAENTVLR,
saldoitem(ITEMAGROESTAB.estab, ITEMAGROESTAB.item, 5,1,9999,:DTFIM,null,null,null,null,null)contabil,
PCUSTO(ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM,3, :DTFIM,NULL) AS CUSTO_CONTABIL

FROM ITEMAGROESTAB

INNER JOIN FILIAL ON FILIAL.ESTAB = ITEMAGROESTAB.ESTAB

INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

inner JOIN ITEMAGRO ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM


WHERE 
0=0
and U_TEMPRESA.GRAOS = 'S'
and itemagro.item <=50
  AND saldoitem(ITEMAGROESTAB.estab, ITEMAGROESTAB.item, 5,1,9999, :DTFIM ,null,null,null,null,null) <> 0
   <#if ESTAB?has_content>
    AND FILIAL.ESTAB IN (:ESTAB)
     </#if>
 
  <#if ITEM?has_content>
   and ITEMAGRO.ITEM IN (:ITEM)
  </#if>


  
 )DADOS1


HAVING SUM(DADOS1.SALDOAENTSC) >0

GROUP BY
DADOS1.ESTAB,
DADOS1.NM_ITEM,
DADOS1.ITEM