WITH PESSOAS AS (
    select distinct * from (
    SELECT
    NUMEROCM,
    CNPJF
    FROM VIASOFT.CONTAMOV
    UNION 
    SELECT
    NUMEROCM,
    CNPJF
    FROM VIASOFT.ENDERECO )dados
),
EMP AS (
    SELECT
    ESTAB,
    CASE
        WHEN OUTROS = 'S' THEN 'OUTROS'
        WHEN INSUMOS = 'S' THEN 'INSUMOS'
        WHEN GRAOS = 'S' THEN 'CEREAIS'
        ELSE 'OUTROS'
    END SEGMENTO,
    CASE
        WHEN OUTROS = 'S' THEN 'O'
        WHEN INSUMOS = 'S' THEN 'I'
        WHEN GRAOS = 'S' THEN 'C'
        ELSE 'O'
    END TPESTAB
    FROM VIASOFT.U_TEMPRESA 
),
NOTAS AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.SERIE,
    NFCAB.NOTA,
    NFCAB.NUMEROCM,
    NFCAB.PRAZOPAGTO,
    NFCAB.VALOR,
    NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) AS CNPJF,
    NVL(ENDERECO.CREDENCIALAGRO,CONTAMOV.INSCESTAD) AS INSCESTAD,
    MAX(P.DUPREC) AS DPL,
  MAX(P.DTVENCTO) VENCTO,
    MIN(PANALITI.ANALITICA) AS ANALITICA,
    MIN(PANALITI.DESCRICAO) AS DESC_ANALITICA,
    MAX(CASE WHEN REN.DUPREC IS NOT NULL THEN 1 ELSE 0 END) AS RENEG
    FROM VIASOFT.NFCAB NFCAB
    
    LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    
    LEFT JOIN VIASOFT.ENDERECO ENDERECO ON
        ENDERECO.NUMEROCM = NFCAB.NUMEROCM
        AND ENDERECO.SEQENDERECO = NFCAB.SEQENDERECO
    
    LEFT JOIN VIASOFT.CONTAMOV CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
    
    INNER JOIN VIASOFT.NFCFG NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.ENTRADASAIDA = 'S'
            
    LEFT JOIN VIASOFT.NFCABAGRFIN F ON
        F.ESTAB = NFCAB.ESTAB
        AND F.SEQNOTA = NFCAB.SEQNOTA
    
    LEFT JOIN VIASOFT.AGRFINDUPREC A ON
        A.ESTAB = F.ESTAB
        AND A.SEQPAGAMENTO = F.SEQPAGAMENTO
    
    LEFT JOIN VIASOFT.PDUPREC P ON
        P.EMPRESA = A.ESTAB
        AND P.DUPREC = A.DUPREC
        
    LEFT JOIN VIASOFT.PANALITI PANALITI ON
        PANALITI.EMPRESA = FILIAL.EMPRESA
        AND PANALITI.ANALITICA = P.ANALITICA
        
    LEFT JOIN VIASOFT.RENEGOCIACAODOCTOS REN ON
        REN.ESTAB = P.EMPRESA
        AND REN.DUPREC = P.DUPREC
        AND REN.PESSOA = P.CLIENTE
        
    GROUP BY
    NFCAB.ESTAB,NFCAB.SERIE,NFCAB.NOTA,NFCAB.NUMEROCM,NFCAB.PRAZOPAGTO,
    NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF),
    NVL(ENDERECO.CREDENCIALAGRO,CONTAMOV.INSCESTAD),NFCAB.VALOR
)
SELECT 
    FILIAL.REDUZIDO AS FILIAL,
    EMP.SEGMENTO,
    FMERCS.DESCRICAO as ITEM,
    NOTAS.NUMEROCM  AS CODCLIENTE,
   -- PESSOAS.NUMEROCM as CODCLIENTE,
    --NFCAB.NUMEROCM AS CODCLIENTE,
    NVL(FPESSOAS.NOME,P1.NOME) AS CLIENTE,
    NVL(FPESSOAS.CNPJF,P1.CNPJF) AS CNPJF,
    NVL(FPESSOAS.ENDERECO,P1.ENDERECO) AS ENDERECO,
    CID.UF AS UF_CLIENTE,
    NOTAS.NUMEROCM  AS CLIENTE_DPL,
    NOTAS.DPL,
    NVL(NOTAS.VENCTO,NOTAS.PRAZOPAGTO) AS DTPRAZO,
    NOTAS.VALOR AS VLRDPL,
    NOTAS.ANALITICA,
    NOTAS.DESC_ANALITICA,
    CASE WHEN NOTAS.RENEG = 1 THEN 'S' ELSE 'N' END RENEGIC,
    FSAIITEM.IDOPER AS CFOP,
    FSAIDA.NUMDOC AS NOTA,
    FSAIDA.NUMDOC AS FATURA,
    FSAIDA.EMISSAO,
    SUM(FSAIITEM.VALCONT) AS VALOR,
    NOTAS.PRAZOPAGTO,
    CIDADE.UF,
    FSAIITEM.CFGCTAS||'-'||PLACONAN.DESCRICAO AS CTB
       
FROM FSAIDA

LEFT JOIN FPESSOAS ON
    FPESSOAS.ESTAB = FSAIDA.ESTAB
    AND FPESSOAS.IDPESS = FSAIDA.IDPESS

LEFT JOIN FPESSOAS P1 ON
    P1.IDPESS = FSAIDA.IDPESS
    AND P1.ESTAB = 1

LEFT JOIN VIASOFT.CIDADE CID ON CID.CIDADE = NVL(FPESSOAS.CIDADE,P1.CIDADE)  
--LEFT JOIN PESSOAS ON PESSOAS.CNPJF = NVL(FPESSOAS.CNPJF,P1.CNPJF)

LEFT JOIN NOTAS ON
    NOTAS.ESTAB = FSAIDA.ESTAB
    AND NOTAS.NOTA = FSAIDA.NUMDOC
    AND NOTAS.SERIE = FSAIDA.SERIE
    AND NOTAS.CNPJF = NVL(FPESSOAS.CNPJF,P1.CNPJF)
    AND NVL(NOTAS.INSCESTAD,'0') = COALESCE(FPESSOAS.INSCEST,P1.INSCEST,'0')

INNER JOIN FSAIITEM ON 
    FSAIITEM.ESTAB = FSAIDA.ESTAB
    AND FSAIITEM.SEQDOC = FSAIDA.SEQDOC
                    
LEFT JOIN FMERCS ON 
    FMERCS.IDMERC = FSAIITEM.IDMERC
    AND FMERCS.estab=FSAIDA.ESTAB
                           
LEFT JOIN FSAISERV ON 
    FSAIDA.ESTAB = FSAISERV.ESTAB
    AND FSAIDA.SEQDOC = FSAISERV.SEQDOC

LEFT JOIN FOPERS ON 
    FOPERS.ESTAB = FSAISERV.ESTAB
    AND FOPERS.IDOPER = FSAISERV.IDOPER

LEFT JOIN VIASOFT.ITEMAGRO ITEMAGRO ON ITEMAGRO.ITEM = FSAIITEM.IDMERC
LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = FSAIDA.ESTAB
LEFT JOIN EMP ON EMP.ESTAB = FILIAL.ESTAB
LEFT JOIN VIASOFT.CIDADE CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
LEFT JOIN VIASOFTCTB.PLACONAN PLACONAN ON
    PLACONAN.REDUZIDA = FSAIITEM.CFGCTAS
    AND PLACONAN.PLANO = 1
    
WHERE 
(0 IN (:ESTAB) OR FSAIDA.ESTAB  IN (:ESTAB))
AND FSAIDA.EMISSAO BETWEEN :DTINI AND :DTFIM
--AND NVL(FSAIDA.CANCELADO,'N') <> 'S'
AND ('T' IN (:TPESTAB) OR EMP.TPESTAB IN (:TPESTAB))


GROUP BY
FILIAL.REDUZIDO,
FSAIITEM.CFGCTAS,
PLACONAN.DESCRICAO,
    EMP.SEGMENTO,
    FMERCS.DESCRICAO,
    NOTAS.NUMEROCM,
    NVL(FPESSOAS.NOME,P1.NOME),
    NVL(FPESSOAS.CNPJF,P1.CNPJF),
    NVL(FPESSOAS.ENDERECO,P1.ENDERECO),
    CID.UF,
    NOTAS.NUMEROCM ,
    NOTAS.VENCTO,
    NOTAS.DPL,
    NOTAS.PRAZOPAGTO,
    NOTAS.ANALITICA,
    NOTAS.DESC_ANALITICA,
    FSAIITEM.IDOPER,
    FSAIDA.NUMDOC,
    FSAIDA.NUMDOC,
    FSAIDA.EMISSAO,
    NOTAS.PRAZOPAGTO,
    CIDADE.UF,
    NOTAS.RENEG,NOTAS.VALOR 
                