WITH 
ESTABORI AS 
(
SELECT DISTINCT /*+ MATERIALIZE */
ESTAB,
IDCTB
FROM
VIASOFT.CONTAMOVLAN CONTAMOVLANa
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.CONTRATO CONTRATO
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.CTRC CTRC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.NFCAB NFCAB
WHERE IDCTB IS NOT NULL AND COALESCE(NFCAB.STATUS,'X') <> 'C'

UNION ALL

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PDUPPAGA PDUPPAGA
WHERE IDCTB IS NOT NULL

/* REMOVIDO: bloco PDUPPAGA duplicado - idêntico ao anterior */

UNION ALL

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PDUPREC PDUPREC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.PDUPRECREAJ PDUPRECREAJ
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PLANCA PLANCA
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PPDUPPAG PPDUPPAG
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PRDUPREC PRDUPREC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.ROMA ROMA
WHERE IDCTB IS NOT NULL
),

ESTABORI_UNIF AS (

SELECT 
LISTAGG(DISTINCT FILIAL.ESTAB, ', ') WITHIN GROUP (ORDER BY FILIAL.ESTAB) AS ESTAB,
LISTAGG(DISTINCT FILIAL.REDUZIDO, ', ') WITHIN GROUP (ORDER BY FILIAL.ESTAB) AS FILIAL,
IDCTB AS IDORIGEM
FROM ESTABORI

LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = ESTABORI.ESTAB
GROUP BY IDCTB
),
BASE_LANC AS (
    SELECT /*+ MATERIALIZE */
        LANCOCAB.DATALANC,
        LANCOCAB.LANCTO AS LACTOCTB,
        LANCOCAB.IDORIGEM,
        LANCOCAB.USERID AS LANCOCAB_USERID,
        LANCON.COMPLEM,
        LANCON.VALOR,
        LANCON.DEBITO,
        LANCON.CREDITO,
        LANCON.CENCUSDEB,
        LANCON.CENCUSCRED,
        LANCON.SEQUENCIA,
        NFCAB.ESTAB AS NFCAB_ESTAB,
        NFCAB.SEQNOTA,
        NFCAB.NUMEROCM AS NFCAB_NUMEROCM,
        NFCAB.USERID AS NFCAB_USERID,
        NFCAB_U.NRTICKET,
        CONTAMOV.NUMEROCM,
        CONTAMOV.NOME
    FROM LANCOCAB
    LEFT JOIN LANCON ON LANCON.ESTAB = LANCOCAB.ESTAB 
        AND LANCON.LANCTO = LANCOCAB.LANCTO
    LEFT JOIN VIASOFT.NFCAB NFCAB ON NFCAB.IDCTB = LANCOCAB.IDORIGEM 
        AND COALESCE(NFCAB.STATUS,'X') <> 'C'
    LEFT JOIN VIASOFT.NFCAB_U NFCAB_U ON NFCAB_U.ESTAB = NFCAB.ESTAB 
        AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
    LEFT JOIN VIASOFT.CONTAMOV CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
    WHERE 
        LANCOCAB.ESTAB = 1
        AND LANCOCAB.DATALANC BETWEEN :DTINI AND :DTFIM
),
DEBITO_CREDITO AS (
    -- DEBITO: apenas JOINs leves (PLACONAN, CENCUSCE, PLACONSI, FILIAL, CIDADE, U_TEMPRESA)
    SELECT /*+ USE_HASH(CENCUSCE) */
        'DEBITO' AS DEBCRED,
        B.DATALANC, B.LACTOCTB, B.COMPLEM AS COMPLEMENTO,
        B.VALOR AS CONTABILDEB, 0 AS CONTABILCRED,
        B.IDORIGEM AS IDCTB,
        DEBITO.DESCRICAO,
        B.DEBITO AS CONTA,
        CENCUSCE.CENTROCUS,
        CASE WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
             ELSE FILIAL_CC.ESTAB END AS ESTAB2,
        CASE WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
             ELSE FILIAL_CC.REDUZIDO END AS FILIAL2,
        CENCUSCE.DESCRICAO AS DESC_CC,
        GRUPO7.DESCRICAO AS DESC_CONTA,
        B.NUMEROCM, B.NOME,
        COALESCE(B.NFCAB_USERID, B.LANCOCAB_USERID) AS USERID,
        B.NFCAB_ESTAB AS ESTAB_NOTA,
        B.SEQNOTA,
        CIDADE.UF AS UF,
        B.NRTICKET,
        CASE WHEN U_TEMPRESA.OUTROS = 'S' THEN 'O'
             WHEN U_TEMPRESA.INSUMOS = 'S' THEN 'I'
             WHEN U_TEMPRESA.GRAOS = 'S' THEN 'C' END TPESTAB
    FROM BASE_LANC B
    LEFT JOIN PLACONAN DEBITO ON DEBITO.PLANO = 1 AND DEBITO.REDUZIDA = B.DEBITO
    LEFT JOIN CENCUSCE ON CENCUSCE.CENTROCUS = B.CENCUSDEB AND CENCUSCE.CENCUSCOD = 2
    LEFT JOIN PLACONSI ON PLACONSI.REDSINT = DEBITO.REDSINT AND PLACONSI.PLANO = DEBITO.PLANO
    LEFT JOIN PLACONSI GRUPO7 ON SUBSTR(PLACONSI.CONTABIL, 1, 9) = GRUPO7.CONTABIL 
        AND PLACONSI.PLANO = GRUPO7.PLANO
    LEFT JOIN VIASOFT.FILIAL FILIAL_CC ON FILIAL_CC.ESTAB = TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0'))
    LEFT JOIN VIASOFT.CIDADE CIDADE ON CIDADE.CIDADE = FILIAL_CC.CIDADE
    LEFT JOIN VIASOFT.U_TEMPRESA U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL_CC.ESTAB
    WHERE 
        (0 IN (:CONTACONTABIL) OR B.DEBITO IN (:CONTACONTABIL))
        AND ('T' IN (:GRUPO) OR PLACONSI.GRUPO IN (:GRUPO))
        AND (0 IN (:ESTAB) OR FILIAL_CC.ESTAB IN (:ESTAB))
        AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
        AND B.CENCUSDEB IS NOT NULL

    UNION ALL

    -- CREDITO: mesma estrutura, colunas CREDITO
    SELECT /*+ USE_HASH(CENCUSCE) */
        'CREDITO' AS DEBCRED,
        B.DATALANC, B.LACTOCTB, B.COMPLEM AS COMPLEMENTO,
        0 AS CONTABILDEB, B.VALOR AS CONTABILCRED,
        B.IDORIGEM AS IDCTB,
        CREDITO.DESCRICAO,
        B.CREDITO AS CONTA,
        CENCUSCE.CENTROCUS,
        CASE WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
             ELSE FILIAL_CC.ESTAB END AS ESTAB2,
        CASE WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
             ELSE FILIAL_CC.REDUZIDO END AS FILIAL2,
        CENCUSCE.DESCRICAO AS DESC_CC,
        GRUPO7.DESCRICAO AS DESC_CONTA,
        B.NUMEROCM, B.NOME,
        COALESCE(B.NFCAB_USERID, B.LANCOCAB_USERID) AS USERID,
        B.NFCAB_ESTAB AS ESTAB_NOTA,
        B.SEQNOTA,
        CIDADE.UF AS UF,
        B.NRTICKET,
        CASE WHEN U_TEMPRESA.OUTROS = 'S' THEN 'O'
             WHEN U_TEMPRESA.INSUMOS = 'S' THEN 'I'
             WHEN U_TEMPRESA.GRAOS = 'S' THEN 'C' END TPESTAB
    FROM BASE_LANC B
    LEFT JOIN PLACONAN CREDITO ON CREDITO.PLANO = 1 AND CREDITO.REDUZIDA = B.CREDITO
    LEFT JOIN CENCUSCE ON CENCUSCE.CENTROCUS = B.CENCUSCRED AND CENCUSCE.CENCUSCOD = 2
    LEFT JOIN PLACONSI ON PLACONSI.REDSINT = CREDITO.REDSINT AND PLACONSI.PLANO = CREDITO.PLANO
    LEFT JOIN PLACONSI GRUPO7 ON SUBSTR(PLACONSI.CONTABIL, 1, 9) = GRUPO7.CONTABIL 
        AND PLACONSI.PLANO = GRUPO7.PLANO
    LEFT JOIN VIASOFT.FILIAL FILIAL_CC ON FILIAL_CC.ESTAB = TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0'))
    LEFT JOIN VIASOFT.CIDADE CIDADE ON CIDADE.CIDADE = FILIAL_CC.CIDADE
    LEFT JOIN VIASOFT.U_TEMPRESA U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL_CC.ESTAB
    WHERE 
        (0 IN (:CONTACONTABIL) OR B.CREDITO IN (:CONTACONTABIL))
        AND ('T' IN (:GRUPO) OR PLACONSI.GRUPO IN (:GRUPO))
        AND (0 IN (:ESTAB) OR FILIAL_CC.ESTAB IN (:ESTAB))
        AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
        AND B.CENCUSCRED IS NOT NULL
),

LANCAMENTOS AS (

    SELECT
    ESTABORI_UNIF.ESTAB,
    ESTABORI_UNIF.FILIAL,
    DEBITO_CREDITO.*
    FROM DEBITO_CREDITO
    
    LEFT JOIN ESTABORI_UNIF ON ESTABORI_UNIF.IDORIGEM = DEBITO_CREDITO.IDCTB
),

HISTORICO_CTE AS (
    SELECT /*+ NO_MERGE CARDINALITY(NFCABAGRFIN 300000) */
        NFCABAGRFIN.ESTAB,
        NFCABAGRFIN.SEQNOTA,
        COALESCE(PDUPPAGA.HISTORICO, PDUPREC.HISTORICO, CONTAMOVLAN.HISTORICO) AS HISTORICO,
        ROW_NUMBER() OVER (PARTITION BY NFCABAGRFIN.ESTAB, NFCABAGRFIN.SEQNOTA ORDER BY COALESCE(PDUPPAGA.HISTORICO, PDUPREC.HISTORICO, CONTAMOVLAN.HISTORICO)) AS RN
    FROM 
        VIASOFT.NFCABAGRFIN NFCABAGRFIN
    JOIN VIASOFT.NFCAB NFCAB ON NFCAB.ESTAB = NFCABAGRFIN.ESTAB AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA 
    LEFT JOIN VIASOFT.AGRFINDUPREC AGRFINDUPREC ON AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.PDUPREC PDUPREC ON PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB AND PDUPREC.DUPREC = AGRFINDUPREC.DUPREC
    LEFT JOIN VIASOFT.AGRFINDUPPAG AGRFINDUPPAG ON AGRFINDUPPAG.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.PDUPPAGA PDUPPAGA ON PDUPPAGA.EMPRESA = AGRFINDUPPAG.ESTAB AND PDUPPAGA.DUPPAG = AGRFINDUPPAG.DUPPAG AND PDUPPAGA.FORNECEDOR = AGRFINDUPPAG.FORNECEDOR
    LEFT JOIN VIASOFT.AGRFINCTAMOV AGRFINCTAMOV ON AGRFINCTAMOV.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.CONTAMOVLAN CONTAMOVLAN ON CONTAMOVLAN.ESTAB = AGRFINCTAMOV.ESTAB AND CONTAMOVLAN.NUMEROCM = AGRFINCTAMOV.NUMEROCM AND CONTAMOVLAN.SEQCM = AGRFINCTAMOV.SEQCM
    WHERE
        NFCAB.DTENTSAI BETWEEN :DTINI AND :DTFIM    
        AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
),

ITENS AS (
    SELECT /*+ NO_MERGE CARDINALITY(NFCAB 300000) */
        NFCAB.ESTAB,
        NFCAB.SEQNOTA,
        LISTAGG(DISTINCT U_GESTOQUE.DESCRICAO, ', ') WITHIN GROUP (ORDER BY U_GESTOQUE.DESCRICAO) AS DESCRICOES
    FROM
        VIASOFT.NFITEM NFITEM
    JOIN VIASOFT.ITEMAGRO ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    JOIN VIASOFT.ITEMGRUPO_U ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMAGRO.GRUPO
    JOIN VIASOFT.U_GESTOQUE U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
    JOIN VIASOFT.NFCAB NFCAB ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA   
    WHERE
        NFCAB.DTENTSAI BETWEEN :DTINI AND :DTFIM    
        AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
    GROUP BY 
        NFCAB.ESTAB,
        NFCAB.SEQNOTA
),

DEPARA AS (
    SELECT DISTINCT
        U_PCC.REDUZIDA AS DEPARA,
        U_PCC.CONTA AS DESC_DE_PARA,
   U_PCC.DEPARA AS CONTA_DEPARA,
        U_TIPONAT.DESCRICAO AS NATUREZA,
        U_TIPOUNIDADE.DESCRICAO AS UNIDADE
    FROM
        U_PCC
    LEFT JOIN U_TIPONAT ON U_TIPONAT.U_TIPONAT_ID = U_PCC.U_TIPONAT_ID
    LEFT JOIN U_TIPOUNIDADE ON U_TIPOUNIDADE.U_TIPOUNIDADE_ID = U_PCC.U_TIPOUNIDADE_ID
    WHERE 
        OSPLANO = '1#1'
),

DRE AS (
     SELECT
CASE 
    WHEN U_DRE.reduzida IN (31152, 31153, 31155, 31154, 31911) THEN 'Custos e Despesas Variaveis'
    ELSE REPLACE(U_DRE.DESC1, 'á', 'a')
END AS DESC1,
    case
        when U_DRE.reduzida in (31152, 31153, 31155, 31154, 31911) then 'Custo das Vendas'
        else U_DRE.DESC2
    END AS DESC2, 
    U_DRE.REDUZIDA, 
    U_DRE.TPESTAB,
    U_PCC.CONTA
    
    FROM U_DRE
    
    left join u_pcc 
    on u_dre.reduzida = u_pcc.reduzida
    and u_pcc.OSPLANO = '0#1'
)

SELECT /*+ GATHER_PLAN_STATISTICS DYNAMIC_SAMPLING(4) */
    DADOS.DEBCRED, 
    DADOS.ESTAB,
    DADOS.FILIAL,
    DADOS.UF,
    DADOS.DATALANC,
    DADOS.LACTOCTB,
    DADOS.COMPLEMENTO,
   SUM( (TO_NUMBER(DADOS.CONTABILDEB) - TO_NUMBER(DADOS.CONTABILCRED)) )AS VALOR,
    DADOS.IDCTB,
    DEPARA.DESC_DE_PARA,
    DADOS.CONTA,
    DADOS.CENTROCUS,
    DADOS.ESTAB2,
    DADOS.FILIAL2,
    DADOS.DESC_CC,
    DADOS.DESC_CONTA,
    DADOS.NUMEROCM,
    DADOS.NOME,
   'Tkt-'||NRTICKET||' '||HISTORICO.HISTORICO as HISTORICO,
    DADOS.USERID,
    ITENS.DESCRICOES AS DES_ITENS,
    DEPARA.UNIDADE,
    DEPARA.NATUREZA,
    DRE.DESC1,
    DRE.DESC2
    
FROM (
    SELECT * FROM LANCAMENTOS
) DADOS
LEFT JOIN (
    SELECT ESTAB, SEQNOTA, HISTORICO
    FROM HISTORICO_CTE
    WHERE RN = 1
) HISTORICO ON HISTORICO.ESTAB = DADOS.ESTAB_NOTA AND HISTORICO.SEQNOTA = DADOS.SEQNOTA

LEFT JOIN ITENS ON ITENS.ESTAB = DADOS.ESTAB_NOTA AND ITENS.SEQNOTA = DADOS.SEQNOTA

LEFT JOIN DEPARA ON (DEPARA.DEPARA) = (DADOS.CONTA)

LEFT JOIN DRE ON 
    (DRE.REDUZIDA) = (DEPARA.CONTA_DEPARA)
    AND DRE.TPESTAB = DADOS.TPESTAB

WHERE
    (DADOS.CONTA <> 0)
    AND ('0' IN (:SEGMENTO) OR DADOS.TPESTAB IN (:SEGMENTO))
GROUP BY 
    DADOS.DEBCRED, 
    DADOS.ESTAB,
    DADOS.FILIAL,
    DADOS.UF,
    DADOS.DATALANC,
    DADOS.LACTOCTB,
    DADOS.COMPLEMENTO,
    DADOS.IDCTB,
    DADOS.DESCRICAO,
    DADOS.CONTA,
    DADOS.CENTROCUS,
    DADOS.ESTAB2,
    DADOS.FILIAL2,
    DADOS.DESC_CC,
    DADOS.DESC_CONTA,
    DADOS.NUMEROCM,
    DADOS.NOME,
    HISTORICO.HISTORICO,
    DADOS.USERID,
    ITENS.DESCRICOES,
    DEPARA.NATUREZA,
    DEPARA.UNIDADE,
    DEPARA.DESC_DE_PARA,
    NRTICKET,
     DRE.DESC1,
    DRE.DESC2
