WITH NOTAS AS (
    SELECT NFCAB.ESTAB,
           NFCAB.SEQNOTA,
  			NFCAB.DTEMISSAO,
           NFCAB.NOTACONF,
           natoperacao.TIPODCTO,
           NFCAB.NUMEROCM,
           NFCAB.NOTA,
           nfitem.seqnotaitem,
           NFITEM.ITEM,
           NFITEM.ITEM || '-' || ITEMAGRO.DESCRICAO AS DESCITEM,
           U_GESTOQUE.DESCRICAO AS GESTOQUE,
           (COALESCE(NFITEM.quantidade, 0)) AS QUANTIDADE,
           (COALESCE(NFITEM.DESCTOTAL, 0) + COALESCE(DESCNOTA.VALORDESCONTO * DIVIDE(NFITEM.VALORTOTAL, NFCAB.VALORPRODBRUTO), 0)) AS DESCONTOVENDA,
           NFITEM.VALORTOTAL - COALESCE(DESCNOTA.VALORDESCONTO * DIVIDE(NFITEM.VALORTOTAL, NFCAB.VALORPRODBRUTO), 0) AS VALORVENDA,
           (COALESCE(NFITEM.VALORTOTAL, 0)) VALORNOTA,
           NFITEM.VALORTOTAL - COALESCE(DESCNOTA.VALORDESCONTO * DIVIDE(NFITEM.VALORTOTAL, NFCAB.VALORPRODBRUTO), 0) - COALESCE(nfitem.VLRAUXIMPDESP, 0) VALORENTRE
    FROM NFCAB
    LEFT JOIN (
        SELECT NFDESC.ESTAB,
               NFDESC.SEQNOTA,
               SUM(NFDESC.VALORDESCONTO) AS VALORDESCONTO
        FROM NFDESC
        GROUP BY NFDESC.ESTAB, NFDESC.SEQNOTA
    ) DESCNOTA
    ON NFCAB.ESTAB = DESCNOTA.ESTAB AND NFCAB.SEQNOTA = DESCNOTA.SEQNOTA
    INNER JOIN NFITEM ON NFITEM.ESTAB = NFCAB.ESTAB AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    LEFT JOIN ITEMGRUPO ON ITEMAGRO.GRUPO = ITEMGRUPO.GRUPO
    LEFT JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
    LEFT JOIN U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = itemgrupo_u.u_gestoque_id
    LEFT JOIN ITEMMARCA ON ITEMAGRO.MARCA = ITEMMARCA.MARCA
    INNER JOIN filial ON filial.estab = nfcab.estab
    inner join nfcfg on nfcfg.notaconf = nfcab.notaconf
    inner join natoperacao on natoperacao.naturezadaoperacao = nfcfg.naturezadaoperacao
    and natoperacao.entradasaida = nfcfg.entradasaida
    WHERE NFCAB.NOTACONF IN (4, 111, 112, 142,148, 404, 998, 418, 240, 329, 422, 5, 6, 75, 83, 242, 405, 419, 241, 423,228,143,130,155,157/*,156*/,345)
      AND (NFCAB.ESTAB IN (:ESTAB) OR 0 IN (:ESTAB))
      AND filial.empresa = 1
      AND NFCAB.STATUS <> 'C'
      AND NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
      order by nfcab.estab, nfcab.dtemissao
),
IMP AS (
  SELECT
  N.ESTAB,
  N.SEQNOTA,
  N.SEQNOTAITEM,
  SUM(N.VALORTRIBISENTAS) AS VALORTRIBISENTAS
  FROM NFITEMIMPOSTO N
  INNER JOIN NOTAS ON
    NOTAS.ESTAB = N.ESTAB
    AND NOTAS.SEQNOTA = N.SEQNOTA
  GROUP BY N.ESTAB, N.SEQNOTA, N.SEQNOTAITEM
),
ITENS AS (
    SELECT ITEMAGROESTAB.estab,
           ITEMAGROESTAB.ITEM,
           ITEMAGROESTAB.ITEM || '-' || ITEMAGRO.DESCRICAO AS DESCITEM,
           U_GESTOQUE.DESCRICAO AS GESTOQUE,
           ARREDONDAR(PCUSTO(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 3, :DTFIM, NULL), 2) CUSTOCMV,
           SALDOITEM(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 5, 1, 99999, :DTFIM, NULL, NULL, NULL) AS SALDO_CTB
    FROM ITEMAGROESTAB
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM
    LEFT JOIN ITEMGRUPO ON ITEMAGRO.GRUPO = ITEMGRUPO.GRUPO
    LEFT JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
    LEFT JOIN U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = itemgrupo_u.u_gestoque_id
    LEFT JOIN ITEMMARCA ON ITEMAGRO.MARCA = ITEMMARCA.MARCA
    WHERE ITEMAGROESTAB.ITEM < 50
      AND (ITEMAGROESTAB.ESTAB IN (:ESTAB) OR 0 IN (:ESTAB))
      AND EXISTS (
          SELECT 1
          FROM NOTAS
          WHERE notas.estab = itemagroestab.estab
            AND notas.item = itemagroestab.item
      )
)
SELECT dados.*,
       GREATEST(DADOS.QTDNOTA - DADOS.QTDENTRE, 0) AS Qtd_Entregar,
       GREATEST(DADOS.VALORVENDA - DADOS.VALORENTRE) AS VALOR_A_ENTREGAR,
       CASE 
           WHEN ARREDONDAR((DADOS.VALORVENDA - (DADOS.VALORENTRE * -1)), 2) < 0 THEN 0
           ELSE ARREDONDAR((DADOS.VALORVENDA - (DADOS.VALORENTRE * -1)), 2)
       END AS VLRAENTREGAR,
       NULL AS CUSTOCMV,
       NULL AS saldo_ctb
FROM (
    SELECT NOTAS.ESTAB,
           NOTAS.SEQNOTA,
           NOTAS.NOTACONF,
           notas.NUMEROCM,
           notas.NOTA,
           notas.seqnotaitem,
           notas.ITEM,
           notas.DESCITEM,
           notas.GESTOQUE,
           CASE WHEN NOTACONF IN (4, 111, 112, 142, 143,404, 998, 418, 240, 329, 422,130,345) THEN QUANTIDADE ELSE 0 END QTDNOTA,
           CASE WHEN NOTACONF IN (5, 6, 75, 83, 242, 405, 419, 241, 423,148,228,157,156,155) THEN QUANTIDADE ELSE 0 END QTDENTRE,
           DESCONTOVENDA,
           CASE 
                WHEN NOTACONF IN (4, 111, 112, 142, 143,404, 998, 418, 240, 329, 422,130,345) AND TIPODCTO <> 'D' THEN VALORVENDA  
                WHEN NOTACONF IN (4, 111, 112, 142, 143,404, 998, 418, 240, 329, 422,130,345) AND TIPODCTO = 'D' THEN VALORVENDA - NVL(IMP.VALORTRIBISENTAS,0)
                ELSE 0 END VALORVENDA,
           CASE 
                WHEN NOTACONF IN (4, 111, 112, 142, 143,404, 998, 418, 240, 329, 422,130,345) AND TIPODCTO <> 'D'THEN VALORVENDA  
                WHEN NOTACONF IN (4, 111, 112, 142, 143,404, 998, 418, 240, 329, 422,130,345) AND TIPODCTO = 'D'THEN VALORVENDA - NVL(IMP.VALORTRIBISENTAS,0)
                ELSE 0 END VALORNOTA,
           CASE 
                WHEN NOTACONF IN (5, 6, 75, 83, 242, 405, 419, 241, 423,148,228,157,156,155) THEN VALORENTRE
                ELSE 0 END VALORENTRE,
            CASE 
                WHEN NOTACONF IN (5, 6, 75, 83,148, 242, 405, 419, 241, 423,228,157,156,155)  AND DTEMISSAO <= :DATA_CORTE THEN VALORENTRE
                ELSE 0 END VALORENTRE_BX
    FROM NOTAS
    LEFT JOIN IMP ON 
      IMP.ESTAB = NOTAS.ESTAB
      AND IMP.SEQNOTA = NOTAS.SEQNOTA
      AND IMP.SEQNOTAITEM = NOTAS.SEQNOTAITEM
      
) dados

UNION ALL

SELECT ESTAB,
       NULL SEQNOTA,
       NULL NOTACONF,
       NULL NUMEROCM,
       NULL NOTA,
       NULL seqnotaitem,
       ITEM,
       DESCITEM,
       GESTOQUE,
       NULL QTDNOTA,
       NULL QTDENTRE,
       NULL DESCONTOVENDA,
       NULL VALORVENDA,
       NULL VALORNOTA,
       NULL VALORENTRE,
       NULL VALORENTRE_BX,
       NULL AS VLRAENTREGAR,
       NULL AS Qtd_Entregar,
       NULL AS VALOR_A_ENTREGAR,
       CUSTOCMV,
       SALDO_CTB
FROM ITENS
