WITH
  -- 0) Lista de pedidos por NF (usando LISTAGG) e materializada
  PedidosPorNF AS (
    SELECT /*+ MATERIALIZE */
      NF.ESTAB AS ESTAB_NF,
      NF.SEQNOTA AS SEQNOTA_NF,
      LISTAGG(
        DISTINCT (PI.SERIE || '-' || TO_CHAR(PI.NUMERO)),
        ', '
      ) WITHIN GROUP (ORDER BY PI.SERIE, PI.NUMERO) AS PEDIDOS
    FROM NFCAB NF
    JOIN NFITEM NI
      ON NI.ESTAB = NF.ESTAB
      AND NI.SEQNOTA = NF.SEQNOTA
    JOIN PEDITEMNFITEM PI
      ON PI.ESTABNOTA = NI.ESTAB
      AND PI.SEQNOTA = NI.SEQNOTA
      AND PI.SEQNOTAITEM = NI.SEQNOTAITEM
    GROUP BY
      NF.ESTAB,
      NF.SEQNOTA
  ),
  -- 1) Base de PDUPPAGA já filtrada (reduz o volume)
  PD_Base AS (
    SELECT
      PD.EMPRESA,
      PD.DUPPAG,
      PD.FORNECEDOR,
      PD.DTVENCTO,
      PD.DTEMISSAO,
      PD.NRODOCTOORIGEM,
      PD.HISTORICO,
      PD.VALOR AS VLRDUP
    FROM PDUPPAGA PD
    WHERE (PD.DEPOSITAR IS NULL OR PD.DEPOSITAR = 'N')
      AND PD.QUITADA = 'N'
      AND PD.SITUACAO NOT IN (55)
  ),
  -- 2) Grupo do usuário logado
  UsuarioGrupo AS (
    SELECT IDGRPAPROVADORES
    FROM GRUPOUSUARIO
    WHERE USERID = :usuario_logado
  ),
  -- 3) Regras do grupo de aprovação
  RegrasDoGrupo AS (
    SELECT EG.IDREGRA
    FROM ESTRATEGIAGRUPO EG
    JOIN UsuarioGrupo UG
      ON UG.IDGRPAPROVADORES = EG.IDGRPAPROVADORES
  ),
  -- 4) Regras com faixa de valor e estabelecimento
  RegrasComFiltro AS (
    SELECT
      R.IDREGRA,
      R.VLRINICIAL AS VALORMINIMO,
      R.VLRFINAL AS VALORMAXIMO,
      R.IDESTAB AS ESTAB
    FROM ESTRATEGIAREGRA R
    JOIN ESTRATEGIAPEDIDO EP
      ON R.IDESTRATEGIA = EP.IDESTRATEGIA
      AND EP.IDESTRATEGIA IN (427, 431, 433) -- REGRA DA APROVACAO DE ORCAMENTO
    JOIN RegrasDoGrupo RG
      ON RG.IDREGRA = R.IDREGRA
  ),
  -- 5) Centros de custo válidos permitidos para a regra
  CentrosValidos AS (
    SELECT
      EC.IDREGRA,
      EC.CENTROCUS AS CENTROCUSTO
    FROM ESTRATEGIACENCUSTO EC
    JOIN RegrasDoGrupo RG
      ON RG.IDREGRA = EC.IDREGRA
  ),
  -- 6) Notas pendentes
  NotasPendentes AS (
    SELECT
      CAST(0 AS INTEGER) AS APROVAR,
      CAST(0 AS INTEGER) AS CANCELAR,
      NF.DTEMISSAO,
      PDB.HISTORICO AS OBS_PEDIDO,
      CM.NOME AS PESSOANOME,
      NF.CENCUSCOD,
      NF.CENTROCUS,
      (NF.CENTROCUS || ' - ' || CC.DESCRICAO) AS CENTROCUS_COMPLETO,
      NF.NOTA,
      NF.NUMEROCM AS FORNECEDOR,
      NF.ESTAB,
      FL.REDUZIDO,
      PDB.DUPPAG,
      PDB.DTVENCTO,
      PDB.VLRDUP AS VLRAUTPAGAR,
      NVL(PNF.PEDIDOS, '') AS PEDIDOS,
      RF.IDREGRA
    FROM PD_Base PDB
    JOIN AGRFINDUPPAG AF
      ON PDB.EMPRESA = AF.ESTAB
      AND PDB.DUPPAG = AF.DUPPAG
    JOIN NFCABAGRFIN NA
      ON AF.SEQPAGAMENTO = NA.SEQPAGAMENTO
      AND AF.ESTAB = NA.ESTAB
      AND AF.FORNECEDOR = PDB.FORNECEDOR
    JOIN NFCAB NF
      ON NF.ESTAB = NA.ESTAB
      AND NF.SEQNOTA = NA.SEQNOTA
    JOIN FILIAL FL
      ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM
      ON CM.NUMEROCM = NF.NUMEROCM
    -- Join com CENCUSCE para obter a descrição do centro de custo
    INNER JOIN CENCUSCE CC
      ON CC.CENCUSCOD = NF.CENCUSCOD
      AND CC.CENTROCUS = NF.CENTROCUS
    LEFT JOIN PedidosPorNF PNF
      ON PNF.ESTAB_NF = NF.ESTAB
      AND PNF.SEQNOTA_NF = NF.SEQNOTA
    -- Primeiro valida o estabelecimento e valor
    INNER JOIN RegrasComFiltro RF
      ON RF.ESTAB = NF.ESTAB
      AND NF.VALOR BETWEEN RF.VALORMINIMO AND RF.VALORMAXIMO
    -- Depois valida se o centro de custo está permitido na regra
    INNER JOIN CentrosValidos CV
      ON CV.IDREGRA = RF.IDREGRA
      AND NF.CENTROCUS = CV.CENTROCUSTO
  ),
  -- 7) Notas pendentes (via movimento)
  NotasPendentesMov AS (
    SELECT
      CAST(0 AS INTEGER) AS APROVAR,
      CAST(0 AS INTEGER) AS CANCELAR,
      NF.DTEMISSAO,
      PDB.HISTORICO AS OBS_PEDIDO,
      CM.NOME AS PESSOANOME,
      NF.CENCUSCOD,
      NF.CENTROCUS,
      (NF.CENTROCUS || ' - ' || CC.DESCRICAO) AS CENTROCUS_COMPLETO,
      NF.NOTA,
      NF.NUMEROCM AS FORNECEDOR,
      NF.ESTAB,
      FL.REDUZIDO,
      PDB.DUPPAG,
      PDB.DTVENCTO,
      PDB.VLRDUP AS VLRAUTPAGAR,
      NVL(PNF.PEDIDOS, '') AS PEDIDOS,
      RF.IDREGRA
    FROM PD_Base PDB
    JOIN CONTAMOVLAN CML
      ON CML.ESTAB = PDB.EMPRESA
      AND CML.NUMEROCM = PDB.FORNECEDOR
      AND CML.DTMOVTO = PDB.DTEMISSAO
      AND PDB.NRODOCTOORIGEM = TO_CHAR(CML.ESTAB || CML.NUMEROCM || CML.SEQCM)
    JOIN AGRFINCTAMOV AFM
      ON AFM.ESTAB = CML.ESTAB
      AND AFM.SEQCM = CML.SEQCM
      AND AFM.NUMEROCM = CML.NUMEROCM
    JOIN NFCABAGRFIN NAF
      ON NAF.ESTAB = AFM.ESTAB
      AND NAF.SEQPAGAMENTO = AFM.SEQPAGAMENTO
    JOIN NFCAB NF
      ON NF.ESTAB = NAF.ESTAB
      AND NF.SEQNOTA = NAF.SEQNOTA
      AND NF.NUMEROCM = AFM.NUMEROCM
    JOIN FILIAL FL
      ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM
      ON CM.NUMEROCM = NF.NUMEROCM
    -- Join com CENCUSCE para obter a descrição do centro de custo
    INNER JOIN CENCUSCE CC
      ON CC.CENCUSCOD = NF.CENCUSCOD
      AND CC.CENTROCUS = NF.CENTROCUS
    LEFT JOIN PedidosPorNF PNF
      ON PNF.ESTAB_NF = NF.ESTAB
      AND PNF.SEQNOTA_NF = NF.SEQNOTA
    -- Primeiro valida o estabelecimento e valor
    INNER JOIN RegrasComFiltro RF
      ON RF.ESTAB = NF.ESTAB
      AND NF.VALOR BETWEEN RF.VALORMINIMO AND RF.VALORMAXIMO
    -- Depois valida se o centro de custo está permitido na regra
    INNER JOIN CentrosValidos CV
      ON CV.IDREGRA = RF.IDREGRA
      AND NF.CENTROCUS = CV.CENTROCUSTO
  ),
    -- 8) CTRC (via movimento)
  CtrcMov AS (
    SELECT
      CAST(0 AS INTEGER) AS APROVAR,
      CAST(0 AS INTEGER) AS CANCELAR,
      CT.DTEMISSAO,
      PDB.HISTORICO AS OBS_PEDIDO,
      CM.NOME AS PESSOANOME,
      CT.CENCUSCOD,
      CT.CENTROCUS,
      (CT.CENTROCUS || ' - ' || CC.DESCRICAO) AS CENTROCUS_COMPLETO,
      CT.NROCTRC AS NOTA,
      CT.PRESTADOR AS FORNECEDOR,
      CT.ESTAB,
      FL.REDUZIDO,
      PDB.DUPPAG,
      PDB.DTVENCTO,
      PDB.VLRDUP AS VLRAUTPAGAR,
      '' AS PEDIDOS,
      RF.IDREGRA
    FROM PD_Base PDB
   JOIN AGRFINDUPPAG AF
      ON PDB.EMPRESA = AF.ESTAB
      AND PDB.DUPPAG = AF.DUPPAG
   JOIN AGRFINCTRC CTRF
    ON CTRF.SEQPAGAMENTO = AF.SEQPAGAMENTO
    AND CTRF.ESTAB = AF.ESTAB
    AND CTRF.PRESTADOR = PDB.FORNECEDOR
     JOIN CTRC CT
      ON CT.ESTAB = CTRF.ESTAB
      AND CT.SEQCTRC = CTRF.SEQCTRC
      AND CT.PRESTADOR = CTRF.PRESTADOR    
    JOIN FILIAL FL
      ON FL.ESTAB = CT.ESTAB
    JOIN CONTAMOV CM
      ON CM.NUMEROCM = CT.FORNECEDOR
    -- Join com CENCUSCE para obter a descrição do centro de custo
    INNER JOIN CENCUSCE CC
      ON CC.CENCUSCOD = CT.CENCUSCOD
      AND CC.CENTROCUS = CT.CENTROCUS
      -- Primeiro valida o estabelecimento e valor
    INNER JOIN RegrasComFiltro RF
      ON RF.ESTAB = CT.ESTAB
      AND CT.TOTAL BETWEEN RF.VALORMINIMO AND RF.VALORMAXIMO
    -- Depois valida se o centro de custo está permitido na regra
    INNER JOIN CentrosValidos CV
      ON CV.IDREGRA = RF.IDREGRA
      AND CT.CENTROCUS = CV.CENTROCUSTO
)      
-- 9) Resultado final com formatação igual à consulta 1
SELECT
  APROVAR,
  CANCELAR,
  ESTAB,
  ESTAB || '-' || REDUZIDO AS FILIAL,
  DTEMISSAO,
  PEDIDOS AS PEDIDO,
  NOTA,
  PESSOANOME || '-' || FORNECEDOR AS FORNECEDOR,
  CENTROCUS_COMPLETO AS CENTROCUS,
  DUPPAG,
  DTVENCTO AS DTVALIDADE,
  VLRAUTPAGAR,
  OBS_PEDIDO AS OBS
FROM NotasPendentes
UNION ALL
SELECT
  APROVAR,
  CANCELAR,
  ESTAB,
  ESTAB || '-' || REDUZIDO AS FILIAL,
  DTEMISSAO,
  PEDIDOS AS PEDIDO,
  NOTA,
  PESSOANOME || '-' || FORNECEDOR AS FORNECEDOR,
  CENTROCUS_COMPLETO AS CENTROCUS,
  DUPPAG,
  DTVENCTO,
  VLRAUTPAGAR,
  OBS_PEDIDO
FROM NotasPendentesMov
UNION ALL
SELECT
  APROVAR,
  CANCELAR,
  ESTAB,
  ESTAB || '-' || REDUZIDO AS FILIAL,
  DTEMISSAO,
  PEDIDOS AS PEDIDO,
  NOTA,
  PESSOANOME || '-' || FORNECEDOR AS FORNECEDOR,
  CENTROCUS_COMPLETO AS CENTROCUS,
  DUPPAG,
  DTVENCTO,
  VLRAUTPAGAR,
  OBS_PEDIDO
FROM CtrcMov