WITH UsuarioGrupo AS (
    SELECT IDGRPAPROVADORES
    FROM GRUPOUSUARIO
    WHERE USERID = :usuario_logado
),
RegrasValidas AS (
    SELECT
        R.IDREGRA,
        R.IDESTAB,
        R.VLRINICIAL,
        R.VLRFINAL,
        EC.CENTROCUS,
        EP.IDESTRATEGIA
    FROM ESTRATEGIAREGRA R
    JOIN ESTRATEGIAPEDIDO EP
        ON EP.IDESTRATEGIA = R.IDESTRATEGIA
       AND EP.IDESTRATEGIA IN (427,431,433,2)
    JOIN ESTRATEGIACENCUSTO EC
        ON EC.IDREGRA = R.IDREGRA
    JOIN ESTRATEGIAGRUPO EG
        ON EG.IDREGRA = R.IDREGRA
    JOIN UsuarioGrupo UG
        ON UG.IDGRPAPROVADORES = EG.IDGRPAPROVADORES
),
NF_Filtrada AS (
    SELECT /*+ MATERIALIZE */
        NF.ESTAB,
        NF.SEQNOTA,
        NF.CENTROCUS,
        NF.CENCUSCOD,
        NF.NUMEROCM,
        SUM(NFITEM.QUANTIDADE) AS QTD
    FROM NFCAB NF
    JOIN NFITEM ON
        NFITEM.ESTAB = NF.ESTAB
        AND NFITEM.SEQNOTA = NF.SEQNOTA
    JOIN RegrasValidas RV
      ON RV.IDESTAB = NF.ESTAB
     AND NF.VALOR BETWEEN RV.VLRINICIAL AND RV.VLRFINAL
     AND NF.CENTROCUS = RV.CENTROCUS
     AND RV.IDESTRATEGIA NOT IN (2)
     GROUP BY NF.ESTAB,NF.SEQNOTA,NF.CENTROCUS,NF.CENCUSCOD,NF.NUMEROCM
),
CT_Filtrado as (
    SELECT /*+ MATERIALIZE */
    C.ESTAB,
    C.SEQCTRC,
    C.PRESTADOR,
    C.FORNECEDOR,
    C.CENTROCUS,
    C.CENCUSCOD,
    C.TOTAL
    FROM CTRC C
    JOIN RegrasValidas RV
      ON RV.IDESTAB = C.ESTAB
     AND C.TOTAL BETWEEN RV.VLRINICIAL AND RV.VLRFINAL
     AND C.CENTROCUS = RV.CENTROCUS
     AND RV.IDESTRATEGIA NOT IN (2)
),
PD_Base AS (
    SELECT /*+ MATERIALIZE */
      PD.EMPRESA,
      PD.DUPPAG,
      PD.FORNECEDOR,
      PD.DTVENCTO,
      PD.DTEMISSAO,
      PD.NRODOCTOORIGEM,
      PD.HISTORICO,
      PD.VALOR
    FROM PDUPPAGA PD
    WHERE (PD.DEPOSITAR IS NULL OR PD.DEPOSITAR = 'N')
      AND PD.QUITADA = 'N'
      AND PD.SITUACAO NOT IN (55)
),
NotasPendentes as (
    SELECT
    (PDB.VALOR) AS VLRAUTPAGAR,
    NF.QTD,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN (NF.QTD) ELSE 0 END QTD_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN (NF.QTD) ELSE 0 END QTD_ATRASADO,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_ATRASADO
    FROM PD_Base PDB
    JOIN AGRFINDUPPAG AF ON 
        PDB.EMPRESA = AF.ESTAB
        AND PDB.DUPPAG = AF.DUPPAG
    JOIN NFCABAGRFIN NA ON 
        AF.SEQPAGAMENTO = NA.SEQPAGAMENTO
        AND AF.ESTAB = NA.ESTAB
        AND AF.FORNECEDOR = PDB.FORNECEDOR
    JOIN NF_Filtrada NF ON 
        NF.ESTAB = NA.ESTAB
        AND NF.SEQNOTA = NA.SEQNOTA
    JOIN FILIAL FL ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM ON CM.NUMEROCM = NF.NUMEROCM
    INNER JOIN CENCUSCE CC ON 
        CC.CENCUSCOD = NF.CENCUSCOD
        AND CC.CENTROCUS = NF.CENTROCUS
),
NotasPendentesMov  AS (
    SELECT
    (PDB.VALOR) AS VLRAUTPAGAR,
    NF.QTD,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN (NF.QTD) ELSE 0 END QTD_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN (NF.QTD) ELSE 0 END QTD_ATRASADO,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_ATRASADO
    FROM PD_Base PDB
    JOIN CONTAMOVLAN CML ON 
        CML.ESTAB = PDB.EMPRESA
        AND CML.NUMEROCM = PDB.FORNECEDOR
        AND CML.DTMOVTO = PDB.DTEMISSAO
        AND PDB.NRODOCTOORIGEM = TO_CHAR(CML.ESTAB || CML.NUMEROCM || CML.SEQCM)
    JOIN AGRFINCTAMOV AFM ON 
        AFM.ESTAB = CML.ESTAB
        AND AFM.SEQCM = CML.SEQCM
        AND AFM.NUMEROCM = CML.NUMEROCM
    JOIN NFCABAGRFIN NAF ON 
        NAF.ESTAB = AFM.ESTAB
        AND NAF.SEQPAGAMENTO = AFM.SEQPAGAMENTO
    JOIN NF_Filtrada NF ON 
        NF.ESTAB = NAF.ESTAB
        AND NF.SEQNOTA = NAF.SEQNOTA
        AND NF.NUMEROCM = AFM.NUMEROCM
    JOIN FILIAL FL ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM ON CM.NUMEROCM = NF.NUMEROCM
    INNER JOIN CENCUSCE CC ON 
        CC.CENCUSCOD = NF.CENCUSCOD
        AND CC.CENTROCUS = NF.CENTROCUS
),
CtrcMov AS (
    SELECT
    (PDB.VALOR) AS VLRAUTPAGAR,
    1 AS QTD,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN 1 ELSE 0 END QTD_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN 1 ELSE 0 END QTD_ATRASADO,
    CASE WHEN TRUNC(PDB.DTVENCTO) = TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_HJ,
    CASE WHEN TRUNC(PDB.DTVENCTO) < TRUNC(CURRENT_DATE) THEN (PDB.VALOR) ELSE 0 END VLRAUTPAGAR_ATRASADO
    FROM PD_Base PDB
    JOIN AGRFINDUPPAG AF ON 
        PDB.EMPRESA = AF.ESTAB
        AND PDB.DUPPAG = AF.DUPPAG
    JOIN AGRFINCTRC CTRF ON 
        CTRF.SEQPAGAMENTO = AF.SEQPAGAMENTO
        AND CTRF.ESTAB = AF.ESTAB
        AND CTRF.PRESTADOR = PDB.FORNECEDOR
    JOIN CT_Filtrado CT ON 
        CT.ESTAB = CTRF.ESTAB
        AND CT.SEQCTRC = CTRF.SEQCTRC
        AND CT.PRESTADOR = CTRF.PRESTADOR
    JOIN FILIAL FL ON FL.ESTAB = CT.ESTAB
    JOIN CONTAMOV CM ON CM.NUMEROCM = CT.FORNECEDOR
    INNER JOIN CENCUSCE CC ON 
        CC.CENCUSCOD = CT.CENCUSCOD
        AND CC.CENTROCUS = CT.CENTROCUS
),
PedidoPendente AS (
    SELECT 
    PC.ESTAB,
    PC.SERIE,
    PC.NUMERO,
    PC.PESSOA,
    PC.DTPRAZOPAGTO,
    PC.CENCUSCOD,
    PC.CENTROCUS,
    PEDITEM.VALOR - NVL(PEDITEM.DESCONTO,0) AS VALORMERCADORIA,
    PEDITEM.QUANTIDADE,
    NE.IDNOTIFICA,
    PEDCFG.IDESTRATEGIA,
    PC.PEDIDOCONF
    FROM PEDCAB PC
    INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PC.PEDIDOCONF
    INNER JOIN NOTIFICAESTRATEGIA NE ON 
        NE.ESTAB  = PC.ESTAB
        AND NE.SERIE  = PC.SERIE
        AND NE.NUMERO = PC.NUMERO
    JOIN RegrasValidas RV ON 
        RV.IDESTAB = PC.ESTAB
        AND PC.VALORMERCADORIA BETWEEN RV.VLRINICIAL AND RV.VLRFINAL
        AND PC.CENTROCUS = RV.CENTROCUS
        AND RV.IDREGRA = NE.IDREGRA
        AND PEDCFG.IDESTRATEGIA = RV.IDESTRATEGIA
    INNER JOIN PEDITEM ON
        PEDITEM.ESTAB = PC.ESTAB
        AND PEDITEM.SERIE = PC.SERIE
        AND PEDITEM.NUMERO = PC.NUMERO
    WHERE PC.STATUS = 'N'
    AND PEDCFG.CTRLESTRATEGIA = 1
    AND PEDCFG.IDESTRATEGIA IN (427, 431, 433,2)
    AND NE.PENDENTEAPROV = 1
),
UltimasNotificacoes AS (
    SELECT
    NE.ESTAB,
    NE.NUMERO,
    NE.SERIE,
    NE.IDNOTIFICA,
    NE.IDREGRA,
    NE.USERID
    FROM NOTIFICAESTRATEGIA NE
    INNER JOIN (
        SELECT
        ESTAB,
        NUMERO,
        SERIE,
        MAX(IDNOTIFICA) AS IDNOTIFICA
        FROM NOTIFICAESTRATEGIA
        GROUP BY
        ESTAB,
        NUMERO,
        SERIE
    ) MaxNotif ON 
    NE.ESTAB      = MaxNotif.ESTAB
    AND NE.NUMERO     = MaxNotif.NUMERO
    AND NE.SERIE      = MaxNotif.SERIE
    AND NE.IDNOTIFICA = MaxNotif.IDNOTIFICA
    WHERE NE.PENDENTEAPROV = 1
)
SELECT
SUM(VLRAUTPAGAR) AS VLRAUTPAGAR,
SUM(VLRAUTPAGAR_HJ) AS VLRAUTPAGAR_HJ,
SUM(VLRAUTPAGAR_ATRASADO) AS VLRAUTPAGAR_ATRASADO,
SUM(QTD) AS QTD,
SUM(QTD_HJ) AS QTD_HJ,
SUM(QTD_ATRASADO) AS QTD_ATRASADO
FROM(
SELECT 
PP.VALORMERCADORIA AS VLRAUTPAGAR,
PP.QUANTIDADE AS QTD,
CASE WHEN TRUNC(PP.DTPRAZOPAGTO) = TRUNC(CURRENT_DATE) THEN (PP.QUANTIDADE) ELSE 0 END QTD_HJ,
CASE WHEN TRUNC(PP.DTPRAZOPAGTO) < TRUNC(CURRENT_DATE) THEN (PP.QUANTIDADE) ELSE 0 END QTD_ATRASADO,
CASE WHEN TRUNC(PP.DTPRAZOPAGTO) = TRUNC(CURRENT_DATE) THEN (PP.VALORMERCADORIA) ELSE 0 END VLRAUTPAGAR_HJ,
CASE WHEN TRUNC(PP.DTPRAZOPAGTO) < TRUNC(CURRENT_DATE) THEN (PP.VALORMERCADORIA) ELSE 0 END VLRAUTPAGAR_ATRASADO
FROM PedidoPendente PP
INNER JOIN UltimasNotificacoes UN ON 
    UN.ESTAB      = PP.ESTAB
    AND UN.NUMERO     = PP.NUMERO
    AND UN.SERIE      = PP.SERIE
    AND UN.IDNOTIFICA = PP.IDNOTIFICA
WHERE
(
IDESTRATEGIA IN (427, 431, 433)
OR
(IDESTRATEGIA IN (431,2) AND PEDIDOCONF = 301)
)
UNION ALL
 
SELECT
*
FROM NOTASPENDENTES
 
UNION ALL
 
SELECT
*
FROM NOTASPENDENTESMOV
 
UNION ALL
 
SELECT
*
FROM CTRCMOV
)DADOS