WITH REMESSA_CF AS (
    SELECT
    ESTAB,
    SEQNOTA,
    NOTA,
    ESTABORIGEM,
    SEQNOTAORIGEM,
    SUM(COFINS) AS COFINS,
    SUM(PIS) AS PIS
    FROM 
    (
        SELECT
        -- ESTAB E SEQNOTA SÃO DAS NOTAS DE ORIGEM DA REMESSA DE COMPRA
        NFITEMAPARTIRDE.ESTAB,
        NFITEMAPARTIRDE.SEQNOTA,
        NF_APARTIR.NOTA,
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        ((CASE WHEN NFITEMIMPOSTO.IMPOSTO = 5 THEN NFITEMIMPOSTO.ALIQUOTA ELSE 0 END)) COFINS,
        ((CASE WHEN NFITEMIMPOSTO.IMPOSTO = 4 THEN NFITEMIMPOSTO.ALIQUOTA ELSE 0 END)) PIS
        FROM
        NFCAB
        LEFT JOIN NFITEM ON NFITEM.ESTAB = NFCAB.ESTAB AND 
                            NFITEM.SEQNOTA = NFCAB.SEQNOTA 
        --- NOTA DE ORIGEM                    
        LEFT JOIN NFITEMAPARTIRDE ON  NFITEMAPARTIRDE.ESTABORIGEM = NFITEM.ESTAB AND
                                      NFITEMAPARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA AND
                                      NFITEMAPARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM 
        -- NOTA DE DESTINO
        LEFT JOIN NFITEMIMPOSTO ON NFITEMAPARTIRDE.ESTAB = NFITEMIMPOSTO.ESTAB AND
                                   NFITEMAPARTIRDE.SEQNOTA = NFITEMIMPOSTO.SEQNOTA AND
                                   NFITEMAPARTIRDE.SEQNOTAITEM = NFITEMIMPOSTO.SEQNOTAITEM  
                                   
        -- NOTA DE DESTINO
        LEFT JOIN NFCAB NF_APARTIR ON NF_APARTIR.ESTAB = NFITEMAPARTIRDE.ESTAB AND 
                                      NF_APARTIR.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
                                      
        INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NF_APARTIR.NOTACONF 
        INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID
        
        WHERE
        U_TIPOOP.U_TIPOOP_ID IN (57,63) AND
        NFCAB.DTEMISSAO BETWEEN (:DTINI) AND (:DTFIM)
        
        GROUP BY 
        NFITEMAPARTIRDE.ESTAB,
        NFITEMAPARTIRDE.SEQNOTA,
        NFITEMIMPOSTO.IMPOSTO,
        NFITEMIMPOSTO.ALIQUOTA,
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        NF_APARTIR.NOTA
    )
    GROUP BY 
    ESTAB,
    SEQNOTA,
    SEQNOTAORIGEM,
    ESTABORIGEM,
    NOTA
),
NOTAS AS (
    SELECT 
    REMESSA_CF.ESTAB,
    
    ROW_NUMBER() 
        OVER (
            PARTITION BY REMESSA_CF.ESTAB,PEDCAB.NUMERO,PEDCAB.PESSOA,PEDITEM.ITEM
            ORDER BY  REMESSA_CF.ESTAB,PEDCAB.NUMERO,PEDCAB.PESSOA,PEDITEM.ITEM
            ) RN,
    CONTRATONFITE.CONTRATO,
    PEDCAB.PESSOA,
    PEDCAB.NUMERO AS PEDIDO,
    PEDITEM.ITEM,
    REMESSA_CF.NOTA,
    REMESSA_CF.PIS,
    REMESSA_CF.COFINS
    FROM CONTRATONFITE
    
    INNER JOIN REMESSA_CF ON
        REMESSA_CF.ESTABORIGEM = CONTRATONFITE.ESTABNOTA
        AND REMESSA_CF.SEQNOTAORIGEM = CONTRATONFITE.SEQNOTA
    
    INNER JOIN U_LOGPEDCTR ON 
        CONTRATONFITE.ESTAB = U_LOGPEDCTR.ESTAB 
        AND CONTRATONFITE.CONTRATO = U_LOGPEDCTR.CONTRATO
    
    INNER JOIN PEDCAB ON 
        PEDCAB.ESTAB = U_LOGPEDCTR.ESTAB 
        AND PEDCAB.SERIE = U_LOGPEDCTR.SERIE_PED 
        AND PEDCAB.NUMERO = U_LOGPEDCTR.PEDIDO
    
    INNER JOIN PEDITEM ON 
        PEDITEM.ESTAB = U_LOGPEDCTR.ESTAB 
        AND PEDITEM.SERIE = U_LOGPEDCTR.SERIE_PED 
        AND PEDITEM.NUMERO = U_LOGPEDCTR.PEDIDO  
    
    WHERE
    PEDCAB.DTEMISSAO BETWEEN (:DTINI) AND ADD_MONTHS(:DTFIM, 1)
    AND CONTRATONFITE.QUANTIDADE > 0
)

SELECT DISTINCT
ESTAB, 
CASE WHEN RN = 1 THEN CONTRATO ELSE NULL END CONTRATO, 
PESSOA, 
PEDIDO, 
ITEM, 
NOTA, 
PIS, 
COFINS
FROM NOTAS
ORDER BY ESTAB,PEDIDO,PESSOA,ITEM