WITH MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        LOCAL,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO
    WHERE
    codigosaldo in (1,2,4,6,23,27)
    AND (TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) <= CURRENT_DATE
    -- 2,4,6,23,27: fisico
    -- 1: disponivel
  GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO,LOCAL
),
BASE AS (
    SELECT
    ITEMSALDO.CODIGOSALDO,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    ITEMAGROESTAB.ESTAB,
    ITEMSALDO.LOCAL,
    (ITEMSALDO.SALDOQUANTIDADE) as SALDO
    FROM ITEMAGROESTAB
    
    LEFT JOIN ITEMSALDO ON 
        ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM 
        AND ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ITEMSALDO.ITEM 
        AND MD.ESTAB = ITEMSALDO.ESTAB 
        AND MD.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND MD.LOCAL = ITEMSALDO.LOCAL
        AND TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    LEFT JOIN FILIAL ON FILIAL.ESTAB = ITEMAGROESTAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN ITEMAGRO  ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM 
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID=ITEMAGRO_U.U_AGRPRODGR_ID

    WHERE
    ITEMSALDO.CODIGOSALDO in (1,2,4,6,23,27)
    and U_AGRPRODGR.U_AGRPRODGR_ID <=50
    and U_TEMPRESA.GRAOS='S'
    AND U_AGRPRODGR.U_AGRPRODGR_ID = $P{ITEM}
    and (FILIAL.ESTAB = $P{ESTAB} or 0=  $P{ESTAB}) and FILIAL.ESTAB <> 800
    AND CIDADE.UF = $P{UF}   
),
DISPONIVEL AS (
    SELECT
    ESTAB,
    ITEM,
    LOCAL,
    SUM(SALDODISP)SALDODISP
    FROM(
        SELECT 
        ESTAB,
        U_AGRPRODGR_ID AS ITEM,
        LOCAL,
        QUANTIDADE*-1 SALDODISP
        FROM U_AJLOCALEST
        WHERE DATAMOV >= CURRENT_DATE
        UNION ALL
        SELECT
        ESTAB,
        ITEM,
        LOCAL,
        SALDO AS SALDODISP
        FROM BASE
        WHERE
        CODIGOSALDO = 1
    )DADOS
    GROUP BY ESTAB,ITEM,LOCAL
),
FISICO AS (
    SELECT
    ESTAB,
    ITEM,
    LOCAL,
    SUM(SALDOFIS)SALDOFIS
    FROM(
        SELECT 
        ESTAB,
        U_AGRPRODGR_ID AS ITEM,
        LOCAL,
        QUANTIDADE*-1 SALDOFIS
        FROM U_AJLOCALEST
        WHERE DATAMOV >= CURRENT_DATE
        UNION ALL
        SELECT
        ESTAB,
        ITEM,
        LOCAL,
        SALDO AS SALDOFIS
        FROM BASE
        WHERE
        CODIGOSALDO NOT IN (1,14,30,11)
    )DADOS
    GROUP BY ESTAB,ITEM,LOCAL
),
ROMA_ABERTO AS (
    SELECT
    FILIAL.ESTAB,
    U_AGRPRODGR.U_AGRPRODGR_ID as ITEM,
    LOCALEST.LOCAL,
    ITEMAGRO.DESCRICAO AS PRODUTO,
    ROMA.NUMEROCM,
    ROMACFG.ENTRADASAIDA,
    ROMA.ROMANEIO,
    ROMA.PESOLIQUIDO
    FROM ROMA
    
    INNER JOIN FILIAL ON FILIAL.ESTAB    = ROMA.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB=FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN ROMACFG ON
    ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
    ROMACFG.ENTRADASAIDA    IN ('E','S')

    INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB         = ROMA.ESTAB AND
    ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
    ROMACLASS.PERCENTUAL    > 0

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL THEN ROMA.ITEM ELSE ROMACLASS.ITEM END

    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM

    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID=ITEMAGRO_U.U_AGRPRODGR_ID

    INNER JOIN LOCALEST ON
    LOCALEST.ESTAB      = ROMA.ESTAB AND
    LOCALEST.LOCAL      = ROMA.LOCAL
    
    WHERE
    NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
        WHERE NFCABROMA.ESTAB         = ROMACLASS.ESTAB
          AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
          AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
          AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM
    )
    AND ROMA.ESTORNADO            = 'N'
    AND U_TEMPRESA.GRAOS='S'
    AND U_AGRPRODGR.U_AGRPRODGR_ID = $P{ITEM}
    AND (FILIAL.ESTAB = $P{ESTAB} or 0=  $P{ESTAB}) and FILIAL.ESTAB <> 800
    AND CIDADE.UF = $P{UF}   
),
ROMA_PAGO AS  (
    SELECT
    R.ESTAB,
    R.ROMANEIO,
    R.ENTRADASAIDA,
    R.NUMEROCM,
    SUM(R.QTDEPAGO) AS QTDEPAGO
    FROM ROMATXSERVICOPG R
    INNER JOIN ROMA_ABERTO ON 
        R.ESTAB = ROMA_ABERTO.ESTAB
        AND R.ROMANEIO      = ROMA_ABERTO.ROMANEIO
        AND R.ENTRADASAIDA  = ROMA_ABERTO.ENTRADASAIDA
        AND R.NUMEROCM      = ROMA_ABERTO.NUMEROCM
    GROUP BY
    R.ESTAB,R.ROMANEIO,R.ENTRADASAIDA,R.NUMEROCM
),
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE U_TIPOCTR.U_TIPOCTR_ID IN (2,7,12)
),
BAIXAS AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE U_TIPOCTR.U_TIPOCTR_ID IN (2,7,12)
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
VENCTO AS (
    SELECT
    ESTAB,
    CONTRATO,
    MAX(DTVENCTO) AS DTVENCTO
    FROM CONTRATODTVENCTO C
    GROUP BY ESTAB,CONTRATO
),
SALDO_MANUAL AS (
SELECT 
    CONTRATO.ESTAB,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    LOCALEST.LOCAL,
    ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) QTDSALDO
FROM CONTRATO
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = CONTRATO.NUMEROCM
    AND ENDERECO.SEQENDERECO =  CONTRATO.ENDALTERNATIVO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
LEFT JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

INNER JOIN CONTRATOITE ON 
    CONTRATOITE.ESTAB = CONTRATO.ESTAB 
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN LOCALEST ON 
    LOCALEST.ESTAB = CONTRATOITE.ESTAB
    AND LOCALEST.LOCAL = CONTRATOITE.LOCAL
    
LEFT JOIN BAIXAS ON 
    BAIXAS.ESTAB = CONTRATOITE.ESTAB 
    AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
    AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN CANC ON 
    CANC.ESTAB = CONTRATOITE.ESTAB 
    AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
    AND CANC.SEQITEM = CONTRATOITE.SEQITEM

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID

WHERE 
U_TIPOCTR.U_TIPOCTR_ID IN (2,7,12)
AND CONTRATO.DTMOVSALDO <= LAST_DAY(CURRENT_DATE)
AND U_AGRPRODGR.U_AGRPRODGR_ID=$P{ITEM}
AND U.GRAOS='S'
AND CIDADE.UF =$P{UF}
AND FILIAL.INATIVA = 'N'
AND (FILIAL.ESTAB = $P{ESTAB} OR 0=  $P{ESTAB}) 
--and contrato.contrato = 2262
AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
)
SELECT
'O' AS TIPO,
DADOS.ESTAB,
CASE 
    WHEN CIDADE.UF='SP' AND DADOS.ESTAB = 5 THEN 'SP - VJ'
    WHEN DADOS.ESTAB = 79 THEN 'TR'
    ELSE CIDADE.UF 
END AS ESTADO,
FILIAL.REDUZIDO AS DESCESTAB,
DADOS.ITEM,
U_AGRPRODGR.U_AGRPRODGR_ID||'-'||U_AGRPRODGR.DESCAGRUPA AS DESCITEM,
DADOS.LOCAL,
DADOS.LOCAL||'-'||LOCALEST.DESCRICAO AS DESCLOCAL,
DIVIDE(SUM(SALDODIP),60) AS SALDODIP,
DIVIDE(SUM(SALDOFIS+SALDOROMA),60) AS SALDOFIS,
DIVIDE(SUM(SALDOROMA+DEPOSTOPROD),60) AS SALDOPROD,
DIVIDE(SUM(QTDSALDO),60) AS SALDOCAMP,
DIVIDE(SUM(SALDODIP - QTDSALDO),60) AS SALDOEMP
FROM(
SELECT
DISPONIVEL.ESTAB,
DISPONIVEL.ITEM,
DISPONIVEL.LOCAL,
DISPONIVEL.SALDODISP AS SALDODIP,
0 AS SALDOFIS,
0 AS QTDSALDO,
0 AS SALDOROMA,
0 AS DEPOSTOPROD
FROM DISPONIVEL WHERE SALDODISP <> 0 

UNION ALL

SELECT
FISICO.ESTAB,
FISICO.ITEM,
FISICO.LOCAL,
0 AS SALDODIP,
FISICO.SALDOFIS,
0 AS QTDSALDO,
0 AS SALDOROMA,
0 AS DEPOSTOPROD
FROM FISICO WHERE SALDOFIS <> 0 

UNION ALL

SELECT
S.ESTAB,
S.ITEM,
S.LOCAL,
0 AS SALDODIP,
0 AS SALDOFIS,
SUM(QTDSALDO) AS QTDSALDO,
0 AS SALDOROMA,
0 AS DEPOSTOPROD
FROM SALDO_MANUAL S
GROUP BY S.ESTAB,S.ITEM,S.LOCAL

UNION ALL

SELECT
A.ESTAB,
A.ITEM,
A.LOCAL,
0 AS SALDODIP,
0 AS SALDOFIS,
0 AS QTDSALDO,
SUM(CASE
    WHEN A.ENTRADASAIDA = 'E' THEN A.PESOLIQUIDO - NVL(ROMA_PAGO.QTDEPAGO,0)
    ELSE (A.PESOLIQUIDO - NVL(ROMA_PAGO.QTDEPAGO,0))*-1
END)SALDOROMA,
0 AS DEPOSTOPROD
FROM ROMA_ABERTO A
LEFT JOIN ROMA_PAGO ON 
    ROMA_PAGO.ESTAB = A.ESTAB
    AND ROMA_PAGO.ROMANEIO      = A.ROMANEIO
    AND ROMA_PAGO.ENTRADASAIDA  = A.ENTRADASAIDA
    AND ROMA_PAGO.NUMEROCM      = A.NUMEROCM
    
GROUP BY
A.ESTAB,
A.ITEM,
A.LOCAL
HAVING SUM(CASE
    WHEN A.ENTRADASAIDA = 'E' THEN A.PESOLIQUIDO - NVL(ROMA_PAGO.QTDEPAGO,0)
    ELSE (A.PESOLIQUIDO - NVL(ROMA_PAGO.QTDEPAGO,0))*-1
END) > 0

UNION ALL

SELECT 
BI_SALDODEPOSITO.ESTAB,
BI_SALDODEPOSITO.ITEM,
BI_SALDODEPOSITO.LOCAL,
0 AS SALDODIP,
0 AS SALDOFIS,
0 AS QTDSALDO,
0 AS SALDOROMA,
DEPOSTOPROD
FROM BI_SALDODEPOSITO
INNER JOIN FILIAL ON FILIAL.ESTAB = BI_SALDODEPOSITO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE  = FILIAL.CIDADE
WHERE
BI_SALDODEPOSITO.ITEM = $P{ITEM}
AND CIDADE.UF = $P{UF}
AND (FILIAL.ESTAB = $P{ESTAB} OR 0 = $P{ESTAB} ) AND FILIAL.ESTAB <> 800 AND DEPOSTOPROD <> 0

)DADOS

LEFT JOIN LOCALEST ON
    LOCALEST.ESTAB = DADOS.ESTAB
    AND LOCALEST.LOCAL = DADOS.LOCAL

INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = DADOS.ITEM
INNER JOIN FILIAL ON FILIAL.ESTAB = DADOS.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

GROUP BY
DADOS.ESTAB,
CIDADE.UF,
FILIAL.REDUZIDO,
DADOS.ITEM,
U_AGRPRODGR.U_AGRPRODGR_ID,
U_AGRPRODGR.DESCAGRUPA,
DADOS.LOCAL,
LOCALEST.DESCRICAO 

ORDER BY U_AGRPRODGR.U_AGRPRODGR_ID,
(CASE 
    WHEN CIDADE.UF='SP' AND DADOS.ESTAB = 5 THEN 'SP - VJ'
    WHEN DADOS.ESTAB = 79 THEN 'TR'
    ELSE CIDADE.UF 
END ) DESC,
DADOS.ESTAB,
DADOS.LOCAL