WITH NOTAS AS (
    SELECT
    *
    FROM(
    
    SELECT
    UF,
    UFNOME,
    ITEM,
    CIDENTREGA,
  --  SUM(CASE WHEN COALESCE(CONFERIDO,'N') = 'S'  THEN /*QTDNOTA_DESC*/ SALDONOTA ELSE 0 END) AS DESCARREGADO,
  --  SUM(CASE WHEN coalesce(CONFERIDO,'N') = 'N' THEN SALDONOTA ELSE 0 END) TRANSITO,
    SUM(SALDONOTA) AS SALDOTOTAL
    FROM(

    SELECT
    CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END UF,
    CASE WHEN TRADING = 'S' THEN 'Trading' ELSE UF.NOME END UFNOME,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    CID.NOME AS CIDENTREGA,
      NFCAB.NOTA,
   -- COALESCE(RETENPORTO_U.CONFERIDO,'N') AS CONFERIDO,
    SUM(NFITEM.QUANTIDADE) AS QTDNOTA,
    SUM(NFITEM.QUANTIDADE) - COALESCE(BAIXAS.BX,0) AS SALDONOTA
   -- SUM(CASE WHEN COALESCE(RETENPORTO_U.CONFERIDO,'N') = 'S' THEN COALESCE(RETENPORTO.PESODESCARREGAMENTO,0) ELSE 0 END) QTDNOTA_DESC 
    FROM NFCAB
    
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
        
    LEFT JOIN (
        SELECT
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        SUM(QUANTIDADE) AS BX
        FROM NFITEMAPARTIRDE
      
     -- INNER JOIN NFCAB ON 
      -- NFCAB.ESTAB = NFITEMAPARTIRDE.ESTAB
     -- AND NFCAB.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
      
      -- WHERE NFCAB.NOTACONF NOT IN (382)
    
        GROUP BY
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM
    )BAIXAS ON
    BAIXAS.ESTABORIGEM = NFITEM.ESTAB
    AND BAIXAS.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
    AND BAIXAS.SEQNOTAORIGEM = NFITEM.SEQNOTA
    
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN UF ON UF.UF = CIDADE.UF
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN RETENPORTO ON
        RETENPORTO.ESTAB = NFITEM.ESTAB
        AND RETENPORTO.SEQNOTA = NFITEM.SEQNOTA
        AND RETENPORTO.SEQNOTAITEM = NFITEM.SEQNOTAITEM
        AND RETENPORTO.NUMEROCM = NFCAB.NUMEROCM

  /*  LEFT JOIN RETENPORTO_U ON 
        RETENPORTO_U.ESTAB = NFCAB.ESTAB
        AND RETENPORTO_U.SEQNOTA = NFCAB.SEQNOTA
        AND RETENPORTO_U.NUMEROCM = NFCAB.NUMEROCM*/
      
    /*  LEFT JOIN RETENPORTO_U ON 
        RETENPORTO_U.ESTAB = RETENPORTO.ESTAB
        AND RETENPORTO_U.SEQNOTA = RETENPORTO.SEQNOTA
        AND RETENPORTO_U.NUMEROCM = RETENPORTO.NUMEROCM
        AND RETENPORTO_U.SEQNOTAITEM = RETENPORTO.SEQNOTAITEM*/
  
    LEFT JOIN CONTAMOV MOV ON MOV.NUMEROCM = NFCAB.PESSENTREGA
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = NFCAB.PESSENTREGA
        AND ENDERECO.SEQENDERECO = NFCAB.SEQENDENTREGA
        
    LEFT JOIN CIDADE CID ON CID.CIDADE = COALESCE(ENDERECO.CIDADE,MOV.CIDADE)
  
    WHERE
    NFCAB.NOTACONF IN (388,394,382)
    AND COALESCE(NFCAB.STATUS,'X') <> 'C'
    AND (
        'X' IN (:UF)
        OR
        (CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END) IN (:UF)
        )
      AND U_AGRPRODGR.U_AGRPRODGR_ID = :ITEM

    GROUP BY
  --  RETENPORTO_U.CONFERIDO,
    TRADING,
      NFCAB.NOTA,
    UF.UF,
    UF.NOME ,
    U_AGRPRODGR.U_AGRPRODGR_ID,
    BAIXAS.BX,
    CID.NOME

    )DADOS

    GROUP BY
    UF,
    UFNOME,
    ITEM,
    CIDENTREGA
    
    )DADOS1
   WHERE /*DESCARREGADO <> 0 OR TRANSITO <> 0 OR*/ SALDOTOTAL <> 0
    
),

CONTRATOS AS (
  SELECT
  *
  FROM(
    SELECT
    CASE WHEN CONTCONF = 7 AND CONTRATO_U.TIPOFRETES = 'CIF' THEN CIDPESS.NOME ELSE CID.NOME END AS CIDENTREGA,
    --CID.NOME AS CIDENTREGA,
    CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END UF,
    CASE WHEN TRADING = 'S' THEN 'Trading' ELSE UF.NOME END UFNOME,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    SUM(
        CASE WHEN CONTRATO.CONTCONF = 26 then ARREDONDAR(PSALDO.NQTDSALDO,2) ELSE 0 END
        ) AS QTDCTR,
      SUM(
        CASE WHEN CONTRATO.CONTCONF = 7 AND CONTRATO_U.TIPOFRETES = 'CIF' then ARREDONDAR(PSALDO.NQTDSALDO,2) ELSE 0 END
        ) AS QTDCTR_C
   -- SUM(CONTRATOITE.QUANTIDADE - COALESCE(CANCELADO.QTDCANC,0)) AS QTDCTR
    FROM CONTRATO
    
    INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATO.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
        
    INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN UF ON UF.UF = CIDADE.UF
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN (
        SELECT
        ESTAB,
        CONTRATO,
        SEQITEM,
        SUM(QUANTIDADE) AS QTDCANC
        FROM CONTRATOCANC
        
        GROUP BY
        ESTAB,CONTRATO,SEQITEM
    )CANCELADO ON
    CANCELADO.ESTAB = CONTRATOITE.ESTAB
    AND CANCELADO.CONTRATO = CONTRATOITE.CONTRATO
    AND CANCELADO.SEQITEM = CONTRATOITE.SEQITEM
    
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.PESSENTREGA
    LEFT JOIN ENDERECO ON 
        ENDERECO.NUMEROCM = CONTRATO.PESSENTREGA
        AND ENDERECO.SEQENDERECO = CONTRATO.SEQENDENTREGA
    
    LEFT JOIN CIDADE CID ON CID.CIDADE = COALESCE(ENDERECO.CIDADE,CONTAMOV.CIDADE)
    
     INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
  
    LEFT JOIN CONTRATO_U ON
        CONTRATO_U.ESTAB = CONTRATO.ESTAB
        AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO

    LEFT JOIN LOCALEST ON 
        LOCALEST.ESTAB = CONTRATOITE.ESTAB
        AND LOCALEST.LOCAL = CONTRATOITE.LOCAL
        
    LEFT JOIN LOCALEST_U ON
       LOCALEST.ESTAB = LOCALEST_U.ESTAB
        AND LOCALEST.LOCAL = LOCALEST_U.LOCAL 
        
    LEFT JOIN CIDADE CIDPESS ON CIDPESS.CIDADE = LOCALEST_U.CIDADEPESSOA
    
    WHERE
    CONTRATO.CONTCONF  in (26,7)
    AND CONTRATO.DTLIMENTIMP BETWEEN :DTINI AND :DTFIM
    and ARREDONDAR(PSALDO.NQTDSALDO,2) > 0
   AND (
        'X' IN (:UF)
        OR
        (CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END) IN (:UF)
        )
    AND U_AGRPRODGR.U_AGRPRODGR_ID = :ITEM
    
    GROUP BY
    TRADING,
    UF.UF,
    UF.NOME ,
    CID.NOME,
    CIDPESS.NOME,
    CONTCONF,
    CONTRATO_U.TIPOFRETES,
    U_AGRPRODGR.U_AGRPRODGR_ID
    )DADOS WHERE QTDCTR <> 0 OR QTDCTR_C <> 0
),

BASE AS (
    SELECT
    UF,
    UFNOME,
    CIDENTREGA,
    ITEM,
    SUM(QTDCTR_C) AS QTDCTR_C,
    SUM(QTDCTR_C_SC) AS QTDCTR_C_SC,
    SUM(VENDIDO) AS VENDIDO,
    SUM(VENDIDO_SC) AS VENDIDO_SC,
    SUM(DESCARREGADO) AS DESCARREGADO,
    SUM(DESCARREGADO_SC) AS DESCARREGADO_SC,
    SUM(TRANSITO) AS TRANSITO,
    SUM(TRANSITO_SC) AS TRANSITO_SC,
    SUM(SALDOTOTAL) AS SALDOTOTAL
    FROM(
    SELECT
    CONTRATOS.UF,
    CONTRATOS.UFNOME,
    CONTRATOS.CIDENTREGA,
    CONTRATOS.ITEM,
    QTDCTR_C,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR_C,60),2) AS QTDCTR_C_SC,
    CONTRATOS.QTDCTR AS VENDIDO,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR,60),2) AS VENDIDO_SC,
    0 DESCARREGADO,
    0 DESCARREGADO_SC,
    0 TRANSITO,
    0 TRANSITO_SC,
      0 AS SALDOTOTAL/*
    CONTRATOS.QTDCTR - COALESCE(NOTAS.QTDNOTA,0) - COALESCE(NOTAS.SALDONOTA,0) AS A_EMBARCAR,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR - COALESCE(NOTAS.QTDNOTA,0) - COALESCE(NOTAS.SALDONOTA,0),60),2) A_EMBARCAR_SC,
    
    CONTRATOS.QTDCTR - COALESCE(NOTAS.QTDNOTA,0) AS A_PERFORMAR,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR - COALESCE(NOTAS.QTDNOTA,0),60),2) A_PERFORMAR_SC*/
    
    FROM CONTRATOS
        
    UNION ALL
    
    SELECT
    NOTAS.UF,
    NOTAS.UFNOME,
    NOTAS.CIDENTREGA,
    NOTAS.ITEM,
    0 AS QTDCTR_C,
    0 AS QTDCTR_C_SC,
    0 VENDIDO,
    0 VENDIDO_SC,
  0  DESCARREGADO,
0 AS DESCARREGADO_SC,
      --    ARREDONDAR(DIVIDE(DESCARREGADO,60),2) AS DESCARREGADO_SC,
  0  TRANSITO,
 0 AS TRANSITO_SC,
      SALDOTOTAL
      --   ARREDONDAR(DIVIDE(TRANSITO,60),2) AS TRANSITO_SC
   -- COALESCE(NOTAS.QTDNOTA,0) AS DESCARREGADO,
   -- ARREDONDAR(DIVIDE(COALESCE(NOTAS.QTDNOTA,0),60),2) AS DESCARREGADO_SC,
   -- COALESCE(NOTAS.QTDNOTA_DESC,0) AS DESCARREGADO,
   -- ARREDONDAR(DIVIDE(COALESCE(NOTAS.QTDNOTA_DESC,0),60),2) AS DESCARREGADO_SC,
   -- COALESCE(NOTAS.SALDONOTA,0) AS TRANSITO,
   -- ARREDONDAR(DIVIDE(COALESCE(NOTAS.SALDONOTA,0),60),2) AS TRANSITO_SC
    FROM NOTAS
    
    )DADOS
    
    GROUP BY
    UF,
    UFNOME,
    CIDENTREGA,
    ITEM
)

SELECT
BASE.*,
VENDIDO - SALDOTOTAL /*COALESCE(DESCARREGADO,0) - COALESCE(TRANSITO,0) */ AS A_EMBARCAR,
VENDIDO_SC -  ARREDONDAR(DIVIDE(SALDOTOTAL,60),2)/*COALESCE(DESCARREGADO_SC,0) - COALESCE(TRANSITO_SC,0) */ AS A_EMBARCAR_SC,
    
VENDIDO - SALDOTOTAL/*COALESCE(DESCARREGADO,0)*/ AS A_PERFORMAR,
VENDIDO_SC - ARREDONDAR(DIVIDE(SALDOTOTAL,60),2)/*COALESCE(DESCARREGADO_SC,0) */ AS A_PERFORMAR_SC
FROM BASE

