WITH NOTAS AS (
    SELECT
    *
    FROM(
    
    SELECT
    UF,
    UFNOME,
    ITEM,
    CIDENTREGA,
    SUM(SALDONOTA) AS SALDOTOTAL
    FROM(

    SELECT
    CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END UF,
    CASE WHEN TRADING = 'S' THEN 'Trading' ELSE UF.NOME END UFNOME,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    CID.NOME AS CIDENTREGA,
    NFCAB.NOTA,
    SUM(NFITEM.QUANTIDADE) AS QTDNOTA,
    -- CÁLCULO CORRIGIDO - VERSÃO FINAL
    SUM(NFITEM.QUANTIDADE) - 
    SUM(COALESCE((
        SELECT SUM(B.QUANTIDADE) 
        FROM NFITEMAPARTIRDE B 
        WHERE B.ESTABORIGEM = NFCAB.ESTAB 
        AND B.SEQNOTAORIGEM = NFCAB.SEQNOTA 
        AND B.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
    ), 0)) AS SALDONOTA
    FROM NFCAB
    
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
        
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN UF ON UF.UF = CIDADE.UF
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
  
    LEFT JOIN CONTAMOV MOV ON MOV.NUMEROCM = NFCAB.PESSENTREGA
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = NFCAB.PESSENTREGA
        AND ENDERECO.SEQENDERECO = NFCAB.SEQENDENTREGA
        
    LEFT JOIN CIDADE CID ON CID.CIDADE = COALESCE(ENDERECO.CIDADE,MOV.CIDADE)
  
    WHERE
    NFCAB.NOTACONF IN (388,394,382)
    AND COALESCE(NFCAB.STATUS,'X') <> 'C'
    AND (
        'X' IN (:UF)
        OR
        (CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END) IN (:UF)
        )
      AND U_AGRPRODGR.U_AGRPRODGR_ID = :ITEM

    GROUP BY
    TRADING,
    NFCAB.NOTA,
    UF.UF,
    UF.NOME,
    U_AGRPRODGR.U_AGRPRODGR_ID,
    CID.NOME

    )DADOS

    GROUP BY
    UF,
    UFNOME,
    ITEM,
    CIDENTREGA
    
    )DADOS1
   WHERE SALDOTOTAL <> 0
    
),

CONTRATOS AS (
  SELECT
  *
  FROM(
    SELECT
    CASE WHEN CONTCONF = 7 AND CONTRATO_U.TIPOFRETES = 'CIF' THEN CIDPESS.NOME ELSE CID.NOME END AS CIDENTREGA,
    CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END UF,
    CASE WHEN TRADING = 'S' THEN 'Trading' ELSE UF.NOME END UFNOME,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    SUM(
        CASE WHEN CONTRATO.CONTCONF = 26 then ARREDONDAR(PSALDO.NQTDSALDO,2) ELSE 0 END
        ) AS QTDCTR,
      SUM(
        CASE WHEN CONTRATO.CONTCONF = 7 AND CONTRATO_U.TIPOFRETES = 'CIF' then ARREDONDAR(PSALDO.NQTDSALDO,2) ELSE 0 END
        ) AS QTDCTR_C,
    SUM(
        CASE WHEN CONTRATO.CONTCONF = 38 then ARREDONDAR(PSALDO.NQTDSALDO,2) ELSE 0 END
        ) AS QTD_AFIXAR
    FROM CONTRATO
    
    INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATO.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
        
    INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN UF ON UF.UF = CIDADE.UF
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN (
        SELECT
        ESTAB,
        CONTRATO,
        SEQITEM,
        SUM(QUANTIDADE) AS QTDCANC
        FROM CONTRATOCANC
        GROUP BY
        ESTAB,CONTRATO,SEQITEM
    )CANCELADO ON
    CANCELADO.ESTAB = CONTRATOITE.ESTAB
    AND CANCELADO.CONTRATO = CONTRATOITE.CONTRATO
    AND CANCELADO.SEQITEM = CONTRATOITE.SEQITEM
    
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.PESSENTREGA
    LEFT JOIN ENDERECO ON 
        ENDERECO.NUMEROCM = CONTRATO.PESSENTREGA
        AND ENDERECO.SEQENDERECO = CONTRATO.SEQENDENTREGA
    
    LEFT JOIN CIDADE CID ON CID.CIDADE = COALESCE(ENDERECO.CIDADE,CONTAMOV.CIDADE)
    
     INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
  
    LEFT JOIN CONTRATO_U ON
        CONTRATO_U.ESTAB = CONTRATO.ESTAB
        AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO

    LEFT JOIN LOCALEST ON 
        LOCALEST.ESTAB = CONTRATOITE.ESTAB
        AND LOCALEST.LOCAL = CONTRATOITE.LOCAL
        
    LEFT JOIN LOCALEST_U ON
       LOCALEST.ESTAB = LOCALEST_U.ESTAB
        AND LOCALEST.LOCAL = LOCALEST_U.LOCAL 
        
    LEFT JOIN CIDADE CIDPESS ON CIDPESS.CIDADE = LOCALEST_U.CIDADEPESSOA
    
    WHERE
    CONTRATO.CONTCONF  in (26,7,38)
    AND CONTRATO.DTLIMENTIMP BETWEEN :DTINI AND :DTFIM
    and ARREDONDAR(PSALDO.NQTDSALDO,2) > 0
   AND (
        'X' IN (:UF)
        OR
        (CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END) IN (:UF)
        )
    AND U_AGRPRODGR.U_AGRPRODGR_ID = :ITEM
    
    GROUP BY
    TRADING,
    UF.UF,
    UF.NOME ,
    CID.NOME,
    CIDPESS.NOME,
    CONTCONF,
    CONTRATO_U.TIPOFRETES,
    U_AGRPRODGR.U_AGRPRODGR_ID
    )DADOS WHERE QTDCTR <> 0 OR QTDCTR_C <> 0 or QTD_AFIXAR <> 0
),

RETENCAO AS (
   SELECT
    CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END UF,
    CASE WHEN TRADING = 'S' THEN 'Trading' ELSE UF.NOME END UFNOME,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    CID.NOME AS CIDENTREGA,
    R.PESORETENCAO,
    ARREDONDAR(DIVIDE(R.PESORETENCAO,60),2) AS PESORETENCAO_SC
    FROM RETENPORTO R
    
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = R.ESTAB
        AND NFCAB.SEQNOTA = R.SEQNOTA
        AND NFCAB.NUMEROCM = R.NUMEROCM
        
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = NFCAB.PESSENTREGA
        AND ENDERECO.SEQENDERECO = NFCAB.SEQENDENTREGA
    
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.PESSENTREGA
    LEFT JOIN CIDADE CID ON CID.CIDADE = COALESCE(ENDERECO.CIDADE,CONTAMOV.CIDADE)
    
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN UF ON UF.UF = CIDADE.UF 
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = R.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN RETENPORTO_U ON 
        RETENPORTO_U.ESTAB = R.ESTAB
        AND RETENPORTO_U.SEQNOTA = R.SEQNOTA
        AND RETENPORTO_U.NUMEROCM = R.NUMEROCM
        AND RETENPORTO_U.SEQNOTAITEM = R.SEQNOTAITEM
        
    WHERE 
    R.TRANSACAO = 'E'
    AND NFCAB.NOTACONF IN (394,382,388)
    AND R.PESORETENCAO <> 0
    AND R.DTRETENCAO BETWEEN :DTINI AND :DTFIM
    AND RETENPORTO_U.CONFERIDO = 'S'
    AND (
        'X' IN (:UF)
        OR
        (CASE WHEN TRADING = 'S' THEN 'TR' ELSE UF.UF END) IN (:UF)
        )
    AND U_AGRPRODGR.U_AGRPRODGR_ID = :ITEM

),

BASE AS (
    SELECT
    UF,
    UFNOME,
    CIDENTREGA,
    ITEM,
    SUM(QTDCTR_C) AS QTDCTR_C,
    SUM(QTDCTR_C_SC) AS QTDCTR_C_SC,
    SUM(VENDIDO) AS VENDIDO,
    SUM(VENDIDO_SC) AS VENDIDO_SC,
    SUM(QTD_AFIXAR) AS QTD_AFIXAR,
    SUM(AFIXAR_SC) AS AFIXAR_SC,
    SUM(PESORETENCAO)PESORETENCAO,
    SUM(PESORETENCAO_SC)PESORETENCAO_SC,
    SUM(DESCARREGADO) AS DESCARREGADO,
    SUM(DESCARREGADO_SC) AS DESCARREGADO_SC,
    SUM(TRANSITO) AS TRANSITO,
    SUM(TRANSITO_SC) AS TRANSITO_SC,
    SUM(SALDOTOTAL) AS SALDOTOTAL
    FROM(
    
    SELECT
    CONTRATOS.UF,
    CONTRATOS.UFNOME,
    CONTRATOS.CIDENTREGA,
    CONTRATOS.ITEM,
    QTDCTR_C,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR_C,60),2) AS QTDCTR_C_SC,
    CONTRATOS.QTDCTR AS VENDIDO,
    ARREDONDAR(DIVIDE(CONTRATOS.QTDCTR,60),2) AS VENDIDO_SC,
    QTD_AFIXAR,
    ARREDONDAR(DIVIDE(CONTRATOS.QTD_AFIXAR,60),2) AS AFIXAR_SC,
    0 AS PESORETENCAO,
    0 AS PESORETENCAO_SC,
    0 DESCARREGADO,
    0 DESCARREGADO_SC,
    0 TRANSITO,
    0 TRANSITO_SC,
      0 AS SALDOTOTAL
    FROM CONTRATOS
        
    UNION ALL
    
    SELECT
    NOTAS.UF,
    NOTAS.UFNOME,
    NOTAS.CIDENTREGA,
    NOTAS.ITEM,
    0 AS QTDCTR_C,
    0 AS QTDCTR_C_SC,
    0 VENDIDO,
    0 VENDIDO_SC,
    0 AS QTD_AFIXAR,
    0 AS AFIXAR_SC,
    0 AS PESORETENCAO,
    0 AS PESORETENCAO_SC,
    0 DESCARREGADO,
    0 AS DESCARREGADO_SC,
    0 TRANSITO,
    0 AS TRANSITO_SC,
    SALDOTOTAL
    FROM NOTAS
    
    UNION ALL
    
    SELECT
    RETENCAO.UF,
    RETENCAO.UFNOME,
    RETENCAO.CIDENTREGA,
    RETENCAO.ITEM,
    0 AS QTDCTR_C,
    0 AS QTDCTR_C_SC,
    0 AS VENDIDO,
    0 AS VENDIDO_SC,
    0 QTD_AFIXAR,
    0 AFIXAR_SC,
    PESORETENCAO,
    PESORETENCAO_SC,
    0 DESCARREGADO,
    0 DESCARREGADO_SC,
    0 TRANSITO,
    0 TRANSITO_SC,
    0 AS SALDOTOTAL
    FROM RETENCAO
    
    )DADOS
    GROUP BY
    UF,
    UFNOME,
    CIDENTREGA,
    ITEM
)

SELECT
BASE.*,
VENDIDO - SALDOTOTAL + QTD_AFIXAR AS A_EMBARCAR,
VENDIDO_SC - ARREDONDAR(DIVIDE(SALDOTOTAL,60),2) + AFIXAR_SC AS A_EMBARCAR_SC,
VENDIDO - SALDOTOTAL AS A_PERFORMAR,
VENDIDO_SC - ARREDONDAR(DIVIDE(SALDOTOTAL,60),2) AS A_PERFORMAR_SC
FROM BASE