WITH BASE AS (
    SELECT DISTINCT
    ESTAB,
    CHAVEACESSO,
    CODFORNECEDOR
    FROM U_DESCARGA_TRADING
    WHERE DATA BETWEEN :DTINI AND :DTFIM
    AND (0 IN (:ITEM) OR CODITEM IN (:ITEM))
    AND (0 IN (:TERMINAL) OR CODTERMINAL IN (:TERMINAL))
),
CHAVES AS (
SELECT
--DESC_NAVIO,
CHAVENFE_FL,
CHAVENFE_ORI,
SUM(QTD_BAIXADA) AS QTD_BAIXADA
FROM(

SELECT  
NAVIOS.NAVIO||'-'||NAVIOS.DESCRICAO AS DESC_NAVIO,
NF_FM.CHAVEACESSONFE CHAVENFE_FL,
case when NF_ORI.notaconf = 394 then null else nfitemexporta.chnfe end CHAVENFE_ORI,
coalesce(nfitemexporta.qexport,NFEXPORIGEM.quantidade) AS QTD_BAIXADA

FROM NFCAB

INNER JOIN FILIAL ON FILIAL.ESTAB=NFCAB.ESTAB

inner join nfcab_u on nfcab_u.estab=nfcab.estab
		                      and nfcab_u.seqnota=nfcab.seqnota

INNER JOIN NAVIOS ON NAVIOS.NAVIO=NFCAB.expnavio



INNER JOIN NFITEM ON NFITEM.ESTAB=NFCAB.ESTAB
                AND NFITEM.SEQNOTA=NFCAB.SEQNOTA

--FORMACAO  
 INNER JOIN NFEXPORIGEM ON NFEXPORIGEM.ESTAB=NFITEM.ESTAB
                    AND NFEXPORIGEM.SEQNOTA=NFITEM.SEQNOTA
                    --AND NFEXPORIGEM.SEQNOTAITEMO=NFITEM.ESTAB



LEFT JOIN NFITEM NFI_FM ON NFI_FM.ESTAB=NFEXPORIGEM.ESTABORI
                       AND NFI_FM.SEQNOTA=NFEXPORIGEM.SEQNOTAORI
                       AND NFI_FM.SEQNOTAITEM=NFEXPORIGEM.SEQNOTAITEMORI


LEFT JOIN NFCAB NF_FM ON    NF_FM.ESTAB=NFI_FM.ESTAB      
                      AND NF_FM.SEQNOTA=NFI_FM.SEQNOTA   

left join contamov  cmentrega on cmentrega.numerocm=NF_FM.pessentrega                   

--ORIGEM
left JOIN NFITEMEXPORTA ON NFITEMEXPORTA.ESTABORI=NFI_FM.ESTAB
                AND NFITEMEXPORTA.SEQNOTAORI=NFI_FM.SEQNOTA
                AND NFITEMEXPORTA.SEQNOTAITEMORI=NFI_FM.SEQNOTAITEM   
                -------OLHAR
                 AND NFITEMEXPORTA.SEQNOTA=NFITEM.SEQNOTA
                AND NFITEMEXPORTA.SEQNOTAITEM=NFITEM.SEQNOTAITEM


LEFT JOIN NFITEM NFI_ORI ON NFI_ORI.ESTAB=NFITEMEXPORTA.ESTABORI
                       AND NFI_ORI.SEQNOTA=NFITEMEXPORTA.SEQNOTAORI
                       AND NFI_ORI.SEQNOTAITEM=NFITEMEXPORTA.SEQNOTAITEMORI


LEFT JOIN NFCAB NF_ORI ON    NF_ORI.ESTAB=NFI_ORI.ESTAB      
                      AND NF_ORI.SEQNOTA=NFI_ORI.SEQNOTA                      



WHERE  NFCAB.STATUS <> 'C' 
)DADOS
GROUP BY
--DESC_NAVIO,
CHAVENFE_FL,
CHAVENFE_ORI
),
COMPLEMT AS (
    SELECT
    NFCAB.CHAVEACESSONFE,
    NFCAB.ESTAB,
    SUM(NFITEM.QUANTIDADE) AS NF_C
    FROM NFCAB
    INNER JOIN BASE ON
        BASE.ESTAB = NFCAB.ESTAB
        AND BASE.CHAVEACESSO = NFCAB.CHAVEACESSONFE
    INNER JOIN NFCAB_U N ON
        NFCAB.ESTAB = N.ESTAB
        AND NFCAB.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCAB NF ON
        NF.ESTAB = N.ESTAB
        AND NF.NOTA = N.NNOTA
        AND N.NNOTA <> 0
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NF.ESTAB
        AND NFITEM.SEQNOTA = NF.SEQNOTA
    GROUP BY
    NFCAB.CHAVEACESSONFE,
    NFCAB.ESTAB
),
DESCARGA AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.CHAVEACESSONFE,
    NFCAB.SEQNOTA,
    ITEMAGRO.ITEM||'-'||ITEMAGRO.DESCRICAO AS ITEM,
    NFCFG.NOTACONF||'-'||NFCFG.DESCRICAO AS CONFIG,
    SUM(DISTINCT NFITEM.QUANTIDADE) AS QTD_NOTA,
   -- NVL(NF_C,0) AS NF_C,
   0 AS NF_C,
    SUM(CASE WHEN NF.NOTACONF IN (383,399) THEN N.QUANTIDADE ELSE 0 END) AS NF_CD,
    SUM(CASE WHEN NF.NOTACONF IN (206,373,384) THEN N.QUANTIDADE ELSE 0 END) AS NF_QB,
    SUM(CASE WHEN NF.NOTACONF IN (389,395) THEN N.QUANTIDADE ELSE 0 END) AS NF_RET
    FROM BASE
    
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = BASE.ESTAB
        AND NFCAB.CHAVEACESSONFE = BASE.CHAVEACESSO
    
    INNER JOIN NFITEM ON 
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    LEFT JOIN NFITEMAPARTIRDE N ON 
        N.ESTABORIGEM = NFITEM.ESTAB
        AND N.SEQNOTAORIGEM = NFITEM.SEQNOTA
        AND N.SEQNOTAITEMORIGEM  = NFITEM.SEQNOTAITEM
    
    LEFT JOIN NFCAB NF ON 
        NF.ESTAB   = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA

    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    LEFT JOIN COMPLEMT ON 
        COMPLEMT.ESTAB = NFCAB.ESTAB
        AND COMPLEMT.CHAVEACESSONFE = NFCAB.CHAVEACESSONFE

    WHERE
    NFCAB.STATUS <> 'C'
    GROUP BY NFCAB.ESTAB,NFCAB.CHAVEACESSONFE,ITEMAGRO.ITEM,ITEMAGRO.DESCRICAO,NFCFG.NOTACONF,NFCFG.DESCRICAO,NFCAB.SEQNOTA--,NF_C
),
REF1 AS (
    SELECT
    U.ESTAB,
    U.CHAVEACESSO,
    U.NF,
    U.DATA AS DTDESCARGA,
    U.REF AS REF1,
    CONTAMOV.NOME AS CLIENTE,
    COALESCE(ENDERECO.NOME,MOV.NOME) AS TERMINAL1,
    U.STATUS AS STATUS1,
    U.PORIGEM AS PESO1,
    U.PLIQUIDO AS PESOLIQ1,
    U.QUEBRA_SOBRA AS QUEBRA1,
    U.RETENCAO AS RET1,
    U.SALDO_NF_CCT AS SCCT,
    U.PESO_AF_CCT AS AFCCT,
    U.DATA_CCT AS DTCCT 
    FROM U_DESCARGA_TRADING U
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = U.CODFORNECEDOR
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = U.CODTERMINAL
        AND ENDERECO.SEQENDERECO = U.SEQ_END_TERMINA
    LEFT JOIN CONTAMOV MOV ON MOV.NUMEROCM = U.CODTERMINAL
    WHERE
    U.CHAVEACESSO IS NOT NULL
    AND (U.CODTERMINAL NOT IN (80861,28910))
),
REF2 AS (
    SELECT
    X.CHAVEACESSO,
    X.REF AS REF2,
    COALESCE(ENDERECO.NOME,CONTAMOV.NOME) AS TERMINAL2,
    X.STATUS AS STATUS2,
    X.PORIGEM AS PESO2,
    X.PLIQUIDO AS PESOLIQ2,
    X.QUEBRA_SOBRA AS QUEBRA2,
    X.RETENCAO AS RET2
    FROM U_DESCARGA_TRADING X
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = X.CODTERMINAL
        AND ENDERECO.SEQENDERECO = X.SEQ_END_TERMINA
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = X.CODTERMINAL
    WHERE
    X.CODTERMINAL IN (80861,28910)
    AND X.CHAVEACESSO IS NOT NULL
)
SELECT
D.CHAVEACESSONFE,
D.QTD_NOTA, 
REF1.ESTAB,
D.ITEM,
D.CONFIG,
REF1.NF,
D.SEQNOTA,
REF1.REF1,
REF1.DTDESCARGA,
REF1.CLIENTE,
REF1.TERMINAL1,
REF1.STATUS1,
REF1.PESO1,
REF1.PESOLIQ1,
REF1.QUEBRA1,
REF1.RET1,
REF2.TERMINAL2,
REF2.REF2,
REF2.STATUS2,
REF2.PESO2,
REF2.PESOLIQ2,
REF2.QUEBRA2,
REF2.RET2,
REF1.SCCT,
REF1.AFCCT,
REF1.DTCCT,
D.NF_C,
D.NF_CD, 
D.NF_QB, 
D.NF_RET,
NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) AS DIF_APARTIR,
D.QTD_NOTA - NVL(REF2.PESO2,REF1.PESO1) AS DIF_QTD,
D.NF_CD + D.NF_C + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0) AS DIF_QDC,
CASE WHEN D.NF_QB > (NVL(REF1.RET1,0)+NVL(REF2.RET2,0)) THEN 0 ELSE D.QTD_NOTA - D.NF_CD -  - NVL(REF1.RET1,0) - D.NF_RET - NVL(REF2.RET2,0) END S_UTIL,
CASE
    WHEN NVL(REF1.SCCT,0) = 0 THEN 'Consultar CCT'
    WHEN NVL(REF1.SCCT,0) >= (D.NF_CD + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0)) THEN 'Saldo OK'
    WHEN NVL(REF1.SCCT,0) < (D.NF_CD + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0)) THEN 'Saldo Verificar'
END DIF_CCT,
COALESCE(FL.QTD_BAIXADA,ORI.QTD_BAIXADA,0) AS QTD_NV,
NVL(REF1.PESOLIQ1,0)  - COALESCE(FL.QTD_BAIXADA,ORI.QTD_BAIXADA,0) AS DIF_NV,
D.NF_RET - COALESCE(FL.QTD_BAIXADA,ORI.QTD_BAIXADA,0) DIF_NF_RET
FROM DESCARGA D

LEFT JOIN REF1 ON REF1.CHAVEACESSO = D.CHAVEACESSONFE
LEFT JOIN REF2 ON REF2.CHAVEACESSO = D.CHAVEACESSONFE
LEFT JOIN CHAVES FL ON FL.CHAVENFE_FL = D.CHAVEACESSONFE
LEFT JOIN CHAVES ORI ON ORI.CHAVENFE_ORI = D.CHAVEACESSONFE
WHERE
(
    (NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) < 0 AND :DIF = 1)
    OR
     (NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) = 0 AND :DIF = 2)
     OR
     :DIF = 3
)