WITH NOTAS_NAVIO AS (
    SELECT
    --NFCAB_U.NAVIO,
    NFCAB.EXPNAVIO AS NAVIO,
    NFCAB.NOTA,
    NFCAB.VALOR
    FROM NFCAB
    
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCAB_U ON 
        NFCAB_U.ESTAB = NFCAB.ESTAB
        AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
        
    WHERE
    NFCAB.NOTACONF NOT IN (381) AND NFCFG.FISCAL = 'S'
),

CANCELADOS AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(QUANTIDADE) QTD
    FROM CONTRATOCANC

    GROUP BY ESTAB,CONTRATO,SEQITEM
    
)

SELECT
*
FROM(
SELECT DISTINCT
CONTRATO.NUMCOMPRADOR AS BOLETA,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
CONTRATO.CONTRATO,
ITEMAGRO.DESCRICAO AS PRODUTO,
TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
CONTRATOITE.VALORUNIT,
NAVIOS.DESCRICAO AS NAVIO,
NFCAB.NOTA AS NOTA_GERENCIAL,
NFCAB.VALOR AS VALOR_GERENCIAL,
TO_CHAR(CONTRATO.DTVENCTO,'DD/MM/YYYY') AS PRAZOPAGTO,
NOTAS_NAVIO.NOTA AS NOTAS_VENDA,
NOTAS_NAVIO.VALOR AS VALOR_VENDA,
CONTRATOITE.QUANTIDADE - COALESCE(CANCELADOS.QTD,0) as QTDECTR,
NFITEM.QUANTIDADE AS QTDENF,
PSALDO.NQTDSALDO AS SALDO
FROM CONTRATO

INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB

INNER JOIN CONTRATOITE ON
    CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN CONTRATONFITE ON
    CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
    AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
    AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN NFITEM ON
    NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA
    AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA
    AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
    
LEFT JOIN NFCAB ON
    NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA
    AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    
LEFT JOIN NFCAB_U ON
    NFCAB_U.ESTAB = NFCAB.ESTAB
    AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
    
LEFT JOIN NAVIOS ON NAVIOS.NAVIO = NFCAB_U.NAVIO_OS

LEFT JOIN NOTAS_NAVIO ON NOTAS_NAVIO.NAVIO = NAVIOS.NAVIO

LEFT JOIN CANCELADOS ON
    CANCELADOS.ESTAB = CONTRATOITE.ESTAB
    AND CANCELADOS.CONTRATO = CONTRATOITE.CONTRATO
    AND CANCELADOS.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM

LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON u_agrprodgr.u_agrprodgr_id = ITEMAGRO_U.U_AGRPRODGR_ID

  INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)

WHERE CONTCONF = 26
AND COALESCE(CONTRATO.ATIVO,'X') <> 'C'
AND (0 IN (:NAVIO) OR NAVIOS.NAVIO IN (:NAVIO))
AND (0 IN (:ITEM) OR u_agrprodgr.u_agrprodgr_id IN (:ITEM))

)DADOS

-- ORDER BY NAVIO
