WITH CTRNOTA AS (
    SELECT /*+ 
    QB_NAME(CTRNOTA_QB)
    MATERIALIZE
    NO_MERGE
    LEADING(CONTRATO)
    USE_HASH(NAT NATAPARTIRDE NFCFG)
    USE_NL(CONTRATONFITE NFCAB)
    INDEX(CONTRATONFITE IDX_FK_CONTITE_CONTRATONFITE)
    INDEX(NFCAB NFCAB01)
*/
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    NFCAB.DTEMISSAO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE CONTRATO.CONTCONF NOT IN (24,25,51,23,52) AND CONTRATOCFG.ENTRADASAIDA = 'S' AND CONTRATO.DTLIMENTIMP <= :DTFIN
),
BAIXAS AS (
    SELECT 
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO,
    SUM(CASE WHEN TRUNC(DTEMISSAO) = TRUNC(CURRENT_DATE) THEN BAIXADO ELSE 0 END)QTDPDIA
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE CONTRATO.CONTCONF NOT IN (24,25,51,23,52) AND CONTRATOCFG.ENTRADASAIDA = 'S'
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
SALDO_MANUAL AS (
    SELECT 
        FILIAL.ESTAB,
        FILIAL.REDUZIDO AS FILIAL,
        CONTRATO.CONTRATO,
        ITEMAGRO.ITEM AS COD_ITEM,
        U_AGRPRODGR.DESCAGRUPA AS PRODUTO,
        CONTAMOV.NOME AS CLIENTE,
        COALESCE(ENDALT.CNPJF,CONTAMOV.CNPJF) AS CNPJF,
        CONTRATO.CONTCONF,
        CONTRATO.PRIORIDADE,
        TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY')DTEMISSAO,
        TO_CHAR(CONTRATO_U.DTINICIOENT, 'DD/MM/YYYY') DTINICIOENT,
        TO_CHAR(CONTRATO.DTLIMENTIMP,'DD/MM/YYYY')AS LIMITE_ENT,
        TO_CHAR(CONTRATO.DTVENCTO,'DD/MM/YYYY')AS DTVENCTO ,
        CONTRATO_U.TIPOFRETES,
        CONTRATO_U.TIPOPGTO,
        CONTRATO_U.STATUSASS,
        CONTRATO_U.NOTACONF,
        CASE 
            WHEN CONTRATO.SEQENDENTREGA IS NULL THEN (CONTAMOV.ENDERECO||', '||CONTAMOV.BAIRRO)
            ELSE (ENDERECO.ENDERECO||', '||ENDERECO.BAIRRO) 
        END ENDERECO,
        PESSENT.NOME AS PESSOA_ENTREGA,
        CID_ENT.NOME AS CID_PESSENTREGA,
        UF.CODIGO || LPAD(CID_ENT.IBGE, 7 - LENGTH(UF.CODIGO), '0') AS COD_IBGE,
        CONTRATO.PESSENTREGA,
        CONTRATO.SEQENDENTREGA,
        CONTRATO.PESSRETIRADA,
        CONTRATO.SEQENDRETIRADA,
        PESS_RET.NOME AS PESSOA_RETIRADA,
        CID_RET.NOME AS CID_RETIRADA,
        NVL(BAIXAS.QTDPDIA,0) AS QTDPDIA,
        ARREDONDAR(CONTRATOITE.QUANTIDADE,2) AS QTD,
        NVL(BAIXAS.CANCELADO,0) + NVL(CANC.CANC,0) AS QTDCANC,
        NVL(BAIXAS.DEVOLIDO,0) AS QTDDEV,
        NVL(BAIXAS.BAIXADO,0) AS ENTREGUE,
        TO_CHAR(CONTRATO.DTMOVSALDO, 'DD/MM/YY') AS DTMOVSALDO,
        TO_CHAR(CONTRATO.DTLIMLIQIMP, 'DD/MM/YY') AS DTLIMLIQIMP,
        TO_CHAR(CONTRATO_U.DTPOSTERGACAO, 'DD/MM/YY') AS DTPOSTERGACAO,
        TO_CHAR(CT.DTVENCTO, 'DD/MM/YY') AS DTFLUXOFIXA,
        CT.NUMDIASPAGTO AS DTFLUXODIAS,
        CONTRATO.NUMCOMPRADOR,
        ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) AS SALDO
        
    FROM CONTRATO
    INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE=FILIAL.CIDADE
    INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
    
    INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
    LEFT JOIN CONTAMOV PESSENT ON PESSENT.NUMEROCM = CONTRATO.PESSENTREGA
    LEFT JOIN ENDERECO ENDALT ON 
        ENDALT.NUMEROCM = CONTRATO.NUMEROCM 
        AND ENDALT.seqendereco = CONTRATO.ENDALTERNATIVO
    LEFT JOIN ENDERECO ON 
        ENDERECO.NUMEROCM = CONTRATO.PESSENTREGA
        AND ENDERECO.SEQENDERECO = CONTRATO.SEQENDENTREGA
    LEFT JOIN CIDADE CID_ENT ON CID_ENT.CIDADE = COALESCE(ENDERECO.CIDADE,PESSENT.CIDADE)
    LEFT JOIN UF ON UF.UF = CID_ENT.UF
    
    LEFT JOIN ENDERECO END_RET ON END_RET.NUMEROCM = contrato.pessretirada
                AND END_RET.Seqendereco = CONTRATO.SEQENDRETIRADA
    LEFT JOIN CONTAMOV PESS_RET ON PESS_RET.NUMEROCM = CONTRATO.PESSRETIRADA
    LEFT JOIN CIDADE CID_RET ON CID_RET.CIDADE = COALESCE(END_RET.CIDADE,PESS_RET.CIDADE)

    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATO.ESTAB 
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
    LEFT JOIN CONTRATO_U ON 
        CONTRATO_U.ESTAB = CONTRATO.ESTAB
        AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO
    
    LEFT JOIN BAIXAS ON 
        BAIXAS.ESTAB = CONTRATOITE.ESTAB 
        AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
        AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM
    
    LEFT JOIN CANC ON 
        CANC.ESTAB = CONTRATOITE.ESTAB 
        AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
        AND CANC.SEQITEM = CONTRATOITE.SEQITEM
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN (
        SELECT
        ESTAB,
        CONTRATO,
        MAX(DTVENCTO) AS DTVENCTO,
        MAX(NUMDIASPAGTO) AS NUMDIASPAGTO
        FROM CONTRATODTVENCTO 
        GROUP BY ESTAB,CONTRATO
    ) CT ON CT.CONTRATO = CONTRATO.CONTRATO
            AND CT.ESTAB = CONTRATO.ESTAB

    WHERE 
    CONTRATO.CONTCONF NOT IN (24,25,51,23,52)
    AND CONTRATOCFG.ENTRADASAIDA = 'S'
    AND CONTRATO.DTLIMENTIMP <= :DTFIN
    AND FILIAL.INATIVA = 'N'
    AND (CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0)) > 1
    <#if UF?has_content>
        AND CIDADE.UF IN (:UF)
    </#if>
     <#if ITEM?has_content>
        AND U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM)
    </#if>
)


SELECT /*+ 
    GATHER_PLAN_STATISTICS
    QB_NAME(MAIN_QB)
*/
S.*
FROM SALDO_MANUAL S