SELECT DISTINCT
  U_CONTRNOTA_ALTER.TABELA, 
  U_CONTRNOTA_ALTER.ACAO, 
  U_CONTRNOTA_ALTER.USERID,
  U_CONTRNOTA_ALTER.DATA,
  U_CONTRNOTA_ALTER.HORA,
  U_CONTRNOTA_ALTER.COLUNANEW,
  U_CONTRNOTA_ALTER.CONTEUDONEW AS CONTEUDONEW,
  U_CONTRNOTA_ALTER.COLUNAOLD,
  U_CONTRNOTA_ALTER.CONTEUDOOLD AS CONTEUDOOLD,
  U_CONTRNOTA_ALTER.ESTAB,
  'Nota: '||U_CONTRNOTA_ALTER.DOCUMENTO AS DOCUMENTO,
  U_CONTRNOTA_ALTER.SEQITEM,
  U_CONTRNOTA_ALTER.DATAALT,
  COALESCE(U_CONTRNOTA_ALTER.DTEMISSAO,NFCAB.DTEMISSAO) AS DTEMISSAO, 
  NFCAB.NOTA, 
  NFITEM.ITEM, 
  CONTAMOV.NUMEROCM || '-' || CONTAMOV.NOME AS NOME, 
  NFCFG.NOTACONF || ' - ' || NFCFG.DESCRICAO AS CONFIGURACAO, 
  ITEMAGRO.DESCRICAO,
  0 AS CONTRATOBX
FROM U_CONTRNOTA_ALTER 
LEFT JOIN NFITEM 
  ON NFITEM.ESTAB = U_CONTRNOTA_ALTER.ESTAB 
  AND NFITEM.SEQNOTA = U_CONTRNOTA_ALTER.DOCUMENTO 
  AND NFITEM.SEQNOTAITEM = U_CONTRNOTA_ALTER.SEQITEM 
LEFT JOIN NFCAB 
  ON NFCAB.ESTAB = U_CONTRNOTA_ALTER.ESTAB 
  AND NFCAB.SEQNOTA = U_CONTRNOTA_ALTER.DOCUMENTO 
LEFT JOIN NFCFG 
  ON NFCFG.NOTACONF = COALESCE(U_CONTRNOTA_ALTER.CONF, NFCAB.NOTACONF)
LEFT JOIN CONTAMOV 
  ON CONTAMOV.NUMEROCM = COALESCE(NFCAB.NUMEROCM, U_CONTRNOTA_ALTER.NUMEROCM) 
LEFT JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = COALESCE(NFITEM.ITEM,U_CONTRNOTA_ALTER.ITEM)
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
WHERE U_CONTRNOTA_ALTER.TABELA IN ('NFITEM')
AND TRUNC(CAST(U_CONTRNOTA_ALTER.DATA AS DATE)) BETWEEN :DTINI AND :DTFIM 
AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))

UNION ALL 

SELECT DISTINCT 
  U_CONTRNOTA_ALTER.TABELA, 
  U_CONTRNOTA_ALTER.ACAO, 
  U_CONTRNOTA_ALTER.USERID,
  U_CONTRNOTA_ALTER.DATA,
  U_CONTRNOTA_ALTER.HORA,
  U_CONTRNOTA_ALTER.COLUNANEW,
  U_CONTRNOTA_ALTER.CONTEUDONEW AS CONTEUDONEW,
  U_CONTRNOTA_ALTER.COLUNAOLD,
  U_CONTRNOTA_ALTER.CONTEUDOOLD AS CONTEUDOOLD,
  U_CONTRNOTA_ALTER.ESTAB,
  'Contrato: '|| U_CONTRNOTA_ALTER.DOCUMENTO AS DOCUMENTO,
  U_CONTRNOTA_ALTER.SEQITEM,
  U_CONTRNOTA_ALTER.DATAALT,
  COALESCE(U_CONTRNOTA_ALTER.DTEMISSAO,CONTRATO.DTEMISSAO) AS DTEMISSAO, 
  CONTRATO.CONTRATO, 
  CONTRATOITE.ITEM, 
  CONTAMOV.NUMEROCM || '-' || CONTAMOV.NOME AS NOME, 
  CONTRATOCFG.CONTCONF || ' - ' || CONTRATOCFG.DESCRICAO AS CONFIGURACAO, 
  ITEMAGRO.DESCRICAO,
   COALESCE(CONTRATOBX.CONTRATOBX,0)CONTRATOBX
FROM U_CONTRNOTA_ALTER 
LEFT JOIN CONTRATOITE 
  ON CONTRATOITE.ESTAB = U_CONTRNOTA_ALTER.ESTAB 
  AND CONTRATOITE.CONTRATO = U_CONTRNOTA_ALTER.DOCUMENTO 
  AND CONTRATOITE.SEQITEM = U_CONTRNOTA_ALTER.SEQITEM 
LEFT JOIN CONTRATO 
  ON CONTRATO.ESTAB = CONTRATOITE.ESTAB 
  AND CONTRATO.CONTRATO = CONTRATOITE.CONTRATO
  LEFT JOIN CONTRATOBX
  ON CONTRATOBX.CONTRATO = CONTRATO.CONTRATO 
  AND CONTRATOBX.ESTAB = CONTRATO.ESTAB 
LEFT JOIN CONTRATOCFG 
  ON CONTRATOCFG.CONTCONF = COALESCE(U_CONTRNOTA_ALTER.CONF, CONTRATO.CONTCONF)
LEFT JOIN CONTAMOV 
  ON CONTAMOV.NUMEROCM = COALESCE(CONTRATO.NUMEROCM,U_CONTRNOTA_ALTER.NUMEROCM) 
LEFT JOIN ITEMAGRO 
  ON ITEMAGRO.ITEM = COALESCE(CONTRATOITE.ITEM,U_CONTRNOTA_ALTER.ITEM)
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
WHERE U_CONTRNOTA_ALTER.TABELA IN ('CONTRATOITE') 
AND TRUNC(CAST(U_CONTRNOTA_ALTER.DATA AS DATE)) BETWEEN :DTINI AND :DTFIM
AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND (0 IN (:ESTAB) OR CONTRATO.ESTAB IN (:ESTAB))

ORDER BY 2,16,11