WITH BASE AS (
    SELECT DISTINCT
    ESTAB,
    CHAVEACESSO
    FROM U_DESCARGA_TRADING
    WHERE DATA BETWEEN :DTINI AND :DTFIM
    AND (0 IN (:ITEM) OR CODITEM IN (:ITEM))
    AND (0 IN (:TERMINAL) OR CODTERMINAL IN (:TERMINAL))
),
DESCARGA AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.CHAVEACESSONFE,
    SUM(DISTINCT NFITEM.QUANTIDADE) AS QTD_NOTA,
    SUM(CASE WHEN NF.NOTACONF IN (383,399) THEN N.QUANTIDADE ELSE 0 END) AS NF_CD,
    SUM(CASE WHEN NF.NOTACONF IN (206,373,384) THEN N.QUANTIDADE ELSE 0 END) AS NF_QB,
    SUM(CASE WHEN NF.NOTACONF IN (389,395) THEN N.QUANTIDADE ELSE 0 END) AS NF_RET
    FROM BASE
    
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = BASE.ESTAB
        AND NFCAB.CHAVEACESSONFE = BASE.CHAVEACESSO
    
    INNER JOIN NFITEM ON 
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    LEFT JOIN NFITEMAPARTIRDE N ON 
        N.ESTABORIGEM = NFITEM.ESTAB
        AND N.SEQNOTAORIGEM = NFITEM.SEQNOTA
        AND N.SEQNOTAITEMORIGEM  = NFITEM.SEQNOTAITEM
    
    LEFT JOIN NFCAB NF ON 
        NF.ESTAB   = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA

    WHERE
    NFCAB.STATUS <> 'C'
    GROUP BY NFCAB.ESTAB,NFCAB.CHAVEACESSONFE
),
REF1 AS (
    SELECT
    U.ESTAB,
    U.CHAVEACESSO,
    U.NF,
    U.DATA AS DTDESCARGA,
    U.REF AS REF1,
    CONTAMOV.NOME AS CLIENTE,
    COALESCE(ENDERECO.NOME,MOV.NOME) AS TERMINAL1,
    U.STATUS AS STATUS1,
    U.PORIGEM AS PESO1,
    U.PLIQUIDO AS PESOLIQ1,
    U.QUEBRA_SOBRA AS QUEBRA1,
    U.RETENCAO AS RET1,
    U.SALDO_NF_CCT AS SCCT,
    U.PESO_AF_CCT AS AFCCT,
    U.DATA_CCT AS DTCCT 
    FROM U_DESCARGA_TRADING U
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = U.CODFORNECEDOR
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = U.CODTERMINAL
        AND ENDERECO.SEQENDERECO = U.SEQ_END_TERMINA
    LEFT JOIN CONTAMOV MOV ON MOV.NUMEROCM = U.CODTERMINAL
    WHERE
    U.CHAVEACESSO IS NOT NULL
    AND (U.CODTERMINAL NOT IN (80861,28910))
),
REF2 AS (
    SELECT
    X.CHAVEACESSO,
    X.REF AS REF2,
    COALESCE(ENDERECO.NOME,CONTAMOV.NOME) AS TERMINAL2,
    X.STATUS AS STATUS2,
    X.PORIGEM AS PESO2,
    X.PLIQUIDO AS PESOLIQ2,
    X.QUEBRA_SOBRA AS QUEBRA2,
    X.RETENCAO AS RET2
    FROM U_DESCARGA_TRADING X
    LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM = X.CODTERMINAL
        AND ENDERECO.SEQENDERECO = X.SEQ_END_TERMINA
    LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = X.CODTERMINAL
    WHERE
    X.CODTERMINAL IN (80861,28910)
    AND X.CHAVEACESSO IS NOT NULL
)
SELECT
D.CHAVEACESSONFE,
D.QTD_NOTA, 
REF1.ESTAB,
REF1.NF,
REF1.REF1,
REF1.DTDESCARGA,
REF1.CLIENTE,
REF1.TERMINAL1,
REF1.STATUS1,
REF1.PESO1,
REF1.PESOLIQ1,
REF1.QUEBRA1,
REF1.RET1,
REF2.TERMINAL2,
REF2.REF2,
REF2.STATUS2,
REF2.PESO2,
REF2.PESOLIQ2,
REF2.QUEBRA2,
REF2.RET2,
REF1.SCCT,
REF1.AFCCT,
REF1.DTCCT,
D.NF_CD, 
D.NF_QB, 
D.NF_RET,
NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) AS DIF_APARTIR,
D.QTD_NOTA - NVL(REF1.PESO1,0) AS DIF_QTD,
D.NF_CD + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0) AS DIF_QDC,
CASE WHEN D.NF_QB > NVL(REF1.RET1,0) THEN 0 ELSE D.QTD_NOTA - D.NF_CD - NVL(REF1.RET1,0) - D.NF_RET END S_UTIL,
CASE
    WHEN NVL(REF1.SCCT,0) = 0 THEN 'Consultar CCT'
    WHEN NVL(REF1.SCCT,0) >= (D.NF_CD + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0)) THEN 'Saldo OK'
    WHEN NVL(REF1.SCCT,0) < (D.NF_CD + NVL(REF1.QUEBRA1,0) + NVL(REF2.QUEBRA2,0)) THEN 'Saldo Verificar'
END DIF_CCT
FROM DESCARGA D

LEFT JOIN REF1 ON REF1.CHAVEACESSO = D.CHAVEACESSONFE
LEFT JOIN REF2 ON REF2.CHAVEACESSO = D.CHAVEACESSONFE
WHERE
(
    (NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) > 0 AND :DIF = 1)
    OR
     (NVL(D.NF_RET + D.NF_QB + D.NF_CD - D.QTD_NOTA,0) = 0 AND :DIF = 2)
     OR
     :DIF = 3
)