SELECT
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
CONTRATO.CONTRATO,
ITEMAGRO.ITEM AS COD_ITEM,
u_agrprodgr.descagrupa AS PRODUTO,
CONTAMOV.NOME AS CLIENTE,
COALESCE(ENDALT.CNPJF,CONTAMOV.CNPJF) AS CNPJF,
CONTRATO.CONTCONF,
CONTRATO.PRIORIDADE,
TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY')DTEMISSAO,
TO_CHAR(CONTRATO_U.DTINICIOENT, 'DD/MM/YYYY') DTINICIOENT,
TO_CHAR(contrato.dtlimentimp,'DD/MM/YYYY')AS lIMITE_ENT,
TO_CHAR(contrato.dtvencto,'DD/MM/YYYY')AS dtvencto ,
contrato_u.tipofretes,
contrato_u.tipopgto,
contrato_u.statusass,
contrato_u.notaconf,
CASE WHEN contrato.seqendentrega IS NULL THEN (CONTAMOV.ENDERECO||', '||CONTAMOV.BAIRRO)
ELSE   (ENDERECO.ENDERECO||', '||ENDERECO.BAIRRO) END ENDERECO,
PESSENT.NOME AS PESSOA_ENTREGA,
CID_ENT.NOME AS CID_PESSENTREGA,
UF.CODIGO || LPAD(CID_ENT.IBGE, 7 - LENGTH(UF.CODIGO), '0') AS COD_IBGE,
--CONSULTOR.NOME AS CONSULTOR,
--CONSULTOR.NUMEROCM AS COD_CONSULTOR,
contrato.pessentrega,
contrato.seqendentrega,
contrato.pessretirada,
contrato.seqendretirada,
PESS_RET.NOME AS PESSOA_RETIRADA,
CID_RET.NOME AS CID_RETIRADA,
NVL((SELECT SUM(QUANTIDADE) FROM NFITEM
JOIN NFCAB ON (NFCAB.SEQNOTA = NFITEM.SEQNOTA AND NFITEM.ESTAB = NFCAB.ESTAB)
WHERE NFITEM.CONTRATO = CONTRATO.CONTRATO AND NFITEM.ESTAB = FILIAL.ESTAB AND TO_DATE(NFCAB.DTEMISSAO, 'DD/MM/YY')= TO_DATE(CURRENT_DATE, 'DD/MM/YY')),0) AS QTDPDIA,

ARREDONDAR(CONTRATOITE.QUANTIDADE,2)QTD,
--(ARREDONDAR(CONTRATOITE.QUANTIDADE,2) - ARREDONDAR(PSALDO.NQTDCANC,2) - ARREDONDAR(PSALDO.NQTDDEV,2) )QTD,
ARREDONDAR(PSALDO.NQTDCANC,2) as QTDCANC,
ARREDONDAR(PSALDO.NQTDDEV,2) AS QTDDEV,
ARREDONDAR(PSALDO.NQTDBX,2)AS ENTREGUE,
ARREDONDAR(PSALDO.NQTDSALDO,2) AS SALDO,
TO_CHAR(CONTRATO.DTMOVSALDO, 'DD/MM/YY') AS DTMOVSALDO,
TO_CHAR(CONTRATO.DTLIMLIQIMP, 'DD/MM/YY') AS DTLIMLIQIMP,
TO_CHAR(CONTRATO_U.DTPOSTERGACAO, 'DD/MM/YY') AS DTPOSTERGACAO,
LISTAGG(TO_CHAR(CONTRATODTVENCTO.DTVENCTO, 'DD/MM/YY')||'; ') AS DTFLUXOFIXA,
CONTRATODTVENCTO.NUMDIASPAGTO AS DTFLUXODIAS,
CONTRATO.NUMCOMPRADOR

/*(ARREDONDAR(DIVIDE(CONTRATOITE.QUANTIDADE,60),2) -   ARREDONDAR(DIVIDE(PSALDO.NQTDCANC,60),2)  -  ARREDONDAR(DIVIDE(PSALDO.NQTDDEV,60),2)  )   QTD_SC,
ARREDONDAR(DIVIDE(PSALDO.NQTDCANC,60),2) as QTDCANC,
ARREDONDAR(DIVIDE(PSALDO.NQTDDEV,60),2) AS QTDDEV,
ARREDONDAR(DIVIDE(PSALDO.NQTDBX,60),2) AS ENTREGUE,
ARREDONDAR(DIVIDE(PSALDO.NQTDSALDO,60),2) AS SALDO*/
FROM CONTRATO

INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB

INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

INNER JOIN CONTRATOITE ON CONTRATOITE.ESTAB = CONTRATO.ESTAB
                    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO

LEFT JOIN CONTRATO_U ON CONTRATO_U.ESTAB = CONTRATO.ESTAB
                    AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO
                    
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM

LEFT JOIN ENDERECO ENDALT ON ENDALT.NUMEROCM = CONTRATO.NUMEROCM AND ENDALT.seqendereco = CONTRATO.ENDALTERNATIVO

INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
 
LEFT JOIN ENDERECO ON ENDERECO.NUMEROCM = CONTRATO.PESSENTREGA
                AND endereco.seqendereco = contrato.seqendentrega
                
LEFT JOIN CONTAMOV PESSENT ON PESSENT.NUMEROCM = CONTRATO.PESSENTREGA

/*LEFT JOIN CONTRATOCOM ON CONTRATOCOM.ESTAB = CONTRATO.ESTAB
                    AND CONTRATOCOM.CONTRATO = CONTRATO.CONTRATO
                    
LEFT JOIN CONTAMOV CONSULTOR ON CONSULTOR.NUMEROCM = CONTRATOCOM.NUMEROCM*/

INNER JOIN TABLE (PCONTRATOSALDO( CONTRATOITE.ESTAB,
                 CURRENT_DATE, CONTRATOITE.CONTRATO, CONTRATOITE.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
    
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM

LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM

LEFT JOIN U_AGRPRODGR ON u_agrprodgr.u_agrprodgr_id = itemagro_u.u_agrprodgr_id

LEFT JOIN CIDADE CID_ENT ON CID_ENT.CIDADE = COALESCE(ENDERECO.CIDADE,PESSENT.CIDADE)
LEFT JOIN UF ON UF.UF = CID_ENT.UF

LEFT JOIN ENDERECO END_RET ON END_RET.NUMEROCM = contrato.pessretirada
                AND END_RET.seqendereco = contrato.seqendretirada
                
LEFT JOIN CONTAMOV PESS_RET ON PESS_RET.NUMEROCM = contrato.pessretirada

LEFT JOIN CIDADE CID_RET ON CID_RET.CIDADE = COALESCE(END_RET.CIDADE,PESS_RET.CIDADE)

LEFT JOIN CONTRATODTVENCTO ON CONTRATODTVENCTO.CONTRATO = CONTRATO.CONTRATO
                        AND CONTRATODTVENCTO.ESTAB = CONTRATO.ESTAB

WHERE ARREDONDAR(PSALDO.NQTDSALDO,0) >0 
AND CONTRATO.CONTCONF NOT IN (24,25,51,23,52)
AND CONTRATOCFG.ENTRADASAIDA = 'S'
--AND CONTRATO.PESSENTREGA IS NOT NULL
AND contrato.dtlimentimp BETWEEN '01/01/2000' AND :DTFIN

<#if UF?has_content>
AND CIDADE.UF IN (:UF)
 </#if>
 
 <#if ITEM?has_content>
 AND u_agrprodgr.u_agrprodgr_id IN (:ITEM)
 </#if>
GROUP BY 
FILIAL.ESTAB,
FILIAL.REDUZIDO,
CONTRATO.CONTRATO,
ITEMAGRO.ITEM,
u_agrprodgr.descagrupa,
CONTAMOV.NOME,
CONTRATO.CONTCONF,
CONTRATO.PRIORIDADE,
CONTRATO.DTEMISSAO,
CONTRATO_U.DTINICIOENT,
contrato.dtlimentimp,
contrato.dtvencto,
contrato_u.tipofretes,
contrato_u.tipopgto,
contrato_u.statusass,
contrato_u.notaconf,
contrato.seqendentrega,
CONTAMOV.ENDERECO,
CONTAMOV.BAIRRO,
ENDERECO.ENDERECO,
ENDERECO.BAIRRO,
PESSENT.NOME,
CID_ENT.NOME,
contrato.pessentrega,
contrato.seqendentrega,
contrato.pessretirada,
contrato.seqendretirada,
PESS_RET.NOME,
CID_RET.NOME,
CONTRATOITE.QUANTIDADE,
PSALDO.NQTDCANC,
PSALDO.NQTDDEV,
PSALDO.NQTDBX,
PSALDO.NQTDSALDO,
CONTRATO.DTMOVSALDO, 
CONTRATO.DTLIMLIQIMP,
CONTRATO_U.DTPOSTERGACAO,
CONTRATODTVENCTO.NUMDIASPAGTO ,
CONTRATO.NUMCOMPRADOR,
CID_ENT.IBGE,
UF.CODIGO,
ENDALT.CNPJF,
CONTAMOV.CNPJF

