WITH CONVERSAO AS (
    SELECT 
    *
    FROM 
    (
        SELECT moedaval.*,
               ROW_NUMBER() OVER (PARTITION BY moeda ORDER BY data DESC) AS rn
        FROM moedaval
    )dados
    WHERE rn = 1
)

select
*
from(
SELECT
    /* ESTAB */
    FILIAL.ESTAB,
    FILIAL.REDUZIDO AS ESTAB_COMPLETO,
    /* CONTRATO */
    CONTRATO.CONTRATO AS CTR_SEQ,
    CONTRATO.NUMCOMPRADOR AS CTR_CN,
    CONTRATO.CONTCONF ||' - '|| CONTRATOCFG.DESCRICAO AS CTR_CONFIG,
    CASE WHEN CONTRATOCFG.ENTRADASAIDA = 'S' THEN 'CONTRATO DE VENDA' ELSE 'CONTRATO DE COMPRA' END AS CTR_TIPO,
    CONTRATO.DTEMISSAO,
    CASE
        WHEN CONTRATO_U.TIPOPGTO ='AVISTA' THEN 'A VISTA'
        WHEN CONTRATO_U.TIPOPGTO ='5DIAUTIL' THEN '5º DIA ÚTIL DO MÊS SUBSEQUENTE AO MÊS DA ENTREGA'
        WHEN CONTRATO_U.TIPOPGTO ='SOBRERODAS' THEN 'APÓS O CARREGAMENTO'
        WHEN CONTRATO_U.TIPOPGTO ='ANTECIPADO' THEN 'ANTECIPADO - '||TO_CHAR(CONTRATODTVENCTO.DTVENCTO,'DD/MM/YYYY')
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOCTR' THEN   NUMDIASPAGTO||'DIAS DA EMISSÃO DO CONTRATO'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOAMOSTRA' THEN NUMDIASPAGTO||' DIAS DA ENTREGA DA CARGA DE AMOSTRA'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOEMBARQUE' THEN NUMDIASPAGTO||' DIAS DO CARREGAMENTO DA MERCADORIA'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZODESCARGA' THEN NUMDIASPAGTO||' DIAS DA ENTREGA DA MERCADORIA'
        WHEN CONTRATODTVENCTO.DTVENCTO IS NULL THEN  NUMDIASPAGTO||'DIAS'
        ELSE TO_CHAR(CONTRATODTVENCTO.DTVENCTO,'DD/MM/YYYY')
    END DTPGTO,
    CONTRATO.DTVENCTO,
    CONTRATO.DTMOVSALDO AS CTR_DT_VIG_INI,
    CONTRATO.DATALIMITEENT AS CTR_DT_VIG_FIN,
    SAFRAS.DESCRICAO AS CTR_SAFRA,
    /* PESSOA */
    CONTAMOV.NUMEROCM,
    CONTAMOV.NUMEROCM ||' - '|| CONTAMOV.NOME AS PESSOA,
    /* ITEM */
    ITEMAGRO.ITEM,
    ITEMAGRO.ITEM ||' - '|| ITEMAGRO.DESCRICAO AS PRODUTO,
    /* SALDO QUANTIDADE */
    CONTRATOITE.QUANTIDADE AS Q_QUANTIDADE,
    CONTRATOITE.VALORUNIT,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.NOTACONF NOT IN (291)
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO IN ('N','X','A','T')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_BAIXADO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN CONTRATO ON
            CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND
            CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
            INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
            INNER JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id AND
            u_tipoctr.u_tipoctr_id NOT IN (11)
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO = 'D'
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_DEVOLVIDO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATOCANC.QUANTIDADE),0) FROM CONTRATOCANC
            WHERE CONTRATOCANC.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATOCANC.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATOCANC.SEQITEM  = CONTRATOITE.SEQITEM),0) +
            COALESCE((SELECT COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.NOTACONF IN (291)
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO IN ('N','X','A')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_CANCELADO,
    /* SALDO VALOR */
    CONTRATOITE.VALORTOTAL *coalesce(CONVERSAO.valor,1) AS V_VALORTOTAL,
    COALESCE((SELECT
                    COALESCE(SUM(CONTRATONFITE.VALOR),0) FROM CONTRATONFITE
        
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.NOTACONF NOT IN (291)
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO IN ('N','X','A','T')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','V'))
    ,0) AS V_BAIXADO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.VALOR),0) FROM CONTRATONFITE
            INNER JOIN CONTRATO ON
            CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND
            CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
            INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
            INNER JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id AND
            u_tipoctr.u_tipoctr_id NOT IN (11)
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO = 'D'
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','V'))
    ,0) AS V_DEVOLVIDO,
    COALESCE((SELECT
                    COALESCE(SUM(CONTRATOCANC.VALOR),0) FROM CONTRATOCANC
            WHERE CONTRATOCANC.ESTAB = CONTRATOITE.ESTAB
                AND CONTRATOCANC.CONTRATO = CONTRATOITE.CONTRATO
                AND CONTRATOCANC.SEQITEM  = CONTRATOITE.SEQITEM),0) +
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.VALOR),0)
            FROM CONTRATONFITE
            INNER JOIN NFITEM
                ON NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA
                AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA
                AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB
                ON NFCAB.ESTAB = NFITEM.ESTAB
                AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG
                ON NFCFG.NOTACONF = NFCAB.NOTACONF
                AND NFCFG.NOTACONF IN (291)
            INNER JOIN NATOPERACAO NAT
                ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
                AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
                AND NAT.TIPODCTO IN ('N','X','A')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
                AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
                AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
                AND CONTRATONFITE.TIPOBAIXA IN ('A','V'))
    ,0) AS V_CANCELADO,
    CONTRATO_U.STATUSASS,
    CONTRATO_U.STATUSAPROV,
    CONTRATO_U.STATUSFAT,
    CONTRATO_U.TIPOFRETES
FROM CONTRATO
INNER JOIN FILIAL
    ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CONTRATOCFG
    ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTAMOV
    ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
INNER JOIN CONTRATOITE
    ON CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
INNER JOIN ITEMAGRO
    ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
INNER JOIN SAFRAS
    ON SAFRAS.SAFRA = CONTRATO.SAFRA
LEFT JOIN CONTRATO_U
    ON CONTRATO_U.ESTAB = CONTRATO.ESTAB
    AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO
LEFT JOIN CONTRATODTVENCTO
    ON CONTRATODTVENCTO.ESTAB = CONTRATO.ESTAB
    AND CONTRATODTVENCTO.CONTRATO = CONTRATO.CONTRATO
    AND ((CONTRATO_U.TIPOPGTO = 'ANTECIPADO')
    OR (CONTRATO_U.TIPOPGTO IN ('APRAZO','APRAZOCTR','APRAZOAMOSTRA','APRAZOEMBARQUE','APRAZODESCARGA')))
INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
 
LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id    
LEFT JOIN CONVERSAO ON
        CONVERSAO.MOEDA = CONTRATO.MOEDA
    
 WHERE CONTRATO.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
 AND $X{IN,CONTRATO.NUMEROCM,PRODUTOR}
 AND $X{IN,CONTRATO.ESTAB,ESTAB}
 AND $X{IN,CONTRATOITE.ITEM,ITEM} 
 AND (CONTRATO.CONTRATO = $P{CONTRATO} OR 0 = $P{CONTRATO})
 and u_tipoctr.u_tipoctr_id not in (11)
--ORDER BY
--CONTRATO.ESTAB,
--CONTRATO.CONTRATO

UNION ALL

SELECT
    /* ESTAB */
    FILIAL.ESTAB,
    FILIAL.REDUZIDO AS ESTAB_COMPLETO,
    /* CONTRATO */
    CONTRATO.CONTRATO AS CTR_SEQ,
    CONTRATO.NUMCOMPRADOR AS CTR_CN,
    CONTRATO.CONTCONF ||' - '|| CONTRATOCFG.DESCRICAO AS CTR_CONFIG,
    CASE WHEN CONTRATOCFG.ENTRADASAIDA = 'S' THEN 'CONTRATO DE VENDA' ELSE 'CONTRATO DE COMPRA' END AS CTR_TIPO,
    CONTRATO.DTEMISSAO,
    CASE
        WHEN CONTRATO_U.TIPOPGTO ='AVISTA' THEN 'A VISTA'
        WHEN CONTRATO_U.TIPOPGTO ='5DIAUTIL' THEN '5º DIA ÚTIL DO MÊS SUBSEQUENTE AO MÊS DA ENTREGA'
        WHEN CONTRATO_U.TIPOPGTO ='SOBRERODAS' THEN 'APÓS O CARREGAMENTO'
        WHEN CONTRATO_U.TIPOPGTO ='ANTECIPADO' THEN 'ANTECIPADO - '||TO_CHAR(CONTRATODTVENCTO.DTVENCTO,'DD/MM/YYYY')
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOCTR' THEN   NUMDIASPAGTO||'DIAS DA EMISSÃO DO CONTRATO'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOAMOSTRA' THEN NUMDIASPAGTO||' DIAS DA ENTREGA DA CARGA DE AMOSTRA'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZOEMBARQUE' THEN NUMDIASPAGTO||' DIAS DO CARREGAMENTO DA MERCADORIA'
        WHEN CONTRATO_U.TIPOPGTO ='APRAZODESCARGA' THEN NUMDIASPAGTO||' DIAS DA ENTREGA DA MERCADORIA'
        WHEN CONTRATODTVENCTO.DTVENCTO IS NULL THEN  NUMDIASPAGTO||'DIAS'
        ELSE TO_CHAR(CONTRATODTVENCTO.DTVENCTO,'DD/MM/YYYY')
    END DTPGTO,
    CONTRATO.DTVENCTO,
    CONTRATO.DTMOVSALDO AS CTR_DT_VIG_INI,
    CONTRATO.DATALIMITEENT AS CTR_DT_VIG_FIN,
    SAFRAS.DESCRICAO AS CTR_SAFRA,
    /* PESSOA */
    CONTAMOV.NUMEROCM,
    CONTAMOV.NUMEROCM ||' - '|| CONTAMOV.NOME AS PESSOA,
    /* ITEM */
    ITEMAGRO.ITEM,
    ITEMAGRO.ITEM ||' - '|| ITEMAGRO.DESCRICAO AS PRODUTO,
    /* SALDO QUANTIDADE */
    CONTRATOITE.QUANTIDADE AS Q_QUANTIDADE,
    CONTRATOITE.VALORUNIT,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN CONTRATO ON
            CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND
            CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
            INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
            INNER JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id AND
            u_tipoctr.u_tipoctr_id IN (11)            
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.NOTACONF NOT IN (291)
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO IN ('D')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_BAIXADO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN CONTRATO ON
            CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND
            CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
            INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
            INNER JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id AND
            u_tipoctr.u_tipoctr_id NOT IN (11)
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO = 'D'
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_DEVOLVIDO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATOCANC.QUANTIDADE),0) FROM CONTRATOCANC
            WHERE CONTRATOCANC.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATOCANC.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATOCANC.SEQITEM  = CONTRATOITE.SEQITEM),0) +
            COALESCE((SELECT COALESCE(SUM(CONTRATONFITE.QUANTIDADE),0) FROM CONTRATONFITE
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.NOTACONF IN (291)
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO IN ('N','X','A')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','Q'))
    ,0) AS Q_CANCELADO,
    /* SALDO VALOR */
    CONTRATOITE.VALORTOTAL *coalesce(CONVERSAO.valor,1) AS V_VALORTOTAL,
    0 AS V_BAIXADO,
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.VALOR),0) FROM CONTRATONFITE
            INNER JOIN CONTRATO ON
            CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND
            CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
            INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
            INNER JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id AND
            u_tipoctr.u_tipoctr_id NOT IN (11)            
            INNER JOIN NFITEM ON
            NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND
            NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND
            NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB AND
            NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG ON
            NFCFG.NOTACONF = NFCAB.NOTACONF
            INNER JOIN NATOPERACAO NAT ON
            NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND
            NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA AND
            NAT.TIPODCTO = 'D'
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
            AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
            AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
            AND CONTRATONFITE.TIPOBAIXA IN ('A','V'))
    ,0) AS V_DEVOLVIDO,
    COALESCE((SELECT
                    COALESCE(SUM(CONTRATOCANC.VALOR),0) FROM CONTRATOCANC
            WHERE CONTRATOCANC.ESTAB = CONTRATOITE.ESTAB
                AND CONTRATOCANC.CONTRATO = CONTRATOITE.CONTRATO
                AND CONTRATOCANC.SEQITEM  = CONTRATOITE.SEQITEM),0) +
    COALESCE((SELECT
                COALESCE(SUM(CONTRATONFITE.VALOR),0)
            FROM CONTRATONFITE
            INNER JOIN NFITEM
                ON NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA
                AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA
                AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
            INNER JOIN NFCAB
                ON NFCAB.ESTAB = NFITEM.ESTAB
                AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
            INNER JOIN NFCFG
                ON NFCFG.NOTACONF = NFCAB.NOTACONF
                AND NFCFG.NOTACONF IN (291)
            INNER JOIN NATOPERACAO NAT
                ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
                AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
                AND NAT.TIPODCTO IN ('N','X','A')
            WHERE CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
                AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
                AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM
                AND CONTRATONFITE.TIPOBAIXA IN ('A','V'))
    ,0) AS V_CANCELADO,
    CONTRATO_U.STATUSASS,
    CONTRATO_U.STATUSAPROV,
    CONTRATO_U.STATUSFAT,
    CONTRATO_U.TIPOFRETES
FROM CONTRATO
INNER JOIN FILIAL
    ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CONTRATOCFG
    ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTAMOV
    ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
INNER JOIN CONTRATOITE
    ON CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
INNER JOIN ITEMAGRO
    ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
INNER JOIN SAFRAS
    ON SAFRAS.SAFRA = CONTRATO.SAFRA
LEFT JOIN CONTRATO_U
    ON CONTRATO_U.ESTAB = CONTRATO.ESTAB
    AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO
LEFT JOIN CONTRATODTVENCTO
    ON CONTRATODTVENCTO.ESTAB = CONTRATO.ESTAB
    AND CONTRATODTVENCTO.CONTRATO = CONTRATO.CONTRATO
    AND ((CONTRATO_U.TIPOPGTO = 'ANTECIPADO')
    OR (CONTRATO_U.TIPOPGTO IN ('APRAZO','APRAZOCTR','APRAZOAMOSTRA','APRAZOEMBARQUE','APRAZODESCARGA')))
INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id 
LEFT JOIN CONVERSAO ON
        CONVERSAO.MOEDA = CONTRATO.MOEDA
        
 WHERE CONTRATO.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
 AND $X{IN,CONTRATO.NUMEROCM,PRODUTOR}
 AND $X{IN,CONTRATO.ESTAB,ESTAB}
 AND $X{IN,CONTRATOITE.ITEM,ITEM} 
 AND (CONTRATO.CONTRATO = $P{CONTRATO} OR 0 = $P{CONTRATO})
 and u_tipoctr.u_tipoctr_id in (11)
 
 )DADOS
ORDER BY
ESTAB,
CTR_SEQ