WITH SALDO_TEMP AS (
SELECT  
    NFCAB_A.NUMEROCM,
    NFITEM.ESTAB,
    NFITEM.SEQNOTA,
    NFITEM.SEQNOTAITEM,
    SUM((NFITEM.QUANTIDADE +                
                COALESCE((SELECT SUM(NFITEMTRANSF_TR.QTDETRANSF)
                          FROM NFITEMTRANSF NFITEMTRANSF_TR
                        WHERE (NFITEMTRANSF_TR.ESTAB = NFITEM.ESTAB)
                          AND (NFITEMTRANSF_TR.SEQNOTA = NFITEM.SEQNOTA)
                          AND (NFITEMTRANSF_TR.SEQNOTAITEM = NFITEM.SEQNOTAITEM)
                          AND (NFITEMTRANSF_TR.DESTINATARIO = NFCAB_A.NUMEROCM)
                          AND (NOT EXISTS
                              (SELECT NFITEMAPARTIRDE_TR.*
                                 FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_TR
                               WHERE (NFITEMAPARTIRDE_TR.ESTABORIGEM = NFITEMTRANSF_TR.ESTAB)
                                 AND (NFITEMAPARTIRDE_TR.SEQNOTAORIGEM = NFITEMTRANSF_TR.SEQNOTA)
                                 AND (NFITEMAPARTIRDE_TR.SEQNOTAITEMORIGEM = NFITEMTRANSF_TR.SEQNOTAITEM)
                                 AND (NFITEMAPARTIRDE_TR.SEQTRANSF = NFITEMTRANSF_TR.SEQTRANSF)
                                 AND (COALESCE(NFITEMAPARTIRDE_TR.SEQTRANSF, 0) <> 0)))),0)
                 )
                 -
                 (
             COALESCE((SELECT SUM(NFITEMAPARTIRDE_X.QUANTIDADE)
                  FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_X
                  LEFT JOIN NFCAB NFCAB_X
                   ON (NFCAB_X.ESTAB = NFITEMAPARTIRDE_X.ESTAB)
                  AND (NFCAB_X.SEQNOTA = NFITEMAPARTIRDE_X.SEQNOTA)
                  LEFT JOIN NFCFG NFCFG_X
                   ON (NFCFG_X.NOTACONF = NFCAB_X.NOTACONF)
                  LEFT JOIN NATOPERACAO NATOPERACAO_X
                   ON (NATOPERACAO_X.NATUREZADAOPERACAO = NFCFG_X.NATUREZADAOPERACAO)
                  AND (NATOPERACAO_X.ENTRADASAIDA = NFCFG_X.ENTRADASAIDA)
                WHERE (NFITEMAPARTIRDE_X.ESTABORIGEM = NFITEM.ESTAB)
                  AND (NFITEMAPARTIRDE_X.SEQNOTAORIGEM = NFITEM.SEQNOTA)
                  AND (NFITEMAPARTIRDE_X.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
                  AND (COALESCE(NFITEMAPARTIRDE_X.SEQTRANSF, 0) = 0)
                  AND (NFCAB_X.NUMEROCM = NFCAB_A.NUMEROCM)
                  AND (NATOPERACAO_X.TIPODCTO IN ('X','N') )),0)
                +
               COALESCE((SELECT SUM(NFITEMAPARTIRDE_X.QUANTIDADE) +
                                SUM(NVLF0(NFITEMAPARTIRDE_X.QTDEARMAZENAGEM)) +
                                SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOSEGURO)) +
                                SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOQUEBRA)) +
                                SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOEXPED))+
                                SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOFINALIDADE))
                  FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_X
                  LEFT JOIN NFCAB NFCAB_X
                   ON (NFCAB_X.ESTAB = NFITEMAPARTIRDE_X.ESTAB)
                  AND (NFCAB_X.SEQNOTA = NFITEMAPARTIRDE_X.SEQNOTA)
                  LEFT JOIN NFCFG NFCFG_X
                   ON (NFCFG_X.NOTACONF = NFCAB_X.NOTACONF)
                  LEFT JOIN NATOPERACAO NATOPERACAO_X
                   ON (NATOPERACAO_X.NATUREZADAOPERACAO = NFCFG_X.NATUREZADAOPERACAO)
                  AND (NATOPERACAO_X.ENTRADASAIDA = NFCFG_X.ENTRADASAIDA)
                WHERE (NFITEMAPARTIRDE_X.ESTABORIGEM = NFITEM.ESTAB)
                  AND (NFITEMAPARTIRDE_X.SEQNOTAORIGEM = NFITEM.SEQNOTA)
                  AND (NFITEMAPARTIRDE_X.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
                  AND (COALESCE(NFITEMAPARTIRDE_X.SEQTRANSF, 0) = 0)
                  AND (NATOPERACAO_X.TIPODCTO = 'D')),0)
              +
               COALESCE((SELECT SUM(NFITEMTRANSF_TC.QTDETRANSF)
                            FROM NFITEMTRANSF NFITEMTRANSF_TC
                          WHERE (NFITEMTRANSF_TC.ESTAB = NFITEM.ESTAB)
                            AND (NFITEMTRANSF_TC.SEQNOTA = NFITEM.SEQNOTA)
                            AND (NFITEMTRANSF_TC.SEQNOTAITEM = NFITEM.SEQNOTAITEM)
                            AND (NFITEMTRANSF_TC.CEDENTE = NFCAB_A.NUMEROCM)
                            AND (NOT EXISTS
                                (SELECT NFITEMAPARTIRDE_TC.*
                                   FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_TC
                                   LEFT JOIN NFCAB NFCAB_X
                                     ON (NFCAB_X.ESTAB = NFITEMAPARTIRDE_TC.ESTABORIGEM)
                                    AND (NFCAB_X.SEQNOTA = NFITEMAPARTIRDE_TC.SEQNOTAORIGEM)
                                   LEFT JOIN NFCFG NFCFG_X
                                    ON (NFCFG_X.NOTACONF = NFCAB_X.NOTACONF)
                                   LEFT JOIN NATOPERACAO NATOPERACAO_X
                                     ON (NATOPERACAO_X.NATUREZADAOPERACAO = NFCFG_X.NATUREZADAOPERACAO)
                                    AND (NATOPERACAO_X.ENTRADASAIDA = NFCFG_X.ENTRADASAIDA)
                                 WHERE (NFITEMAPARTIRDE_TC.ESTABORIGEM = NFITEMTRANSF_TC.ESTAB)
                                   AND (NFITEMAPARTIRDE_TC.SEQNOTAORIGEM = NFITEMTRANSF_TC.SEQNOTA)
                                   AND (NFITEMAPARTIRDE_TC.SEQNOTAITEMORIGEM = NFITEMTRANSF_TC.SEQNOTAITEM)
                                   AND (NFITEMAPARTIRDE_TC.SEQTRANSF = NFITEMTRANSF_TC.SEQTRANSF)
                                   AND (COALESCE(NFITEMAPARTIRDE_TC.SEQTRANSF, 0) <> 0)
                                   AND (NATOPERACAO_X.TIPODCTO = 'D')))),0)
              )) AS SALDO
FROM (
        SELECT NFCAB_A.ESTAB, NFCAB_A.SEQNOTA, NFCAB_A.NUMEROCM, NFCFG_NOTA.NATUREZADAOPERACAO, NFCFG_NOTA.ENTRADASAIDA 
          FROM NFCAB NFCAB_A
          LEFT JOIN NFCFG NFCFG_NOTA ON (NFCFG_NOTA.NOTACONF = NFCAB_A.NOTACONF)
              INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB_A.ESTAB
             INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
         WHERE (COALESCE(NFCAB_A.STATUS, 'N') <> 'C')
           AND (NFCFG_NOTA.ENTRADASAIDA = 'E')
             AND CIDADE.UF = 'SP'
     ) NFCAB_A   
LEFT JOIN NFITEM
       ON (NFITEM.ESTAB = NFCAB_A.ESTAB)
      AND (NFITEM.SEQNOTA = NFCAB_A.SEQNOTA)
      


GROUP BY NFCAB_A.SEQNOTA,
         NFCAB_A.NUMEROCM,
         NFITEM.ESTAB,
         NFITEM.SEQNOTA,
         NFITEM.SEQNOTAITEM
)

-- ===============================
-- BLOCO DV
-- ===============================

SELECT 'DV' AS TIPO,  
       NFITEMPGSERVICO.ESTAB, 
       CONTAMOV.NUMEROCM, 
       NFITEMTXSERVICO.SERVICO,
       ITEMAGRONF.ITEM AS ITEM, 
       ROMA.ROMANEIO 
               
FROM NFITEMPGSERVICO, NFITEMTXSERVICO, NFITEM NFITEM_DEV, 
     NFITEM NFITEM_DEP, NFCAB NFCAB_DEP, ENDERECO, CONTAMOV, 
     ITEMAGRO ITEMAGROSERVICO, ITEMAGRO ITEMAGRONF, 
     ITEMAGROESTAB ITEMAGROESTAB_DEP, NFCABROMA, ROMA, RETENPORTO
WHERE (NFITEMTXSERVICO.ESTAB = NFITEMPGSERVICO.ESTAB)
  AND (NFITEMTXSERVICO.SEQNOTA = NFITEMPGSERVICO.SEQNOTADEP)
  AND (NFITEMTXSERVICO.SEQNOTAITEM = NFITEMPGSERVICO.SEQNOTAITEMDEP)
  AND (NFITEMTXSERVICO.SEQUENCIA = NFITEMPGSERVICO.SEQUENCIA)
  AND (NFITEM_DEV.ESTAB = NFITEMPGSERVICO.ESTABDEV)
  AND (NFITEM_DEV.SEQNOTA = NFITEMPGSERVICO.SEQNOTADEV)
  AND (NFITEM_DEV.SEQNOTAITEM = NFITEMPGSERVICO.SEQNOTAITEMDEV)
  AND (NFITEM_DEP.ESTAB = NFITEMTXSERVICO.ESTAB)
  AND (NFITEM_DEP.SEQNOTA = NFITEMTXSERVICO.SEQNOTA)
  AND (NFITEM_DEP.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM)
  AND (NFCAB_DEP.ESTAB = NFITEM_DEP.ESTAB)
  AND (NFCAB_DEP.SEQNOTA = NFITEM_DEP.SEQNOTA)
  AND (NFCAB_DEP.NUMEROCM = ENDERECO.NUMEROCM(+))
  AND (NFCAB_DEP.SEQENDERECO = ENDERECO.SEQENDERECO(+))
  AND (CONTAMOV.NUMEROCM = NFCAB_DEP.NUMEROCM)
  AND (NFITEMTXSERVICO.SERVICO = ITEMAGROSERVICO.ITEM)
  AND (ITEMAGRONF.ITEM = NFITEM_DEP.ITEM)
  AND (ITEMAGROESTAB_DEP.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (ITEMAGROESTAB_DEP.ITEM(+) = NFITEM_DEP.ITEM)
  AND (NFCABROMA.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (NFCABROMA.SEQNOTA(+) = NFITEM_DEP.SEQNOTA)
  AND (NFCABROMA.ROMANEIO(+) = NFITEM_DEP.ROMANEIO)
  AND (ROMA.ESTAB(+) = NFCABROMA.ESTAB)
  AND (ROMA.ROMANEIO(+) = NFCABROMA.ROMANEIO)
  AND (ROMA.NUMEROCM(+) = NFCABROMA.NUMEROCM)
  AND (ROMA.ENTRADASAIDA(+) = NFCABROMA.ENTRADASAIDA)
  AND (RETENPORTO.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (RETENPORTO.SEQNOTA(+) = NFITEM_DEP.SEQNOTA)
  AND (RETENPORTO.SEQNOTAITEM(+) = NFITEM_DEP.SEQNOTAITEM)
  AND (RETENPORTO.ITEM(+) = NFITEM_DEP.ITEM)
  AND (RETENPORTO.TRANSACAO(+) = 'E')
  and NFITEMTXSERVICO.SERVICO = 30
  AND 1 = 1
  AND (NFITEMPGSERVICO.SITUACAO = 'P')
  AND NOT EXISTS (SELECT 1 
                    FROM COBSERCONC 
                   WHERE COBSERCONC.ESTAB          = NFITEMPGSERVICO.ESTAB
                     AND COBSERCONC.SEQNOTADEP     = NFITEMPGSERVICO.SEQNOTADEP  
                     AND COBSERCONC.SEQNOTAITEMDEP = NFITEMPGSERVICO.SEQNOTAITEMDEP
                     AND COBSERCONC.SERVICO        = NFITEMTXSERVICO.SERVICO)

UNION 
-- ===============================
-- BLOCO DP
-- ===============================

SELECT 'DP' AS TIPO, 
       NFITEMTXSERVICO.ESTAB, 
       CONTAMOV.NUMEROCM, 
       NFITEMTXSERVICO.SERVICO,
       ITEMAGRONF.ITEM AS ITEM, 
       ROMA.ROMANEIO
            
FROM NFITEMTXSERVICO, NFITEM NFITEM_DEP, NFCAB NFCAB_DEP, 
     SALDO_TEMP, TRANSFPRODUTORES, NFITEM NFITEM_CED, ENDERECO,
     CONTAMOV, ITEMAGRO ITEMAGROSERVICO, ITEMAGRO ITEMAGRONF, 
     ITEMAGROESTAB ITEMAGROESTAB_DEP, TABPERSERVCAB, TABPRCSERVCAB,
     NFCABROMA, ROMA, RETENPORTO, NFITEMTXSERVPARCIAL
WHERE (NFITEM_DEP.ESTAB = NFITEMTXSERVICO.ESTAB)
  AND (NFITEM_DEP.SEQNOTA = NFITEMTXSERVICO.SEQNOTA)
  AND (NFITEM_DEP.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM)
  AND (NFCAB_DEP.ESTAB = NFITEM_DEP.ESTAB)
  AND (NFCAB_DEP.SEQNOTA = NFITEM_DEP.SEQNOTA)
  AND SALDO_TEMP.NUMEROCM = NFCAB_DEP.NUMEROCM
  AND SALDO_TEMP.ESTAB = NFITEM_DEP.ESTAB
  AND SALDO_TEMP.SEQNOTA = NFITEM_DEP.SEQNOTA
  AND SALDO_TEMP.SEQNOTAITEM = NFITEM_DEP.SEQNOTAITEM
  AND (TRANSFPRODUTORES.ESTABD(+) = NFITEMTXSERVICO.ESTAB)
  AND (TRANSFPRODUTORES.SEQNOTAD(+) = NFITEMTXSERVICO.SEQNOTA)
  AND (NFITEM_CED.ESTAB(+) = TRANSFPRODUTORES.ESTABC)
  AND (NFITEM_CED.SEQNOTA(+) = TRANSFPRODUTORES.SEQNOTAC)
  AND ((NFITEM_CED.SEQNOTA IS NULL) OR (NFITEM_CED.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM))
  AND (NFCAB_DEP.NUMEROCM = ENDERECO.NUMEROCM(+))
  AND (NFCAB_DEP.SEQENDERECO = ENDERECO.SEQENDERECO(+))
  AND (CONTAMOV.NUMEROCM = NFCAB_DEP.NUMEROCM)
  AND (NFITEMTXSERVICO.SERVICO = ITEMAGROSERVICO.ITEM)
  AND (ITEMAGRONF.ITEM = NFITEM_DEP.ITEM)
  AND (ITEMAGROESTAB_DEP.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (ITEMAGROESTAB_DEP.ITEM(+) = NFITEM_DEP.ITEM)
  AND (TABPERSERVCAB.TABELA(+) = NFITEMTXSERVICO.TABPERSERV)
  AND (TABPRCSERVCAB.TABELA(+) = NFITEMTXSERVICO.TABPRCSERV)
  AND (NFCABROMA.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (NFCABROMA.SEQNOTA(+) = NFITEM_DEP.SEQNOTA)
  AND (NFCABROMA.ROMANEIO(+) = NFITEM_DEP.ROMANEIO)
  AND (ROMA.ESTAB(+) = NFCABROMA.ESTAB)
  AND (ROMA.ROMANEIO(+) = NFCABROMA.ROMANEIO)
  AND (ROMA.NUMEROCM(+) = NFCABROMA.NUMEROCM)
  AND (ROMA.ENTRADASAIDA(+) = NFCABROMA.ENTRADASAIDA)
  AND (RETENPORTO.ESTAB(+) = NFITEM_DEP.ESTAB)
  AND (RETENPORTO.SEQNOTA(+) = NFITEM_DEP.SEQNOTA)
  AND (RETENPORTO.SEQNOTAITEM(+) = NFITEM_DEP.SEQNOTAITEM)
  AND (RETENPORTO.ITEM(+) = NFITEM_DEP.ITEM)
  AND (RETENPORTO.TRANSACAO(+) = 'E')
  AND (NFITEMTXSERVPARCIAL.ESTAB(+) = NFITEMTXSERVICO.ESTAB)
  AND (NFITEMTXSERVPARCIAL.SEQNOTA(+) = NFITEMTXSERVICO.SEQNOTA)
  AND (NFITEMTXSERVPARCIAL.SEQNOTAITEM(+) = NFITEMTXSERVICO.SEQNOTAITEM)
  AND (NFITEMTXSERVPARCIAL.SEQUENCIA(+) = NFITEMTXSERVICO.SEQUENCIA)
    and NFITEMTXSERVICO.SERVICO = 30
  AND 1 = 1 
  AND (NFITEMTXSERVICO.SITUACAO = 'P')
  AND (
        ((TABPERSERVCAB.DTVIGENCIAINI IS NULL) AND (TABPERSERVCAB.DTVIGENCIAFIN IS NULL))
     OR (SYSDATE BETWEEN TABPERSERVCAB.DTVIGENCIAINI AND TABPERSERVCAB.DTVIGENCIAFIN)
     OR (SYSDATE >= TABPERSERVCAB.DTVIGENCIAFIN)
      )
  AND (
        ((TABPRCSERVCAB.DTVIGENCIAINI IS NULL) AND (TABPRCSERVCAB.DTVIGENCIAFIN IS NULL))
     OR (SYSDATE BETWEEN TABPRCSERVCAB.DTVIGENCIAINI AND TABPRCSERVCAB.DTVIGENCIAFIN)
     OR (SYSDATE >= TABPRCSERVCAB.DTVIGENCIAFIN)
      )
  AND (
       ((NFITEMTXSERVICO.COBUNICA IN ('S','C'))
         AND NOT EXISTS(SELECT 1
                          FROM NFITEMPGSERVICO
                         WHERE ESTAB = NFITEMTXSERVICO.ESTAB
                           AND SEQNOTADEP = NFITEMTXSERVICO.SEQNOTA
                           AND SEQNOTAITEMDEP = NFITEMTXSERVICO.SEQNOTAITEM
                           AND SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA)
         AND NOT EXISTS(SELECT 1
                          FROM NFITEMTXSERVICOPG
                         WHERE ESTAB = NFITEMTXSERVICO.ESTAB
                           AND SEQNOTA = NFITEMTXSERVICO.SEQNOTA
                           AND SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
                           AND SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA)
       )
       OR (NFITEMTXSERVICO.COBUNICA = 'N')
      )
  AND (((SALDO_TEMP.SALDO) - COALESCE(RETENPORTO.PESORETENCAO,0) - 
         COALESCE((SELECT SUM(QTDBASECALC)                                                                           
                    FROM NFITEMTXSERVPARCIAL
                   WHERE ESTABORI = NFITEMTXSERVICO.ESTAB
                     AND SEQNOTAORI = NFITEMTXSERVICO.SEQNOTA
                     AND SEQNOTAITEMORI = NFITEMTXSERVICO.SEQNOTAITEM
                     AND SEQUENCIAORI = NFITEMTXSERVICO.SEQUENCIA),0)) > 0)
  AND NOT EXISTS (SELECT 1
                    FROM COBSERCONC 
                   WHERE COBSERCONC.ESTAB          = NFITEMTXSERVICO.ESTAB
                     AND COBSERCONC.SEQNOTADEP     = NFITEMTXSERVICO.SEQNOTA  
                     AND COBSERCONC.SEQNOTAITEMDEP = NFITEMTXSERVICO.SEQNOTAITEM
                     AND COBSERCONC.SERVICO        = NFITEMTXSERVICO.SERVICO)