WITH NFCAB_A AS (
    SELECT 
    NFCAB_A.ESTAB, 
    NFCAB_A.SEQNOTA,
    NFITEM.SEQNOTAITEM,
    NFITEM.QUANTIDADE,
    NFCAB_A.NUMEROCM, 
    NFCFG_NOTA.NATUREZADAOPERACAO, 
    NFCFG_NOTA.ENTRADASAIDA 
    FROM NFCAB NFCAB_A
    LEFT JOIN NFCFG NFCFG_NOTA ON (NFCFG_NOTA.NOTACONF = NFCAB_A.NOTACONF)
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB_A.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN U_TEMPRESA T ON T.ESTAB = FILIAL.ESTAB
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB_A.ESTAB
        AND NFITEM.SEQNOTA = NFCAB_A.SEQNOTA
    WHERE (COALESCE(NFCAB_A.STATUS, 'N') <> 'C')
    AND (NFCFG_NOTA.ENTRADASAIDA = 'E')
    AND CIDADE.UF = 'SP'
    AND GRAOS = 'S'
),
APARTIRDE_BASE AS (
    SELECT
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    N.SEQNOTAITEMORIGEM,
    NFCAB.NUMEROCM,
    NVL(N.SEQTRANSF,0) AS SEQTRANSF,
    NATOPERACAO.TIPODCTO,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('X','N') THEN N.QUANTIDADE ELSE 0 END QUANTIDADE,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.QUANTIDADE ELSE 0 END QTD_D,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.QTDEARMAZENAGEM ELSE 0 END QTDEARMAZENAGEM,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.DESCTOSEGURO ELSE 0 END DESCTOSEGURO,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.DESCTOQUEBRA ELSE 0 END DESCTOQUEBRA,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.DESCTOEXPED ELSE 0 END DESCTOEXPED,
    CASE WHEN NATOPERACAO.TIPODCTO IN ('D') THEN N.DESCTOFINALIDADE ELSE 0 END DESCTOFINALIDADE
    FROM NFITEMAPARTIRDE N
    INNER JOIN FILIAL ON FILIAL.ESTAB = N.ESTAB
    INNER JOIN U_TEMPRESA T ON T.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = N.ESTAB
        AND NFCAB.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    LEFT JOIN NATOPERACAO ON 
        NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA

    WHERE
    NATOPERACAO.TIPODCTO IN ('X','N','D')
    AND T.GRAOS = 'S'
    AND CIDADE.UF = 'SP'
),
APARTIRDE AS (
    SELECT
    B.ESTABORIGEM,
    B.SEQNOTAORIGEM,
    B.SEQNOTAITEMORIGEM,
    B.NUMEROCM,
    SUM(QUANTIDADE) AS QUANTIDADE,
    SUM(QTD_D) AS QTD_D,
    SUM(QTDEARMAZENAGEM) AS QTDEARMAZENAGEM,
    SUM(DESCTOSEGURO) AS DESCTOSEGURO,
    SUM(DESCTOQUEBRA) AS DESCTOQUEBRA,
    SUM(DESCTOEXPED) DESCTOEXPED,
    SUM(DESCTOFINALIDADE) AS DESCTOFINALIDADE
    FROM APARTIRDE_BASE B
    WHERE
    B.SEQTRANSF = 0
    GROUP BY B.ESTABORIGEM,B.SEQNOTAORIGEM,B.SEQNOTAITEMORIGEM,B.NUMEROCM
),
TRANSF_BASE AS (
    SELECT
    T.ESTAB,
    T.SEQNOTA,
    T.SEQNOTAITEM,
    NVL(T.SEQTRANSF,0) AS SEQTRANSF,
    T.QTDETRANSF,
    T.CEDENTE,
    T.DESTINATARIO
    FROM NFITEMTRANSF T
    INNER JOIN FILIAL ON FILIAL.ESTAB = T.ESTAB
    INNER JOIN U_TEMPRESA T ON T.ESTAB = FILIAL.ESTAB
    WHERE T.GRAOS = 'S'
),
TRANSF_DESTINATARIO AS (
    SELECT
    TRANSF_BASE.ESTAB,
    TRANSF_BASE.SEQNOTA,
    TRANSF_BASE.SEQNOTAITEM,
    TRANSF_BASE.DESTINATARIO,
    SUM(TRANSF_BASE.QTDETRANSF) AS QTDETRANSF_DESTINATARIO
    FROM TRANSF_BASE
    WHERE TRANSF_BASE.SEQTRANSF <> 0
    AND NOT EXISTS (
        SELECT
        1
        FROM NFITEMAPARTIRDE F
        WHERE
        F.ESTABORIGEM = TRANSF_BASE.ESTAB
        AND F.SEQNOTAORIGEM = TRANSF_BASE.SEQNOTA
        AND F.SEQNOTAITEMORIGEM = TRANSF_BASE.SEQNOTAITEM
        AND F.SEQTRANSF = TRANSF_BASE.SEQTRANSF
    )
    GROUP BY TRANSF_BASE.ESTAB,TRANSF_BASE.SEQNOTA,TRANSF_BASE.SEQNOTAITEM,TRANSF_BASE.DESTINATARIO
),
TRANSF_CEDENTE AS (
    SELECT
    TRANSF_BASE.ESTAB,
    TRANSF_BASE.SEQNOTA,
    TRANSF_BASE.SEQNOTAITEM,
    TRANSF_BASE.CEDENTE,
    SUM(TRANSF_BASE.QTDETRANSF) AS QTDETRANSF_CEDENTE
    FROM TRANSF_BASE
    WHERE TRANSF_BASE.SEQTRANSF <> 0
    AND NOT EXISTS (
        SELECT
        1
        FROM APARTIRDE_BASE AB
        WHERE
        AB.ESTABORIGEM = TRANSF_BASE.ESTAB
        AND AB.SEQNOTAORIGEM = TRANSF_BASE.SEQNOTA
        AND AB.SEQNOTAITEMORIGEM = TRANSF_BASE.SEQNOTAITEM
        AND AB.SEQTRANSF = TRANSF_BASE.SEQTRANSF
        AND AB.TIPODCTO IN ('D')
    )
    GROUP BY TRANSF_BASE.ESTAB,TRANSF_BASE.SEQNOTA,TRANSF_BASE.SEQNOTAITEM,TRANSF_BASE.CEDENTE
),
BASE_TAB AS (
    SELECT
    NFITEMTXSERVICO.ESTAB,
    NFITEMTXSERVICO.SEQNOTA,
    NFITEMTXSERVICO.SEQNOTAITEM,
    NFITEMTXSERVICO.SEQUENCIA,
    NFITEMTXSERVICO.TABPERSERV,
    NFITEMTXSERVICO.TABPRCSERV,
    NFITEMTXSERVICO.COBUNICA,
    NFITEMTXSERVICO.SERVICO
    FROM NFITEMTXSERVICO
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFITEMTXSERVICO.ESTAB
    INNER JOIN U_TEMPRESA T ON T.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    WHERE
    NFITEMTXSERVICO.SITUACAO = 'P'
    AND NFITEMTXSERVICO.SERVICO = 30
    AND T.GRAOS = 'S'
    AND CIDADE.UF = 'SP'
    AND (
        (
            (NFITEMTXSERVICO.COBUNICA IN ('S','C'))
                AND NOT EXISTS(SELECT 1
                                FROM NFITEMPGSERVICO
                                WHERE ESTAB = NFITEMTXSERVICO.ESTAB
                                AND SEQNOTADEP = NFITEMTXSERVICO.SEQNOTA
                                AND SEQNOTAITEMDEP = NFITEMTXSERVICO.SEQNOTAITEM
                                AND SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA)
                AND NOT EXISTS(SELECT 1
                                FROM NFITEMTXSERVICOPG
                                WHERE ESTAB = NFITEMTXSERVICO.ESTAB
                                AND SEQNOTA = NFITEMTXSERVICO.SEQNOTA
                                AND SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
                                AND SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA)
       )
       OR (NFITEMTXSERVICO.COBUNICA = 'N')
    )
    AND NOT EXISTS (
        SELECT
        1
        FROM COBSERCONC 
        WHERE COBSERCONC.ESTAB = NFITEMTXSERVICO.ESTAB
        AND COBSERCONC.SEQNOTADEP     = NFITEMTXSERVICO.SEQNOTA  
        AND COBSERCONC.SEQNOTAITEMDEP = NFITEMTXSERVICO.SEQNOTAITEM
        AND COBSERCONC.SERVICO        = NFITEMTXSERVICO.SERVICO
    )
),
PARCIAL AS (
    SELECT
    P.ESTABORI,
    P.SEQNOTAORI,
    P.SEQNOTAITEMORI,
    P.SEQUENCIAORI,
    SUM(P.QTDBASECALC) AS QTDBASECALC
    FROM NFITEMTXSERVPARCIAL P
    GROUP BY P.ESTABORI,P.SEQNOTAORI,P.SEQNOTAITEMORI,P.SEQUENCIAORI
),
RETENCAO AS (
    SELECT
    RETENPORTO.ESTAB,
    RETENPORTO.SEQNOTA,
    RETENPORTO.SEQNOTAITEM,
    RETENPORTO.ITEM,
    NVL(RETENPORTO.PESORETENCAO,0) AS PESORETENCAO
    FROM RETENPORTO
    WHERE RETENPORTO.TRANSACAO = 'E'
),
TAB_PERSERV AS (
    SELECT T.*
    FROM TABPERSERVCAB T
    WHERE (T.DTVIGENCIAINI IS NULL AND T.DTVIGENCIAFIN IS NULL)
       OR (SYSDATE BETWEEN T.DTVIGENCIAINI AND T.DTVIGENCIAFIN)
       OR (SYSDATE >= T.DTVIGENCIAFIN)
),
TAB_PRCSERV as (
    SELECT T.*
    FROM TABPRCSERVCAB T
    WHERE (T.DTVIGENCIAINI IS NULL AND T.DTVIGENCIAFIN IS NULL)
       OR (SYSDATE BETWEEN T.DTVIGENCIAINI AND T.DTVIGENCIAFIN)
       OR (SYSDATE >= T.DTVIGENCIAFIN)
),
SALDO_TEMP AS (
    SELECT
    NF.ESTAB, 
    NF.SEQNOTA,
    NF.SEQNOTAITEM, 
    NF.NUMEROCM, 
    NF.NATUREZADAOPERACAO, 
    NF.ENTRADASAIDA,
    (
        NF.QUANTIDADE
        +
        NVL(TD.QTDETRANSF_DESTINATARIO,0)
        -
        (NVL(APARTIRDE.QUANTIDADE,0) + NVL(QTD_D,0) + NVL(APARTIRDE.QTDEARMAZENAGEM,0) + NVL(DESCTOSEGURO,0) + NVL(DESCTOQUEBRA,0) + NVL(DESCTOEXPED,0) + NVL(DESCTOFINALIDADE,0) + NVL(QTDETRANSF_CEDENTE,0))
    )
    AS SALDO
    FROM NFCAB_A NF

    LEFT JOIN APARTIRDE ON
        APARTIRDE.ESTABORIGEM = NF.ESTAB
        AND APARTIRDE.SEQNOTAORIGEM = NF.SEQNOTA
        AND APARTIRDE.SEQNOTAITEMORIGEM = NF.SEQNOTAITEM
        AND APARTIRDE.NUMEROCM = NF.NUMEROCM

    LEFT JOIN TRANSF_DESTINATARIO TD ON
        TD.ESTAB = NF.ESTAB
        AND TD.SEQNOTA = NF.SEQNOTA
        AND TD.SEQNOTAITEM = NF.SEQNOTAITEM
        AND TD.DESTINATARIO = NF.NUMEROCM

    LEFT JOIN TRANSF_CEDENTE TC ON
        TC.ESTAB = NF.ESTAB
        AND TC.SEQNOTA = NF.SEQNOTA
        AND TC.SEQNOTAITEM = NF.SEQNOTAITEM
        AND TC.CEDENTE = NF.NUMEROCM
)
SELECT
       'DV' AS TIPO,
       NFITEMPGSERVICO.ESTAB,
       CONTAMOV.NUMEROCM,
       NFITEMTXSERVICO.SERVICO,
       ITEMAGRONF.ITEM AS ITEM,
       ROMA.ROMANEIO
FROM NFITEMPGSERVICO
JOIN FILIAL ON FILIAL.ESTAB = NFITEMPGSERVICO.ESTAB
JOIN U_TEMPRESA T ON T.ESTAB = FILIAL.ESTAB
JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

JOIN NFITEMTXSERVICO
  ON NFITEMTXSERVICO.ESTAB       = NFITEMPGSERVICO.ESTAB
 AND NFITEMTXSERVICO.SEQNOTA     = NFITEMPGSERVICO.SEQNOTADEP
 AND NFITEMTXSERVICO.SEQNOTAITEM = NFITEMPGSERVICO.SEQNOTAITEMDEP
 AND NFITEMTXSERVICO.SEQUENCIA   = NFITEMPGSERVICO.SEQUENCIA

JOIN NFITEM NFITEM_DEV
  ON NFITEM_DEV.ESTAB       = NFITEMPGSERVICO.ESTABDEV
 AND NFITEM_DEV.SEQNOTA     = NFITEMPGSERVICO.SEQNOTADEV
 AND NFITEM_DEV.SEQNOTAITEM = NFITEMPGSERVICO.SEQNOTAITEMDEV

JOIN NFITEM NFITEM_DEP
  ON NFITEM_DEP.ESTAB       = NFITEMTXSERVICO.ESTAB
 AND NFITEM_DEP.SEQNOTA     = NFITEMTXSERVICO.SEQNOTA
 AND NFITEM_DEP.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM

JOIN NFCAB NFCAB_DEP
  ON NFCAB_DEP.ESTAB   = NFITEM_DEP.ESTAB
 AND NFCAB_DEP.SEQNOTA = NFITEM_DEP.SEQNOTA

LEFT JOIN ENDERECO
  ON ENDERECO.NUMEROCM    = NFCAB_DEP.NUMEROCM
 AND ENDERECO.SEQENDERECO = NFCAB_DEP.SEQENDERECO

JOIN CONTAMOV
  ON CONTAMOV.NUMEROCM = NFCAB_DEP.NUMEROCM

JOIN ITEMAGRO ITEMAGROSERVICO
  ON ITEMAGROSERVICO.ITEM = NFITEMTXSERVICO.SERVICO

JOIN ITEMAGRO ITEMAGRONF
  ON ITEMAGRONF.ITEM = NFITEM_DEP.ITEM

LEFT JOIN NFCABROMA
  ON NFCABROMA.ESTAB    = NFITEM_DEP.ESTAB
 AND NFCABROMA.SEQNOTA  = NFITEM_DEP.SEQNOTA
 AND NFCABROMA.ROMANEIO = NFITEM_DEP.ROMANEIO

LEFT JOIN ROMA
  ON ROMA.ESTAB         = NFCABROMA.ESTAB
 AND ROMA.ROMANEIO      = NFCABROMA.ROMANEIO
 AND ROMA.NUMEROCM      = NFCABROMA.NUMEROCM
 AND ROMA.ENTRADASAIDA  = NFCABROMA.ENTRADASAIDA


WHERE NFITEMTXSERVICO.SERVICO = 30
  AND NFITEMPGSERVICO.SITUACAO = 'P'
  AND T.GRAOS = 'S'
  AND CIDADE.UF = 'SP'
  AND NOT EXISTS (
        SELECT 1
          FROM COBSERCONC
         WHERE COBSERCONC.ESTAB          = NFITEMPGSERVICO.ESTAB
           AND COBSERCONC.SEQNOTADEP     = NFITEMPGSERVICO.SEQNOTADEP  
           AND COBSERCONC.SEQNOTAITEMDEP = NFITEMPGSERVICO.SEQNOTAITEMDEP
           AND COBSERCONC.SERVICO        = NFITEMTXSERVICO.SERVICO
      )
      
UNION ALL

SELECT
'DP' AS TIPO, 
BASE_TAB.ESTAB, 
CONTAMOV.NUMEROCM, 
BASE_TAB.SERVICO,
ITEMAGRO.ITEM AS ITEM, 
ROMA.ROMANEIO
FROM BASE_TAB

JOIN NFITEM ON
    NFITEM.ESTAB = BASE_TAB.ESTAB
    AND NFITEM.SEQNOTA = BASE_TAB.SEQNOTA
    AND NFITEM.SEQNOTAITEM = BASE_TAB.SEQNOTAITEM
JOIN NFCAB ON
    NFCAB.ESTAB = NFITEM.ESTAB
    AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM

JOIN SALDO_TEMP ON
    SALDO_TEMP.ESTAB = NFITEM.ESTAB
    AND SALDO_TEMP.SEQNOTA = NFITEM.SEQNOTA
    AND SALDO_TEMP.SEQNOTAITEM = NFITEM.SEQNOTAITEM
    AND SALDO_TEMP.NUMEROCM = NFCAB.NUMEROCM

LEFT JOIN RETENCAO ON
    RETENCAO.ESTAB = NFITEM.ESTAB
    AND RETENCAO.ESTAB = NFITEM.ESTAB
    AND RETENCAO.SEQNOTA = NFITEM.SEQNOTA
    AND RETENCAO.SEQNOTAITEM = NFITEM.SEQNOTAITEM
    AND RETENCAO.ITEM = NFITEM.ITEM

LEFT JOIN PARCIAL ON
    PARCIAL.ESTABORI = BASE_TAB.ESTAB
    AND PARCIAL.SEQNOTAORI = BASE_TAB.SEQNOTA
    AND PARCIAL.SEQNOTAITEMORI = BASE_TAB.SEQNOTAITEM
    AND PARCIAL.SEQUENCIAORI = BASE_TAB.SEQUENCIA

LEFT JOIN NFCABROMA ON
    NFCABROMA.ESTAB = NFITEM.ESTAB
    AND NFCABROMA.SEQNOTA = NFITEM.SEQNOTA
    AND NFCABROMA.ROMANEIO = NFITEM.ROMANEIO

LEFT JOIN ROMA ON
    ROMA.ESTAB = NFCABROMA.ESTAB
    AND ROMA.ROMANEIO = NFCABROMA.ROMANEIO
    AND ROMA.NUMEROCM = NFCABROMA.NUMEROCM
    AND ROMA.ENTRADASAIDA = NFCABROMA.ENTRADASAIDA

WHERE
(SALDO_TEMP.SALDO - NVL(QTDBASECALC,0) - NVL(RETENCAO.PESORETENCAO,0)) > 0