create or replace TRIGGER OS_INS_STATUSAD
BEFORE UPDATE
ON VIASOFT.PEDCAB_U FOR EACH ROW

DECLARE
V_CENCUSCOD	NUMBER;
V_CENTROCUS	VARCHAR2(6);
V_PESSOA NUMBER;
V_ESTAB NUMBER;
V_CHAVE VARCHAR2(500);
V_CONTADOR NUMBER;
V_VALOR NUMBER;
V_PRAZO DATE;
V_BANCO VARCHAR2(20); 
V_AGENCIA VARCHAR2(20); 
V_CONTA VARCHAR2(20);
V_PIX VARCHAR2(20); 
V_USER VARCHAR2(80);
BEGIN

            IF :NEW.STATUS_AD = 'PENDENTE DOCUMENTO' AND NVL(:OLD.STATUS_AD,'N') <> 'PENDENTE DOCUMENTO' THEN

            SELECT
            CENCUSCOD,CENTROCUS,ESTAB,PESSOA,DTPRAZOPAGTO
            INTO V_CENCUSCOD,V_CENTROCUS,V_ESTAB,V_PESSOA,V_PRAZO
            FROM PEDCAB WHERE
            PEDCAB.ESTAB = :NEW.ESTAB
            AND PEDCAB.SERIE = :NEW.SERIE
            AND PEDCAB.NUMERO = :NEW.NUMERO;

            V_CHAVE := 'NUMEROCM=' || V_PESSOA || ';ESTAB=' || V_ESTAB;

            BEGIN
                SELECT PIX, BANCO, AGENCIA, CONTA, VALOR, USERID_ALT
                INTO V_PIX, V_BANCO, V_AGENCIA, V_CONTA, V_VALOR, V_USER
                FROM U_ADIANTAMENTOS
                WHERE U_ADIANTAMENTOS.ESTAB = :NEW.ESTAB
                AND U_ADIANTAMENTOS.SERIE = :NEW.SERIE
                AND U_ADIANTAMENTOS.NUM_PED = :NEW.NUMERO;
            END;

            BEGIN
                SELECT ID_INT
                INTO V_CONTADOR
                FROM SEQPRIMARYKEY
                WHERE CHAVEVALOR = V_CHAVE
                AND TABELA = 'CONTAMOVLAN';
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    V_CONTADOR := 0;
            END;

            IF V_CONTADOR = 0 THEN

                INSERT INTO SEQPRIMARYKEY (TABELA,CHAVEVALOR,ID_INT) VALUES ('CONTAMOVLAN',V_CHAVE,1);

                V_CONTADOR := 1;

            ELSE
                UPDATE SEQPRIMARYKEY 
                    SET ID_INT = ID_INT + 1 
                WHERE CHAVEVALOR = V_CHAVE
                    AND TABELA = 'CONTAMOVLAN'
                RETURNING ID_INT INTO V_CONTADOR;
            END IF;

            INSERT INTO CONTAMOVLAN (NUMEROCM,ESTAB,SEQCM,DTMOVTO,TIPO,DEBCRED,MOEDA,VALOR,VENCIMENTO,SITUACAO,HISTORICO,USERID)
            VALUES (V_PESSOA,V_ESTAB,V_CONTADOR,TRUNC(CURRENT_DATE+1),'AFGR','D',0,V_VALOR,TRUNC(CURRENT_DATE+1),'P',
            'Aprovação via SGI: Pedido:'|| :NEW.NUMERO ||' Serie:'|| :NEW.SERIE,V_USER
            );
            
            INSERT INTO CONTAMOVLAN_U (NUMEROCM,ESTAB,SEQCM,BANCO,OS_AGENCIA,OS_CONTA,PIX)
            VALUES (V_PESSOA,V_ESTAB,V_CONTADOR,V_BANCO,V_AGENCIA,V_CONTA,V_PIX);

            END IF;

END;	