create or replace TRIGGER OS_INSEREDPLCM 
BEFORE INSERT ON CONTAMOVLAN FOR EACH ROW
DECLARE
V_BANCO VARCHAR2(20);
V_AGENCIA VARCHAR2(20);
V_CONTA VARCHAR2(20);
V_PIX VARCHAR2(20);
BEGIN

 IF (:NEW.TIPO = 'AFGR') THEN
 
    BEGIN
        SELECT
        BANCO,OS_AGENCIA,OS_CONTA,PIX
        INTO V_BANCO,V_AGENCIA,V_CONTA,V_PIX
        FROM CONTAMOVLAN_U
        WHERE CONTAMOVLAN_U.ESTAB = :NEW.ESTAB
        AND CONTAMOVLAN_U.NUMEROCM = :NEW.NUMEROCM
        AND CONTAMOVLAN_U.SEQCM = :NEW.SEQCM;
    END;
    
    INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.BANCO,PDUPPAGA.AGENCIA,PDUPPAGA.CONTA,PDUPPAGA.CHAVEPIX,PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.USERIDAUTPAG
    ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'AFGR-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'AFGR-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM, 
    V_BANCO, V_AGENCIA, V_CONTA, V_PIX, :NEW.VALOR,:NEW.USERID
    );
   END IF;
  
   IF (:NEW.TIPO = 'AFLG') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'AFLG-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'AFLG-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF;
   
  IF (:NEW.TIPO = 'AFI') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'AFI-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'AFI-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF; 
   
 IF (:NEW.TIPO = 'AFG') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'AFG-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'AFG-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF;
   
     IF (:NEW.TIPO = 'DJRE') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'DJRE-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'DJRE-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,445, 2, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF;  
   
    IF (:NEW.TIPO = 'ACT') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'ACT-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACT-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,420, 31, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF;

   IF  (:NEW.TIPO = 'ADG') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'ACT-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ADG-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,429, 19, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF; 

   IF  (:NEW.TIPO = 'ACC') THEN
   INSERT INTO PDUPREC
    (PDUPREC.EMPRESA, PDUPREC.ESTABCLIENTE,PDUPREC.CLIENTE,PDUPREC.DUPREC,
    PDUPREC.DTEMISSAO, PDUPREC.VALOR, PDUPREC.ANOCOMPET,PDUPREC.MESCOMPET,
    PDUPREC.INCMANUT, PDUPREC.MOEDA,PDUPREC.DTVENCTO,PDUPREC.FATURA,PDUPREC.VALORFATURA, 
    PDUPREC.HISTORICO,PDUPREC.ANALITICA,PDUPREC.SITUACAO,PDUPREC.QUITADA,
    PDUPREC.USERID, PDUPREC.DTBASEJUROS,PDUPREC.ESTABANALITICA,PDUPREC.CONTABILIZAR,PDUPREC.NRODOCTOORIGEM ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'ACC-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACC-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,4, 30, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF;  
     
   IF  (:NEW.TIPO = 'PCLD') THEN
   INSERT INTO PDUPREC
    (PDUPREC.EMPRESA, PDUPREC.ESTABCLIENTE,PDUPREC.CLIENTE,PDUPREC.DUPREC,
    PDUPREC.DTEMISSAO, PDUPREC.VALOR, PDUPREC.ANOCOMPET,PDUPREC.MESCOMPET,
    PDUPREC.INCMANUT, PDUPREC.MOEDA,PDUPREC.DTVENCTO,PDUPREC.FATURA,PDUPREC.VALORFATURA, 
    PDUPREC.HISTORICO,PDUPREC.ANALITICA,PDUPREC.SITUACAO,PDUPREC.QUITADA,
    PDUPREC.USERID, PDUPREC.DTBASEJUROS,PDUPREC.ESTABANALITICA,PDUPREC.CONTABILIZAR,PDUPREC.NRODOCTOORIGEM ) 

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'PCLD-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACC-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,337, 12, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF;
     
  IF (:NEW.TIPO = 'CCPR') THEN
   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM  )
 
    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'CCPR-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'CCPR-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,510, 2, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
   END IF;
     
END;