create or replace TRIGGER OS_INSERECTRITE
BEFORE INSERT OR UPDATE ON CONTRATO_U FOR EACH ROW
DECLARE
ESTABD NUMBER;
CONTRATOD NUMBER;
CONTCONFO NUMBER;
SEQITEM NUMBER;
ITEM NUMBER;
LOCAL NUMBER;
DTEMISSAO DATE;
QUANTIDADE NUMBER;
VALORUNIT NUMBER;
VALORTOTAL NUMBER;
TIPOSALDO VARCHAR2(10);
DTMOVSALDO DATE;
GERADO VARCHAR2(10);
V_VALIDA_ESTAB NUMBER := 0;

BEGIN

    SELECT ESTABD,CONTRATOD,CONTCONFO,GERADO 
    INTO ESTABD,CONTRATOD,CONTCONFO,GERADO FROM U_LOGCTR
    WHERE u_logctr.estabo = :NEW.ESTAB
    AND u_logctr.contratoo=:NEW.CONTRATO;      
                                                                            
    IF UPDATING AND GERADO='N' AND :NEW.statusaprov= '2 - Aprovado' THEN

        BEGIN
            SELECT 1
            INTO V_VALIDA_ESTAB
            FROM U_TEMPRESA
            WHERE U_TEMPRESA.ESTAB = :NEW.ESTAB
            AND U_TEMPRESA.GRAOS = 'S' AND U_TEMPRESA.EXVENDA = 'S';
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                V_VALIDA_ESTAB := 0;
        END;
        
        IF V_VALIDA_ESTAB = 1 THEN 

            SELECT SEQITEM,ITEM,LOCAL,DTEMISSAO,QUANTIDADE,VALORUNIT,VALORTOTAL,TIPOSALDO,DTMOVSALDO 
            INTO SEQITEM,ITEM,LOCAL,DTEMISSAO,QUANTIDADE,VALORUNIT,VALORTOTAL,TIPOSALDO,DTMOVSALDO FROM CONTRATOITE
            WHERE CONTRATOITE.ESTAB=:NEW.ESTAB
            AND CONTRATOITE.CONTRATO=:NEW.CONTRATO;
                                                             
            IF ( CONTCONFO = 6) THEN
            
               INSERT INTO CONTRATOITE (CONTRATOITE.ESTAB,CONTRATOITE.CONTRATO,CONTRATOITE.SEQITEM,CONTRATOITE.ITEM,CONTRATOITE.LOCAL,CONTRATOITE.DTEMISSAO,CONTRATOITE.QUANTIDADE,
               CONTRATOITE.VALORUNIT,CONTRATOITE.VALORTOTAL,
               CONTRATOITE.TIPOSALDO,CONTRATOITE.PRECOVENDA,CONTRATOITE.QUALCOTACAO,CONTRATOITE.DTMOVSALDO)
               VALUES (ESTABD,CONTRATOD,SEQITEM,ITEM,999,DTEMISSAO,QUANTIDADE,VALORUNIT,VALORTOTAL,TIPOSALDO,'I','N',DTMOVSALDO);
   
               UPDATE CONTRATODTVENCTO CDT SET CDT.QTDFLUXOCX=VALORTOTAL WHERE CDT.ESTAB=:NEW.ESTAB AND CDT.CONTRATO =:NEW.CONTRATO;
               
               UPDATE CONTRATO SET CONTRATO.PRIORIDADE = 3 WHERE CONTRATO.ESTAB=:NEW.ESTAB AND CONTRATO.CONTRATO =:NEW.CONTRATO;
               
               UPDATE u_logctr SET u_logctr.GERADO='S' WHERE  u_logctr.estabo = :NEW.ESTAB AND u_logctr.contratoo=:NEW.CONTRATO;      
                                                                            
            END IF;
        
        END IF;

END IF;
 EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;
END;