WITH NOTAS AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCAB.NOTACONF,
    NFCAB.NUMEROCM,
    NFCABROMA.ROMANEIO,
    NFCABROMA.ENTRADASAIDA,
    NFCABROMA.CLASSIFICACAO,
    CONTAMOV.REACOBFINLEITURA
    FROM NFCAB
    INNER JOIN FILIAL ON
    FILIAL.ESTAB                    = NFCAB.ESTAB

    INNER JOIN CIDADE ON
    CIDADE.CIDADE                   = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF                  = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA              = 'E'
    and nfcfg.notaconf in (
    -- compra futura
    200,201,258,221,234,237,414,334,335,336,337,338,
    --- compra direta
    202,203,278
    )

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO             IN ('A','N')

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM               = NFCAB.NUMEROCM

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM               = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO            = NFCAB.SEQENDERECO

    INNER JOIN NFCABROMA ON
    NFCABROMA.ESTAB                 = NFCAB.ESTAB AND
    NFCABROMA.SEQNOTA               = NFCAB.SEQNOTA
    
    --WHERE NFCAB.NUMEROCM = 1231 AND NFCABROMA.ROMANEIO = 3431
),
UMIDADE AS (
    SELECT
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM,
        SUM(TABUMISERVITEM.VALOR) AS VALOR_UMIDADE
    FROM ROMATXSERVICO
        INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM
        INNER JOIN CONTAMOV ON
                CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM
                 AND CONTAMOV.REACOBFINLEITURA  = 0
        INNER JOIN ROMADESC ON
                ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
                ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
                ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
                ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
                ROMADESC.ROMADESC                   = 2
        INNER JOIN TABUMISERVCAB ON
                TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV
        INNER JOIN TABUMISERVITEM ON
                TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
                ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN
        INNER JOIN NOTAS ON
            NOTAS.ESTAB = ROMASERV.ESTAB
            AND NOTAS.NUMEROCM = ROMASERV.NUMEROCM
            AND NOTAS.ROMANEIO = ROMASERV.ROMANEIO
            AND NOTAS.ENTRADASAIDA = ROMASERV.ENTRADASAIDA
    WHERE ROMATXSERVICO.SERVICO = 30
      AND ROMATXSERVICO.STATUS <> 'C'
    GROUP BY
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM
),
NOTAS_ITEM AS (
    SELECT DISTINCT
    NFITEM.ESTAB,NFITEM.SEQNOTA,NFITEM.ITEM,NFITEM.ROMANEIO FROM NOTAS
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NOTAS.ESTAB
        AND NFITEM.SEQNOTA = NOTAS.SEQNOTA
    WHERE NFITEM.ROMANEIO IS NOT NULL
),
PAGAMENTOS AS (
    SELECT
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM,
        SUM(QTDEPAGO) AS QTDEPAGO
    FROM ROMATXSERVICOPG
        INNER JOIN NOTAS ON
            NOTAS.ESTAB = ROMATXSERVICOPG.ESTAB
            AND NOTAS.NUMEROCM = ROMATXSERVICOPG.NUMEROCM
            AND NOTAS.ROMANEIO = ROMATXSERVICOPG.ROMANEIO
            AND NOTAS.ENTRADASAIDA = ROMATXSERVICOPG.ENTRADASAIDA
    GROUP BY
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM
)
SELECT
CASE WHEN NOTAS.NOTACONF IN (200,201,258,221,234,237,414,334,335,336,337,338) THEN 'FUTURO' ELSE 'DIRETO' END TIPO,
NOTAS.ESTAB,
NOTAS.SEQNOTA,
NOTAS.NOTACONF,
NOTAS.NUMEROCM,
NOTAS.ROMANEIO,
ROMA.ROMANEIOCONFIG,
NOTAS.ENTRADASAIDA,
ITEMCOTITE.FIXACAO,
ROMA.PESOLIQUIDO,
PAGAMENTOS.QTDEPAGO,
NOTAS.REACOBFINLEITURA,
CASE 
    --- validação compra direta
    WHEN  NOTAS.NOTACONF IN (202,203,278) AND ROMA.ROMANEIOCONFIG = 9 THEN 0
    WHEN NOTAS.NOTACONF IN (202,203,278) AND ROMA.ROMANEIOCONFIG <> 9 THEN
        ROMA.PESOLIQUIDO - (CASE WHEN NOTAS.REACOBFINLEITURA = 0 THEN NVL(PAGAMENTOS.QTDEPAGO,0) ELSE 0 END)
    --- VALIDAÇÃO COMPRA FUTURA
    WHEN ROMA.ROMANEIOCONFIG = 52 THEN ROMA.PESOORIGEM 
    ELSE ROMA.PESOLIQUIDO - 
        CASE
            WHEN NOTAS.REACOBFINLEITURA = 0 AND PAGAMENTOS.QTDEPAGO > 0 THEN PAGAMENTOS.QTDEPAGO
            WHEN NOTAS.REACOBFINLEITURA = 0 AND PAGAMENTOS.QTDEPAGO = 0 THEN
            DIVIDE(    
                DIVIDE(
                    (NVL(ROMA.PESOTOTAL,0) - NVL(ROMA.TARA,0)) * UMIDADE.VALOR_UMIDADE,
                    60),
            ITEMCOTITE.FIXACAO
            )*60
        ELSE 0 END
    END AS SALDO
FROM NOTAS
--  ROMA.PESOLIQUIDO - CASE WHEN CONTAMOV.REACOBFINLEITURA = 0 THEN COALESCE(SUM((SELECT SUM(ROMATXSERVICOPG.QTDEPAGO)
INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB                 = NOTAS.ESTAB AND
    ROMACLASS.ROMANEIO              = NOTAS.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA          = NOTAS.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM              = NOTAS.NUMEROCM AND
    ROMACLASS.CLASSIFICACAO         = NOTAS.CLASSIFICACAO /*AND
    ROMACLASS.PERCENTUAL            > 0                         */

INNER JOIN ROMA ON
    ROMA.ESTAB                      = ROMACLASS.ESTAB AND
    ROMA.ROMANEIO                   = ROMACLASS.ROMANEIO AND
    ROMA.ENTRADASAIDA               = ROMACLASS.ENTRADASAIDA AND
    ROMA.NUMEROCM                   = ROMACLASS.NUMEROCM AND
    ROMA.ESTORNADO <> 'S'

INNER JOIN NOTAS_ITEM ON
    NOTAS_ITEM.ESTAB                    = NOTAS.ESTAB AND
    NOTAS_ITEM.SEQNOTA                  = NOTAS.SEQNOTA AND
    NOTAS_ITEM.ROMANEIO                 = NOTAS.ROMANEIO
    
LEFT JOIN UMIDADE ON
    NOTAS.ESTAB = UMIDADE.ESTAB
    AND NOTAS.NUMEROCM = UMIDADE.NUMEROCM
    AND NOTAS.ROMANEIO = UMIDADE.ROMANEIO
    AND NOTAS.ENTRADASAIDA = UMIDADE.ENTRADASAIDA
    
LEFT JOIN PAGAMENTOS ON
    NOTAS.ESTAB = PAGAMENTOS.ESTAB
    AND NOTAS.NUMEROCM = PAGAMENTOS.NUMEROCM
    AND NOTAS.ROMANEIO = PAGAMENTOS.ROMANEIO
    AND NOTAS.ENTRADASAIDA = PAGAMENTOS.ENTRADASAIDA

INNER JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = NOTAS_ITEM.ESTAB AND
    ITEMAGROESTAB.ITEM              = NOTAS_ITEM.ITEM

INNER JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

INNER JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
WHERE NOTAS.NUMEROCM IN (
1287
) --AND NOTAS.ROMANEIO = 3431
