SELECT ROMAPESO.*, CONTAMOV.NOME AS NOMEFORN, ITEMAGRO.DESCRICAO AS NOMEITEM,
       TRANSP.NOME AS NOMEPRESTADOR, TERCEIROS.NOME AS NOMETERCEIROS,
       ROMAPESO.IDPESOTOTALMANUAL, ROMAPESO.IDTARAMANUAL, CAST('' AS VARCHAR(20)) AS AUTORIZADO,
       CAST('' AS VARCHAR(20)) AS AUTORIZADOROMAQUALI,
      (ROMAPESO.PESOTOTAL - ROMAPESO.TARA) AS PESOLIQUIDO,
      
       /*Retorna S se nos desctos tem algum que obriga informar*/
      CAST((SELECT 'S' FROM ROMAPESODESC R 
         WHERE (ROMAPESO.ESTAB = R.ESTAB)
           AND (ROMAPESO.PLACA = R.PLACA)
           AND (ROMAPESO.SEQUENCIA = R.SEQUENCIA)
           AND (R.OBRIGATORIO='S')
           AND (ROWNUM = 1)) AS VARCHAR(2)) AS OBRDESCTOS, 
       /*Retorna N se tem um ou mais descto obrigatorio que falta informar*/
       CAST(COALESCE((SELECT 'N' FROM ROMAPESODESC  
                  WHERE (ROMAPESO.ESTAB = ROMAPESODESC.ESTAB)
                    AND (ROMAPESO.PLACA = ROMAPESODESC.PLACA)                                   
                    AND (ROMAPESO.SEQUENCIA = ROMAPESODESC.SEQUENCIA)
                    AND (ROMAPESODESC.OBRIGATORIO='S')
                    AND (ROMAPESODESC.REFTABELA = 0)      
                    AND (ROWNUM = 1)), 'S') AS VARCHAR(2)) AS DESCTOSOK,  
       /*Retorna N se tem uma ou mais Qualidade que falta informar*/
       CAST(COALESCE((SELECT 'N' FROM ROMAPESOQUALIDADE
            WHERE (ROMAPESOQUALIDADE.ESTAB       = ROMAPESO.ESTAB)  
              AND (ROMAPESOQUALIDADE.PLACA       = ROMAPESO.PLACA)  
              AND (ROMAPESOQUALIDADE.SEQUENCIA   = ROMAPESO.SEQUENCIA)  
              AND (ROMAPESOQUALIDADE.ALTEROUGRAU = 'N')  
              AND (ROWNUM = 1)), 'S') AS VARCHAR(2)) AS QUALIDADEOK,
      
      COALESCE((SELECT SUM(CASE WHEN Coalesce(LIBERADO,'N')='S' THEN 1 ELSE 0 END)
        FROM LEITURAAUT LEITURA
       WHERE (LEITURA.ESTAB = ROMAPESO.ESTAB)
         AND (LEITURA.PLACA = ROMAPESO.PLACA)
         AND (LEITURA.SEQUENCIA = ROMAPESO.SEQUENCIA)
         AND ((LEITURA.ID = ROMAPESO.IDPESOTOTALMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDTARAMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAOPESO)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAODESCONT)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZAEMBARQUE))
       GROUP BY ESTAB, PLACA, SEQUENCIA),0) AS LIBE,
     COALESCE((SELECT SUM(CASE WHEN Coalesce(LIBERADO,'N')='N' THEN 1 ELSE 0 END)
        FROM LEITURAAUT LEITURA
       WHERE (LEITURA.ESTAB = ROMAPESO.ESTAB)
         AND (LEITURA.PLACA = ROMAPESO.PLACA)
         AND (LEITURA.SEQUENCIA = ROMAPESO.SEQUENCIA)
         AND ((LEITURA.ID = ROMAPESO.IDPESOTOTALMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDTARAMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAOPESO)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAODESCONT)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZAEMBARQUE))
       GROUP BY ESTAB, PLACA, SEQUENCIA),0) AS BLOQ,
     COALESCE((SELECT SUM(CASE WHEN Coalesce(LIBERADO,'N')='C' THEN 1 ELSE 0 END)
        FROM LEITURAAUT LEITURA
       WHERE (LEITURA.ESTAB = ROMAPESO.ESTAB)
         AND (LEITURA.PLACA = ROMAPESO.PLACA)
         AND (LEITURA.SEQUENCIA = ROMAPESO.SEQUENCIA)
         AND ((LEITURA.ID = ROMAPESO.IDPESOTOTALMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDTARAMANUAL)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAOPESO)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZACAODESCONT)
           OR (LEITURA.ID = ROMAPESO.IDAUTORIZAEMBARQUE))
       GROUP BY ESTAB, PLACA, SEQUENCIA),0) AS CANC,
        (SELECT AUTOROMAQUALI.AUTORIZADO FROM ROMAPESOQUALIDADE
               INNER JOIN AUTOROMAQUALI
               ON AUTOROMAQUALI.SEQUENCIA          = ROMAPESOQUALIDADE.SEQAUTORIZACAO
            WHERE (ROMAPESOQUALIDADE.ESTAB   = ROMAPESO.ESTAB)                  
            AND (ROMAPESOQUALIDADE.PLACA     = ROMAPESO.PLACA)  
            AND (ROMAPESOQUALIDADE.SEQUENCIA = ROMAPESO.SEQUENCIA)
            AND (ROWNUM = 1)) AS QUALIDADEAPROVA
FROM ROMAPESO
INNER JOIN ROMACFG 
   ON ROMACFG.ROMANEIOCONFIG = ROMAPESO.ROMANEIOCONFIG 
LEFT JOIN CONTAMOV
  ON (CONTAMOV.NUMEROCM=ROMAPESO.NUMEROCM)
LEFT JOIN CONTAMOV TRANSP
  ON (TRANSP.NUMEROCM=ROMAPESO.PRESTADOR)
LEFT JOIN CONTAMOV TERCEIROS
  ON (TERCEIROS.NUMEROCM=ROMAPESO.TERCEIROS)
LEFT JOIN ITEMAGRO
  ON (ITEMAGRO.ITEM=ROMAPESO.ITEM)
LEFT JOIN PUSERS
  ON (PUSERS.USERID = :USERID)
WHERE (ROMAPESO.ESTAB = :ESTAB)
  /*Se estiver para visualizar todas as leituras de peso*/
  AND ((PUSERS.VISULEITPESO='S') OR
       /* ou o usuário só pode ver suas leituras de peso*/
       ((ROMAPESO.USERID = :USERID) AND
        (PUSERS.VISULEITPESO='N')))
    AND ((ROMAPESO.PESOTOTAL=0 OR ROMAPESO.TARA=0 OR  ROMAPESO.SALVALEPESOSEMROMA='S' OR ROMAPESO.NUMEROCM IS NULL)
     OR (((ROMAPESO.IDAUTORIZACAOPESO > 0) OR  (ROMAPESO.IDAUTORIZACAODESCONT > 0)) AND 
       ((SELECT COUNT(LIBERADO) FROM LEITURAAUT WHERE LEITURAAUT.TIPOLIBERACAO = 'E' AND ((LEITURAAUT.ID = ROMAPESO.IDAUTORIZACAOPESO) OR (LEITURAAUT.ID = ROMAPESO.IDAUTORIZACAODESCONT))) > 0))
     OR (EXISTS(SELECT 1 FROM ROMAPESOQUALIDADE
               INNER JOIN AUTOROMAQUALI
               ON AUTOROMAQUALI.SEQUENCIA            = ROMAPESOQUALIDADE.SEQAUTORIZACAO
            WHERE (ROMAPESOQUALIDADE.ESTAB     = ROMAPESO.ESTAB)                  
              AND (ROMAPESOQUALIDADE.PLACA       = ROMAPESO.PLACA)  
              AND (ROMAPESOQUALIDADE.SEQUENCIA   = ROMAPESO.SEQUENCIA)
              AND (AUTOROMAQUALI.AUTORIZADO <> 'S')
              AND (ROWNUM = 1))) AND
        (EXISTS(SELECT  1 FROM ROMAPESOCLASS
                INNER JOIN ROMACLASSNOME ON
                ROMACLASSNOME.CLASSIFICACAO = ROMAPESOCLASS.CLASSIFICACAO
                WHERE ROMAPESOCLASS.ESTAB =  ROMAPESO.ESTAB
                AND ROMAPESOCLASS.PLACA = ROMAPESO.PLACA
                AND ROMAPESOCLASS.SEQUENCIA = ROMAPESO.SEQUENCIA
                AND ROMAPESOCLASS.PERCENTUAL > 0 
                AND ROMACLASSNOME.SEMENTE = 'S'
                AND (ROWNUM = 1)))    
          OR (((ROMAPESO.PESOTOTAL>0 )
         AND (ROMAPESO.TARA>0)) 
         AND ((COALESCE(ROMACFG.OBRIGAPH,'') = 'L') 
         AND (COALESCE(ROMAPESO.PHORIGINAL,0) < 0))))
                
    AND NOT EXISTS (SELECT ROMAPESOFAT.ESTAB FROM ROMAPESOFAT
          WHERE ROMAPESOFAT.ESTAB = ROMAPESO.ESTAB AND ROMAPESOFAT.PLACA = ROMAPESO.PLACA 
            AND ROMAPESOFAT.SEQUENCIA = ROMAPESO.SEQUENCIA AND ROMAPESOFAT.NUMEROCM = ROMAPESO.NUMEROCM)