WITH PESO AS (
    SELECT
    ROMAPESO.*, 
    CONTAMOV.NOME AS NOMEFORN, 
    ITEMAGRO.DESCRICAO AS NOMEITEM,
    TRANSP.NOME AS NOMEPRESTADOR,
    TERCEIROS.NOME AS NOMETERCEIROS,
    --ROMAPESO.IDPESOTOTALMANUAL, 
    --ROMAPESO.IDTARAMANUAL, 
    CAST('' AS VARCHAR(20)) AS AUTORIZADO,
    CAST('' AS VARCHAR(20)) AS AUTORIZADOROMAQUALI,
    (ROMAPESO.PESOTOTAL - ROMAPESO.TARA) AS PESOLIQUIDO
    FROM ROMAPESO
    INNER JOIN ROMACFG ON ROMACFG.ROMANEIOCONFIG = ROMAPESO.ROMANEIOCONFIG 
    LEFT JOIN CONTAMOV ON (CONTAMOV.NUMEROCM=ROMAPESO.NUMEROCM)
    LEFT JOIN CONTAMOV TRANSP ON (TRANSP.NUMEROCM=ROMAPESO.PRESTADOR)
    LEFT JOIN CONTAMOV TERCEIROS ON (TERCEIROS.NUMEROCM=ROMAPESO.TERCEIROS)
    LEFT JOIN ITEMAGRO ON (ITEMAGRO.ITEM=ROMAPESO.ITEM)
    -- USUARIO DA TELA
    LEFT JOIN PUSERS ON (PUSERS.USERID = :USERID)
    WHERE
    NOT EXISTS (
        SELECT ROMAPESOFAT.ESTAB FROM ROMAPESOFAT
        WHERE ROMAPESOFAT.ESTAB = ROMAPESO.ESTAB AND ROMAPESOFAT.PLACA = ROMAPESO.PLACA 
        AND ROMAPESOFAT.SEQUENCIA = ROMAPESO.SEQUENCIA AND ROMAPESOFAT.NUMEROCM = ROMAPESO.NUMEROCM
    )
    and ROMAPESO.ESTAB = :ESTAB
      /*Se estiver para visualizar todas as leituras de peso*/
    AND (
        (PUSERS.VISULEITPESO='S') OR
       /* ou o usuário só pode ver suas leituras de peso*/
       ((ROMAPESO.USERID = :USERID) AND (PUSERS.VISULEITPESO='N'))
    )
),
LEITURA AS (
    SELECT
    L.ESTAB,L.PLACA,L.SEQUENCIA,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='S' THEN 1 ELSE 0 END) LIBE,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='N' THEN 1 ELSE 0 END) BLOQ,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='C' THEN 1 ELSE 0 END) CANC
    FROM LEITURAAUT L
    INNER JOIN PESO ON
        PESO.ESTAB = L.ESTAB
        AND PESO.PLACA = L.PLACA
        AND PESO.SEQUENCIA = L.SEQUENCIA
        AND (
            (L.ID = PESO.IDPESOTOTALMANUAL)
            OR (L.ID = PESO.IDTARAMANUAL)
            OR (L.ID = PESO.IDAUTORIZACAOPESO)
            OR (L.ID = PESO.IDAUTORIZACAODESCONT)
            OR (L.ID = PESO.IDAUTORIZAEMBARQUE)
        )
    GROUP BY L.ESTAB,L.PLACA,L.SEQUENCIA
),
INFO_DESCTO AS (
    SELECT
    R.ESTAB,R.PLACA,R.SEQUENCIA,
    MAX(CASE WHEN R.OBRIGATORIO='S' THEN 'S' END) OBRDESCTOS,
    MAX(CASE WHEN R.OBRIGATORIO='S' AND R.REFTABELA = 0 THEN 'N' END) DESCTOSOK
    FROM ROMAPESODESC R
    INNER JOIN PESO ON
        PESO.ESTAB = R.ESTAB
        AND PESO.PLACA = R.PLACA
        AND PESO.SEQUENCIA = R.SEQUENCIA
    GROUP BY R.ESTAB, R.PLACA, R.SEQUENCIA
),
QUALIDADE AS (
    SELECT DISTINCT
    Q.ESTAB,Q.PLACA,Q.SEQUENCIA,'N'  AS QUALIDADEOK
    FROM ROMAPESOQUALIDADE Q
    INNER JOIN PESO ON
        PESO.ESTAB = Q.ESTAB
        AND PESO.PLACA = Q.PLACA
        AND PESO.SEQUENCIA = Q.SEQUENCIA
    GROUP BY Q.ESTAB, Q.PLACA, Q.SEQUENCIA
),
QUALIDADE_APRV AS (
    SELECT
    R.ESTAB,R.PLACA,R.SEQUENCIA,AUTOROMAQUALI.AUTORIZADO
    FROM ROMAPESOQUALIDADE R
    INNER JOIN PESO ON
        PESO.ESTAB = R.ESTAB
        AND PESO.PLACA = R.PLACA
        AND PESO.SEQUENCIA = R.SEQUENCIA
    INNER JOIN AUTOROMAQUALI ON AUTOROMAQUALI.SEQUENCIA = R.SEQAUTORIZACAO
)
SELECT
----- 1 VALIDAÇÃO DA VSCONSULTA
PESO.*
FROM PESO
WHERE
(PESO.PESOTOTAL=0 OR PESO.TARA=0 OR  PESO.SALVALEPESOSEMROMA='S' OR PESO.NUMEROCM IS NULL)

UNION ALL

SELECT
----- 2 VALIDAÇÃO DA VSCONSULTA
PESO.*
FROM PESO

WHERE
(
    ((PESO.IDAUTORIZACAOPESO > 0) OR  (PESO.IDAUTORIZACAODESCONT > 0)) 
    AND 
    (
        (
            SELECT COUNT(LIBERADO) 
            FROM LEITURAAUT WHERE LEITURAAUT.TIPOLIBERACAO = 'E' 
            AND ((LEITURAAUT.ID = PESO.IDAUTORIZACAOPESO) OR (LEITURAAUT.ID = PESO.IDAUTORIZACAODESCONT))
        ) > 0
    )
)