WITH PESO /*+ MATERIALIZE */ AS (
    SELECT
    ROMAPESO.*, 
    CONTAMOV.NOME AS NOMEFORN, 
    ITEMAGRO.DESCRICAO AS NOMEITEM,
    TRANSP.NOME AS NOMEPRESTADOR,
    TERCEIROS.NOME AS NOMETERCEIROS,
    CAST('' AS VARCHAR(20)) AS AUTORIZADO,
    CAST('' AS VARCHAR(20)) AS AUTORIZADOROMAQUALI,
    (ROMAPESO.PESOTOTAL - ROMAPESO.TARA) AS PESOLIQUIDO,
    ROMACFG.OBRIGAPH
    FROM ROMAPESO
    INNER JOIN ROMACFG ON ROMACFG.ROMANEIOCONFIG = ROMAPESO.ROMANEIOCONFIG 
    LEFT JOIN CONTAMOV ON (CONTAMOV.NUMEROCM=ROMAPESO.NUMEROCM)
    LEFT JOIN CONTAMOV TRANSP ON (TRANSP.NUMEROCM=ROMAPESO.PRESTADOR)
    LEFT JOIN CONTAMOV TERCEIROS ON (TERCEIROS.NUMEROCM=ROMAPESO.TERCEIROS)
    LEFT JOIN ITEMAGRO ON (ITEMAGRO.ITEM=ROMAPESO.ITEM)
    -- USUARIO DA TELA
    LEFT JOIN PUSERS ON (PUSERS.USERID = :USERID)
    WHERE
    NOT EXISTS (
        SELECT 1 FROM ROMAPESOFAT
        WHERE ROMAPESOFAT.ESTAB = ROMAPESO.ESTAB AND ROMAPESOFAT.PLACA = ROMAPESO.PLACA 
        AND ROMAPESOFAT.SEQUENCIA = ROMAPESO.SEQUENCIA AND ROMAPESOFAT.NUMEROCM = ROMAPESO.NUMEROCM
    )
    and ROMAPESO.ESTAB = :ESTAB
      /*Se estiver para visualizar todas as leituras de peso*/
    AND (
        (PUSERS.VISULEITPESO='S') OR
       /* ou o usuário só pode ver suas leituras de peso*/
       ((ROMAPESO.USERID = :USERID) AND (PUSERS.VISULEITPESO='N'))
    )
),
LEITURA AS (
    SELECT
    L.ESTAB,L.PLACA,L.SEQUENCIA,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='S' THEN 1 ELSE 0 END) LIBE,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='N' THEN 1 ELSE 0 END) BLOQ,
    SUM(CASE WHEN COALESCE(L.LIBERADO,'N')='C' THEN 1 ELSE 0 END) CANC,
    MAX(CASE WHEN L.TIPOLIBERACAO='E' THEN 1 END) TEM_LIBERACAO
    FROM LEITURAAUT L
    INNER JOIN PESO ON
        PESO.ESTAB = L.ESTAB
        AND PESO.PLACA = L.PLACA
        AND PESO.SEQUENCIA = L.SEQUENCIA
        AND (
            (L.ID = PESO.IDPESOTOTALMANUAL)
            OR (L.ID = PESO.IDTARAMANUAL)
            OR (L.ID = PESO.IDAUTORIZACAOPESO)
            OR (L.ID = PESO.IDAUTORIZACAODESCONT)
            OR (L.ID = PESO.IDAUTORIZAEMBARQUE)
        )
    GROUP BY L.ESTAB,L.PLACA,L.SEQUENCIA
),
INFO_DESCTO AS (
    SELECT
    R.ESTAB,R.PLACA,R.SEQUENCIA,
    MAX(CASE WHEN R.OBRIGATORIO='S' THEN 'S' END) OBRDESCTOS,
    MAX(CASE WHEN R.OBRIGATORIO='S' AND R.REFTABELA = 0 THEN 'N' END) DESCTOSOK
    FROM ROMAPESODESC R
    INNER JOIN PESO ON
        PESO.ESTAB = R.ESTAB
        AND PESO.PLACA = R.PLACA
        AND PESO.SEQUENCIA = R.SEQUENCIA
    GROUP BY R.ESTAB, R.PLACA, R.SEQUENCIA
),
QUALIDADE AS (
    SELECT DISTINCT
    Q.ESTAB,Q.PLACA,Q.SEQUENCIA,
    MAX(CASE WHEN ALTEROUGRAU = 'N' THEN 1 ELSE 0 END) AS QUALIDADEOK,
    MAX(CASE WHEN A.AUTORIZADO <> 'S' THEN 1 END) QUALIDADE_PENDENTE,
    MAX(A.AUTORIZADO) AUTORIZADO
    FROM ROMAPESOQUALIDADE Q
    INNER JOIN PESO ON
        PESO.ESTAB = Q.ESTAB
        AND PESO.PLACA = Q.PLACA
        AND PESO.SEQUENCIA = Q.SEQUENCIA
    LEFT JOIN AUTOROMAQUALI A ON A.SEQUENCIA = Q.SEQAUTORIZACAO
    GROUP BY Q.ESTAB, Q.PLACA, Q.SEQUENCIA
),
CLASS_SEMENTE AS (
    SELECT DISTINCT
    C.ESTAB,
    C.PLACA,
    C.SEQUENCIA
    FROM ROMAPESOCLASS C
    INNER JOIN ROMACLASSNOME N ON N.CLASSIFICACAO = C.CLASSIFICACAO
    INNER JOIN PESO ON 
        PESO.ESTAB = C.ESTAB
        AND PESO.PLACA = C.PLACA
        AND PESO.SEQUENCIA = C.SEQUENCIA  
    WHERE C.PERCENTUAL > 0 AND N.SEMENTE = 'S'
),
PESO_FINAL AS (
    SELECT
    PESO.*,
    INFO_DESCTO.OBRDESCTOS,
    INFO_DESCTO.DESCTOSOK,
    CASE WHEN QUALIDADE.QUALIDADEOK = 1 THEN 'N' ELSE 'S' END AS QUALIDADEOK,
    LEITURA.LIBE,
    LEITURA.BLOQ,
    LEITURA.CANC,
    QUALIDADE.AUTORIZADO AS QUALIDADEAPROVA,
    LEITURA.TEM_LIBERACAO,
    QUALIDADE.QUALIDADE_PENDENTE,
    CASE WHEN CLASS_SEMENTE.ESTAB IS NOT NULL THEN 1 END AS TEM_SEMENTE
    FROM PESO
    LEFT JOIN INFO_DESCTO ON
        INFO_DESCTO.ESTAB = PESO.ESTAB
        AND INFO_DESCTO.PLACA = PESO.PLACA
        AND INFO_DESCTO.SEQUENCIA = PESO.SEQUENCIA
    LEFT JOIN QUALIDADE ON
        QUALIDADE.ESTAB = PESO.ESTAB
        AND QUALIDADE.PLACA = PESO.PLACA
        AND QUALIDADE.SEQUENCIA = PESO.SEQUENCIA
    LEFT JOIN LEITURA ON
        LEITURA.ESTAB = PESO.ESTAB
        AND LEITURA.PLACA = PESO.PLACA
        AND LEITURA.SEQUENCIA = PESO.SEQUENCIA
    LEFT JOIN CLASS_SEMENTE ON 
        CLASS_SEMENTE.ESTAB = PESO.ESTAB
        AND CLASS_SEMENTE.PLACA = PESO.PLACA
        AND CLASS_SEMENTE.SEQUENCIA = PESO.SEQUENCIA
)
SELECT
----- 1 VALIDAÇÃO DA VSCONSULTA
PESO_FINAL.*
FROM PESO_FINAL
WHERE
(PESO_FINAL.PESOTOTAL=0 OR PESO_FINAL.TARA=0 OR  PESO_FINAL.SALVALEPESOSEMROMA='S' OR PESO_FINAL.NUMEROCM IS NULL)

UNION ALL

SELECT
----- 2 VALIDAÇÃO DA VSCONSULTA
PESO_FINAL.*
FROM PESO_FINAL
WHERE
(PESO_FINAL.IDAUTORIZACAOPESO > 0 OR PESO_FINAL.IDAUTORIZACAODESCONT > 0)
AND PESO_FINAL.TEM_LIBERACAO = 1

UNION ALL

SELECT
----- 3 VALIDAÇÃO DA VSCONSULTA
PESO_FINAL.*
FROM PESO_FINAL
WHERE
PESO_FINAL.QUALIDADE_PENDENTE = 1
AND PESO_FINAL.TEM_SEMENTE = 1

UNION ALL

SELECT
----- 4 VALIDAÇÃO DA VSCONSULTA
PESO_FINAL.*
FROM PESO_FINAL
WHERE PESO_FINAL.PESOTOTAL > 0
AND PESO_FINAL.TARA > 0
AND PESO_FINAL.OBRIGAPH = 'L'
AND PESO_FINAL.PHORIGINAL < 0