SELECT
COD_SAFRA,
COD_APONTA,
COD_SAFRA||'#'||COD_APONTA AS OSAPONTA,
ESTAB||'#'||LOCALEST AS OSLOCAL, -- ALMOFERIXADO
SEQ,
COD_ITEM,
UN_ITEM,
UN_MOVIM,
QUANTIDADE,
CUSTO_UNIT,
CUSTO_TOTAL,
DATA,
HORA,
APLICACAO,
DOSAGEM,
DOSAGEM_REAL,
COD_COMP AS COD_COMPONENTE
FROM LVAPTPROD