WITH 
----- ###### SALDO CONTABIL
SALDO AS (
    SELECT
    ITEMSALDO.ESTAB,
    ITEMSALDO.LOCAL,
    ITEMSALDO.ITEM,
    ITEMSALDO.CODIGOSALDO,
    ROW_NUMBER() OVER (
        PARTITION BY ESTAB, LOCAL, ITEM, CODIGOSALDO
        ORDER BY ANO DESC, MES DESC
    ) AS RK
    --MAX(TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO
    WHERE
    ITEMSALDO.CODIGOSALDO = 5
    AND (0 IN (:ESTAB) OR ITEMSALDO.ESTAB IN (:ESTAB))
    AND (TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY')) <= :DTCORTE
    -- GROUP BY ITEMSALDO.ESTAB,ITEMSALDO.LOCAL,ITEMSALDO.ITEM,ITEMSALDO.CODIGOSALDO
),
BASE AS (
    SELECT
    ITEMAGROESTAB.ESTAB,
    ITEMAGROESTAB.ITEM,
    SUM(ITEMSALDO.SALDOQUANTIDADE) SALDO_CTB
    FROM ITEMAGROESTAB

    INNER JOIN ITEMSALDO ON
        ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB
        AND ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM
        AND ITEMSALDO.CODIGOSALDO = 5
    
    INNER JOIN SALDO ON
        SALDO.ESTAB = ITEMSALDO.ESTAB
        AND SALDO.ITEM = ITEMSALDO.ITEM
        AND SALDO.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND SALDO.LOCAL = ITEMSALDO.LOCAL
        AND SALDO.RK = 1
        --AND SALDO.DATA_MAX = (TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY'))
    
    GROUP BY
    ITEMAGROESTAB.ESTAB,ITEMAGROESTAB.ITEM
),
INVENTARIO AS (
    SELECT
    BASE.ESTAB,
    BASE.ITEM,
    BASE.SALDO_CTB,
    PCUSTO(BASE.ESTAB,BASE.ITEM,3,:DTCORTE,NULL,NULL) AS CUSTO_CTB
    FROM BASE
),
TERCEIROS AS (
    ---- 4: Em Terceiros
    ---- 13: De Terceiros
    SELECT
    NFCAB.ESTAB,
    NFITEM.ITEM,
    NATITEMSALDO.CODIGOSALDO,
    NFCAB.NOTACONF,
    NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0) AS SALDO_EMTERC,
    ARREDONDAR(
        DIVIDE(
            (NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0)) * NFITEM.CUSTOCMV, 
            COALESCE(ITEMPREMB.MULTIPLIC,1)
        ),2) AS CUSTO_EMTERC
    FROM NFCAB
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    LEFT JOIN ITEMPREMB ON 
    ITEMPREMB.ITEM = NFITEM.ITEM 
    AND ITEMPREMB.ESTAB = NFITEM.ESTAB

    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NATO ON 
        NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
        AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN NATITEMSALDO ON
        NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO 
        AND NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA 
        AND NATITEMSALDO.CODIGOSALDO in (4,13) 
        AND NATITEMSALDO.SOMADIMINUINADA_ITEM = 'S'

    LEFT JOIN ( 
        SELECT 
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        SUM(NFITEMAPARTIRDE.QUANTIDADE) AS QTD
        FROM NFITEMAPARTIRDE   
    
        INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEMAPARTIRDE.ESTAB AND
            NFCAB.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
                
        INNER JOIN NFCFG CONF ON CONF.NOTACONF = NFCAB.NOTACONF 
        INNER JOIN NATOPERACAO NATO ON 
            NATO.NATUREZADAOPERACAO = CONF.NATUREZADAOPERACAO AND
            NATO.ENTRADASAIDA = CONF.ENTRADASAIDA
        INNER JOIN NATITEMSALDO ON
            NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO AND
            NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA AND
            NATITEMSALDO.CODIGOSALDO in (4,13) AND
            NATITEMSALDO.SOMADIMINUINADA_ITEM = 'D'
                                
        WHERE NFCAB.DTENTSAI <= :DTCORTE
        GROUP BY NFITEMAPARTIRDE.ESTABORIGEM,NFITEMAPARTIRDE.SEQNOTAORIGEM,NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
    ) BAIXAS ON
        BAIXAS.ESTABORIGEM = NFITEM.ESTAB AND
        BAIXAS.SEQNOTAORIGEM = NFITEM.SEQNOTA AND
        BAIXAS.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM

    WHERE
    NFCAB.STATUS <> 'C'
    AND NFCAB.DTENTSAI <= :DTCORTE
    AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
    --AND NFCAB.NOTACONF IN (42,43,223,225,232,246,1013)
),
----- ###### DEPOSITO EM PODER DE TERCEIROS
DEPOSITO AS (
    SELECT
    NFCAB.ESTAB,
    NFITEM.ITEM,
    NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0) AS SALDO_EMTERC,
    ARREDONDAR(
        DIVIDE(
            (NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0)) * NFITEM.CUSTOCMV, 
            COALESCE(ITEMPREMB.MULTIPLIC,1)
        ),2) AS CUSTO_EMTERC
    FROM NFCAB
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    LEFT JOIN ITEMPREMB ON 
    ITEMPREMB.ITEM = NFITEM.ITEM 
    AND ITEMPREMB.ESTAB = NFITEM.ESTAB

    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NATO ON 
        NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
        AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN NATITEMSALDO ON
        NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO 
        AND NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA 
        AND NATITEMSALDO.CODIGOSALDO = 4 
        AND NATITEMSALDO.SOMADIMINUINADA_ITEM = 'S'

    LEFT JOIN ( 
        SELECT 
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        SUM(NFITEMAPARTIRDE.QUANTIDADE) AS QTD
        FROM NFITEMAPARTIRDE   
    
        INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEMAPARTIRDE.ESTAB AND
            NFCAB.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
                
        INNER JOIN NFCFG CONF ON CONF.NOTACONF = NFCAB.NOTACONF 
        INNER JOIN NATOPERACAO NATO ON 
            NATO.NATUREZADAOPERACAO = CONF.NATUREZADAOPERACAO AND
            NATO.ENTRADASAIDA = CONF.ENTRADASAIDA
        INNER JOIN NATITEMSALDO ON
            NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO AND
            NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA AND
            NATITEMSALDO.CODIGOSALDO = 4 AND
            NATITEMSALDO.SOMADIMINUINADA_ITEM = 'D'
                                
        WHERE NFCAB.DTENTSAI <= :DTCORTE
        GROUP BY NFITEMAPARTIRDE.ESTABORIGEM,NFITEMAPARTIRDE.SEQNOTAORIGEM,NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
    ) BAIXAS ON
        BAIXAS.ESTABORIGEM = NFITEM.ESTAB AND
        BAIXAS.SEQNOTAORIGEM = NFITEM.SEQNOTA AND
        BAIXAS.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM

    WHERE
    NFCAB.STATUS <> 'C'
    AND NFCAB.DTENTSAI <= :DTCORTE
    AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
    AND NFCAB.NOTACONF IN (42,43,223,225,232,246,1013)
),
----- ###### ESTOQUE DE TERCEIROS
DETERCEIRO AS (
    SELECT
    NFCAB.ESTAB,
    NFITEM.ITEM,
    NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0) AS SALDO_DETERC,
    ARREDONDAR(
        DIVIDE(
            (NFITEM.QUANTIDADE - COALESCE(BAIXAS.QTD,0)) * NFITEM.CUSTOCMV, 
            COALESCE(ITEMPREMB.MULTIPLIC,1)
        ),2) AS CUSTO_DETERC,
    NFITEM.CUSTOCMVP,
    NFITEM.CUSTOCMV
    FROM NFCAB
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    LEFT JOIN ITEMPREMB ON 
    ITEMPREMB.ITEM = NFITEM.ITEM 
    AND ITEMPREMB.ESTAB = NFITEM.ESTAB
    
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NATO ON 
        NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
        AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN NATITEMSALDO ON
        NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO 
        AND NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA 
        AND NATITEMSALDO.CODIGOSALDO = 13 
        AND NATITEMSALDO.SOMADIMINUINADA_ITEM = 'S'

    LEFT JOIN ( 
        SELECT 
        NFITEMAPARTIRDE.ESTABORIGEM,
        NFITEMAPARTIRDE.SEQNOTAORIGEM,
        NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
        SUM(NFITEMAPARTIRDE.QUANTIDADE) AS QTD
        FROM NFITEMAPARTIRDE   
    
        INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEMAPARTIRDE.ESTAB AND
            NFCAB.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
                
        INNER JOIN NFCFG CONF ON CONF.NOTACONF = NFCAB.NOTACONF 
        INNER JOIN NATOPERACAO NATO ON 
            NATO.NATUREZADAOPERACAO = CONF.NATUREZADAOPERACAO AND
            NATO.ENTRADASAIDA = CONF.ENTRADASAIDA
        INNER JOIN NATITEMSALDO ON
            NATITEMSALDO.NATUREZADAOPERACAO = NATO.NATUREZADAOPERACAO AND
            NATITEMSALDO.ENTRADASAIDA = NATO.ENTRADASAIDA AND
            NATITEMSALDO.CODIGOSALDO = 13 AND
            NATITEMSALDO.SOMADIMINUINADA_ITEM = 'D'
                                
        WHERE NFCAB.DTENTSAI <= :DTCORTE
        GROUP BY NFITEMAPARTIRDE.ESTABORIGEM,NFITEMAPARTIRDE.SEQNOTAORIGEM,NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
    ) BAIXAS ON
        BAIXAS.ESTABORIGEM = NFITEM.ESTAB AND
        BAIXAS.SEQNOTAORIGEM = NFITEM.SEQNOTA AND
        BAIXAS.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM

    WHERE
    NFCAB.STATUS <> 'C'
    AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
    AND NFCAB.DTENTSAI <= :DTCORTE
)
SELECT
DADOS.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
DADOS.ITEM,
ITEMAGRO.DESCRICAO AS PRODUTO,
ITEMAGRO.UNIDADE,
SUM(SALDO_CTB)SALDO_CTB,
ARREDONDAR(SUM(CUSTO_CTB),2) AS CUSTO_CTB,
SUM(SALDO_EMTERC)SALDO_EMTERC,
SUM(CUSTO_EMTERC)CUSTO_EMTERC,
SUM(SALDO_DETERC)SALDO_DETERC,
SUM(CUSTO_DETERC)CUSTO_DETERC

FROM(

SELECT
ESTAB,
ITEM,
SALDO_CTB,
SALDO_CTB * CUSTO_CTB as CUSTO_CTB,
0 SALDO_EMTERC,
0 CUSTO_EMTERC,
0 SALDO_DETERC,
0 CUSTO_DETERC
FROM INVENTARIO
WHERE SALDO_CTB <> 0

UNION ALL

SELECT
ESTAB,
ITEM,
0 SALDO_CTB,
0 CUSTO_CTB,
SALDO_EMTERC,
CUSTO_EMTERC,
0 SALDO_DETERC,
0 CUSTO_DETERC
FROM DEPOSITO
WHERE SALDO_EMTERC <> 0

UNION ALL

SELECT
ESTAB,
ITEM,
0 SALDO_CTB,
0 CUSTO_CTB,
0 SALDO_EMTERC,
0 CUSTO_EMTERC,
SALDO_DETERC,
CUSTO_DETERC
FROM DETERCEIRO
WHERE SALDO_DETERC <> 0
)DADOS

INNER JOIN FILIAL ON FILIAL.ESTAB = DADOS.ESTAB
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = DADOS.ITEM
GROUP BY DADOS.ESTAB,DADOS.ITEM,ITEMAGRO.DESCRICAO,ITEMAGRO.UNIDADE,FILIAL.REDUZIDO