WITH BASE AS (
    SELECT
    M.ESTAB,
    M.ITEM,
    M.DOC,
    M.SEQ,
    NFITEM.SEQNOTAITEM,
    NFCFG.ENTRADASAIDA,
    NATO.NATUREZADAOPERACAO,
    NATO.TIPODCTO,
    M.DATAMOVIM,
    M.HORAMOVIM,
    NFITEM.VALORTOTAL,
    ARREDONDAR(NFITEM.CUSTOCMV*M.QUANTIDADE,2) AS CUSTO_NOTA,
    M.QUANTIDADE,
    SUM(CASE
        WHEN M.SOMADIMINUI = 'D' THEN M.QUANTIDADE *-1 ELSE M.QUANTIDADE
    END)
    OVER (
        PARTITION BY M.ESTAB, M.ITEM
        ORDER BY M.ESTAB,M.ITEM,M.DATAMOVIM,
        TO_DATE(
                SUBSTR(M.HORAMOVIM,1,6) ||
                LPAD(
                    LEAST(
                        TO_NUMBER(SUBSTR(M.HORAMOVIM,7,2)),
                        59
                    ),
                    2,
                    '0'
                ),
                'HH24:MI:SS'
            )
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )  AS SALDO_QTD
    FROM MOVITEMAGRO M
    INNER JOIN NFCAB ON
        NFCAB.ESTAB = M.ESTAB
        AND NFCAB.SEQNOTA = M.SEQ
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = M.ESTAB
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NATO ON 
        NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
        AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
        AND NFITEM.ITEM = M.ITEM
        AND NFITEM.QUANTIDADE = M.QUANTIDADE
        
    WHERE
    M.CODIGOSALDO = 5
    AND U_TEMPRESA.OUTROS = 'N'

),
DEVOL AS (
    SELECT
    *
    FROM BASE
    WHERE
    BASE.SALDO_QTD = 0 AND BASE.TIPODCTO = 'D' AND BASE.DATAMOVIM >= :DTBASE --AND BASE.DIF <> 0
),
IMP AS (
    SELECT
    N.ESTAB,
    N.SEQNOTA,
    N.SEQNOTAITEM,
    NVL(SUM(VALORIMPOSTO),0) AS VALORIMPOSTO,
    NVL(SUM(VALORDESONERACAO),0) AS VALORDESONERACAO
    FROM NFITEMIMPOSTO N
    INNER JOIN DEVOL ON
        DEVOL.ESTAB = N.ESTAB
        AND DEVOL.SEQ = N.SEQNOTA
    GROUP BY N.ESTAB,N.SEQNOTA,N.SEQNOTAITEM
),
DADOS AS (
    SELECT
    DEVOL.*,
    DEVOL.VALORTOTAL - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0) AS VLR_CTB,
    DEVOL.CUSTO_NOTA - (DEVOL.VALORTOTAL - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0)) as DIF
    FROM DEVOL
    LEFT JOIN IMP ON
        IMP.ESTAB = DEVOL.ESTAB
        AND IMP.SEQNOTA = DEVOL.SEQ
        AND IMP.SEQNOTAITEM = DEVOL.SEQNOTAITEM
    WHERE
    (DEVOL.CUSTO_NOTA - (DEVOL.VALORTOTAL - IMP.VALORIMPOSTO - NVL(IMP.VALORDESONERACAO,0))) <> 0
)
SELECT
D.ESTAB,
D.ITEM,
D.DOC,
D.SEQ,
TO_CHAR(D.DATAMOVIM,'DD/MM/YYYY') AS DATAMOVIM,
D.HORAMOVIM,
D.VALORTOTAL,
D.CUSTO_NOTA,
ARREDONDAR(CASE
    WHEN D.ENTRADASAIDA = 'E' AND D.TIPODCTO <> 'D' THEN PCUSTO(D.ESTAB, D.ITEM, 2, D.DATAMOVIM, NULL, NULL)
    WHEN D.TIPODCTO = 'D' AND D.NATUREZADAOPERACAO = 'DC' THEN PCUSTO(D.ESTAB, D.ITEM, 2, NFI.DTEMISSAO, NULL, NULL)
    ELSE PCUSTO(D.ESTAB, D.ITEM, 3, D.DATAMOVIM, NULL, NULL)
END,2) AS CUSTO_MEDIO,
D.QUANTIDADE AS QTD_DC,
D.VLR_CTB,
D.DIF
FROM DADOS D

INNER JOIN NFITEM ON
    NFITEM.ESTAB = D.ESTAB
    AND NFITEM.SEQNOTA = D.SEQ
    AND NFITEM.ITEM = D.ITEM
    
LEFT JOIN NFITEMAPARTIRDE PARTIRDE ON
    PARTIRDE.ESTABORIGEM = NFITEM.ESTABORIGEM
    AND PARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTAORIGEM
    AND PARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEMORIGEM
    AND PARTIRDE.ESTAB = NFITEM.ESTAB
    AND PARTIRDE.SEQNOTA = NFITEM.SEQNOTA
    AND PARTIRDE.SEQNOTAITEM = NFITEM.SEQNOTAITEM

LEFT JOIN NFITEM NFI ON
    NFI.ESTAB = PARTIRDE.ESTABORIGEM
    AND NFI.SEQNOTA = PARTIRDE.SEQNOTAORIGEM
    AND NFI.SEQNOTAITEM = PARTIRDE.SEQNOTAITEMORIGEM
    AND NFI.ITEM = D.ITEM