WITH BASE AS (
SELECT
M.ESTAB,
M.ITEM,
M.DOC,
M.SEQ,
NFCFG.ENTRADASAIDA,
NATO.NATUREZADAOPERACAO,
NATO.TIPODCTO,
M.DATAMOVIM,
M.HORAMOVIM,
NFITEM.VALORTOTAL,
ARREDONDAR(NFITEM.CUSTOCMV*M.QUANTIDADE,2) AS CUSTO_NOTA,
M.QUANTIDADE,
IMP.VALORIMPOSTO,
NFITEM.VALORTOTAL - IMP.VALORIMPOSTO AS VLR_CTB,
ARREDONDAR(NFITEM.CUSTOCMV*M.QUANTIDADE,2) - (NFITEM.VALORTOTAL - IMP.VALORIMPOSTO) as DIF,
SUM(CASE
    WHEN M.SOMADIMINUI = 'D' THEN M.QUANTIDADE *-1 ELSE M.QUANTIDADE
END)
OVER (
    PARTITION BY M.ESTAB, M.ITEM
    ORDER BY TO_TIMESTAMP(
    TO_CHAR(DATAMOVIM, 'DD/MM/YYYY') || ' ' || HORAMOVIM,
    'DD/MM/YYYY HH24:MI:SS'
        )
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )  AS SALDO_QTD
FROM MOVITEMAGRO M
INNER JOIN NFCAB ON
    NFCAB.ESTAB = M.ESTAB
    AND NFCAB.SEQNOTA = M.SEQ
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = M.ESTAB
INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
INNER JOIN NATOPERACAO NATO ON 
    NATO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO 
    AND NATO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
INNER JOIN NFITEM ON
    NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    AND NFITEM.ITEM = M.ITEM
    
LEFT JOIN NFITEMIMPOSTO IMP ON
    IMP.ESTAB = NFITEM.ESTAB
    AND IMP.SEQNOTA = NFITEM.SEQNOTA
    AND IMP.SEQNOTAITEM = NFITEM.SEQNOTAITEM
    AND IMP.IMPOSTO = 1    
    
WHERE
M.CODIGOSALDO = 5
AND U_TEMPRESA.INSUMOS ='S'
),
DEVOL AS (
SELECT
*
FROM BASE
WHERE
BASE.SALDO_QTD = 0 AND BASE.NATUREZADAOPERACAO = 'DC' AND BASE.DATAMOVIM >= '01/02/2026' AND BASE.DIF <> 0
)
SELECT
D.ESTAB,
D.ITEM,
D.DOC,
D.SEQ,
D.DATAMOVIM,
D.HORAMOVIM,
D.VALORTOTAL,
D.CUSTO_NOTA,
ARREDONDAR(CASE
    WHEN D.ENTRADASAIDA = 'E' AND D.TIPODCTO <> 'D' THEN PCUSTO(D.ESTAB, D.ITEM, 2, D.DATAMOVIM, NULL, NULL)
    WHEN D.TIPODCTO = 'D' AND D.NATUREZADAOPERACAO = 'DC' THEN PCUSTO(D.ESTAB, D.ITEM, 2, NFI.DTEMISSAO, NULL, NULL)
    ELSE PCUSTO(D.ESTAB, D.ITEM, 3, D.DATAMOVIM, NULL, NULL)
END,2) AS CUSTO_MEDIO,
D.QUANTIDADE AS QTD_DC,
D.VLR_CTB,
D.DIF
FROM DEVOL D

INNER JOIN NFITEM ON
    NFITEM.ESTAB = D.ESTAB
    AND NFITEM.SEQNOTA = D.SEQ
    AND NFITEM.ITEM = D.ITEM
    
LEFT JOIN NFITEMAPARTIRDE PARTIRDE ON
    PARTIRDE.ESTABORIGEM = NFITEM.ESTABORIGEM
    AND PARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTAORIGEM
    AND PARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEMORIGEM
    AND PARTIRDE.ESTAB = NFITEM.ESTAB
    AND PARTIRDE.SEQNOTA = NFITEM.SEQNOTA
    AND PARTIRDE.SEQNOTAITEM = NFITEM.SEQNOTAITEM

LEFT JOIN NFITEM NFI ON
    NFI.ESTAB = PARTIRDE.ESTABORIGEM
    AND NFI.SEQNOTA = PARTIRDE.SEQNOTAORIGEM
    AND NFI.SEQNOTA = PARTIRDE.SEQNOTAORIGEM
    AND NFI.ITEM = D.ITEM