WITH 
PERIODO AS (
    SELECT TO_CHAR(:DTINI) AS DATAINI, TO_CHAR(:DTFIM) AS DATAFIM FROM DUAL
),

ESTAB AS (
    SELECT ESTAB AS EMPRESA FROM FILIAL
    WHERE (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
),

ICMS_RECUPERAR AS (
SELECT 
F.*
FROM TABLE(PRELEXTRATOCONTACENTROCUSTO(1, :DTINI, :DTFIM, NULL,
                                         11601, NULL, NULL, NULL, NULL)) F

WHERE F.RCONTROLE IS NOT NULL),

ICMS_RECOLHER AS (
SELECT 
F.*
FROM TABLE(PRELEXTRATOCONTACENTROCUSTO(1, :DTINI, :DTFIM, NULL,
                                         21401, NULL, NULL, NULL, NULL)) F

WHERE F.RCONTROLE IS NOT NULL),

FISCAL_ENT AS (
SELECT * FROM ESTAB
INNER JOIN TABLE(VIASOFTFISCAL.FRELATORIOICMS(EMPRESA,NULL, :DTINI, :DTFIM, NULL)) ENT ON 0=0
WHERE MOVIMENTO = 'E'),

FISCAL_SAI AS (
SELECT * FROM ESTAB
INNER JOIN TABLE(VIASOFTFISCAL.FRELATORIOICMS(EMPRESA,NULL, :DTINI, :DTFIM, NULL)) SAI ON 0=0
WHERE MOVIMENTO = 'S'),

BASE AS (
SELECT 
'Contábil' AS LOCAL,
 TO_NUMBER(SUBSTR(CCENTROCUS,0,2)) AS ESTAB,
COALESCE(SUM(RVALOR/2),0) + (SELECT COALESCE(SUM(REC.RVLRDEBITO/2),0) FROM ICMS_RECOLHER REC WHERE REC.RCENTROPAI = TO_NUMBER(SUBSTR(i.CCENTROCUS,0,2))) AS ICMS_ENTRADA,
0 AS ICMS_SAIDA
 FROM ICMS_RECUPERAR i
 
 GROUP BY TO_NUMBER(SUBSTR(CCENTROCUS,0,2))
 
 UNION ALL
 
 SELECT 
'Contábil' AS LOCAL,
 TO_NUMBER(SUBSTR(CCENTROCUS,0,2)) AS ESTAB,
0 AS ICMS_ENTRADA,
COALESCE(SUM(RVALOR/2),0) - COALESCE(SUM(RVLRDEBITO/2),0) AS ICMS_SAIDA
 FROM ICMS_RECOLHER
 
GROUP BY TO_NUMBER(SUBSTR(CCENTROCUS,0,2))

UNION 

SELECT 
'Fiscal' AS LOCAL,
 ESTAB,
SUM(COALESCE(VALIMP,0)) ICMS_ENTRADA,
0 AS ICMS_SAIDA

FROM FISCAL_ENT

GROUP BY ESTAB

UNION 

SELECT 
'Fiscal' AS LOCAL,
 ESTAB,
0 ICMS_ENTRADA,
SUM(COALESCE(VALIMP,0)) AS ICMS_SAIDA

FROM FISCAL_SAI
GROUP BY ESTAB
),
DADOS AS (
SELECT 
LOCAL,
FILIAL.ESTAB,
FILIAL.ESTAB || ' - ' || REDUZIDO AS FILIAL,
COALESCE(SUM(ICMS_ENTRADA),0) ICMS_ENTRADA,
COALESCE(SUM(ICMS_SAIDA),0) ICMS_SAIDA

 FROM BASE
 JOIN FILIAL ON FILIAL.ESTAB = BASE.ESTAB
 GROUP BY LOCAL, FILIAL.ESTAB, REDUZIDO
 
 ORDER BY 1, FILIAL.ESTAB)
 
, UNPIVOTED AS (
  SELECT 
    FILIAL,
    LOCAL,
    'ICMS Entrada' AS TIPO,
    ICMS_ENTRADA AS VALOR
  FROM DADOS
  UNION ALL
  SELECT 
    FILIAL,
    LOCAL,
    'ICMS Saída' AS TIPO,
    ICMS_SAIDA AS VALOR
  FROM DADOS
)
SELECT 
  FILIAL,
  TIPO,
  COALESCE(CONTABIL, 0) AS CONTABIL,
  COALESCE(FISCAL, 0) AS FISCAL
FROM UNPIVOTED
PIVOT (
  MAX(VALOR) FOR LOCAL IN ('Contábil' AS CONTABIL, 'Fiscal' AS FISCAL)
)
WHERE CONTABIL > 0 OR FISCAL > 0 
ORDER BY FILIAL, TIPO