WITH CONF_1041 AS
    (SELECT
        NFITEM_1.ITEM,
     --   NFCAB_1.NOTACONF,
        NFITEMAPARTIRDE.ESTAB,
        COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE), 0) AS QTDBX
    FROM NFITEMAPARTIRDE
        INNER JOIN NFITEM NFITEM_1
            ON NFITEM_1.ESTAB = NFITEMAPARTIRDE.ESTAB AND NFITEM_1.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND NFITEM_1.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
            LEFT JOIN NFCAB NFCAB_1
                ON NFCAB_1.ESTAB = NFITEM_1.ESTAB AND NFCAB_1.SEQNOTA = NFITEM_1.SEQNOTA
    WHERE
        NFCAB_1.NOTACONF IN (1041)
        AND NFCAB_1.DTEMISSAO BETWEEN '01/01/2000' AND :DTFIM
    GROUP BY
        NFITEM_1.ITEM,
     --   NFCAB_1.NOTACONF,
        NFITEMAPARTIRDE.ESTAB
    )
SELECT
    DADOS_GERAIS.ESTAB,
    DADOS_GERAIS.FILIAL,
    DADOS_GERAIS.PRODUTO,
    SUM(DADOS_GERAIS.AFIXAR_QTD) AS AFIXAR_QTD, -- QUANTIDADE TOTAL DO NFITEM (CONF 358)
    SUM(DADOS_GERAIS.FIXACAO_QTD) AS FIXACAO_QTD, -- QUANTIDADE BAIXADA (CONF 359)
    COALESCE(CONF_1041.QTDBX, 0) AS DEVOL_CONF1041, -- QUANTIDADE DEVOLUÇÃO (CONF 1041)
    (SUM(DADOS_GERAIS.AFIXAR_QTD) - (SUM(DADOS_GERAIS.FIXACAO_QTD) + COALESCE(CONF_1041.QTDBX, 0))) AS SALDO_QTD, -- QUANTIDADE LÍQUIDA (TOTAL NFITEM - BAIXADO E DEVOLUÇÃO)
    SUM(DADOS_GERAIS.VLR_AFIXAR) AS AFIXAR_VLR, -- VALOR TOTAL DO NFITEM (CONF 358)
    (SUM(DADOS_GERAIS.VALORUNITARIO) / SUM(DADOS_GERAIS.CONTAGEM)) * DIVIDE((SUM(DADOS_GERAIS.AFIXAR_QTD) - SUM(DADOS_GERAIS.FIXACAO_QTD) - COALESCE(CONF_1041.QTDBX, 0)), 60) AS FIXACAO_VLR -- VALOR LÍQ.
FROM
    (SELECT
        1 AS CONTAGEM,
        NFCAB.ESTAB,
        FILIAL.REDUZIDO AS FILIAL,
        NFITEM.SEQNOTA,
        NFITEM.SEQNOTAITEM,
        NFITEM.VALORUNITARIO,
        ITEMAGRO.ITEM,
        (ITEMAGRO.ITEM || ' - ' || ITEMAGRO.DESCRICAO) AS PRODUTO,
        NFITEM.QUANTIDADE AS AFIXAR_QTD,
        COALESCE(BAIXADO.QTDBX, 0) AS FIXACAO_QTD,
        NFITEM.VALORTOTAL AS VLR_AFIXAR/*,
        NFITEM.QUANTIDADE - COALESCE(BAIXADO.QTDBX, 0) AS SALDO_QTD,
        NFITEM.VALORTOTAL - COALESCE(BAIXADO.VLRBX, 0) AS SALDO_VLR,
        NFITEM.VALORUNITARIO * DIVIDE((NFITEM.QUANTIDADE - COALESCE(BAIXADO.QTDBX, 0)), 60) AS VLR_FIXACAO*/
    FROM NFCAB
        INNER JOIN FILIAL
            ON FILIAL.ESTAB = NFCAB.ESTAB
        INNER JOIN NFITEM
            ON NFITEM.ESTAB = NFCAB.ESTAB AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
            LEFT JOIN ITEMAGRO
                ON ITEMAGRO.ITEM = NFITEM.ITEM
    LEFT JOIN
        (SELECT
            NFCAB_1.NOTACONF,
            NFITEMAPARTIRDE.ESTABORIGEM,
            NFITEMAPARTIRDE.SEQNOTAORIGEM,
            NFITEMAPARTIRDE.SEQNOTAITEMORIGEM,
            COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE), 0) AS QTDBX
        FROM NFITEMAPARTIRDE
            INNER JOIN NFITEM NFITEM_1
                ON NFITEM_1.ESTAB = NFITEMAPARTIRDE.ESTAB AND NFITEM_1.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND NFITEM_1.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
                LEFT JOIN NFCAB NFCAB_1
                    ON NFCAB_1.ESTAB = NFITEM_1.ESTAB AND NFCAB_1.SEQNOTA = NFITEM_1.SEQNOTA
        WHERE
            NFCAB_1.NOTACONF IN (359)
            AND NFCAB_1.DTEMISSAO BETWEEN '01/01/2000' AND :DTFIM
        GROUP BY
            NFCAB_1.NOTACONF,
            NFITEMAPARTIRDE.ESTABORIGEM,
            NFITEMAPARTIRDE.SEQNOTAORIGEM,
            NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
        ) BAIXADO
        ON BAIXADO.ESTABORIGEM = NFITEM.ESTAB
        AND BAIXADO.SEQNOTAORIGEM = NFITEM.SEQNOTA
        AND BAIXADO.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
    WHERE 
        NFCAB.NOTACONF = 358
        --AND NFCAB.SEQNOTA = 4975
        --AND NFCAB.ESTAB = 36
        AND NFCAB.DTEMISSAO BETWEEN '01/01/2000' AND :DTFIM
        AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
    ) DADOS_GERAIS
    LEFT JOIN CONF_1041
        ON DADOS_GERAIS.ITEM = CONF_1041.ITEM
        AND DADOS_GERAIS.ESTAB = CONF_1041.ESTAB
GROUP BY
    DADOS_GERAIS.ESTAB,
    DADOS_GERAIS.FILIAL,
    DADOS_GERAIS.PRODUTO,
    CONF_1041.QTDBX