WITH CONF_1041 AS (
    SELECT
    NFITEM_1.ITEM,
    NFITEMAPARTIRDE.ESTAB,
    COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE), 0) AS QTDBX
    FROM NFITEMAPARTIRDE
    INNER JOIN NFITEM NFITEM_1 ON 
        NFITEM_1.ESTAB = NFITEMAPARTIRDE.ESTAB 
        AND NFITEM_1.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA 
        AND NFITEM_1.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
    
    LEFT JOIN NFCAB NFCAB_1 ON 
        NFCAB_1.ESTAB = NFITEM_1.ESTAB 
        
        AND NFCAB_1.SEQNOTA = NFITEM_1.SEQNOTA
    WHERE
        NFCAB_1.NOTACONF IN (1041)
        AND NFCAB_1.DTEMISSAO <= :DTFIM
    GROUP BY
        NFITEM_1.ITEM,
        NFITEMAPARTIRDE.ESTAB
),
NOTAS AS (
    SELECT
    1 AS CONTAGEM,
    NFCAB.ESTAB,
    FILIAL.REDUZIDO AS FILIAL,
    NFITEM.SEQNOTA,
    NFITEM.SEQNOTAITEM,
    NFITEM.VALORUNITARIO,
    ITEMAGRO.ITEM,
    (ITEMAGRO.ITEM || ' - ' || ITEMAGRO.DESCRICAO) AS PRODUTO,
    NFITEM.QUANTIDADE AS AFIXAR_QTD,
    NFITEM.VALORTOTAL AS VLR_AFIXAR
    FROM NFCAB
    INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
    INNER JOIN NFITEM ON 
        NFITEM.ESTAB = NFCAB.ESTAB 
        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    WHERE
    NFCAB.NOTACONF = 358
    AND NFCAB.DTEMISSAO <= :DTFIM
    AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
),
PARTIRDE AS (
    SELECT
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    N.SEQNOTAITEMORIGEM,
    SUM(N.QUANTIDADE) AS BX
    FROM NFITEMAPARTIRDE N
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = N.ESTABORIGEM
        AND NOTAS.SEQNOTA = N.SEQNOTAORIGEM
        AND NOTAS.SEQNOTAITEM = N.SEQNOTAITEMORIGEM
    INNER JOIN NFCAB NF ON
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    WHERE NF.NOTACONF IN (359)
    AND NF.DTEMISSAO <= :DTFIM
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM,N.SEQNOTAITEMORIGEM
)
SELECT
DADOS.ESTAB,
DADOS.FILIAL,
DADOS.PRODUTO,
SUM(DADOS.AFIXAR_QTD) AS AFIXAR_QTD, -- QUANTIDADE TOTAL DO NFITEM (CONF 358)
SUM(DADOS.FIXACAO_QTD) AS FIXACAO_QTD, -- QUANTIDADE BAIXADA (CONF 359)
COALESCE(CONF_1041.QTDBX, 0) AS DEVOL_CONF1041, -- QUANTIDADE DEVOLUÇÃO (CONF 1041)
(SUM(DADOS.AFIXAR_QTD) - (SUM(DADOS.FIXACAO_QTD) + COALESCE(CONF_1041.QTDBX, 0))) AS SALDO_QTD, -- QUANTIDADE LÍQUIDA (TOTAL NFITEM - BAIXADO E DEVOLUÇÃO)
SUM(DADOS.VLR_AFIXAR) AS AFIXAR_VLR, -- VALOR TOTAL DO NFITEM (CONF 358)
SUM(
    (DADOS.VALORUNITARIO) --/ (DADOS_GERAIS.CONTAGEM)
    * 
    DIVIDE(
        (DADOS.AFIXAR_QTD) - COALESCE(DADOS.FIXACAO_QTD,0)
        ,60)
    ) -
    SUM(DADOS.VALORUNITARIO) / SUM(DADOS.CONTAGEM)* DIVIDE(COALESCE(CONF_1041.QTDBX,0),60)
    
    AS FIXACAO_VLR 
    
FROM(

SELECT
NOTAS.CONTAGEM,
NOTAS.ESTAB,
NOTAS.FILIAL,
NOTAS.SEQNOTA,
NOTAS.SEQNOTAITEM,
NOTAS.VALORUNITARIO,
NOTAS.ITEM,
NOTAS.PRODUTO,
NOTAS.AFIXAR_QTD,
NOTAS.VLR_AFIXAR,
COALESCE(PARTIRDE.BX, 0) AS FIXACAO_QTD
FROM NOTAS

LEFT JOIN PARTIRDE ON
    NOTAS.ESTAB = PARTIRDE.ESTABORIGEM
    AND NOTAS.SEQNOTA = PARTIRDE.SEQNOTAORIGEM
    AND NOTAS.SEQNOTAITEM = PARTIRDE.SEQNOTAITEMORIGEM
    
)DADOS

LEFT JOIN CONF_1041 ON 
    DADOS.ITEM = CONF_1041.ITEM
    AND DADOS.ESTAB = CONF_1041.ESTAB
    
GROUP BY
    DADOS.ESTAB,
    DADOS.FILIAL,
    DADOS.PRODUTO,
    CONF_1041.QTDBX