-- SALDO SOJA NOVO
WITH MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO

    --INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ISALDO.ESTAB
    WHERE
    codigosaldo in (7,8,2,20,26,28,6,11)
  -- AND (0 IN (:ESTAB) OR U_TEMPRESA.ESTABC IN (:ESTAB))
    GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO
),
-- ############## SALDO DOS ITENS ############
BASE_DADOS AS (
    SELECT 
        ISALDO.codigosaldo,
        IESTAB.ESTAB,
        IESTAB.ITEM ,
        U_TEMPRESA.ESTABC,
        F.REDUZIDO AS ESTABESTOQUE,
        FILIAL.REDUZIDO AS FILIAL,
        CIDADE.NOME AS GR_ESTAB,
        IA.DESCRICAO || '-' || IESTAB.ITEM AS DESCRICAO_CULTIVAR,
        IA.UNIDADE,
        IMARCA.DESCRICAO AS SEMENTEIRA,
        IMARCA.MARCA,
        IA.PESOLIQUIDO AS KGLT,
        U_AGRPROD.U_AGRPROD_ID AGR,
        U_AGRPROD.U_AGRPROD_ID ||'-'||U_AGRPROD.DESCAGRUPA CULTIVAR,
        SUM(ISALDO.SALDOQUANTIDADE) AS SALDO,
        SUM(ISALDO.SALDOQUANTIDADE) * IA.PESOLIQUIDO AS SALDOKG

    FROM ITEMAGROESTAB IESTAB
    LEFT JOIN ITEMSALDO ISALDO ON 
        ISALDO.ITEM = IESTAB.ITEM 
        AND ISALDO.ESTAB = IESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ISALDO.ITEM 
        AND MD.ESTAB = ISALDO.ESTAB 
        AND MD.CODIGOSALDO = ISALDO.CODIGOSALDO
        AND TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    LEFT JOIN FILIAL ON FILIAL.ESTAB = IESTAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

    INNER JOIN ITEMAGRO IA ON 
        IA.ITEM = IESTAB.ITEM 
            AND IA.ATIVO = 'S'

    LEFT JOIN ITEMMARCA IMARCA ON IMARCA.MARCA = IA.MARCA
    LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = IA.ITEM
    LEFT JOIN ITEMGRUPO ON  ITEMGRUPO.GRUPO = IA.GRUPO
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
    LEFT JOIN u_gestoque ON itemgrupo_u.u_gestoque_id = u_gestoque.u_gestoque_id

    LEFT JOIN FILIAL F ON F.ESTAB = U_TEMPRESA.ESTABC

    LEFT JOIN CIDADE ON CIDADE.CIDADE = f.CIDADE

    LEFT JOIN U_AGRPROD 
      ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID    <> 205

    WHERE (U_TEMPRESA.ESTABC IN (:ESTAB) or 0 in (:ESTAB))
        and ITEMGRUPO.GRUPO = 62
      AND IA.ATIVO = 'S'
      and ISALDO.codigosaldo in (7,8,2,20,26,28,6,11)

    GROUP BY IESTAB.ESTAB, IESTAB.ITEM, U_TEMPRESA.ESTABC, FILIAL.REDUZIDO, CIDADE.NOME,
             IA.DESCRICAO, IA.UNIDADE,
             IMARCA.DESCRICAO, IA.PESOLIQUIDO,ISALDO.CODIGOSALDO,F.REDUZIDO,IMARCA.MARCA,U_AGRPROD.U_AGRPROD_ID,U_AGRPROD.DESCAGRUPA
),
/*
-- ############## NOTAS QUE BAIXARAM VENDA FUTURA ##############
NFCAB_BAIXADO AS (
    SELECT
      NFITEM_DESTI.ESTAB,
        NFITEM_DESTI.ITEM,
        SUM(NFITEMAPARTIRDE.QUANTIDADE) AS QUANTIDADE,
        SUM(NFITEM_DESTI.VALORTOTAL) AS VALORTOTAL
    FROM NFITEMAPARTIRDE
    INNER JOIN NFITEM NFITEM_DESTI
        ON NFITEM_DESTI.ESTAB = NFITEMAPARTIRDE.ESTAB
        AND NFITEM_DESTI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
        AND NFITEM_DESTI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
    INNER JOIN NFCAB
        ON NFCAB.ESTAB = NFITEM_DESTI.ESTAB
        AND NFCAB.SEQNOTA = NFITEM_DESTI.SEQNOTA
    INNER JOIN NFCFG
        ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO
        ON NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    LEFT JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP ON u_tipoop.u_tipoop_id = nfcfg_u.u_tipoop_id

    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM_DESTI.ITEM
    LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    LEFT JOIN ITEMGRUPO ON  ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
    LEFT JOIN u_gestoque ON itemgrupo_u.u_gestoque_id = u_gestoque.u_gestoque_id

    LEFT JOIN U_AGRPROD 
      ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID    <> 205

    left join nfitem nfite on
        nfite.estab = NFITEMAPARTIRDE.ESTABORIGEM
        and nfite.seqnota = NFITEMAPARTIRDE.SEQNOTAORIGEM
        and nfite.seqnotaitem = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM

   -- INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB =NFITEMAPARTIRDE.ESTAB 

    WHERE NFCFG.ENTRADASAIDA = 'S'
      AND NATOPERACAO.TIPODCTO = 'N'
      AND COALESCE(NFCAB.STATUS,'-') <> 'C'
      AND U_TIPOOP.TIPOOP IN ('RF')
      AND nfite.DTEMISSAO >= :DTINIVEND
   --   AND U_TEMPRESA.ESTABC IN (:ESTAB)
      AND ITEMGRUPO.GRUPO = 62

     GROUP BY 
     NFITEM_DESTI.ESTAB,
        NFITEM_DESTI.ITEM
),

-- ############## NOTAS DE DEVOLUCAO/DESFAZIMENTO ##############
NFCAB_CANCELADO AS (
    SELECT
      NFITEM_DESTI.ITEM,
      NFITEM_DESTI.ESTAB,
    --  NFCAB.NUMEROCM,
     -- NFCAB.REPRESENT,
        SUM(NFITEM_DESTI.QUANTIDADE) AS QUANTIDADE,
        SUM(NFITEM_DESTI.VALORTOTAL) AS VALORTOTAL
    FROM NFITEMAPARTIRDE
    INNER JOIN NFITEM NFITEM_DESTI
        ON NFITEM_DESTI.ESTAB = NFITEMAPARTIRDE.ESTAB
        AND NFITEM_DESTI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
        AND NFITEM_DESTI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
    INNER JOIN NFCAB
        ON NFCAB.ESTAB = NFITEM_DESTI.ESTAB
        AND NFCAB.SEQNOTA = NFITEM_DESTI.SEQNOTA
    INNER JOIN NFCFG
        ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO
        ON NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA

     LEFT JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP ON u_tipoop.u_tipoop_id = nfcfg_u.u_tipoop_id 

    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM_DESTI.ITEM
    LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    LEFT JOIN ITEMGRUPO ON  ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
    LEFT JOIN u_gestoque ON itemgrupo_u.u_gestoque_id = u_gestoque.u_gestoque_id

    LEFT JOIN U_AGRPROD 
      ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID    <> 205

    left join nfitem nfite on
        nfite.estab = NFITEMAPARTIRDE.ESTABORIGEM
        and nfite.seqnota = NFITEMAPARTIRDE.SEQNOTAORIGEM
        and nfite.seqnotaitem = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM

  --  INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = NFITE.ESTAB

    WHERE NFCFG.ENTRADASAIDA = 'E'
      AND NATOPERACAO.TIPODCTO = 'D'
      AND COALESCE(NFCAB.STATUS,'-') <> 'C'
      and u_tipoop.tipoop in ('DF-V','DV')
      AND ITEMGRUPO.GRUPO = 62
   --   AND U_TEMPRESA.ESTABC IN (:ESTAB)
      AND nfite.dtemissao >= :DTINIVEND

      GROUP BY
     NFITEM_DESTI.ESTAB,
        NFITEM_DESTI.ITEM
),

-- ############## VENDAS ##############
VENDAS AS (
    SELECT
    u_tipoop.tipoop,
    FILIAL.ESTAB,
            ITEMAGRO.ITEM  AS ITEM,
            u_tempresa.estabc,
            F.REDUZIDO AS ESTABESTOQUE,
            FILIAL.REDUZIDO AS FILIAL,
            CIDADE.NOME AS GR_ESTAB,
           -- PREPRESE.DESCRICAO AS  REPRESENT,
           -- CONTAMOV.NOME AS CLIENTE,
           -- CONTAMOV.NUMEROCM,
          --  PREPRESE.REPRESENT AS COD_RTV,
            ITEMAGRO.DESCRICAO||'-'||ITEMAGRO.ITEM AS DESCRICAO_CULTIVAR,
             ITEMAGRO.UNIDADE,
             ITEMMARCA.MARCA,
           ITEMMARCA.descricao  AS SEMENTEIRA,
            ITEMAGRO.PESOLIQUIDO AS KGLT,
            U_AGRPROD.U_AGRPROD_ID AGR,
            U_AGRPROD.U_AGRPROD_ID ||'-'||U_AGRPROD.DESCAGRUPA CULTIVAR,
            SUM(NFITEM.QUANTIDADE) AS VF,
            SUM(COALESCE((NFITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO),0)) VF_KG
    FROM NFCAB

    INNER JOIN FILIAL ON  FILIAL.ESTAB = NFCAB.ESTAB

    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN NFCFG ON  NFCFG.NOTACONF = NFCAB.NOTACONF
    LEFT JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP ON u_tipoop.u_tipoop_id = nfcfg_u.u_tipoop_id

    INNER JOIN NATOPERACAO
      ON NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
      AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA

    INNER JOIN NFITEM
      ON  NFITEM.ESTAB = NFCAB.ESTAB
      AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    INNER JOIN ITEMAGRO ON  ITEMAGRO.ITEM = NFITEM.ITEM
    LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM  
    LEFT JOIN ITEMMARCA ON  ITEMMARCA.MARCA = ITEMAGRO.MARCA
    LEFT JOIN ITEMGRUPO ON  ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO  
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
    LEFT JOIN u_gestoque ON itemgrupo_u.u_gestoque_id = u_gestoque.u_gestoque_id   

    LEFT JOIN FILIAL F ON F.ESTAB = U_TEMPRESA.ESTABC
    LEFT JOIN CIDADE ON CIDADE.CIDADE = F.CIDADE

    LEFT JOIN U_AGRPROD 
      ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID    <> 205

    -- LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
   --  LEFT JOIN PREPRESE ON PREPRESE.REPRESENT = NFCAB.REPRESENT

    WHERE
    COALESCE(NFCAB.STATUS,'-') <> 'C'
        AND NFCAB.DTEMISSAO BETWEEN :DTINIVEND AND CURRENT_DATE
  	and itemgrupo.grupo = 62
        AND u_tempresa.estabc IN (:ESTAB)
        AND  u_tipoop.tipoop IN ('VF','V')

        GROUP BY
        u_tipoop.tipoop,
    FILIAL.ESTAB,
            ITEMAGRO.ITEM ,
            u_tempresa.estabc,
            FILIAL.REDUZIDO ,
  CIDADE.NOME ,
            ITEMAGRO.DESCRICAO,
             ITEMAGRO.UNIDADE,
           ITEMMARCA.descricao  ,
            ITEMAGRO.PESOLIQUIDO,
            F.REDUZIDO, ITEMMARCA.MARCA,U_AGRPROD.U_AGRPROD_ID,U_AGRPROD.DESCAGRUPA
          --  ,PREPRESE.REPRESENT ,CONTAMOV.NOME,
          --  CONTAMOV.NUMEROCM,PREPRESE.descricao


),
*/
CUSTO_GERENCIAL AS (
    SELECT
    FILIAL.ESTAB,
    ITEMAGRO.ITEM  AS ITEM,
    u_tempresa.estabc,
    F.REDUZIDO AS ESTABESTOQUE,
    FILIAL.REDUZIDO AS FILIAL,
    CIDADE.NOME AS GR_ESTAB,
    ITEMAGRO.DESCRICAO||'-'||ITEMAGRO.ITEM AS DESCRICAO_CULTIVAR,
    ITEMAGRO.UNIDADE,
    ITEMMARCA.MARCA,
    ITEMMARCA.descricao  AS SEMENTEIRA,
    ITEMAGRO.PESOLIQUIDO AS KGLT,
    U_AGRPROD.U_AGRPROD_ID AGR,
    U_AGRPROD.U_AGRPROD_ID ||'-'||U_AGRPROD.DESCAGRUPA CULTIVAR,
    TO_CHAR(TABPRECOCAB.dtbase,'DD/MM/YYYY')dtbase,
    arredondar(current_date - tabprecocab.dtbase,0) as dias,
    arredondar(divide(tabprecocab.percacrescimo,30),3) as precomes,
    TABPRECOCAB.CUSTOGERENCIAL AS CUSTOGEREN_ORI,
   CASE 
    WHEN arredondar(current_date - tabprecocab.dtbase, 0) < 0 
        THEN tabprecocab.CUSTOGERENCIAL 
    ELSE ARREDONDAR(
        tabprecocab.CUSTOGERENCIAL * (
            divide(
                arredondar(divide(tabprecocab.percacrescimo, 30), 3) * 
                arredondar(current_date - tabprecocab.dtbase, 0),
                100
            ) + 1
        ),
        3
    )
END AS CUSTOGERENCIAL
    FROM TABPRECOCAB

    INNER JOIN FILIAL ON  FILIAL.ESTAB = TABPRECOCAB.ESTAB

    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

    inner JOIN TABPRECOITEM ON 
        TABPRECOCAB.ESTAB=TABPRECOITEM.ESTAB
        AND TABPRECOCAB.TABELA=TABPRECOITEM.TABELA

    INNER JOIN ITEMAGRO ON  ITEMAGRO.ITEM = TABPRECOITEM.ITEM
    INNER JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM
    LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA

    INNER JOIN ITEMGRUPO_U 
      ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
      AND ITEMGRUPO.GRUPO = 62

    inner JOIN U_AGRPROD 
      ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID   <> 205


     LEFT JOIN FILIAL F ON F.ESTAB = U_TEMPRESA.ESTABC
     LEFT JOIN CIDADE ON CIDADE.CIDADE = F.CIDADE

    where
    tabprecocab.dtinivigencia <=CURRENT_DATE
    AND tabprecocab.dtfinvigencia >=CURRENT_DATE
    and TABPRECOITEM.ativo = 'S'
    and (U_TEMPRESA.ESTABC IN (:ESTAB) OR 0 in (:ESTAB))
),

-- ############## VINCULO PEDIDO E NOTA ##############
PEDNOTA AS (
    SELECT
    PEDITEMNFITEM.ESTAB,
    PEDITEMNFITEM.SERIE,
    PEDITEMNFITEM.NUMERO,
    PEDITEMNFITEM.SEQPEDITE,
    SUM(PEDITEMNFITEM.QUANTIDADE) AS QTD
    FROM PEDITEMNFITEM

    GROUP BY
    PEDITEMNFITEM.ESTAB,
    PEDITEMNFITEM.SERIE,
    PEDITEMNFITEM.NUMERO,
    PEDITEMNFITEM.SEQPEDITE

),
-- ############## TRANSFERENCIAS - POR PEDIDO ##############

TRANSFERENCIAS_ENTRADA AS (
     SELECT
      PEDCAB.ESTAB , -- SAIDA
      U_TEMPRESA.ESTABC, -- SAIDA
      FILIAL.REDUZIDO AS FILIAL, -- SAIDA
      CIDADE.NOME AS GR_ESTAB, --SAIDA
        ITEMAGRO.ITEM,
      ITEMAGRO.DESCRICAO AS DESCRICAO_CULTIVAR,
       U_AGRPROD.U_AGRPROD_ID AGR,
        U_AGRPROD.U_AGRPROD_ID ||'-'||U_AGRPROD.DESCAGRUPA CULTIVAR,
        ITEMMARCA.MARCA,
           ITEMMARCA.MARCA||'-'||ITEMMARCA.descricao as SEMENTEIRA,
      ITEMAGRO.PESOLIQUIDO AS KGLT,
      ITEMAGRO.UNIDADE,
    ( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0) - COALESCE(PEDNOTA.QTD,0) ) ) PEDTRANSF,
    (( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0) - COALESCE(PEDNOTA.QTD,0)   )  ) * ITEMAGRO.PESOLIQUIDO) AS PEDTRANSF_KG,
    (ARREDONDAR(DIVIDE( ( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)  - COALESCE(PEDNOTA.QTD,0)  )  ) * ITEMAGRO.PESOLIQUIDO,40),3)) AS PEDTRANSF_SC

    FROM PEDCAB

    INNER JOIN FILIAL ON  FILIAL.ESTAB = PEDCAB.ESTAB
    LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN PEDCFG ON  PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF

    INNER JOIN PEDITEM
      ON  PEDITEM.ESTAB = PEDCAB.ESTAB
      AND PEDITEM.SERIE = PEDCAB.SERIE
      AND PEDITEM.NUMERO = PEDCAB.NUMERO

    INNER JOIN ITEMAGRO ON  ITEMAGRO.ITEM = PEDITEM.ITEM
    INNER JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM
    LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
      AND ITEMGRUPO.GRUPO = 62
    inner JOIN U_AGRPROD ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID   <> 205

    LEFT JOIN FILIAL FILIALF ON FILIALF.ESTAB = PEDCAB.PESSOA
    LEFT JOIN U_TEMPRESA EMPRESAF ON EMPRESAF.ESTAB = PEDCAB.PESSOA

    LEFT JOIN PEDNOTA ON 
        PEDNOTA.ESTAB = PEDITEM.ESTAB
        AND PEDNOTA.SERIE = PEDITEM.SERIE
        AND PEDNOTA.NUMERO = PEDITEM.NUMERO
        AND PEDNOTA.SEQPEDITE = PEDITEM.SEQPEDITE

    LEFT JOIN FILIAL F ON F.ESTAB = U_TEMPRESA.ESTABC
    LEFT JOIN CIDADE ON CIDADE.CIDADE = F.CIDADE
    LEFT JOIN CIDADE CID ON CID.CIDADE = EMPRESAF.ESTABC

     WHERE
    PEDCAB.SERIE = 'PTE'
    --PEDCFG.PEDIDOCONF in (5)
    AND PEDCAB.STATUS <> 'C'
    --AND PEDCAB.ESTAB IN (:ESTAB)
    AND ((0 IN (:ESTAB)) OR U_TEMPRESA.ESTABC IN (:ESTAB) )
    AND (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) -  COALESCE(PEDNOTA.QTD,0) > 0



),

TRANSFERENCIAS_SAIDA AS (
     SELECT
      PEDCAB.ESTAB , -- SAIDA
      U_TEMPRESA.ESTABC, -- SAIDA
      FILIAL.REDUZIDO AS FILIAL, -- SAIDA
      CIDADE.NOME AS GR_ESTAB, --SAIDA
        ITEMAGRO.ITEM,
      ITEMAGRO.DESCRICAO AS DESCRICAO_CULTIVAR,
       U_AGRPROD.U_AGRPROD_ID AGR,
        U_AGRPROD.U_AGRPROD_ID ||'-'||U_AGRPROD.DESCAGRUPA CULTIVAR,
        ITEMMARCA.MARCA,
           ITEMMARCA.MARCA||'-'||ITEMMARCA.descricao as SEMENTEIRA,
      ITEMAGRO.PESOLIQUIDO AS KGLT,
      ITEMAGRO.UNIDADE,
    ( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0) - COALESCE(PEDNOTA.QTD,0) ) )*-1 PEDTRANSF,
    (( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0) - COALESCE(PEDNOTA.QTD,0)   )  ) * ITEMAGRO.PESOLIQUIDO)*-1 AS PEDTRANSF_KG,
    (ARREDONDAR(DIVIDE( ( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)  - COALESCE(PEDNOTA.QTD,0)  )  ) * ITEMAGRO.PESOLIQUIDO,40),3))*-1 AS PEDTRANSF_SC

    FROM PEDCAB

    INNER JOIN FILIAL ON  FILIAL.ESTAB = PEDCAB.ESTAB
    LEFT JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN PEDCFG ON  PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF

    INNER JOIN PEDITEM
      ON  PEDITEM.ESTAB = PEDCAB.ESTAB
      AND PEDITEM.SERIE = PEDCAB.SERIE
      AND PEDITEM.NUMERO = PEDCAB.NUMERO

    INNER JOIN ITEMAGRO ON  ITEMAGRO.ITEM = PEDITEM.ITEM
    INNER JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    LEFT JOIN ITEMAGRO_U ON  itemagro_u.item = ITEMAGRO.ITEM
    LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA=ITEMAGRO.MARCA
    INNER JOIN ITEMGRUPO_U ON itemgrupo_u.grupo=ITEMGRUPO.GRUPO
      AND ITEMGRUPO.GRUPO = 62
    inner JOIN U_AGRPROD ON ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID      
     and  U_AGRPROD.U_AGRPROD_ID   <> 205

    LEFT JOIN FILIAL FILIALF ON FILIALF.ESTAB = PEDCAB.PESSOA
    LEFT JOIN U_TEMPRESA EMPRESAF ON EMPRESAF.ESTAB = PEDCAB.PESSOA

    LEFT JOIN PEDNOTA ON 
        PEDNOTA.ESTAB = PEDITEM.ESTAB
        AND PEDNOTA.SERIE = PEDITEM.SERIE
        AND PEDNOTA.NUMERO = PEDITEM.NUMERO
        AND PEDNOTA.SEQPEDITE = PEDITEM.SEQPEDITE

    LEFT JOIN FILIAL F ON F.ESTAB = U_TEMPRESA.ESTABC
    LEFT JOIN CIDADE ON CIDADE.CIDADE = F.CIDADE
    LEFT JOIN CIDADE CID ON CID.CIDADE = EMPRESAF.ESTABC

     WHERE
    PEDCFG.PEDIDOCONF in (5)
    AND PEDCAB.STATUS <> 'C'
    --AND PEDCAB.ESTAB IN (:ESTAB)
    AND ((0 IN (:ESTAB)) OR U_TEMPRESA.ESTABC IN (:ESTAB) )
    AND (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) -  COALESCE(PEDNOTA.QTD,0) > 0



)

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
SALDO AS PEDIDOCOMP,
SALDOKG AS PEDIDOCOMPKG,
DIVIDE(SALDOKG,40) AS PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 8
and saldo <> 0

union 

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
SALDO AS PEDIDOVEND,
SALDOKG AS PEDIDOVENDKG,
DIVIDE(SALDOKG,40)  PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 7
and saldo <> 0

union

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
SALDO AS  FISICO,
SALDOKG AS  FISICOKG,
DIVIDE(SALDOKG,40)   FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 2
and saldo <> 0

union 

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0  FISICOKG,
0 FISICOSC,
SALDO AS COMPRAFUT,
SALDOKG AS COMPRAFUTKG,
DIVIDE(SALDOKG,40)  COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 6
and saldo <> 0

union 

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0  FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
SALDO as TRANSITO,
SALDOKG as  TRANSITOKG,
DIVIDE(SALDOKG,40) as TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 20
and saldo <> 0

UNION ALL
SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
SALDO as PEDIDOCART,
SALDOKG as PEDIDOCARTKG,
DIVIDE(SALDOKG,40) as PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 26
and saldo <> 0

union all

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0  FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
SALDO as CONSIGNADO,
SALDOKG as CONSIGNADOKG,
DIVIDE(SALDOKG,40) as CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 28
and saldo <> 0

union

SELECT
----- ##### PARTE DA SAIDA DAS TRANSFERENCIAS
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
PEDTRANSF,
PEDTRANSF_KG,
PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM TRANSFERENCIAS_SAIDA

union 

SELECT
----- ##### PARTE DA ->ENTRADA<- DAS TRANSFERENCIAS
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
PEDTRANSF,
PEDTRANSF_KG,
PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM TRANSFERENCIAS_ENTRADA
/*
UNION

SELECT
----- ##### VENDA FUTURA
VENDAS.ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
VENDAS.ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
VF - COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) - COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) AS SALDO_VF,
VF_KG - (COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) * KGLT) - (COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) * KGLT) AS  SALDO_VF_KG,
DIVIDE(VF_KG,40) - DIVIDE(COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) * KGLT,40) -  DIVIDE( COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) * KGLT, 40) SALDO_VF_SC,
VF,
VF_KG,
DIVIDE(VF_KG,40) AS VF_SC,
COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) AS  QTDCANC,
COALESCE(NFCAB_CANCELADO.VALORTOTAL,0) AS  CANCELADO,
COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) * KGLT AS CANCELADO_KG,
DIVIDE(COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) * KGLT,40) AS CANCELADO_SC,
COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) AS QTDBAIXADO,
COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) * KGLT AS  QTDBAIXADOKGLT,
DIVIDE( COALESCE(NFCAB_BAIXADO.QUANTIDADE,0) * KGLT, 40) AS QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM VENDAS

LEFT JOIN NFCAB_CANCELADO ON 
    NFCAB_CANCELADO.ESTAB = VENDAS.ESTAB
    AND NFCAB_CANCELADO.ITEM = VENDAS.ITEM

LEFT JOIN NFCAB_BAIXADO ON 
    NFCAB_BAIXADO.ESTAB = VENDAS.ESTAB
    AND NFCAB_BAIXADO.ITEM = VENDAS.ITEM

where
tipoop = 'VF'

UNION 

SELECT
----- ##### VENDA FUTURA
VENDAS.ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
VENDAS.ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
VF VENDA,
VF_KG AS VENDA_KG,
COALESCE(NFCAB_CANCELADO.QUANTIDADE,0) AS V_QTDCANC,
COALESCE(NFCAB_CANCELADO.QUANTIDADE,0)*KGLT AS V_CANCELADO_KG,
COALESCE(NFCAB_CANCELADO.VALORTOTAL,0)  AS V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
0 SALDO_VENDAF
FROM VENDAS

LEFT JOIN NFCAB_CANCELADO ON 
    NFCAB_CANCELADO.ESTAB = VENDAS.ESTAB
    AND NFCAB_CANCELADO.ITEM = VENDAS.ITEM


where
tipoop = 'V'
*/
UNION

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0 PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
CUSTOGEREN_ORI,
CUSTOGERENCIAL,
DTBASE,
0 SALDO_VENDAF
FROM CUSTO_GERENCIAL

union 

SELECT
ESTAB,
FILIAL,
ESTABC,
GR_ESTAB,
ITEM AS COD_ITEM,
DESCRICAO_CULTIVAR,
CULTIVAR,
MARCA,
SEMENTEIRA,
KGLT,
UNIDADE,
0 PEDIDOCART,
0 PEDIDOCARTKG,
0 PEDIDOCARTSC,
0 PEDIDOCOMP,
0  PEDIDOCOMPKG,
0 PEDIDOCOMPSC,
0 PEDIDOVEND,
0 PEDIDOVENDKG,
0 PEDIDOVENDSC,
0 FISICO,
0 FISICOKG,
0 FISICOSC,
0 COMPRAFUT,
0 COMPRAFUTKG,
0 COMPRAFUTSC,
0 TRANSITO,
0 TRANSITOKG,
0 TRANSITOSC,
0 CONSIGNADO,
0 CONSIGNADOKG,
0 CONSIGNADOSC,
0 PEDTRANSF,
0 PEDTRANSF_KG,
0 PEDTRANSF_SC,
0 SALDO_VF,
0 SALDO_VF_KG,
0 SALDO_VF_SC,
0 VF,
0 VF_KG,
0 VF_SC,
0 QTDCANC,
0 CANCELADO,
0 CANCELADO_KG,
0 CANCELADO_SC,
0 QTDBAIXADO,
0 QTDBAIXADOKGLT,
0 QTDBAIXADO_SC,
0 VENDA,
0 VENDA_KG,
0 V_QTDCANC,
0 V_CANCELADO_KG,
0 V_CANCELADO,
0 CUSTOGEREN_ORI,
0 CUSTOGERENCIAL,
NULL DTBASE,
divide(SALDOKG,40) as SALDO_VENDAF
FROM BASE_DADOS

WHERE codigosaldo = 11
and saldo <> 0
