WITH VENDAS AS
(
    SELECT DISTINCT
        NFCAB.ESTAB AS FILIAL,
        (NFCAB.ESTAB || ' - ' || FILIAL.REDUZIDO) AS ESTAB,
        ENDERECO.NUMEROCM,
        contamov.NOME,
        ENDERECO.CNPJF,
        COALESCE(ENDERECO.SEQENDERECO,0) AS SEQENDERECO,
        ENDERECO.ENDERECO,
        ENDERECO.BAIRRO,
        CIDADE.NOME AS CIDADE,
        CIDADE.UF,
        ENDERECO.LATITUDE,
        ENDERECO.LONGITUDE,
        PPESCLI.DTCADASTRO AS DATA_CADASTRO,
        CONTAMOV.USERID,
        COALESCE(ENDERECO.CREDENCIALAGRO,'VAZIO') AS INSC_ESTADUAL,
        ENDERECO.CEP,
        ENDERECO.TELEFONE
    FROM ENDERECO
         LEFT JOIN CONTAMOV
                ON ENDERECO.NUMEROCM = CONTAMOV.NUMEROCM
         INNER JOIN CIDADE
                ON ENDERECO.CIDADE = CIDADE.CIDADE
         INNER JOIN NFCAB
                ON ENDERECO.NUMEROCM = NFCAB.NUMEROCM
               AND COALESCE(ENDERECO.SEQENDERECO,0)
                   = COALESCE(NFCAB.SEQENDERECO,0)
               AND NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIN
         INNER JOIN FILIAL
                ON NFCAB.ESTAB = FILIAL.ESTAB
         INNER JOIN NFCFG_U
                ON NFCAB.NOTACONF = NFCFG_U.NOTACONF
         INNER JOIN U_TIPOOP
                ON NFCFG_U.U_TIPOOP_ID = U_TIPOOP.U_TIPOOP_ID
               AND U_TIPOOP.TIPOOP IN ('V','VF')
         INNER JOIN U_TEMPRESA
                ON NFCAB.ESTAB = U_TEMPRESA.ESTAB
               AND U_TEMPRESA.INSUMOS = 'S'
         INNER JOIN PPESCLI
                ON ENDERECO.NUMEROCM = PPESCLI.CLIENTE
    WHERE U_TEMPRESA.INSUMOS = 'S'
      AND U_TEMPRESA.EXVENDA = 'S'
      AND NFCAB.ESTAB <> 2
      AND (0 IN (:NUMEROCM)
           OR ENDERECO.NUMEROCM IN (:NUMEROCM))

    UNION ALL

    SELECT DISTINCT
        NFCAB.ESTAB AS FILIAL,
        (NFCAB.ESTAB || ' - ' || FILIAL.REDUZIDO) AS ESTAB,
        CONTAMOV.NUMEROCM,
        CONTAMOV.NOME,
        CONTAMOV.CNPJF,
        0 AS SEQENDERECO,
        ENDERECO.ENDERECO,
        ENDERECO.BAIRRO,
        CIDADE.NOME AS CIDADE,
        CIDADE.UF,
        CONTAMOV.LATITUDEENDERECO AS LATITUDE,
        CONTAMOV.LONGITUDEENDERECO AS LONGITUDE,
        PPESCLI.DTCADASTRO AS DATA_CADASTRO,
        CONTAMOV.USERID,
        COALESCE(CONTAMOV.INSCESTAD,'VAZIO') AS INSC_ESTADUAL,
        CONTAMOV.CEP,
        (CONTAMOV.TELEFONE || '/' || CONTAMOV.CELULAR) AS TELEFONE
    FROM CONTAMOV
         LEFT JOIN ENDERECO
                ON CONTAMOV.NUMEROCM = ENDERECO.NUMEROCM
         INNER JOIN CIDADE
                ON CONTAMOV.CIDADE = CIDADE.CIDADE
         INNER JOIN NFCAB
                ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
               AND COALESCE(NFCAB.SEQENDERECO,0) = 0
               AND NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIN
         INNER JOIN FILIAL
                ON NFCAB.ESTAB = FILIAL.ESTAB
         INNER JOIN NFCFG_U
                ON NFCAB.NOTACONF = NFCFG_U.NOTACONF
         INNER JOIN U_TIPOOP
                ON NFCFG_U.U_TIPOOP_ID = U_TIPOOP.U_TIPOOP_ID
               AND U_TIPOOP.TIPOOP IN ('V','VF')
         INNER JOIN U_TEMPRESA
                ON NFCAB.ESTAB = U_TEMPRESA.ESTAB
               AND U_TEMPRESA.INSUMOS = 'S'
         INNER JOIN PPESCLI
                ON CONTAMOV.NUMEROCM = PPESCLI.CLIENTE
    WHERE U_TEMPRESA.INSUMOS = 'S'
      AND U_TEMPRESA.EXVENDA = 'S'
      AND NFCAB.ESTAB <> 2
      AND (0 IN (:NUMEROCM)
           OR CONTAMOV.NUMEROCM IN (:NUMEROCM))
)

SELECT
    VENDAS.*,
    CASE
        WHEN NVL(VENDAS.LATITUDE,0) = 0
          OR NVL(VENDAS.LONGITUDE,0) = 0
        THEN 'PENDENTE'
        ELSE 'OK'
    END AS PREENCHIDO,
    1 AS QUANTIDADE
FROM VENDAS
ORDER BY
    FILIAL,
    DATA_CADASTRO