SELECT
NFCAB.NUMEROCM,
EXTRACT(YEAR FROM CAB.DTINCLUSAO) AS ANO,
EXTRACT(MONTH FROM CAB.DTINCLUSAO) AS MES,
EXTRACT(DAY FROM CAB.DTINCLUSAO) AS DIA,
NFCAB.NOTA,
NFITEM.ITEM,
SUM(ARREDONDAR(ITE.QUANTIDADE * ITEMAGRO.PESOLIQUIDO,2)) AS PESO,
SUM(ITE.QUANTIDADE) AS QUANTIDADE,
SUM(ITE.QUANTIDADE * NFITEM.VALORUNITARIO) AS VALOR,
EXTRACT(YEAR FROM PEDCAB.DTPREVISAO) AS ANO_PREV,
EXTRACT(MONTH FROM PEDCAB.DTPREVISAO) AS MES_PREV,
EXTRACT(DAY FROM PEDCAB.DTPREVISAO) AS DIA_PREV

FROM ORDEMCARGACAB CAB
INNER JOIN ORDEMCARGADOC DOC ON DOC.IDCARGA = CAB.IDCARGA
INNER JOIN ORDEMCARGAITEM ITE ON ITE.IDDOC = DOC.IDDOC
INNER JOIN ORDEMCARGATRANSP TR ON TR.IDCARGA = CAB.IDCARGA
LEFT JOIN CONTAMOV TRANSP ON TRANSP.NUMEROCM = TR.PRESTADOR
INNER JOIN NFITEM ON
    NFITEM.ESTAB = ITE.ESTABNOTA
    AND NFITEM.SEQNOTA = ITE.SEQNOTA
    AND NFITEM.SEQNOTAITEM = ITE.SEQITEMNOTA
INNER JOIN NFCAB ON
    NFCAB.ESTAB = NFITEM.ESTAB
    AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
INNER JOIN PEDITEMNFITEM P ON
    P.ESTABNOTA = NFITEM.ESTAB
    AND P.SEQNOTA = NFITEM.SEQNOTA
    AND P.SEQNOTAITEM = NFITEM.SEQNOTAITEM
INNER JOIN PEDITEM ON
    PEDITEM.ESTAB = P.ESTAB
    AND PEDITEM.SERIE = P.SERIE
    AND PEDITEM.SEQPEDITE = P.SEQPEDITE
    AND PEDITEM.NUMERO = P.NUMERO
INNER JOIN PEDCAB ON 
    PEDCAB.ESTAB = PEDITEM.ESTAB
    AND PEDCAB.SERIE = PEDITEM.SERIE
    AND PEDCAB.NUMERO = PEDITEM.NUMERO
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = NFCAB.NUMEROCM
    AND ENDERECO.SEQENDERECO = NFCAB.SEQENDERECO
LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
LEFT JOIN CIDADE ON CIDADE.CIDADE = NVL(ENDERECO.CIDADE,CONTAMOV.CIDADE)
WHERE
U_TEMPRESA.INSUMOS = 'S'
AND CAB.DTINCLUSAO BETWEEN :DTINI AND :DTFIM
<#if ORDEM?has_content>
        and CAB.IDCARGA IN (:ORDEM)
          </#if>

GROUP BY
NFCAB.NUMEROCM,
EXTRACT(YEAR FROM CAB.DTINCLUSAO),
EXTRACT(MONTH FROM CAB.DTINCLUSAO),
EXTRACT(DAY FROM CAB.DTINCLUSAO),
NFCAB.NOTA,
NFITEM.ITEM,
EXTRACT(YEAR FROM PEDCAB.DTPREVISAO),
EXTRACT(MONTH FROM PEDCAB.DTPREVISAO),
EXTRACT(DAY FROM PEDCAB.DTPREVISAO)