SELECT
TR.PLACA,
NFCAB.NOTA,
NFCAB.DTEMISSAO,
FILIAL.CNPJ,
PEDCAB.DTPREVISAO,
TRANSP.NOME AS TRANSPORTADORA,
NULL AS VOLUME,
SUM(ARREDONDAR(ITE.QUANTIDADE * ITEMAGRO.PESOLIQUIDO,2)) AS PESO,
SUM(ITE.QUANTIDADE * NFITEM.VALORUNITARIO) AS VALOR,
null as CUBAGEM,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) AS CNPJF_DEST,
NVL(ENDERECO.NOME,CONTAMOV.NOME) AS NOME_DEST,
NVL(ENDERECO.ENDERECO,CONTAMOV.ENDERECO) AS ENDERECO,
NVL(ENDERECO.BAIRRO,CONTAMOV.BAIRRO) AS BAIRRO,
CIDADE.NOME AS CIDADE,
CIDADE.UF,
NVL(ENDERECO.CEP,CONTAMOV.CEP) AS CEP,
TR.FRETEPORCONTA AS CONDICAO,
NULL AS PARTICULARIDADE,
NFCAB.CHAVEACESSONFE AS CHAVE,
CAB.CONFIG,
NVL(ENDERECO.LATITUDE,CONTAMOV.LATITUDEENDERECO) AS LATITUDE,
NVL(ENDERECO.LONGITUDE,CONTAMOV.LONGITUDEENDERECO) AS LONGITUDE
FROM ORDEMCARGACAB CAB
INNER JOIN ORDEMCARGADOC DOC ON DOC.IDCARGA = CAB.IDCARGA
INNER JOIN ORDEMCARGAITEM ITE ON ITE.IDDOC = DOC.IDDOC
INNER JOIN ORDEMCARGATRANSP TR ON TR.IDCARGA = CAB.IDCARGA
LEFT JOIN CONTAMOV TRANSP ON TRANSP.NUMEROCM = TR.PRESTADOR
INNER JOIN NFITEM ON
    NFITEM.ESTAB = ITE.ESTABNOTA
    AND NFITEM.SEQNOTA = ITE.SEQNOTA
    AND NFITEM.SEQNOTAITEM = ITE.SEQITEMNOTA
INNER JOIN NFCAB ON
    NFCAB.ESTAB = NFITEM.ESTAB
    AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
INNER JOIN PEDITEMNFITEM P ON
    P.ESTABNOTA = NFITEM.ESTAB
    AND P.SEQNOTA = NFITEM.SEQNOTA
    AND P.SEQNOTAITEM = NFITEM.SEQNOTAITEM
INNER JOIN PEDITEM ON
    PEDITEM.ESTAB = P.ESTAB
    AND PEDITEM.SERIE = P.SERIE
    AND PEDITEM.SEQPEDITE = P.SEQPEDITE
    AND PEDITEM.NUMERO = P.NUMERO
INNER JOIN PEDCAB ON 
    PEDCAB.ESTAB = PEDITEM.ESTAB
    AND PEDCAB.SERIE = PEDITEM.SERIE
    AND PEDCAB.NUMERO = PEDITEM.NUMERO
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = NFCAB.NUMEROCM
    AND ENDERECO.SEQENDERECO = NFCAB.SEQENDERECO
LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
LEFT JOIN CIDADE ON CIDADE.CIDADE = NVL(ENDERECO.CIDADE,CONTAMOV.CIDADE)
WHERE
U_TEMPRESA.INSUMOS = 'S'
AND CAB.DTINCLUSAO BETWEEN :DTINI AND :DTFIM
<#if ORDEM?has_content>
        and CAB.IDCARGA IN (:ORDEM)
          </#if>

GROUP BY
TR.PLACA,
NFCAB.NOTA,
CAB.IDCARGA,
NFCAB.ESTAB,
NFCAB.DTEMISSAO,
FILIAL.CNPJ,
PEDCAB.DTPREVISAO,
TRANSP.NOME,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) ,
NVL(ENDERECO.NOME,CONTAMOV.NOME) ,
NVL(ENDERECO.ENDERECO,CONTAMOV.ENDERECO),
NVL(ENDERECO.BAIRRO,CONTAMOV.BAIRRO),
CIDADE.NOME,
CIDADE.UF,
NVL(ENDERECO.CEP,CONTAMOV.CEP),
TR.FRETEPORCONTA,
NFCAB.CHAVEACESSONFE,
CAB.CONFIG,
NVL(ENDERECO.LATITUDE,CONTAMOV.LATITUDEENDERECO),
NVL(ENDERECO.LONGITUDE,CONTAMOV.LONGITUDEENDERECO) 