SELECT
    CIDADE.NOME AS GR_ESTAB,
    FILIAL.REDUZIDO AS FILIAL,
    (U_AGRPROD.U_AGRPROD_ID || ' - ' || U_AGRPROD.DESCAGRUPA) AS CULTIVAR,
    (ITEMAGRO.DESCRICAO || ' - ' || ITEMAGRO.ITEM) AS DESCRICAO_CULTIVAR,
    (ITEMMARCA.MARCA || ' - ' || ITEMMARCA.DESCRICAO) AS SEMENTEIRA,
    TO_CHAR(PEDPRAZO.PRAZOPAGAMENTO, 'DD/MM/YYYY') AS DTPRAZOPAGTO,
    PEDCAB.NUMERO,
    PEDCAB_U.MODSEMENTE,
    PEDCAB.STATUS,
    PEDITEM.QUANTIDADE,
    /*BAG*/DIVIDE(PEDITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO, 40) AS QUANTIDADE_BAG,
    PEDITEM.VALORUNITARIO,
    PEDITEM.VALOR,
    TO_CHAR(COALESCE(PEDITEM.DTENTREGA, PEDCAB.DTPREVISAO), 'DD/MM/YYYY') AS DT_PREVISAO,
    --(PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO, 0) - COALESCE(PEDITEMNF.QTD_BAIXADA, 0)) AS QTD_PENDENTE,
    (CASE
        WHEN NFCFG_PED.DESCRICAO LIKE '%ENTREGA FUTUR%'
            THEN (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO, 0) - COALESCE(NFITEM.QUANTIDADE, 0))
        ELSE (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO, 0) - COALESCE(PEDITEMNF.QUANTIDADE, 0))
    END
    ) AS QTD_PENDENTE,
    /*BAG*/DIVIDE   (CASE
                        WHEN NFCFG_PED.DESCRICAO LIKE '%ENTREGA FUTUR%'
                            THEN ((PEDITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO) - COALESCE(PEDITEM.CANCELADO * ITEMAGRO.PESOLIQUIDO, 0) - COALESCE(NFITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO, 0))
                        ELSE ((PEDITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO) - COALESCE(PEDITEM.CANCELADO * ITEMAGRO.PESOLIQUIDO, 0) - COALESCE(PEDITEMNF.QUANTIDADE * ITEMAGRO.PESOLIQUIDO, 0))
                    END, 40
                    ) AS QTD_PENDENTE_BAG,
    --
    --COALESCE(PEDITEMNF.QTD_BAIXADA, 0) AS QTD_BAIXADA,
    (CASE
        WHEN NFCFG_PED.DESCRICAO LIKE '%ENTREGA FUTUR%'
            THEN COALESCE(NFITEM.QUANTIDADE, 0)
        ELSE COALESCE(PEDITEMNF.QUANTIDADE, 0)
    END
    ) AS QTD_BAIXADA,
    /*BAG*/DIVIDE   (CASE
                        WHEN NFCFG_PED.DESCRICAO LIKE '%ENTREGA FUTUR%'
                            THEN COALESCE(NFITEM.QUANTIDADE * ITEMAGRO.PESOLIQUIDO, 0)
                        ELSE COALESCE(PEDITEMNF.QUANTIDADE * ITEMAGRO.PESOLIQUIDO, 0)
                    END, 40
                    ) AS QTD_BAIXADA_BAG,
    --
    PEDITEM.CANCELADO,
    /*BAG*/DIVIDE(PEDITEM.CANCELADO * ITEMAGRO.PESOLIQUIDO, 40) AS CANCELADO_BAG,
    PEDCAB.OBS,
    COALESCE(PEDCAB_U.PEDTERCEIRO, '0') AS PEDTERCEIRO,
    PEDCAB.PEDIDOCONF,
    PEDCFG.DESCRICAO AS CONFIGURACAO
FROM PEDCAB
    INNER JOIN PEDITEM
        ON  PEDITEM.ESTAB = PEDCAB.ESTAB
        AND PEDITEM.SERIE = PEDCAB.SERIE
        AND PEDITEM.NUMERO = PEDCAB.NUMERO
    LEFT JOIN PEDCAB_U
        ON  PEDCAB_U.ESTAB = PEDCAB.ESTAB
        AND PEDCAB_U.SERIE = PEDCAB.SERIE
        AND PEDCAB_U.NUMERO = PEDCAB.NUMERO
    INNER JOIN PEDCFG
        ON  PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF
    INNER JOIN FILIAL
        ON  FILIAL.ESTAB = PEDCAB.ESTAB
        INNER JOIN U_TEMPRESA
            ON  U_TEMPRESA.ESTAB = FILIAL.ESTAB
            INNER JOIN FILIAL FILIAL_C
                ON  FILIAL_C.ESTAB = U_TEMPRESA.ESTABC
                INNER JOIN CIDADE
                    ON  CIDADE.CIDADE = FILIAL_C.CIDADE
        INNER JOIN ITEMAGRO
            ON  ITEMAGRO.ITEM = PEDITEM.ITEM
            LEFT JOIN ITEMAGROESTAB
                ON  PEDCAB.ESTAB = ITEMAGROESTAB.ESTAB
                AND ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM
                LEFT JOIN
                    (SELECT
                        ITEMSALDO.ESTAB,
                        ITEMSALDO.ITEM,
                        ITEMSALDO.LOCAL,
                        SUM(ITEMSALDO.SALDOQUANTIDADE) AS SALDOQTD
                    FROM ITEMSALDO
                    GROUP BY
                        ITEMSALDO.ESTAB,
                        ITEMSALDO.ITEM,
                        ITEMSALDO.LOCAL
                    ) ITEMSALDO
                    ON  ITEMAGROESTAB.ESTAB = ITEMSALDO.ESTAB
                    AND ITEMAGROESTAB.ITEM = ITEMSALDO.ITEM
                    AND ITEMAGROESTAB.LOCAL = ITEMSALDO.LOCAL
            INNER JOIN ITEMGRUPO
                ON  ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
            INNER JOIN ITEMAGRO_U
                ON  ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
                INNER JOIN U_AGRPROD
                    ON  ITEMAGRO_U.U_AGRPROD_ID = U_AGRPROD.U_AGRPROD_ID
                    AND U_AGRPROD.U_AGRPROD_ID <> 205
            INNER JOIN ITEMMARCA
                ON  ITEMMARCA.MARCA = ITEMAGRO.MARCA
                INNER JOIN ITEMGRUPO_U
                    ON  ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
                    AND ITEMGRUPO.GRUPO = 62
        --
        LEFT JOIN PEDITEMNFITEM PEDITEMNF
            ON  PEDITEMNF.ESTAB = PEDITEM.ESTAB
            AND PEDITEMNF.SERIE = PEDITEM.SERIE
            AND PEDITEMNF.NUMERO = PEDITEM.NUMERO
            AND PEDITEMNF.SEQPEDITE = PEDITEM.SEQPEDITE
            LEFT JOIN NFITEM NFITEM_PED
                ON  PEDITEMNF.ESTABNOTA = NFITEM_PED.ESTAB
                AND PEDITEMNF.SEQNOTA = NFITEM_PED.SEQNOTA
                AND PEDITEMNF.SEQNOTAITEM = NFITEM_PED.SEQNOTAITEM
                LEFT JOIN NFCAB NFCAB_PED
                    ON  NFITEM_PED.ESTAB = NFCAB_PED.ESTAB
                    AND NFITEM_PED.SEQNOTA = NFCAB_PED.SEQNOTA
                    LEFT JOIN NFCFG NFCFG_PED
                        ON  NFCAB_PED.NOTACONF = NFCFG_PED.NOTACONF
        LEFT JOIN PEDITEMNFITEM
            ON  PEDITEMNFITEM.ESTAB = PEDITEM.ESTAB
            AND PEDITEMNFITEM.SERIE = PEDITEM.SERIE
            AND PEDITEMNFITEM.NUMERO = PEDITEM.NUMERO
            AND PEDITEMNFITEM.SEQPEDITE = PEDITEM.SEQPEDITE
            LEFT JOIN NFITEMAPARTIRDE
                ON  PEDITEMNFITEM.ESTABNOTA = NFITEMAPARTIRDE.ESTABORIGEM
                AND PEDITEMNFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                AND PEDITEMNFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                LEFT JOIN NFITEM
                    ON  NFITEMAPARTIRDE.ESTAB = NFITEM.ESTAB
                    AND NFITEMAPARTIRDE.SEQNOTA = NFITEM.SEQNOTA
                    AND NFITEMAPARTIRDE.SEQNOTAITEM = NFITEM.SEQNOTAITEM
                    LEFT JOIN NFCAB
                        ON  NFITEM.ESTAB = NFCAB.ESTAB
                        AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
                        LEFT JOIN NFCFG
                            ON  NFCAB.NOTACONF = NFCFG.NOTACONF
                            LEFT JOIN NATOPERACAO
                                ON  NFCFG.NATUREZADAOPERACAO = NATOPERACAO.NATUREZADAOPERACAO
        --
    LEFT JOIN
        (SELECT
            ESTAB,
            SERIE,
            NUMERO,
            MAX(PRAZOPAGAMENTO) AS PRAZOPAGAMENTO
        FROM PEDCABPGTO
        GROUP BY
            ESTAB,
            SERIE,
            NUMERO
        ) PEDPRAZO
        ON  PEDPRAZO.ESTAB = PEDCAB.ESTAB
        AND PEDPRAZO.SERIE = PEDCAB.SERIE
        AND PEDPRAZO.NUMERO = PEDCAB.NUMERO
WHERE   1=1
    AND PEDCAB.PEDIDOCONF IN (50,51,64,99)
    AND PEDCAB.DTEMISSAO >= (:DITINI)
    AND (   0 IN (:ESTAB)
        OR  U_TEMPRESA.ESTABC IN (:ESTAB)
        )