WITH CUSTOS AS (
    SELECT
        ITEMAGROESTAB.ESTAB,
        ITEMAGROESTAB.ITEM,
        ROUND(PCUSTO(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 5, CURRENT_DATE, NULL, NULL), 2) AS CUSTO_GERENCIAL,
        ROUND(PCUSTO(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 3, CURRENT_DATE, NULL, NULL), 2) AS CUSTO_CONTABIL
    FROM ITEMAGROESTAB
    INNER JOIN U_TEMPRESA U ON U.ESTAB = ITEMAGROESTAB.ESTAB
    WHERE
        INSUMOS = 'S'
        AND ITEMAGROESTAB.ITEM > 50
        AND (0 IN (:ESTAB) OR (:ESTAB) IS NULL OR ITEMAGROESTAB.ESTAB IN (:ESTAB))
        AND EXISTS (
            SELECT 1
            FROM TABPRECOITEM
            WHERE TABPRECOITEM.ESTAB = ITEMAGROESTAB.ESTAB
              AND ITEMAGROESTAB.ITEM = TABPRECOITEM.ITEM
        )
),
MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO

    WHERE
    codigosaldo = 1

    GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO
),
-- ############## SALDO DOS ITENS ############
SALDO AS (
    SELECT 
        ISALDO.codigosaldo,
        IESTAB.ESTAB,
        IESTAB.ITEM ,
        IA.DESCRICAO || '-' || IESTAB.ITEM AS DESCRICAO_CULTIVAR,
        IA.UNIDADE,
        IA.PESOLIQUIDO AS KGLT,
        SUM(ISALDO.SALDOQUANTIDADE) AS SALDO,
        SUM(ISALDO.SALDOQUANTIDADE) * IA.PESOLIQUIDO AS SALDOKG

    FROM ITEMAGROESTAB IESTAB
    
    LEFT JOIN ITEMSALDO ISALDO ON 
        ISALDO.ITEM = IESTAB.ITEM 
        AND ISALDO.ESTAB = IESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ISALDO.ITEM 
        AND MD.ESTAB = ISALDO.ESTAB 
        AND MD.CODIGOSALDO = ISALDO.CODIGOSALDO
        AND TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    INNER JOIN ITEMAGRO IA ON 
        IA.ITEM = IESTAB.ITEM 
            AND IA.ATIVO = 'S'

    WHERE 0=0 
      AND(0 IN (:ESTAB) OR (:ESTAB) IS NULL OR IESTAB.ESTAB IN (:ESTAB))
      AND IA.ATIVO = 'S'
      and ISALDO.codigosaldo  = 1

    GROUP BY IESTAB.ESTAB,
             IESTAB.ITEM, 
             IA.DESCRICAO, 
             IA.UNIDADE,
             IA.PESOLIQUIDO,
             ISALDO.CODIGOSALDO
),
IMPOSTOS AS (
    SELECT DISTINCT
    TRIBUTACAO,
    UF,
    UFORIGEM,
    DIVIDE(ARREDONDAR(T.BASETRI*T.ALIQUOTAESP,0),100) as ALIQUOTAESP
    FROM TRIBITEM T
    WHERE
    ENTRADASAIDA = 'S' 
    AND PRODUTOR = 'S' 
    AND IMPOSTO = 1 
    AND NATOPERACOES LIKE 'P;PR%'
    AND UF = UFORIGEM
    AND ALIQUOTAESP <> 0
),
VENDAS AS (
    SELECT
    peditem.estabtabpreco,
    PEDITEM.ITEM,
    PEDITEM.TABELAPRECO,
    NFITEM.ESTAB,
    NFITEM.SEQNOTA,
    NFITEM.SEQNOTAITEM,
    SUM(COALESCE(PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO, 0) , 0)) AS PEDQTD,
    SUM(COALESCE(PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO, 0),0) * PESOLIQUIDO) AS PEDKGLT
    FROM PEDCAB
    LEFT JOIN PEDITEM 
        ON PEDCAB.ESTAB = PEDITEM.ESTAB 
        AND PEDCAB.NUMERO = PEDITEM.NUMERO 
        AND PEDCAB.SERIE = PEDITEM.SERIE 
    LEFT JOIN PEDITEMNFITEM
        ON PEDITEMNFITEM.ESTAB = PEDITEM.ESTAB
        AND PEDITEMNFITEM.SERIE = PEDITEM.SERIE
        AND PEDITEMNFITEM.NUMERO = PEDITEM.NUMERO
        AND PEDITEMNFITEM.SEQPEDITE = PEDITEM.SEQPEDITE
    LEFT JOIN NFITEM
        ON NFITEM.ESTAB = PEDITEMNFITEM.ESTABNOTA
        AND NFITEM.SEQNOTA = PEDITEMNFITEM.SEQNOTA
        AND NFITEM.SEQNOTAITEM = PEDITEMNFITEM.SEQNOTAITEM
    LEFT JOIN CONTAMOV 
        ON CONTAMOV.NUMEROCM = PEDCAB.PESSOA   
    LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
    INNER JOIN TABPRECOCAB T ON
        T.ESTAB = PEDITEM.ESTABTABPRECO
        AND T.TABELA = PEDITEM.TABELAPRECO
    LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    LEFT JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
    LEFT JOIN U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
    WHERE 
        COALESCE(PEDCAB.STATUS,'C') <> 'C' 
        AND PEDCAB.DTEMISSAO >= '17/04/2025' 
         AND (
                (:ATIVA = 'S' AND T.DTFINVIGENCIA >= CURRENT_DATE) OR
                (:ATIVA = 'N' AND T.DTFINVIGENCIA <  CURRENT_DATE) OR
                (:ATIVA = 'T') OR
                (:ATIVA = 'B' AND T.DESCRICAO LIKE '%BARTER%')
            )
        AND PEDCAB.SERIE IN ('PV','PVM','PF')
        AND (0 IN (:ESTAB) OR (:ESTAB) IS NULL OR T.ESTAB IN (:ESTAB))
        AND (0 IN (:GRUPO) OR U_GESTOQUE.U_GESTOQUE_ID IN (:GRUPO))
    GROUP by
    peditem.estabtabpreco,
    PEDITEM.ITEM,
    PEDITEM.TABELAPRECO,
    NFITEM.ESTAB,
    NFITEM.SEQNOTA,
    NFITEM.SEQNOTAITEM
),
VENDAS_SOMA AS (
    SELECT
    VENDAS.ESTABTABPRECO,
    VENDAS.TABELAPRECO,
    VENDAS.ITEM,
    SUM(COALESCE(VENDAS.PEDQTD,0)) AS VENDA,
    SUM(COALESCE(VENDAS.PEDKGLT,0)) AS VENDA_KG
    FROM VENDAS
    GROUP BY VENDAS.ESTABTABPRECO,VENDAS.TABELAPRECO,VENDAS.ITEM
),
DEVOL AS (
    SELECT
    VENDAS.ESTABTABPRECO,
    VENDAS.TABELAPRECO,
    VENDAS.ITEM,
    SUM(NVL(NP.QUANTIDADE,0)) AS QTD_DEV,
    SUM(NVL(NP.QUANTIDADE,0) * NVL(ITEMAGRO.PESOLIQUIDO,1)) AS KGLT_DEV,
    SUM(
        CASE WHEN U_TIPOOP.TIPOOP = 'RF' THEN N.QUANTIDADE ELSE 0 END
        ) AS QUANTIDADE,
    SUM(
        CASE WHEN U_TIPOOP.TIPOOP = 'RF' THEN N.QUANTIDADE*NVL(ITEMAGRO.PESOLIQUIDO,1) ELSE 0 END
        )  AS KGLT,
    SUM(
        CASE WHEN U_TIPOOP.TIPOOP <> 'RF' THEN N.QUANTIDADE ELSE 0 END
        ) AS QTD_DESFZ,
    SUM(
        CASE WHEN U_TIPOOP.TIPOOP <> 'RF' THEN N.QUANTIDADE*NVL(ITEMAGRO.PESOLIQUIDO,1) ELSE 0 END
        )  AS KGLT_DESFZ
    FROM NFITEMAPARTIRDE N
    INNER JOIN VENDAS ON
        VENDAS.ESTAB = N.ESTABORIGEM
        AND VENDAS.SEQNOTA = N.SEQNOTAORIGEM
        AND VENDAS.SEQNOTAITEM = N.SEQNOTAITEMORIGEM

    INNER JOIN NFCAB ON
            NFCAB.ESTAB = N.ESTAB
            AND NFCAB.SEQNOTA = N.SEQNOTA
            
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCFG_U ON NFCFG.NOTACONF = NFCFG_U.NOTACONF
    INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID

    -- DEVOLUÇÃO DA REMESSA
    LEFT JOIN NFITEMAPARTIRDE NP ON
        NP.ESTABORIGEM = N.ESTAB
        AND NP.SEQNOTAORIGEM = N.SEQNOTA
        AND NP.SEQNOTAITEMORIGEM = N.SEQNOTAITEM
        
    LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = VENDAS.ITEM
    GROUP BY
    VENDAS.ESTABTABPRECO,
    VENDAS.TABELAPRECO,
    VENDAS.ITEM
)
SELECT 
    TABPRECOCAB.ESTAB,
    FILIAL.REDUZIDO,
    TABPRECOCAB.TABELA,
    TABPRECOCAB.DESCRICAO AS TABELA_DESCRICAO,
    TO_CHAR(TABPRECOCAB.DTINIVIGENCIA, 'DD/MM/YYYY') AS DTINIVIGENCIA,
    TO_CHAR(TABPRECOCAB.DTFINVIGENCIA, 'DD/MM/YYYY') AS DTFINVIGENCIA,
    TO_CHAR(TABPRECOCAB.DTBASE, 'DD/MM/YYYY') AS DTBASE,
    TABPRECOCAB.PERCACRESCIMO AS PERCENTUAL_ACRESCIMO,
    TABPRECOITEM.ITEM,
    ITEMAGRO.DESCRICAO AS ITEM_DESCRICAO,
    ITEMAGRO.GRUPO,
    ITEMGRUPO.DESCRICAO AS SUB_GRUPO_DESCRICAO,
    U_GESTOQUE.U_GESTOQUE_ID,
    U_GESTOQUE.DESCRICAO AS GRUPO_DESCRICAO,
    ITEMAGRO.MARCA,
    ITEMMARCA.DESCRICAO AS MARCA_DESCRICAO, 
    TABPRECOITEM.PRECO,
    TABPRECOITEM.CUSTOGERENCIAL AS CUSTO_TABELA,
    ROUND(
        CASE 
            WHEN TABPRECOITEM.PRECO = 0 THEN 0
            ELSE (DIVIDE((TABPRECOITEM.PRECO - TABPRECOITEM.CUSTOGERENCIAL), TABPRECOITEM.PRECO)) * 100
        END, 2) AS MARGEM,
        
    TABPRECOITEM.SALDODISP  AS SALDO,         -- SALDO DA TABELA ANTIGA
    TABPRECOITEM.VALSALDODISP AS SALDODISP_UN,
    -- SALDO DISPONÍVEL EM KG DA TABPRECOITEM
    TABPRECOITEM.SALDODISP * ITEMAGRO.PESOLIQUIDO AS SALDODISP_KG,
    NVL(VENDAS_SOMA.VENDA_KG,0) AS VENDA_KG,
    NVL(VENDAS_SOMA.VENDA,0) AS VENDA_QTD,
    NVL(DEVOL.QUANTIDADE,0) AS QTD_BX,
    NVL(DEVOL.KGLT,0) AS KGLT_BX,
    NVL(VENDAS_SOMA.VENDA,0) - NVL(DEVOL.QUANTIDADE,0) - NVL(DEVOL.QTD_DESFZ,0) AS SLD_VD_QTD,
    NVL(VENDAS_SOMA.VENDA_KG,0) - NVL(DEVOL.KGLT,0) - NVL(DEVOL.KGLT_DESFZ,0) AS SLD_VD_KGLT,
    NVL(DEVOL.QTD_DESFZ,0) + NVL(QTD_DEV,0) AS DEVOL_QTD,
    NVL(DEVOL.KGLT_DESFZ,0) + NVL(KGLT_DEV,0) AS DEVOL_KG,
    TABPRECOITEM.MARGEMMINIMA,
    TABPRECOITEM.MARGEMLUCRO,
    CUSTOS.CUSTO_GERENCIAL,
    CUSTOS.CUSTO_CONTABIL,
    
    CASE 
        WHEN TABPRECOCAB.DTFINVIGENCIA < CURRENT_DATE THEN 'N'
        ELSE 'S'
    END AS TABELA_ATIVA,
    TABPRECOCAB.PERCDESCONTO AS PERCENTUAL_DESCONTO,
    TO_CHAR(TABPRECOCAB.DTPRAZOPAGTO, 'DD/MM/YYYY') AS PRAZO_PAGAMENTO,
    COALESCE(SALDO.SALDO,0) AS SALDO_DISPONIVEL,
    COALESCE(IMPOSTOS.ALIQUOTAESP,0)ALIQUOTAESP
FROM TABPRECOCAB
INNER JOIN TABPRECOITEM
    ON TABPRECOITEM.ESTAB = TABPRECOCAB.ESTAB
    AND TABPRECOITEM.TABELA = TABPRECOCAB.TABELA
INNER JOIN FILIAL ON FILIAL.ESTAB = TABPRECOCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = TABPRECOITEM.ITEM
LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
LEFT JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
LEFT JOIN U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA = ITEMAGRO.MARCA 
LEFT JOIN CUSTOS ON CUSTOS.ESTAB = TABPRECOITEM.ESTAB AND CUSTOS.ITEM = TABPRECOITEM.ITEM
INNER JOIN U_TEMPRESA U ON U.ESTAB = TABPRECOCAB.ESTAB
LEFT JOIN SALDO ON
    SALDO.ESTAB = TABPRECOCAB.ESTAB AND
    SALDO.ITEM = TABPRECOITEM.ITEM
LEFT JOIN IMPOSTOS ON
    IMPOSTOS.TRIBUTACAO = ITEMAGRO.TRIBUTACAO
    AND IMPOSTOS.UFORIGEM = CIDADE.UF
LEFT JOIN VENDAS_SOMA ON
    VENDAS_SOMA.ESTABTABPRECO = TABPRECOCAB.ESTAB
    AND VENDAS_SOMA.TABELAPRECO = TABPRECOCAB.TABELA
    AND VENDAS_SOMA.ITEM = TABPRECOITEM.ITEM
LEFT JOIN DEVOL ON
    DEVOL.ESTABTABPRECO = TABPRECOCAB.ESTAB
    AND DEVOL.TABELAPRECO = TABPRECOCAB.TABELA
    AND DEVOL.ITEM = TABPRECOITEM.ITEM
WHERE (0 IN (:ESTAB) OR (:ESTAB) IS NULL OR TABPRECOCAB.ESTAB IN (:ESTAB))
  AND (0 IN (:GRUPO) OR U_GESTOQUE.U_GESTOQUE_ID IN (:GRUPO))
  AND INSUMOS = 'S'
  AND TABPRECOITEM.ITEM > 50
  AND U_GESTOQUE.U_GESTOQUE_ID NOT IN (22)
  AND (
    (:ATIVA = 'S' AND TABPRECOCAB.DTFINVIGENCIA >= CURRENT_DATE) OR
    (:ATIVA = 'N' AND TABPRECOCAB.DTFINVIGENCIA <  CURRENT_DATE) OR
    (:ATIVA = 'T') OR
    (:ATIVA = 'B' AND TABPRECOCAB.DESCRICAO LIKE '%BARTER%')
  )