WITH 
CUSTOS AS (
    SELECT
        ITEMAGROESTAB.ESTAB,
        ITEMAGROESTAB.ITEM,
        ROUND(PCUSTO(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 5, CURRENT_DATE, NULL, NULL), 2) AS CUSTO_GERENCIAL,
        ROUND(PCUSTO(ITEMAGROESTAB.ESTAB, ITEMAGROESTAB.ITEM, 3, CURRENT_DATE, NULL, NULL), 2) AS CUSTO_CONTABIL
    FROM ITEMAGROESTAB
    INNER JOIN U_TEMPRESA U ON U.ESTAB = ITEMAGROESTAB.ESTAB
    WHERE
        INSUMOS = 'S'
        AND ITEMAGROESTAB.ITEM > 50
        AND (0 IN (:ESTAB) OR ITEMAGROESTAB.ESTAB IN (:ESTAB))
        AND EXISTS (
            SELECT 1
            FROM TABPRECOITEM
            WHERE TABPRECOITEM.ESTAB = ITEMAGROESTAB.ESTAB
              AND ITEMAGROESTAB.ITEM = TABPRECOITEM.ITEM
        )
),

MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO

    WHERE
    codigosaldo = 1

    GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO
),
-- ############## SALDO DOS ITENS ############
SALDO AS (
    SELECT 
        ISALDO.codigosaldo,
        IESTAB.ESTAB,
        IESTAB.ITEM ,
        IA.DESCRICAO || '-' || IESTAB.ITEM AS DESCRICAO_CULTIVAR,
        IA.UNIDADE,
        IA.PESOLIQUIDO AS KGLT,
        SUM(ISALDO.SALDOQUANTIDADE) AS SALDO,
        SUM(ISALDO.SALDOQUANTIDADE) * IA.PESOLIQUIDO AS SALDOKG

    FROM ITEMAGROESTAB IESTAB
    
    LEFT JOIN ITEMSALDO ISALDO ON 
        ISALDO.ITEM = IESTAB.ITEM 
        AND ISALDO.ESTAB = IESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ISALDO.ITEM 
        AND MD.ESTAB = ISALDO.ESTAB 
        AND MD.CODIGOSALDO = ISALDO.CODIGOSALDO
        AND TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    INNER JOIN ITEMAGRO IA ON 
        IA.ITEM = IESTAB.ITEM 
            AND IA.ATIVO = 'S'

    WHERE 0=0 
      AND(0 IN (:ESTAB) OR IESTAB.ESTAB IN (:ESTAB))
      AND IA.ATIVO = 'S'
      and ISALDO.codigosaldo  = 1

    GROUP BY IESTAB.ESTAB,
             IESTAB.ITEM, 
             IA.DESCRICAO, 
             IA.UNIDADE,
             IA.PESOLIQUIDO,
             ISALDO.CODIGOSALDO
),
IMPOSTOS AS (
    SELECT DISTINCT
    TRIBUTACAO,
    UF,
    UFORIGEM,
    DIVIDE(ARREDONDAR(T.BASETRI*T.ALIQUOTAESP,0),100) as ALIQUOTAESP
    FROM TRIBITEM T
    WHERE
    ENTRADASAIDA = 'S' 
    AND PRODUTOR = 'S' 
    AND IMPOSTO = 1 
    AND NATOPERACOES LIKE 'P;PR%'
    AND UF = UFORIGEM
    AND ALIQUOTAESP <> 0
)

SELECT 
    TABPRECOCAB.ESTAB,
    FILIAL.REDUZIDO,
    TABPRECOCAB.TABELA,
    TABPRECOCAB.DESCRICAO AS TABELA_DESCRICAO,
    TO_CHAR(TABPRECOCAB.DTINIVIGENCIA, 'DD/MM/YYYY') AS DTINIVIGENCIA,
    TO_CHAR(TABPRECOCAB.DTFINVIGENCIA, 'DD/MM/YYYY') AS DTFINVIGENCIA,
    TO_CHAR(TABPRECOCAB.DTBASE, 'DD/MM/YYYY') AS DTBASE,
    TABPRECOCAB.PERCACRESCIMO AS PERCENTUAL_ACRESCIMO,
    TABPRECOITEM.ITEM,
    ITEMAGRO.DESCRICAO AS ITEM_DESCRICAO,
    ITEMAGRO.GRUPO,
    ITEMGRUPO.DESCRICAO AS SUB_GRUPO_DESCRICAO,
    U_GESTOQUE.U_GESTOQUE_ID,
    U_GESTOQUE.DESCRICAO AS GRUPO_DESCRICAO,
    ITEMAGRO.MARCA,
    ITEMMARCA.DESCRICAO AS MARCA_DESCRICAO, 
    TABPRECOITEM.PRECO,
    TABPRECOITEM.CUSTOGERENCIAL AS CUSTO_TABELA,
    ROUND(
        CASE 
            WHEN TABPRECOITEM.PRECO = 0 THEN 0
            ELSE (DIVIDE((TABPRECOITEM.PRECO - TABPRECOITEM.CUSTOGERENCIAL), TABPRECOITEM.PRECO)) * 100
        END, 2) AS MARGEM,
        
    TABPRECOITEM.SALDODISP  AS SALDO,         -- SALDO DA TABELA ANTIGA
    TABPRECOITEM.VALSALDODISP AS SALDODISP_UN,
    -- SALDO DISPONÍVEL EM KG DA TABPRECOITEM
    TABPRECOITEM.SALDODISP * ITEMAGRO.PESOLIQUIDO AS SALDODISP_KG,
    
    TABPRECOITEM.MARGEMMINIMA,
    TABPRECOITEM.MARGEMLUCRO,
    CUSTOS.CUSTO_GERENCIAL,
    CUSTOS.CUSTO_CONTABIL,
    
    CASE 
        WHEN TABPRECOCAB.DTFINVIGENCIA < CURRENT_DATE THEN 'N'
        ELSE 'S'
    END AS TABELA_ATIVA,
    TABPRECOCAB.PERCDESCONTO AS PERCENTUAL_DESCONTO,
    TO_CHAR(TABPRECOCAB.DTPRAZOPAGTO, 'DD/MM/YYYY') AS PRAZO_PAGAMENTO,
    COALESCE(SALDO.SALDO,0) AS SALDO_DISPONIVEL,
    COALESCE(IMPOSTOS.ALIQUOTAESP,0)ALIQUOTAESP
FROM TABPRECOCAB
INNER JOIN TABPRECOITEM
    ON TABPRECOITEM.ESTAB = TABPRECOCAB.ESTAB
    AND TABPRECOITEM.TABELA = TABPRECOCAB.TABELA
INNER JOIN FILIAL ON FILIAL.ESTAB = TABPRECOCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = TABPRECOITEM.ITEM
LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
LEFT JOIN ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMGRUPO.GRUPO
LEFT JOIN U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
LEFT JOIN ITEMMARCA ON ITEMMARCA.MARCA = ITEMAGRO.MARCA 
LEFT JOIN CUSTOS ON CUSTOS.ESTAB = TABPRECOITEM.ESTAB AND CUSTOS.ITEM = TABPRECOITEM.ITEM
INNER JOIN U_TEMPRESA U ON U.ESTAB = TABPRECOCAB.ESTAB
LEFT JOIN SALDO ON
    SALDO.ESTAB = TABPRECOCAB.ESTAB AND
    SALDO.ITEM = TABPRECOITEM.ITEM
LEFT JOIN IMPOSTOS ON
    IMPOSTOS.TRIBUTACAO = ITEMAGRO.TRIBUTACAO
    AND IMPOSTOS.UFORIGEM = CIDADE.UF
    
WHERE (0 IN (:ESTAB) OR TABPRECOCAB.ESTAB IN (:ESTAB))
  AND (0 IN (:GRUPO) OR U_GESTOQUE.U_GESTOQUE_ID IN (:GRUPO))
  AND INSUMOS = 'S'
  AND TABPRECOITEM.ITEM > 50
  AND U_GESTOQUE.U_GESTOQUE_ID NOT IN (22)
  AND (
    (:ATIVA = 'S' AND TABPRECOCAB.DTFINVIGENCIA >= CURRENT_DATE) OR
    (:ATIVA = 'N' AND TABPRECOCAB.DTFINVIGENCIA <  CURRENT_DATE) OR
    (:ATIVA = 'T') OR
    (:ATIVA = 'B' AND TABPRECOCAB.DESCRICAO LIKE '%BARTER%')
  )
  AND ITEMAGRO.ITEM = 15968