WITH DEVOLUCAO AS (
    SELECT /*+ MATERIALIZE */
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    SUM(N.QUANTIDADE) AS QTDDEVOL
    FROM NFITEMAPARTIRDE N
    INNER JOIN NFCAB NF ON 
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NF.NOTACONF
    INNER JOIN NATOPERACAO NAT ON
        NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
        AND NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
    WHERE NAT.TIPODCTO = 'D'
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM
),
CAB AS (
    SELECT /*+ MATERIALIZE */
    NFCAB.ESTAB,
    NFCAB.NOTA,
    NFCAB.SEQNOTA,
    NFCAB.NUMEROCM,
    NFCAB.SEQENDERECO,
    NFCAB.NOTACONF,
    NFCAB.STATUS,
    NFCAB.DTEMISSAO
    FROM NFCAB
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    WHERE NFCFG.ENTRADASAIDA = 'S'
),
ITENS AS (
    SELECT
    CAB.ESTAB,
    CAB.NOTA,
    LISTAGG(distinct NFITEM.CFOP,',') WITHIN GROUP (ORDER BY CAB.ESTAB) AS CFOP
    FROM NFITEM
    INNER JOIN CAB ON
        CAB.ESTAB = NFITEM.ESTAB
        AND CAB.SEQNOTA = NFITEM.SEQNOTA
    GROUP BY CAB.ESTAB,CAB.NOTA
),
NOTAS AS (
    SELECT /*+ MATERIALIZE */
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCABAGRFIN.SEQPAGAMENTO,
    NFCAB.DTEMISSAO,
    SUM(NFITEM.QUANTIDADE) AS QUANTIDADE,
    DEVOLUCAO.QTDDEVOL
    FROM CAB NFCAB

    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCAB.NOTACONF
    INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID
    INNER JOIN NFCABAGRFIN ON
        NFCABAGRFIN.ESTAB = NFCAB.ESTAB
        AND NFCABAGRFIN.SEQNOTA = NFCAB.SEQNOTA
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    INNER JOIN DEVOLUCAO ON
        DEVOLUCAO.ESTABORIGEM = NFITEM.ESTAB
    AND DEVOLUCAO.SEQNOTAORIGEM = NFITEM.SEQNOTA

    where
    NVL(NFCAB.STATUS,'X') <> 'C'
    AND U_TIPOOP.TIPOOP IN ('V','VF')
    GROUP BY NFCAB.ESTAB,NFCAB.SEQNOTA,NFCAB.DTEMISSAO,DEVOLUCAO.QTDDEVOL,NFCABAGRFIN.SEQPAGAMENTO

    HAVING 
    SUM(NFITEM.QUANTIDADE) - NVL(DEVOLUCAO.QTDDEVOL, 0) = 0
    
),
DPL_BX AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VALOR) AS VALOR FROM PRDUPRED
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VLRCHEQREC) AS VALOR FROM PRDURECH
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREDUP
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECAR 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREOUT 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECM WHERE TROCO = 'N'
),
BAIXAS_DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,SUM(VALOR) AS VALOR FROM DPL_BX
    GROUP BY EMPRESA,DUPREC,SEQRECBTO 
),
AGR AS  (
    SELECT /*+ MATERIALIZE */
    AGRFINDUPREC.ESTAB,
    AGRFINDUPREC.SEQPAGAMENTO,
    AGRFINDUPREC.DUPREC
    FROM AGRFINDUPREC
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = AGRFINDUPREC.ESTAB
        AND NOTAS.SEQPAGAMENTO = AGRFINDUPREC.SEQPAGAMENTO
),
BX AS (
    SELECT /*+ MATERIALIZE */
    PR.EMPRESA,
    PR.DUPREC,
    PR.DTRECBTO,
    PR.NRORECIBO,
    PR.ESTABRECIBO,
    PR.SEQRECBTO,
    CASE WHEN PR.TIPOREC IN ('R') THEN DPL_BX.VALOR ELSE DPL_BX.VALOR *-1 END  VLR
    FROM PRDUPREC PR
    INNER JOIN DPL_BX ON
        DPL_BX.EMPRESA = PR.EMPRESA
        AND DPL_BX.DUPREC = PR.DUPREC
        AND DPL_BX.SEQRECBTO = PR.SEQRECBTO
    WHERE PR.TIPOREC IN ('R','D')
    AND PR.DTRECBTO BETWEEN :DTINI AND :DTFIM
),
DPL as (
    SELECT /*+ MATERIALIZE */
    EMPRESA,
    DUPREC,
    DTEMISSAO,
    DTVENCTO,
    CLIENTE,
    SEQENDERECO,
    SITUACAO,
    VALOR,
    JUROS,
    DESCONTO
    FROM PDUPREC
),
EMP AS (
    SELECT
    ESTAB,
    CASE 
        WHEN OUTROS = 'S' THEN 'O'
        WHEN INSUMOS = 'S' THEN 'I'
        WHEN GRAOS = 'S' THEN 'C'
        ELSE 'O'
    END TIPOESTAB
    FROM U_TEMPRESA
),
CMV as (
select distinct
    BX.EMPRESA,
    BX.DUPREC,
    BX.SEQRECBTO
    from contamovlanac cl
    inner join contamovlan c on
        c.estab = cl.estabacertado
        and c.numerocm = cl.numerocm
        and c.seqcm = cl.seqacertada
    inner join contamovtp tp on
        tp.tipo = c.tipo
        and tp.DEBCRED = c.DEBCRED
    inner join BX on
        BX.ESTABRECIBO = cl.ESTABRECIBO
        AND BX.NRORECIBO = cl.NRORECIBO
    where
    tp.debcred = 'C' and tp.RECIBO = 'S'
    AND TP.DESCRICAO LIKE '%DEVOL%'
),
RENEG AS (
    SELECT DISTINCT /*+ MATERIALIZE */
    ESTAB,
    DUPREC
    FROM RENEGOCIACAODOCTOS
),
PAG AS (
    SELECT DISTINCT /*+ MATERIALIZE */
    ESTABRECIBO,
    NRORECIBO
    FROM PPDUPPAG
),
PAG_AUX AS (
    SELECT DISTINCT /*+ MATERIALIZE */
    NRORECIBO,
    FORNECEDOR
    FROM PPDUPPAG
)
SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BX.DTRECBTO,
P.VALOR AS VLR,
P.JUROS,
P.DESCONTO,
SUM(BX.VLR) AS VALORPAGO,
SUM(BX.VLR) AS VLRBAIXADO,
CASE
    WHEN RENEG.DUPREC IS NOT NULL THEN 'Renegociação'
    WHEN CMV.EMPRESA IS NOT NULL OR AGR.DUPREC IS NOT NULL THEN 'Devolução'
    WHEN PAG_AUX.NRORECIBO IS NOT NULL THEN 'Baixa em Grãos'
    WHEN PAG.ESTABRECIBO IS NOT NULL THEN 'Baixa em Grãos'
    /*WHEN PSITUACA.DESCRICAO LIKE '%SOJA%' OR PSITUACA.DESCRICAO LIKE '%TRIGO%'
    OR PSITUACA.DESCRICAO LIKE '%MILHO%' OR PSITUACA.DESCRICAO LIKE '%FEIJAO%'
    OR PSITUACA.DESCRICAO LIKE '%SORGO%' OR PSITUACA.DESCRICAO LIKE '%UVA%'
    THEN 'Baixa em Grãos'*/
    else 'Baixa Financeira'
END TIPORECEB,
NFCAB.NOTA,
ITENS.CFOP
FROM DPL P

INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BX ON
    BX.EMPRESA = P.EMPRESA
    AND BX.DUPREC = P.DUPREC

--- DEVOLUÇÃO EM CONTA MOVIMENTO
LEFT JOIN CMV ON
    CMV.EMPRESA = BX.EMPRESA
    AND CMV.DUPREC = BX.DUPREC
    AND CMV.SEQRECBTO = BX.SEQRECBTO
    
--- TITULOS RENEGOCIADOS
LEFT JOIN RENEG ON
    RENEG.ESTAB = P.EMPRESA
    AND RENEG.DUPREC = P.DUPREC

-- NOTAS 100% DEVOLVIDAS
LEFT JOIN AGR ON
    AGR.ESTAB = P.EMPRESA
    AND AGR.DUPREC = P.DUPREC
    
LEFT JOIN AGRFINDUPREC F ON
    F.ESTAB = P.EMPRESA
    AND F.DUPREC = P.DUPREC

LEFT JOIN NFCABAGRFIN N ON
    N.ESTAB = F.ESTAB
    AND N.SEQPAGAMENTO = F.SEQPAGAMENTO

LEFT JOIN NFCAB ON
    NFCAB.ESTAB = N.ESTAB
    AND NFCAB.SEQNOTA = N.SEQNOTA
    AND NFCAB.NUMEROCM = P.CLIENTE

LEFT JOIN ITENS ON
    ITENS.ESTAB = NFCAB.ESTAB
    AND ITENS.NOTA = NFCAB.NOTA
    
--- A PAGAR EM RECEBIDO
LEFT JOIN PAG ON
    PAG.ESTABRECIBO = BX.ESTABRECIBO
    AND PAG.NRORECIBO = BX.NRORECIBO

LEFT JOIN PAG_AUX ON
    PAG_AUX.FORNECEDOR = P.CLIENTE
    AND PAG_AUX.NRORECIBO = BX.NRORECIBO

WHERE
BX.DTRECBTO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))

GROUP BY
FILIAL.REDUZIDO,
P.DUPREC,
PSITUACA.DESCRICAO,
P.CLIENTE,
CONTAMOV.NOME ,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF),
P.DTEMISSAO,
P.DTVENCTO,
BX.DTRECBTO,
P.VALOR,
P.JUROS,
P.DESCONTO,
RENEG.DUPREC,
CMV.EMPRESA,
AGR.DUPREC,
NFCAB.NOTA,
ITENS.CFOP,
PAG.ESTABRECIBO,
PAG_AUX.NRORECIBO

