WITH DEVOLUCAO AS (
    SELECT /*+ MATERIALIZE */
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    SUM(N.QUANTIDADE) AS QTDDEVOL
    FROM NFITEMAPARTIRDE N
    INNER JOIN NFCAB NF ON 
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NF.NOTACONF
    INNER JOIN NATOPERACAO NAT ON
        NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
        AND NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
    WHERE NAT.TIPODCTO = 'D'
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM
),
NOTAS AS (
    SELECT /*+ MATERIALIZE */
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCABAGRFIN.SEQPAGAMENTO,
    NFCAB.DTEMISSAO,
    SUM(NFITEM.QUANTIDADE) AS QUANTIDADE,
    DEVOLUCAO.QTDDEVOL
    FROM NFCAB

    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCAB.NOTACONF
    INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID
    INNER JOIN NFCABAGRFIN ON
        NFCABAGRFIN.ESTAB = NFCAB.ESTAB
        AND NFCABAGRFIN.SEQNOTA = NFCAB.SEQNOTA
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    INNER JOIN DEVOLUCAO ON
        DEVOLUCAO.ESTABORIGEM = NFITEM.ESTAB
    AND DEVOLUCAO.SEQNOTAORIGEM = NFITEM.SEQNOTA

    where
    NVL(NFCAB.STATUS,'X') <> 'C'
    AND U_TIPOOP.TIPOOP IN ('V','VF')
    GROUP BY NFCAB.ESTAB,NFCAB.SEQNOTA,NFCAB.DTEMISSAO,DEVOLUCAO.QTDDEVOL,NFCABAGRFIN.SEQPAGAMENTO

    HAVING 
    SUM(NFITEM.QUANTIDADE) - NVL(DEVOLUCAO.QTDDEVOL, 0) = 0
    
),
DPL_BX AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VALOR) AS VALOR FROM PRDUPRED
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VLRCHEQREC) AS VALOR FROM PRDURECH
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREDUP
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECAR 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREOUT 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECM WHERE TROCO = 'N'
),
BAIXAS_DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,SUM(VALOR) AS VALOR FROM DPL_BX
    GROUP BY EMPRESA,DUPREC,SEQRECBTO
),
AGR AS  (
    SELECT /*+ MATERIALIZE */
    AGRFINDUPREC.ESTAB,
    AGRFINDUPREC.SEQPAGAMENTO,
    AGRFINDUPREC.DUPREC
    FROM AGRFINDUPREC
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = AGRFINDUPREC.ESTAB
        AND NOTAS.SEQPAGAMENTO = AGRFINDUPREC.SEQPAGAMENTO
),
BX AS (
    SELECT /*+ MATERIALIZE */
    PR.EMPRESA,
    PR.DUPREC,
    PR.DTRECBTO,
    --PR.TIPOREC,
    PR.NRORECIBO,
    PR.ESTABRECIBO,
    PR.SEQRECBTO,
    DPL_BX.VALOR AS VLR
    --PR.VALOR AS VLR
    FROM PRDUPREC PR
    INNER JOIN DPL_BX ON
        DPL_BX.EMPRESA = PR.EMPRESA
        AND DPL_BX.DUPREC = PR.DUPREC
        AND DPL_BX.SEQRECBTO = PR.SEQRECBTO
    WHERE PR.TIPOREC IN ('R')
),
BAIXAS AS (
    SELECT
    PP.EMPRESA,
    PP.DUPREC,
    PP.DTRECBTO,
    SUM(PP.VLR) AS VLR
    --SUM(CASE WHEN PP.TIPOREC = 'R' THEN (PP.VALOR) ELSE 0 END) VLR
    /*SUM(CASE WHEN PP.TIPOREC = 'J' THEN SUM(PP.VALOR) ELSE 0 END) JUROS,
    SUM(CASE WHEN PP.TIPOREC = 'D' THEN SUM(PP.VALOR) ELSE 0 END) DESCONT*/
    FROM BX PP

    --WHERE PP.TIPOREC IN ('R')
    GROUP BY PP.EMPRESA,PP.DUPREC,PP.DTRECBTO
),
DPL as (
    SELECT /*+ MATERIALIZE */
    EMPRESA,
    DUPREC,
    DTEMISSAO,
    DTVENCTO,
    CLIENTE,
    SEQENDERECO,
    SITUACAO,
    VALOR,
    JUROS,
    DESCONTO
    FROM PDUPREC
),
EMP AS (
    SELECT
    ESTAB,
    CASE 
        WHEN OUTROS = 'S' THEN 'O'
        WHEN INSUMOS = 'S' THEN 'I'
        WHEN GRAOS = 'S' THEN 'C'
        ELSE 'O'
    END TIPOESTAB
    FROM U_TEMPRESA
),
cmv as (
select distinct
    BX.EMPRESA,
    BX.DUPREC,
    BX.SEQRECBTO
    from contamovlanac cl
    inner join contamovlan c on
        c.estab = cl.estabacertado
        and c.numerocm = cl.numerocm
        and c.seqcm = cl.seqacertada
    inner join contamovtp tp on
        tp.tipo = c.tipo
        and tp.DEBCRED = c.DEBCRED
    inner join BX on
        BX.ESTABRECIBO = cl.ESTABRECIBO
        AND BX.NRORECIBO = cl.NRORECIBO
    where
    tp.debcred = 'C' and tp.RECIBO = 'S'
    AND TP.DESCRICAO LIKE '%DEVOL%'
)
SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
P.VALOR AS VLR,
--BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
'Devolução' as TIPORECEB--,CASE WHEN CMV.DUPREC IS NOT NULL THEN 'Devolução' ELSE null END RECEB
,NFCAB.NOTA
FROM DPL P
INNER JOIN AGR ON
    AGR.ESTAB = P.EMPRESA
    AND AGR.DUPREC = P.DUPREC
INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BX BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC
    
LEFT JOIN CMV ON
    CMV.EMPRESA = BAIXAS.EMPRESA
    AND CMV.DUPREC = BAIXAS.DUPREC
    AND CMV.SEQRECBTO = BAIXAS.SEQRECBTO

LEFT JOIN NFCABAGRFIN ON
    NFCABAGRFIN.ESTAB = AGR.ESTAB
    AND NFCABAGRFIN.SEQPAGAMENTO = AGR.SEQPAGAMENTO

LEFT JOIN NFCAB ON
    NFCAB.ESTAB = NFCABAGRFIN.ESTAB
    AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
    AND NFCAB.NUMEROCM = P.CLIENTE
    
WHERE
BAIXAS.DTRECBTO BETWEEN :DTINI AND :DTFIM
--P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
AND CMV.EMPRESA IS NULL
--and p.duprec  = '141839-1'
--AND P.DUPREC = '392619-1'
--AND P.DUPREC = '100588-1'

UNION ALL

SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
P.VALOR AS VLR,
--BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
'Devolução' as TIPORECEB--,CASE WHEN CMV.DUPREC IS NOT NULL THEN 'Devolução' ELSE null END RECEB
,NFCAB.NOTA
FROM DPL P
INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BX BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC
    AND NVL(BAIXAS.NRORECIBO,0) <> 0
    
INNER JOIN CMV ON
    CMV.EMPRESA = BAIXAS.EMPRESA
    AND CMV.DUPREC = BAIXAS.DUPREC
    AND CMV.SEQRECBTO = BAIXAS.SEQRECBTO
    
LEFT JOIN AGRFINDUPREC F ON
    F.ESTAB = P.EMPRESA
    AND F.DUPREC = P.DUPREC

LEFT JOIN NFCABAGRFIN ON
    NFCABAGRFIN.ESTAB = F.ESTAB
    AND NFCABAGRFIN.SEQPAGAMENTO = F.SEQPAGAMENTO

LEFT JOIN NFCAB ON
    NFCAB.ESTAB = NFCABAGRFIN.ESTAB
    AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
    AND NFCAB.NUMEROCM = P.CLIENTE
    
WHERE
BAIXAS.DTRECBTO BETWEEN :DTINI AND :DTFIM
--P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
--and p.duprec  = '141839-1'
--AND P.DUPREC = '392619-1'
--AND P.DUPREC = '100588-1'

UNION ALL

SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
P.VALOR AS VLR,
--BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
'Renegociação' as TIPORECEB--,CASE WHEN CMV.DUPREC IS NOT NULL THEN 'Devolução' ELSE null END RECEB
,NFCAB.NOTA
FROM DPL P

INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BX BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC
    AND NVL(BAIXAS.NRORECIBO,0) = 0
    
LEFT JOIN AGRFINDUPREC F ON
    F.ESTAB = P.EMPRESA
    AND F.DUPREC = P.DUPREC

LEFT JOIN NFCABAGRFIN ON
    NFCABAGRFIN.ESTAB = F.ESTAB
    AND NFCABAGRFIN.SEQPAGAMENTO = F.SEQPAGAMENTO

LEFT JOIN NFCAB ON
    NFCAB.ESTAB = NFCABAGRFIN.ESTAB
    AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
    AND NFCAB.NUMEROCM = P.CLIENTE
    
WHERE EXISTS (
    SELECT 1 FROM RENEGOCIACAODOCTOS
    WHERE RENEGOCIACAODOCTOS.ESTAB = P.EMPRESA
    AND RENEGOCIACAODOCTOS.DUPREC = P.DUPREC
)
--AND P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND BAIXAS.DTRECBTO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
--and p.duprec  = '141839-1'
--AND P.DUPREC = '392619-1'
--AND P.DUPREC = '100588-1'

UNION ALL

SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BX.DTRECBTO,
P.VALOR AS VLR,
--SUM(BX.VALOR) AS VLR,
P.JUROS,
P.DESCONTO,
SUM(BX.VLR) - NVL(P.DESCONTO,0) AS VALORPAGO,
SUM(BX.VLR) - NVL(P.DESCONTO,0) AS VLRBAIXADO,
CASE 
    WHEN PSITUACA.DESCRICAO LIKE '%SOJA%' OR PSITUACA.DESCRICAO LIKE '%TRIGO%'
    OR PSITUACA.DESCRICAO LIKE '%MILHO%' OR PSITUACA.DESCRICAO LIKE '%FEIJAO%'
    OR PSITUACA.DESCRICAO LIKE '%SORGO%' OR PSITUACA.DESCRICAO LIKE '%UVA%'
    THEN 'Baixa em Grãos'
    else 'Baixa Financeira'
END TIPORECEB
,NFCAB.NOTA
FROM DPL P
INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BX ON
    BX.EMPRESA = P.EMPRESA
    AND BX.DUPREC = P.DUPREC
    AND NVL(BX.NRORECIBO,0) <> 0

LEFT JOIN AGRFINDUPREC F ON
    F.ESTAB = P.EMPRESA
    AND F.DUPREC = P.DUPREC

LEFT JOIN NFCABAGRFIN ON
    NFCABAGRFIN.ESTAB = F.ESTAB
    AND NFCABAGRFIN.SEQPAGAMENTO = F.SEQPAGAMENTO

LEFT JOIN NFCAB ON
    NFCAB.ESTAB = NFCABAGRFIN.ESTAB
    AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
    AND NFCAB.NUMEROCM = P.CLIENTE
    
WHERE
BX.DTRECBTO BETWEEN :DTINI AND :DTFIM
--P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
AND 
    NOT EXISTS (
    SELECT 1 FROM RENEGOCIACAODOCTOS
    WHERE RENEGOCIACAODOCTOS.ESTAB = P.EMPRESA
    AND RENEGOCIACAODOCTOS.DUPREC = P.DUPREC
    )
    and
    NOT EXISTS (
        SELECT 1 FROM AGR
        WHERE AGR.ESTAB = P.EMPRESA
        AND AGR.DUPREC = P.DUPREC
    )
    
    AND NOT EXISTS (
    SELECT
    1
    FROM CMV WHERE CMV.EMPRESA = BX.EMPRESA
    AND CMV.DUPREC = BX.DUPREC
    AND CMV.SEQRECBTO = BX.SEQRECBTO
)
--AND P.DUPREC = '392619-1'
--and p.duprec  = '141839-1'
--AND P.DUPREC = '100588-1'

GROUP BY
FILIAL.REDUZIDO,
P.DUPREC,
PSITUACA.DESCRICAO,
P.CLIENTE,
CONTAMOV.NOME,
ENDERECO.CNPJF,
CONTAMOV.CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BX.DTRECBTO,
P.JUROS,
P.DESCONTO,P.VALOR,
NFCAB.NOTA
