WITH DEVOLUCAO AS (
    SELECT /*+ MATERIALIZE */
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    SUM(N.QUANTIDADE) AS QTDDEVOL
    FROM NFITEMAPARTIRDE N
    INNER JOIN NFCAB NF ON 
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NF.NOTACONF
    INNER JOIN NATOPERACAO NAT ON
        NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
        AND NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
    WHERE NAT.TIPODCTO = 'D'
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM
),
NOTAS AS (
    SELECT /*+ MATERIALIZE */
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCABAGRFIN.SEQPAGAMENTO,
    NFCAB.DTEMISSAO,
    SUM(NFITEM.QUANTIDADE) AS QUANTIDADE,
    DEVOLUCAO.QTDDEVOL
    FROM NFCAB

    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCAB.NOTACONF
    INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID
    INNER JOIN NFCABAGRFIN ON
        NFCABAGRFIN.ESTAB = NFCAB.ESTAB
        AND NFCABAGRFIN.SEQNOTA = NFCAB.SEQNOTA
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

    INNER JOIN DEVOLUCAO ON
        DEVOLUCAO.ESTABORIGEM = NFITEM.ESTAB
    AND DEVOLUCAO.SEQNOTAORIGEM = NFITEM.SEQNOTA

    where
    NVL(NFCAB.STATUS,'X') <> 'C'
    AND U_TIPOOP.TIPOOP IN ('V','VF')
    GROUP BY NFCAB.ESTAB,NFCAB.SEQNOTA,NFCAB.DTEMISSAO,DEVOLUCAO.QTDDEVOL,NFCABAGRFIN.SEQPAGAMENTO

    HAVING 
    SUM(NFITEM.QUANTIDADE) - NVL(DEVOLUCAO.QTDDEVOL, 0) = 0
    
),
AGR AS  (
    SELECT /*+ MATERIALIZE */
    AGRFINDUPREC.ESTAB,
    AGRFINDUPREC.SEQPAGAMENTO,
    AGRFINDUPREC.DUPREC
    FROM AGRFINDUPREC
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = AGRFINDUPREC.ESTAB
        AND NOTAS.SEQPAGAMENTO = AGRFINDUPREC.SEQPAGAMENTO
),
BAIXAS AS (
    SELECT
    PP.EMPRESA,
    PP.DUPREC,
    PP.DTRECBTO,
    SUM(CASE WHEN PP.TIPOREC = 'R' THEN (PP.VALOR) ELSE 0 END) VLR/*,
    SUM(CASE WHEN PP.TIPOREC = 'J' THEN SUM(PP.VALOR) ELSE 0 END) JUROS,
    SUM(CASE WHEN PP.TIPOREC = 'D' THEN SUM(PP.VALOR) ELSE 0 END) DESCONT*/
    FROM PRDUPREC PP

    WHERE PP.TIPOREC IN ('R')
    GROUP BY PP.EMPRESA,PP.DUPREC,PP.DTRECBTO

),
DPL as  (
    SELECT /*+ MATERIALIZE */
    EMPRESA,
    DUPREC,
    DTEMISSAO,
    DTVENCTO,
    CLIENTE,
    SEQENDERECO,
    SITUACAO,
    VALOR,
    JUROS,
    DESCONTO
    FROM PDUPREC
),
EMP AS (
    SELECT
    ESTAB,
    CASE 
        WHEN OUTROS = 'S' THEN 'O'
        WHEN INSUMOS = 'S' THEN 'I'
        WHEN GRAOS = 'S' THEN 'C'
        ELSE 'O'
    END TIPOESTAB
    FROM U_TEMPRESA
)
SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
'Devolução' as TIPORECEB
FROM DPL P
INNER JOIN AGR ON
    AGR.ESTAB = P.EMPRESA
    AND AGR.DUPREC = P.DUPREC
INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC

WHERE
P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))

UNION ALL

SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
'Renegociação' as TIPORECEB
FROM DPL P

INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC

WHERE EXISTS (
    SELECT 1 FROM RENEGOCIACAODOCTOS
    WHERE RENEGOCIACAODOCTOS.ESTAB = P.EMPRESA
    AND RENEGOCIACAODOCTOS.DUPREC = P.DUPREC
)
AND P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))

UNION ALL

SELECT
FILIAL.REDUZIDO AS FILIAL,
P.DUPREC,
PSITUACA.DESCRICAO AS TIPOCOBRANCA,
P.CLIENTE AS CODLCIENTE,
CONTAMOV.NOME AS CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) CNPJF,
P.DTEMISSAO,
P.DTVENCTO,
BAIXAS.DTRECBTO,
BAIXAS.VLR,
P.JUROS,
P.DESCONTO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VALORPAGO,
BAIXAS.VLR - NVL(P.DESCONTO,0) AS VLRBAIXADO,
PSITUACA.DESCRICAO as TIPORECEB
FROM DPL P
INNER JOIN PSITUACA ON PSITUACA.SITUACAO = P.SITUACAO
INNER JOIN FILIAL ON FILIAL.ESTAB = P.EMPRESA
INNER JOIN EMP ON EMP.ESTAB = P.EMPRESA
LEFT JOIN ENDERECO ON 
    ENDERECO.NUMEROCM = P.CLIENTE
    AND ENDERECO.SEQENDERECO = P.SEQENDERECO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = P.CLIENTE

INNER JOIN BAIXAS ON
    BAIXAS.EMPRESA = P.EMPRESA
    AND BAIXAS.DUPREC = P.DUPREC

WHERE
P.DTEMISSAO BETWEEN :DTINI AND :DTFIM
AND ('T' IN (:TPESTAB) OR EMP.TIPOESTAB IN (:TPESTAB))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
AND (
    NOT EXISTS (
    SELECT 1 FROM RENEGOCIACAODOCTOS
    WHERE RENEGOCIACAODOCTOS.ESTAB = P.EMPRESA
    AND RENEGOCIACAODOCTOS.DUPREC = P.DUPREC
    )
    OR
    NOT EXISTS (
        SELECT 1 FROM AGR
        WHERE AGR.ESTAB = P.EMPRESA
        AND AGR.DUPREC = P.DUPREC
    )
)
