WITH DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VALOR) AS VALOR FROM PRDUPRED
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VLRCHEQREC) AS VALOR FROM PRDURECH
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREDUP 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECAR
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREOUT 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECM WHERE TROCO = 'N'
),
BAIXAS_DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO, SUM(VALOR) AS VALOR FROM DPL
    GROUP BY EMPRESA,DUPREC,SEQRECBTO
),    
BAIXAS AS
    (SELECT 
        PRDUPREC.EMPRESA,
        PRDUPREC.DUPREC,
        SUM(BAIXAS_DPL.VALOR) AS VLR,
        SUM(PRDUPREC.VALOR * CASE WHEN PRDUPREC.TIPOREC IN ('R','J') THEN 1 ELSE -1 END) AS PAGO,
        SUM(CASE WHEN PRDUPREC.TIPOREC IN ('J') THEN BAIXAS_DPL.VALOR ELSE 0 END) JUROS,
        SUM(CASE WHEN PRDUPREC.TIPOREC IN ('R') THEN BAIXAS_DPL.VALOR ELSE 0 END) REC
    FROM PRDUPREC
    INNER JOIN BAIXAS_DPL
        ON  BAIXAS_DPL.EMPRESA  = PRDUPREC.EMPRESA
        AND BAIXAS_DPL.DUPREC   = PRDUPREC.DUPREC
        AND BAIXAS_DPL.SEQRECBTO= PRDUPREC.SEQRECBTO
    WHERE
            TIPOREC IN ('R','J')
        AND DTRECBTO <= :DTBASE
    GROUP BY
        PRDUPREC.EMPRESA,
        PRDUPREC.DUPREC
),    
REAJ_ANT AS
    (SELECT
        ESTAB,
        DUPREC,
        DTREAJUSTE,
        VALORATU,
        VALORREAJ,
        ROW_NUMBER() OVER (PARTITION BY ESTAB, DUPREC ORDER BY DTREAJUSTE DESC) AS RN
    FROM PDUPRECREAJ
    WHERE DTREAJUSTE <= (:DTBASE)
    ),
REAJ_MAX AS
    (SELECT
        ESTAB,
        DUPREC,
        DTREAJUSTE,
        VALORATU,
        VALORREAJ,
        ROW_NUMBER() OVER (PARTITION BY ESTAB, DUPREC ORDER BY DTREAJUSTE DESC) AS RN
    FROM PDUPRECREAJ
    WHERE
        DTREAJUSTE >= (:DTBASE)
    ),
DUP_REAJ AS
    (SELECT 
        RM.ESTAB,
        RM.DUPREC,
        (CASE 
         -- Se a data de posição for menor que a data do reajuste, e não houver registro em REAJ_ANT,
         -- usa o VALORATU (valor antes do reajuste) de RM; caso haja RA, você pode optar por usar
         -- o VALORREAJ de RA se isso for o desejado. Aqui, por exemplo, usamos NVL para usar RA.VALORREAJ se existir;
         -- se não, usamos RM.VALORATU.
            WHEN (:DTBASE) < RM.DTREAJUSTE
                THEN NVL(RA.VALORREAJ, RM.VALORATU)
            ELSE RM.VALORREAJ
        END
        ) AS VALORREAJ
        FROM    (SELECT *
                FROM REAJ_MAX
                WHERE RN = 1
                ) RM
            LEFT JOIN   (SELECT *
                        FROM REAJ_ANT
                        WHERE RN = 1
                        ) RA
                ON  RM.ESTAB = RA.ESTAB
                AND RM.DUPREC = RA.DUPREC
),
DUPLICATAS AS (
    SELECT /*+ MATERIALIZE */ 
    PDUPREC.EMPRESA AS ESTAB,
    FILIAL.REDUZIDO AS FILIAL,
    PDUPREC.CLIENTE AS NUMEROCM,
    PDUPREC.SEQENDERECO,
    PDUPREC.DUPREC AS DOCUMENTO,
    'DPL' AS TIPO_DOC,
    'DUPLICATA' AS DESC_TIPO,
    NVL(PANALITI.CTACTB,AUX.CTACTB) AS CTACTB,
    PSITUACA.DESCRICAO AS STATUS,
    PDUPREC.NROPARCELA AS PARCELA,
    TO_CHAR(PDUPREC.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
    EXTRACT(YEAR FROM PDUPREC.DTEMISSAO) AS ANO,
    EXTRACT(MONTH FROM PDUPREC.DTEMISSAO) AS MES,
    TO_CHAR(PDUPREC.DTVENCTO,'DD/MM/YYYY')DTVENCTO,
    ARREDONDAR(CAST(:DTBASE AS DATE) - PDUPREC.DTVENCTO ,0) AS ATRASO,
    LIMCRED.DESCRICAO AS CULTURA,
    PDUPREC.VALORFATURA AS VALOR,
    PDUPREC.JUROS,
    CASE WHEN NVL(PDUPREC.SITUACAO,0) <> 39 THEN NVL(VALORREAJ,PDUPREC.VALOR) - NVL(BAIXAS.REC,0) ELSE NVL(VALORREAJ,PDUPREC.VALOR) - NVL(PDUPREC.DESCONTO,0) END AS SALDO,
    PDUPREC.REPRESENT,
    OCORRENCIADUPREC.IDOCORRENCIA
    FROM PDUPREC
    INNER JOIN FILIAL ON FILIAL.ESTAB = PDUPREC.EMPRESA
    LEFT JOIN LIMCRED ON LIMCRED.ID =  PDUPREC.LIMCRED_ID
    LEFT JOIN PSITUACA ON PSITUACA.SITUACAO = PDUPREC.SITUACAO
    LEFT JOIN BAIXAS ON
    BAIXAS.EMPRESA = PDUPREC.EMPRESA
    AND BAIXAS.DUPREC = PDUPREC.DUPREC

    LEFT JOIN DUP_REAJ ON
        DUP_REAJ.ESTAB = PDUPREC.EMPRESA
        AND DUP_REAJ.DUPREC = PDUPREC.DUPREC
    
    LEFT JOIN PBLOQDIV ON
        PBLOQDIV.EMPRESA = PDUPREC.EMPRESA
        AND PBLOQDIV.DUPREC = PDUPREC.DUPREC
    
    LEFT JOIN ( 
        SELECT OCORRENCIADUPREC.ESTAB,OCORRENCIADUPREC.DUPREC,
        MAX(OCORRENCIADUPREC.IDOCORRENCIA)IDOCORRENCIA
        FROM OCORRENCIADUPREC
        INNER JOIN OCORRENCIAFINAN ON ocorrenciafinan.idocorrencia = ocorrenciaduprec.idocorrencia
        GROUP BY OCORRENCIADUPREC.ESTAB,OCORRENCIADUPREC.DUPREC
    )OCORRENCIADUPREC ON 
        OCORRENCIADUPREC.ESTAB = PDUPREC.EMPRESA
        AND OCORRENCIADUPREC.DUPREC = PDUPREC.DUPREC
    
    LEFT JOIN PANALITI ON
        PANALITI.EMPRESA = FILIAL.EMPRESA
        AND PANALITI.ANALITICA = PDUPREC.ANALITICA
    
    LEFT JOIN PANALITI AUX ON
        AUX.EMPRESA = 1
        AND AUX.ANALITICA = PDUPREC.ANALITICA
    
    WHERE
    ARREDONDAR(NVL(VALORREAJ,PDUPREC.VALOR) - NVL(BAIXAS.REC,0) -  NVL(PDUPREC.DESCPEND,0) ,0) > 0
    AND  ((NVL(VALORREAJ,PDUPREC.VALOR)  - NVL(BAIXAS.REC,0)) - NVL(PDUPREC.DESCONTO,0)) <> 0
    AND PDUPREC.DUPREC <> ('84388-1') 
    AND (0 in (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
    AND PDUPREC.DTEMISSAO BETWEEN :DTINI AND :DTFIM
    AND PDUPREC.DTVENCTO BETWEEN :DTINIVENC AND :DTFIMVENC
    
    <#if REPRESENT?has_content>  
    AND PDUPREC.REPRESENT IN (:REPRESENT)
     </#if>
      
     <#if NUMEROCM?has_content>  
        AND PDUPREC.CLIENTE IN (:NUMEROCM)
    </#if>
    
    AND 
    FILIAL.EMPRESA IN (
        SELECT DISTINCT
        EMPRESA 
        FROM FILIAL
        WHERE (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
        AND FILIAL.EMPRESA IN (
            SELECT DISTINCT
            EMPRESA
            FROM FILIAL
            WHERE
            (:EMPRESA = 1 AND EMPRESA >=1)
            OR
            (:EMPRESA = 2 AND EMPRESA <100)
        )
    )
),
BAIXAS_CM AS (
    SELECT ESTABACERTADO,SEQACERTADA,NUMEROCM,SUM(VALOR) AS VLR FROM CONTAMOVLANAC
    WHERE TIPO = 'B' AND CONTAMOVLANAC.DTACERTO <= (:DTBASE)
    GROUP BY ESTABACERTADO,SEQACERTADA,NUMEROCM
    ),
CONTA_MOV AS (
    SELECT /*+ MATERIALIZE */ 
    CM.ESTAB,
    FILIAL.REDUZIDO AS FILIAL,
    CM.NUMEROCM,
    0 AS SEQENDERECO,
    CM.NRODOCTO AS DOCUMENTO,
    CONTAMOVTP.TIPO as TIPO_DOC,
    CONTAMOVTP.DESCRICAO as DESC_TIPO,
    CONTAMOVTP.CTAPAD AS CTACTB,
    CASE 
        WHEN CM.SITUACAO = 'B' THEN 'Baixado'
        when CM.Situacao = 'P' THEN 'Pendente'
        when CM.Situacao = 'A' THEN 'Acertado Parcialmente'
    END STATUS,--SITUACAO, -- COLUNA STATUS
    1 AS PARCELA,
    TO_CHAR(CM.DTMOVTO,'DD/MM/YYYY')DTEMISSAO,
    EXTRACT(YEAR FROM CM.DTMOVTO) AS ANO,
    EXTRACT(MONTH FROM CM.DTMOVTO) AS MES,
    TO_CHAR(CM.VENCIMENTO,'DD/MM/YYYY') DTVENCTO,
    ARREDONDAR(CAST(:DTBASE AS DATE) - CM.VENCIMENTO,0) AS ATRASO,
    NULL AS CULTURA,
    CASE
        WHEN CONTAMOVTP.TIPO IN ('ACB','AC','DDVE','AC','ACB','ACC','ACV','DUPP','IMEC','TFDP') THEN (CM.VALOR * -1)
        ELSE CM.VALOR
    END VALOR,
    CM.JUROS,
    CASE
        WHEN CONTAMOVTP.TIPO  in ('ACB','AC','DDVE','AC','ACB','ACC','ACV','DUPP','IMEC','TFDP') THEN (CM.VALOR - COALESCE(BAIXAS_CM.VLR,0))*-1
        ELSE CM.VALOR - COALESCE(BAIXAS_CM.VLR,0) 
    END SALDO,
    NFCAB.REPRESENT,
    OCORRENCIACONTAMOV.IDOCORRENCIA
    FROM CONTAMOVLAN CM
    INNER JOIN FILIAL ON FILIAL.ESTAB = CM.ESTAB
    LEFT JOIN CONTAMOVTP ON
        CONTAMOVTP.TIPO = CM.TIPO
        AND CONTAMOVTP.DEBCRED = CM.DEBCRED
        
    LEFT JOIN BAIXAS_CM ON
        BAIXAS_CM.ESTABACERTADO = CM.ESTAB
        AND BAIXAS_CM.SEQACERTADA = CM.SEQCM
        AND BAIXAS_CM.NUMEROCM = CM.NUMEROCM
    
    LEFT JOIN (
        SELECT 
            OCORRENCIACONTAMOV.ESTAB,OCORRENCIACONTAMOV.SEQCM,OCORRENCIACONTAMOV.NUMEROCM,
            MAX(OCORRENCIACONTAMOV.IDOCORRENCIA)IDOCORRENCIA
        FROM OCORRENCIACONTAMOV
            INNER JOIN OCORRENCIAFINAN ON OCORRENCIAFINAN.IDOCORRENCIA = OCORRENCIACONTAMOV.IDOCORRENCIA
        GROUP BY OCORRENCIACONTAMOV.ESTAB,OCORRENCIACONTAMOV.SEQCM,OCORRENCIACONTAMOV.NUMEROCM
    )OCORRENCIACONTAMOV ON 
        OCORRENCIACONTAMOV.ESTAB = CM.ESTAB
        AND OCORRENCIACONTAMOV.SEQCM = CM.SEQCM
        AND OCORRENCIACONTAMOV.NUMEROCM = CM.NUMEROCM
        
    LEFT JOIN AGRFINCTAMOV ON 
        AGRFINCTAMOV.ESTAB = CM.ESTAB
        AND AGRFINCTAMOV.NUMEROCM = CM.NUMEROCM
        AND AGRFINCTAMOV.SEQCM = CM.SEQCM
                            
    LEFT JOIN NFCABAGRFIN ON 
        NFCABAGRFIN.ESTAB = AGRFINCTAMOV.ESTAB
        AND NFCABAGRFIN.SEQPAGAMENTO = AGRFINCTAMOV.SEQPAGAMENTO
                            
    LEFT JOIN NFCAB ON 
        NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
        AND NFCAB.ESTAB = NFCABAGRFIN.ESTAB
        
    WHERE
    ARREDONDAR(CM.VALOR - COALESCE(BAIXAS_CM.VLR,0),0) > 0
    AND (CM.DEBCRED = 'D' OR (CM.DEBCRED = 'C' AND CM.TIPO IN ('ACB','AC','DDVE','AC','ACB','ACC','ACV','DUPP','IMEC','TFDP')))
    and CM.TIPO not in ('ACT','AV','DDCO','JCSB')
    AND CM.TIPO NOT IN ('ACT','TACT','ACCR')
    AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
    AND CM.DTMOVTO BETWEEN :DTINI AND :DTFIM
    AND CM.VENCIMENTO BETWEEN :DTINIVENC AND :DTFIMVENC
     <#if REPRESENT?has_content>  
        AND NFCAB.REPRESENT IN (:REPRESENT)
      </#if>
      
    <#if NUMEROCM?has_content>  
        AND CM.NUMEROCM IN (:NUMEROCM)
    </#if>
    
    AND FILIAL.EMPRESA IN (
        SELECT DISTINCT
        EMPRESA
        FROM FILIAL
        WHERE (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
        AND FILIAL.EMPRESA IN (
            SELECT DISTINCT
            EMPRESA
            FROM FILIAL
            WHERE (:EMPRESA = 1 AND EMPRESA >= 1)
            OR (:EMPRESA = 2 AND EMPRESA <100)
        )
    )
),
CHEQUE AS (
    SELECT /*+ MATERIALIZE */ 
    PCHEQREC.EMPRESA AS ESTAB,
    FILIAL.REDUZIDO AS FILIAL,
    PCHEQREC.CLIENTE AS NUMEROCM,
    0 AS SEQENDERECO,
    CAST(NROCHEQUE AS VARCHAR(100) )AS DOCUMENTO,
    'CHEQ' AS TIPO_DOC,
    'CHEQUE' as DESC_TIPO,
    NVL(PANALITI.CTACTB,AUX.CTACTB) AS CTACTB,
    PSITUACA.DESCRICAO as STATUS,
    1 PARCELA,
    TO_CHAR(PCHEQREC.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
    EXTRACT(YEAR FROM PCHEQREC.DTEMISSAO) AS ANO,
    EXTRACT(MONTH FROM PCHEQREC.DTEMISSAO) AS MES,
    TO_CHAR(PCHEQREC.DTBOMPARA,'DD/MM/YYYY') AS DTVENCTO,
    ARREDONDAR(CAST(:DTBASE AS DATE) - PCHEQREC.DTBOMPARA ,0) AS ATRASO,
    LIMCRED.DESCRICAO as CULTURA,
    PCHEQREC.VALOR,
    0 as JUROS,
    CASE
        WHEN PCHEQREC.DTLANCA IS NULL THEN PCHEQREC.VALOR
        ELSE
            CASE 
              WHEN PCHEQREC.DTLANCA <= :DTBASE THEN 0
              ELSE PCHEQREC.VALOR
             END
    END AS SALDO,
    PCHEQREC.REPRESENTANTE AS REPRESENT,
    NULL AS IDOCORRENCIA
    FROM PCHEQREC
    INNER JOIN FILIAL ON FILIAL.ESTAB = PCHEQREC.EMPRESA
    LEFT JOIN LIMCRED ON LIMCRED.ID =  PCHEQREC.LIMCRED_ID
    LEFT JOIN PSITUACA ON PSITUACA.SITUACAO = PCHEQREC.SITUACAO
    LEFT JOIN PANALITI ON
    PANALITI.EMPRESA = FILIAL.EMPRESA
    AND PANALITI.ANALITICA = PCHEQREC.ANALITICA
    LEFT JOIN PANALITI AUX ON
    AUX.EMPRESA = 1
    AND AUX.ANALITICA = PCHEQREC.ANALITICA
    WHERE
    PCHEQREC.SEQLANCATRAN IS NULL
    AND PCHEQREC.DTEMISSAO BETWEEN :DTINI AND :DTFIM
    AND PCHEQREC.DTBOMPARA BETWEEN :DTINIVENC AND :DTFIMVENC
    AND PCHEQREC.DTLANCA IS NULL 
    AND PCHEQREC.EMPRESA <> 800
    AND PCHEQREC.SITUACAO  in (12,10)
    <#if REPRESENT?has_content>  
    AND PCHEQREC.REPRESENTANTE IN (:REPRESENT)
    </#if>
      
     <#if NUMEROCM?has_content>  
        AND PCHEQREC.CLIENTE IN (:NUMEROCM)
    </#if>
    
    AND FILIAL.EMPRESA IN (
        SELECT DISTINCT
        EMPRESA
        FROM FILIAL
        WHERE (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
        AND FILIAL.EMPRESA IN (
            SELECT DISTINCT
            EMPRESA
            FROM FILIAL
            WHERE (:EMPRESA = 1 AND EMPRESA >= 1)
            OR (:EMPRESA = 2 AND EMPRESA <100)
        )
    )
),
REAJUSTE_DPL AS (
    SELECT
    ESTAB,
    DUPREC,
    MAX(DTBASEJUROS)DTREAJUSTE,
    MIN(DTVENCREAJ)DTREAJ_ORI
    FROM PDUPRECREAJ
    WHERE EXISTS (
        SELECT 1 FROM DUPLICATAS
        WHERE DUPLICATAS.ESTAB = PDUPRECREAJ.ESTAB
        AND DUPLICATAS.DOCUMENTO = PDUPRECREAJ.DUPREC
    )
    GROUP BY
    ESTAB,
    DUPREC
),
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 'BAIXA' ELSE 'N' END TIPO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN (NAT.TIPODCTO = 'D' OR NFCFG.NOTACONF IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END CANCELADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END CANCELADO_CALC
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    INNER JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA--IN ('CO','CU')
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM IN ('S','E')
    WHERE CONTRATO.ATIVO = 'A'
    <#if NUMEROCM?has_content>  
        AND CONTRATO.NUMEROCM IN (:NUMEROCM)
    </#if>
    AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = CONTRATO.NUMEROCM
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = CONTRATO.NUMEROCM
            )
        )
),
BAIXAS_CTR AS (
    SELECT ESTAB,CONTRATO,SEQITEM,SUM(BAIXADO) AS BAIXADO,SUM(DEVOLIDO) AS DEVOLIDO,SUM(CANCELADO) AS CANCELADO FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT CONTRATOCANC.ESTAB,CONTRATOCANC.CONTRATO,CONTRATOCANC.SEQITEM,SUM(CONTRATOCANC.VALOR) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO,CONTRATOCANC.SEQITEM
),
SALDO_CTR AS (
    SELECT
    CONTRATO.NUMEROCM,
    SUM(ARREDONDAR(CONTRATOITE.VALORTOTAL - NVL(BAIXAS_CTR.BAIXADO,0) - NVL(BAIXAS_CTR.CANCELADO,0) + NVL(BAIXAS_CTR.DEVOLIDO,0) - NVL(CANC.CANC,0), 0)) VLRSALDO
    FROM CONTRATO
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = CONTRATO.ESTAB
    INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATO.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    LEFT JOIN BAIXAS_CTR ON
        BAIXAS_CTR.ESTAB = CONTRATOITE.ESTAB
        AND BAIXAS_CTR.CONTRATO = CONTRATOITE.CONTRATO
        AND BAIXAS_CTR.SEQITEM = CONTRATOITE.SEQITEM
    LEFT JOIN CANC ON 
        CANC.ESTAB = CONTRATOITE.ESTAB 
        AND CANC.CONTRATO = CONTRATOITE.CONTRATO
        AND CANC.SEQITEM = CONTRATOITE.SEQITEM
    WHERE CONTRATO.ATIVO = 'A' AND U_TEMPRESA.GRAOS ='S'
    AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = CONTRATO.NUMEROCM
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = CONTRATO.NUMEROCM
            )
        )
    GROUP BY CONTRATO.NUMEROCM
),
BAIXAS_DUPPAG AS (
    SELECT
    EMPRESA,
    DUPPAG,
    FORNECEDOR,
    SUM(VALOR) AS VLR,
    SUM(PPDUPPAG.VALOR * CASE WHEN PPDUPPAG.TIPOPAG IN ('P','J') THEN 1 ELSE -1 END) AS PAGO
    FROM PPDUPPAG

    WHERE TIPOPAG = 'P'
    AND DTPAGTO <= :DTBASE
    AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = PPDUPPAG.FORNECEDOR
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = PPDUPPAG.FORNECEDOR
            )
        )
 <#if NUMEROCM?has_content>  
        AND PPDUPPAG.FORNECEDOR IN (:NUMEROCM)
   </#if>
   AND 
        (
            EXISTS (
                SELECT
                1
                FROM PPDUPPAD
                 WHERE
                 (PPDUPPAD.EMPRESA = PPDUPPAG.EMPRESA)
                           AND (PPDUPPAD.ESTABFORNECEDOR = PPDUPPAG.ESTABFORNECEDOR)
                           AND (PPDUPPAD.FORNECEDOR = PPDUPPAG.FORNECEDOR)
                           AND (PPDUPPAD.DUPPAG = PPDUPPAG.DUPPAG)
                           AND (PPDUPPAD.SEQPAGTODU = PPDUPPAG.SEQPAGTODU)
                )
             OR
             EXISTS (
                 SELECT
                 1
                 FROM PPADUCM
                 WHERE
                 (PPADUCM.EMPRESA = PPDUPPAG.EMPRESA)
                               AND (PPADUCM.ESTABFORNECEDOR = PPDUPPAG.ESTABFORNECEDOR)
                               AND (PPADUCM.FORNECEDOR = PPDUPPAG.FORNECEDOR)
                               AND (PPADUCM.DUPPAG = PPDUPPAG.DUPPAG)
                               AND (PPADUCM.SEQPAGTODU = PPDUPPAG.SEQPAGTODU)
         
                )
            OR
            EXISTS (
                SELECT
                1 
                FROM PPDUPPADUP
                WHERE (PPDUPPADUP.EMPRESA         = PPDUPPAG.EMPRESA)
                        AND (PPDUPPADUP.ESTABFORNECEDOR = PPDUPPAG.ESTABFORNECEDOR)
                        AND (PPDUPPADUP.FORNECEDOR         = PPDUPPAG.FORNECEDOR)
                        AND (PPDUPPADUP.DUPPAG             = PPDUPPAG.DUPPAG)
                        AND (PPDUPPADUP.SEQPAGTODU         = PPDUPPAG.SEQPAGTODU)
                )
            OR
            EXISTS (
                SELECT
                1
                FROM PPADUCHE
                WHERE (PPADUCHE.EMPRESA = PPDUPPAG.EMPRESA)
                            AND (PPADUCHE.ESTABFORNECEDOR = PPDUPPAG.ESTABFORNECEDOR)
                            AND (PPADUCHE.FORNECEDOR = PPDUPPAG.FORNECEDOR)
                            AND (PPADUCHE.DUPPAG = PPDUPPAG.DUPPAG)
                            AND (PPADUCHE.SEQPAGTODU = PPDUPPAG.SEQPAGTODU)
            
                )
            OR
            EXISTS (
                SELECT
                1
                FROM PPADUCHR
                WHERE (PPADUCHR.EMPRESA = PPDUPPAG.EMPRESA)
                            AND (PPADUCHR.ESTABFORNECEDOR = PPDUPPAG.ESTABFORNECEDOR)
                            AND (PPADUCHR.FORNECEDOR = PPDUPPAG.FORNECEDOR)
                            AND (PPADUCHR.DUPPAG = PPDUPPAG.DUPPAG)
                            AND (PPADUCHR.SEQPAGTODU = PPDUPPAG.SEQPAGTODU)
                )
        )
    
    GROUP BY EMPRESA,DUPPAG,FORNECEDOR
),
SALDO_PAG AS (
    SELECT
    PDUPPAGA.FORNECEDOR,
    SUM(PDUPPAGA.VALOR - NVL(PDUPPAGA.DESCPEND,0) - NVL(BAIXAS_DUPPAG.VLR,0)) SALDO_PAGAR
    FROM PDUPPAGA
    LEFT JOIN BAIXAS_DUPPAG ON
			BAIXAS_DUPPAG.EMPRESA = PDUPPAGA.EMPRESA
			AND BAIXAS_DUPPAG.DUPPAG = PDUPPAGA.DUPPAG
			AND BAIXAS_DUPPAG.FORNECEDOR = PDUPPAGA.FORNECEDOR
    WHERE
    0=0
    AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = PDUPPAGA.FORNECEDOR
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = PDUPPAGA.FORNECEDOR
            )
        )
    <#if NUMEROCM?has_content>  
        AND PDUPPAGA.FORNECEDOR IN (:NUMEROCM)
    </#if>
    GROUP BY PDUPPAGA.FORNECEDOR
),
NOTAS AS (
    SELECT 
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCAB.NOTACONF,
    NFCAB.NUMEROCM,
    CONTAMOV.REACOBFINLEITURA
    FROM NFCAB
    INNER JOIN FILIAL ON
    FILIAL.ESTAB                    = NFCAB.ESTAB

    INNER JOIN CIDADE ON
    CIDADE.CIDADE                   = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF                  = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA              = 'E'
    and nfcfg.notaconf in (
    -- compra futura
    200,201,258,221,234,237,414,334,335,336,337,338)

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO             IN ('A','N')

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM               = NFCAB.NUMEROCM

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM               = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO            = NFCAB.SEQENDERECO
    
    WHERE
    EXISTS (
        SELECT
        1
        FROM NFCABROMA
        INNER JOIN ROMACLASS ON
        ROMACLASS.ESTAB                 = NFCABROMA.ESTAB AND
        ROMACLASS.ROMANEIO              = NFCABROMA.ROMANEIO AND
        ROMACLASS.ENTRADASAIDA          = NFCABROMA.ENTRADASAIDA AND
        ROMACLASS.NUMEROCM              = NFCABROMA.NUMEROCM AND
        ROMACLASS.CLASSIFICACAO         = NFCABROMA.CLASSIFICACAO 
    
        INNER JOIN ROMA ON
        ROMA.ESTAB                      = ROMACLASS.ESTAB AND
        ROMA.ROMANEIO                   = ROMACLASS.ROMANEIO AND
        ROMA.ENTRADASAIDA               = ROMACLASS.ENTRADASAIDA AND
        ROMA.NUMEROCM                   = ROMACLASS.NUMEROCM AND
        ROMA.ESTORNADO <> 'S'
        
        WHERE NFCABROMA.ESTAB = NFCAB.ESTAB AND
        NFCABROMA.SEQNOTA= NFCAB.SEQNOTA
    )
    AND NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
    <#if NUMEROCM?has_content>  
        AND NFCAB.NUMEROCM IN (:NUMEROCM)
   </#if>
   AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = NFCAB.NUMEROCM
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = NFCAB.NUMEROCM
            )
        ) 
),
PARTIRDE AS (
    SELECT
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    N.SEQNOTAITEMORIGEM,
    SUM(CASE
        WHEN NATOPERACAO.TIPODCTO = 'D' AND NFCFG.NOTACONF NOT IN (205,250,251) THEN N.QUANTIDADE
        ELSE 0 
    END) QTD_DEVOL,
    SUM(CASE WHEN NATOPERACAO.TIPODCTO = 'X' THEN N.QUANTIDADE ELSE 0 END) QTD_FIX,
    SUM(CASE
        WHEN NATOPERACAO.TIPODCTO = 'D' AND NFCFG.NOTACONF IN (205,250,251) THEN N.QUANTIDADE
        ELSE 0 
    END) QTD_QUEBRA
    FROM NFITEMAPARTIRDE N
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = N.ESTABORIGEM
        AND NOTAS.SEQNOTA = N.SEQNOTAORIGEM
    INNER JOIN NFCAB NF ON
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NF.NOTACONF
    INNER JOIN NATOPERACAO ON
        NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    WHERE
    NF.STATUS <> 'C'
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM,N.SEQNOTAITEMORIGEM

),
ROMA_ABERTO  AS (
    SELECT 
    *
    FROM OS_ROMA_ABERTO ROMA
    

    WHERE ROMA.DTEMISSAO BETWEEN :DTINI AND :DTFIM
    <#if NUMEROCM?has_content>  
        AND ROMA.NUMEROCM IN (:NUMEROCM)
    </#if>
    AND 
        (
            EXISTS (
                SELECT 1 FROM DUPLICATAS
                WHERE DUPLICATAS.NUMEROCM = ROMA.NUMEROCM
                )
            OR
            EXISTS (
                SELECT 1 FROM CONTA_MOV
                WHERE CONTA_MOV.NUMEROCM = ROMA.NUMEROCM
            )
        ) 
),
SALDO_FINAL AS (
---------- ROMANEIO EM ABERTO
SELECT
'ROMA PENDENTE' AS TIPO,
R.ESTAB,
0 AS SEQNOTA,
0 AS NOTACONF,
R.NUMEROCM,
R.ITEM,
R.ROMANEIO,
ITEMAGROESTAB.COTACAO,
ITEMCOTITE.FIXACAO,
(R.PESOLIQUIDO - NVL(TRANSF.QTD_TRANSF,0)) - 
        CASE
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) > 0 THEN PAGAMENTOS_ROMA.QTDEPAGO
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) = 0 THEN
            DIVIDE(    
                DIVIDE(
                    (NVL(R.PESOTOTAL,0) - NVL(R.TARA,0)) * NVL(UMIDADE_ROMA.VALOR_UMIDADE,0),
                    60),
            ITEMCOTITE.FIXACAO
            )*60
        ELSE 0 END
 AS SALDO
    
FROM ROMA_ABERTO R

LEFT JOIN OS_ROMA_UMIDADE UMIDADE_ROMA ON
    R.ESTAB = UMIDADE_ROMA.ESTAB
    AND R.NUMEROCM = UMIDADE_ROMA.NUMEROCM
    AND R.ROMANEIO = UMIDADE_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = UMIDADE_ROMA.ENTRADASAIDA

LEFT JOIN OS_ROMA_PAGAMENTOS PAGAMENTOS_ROMA ON
    R.ESTAB = PAGAMENTOS_ROMA.ESTAB
    AND R.NUMEROCM = PAGAMENTOS_ROMA.NUMEROCM
    AND R.ROMANEIO = PAGAMENTOS_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = PAGAMENTOS_ROMA.ENTRADASAIDA
    
LEFT JOIN OS_ROMA_TRANSF TRANSF ON
    R.ESTAB = TRANSF.ESTAB
    AND R.NUMEROCM = TRANSF.NUMEROCM
    AND R.ROMANEIO = TRANSF.ROMANEIO
    AND R.ENTRADASAIDA = TRANSF.ENTRADASAIDA

LEFT JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = R.ESTAB AND
    ITEMAGROESTAB.ITEM              = R.ITEM

LEFT JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

LEFT JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    R.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
UNION ALL
--- COMPRA FUTURA E COMPRA DIRETA
SELECT
'FUTURO' AS TIPO,
NOTAS.ESTAB,
NOTAS.SEQNOTA,
NOTAS.NOTACONF,
NOTAS.NUMEROCM,
NFITEM.ITEM,
0 AS ROMANEIO, 
ITEMAGROESTAB.COTACAO,
ITEMCOTITE.FIXACAO,
NFITEM.QUANTIDADE - NVL(PARTIRDE.QTD_DEVOL,0) - NVL(PARTIRDE.QTD_FIX,0) - NVL(PARTIRDE.QTD_QUEBRA,0) AS SALDO
FROM NOTAS

INNER JOIN NFITEM ON
    NFITEM.ESTAB = NOTAS.ESTAB
    AND NFITEM.SEQNOTA = NOTAS.SEQNOTA
    
INNER JOIN ROMA ON
    ROMA.ESTAB = NFITEM.ESTAB
    AND ROMA.ROMANEIO = NFITEM.ROMANEIO

INNER JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = NFITEM.ESTAB AND
    ITEMAGROESTAB.ITEM              = NFITEM.ITEM

INNER JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

INNER JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
LEFT JOIN PARTIRDE ON
    PARTIRDE.ESTABORIGEM = NFITEM.ESTAB
    AND PARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA
    AND PARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
),
COTACOES AS (
    SELECT
    ITEMCOTITE.ESTAB,
    ITEMCOTITE.COTACAO,
    ITEMCOTITE.FIXACAO,
    ITEMCOTITE.DTCOTACAO,
    ITEMCOTITE.DTCOTACAOFIN,
    ROW_NUMBER() OVER (
        PARTITION BY ITEMCOTITE.ESTAB,ITEMCOTITE.COTACAO
        ORDER BY ITEMCOTITE.DTCOTACAOFIN DESC
    ) AS RN
    FROM ITEMCOTITE
    INNER JOIN U_TEMPRESA T ON T.ESTAB = ITEMCOTITE.ESTAB
    
    WHERE
    T.GRAOS = 'S'
),
PRODUTOR AS (
SELECT
S.NUMEROCM,
ARREDONDAR(DIVIDE(SUM(S.SALDO),60),2) AS saldoprod_sc,
ARREDONDAR(DIVIDE(SUM(C.FIXACAO * S.SALDO),60),2) AS saldoprod_vlr
FROM SALDO_FINAL S
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = S.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = S.NUMEROCM
LEFT JOIN COTACOES C ON
    C.ESTAB = S.ESTAB
    AND C.COTACAO = S.COTACAO
    AND C.RN = 1
    having SUM(S.SALDO) > 0
GROUP BY S.NUMEROCM
)
SELECT 
DADOS.ESTAB,
CASE 
    WHEN U_TEMPRESA.GRAOS = 'S' THEN 'Cereais'
	when U_TEMPRESA.INSUMOS = 'S' THEN 'Insumos'
    ELSE 'Outros' 
END TIPO_FILIAL,
DADOS.FILIAL,
DADOS.NUMEROCM,
CASE 
    WHEN CONTAMOV.REVENDA = 'S' THEN 'Revenda'
    WHEN CONTAMOV.PRODUTOR = 'S' THEN 'Produtor'
    WHEN CONCEITO.CONCEITO = 96 THEN 'Fornecedor'
    WHEN NVL(ENDERECO.NOME,CONTAMOV.NOME) LIKE '%USINA%' THEN 'USINA'
    WHEN NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF) > 11 THEN 'PJ' ELSE 'PF'
    END TIPO_CLIENTE,
NVL(ENDERECO.CNPJF,CONTAMOV.CNPJF)CNPJF,
CONTAMOV.NOME AS CLIENTE,
DADOS.TIPO_DOC,
DADOS.DESC_TIPO,
DADOS.DOCUMENTO,
DADOS.STATUS,
DADOS.PARCELA,
DADOS.DTEMISSAO,
DADOS.ANO,
DADOS.MES,
DADOS.DTVENCTO,
DADOS.ATRASO,
CASE
    WHEN DADOS.ATRASO <= -31 THEN '0 - Vencer'
    WHEN DADOS.ATRASO >= -30 AND ATRASO <= 0 THEN '1 - A Vencer até 30'
    WHEN DADOS.ATRASO > 0 AND ATRASO < 31 THEN '2 - 1 a 30 '
    WHEN DADOS.ATRASO > 30 AND ATRASO < 61 THEN '3 - 31 a 60 '
    WHEN DADOS.ATRASO > 60 AND ATRASO < 91 THEN '4 - 61 a 90 '
    WHEN DADOS.ATRASO > 90 AND ATRASO < 121 THEN '5 - 91 a 120 '
    WHEN DADOS.ATRASO > 120 AND ATRASO < 181 THEN '6 - 121 a 180 '
    WHEN DADOS.ATRASO > 180 AND ATRASO < 241 THEN '7 - 181 a 240 '
    WHEN DADOS.ATRASO > 240 AND ATRASO < 366 THEN '8 - 241 a 365 '
    WHEN DADOS.ATRASO > 365 THEN '9 - Acima 365 '
END AGING,
DADOS.VALOR,
DADOS.SALDO,
(SALDO_CTR.VLRSALDO*-1) AS SALDO_CTR,
OCORRENCIAFINAN.OBS as OBS,
OCORRENCIATIPO.DESCRICAO as SITUACAO,
TO_CHAR(OCORRENCIAFINAN.DTPROVAVELPAGAMENTO,'DD/MM/YYYY') AS DTPROVAVELPAGAMENTO,
CONCEITO.DESCRICAO AS CONCEITO_CREDITO,
DADOS.CULTURA,
FILIALRTV.REDUZIDO AS FILIAL_RTV,
RTV.NOME as CONSULTOR,
PRODUTOR.SALDOPROD_SC,
PRODUTOR.SALDOPROD_VLR,
SALDO_PAG.SALDO_PAGAR,
DADOS.CTACTB,
PBLOQDIV.fatura AS FAT_AGRUPA,
NVL(DADOS.JUROS,0) AS JUROS
FROM (
    SELECT * FROM DUPLICATAS
    UNION ALL
    SELECT * FROM CONTA_MOV
    UNION ALL
    SELECT * FROM CHEQUE
)DADOS
--- FILIAL
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = DADOS.ESTAB
--- PESSOA
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = DADOS.NUMEROCM
LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
LEFT JOIN CONCEITO ON CONCEITO.CONCEITO=CONCEITOPESSOA.CONCEITO
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = DADOS.NUMEROCM
    AND ENDERECO.SEQENDERECO = DADOS.SEQENDERECO
--- OCORRENCIAS
LEFT JOIN OCORRENCIAFINAN on OCORRENCIAFINAN.IDOCORRENCIA = DADOS.IDOCORRENCIA
LEFT JOIN OCORRENCIATIPO ON OCORRENCIATIPO.ID = OCORRENCIAFINAN.IDTIPO
--- REPRESENTANTE
LEFT JOIN CONTAMOV RTV ON RTV.NUMEROCM = DADOS.REPRESENT
LEFT JOIN CONTAMOVFUNCIONARIO ON CONTAMOVFUNCIONARIO.NUMEROCM = RTV.NUMEROCM
LEFT JOIN FILIAL FILIALRTV ON FILIALRTV.ESTAB = CONTAMOVFUNCIONARIO.LOCALTRABALHO
--- SALDOS
LEFT JOIN SALDO_CTR ON SALDO_CTR.NUMEROCM = DADOS.NUMEROCM
LEFT JOIN PRODUTOR ON PRODUTOR.NUMEROCM = DADOS.NUMEROCM
LEFT JOIN SALDO_PAG ON SALDO_PAG.FORNECEDOR = DADOS.NUMEROCM
--- DUP
LEFT JOIN PBLOQDIV ON
  	PBLOQDIV.EMPRESA = DADOS.ESTAB
    AND PBLOQDIV.DUPREC = DADOS.DOCUMENTO
LEFT JOIN REAJUSTE_DPL ON 
    REAJUSTE_DPL.ESTAB = DADOS.ESTAB
    AND REAJUSTE_DPL.DUPREC = DADOS.DOCUMENTO
 