WITH DPL AS (
    SELECT EMPRESA, DUPREC, SEQRECBTO, VALOR FROM PRDUPRED
    UNION ALL 
    SELECT EMPRESA, DUPREC, SEQRECBTO, VLRCHEQREC FROM PRDURECH
    UNION ALL 
    SELECT EMPRESA, DUPREC, SEQRECBTO, VALOR FROM PRDUREDUP
    UNION ALL 
    SELECT EMPRESA, DUPREC, SEQRECBTO, VALOR FROM PRDURECAR
    UNION ALL 
    SELECT EMPRESA, DUPREC, SEQRECBTO, VALOR FROM PRDUREOUT
    UNION ALL 
    SELECT EMPRESA, DUPREC, SEQRECBTO, VALOR FROM PRDURECM WHERE TROCO = 'N'
),
BAIXAS_DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,SUM(VALOR) AS VALOR FROM DPL
    GROUP BY EMPRESA,DUPREC,SEQRECBTO

),
BAIXAS AS (
    SELECT
    PRDUPREC.EMPRESA,
    PRDUPREC.DUPREC,
    MAX(PRDUPREC.DTRECBTO) AS DTBAIXA,
    SUM(BAIXAS_DPL.VALOR) AS VLR
    FROM PRDUPREC
    
    INNER JOIN BAIXAS_DPL ON 
        BAIXAS_DPL.EMPRESA = PRDUPREC.EMPRESA
        AND BAIXAS_DPL.DUPREC = PRDUPREC.DUPREC
        and BAIXAS_DPL.SEQRECBTO= PRDUPREC.SEQRECBTO

    WHERE TIPOREC IN ('R')

    GROUP BY PRDUPREC.EMPRESA,PRDUPREC.DUPREC
),
RECEBER AS (
    SELECT
    PDUPREC.DUPREC,
    PDUPREC.CLIENTE,
    PDUPREC.DTVENCTO,
    BAIXAS.DTBAIXA,
    PDUPREC.VALOR,
    ARREDONDAR(PDUPREC.VALOR - NVL(BAIXAS.VLR,0),0) AS SALDO,
    TRUNC(PDUPREC.DTVENCTO - BAIXAS.DTBAIXA) AS DIAS
    FROM PDUPREC
    LEFT JOIN BAIXAS ON
        BAIXAS.EMPRESA = PDUPREC.EMPRESA
        AND BAIXAS.DUPREC = PDUPREC.DUPREC
    WHERE
    PDUPREC.DTEMISSAO BETWEEN :DTINI AND :DTFIM
),
DUPPAG AS (
    SELECT
    PDUPPAGA.FORNECEDOR AS CLIENTE,
    SUM(PDUPPAGA.VALOR) AS VALOR
    FROM PDUPPAGA
    WHERE PDUPPAGA.DTEMISSAO BETWEEN :DTINI AND :DTFIM
    GROUP BY PDUPPAGA.FORNECEDOR
),
BASE AS (
    SELECT
    CLIENTE,
    SUM(VLR_FATURADO) AS VLR_FATURADO,
    SUM(MEDIA_ATRASO) AS MEDIA_ATRASO_DIAS,
    SUM(VALOR_COMPRA) AS VALOR_COMPRA
    FROM(
    SELECT
    CLIENTE,
    0 AS VLR_FATURADO,
    TRUNC(ABS(AVG(DIAS))) AS MEDIA_ATRASO,
    0 AS VALOR_COMPRA
    FROM RECEBER
    WHERE SALDO = 0 AND DIAS < 0
    GROUP BY CLIENTE

    UNION ALL

    SELECT
    CLIENTE,
    SUM(VALOR) AS VLR_FATURADO,
    0 AS MEDIA_ATRASO,
    0 AS VLR_COMPRA
    FROM RECEBER
    GROUP BY CLIENTE

    UNION ALL

    SELECT
    DUPPAG.CLIENTE,
    0 AS VLR_FATURADO,
    0 AS MEDIA_ATRASO,
    DUPPAG.VALOR AS VLR_COMPRA
    FROM DUPPAG
    )
    GROUP BY CLIENTE
),
LIMITE AS (
    SELECT NUMEROCM,SUM(VLRLIMITE) AS VLRLIMITE FROM PESSOALIMCRED
    GROUP BY NUMEROCM 
),
LIMITE_ATUAL AS (
    SELECT NUMEROCM,SUM(SALDOATUAL) AS SALDOATUAL
    FROM SALDOLIMITETIPO 
    WHERE SALDOATUAL <> 0.01 AND SALDOATUAL <> 0 AND SALDOATUAL <> 1
    GROUP BY NUMEROCM
)
SELECT
FILIAL.REDUZIDO AS UNIDADE,
BASE.CLIENTE,
CONTAMOV.NOME,
CONCEITO.DESCRICAO AS RATING,
LIMITE.VLRLIMITE AS VLR_LIMITE,
LIMITE_ATUAL.SALDOATUAL AS VLR_LIMITE_DISP,
BASE.VLR_FATURADO,
BASE.MEDIA_ATRASO_DIAS,
BASE.VALOR_COMPRA,
TIPOCLIAGROMETRIKA.DESCRICAO AS TIPO_CLIENTE
FROM BASE
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = BASE.CLIENTE
LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM = CONTAMOV.NUMEROCM
LEFT JOIN CONCEITO ON CONCEITO.CONCEITO = CONCEITOPESSOA.CONCEITO
LEFT JOIN TIPOCLIAGROMETRIKA ON TIPOCLIAGROMETRIKA.IDTIPOCLIAGROMETRIKA = CONTAMOV.IDTIPOCLIAGROMETRIKA
LEFT JOIN FILIAL ON FILIAL.ESTAB = CONTAMOV.ESTABFINRESPONSAVEL
LEFT JOIN LIMITE ON LIMITE.NUMEROCM = CONTAMOV.NUMEROCM
LEFT JOIN LIMITE_ATUAL ON LIMITE_ATUAL.NUMEROCM = CONTAMOV.NUMEROCM