WITH 
REPRESENTANTE AS 
(
  
  SELECT DISTINCT PESSOAREPRE.NUMEROCM
FROM PESSOAREPRE
WHERE 
    ( NVL(:REPRESENT,0) = 0  OR PESSOAREPRE.REPRESENT = :REPRESENT)
    AND (0 IN (:PESSOA) OR PESSOAREPRE.NUMEROCM IN (:PESSOA))
UNION 

SELECT DISTINCT CONTAMOV.NUMEROCM
FROM CONTAMOV
WHERE 
    :REPRESENT IS NULL 
    AND (0 IN (:PESSOA) OR CONTAMOV.NUMEROCM IN (:PESSOA))
  
    /*SELECT DISTINCT
    PESSOAREPRE.NUMEROCM
    FROM PESSOAREPRE
    WHERE 
    ((:REPRESENT) IS NULL OR PESSOAREPRE.REPRESENT = :REPRESENT)*/
),

SALDOCTR AS 
(
SELECT
CONTRATO.NUMEROCM,
LIMCRED.ID AS LIMCRED_ID,
SUM(PSALDO.NVLRSALDO) AS SALDOCTR
FROM CONTRATO
LEFT JOIN REPRESENTANTE ON REPRESENTANTE.NUMEROCM = CONTRATO.NUMEROCM 
INNER JOIN CONTRATOITE ON
    CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
JOIN LIMITEITEMDET ON LIMITEITEMDET.ITEM = CONTRATOITE.ITEM  
JOIN LIMITEITEMCAB ON LIMITEITEMCAB.IDLIMITEITEMCAB = LIMITEITEMDET.IDLIMITEITEMCAB
JOIN LIMCREDLIMITEITEM ON LIMCREDLIMITEITEM.IDLIMITEITEMCAB = LIMITEITEMCAB.IDLIMITEITEMCAB
JOIN LIMCRED ON LIMCREDLIMITEITEM.ID = LIMCRED.ID
INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
 
 
WHERE
(CONTRATO.NUMEROCM IN (REPRESENTANTE.NUMEROCM))
AND (0 IN (:PESSOA) OR CONTRATO.NUMEROCM IN (:PESSOA))
AND CONTRATOCFG.ENTRADASAIDA = 'S'
AND CONTRATO.ATIVO = 'A'
GROUP BY 
LIMCRED.ID,
CONTRATO.NUMEROCM
),

SALDODISP AS 
(
select
CONTAMOV.NUMEROCM,
sum(
    (select PNSALDODUPREC
    from table (PSALDODUPREC (PDUPREC.EMPRESA, PDUPREC.DUPREC, 0, CURRENT_DATE + 10000 ) ) PSALDODUPREC
    )) as SALDO,
    pduprec.LIMCRED_ID AS LIMCRED_ID
from pduprec
LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = pduprec.cliente
LEFT JOIN REPRESENTANTE ON REPRESENTANTE.NUMEROCM = CONTAMOV.NUMEROCM 
WHERE (CONTAMOV.NUMEROCM IN (REPRESENTANTE.NUMEROCM))
AND (0 IN (:PESSOA) OR CONTAMOV.NUMEROCM IN (:PESSOA))
GROUP BY 
    pduprec.LIMCRED_ID,
    CONTAMOV.NUMEROCM
),

LIMITE_CLIENTES AS 
(
SELECT
PESSOALIMCRED.NUMEROCM,
PESSOALIMCRED.LIMCRED_ID,
PESSOALIMCRED.VLRLIMITE,
PESSOALIMCRED.OBSGERAIS,
PESSOALIMCRED.PENDENTE,
DTVIGENCIAFININI,
DTVIGENCIAFINFIM
FROM
PESSOALIMCRED
UNION ALL
SELECT
PPESCLI.CLIENTE AS NUMEROCM,
0 AS LIMCRED_ID,
PPESCLI.VLRLIMCRED AS VLRLIMITE,
'LIMITE GERAL' AS OBSGERAIS,
NULL AS PENDENTE,
NULL DTVIGENCIAFININI,
CURRENT_DATE AS  DTVIGENCIAFINFIM
FROM
PPESCLI
)

SELECT
LIMITE_CLIENTES.NUMEROCM AS NUMEROCM,
CONTAMOV.NOME AS CLIENTE,
LIMITE_CLIENTES.NUMEROCM ||' - '|| CONTAMOV.NOME AS PESSOA,
LIMITE_CLIENTES.LIMCRED_ID || ' - ' || CASE WHEN LIMITE_CLIENTES.LIMCRED_ID = 0 THEN 'LIMITE GERAL' ELSE LIMCRED.DESCRICAO END AS ITEM,
LIMITE_CLIENTES.VLRLIMITE,
SALDOLIMITETIPO.SALDOATUAL AS SALDO,
SUM(COALESCE(SALDODISP.SALDO,0)) AS SALDODDEVEDOR,
LIMITE_CLIENTES.VLRLIMITE - SUM(COALESCE(SALDODISP.SALDO,0)) - SUM(COALESCE(SALDOCTR.SALDOCTR,0)) AS DISPONIVEL,
CONTAMOV.CNPJF AS CNPJ_CPF,
CONCEITO.DESCRICAO AS RATING,
TO_CHAR(DTVIGENCIAFININI,'DD/MM/YYYY') AS DTVIGENCIAINI,
TO_CHAR(DTVIGENCIAFINFIM,'DD/MM/YYYY') AS DTVIGENCIAFIM,
LIMITE_CLIENTES.OBSGERAIS,
LIMITE_CLIENTES.PENDENTE,
FILIAL_RTV.REDUZIDO AS FILIAL_RTV,
  CASE WHEN RTV.NUMEROCM IS NULL THEN 'S/RTV'
    ELSE TO_CHAR(RTV.NUMEROCM) END NUMEROCM_RTV,
  CASE WHEN RTV.NOME IS NULL THEN 'S/RTV'
    ELSE RTV.NOME||' - '||RTV.NUMEROCM END RTV
FROM
LIMITE_CLIENTES
LEFT JOIN LIMCRED ON 
           LIMCRED.ID = LIMITE_CLIENTES.LIMCRED_ID
INNER JOIN CONTAMOV ON 
           CONTAMOV.NUMEROCM = LIMITE_CLIENTES.NUMEROCM
LEFT JOIN
    (
    SELECT DISTINCT
    PESSOAREPRE.NUMEROCM,
    PESSOAREPRE.REPRESENT
    FROM PESSOAREPRE
    )
    PESSOAREPRE ON
    PESSOAREPRE.NUMEROCM = LIMITE_CLIENTES.NUMEROCM
LEFT JOIN CONTAMOV RTV ON 
    RTV.NUMEROCM = PESSOAREPRE.REPRESENT
LEFT JOIN CONTAMOVFUNCIONARIO RTV_REP_LOCAL ON 
    RTV_REP_LOCAL.NUMEROCM = PESSOAREPRE.REPRESENT
LEFT JOIN FILIAL FILIAL_RTV ON
    FILIAL_RTV.ESTAB =  RTV_REP_LOCAL.LOCALTRABALHO 
LEFT JOIN SALDOLIMITETIPO ON
    SALDOLIMITETIPO.NUMEROCM = LIMITE_CLIENTES.NUMEROCM AND
    SALDOLIMITETIPO.TIPOLIMITE = LIMITE_CLIENTES.LIMCRED_ID
LEFT JOIN CONCEITOPESSOA ON
          CONCEITOPESSOA.NUMEROCM = LIMITE_CLIENTES.NUMEROCM 
LEFT JOIN CONCEITO ON
          CONCEITO.CONCEITO = CONCEITOPESSOA.CONCEITO
          
LEFT JOIN SALDODISP ON (CASE WHEN SALDODISP.LIMCRED_ID NOT IN (LIMITE_CLIENTES.LIMCRED_ID) THEN 0 ELSE SALDODISP.LIMCRED_ID END) = LIMITE_CLIENTES.LIMCRED_ID 
                    AND SALDODISP.NUMEROCM = CONTAMOV.NUMEROCM
    
LEFT JOIN SALDOCTR ON (CASE WHEN SALDOCTR.LIMCRED_ID NOT IN (LIMITE_CLIENTES.LIMCRED_ID) THEN 0 ELSE SALDODISP.LIMCRED_ID END) = LIMITE_CLIENTES.LIMCRED_ID 
                   AND SALDOCTR.NUMEROCM = CONTAMOV.NUMEROCM

LEFT JOIN PPESCLI ON PPESCLI.CLIENTE = CONTAMOV.NUMEROCM
WHERE 
(DTVIGENCIAFINFIM >= CURRENT_DATE)
AND CONTAMOV.NUMEROCM > 100
AND (0 IN (:PESSOA) OR CONTAMOV.NUMEROCM IN (:PESSOA))
AND ( NVL(:REPRESENT,0) = 0 OR PESSOAREPRE.REPRESENT = :REPRESENT)

and
exists 
(
select
1
from nfcab
where
nfcab.status <> 'C'
and nfcab.notaconf in (1,4,111)
and
(0 IN (:ESTAB) OR nfcab.estab in (:ESTAB))
AND NFCAB.NUMEROCM = CONTAMOV.NUMEROCM
)


GROUP BY 
LIMITE_CLIENTES.NUMEROCM,
CONTAMOV.NOME,
LIMITE_CLIENTES.NUMEROCM,
CONTAMOV.NOME,
LIMITE_CLIENTES.LIMCRED_ID,
LIMCRED.DESCRICAO,
LIMITE_CLIENTES.VLRLIMITE,
SALDOLIMITETIPO.SALDOATUAL,
CONTAMOV.CNPJF,
CONCEITO.DESCRICAO,
DTVIGENCIAFININI,
DTVIGENCIAFINFIM,
LIMITE_CLIENTES.OBSGERAIS,
LIMITE_CLIENTES.PENDENTE,
FILIAL_RTV.REDUZIDO,
RTV.NUMEROCM,
RTV.NOME,
RTV.NUMEROCM
ORDER BY LIMITE_CLIENTES.NUMEROCM