SELECT ITEMSALDOINI.ESTAB, FILIAL.RAZAOSOC,
       ITEMSALDOINI.LOCAL, LOCALEST.DESCRICAO,
       ITEMSALDOINI.CODIGOSALDO,  ITEMSALDONOME.DESCRICAOSALDO,
       ITEMSALDOINI.SALDOINICIAL AS SALDO,
       ITEMAGRO.UNIDADE, UNIDADE.DECIMAIS,
       CAST(EXTRACT(YEAR FROM ITEMSALDOINI.DTIMPLANTACAO) AS  INTEGER) AS ANO,
       CAST(EXTRACT(MONTH FROM ITEMSALDOINI.DTIMPLANTACAO) AS INTEGER) AS MES
       
FROM ITEMSALDOINI, FILIAL, LOCALEST, ITEMSALDONOME, ITEMAGRO, UNIDADE
--INNER JOIN FILIAL
WHERE (ITEMSALDOINI.ITEM = :ITEM)
   
   AND NOT EXISTS( SELECT ITEMSALDO.ESTAB
                FROM ITEMSALDO
               WHERE (ITEMSALDO.ESTAB       = ITEMSALDOINI.ESTAB)
                 AND (ITEMSALDO.ITEM        = ITEMSALDOINI.ITEM)
                 AND (ITEMSALDO.LOCAL       = ITEMSALDOINI.LOCAL)
                 AND (ITEMSALDO.CODIGOSALDO = ITEMSALDOINI.CODIGOSALDO))
--INNER JOIN FILIAL
  AND (ITEMSALDOINI.ESTAB = FILIAL.ESTAB)
--INNER JOIN LOCALEST  
  AND (ITEMSALDOINI.ESTAB = LOCALEST.ESTAB)
  AND (ITEMSALDOINI.LOCAL = LOCALEST.LOCAL)
--INNER JOIN ITEMSALDONOME
  AND (ITEMSALDOINI.CODIGOSALDO = ITEMSALDONOME.CODIGOSALDO)
--INNER JOIN ITEMAGRO
  AND (ITEMSALDOINI.ITEM = ITEMAGRO.ITEM)
--INNER JOIN UNIDADE
  AND (ITEMAGRO.UNIDADE = UNIDADE.UNIDADE)
  
UNION ALL

SELECT A.ESTAB, FILIAL.RAZAOSOC,
       A.LOCAL, LOCALEST.DESCRICAO,
       A.CODIGOSALDO, ITEMSALDONOME.DESCRICAOSALDO,
       COALESCE(A.SALDOQUANTIDADE,0) AS SALDO,
       ITEMAGRO.UNIDADE,  UNIDADE.DECIMAIS,
       A.ANO,  A.MES
  FROM ITEMSALDO A, FILIAL, LOCALEST, ITEMSALDONOME, ITEMAGRO, UNIDADE
 WHERE (A.ITEM       = :ITEM)
-- INNER JOIN FILIAL   
   AND (FILIAL.ESTAB = A.ESTAB)
-- INNER JOIN ITEMSALDONOME
   AND (A.CODIGOSALDO = ITEMSALDONOME.CODIGOSALDO)
-- INNER JOIN ITEMAGRO
   AND (A.ITEM = ITEMAGRO.ITEM)
-- INNER JOIN UNIDADE
   AND (ITEMAGRO.UNIDADE = UNIDADE.UNIDADE)
-- LEFT JOIN LOCALEST
   AND (A.ESTAB = LOCALEST.ESTAB(+))
   AND (A.LOCAL = LOCALEST.LOCAL(+))
      
   AND (A.ANO          =
  (SELECT MAX(B.ANO)
  FROM ITEMSALDO B
  WHERE (B.ESTAB     = A.ESTAB)
  AND (B.ITEM        = A.ITEM)
  AND (B.LOCAL       = A.LOCAL)
  AND (B.CODIGOSALDO = A.CODIGOSALDO)
  AND (A.MES         =
    (SELECT MAX(C.MES)
    FROM ITEMSALDO C
    WHERE (C.ESTAB     = A.ESTAB)
    AND (C.ITEM        = A.ITEM)
    AND (C.LOCAL       = A.LOCAL)
    AND (C.CODIGOSALDO = A.CODIGOSALDO)
    AND (C.ANO         = A.ANO)
    ))
  ))
ORDER BY 1, 3, 5