SELECT * FROM (
  SELECT NFITEMCUSTO.CUSTO, NFITEMCUSTO.HORA, NFITEMCUSTO.DATA AS DTEMISSAO,
         NFITEMCUSTO.SEQNOTA, NFITEMCUSTO.SEQNOTAITEM                                                    
    FROM NFITEMCUSTO
   INNER JOIN NFITEM                             
      ON (NFITEMCUSTO.ESTAB = NFITEM.ESTAB)
     AND (NFITEMCUSTO.SEQNOTA = NFITEM.SEQNOTA)
     AND (NFITEMCUSTO.SEQNOTAITEM = NFITEM.SEQNOTAITEM)
   INNER JOIN NFCAB
      ON (NFCAB.ESTAB = NFITEM.ESTAB)
     AND (NFCAB.SEQNOTA = NFITEM.SEQNOTA)
   INNER JOIN NFCFG
      ON (NFCFG.NOTACONF = NFCAB.NOTACONF)
   INNER JOIN NATOPERACAO
      ON (NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO)
     AND (NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA)
   WHERE (NFITEMCUSTO.ESTAB IN (SELECT ESTAB FROM FILIAL WHERE ESTAB = :ESTAB OR :ESTAB = 0))
     AND (NFITEMCUSTO.ITEM = :ITEM)
     AND (NFITEMCUSTO.CODIGOCUSTO = :CODIGOCUSTO)
     AND ((NFITEMCUSTO.SEQNOTA <> :SEQNOTA) OR ((NFITEMCUSTO.SEQNOTA = :SEQNOTA) AND (NFITEMCUSTO.SEQNOTAITEM < :SEQNOTAITEM)))                                                                                 
     AND ((NFITEMCUSTO.DATA < :DATA) OR ((NFITEMCUSTO.DATA = :DATA) AND (COALESCE(NFITEMCUSTO.HORA_CUSTO, NFITEMCUSTO.HORA) <= :HORA))) 
     AND ((NFCFG.CALCULARCUSTO = 'S') OR ((NFCFG.CALCULARCUSTO = '?') AND (NATOPERACAO.CALCULARCUSTO = 'S')))
     AND (NFCAB.ME_SITUACAO IS NULL OR NFCAB.ME_SITUACAO IN (50,53,55,80))
   ORDER BY NFITEMCUSTO.DATA DESC, NFITEMCUSTO.HORA DESC, NFITEMCUSTO.HORA_CUSTO DESC, NFITEMCUSTO.SEQNOTA DESC, NFITEMCUSTO.SEQNOTAITEM DESC
) WHERE ROWNUM = 1