WITH SESSAO AS (
SELECT
v$session.AUDSID,
 REGEXP_SUBSTR(
       module,
       '\[(.*?)\]',
       1,
       1,
       NULL,
       1
        ) AS usuario
FROM v$session 
where module like '%[%'
),
USUARIO AS (
    SELECT
 DISTINCT
    SESSAO.usuario,
    PUSUARIO.GRUPO
,
    AUDSID
    FROM SESSAO
    JOIN PUSUARIO
        ON PUSUARIO.USERID = SESSAO.usuario
   WHERE AUDSID = SYS_CONTEXT('USERENV','SESSIONID')
)
SELECT 
  NFCAB.ESTAB
, NFCAB.SEQNOTA
, NFCAB.SERIE
, NFCAB.NOTA
, NFCAB.NOTACONF
, NFCAB.DTEMISSAO
, NFCAB.DTENTSAI
, NFCAB.EMITENFE
, NFCAB.LOTENFE
, NFCAB.NPROTAUTORIZA
, NFCAB.NPROTCANCELA
, NFCAB.CHAVEACESSONFE
, NFCAB.STATUSNFE
, NFCAB.MOTIVONFE
, NFCAB.LOTETETIS
, NFCAB.NUMEROCM
, NFCAB.SEQENDERECO
, NFCAB.DTENVIONFE
, NFCAB.CODVERIFNFS
, NFCAB.NPROTCANCNFS
, NFCAB.STATUSNFS
, NFCAB.MOTIVONFS
, NFCAB.STATUS_WMS
, NFCAB.AMBIENTE
, NFCAB.NOTACONF
, CONTAMOV.NOME AS NOMEPESSOA
, NFCFGESTAB.SERIE AS SERIECHAVE
, NFCFG.ENTRADASAIDA
, NFCFG.CTRLNROSERIE
, NFCFG.NATUREZADAOPERACAO
, NFCFG.DANFE
, NFCAB.NRORPS
, NFCFG.TRANSFAUTOCFG
, NFCFG.TRANSFAUT
, NOTASPROD
, COALESCE(BOLETOHISTORICONFCAB.BOLETOENVIADO, 0) AS BOLETOENVIADO
, NFCFG.ENVDANFEEMAIL   
, (SELECT STRING_AGG(FORMAPGTO) FROM NFCABAGRFIN WHERE ESTAB = NFCAB.ESTAB AND SEQNOTA = NFCAB.SEQNOTA) AS FORMASPGTO
, FILIAL.REDUZIDO
FROM NFCAB
INNER JOIN CONTAMOV
 ON (CONTAMOV.NUMEROCM = NFCAB.NUMEROCM)
INNER JOIN FILIAL 
ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = NFCAB.ESTAB
INNER JOIN NFCFG
 ON (NFCFG.NOTACONF = NFCAB.NOTACONF)
LEFT JOIN NFCFGESTAB
 ON (NFCFGESTAB.ESTAB = NFCAB.ESTAB)
AND (NFCFGESTAB.NOTACONF = NFCAB.NOTACONF)
AND (NFCFGESTAB.SEQ = NFCAB.SEQ_NFCFGESTAB)              
LEFT JOIN NFCABSERIE
  ON (NFCFGESTAB.ESTAB = NFCABSERIE.ESTAB)
 AND (NFCFGESTAB.SERIE = NFCABSERIE.SERIE)
LEFT JOIN (SELECT ESTAB, SEQNOTA, STRING_AGG(NFPROD) AS NOTASPROD
FROM
  (SELECT ESTAB, SEQNOTA, SERIENFPRODUTOR||'-'||NFPRODUTOR AS NFPROD
    FROM  NFCABPRODUTOR 
    )V                                    
GROUP BY ESTAB, SEQNOTA ) NFCABPRODUTOR
ON (NFCABPRODUTOR.SEQNOTA = NFCAB.SEQNOTA)
AND (NFCABPRODUTOR.ESTAB = NFCAB.ESTAB)
LEFT JOIN (SELECT 1 AS BOLETOENVIADO, ESTAB, SEQNOTA FROM BOLETOHISTORICONFCAB GROUP BY ESTAB, SEQNOTA) BOLETOHISTORICONFCAB
  ON BOLETOHISTORICONFCAB.ESTAB   = NFCAB.ESTAB
 AND BOLETOHISTORICONFCAB.SEQNOTA = NFCAB.SEQNOTA
LEFT JOIN USUARIO ON 0=0
WHERE
(
      (USUARIO.GRUPO in (53,999) AND U_TEMPRESA.GRAOS = 'S')
   OR (NVL(USUARIO.GRUPO,0) not in (53,999) AND NFCAB.ESTAB = :ESTAB)
) 
/*Não retornar notas de autorização de depósito*/
--AND (COALESCE(NFCFGDEP.CONFNFAUT, 0) <> NFCFG.NOTACONF)
AND NOT EXISTS(SELECT NFCFGDEP.CONFNFAUT
               FROM NFCFGDEP
                WHERE (NFCFGDEP.ESTAB = NFCAB.ESTAB)
                 AND (NFCFGDEP.ID = NFCAB.IDNFCFGDEP)
                 AND (NFCFG.NOTACONF = COALESCE(NFCFGDEP.CONFNFAUT, 0)))
%0:s
%1:s