WITH DADOS AS (
 
  SELECT
 
    NFCAB.ESTAB,
 
    NFCFG.NOTACONF,
 
    NFCFG.DESCRICAO AS NOTACONF_DESCRICAO,
 
    NFCAB.SEQNOTA,
 
    NFITEM.SEQNOTAITEM,
 
    NFCAB.SERIE,
 
    NFCAB.NOTA,
 
    NFCAB.DTEMISSAO,
 
    NFITEM.ITEM,
 
    ITEMAGRO.DESCRICAO,
 
    CONTAMOV.CNPJF,
 
    CONTAMOV.NUMEROCM,
 
    CONTAMOV.NOME,
 
    NFITEM.QUANTIDADE,
 
    NFCAB.CHAVEACESSONFE AS CHNFE,
 
    CAST(0 AS NUMBER(12,3)) AS QTDBAIXAR,
 
     COALESCE(DEVOLUCAO.QUANTIDADE, 0) -
 
    COALESCE(EXP_ORIGEM.QUANTIDADE, 0)  AS SALDO,
 
 
    NFITEM.CONTRATO,
 
    NFCAB.SAFRA,
 
    CONTAMOV_ENTREGA.NUMEROCM || ' - ' || CONTAMOV_ENTREGA.NOME AS PESSOA_ENTREGA,
 
    CASE
 
      WHEN (NFCAB.SEQENDENTREGA IS NULL) OR (NFCAB.SEQENDENTREGA <= 0) THEN
 
        CONTAMOV_ENTREGA.ENDERECO
 
      ELSE
 
        ENDERECO_ENTREGA.ENDERECO  
 
    END AS ENDERECO_ENTREGA,
 
  CONTAMOV_RETIRADA.NUMEROCM || ' - ' || CONTAMOV_RETIRADA.NOME AS PESSOA_RETIRADA,
 
  CASE
 
      WHEN (NFCAB.SEQENDRETIRADA IS NULL) OR (NFCAB.SEQENDRETIRADA <= 0) THEN
 
        CONTAMOV_RETIRADA.ENDERECO
 
      ELSE
 
        ENDERECO_RETIRADA.ENDERECO  
 
  END AS ENDERECO_RETIRADA
 
  FROM NFCAB
 
  INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
 
  INNER JOIN NFITEM ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
 
  INNER JOIN ITEMAGRO ON NFITEM.ITEM = ITEMAGRO.ITEM
 
  LEFT JOIN ENDERECO ENDERECO_ENTREGA
 
         ON NFCAB.PESSENTREGA = ENDERECO_ENTREGA.NUMEROCM
 
        AND NFCAB.SEQENDENTREGA = ENDERECO_ENTREGA.SEQENDERECO
 
  INNER JOIN CONTAMOV ON NFCAB.NUMEROCM = CONTAMOV.NUMEROCM
 
  LEFT JOIN CONTAMOV CONTAMOV_ENTREGA ON NFCAB.PESSENTREGA = CONTAMOV_ENTREGA.NUMEROCM
 
  LEFT JOIN CONTAMOV CONTAMOV_RETIRADA
 
ON (NFCAB.PESSRETIRADA = CONTAMOV_RETIRADA.NUMEROCM)
 
LEFT JOIN ENDERECO ENDERECO_RETIRADA
 
  ON (NFCAB.PESSRETIRADA = ENDERECO_RETIRADA.NUMEROCM)
 
AND (NFCAB.SEQENDRETIRADA = ENDERECO_RETIRADA.SEQENDERECO)
 
  LEFT JOIN (
 
    SELECT
 
      NFEXPORIGEM.ESTABORI AS ESTAB,
 
      NFEXPORIGEM.SEQNOTAORI AS SEQNOTA,
 
      NFEXPORIGEM.SEQNOTAITEMORI AS SEQNOTAITEM,
 
      ROUND(SUM(COALESCE(NFEXPORIGEM.QUANTIDADE, 0)), COALESCE(T7.CASASDECQTD, 2)) AS QUANTIDADE  
 
    FROM NFEXPORIGEM
 
    INNER JOIN NFCAB T6 ON T6.ESTAB = NFEXPORIGEM.ESTABORI AND T6.SEQNOTA = NFEXPORIGEM.SEQNOTAORI
 
    INNER JOIN NFCFG T7 ON T7.NOTACONF = T6.NOTACONF
 
    WHERE NOT EXISTS (
 
      SELECT 1
 
      FROM NFITEM T1
 
      INNER JOIN NFITEMAPARTIRDE T2 ON T1.ESTAB = T2.ESTABORIGEM AND T1.SEQNOTA = T2.SEQNOTAORIGEM AND T1.SEQNOTAITEM = T2.SEQNOTAITEMORIGEM
 
      INNER JOIN NFCAB T3 ON T3.ESTAB = T2.ESTAB AND T3.SEQNOTA = T2.SEQNOTA
 
      INNER JOIN NFCFG T4 ON T3.NOTACONF = T4.NOTACONF
 
      INNER JOIN NATOPERACAO T5 ON T4.NATUREZADAOPERACAO = T5.NATUREZADAOPERACAO AND T4.ENTRADASAIDA = T5.ENTRADASAIDA                      
 
      WHERE NFEXPORIGEM.ESTAB = T1.ESTAB
 
        AND NFEXPORIGEM.SEQNOTA = T1.SEQNOTA
 
        AND NFEXPORIGEM.ITEM = T1.ITEM
 
        AND T5.NATUREZADAOPERACAO NOT IN ('XL','XK')
 
    )
 
    GROUP BY NFEXPORIGEM.ESTABORI, NFEXPORIGEM.SEQNOTAORI, NFEXPORIGEM.SEQNOTAITEMORI, T7.CASASDECQTD
 
  ) EXP_ORIGEM
 
    ON EXP_ORIGEM.ESTAB = NFITEM.ESTAB AND EXP_ORIGEM.SEQNOTA = NFITEM.SEQNOTA AND EXP_ORIGEM.SEQNOTAITEM = NFITEM.SEQNOTAITEM
 
  LEFT JOIN (
 
    SELECT
 
      T1.ESTABORIGEM AS ESTAB,
 
      T1.SEQNOTAORIGEM AS SEQNOTA,
 
      T1.SEQNOTAITEMORIGEM AS SEQNOTAITEM,  
 
      ROUND(SUM(COALESCE(T1.QUANTIDADE, 0)), COALESCE(T3.CASASDECQTD, 2)) AS QUANTIDADE
 
    FROM NFITEMAPARTIRDE T1
 
    INNER JOIN NFCAB T2 ON T2.ESTAB = T1.ESTAB AND T2.SEQNOTA = T1.SEQNOTA
 
    INNER JOIN NFCFG T3 ON T3.NOTACONF = T2.NOTACONF
 
    INNER JOIN NATOPERACAO T4 ON T4.NATUREZADAOPERACAO = T3.NATUREZADAOPERACAO AND T4.ENTRADASAIDA = T3.ENTRADASAIDA
 
    WHERE T4.NATUREZADAOPERACAO IN ('XL','XK')
 
    GROUP BY T1.ESTABORIGEM, T1.SEQNOTAORIGEM, T1.SEQNOTAITEMORIGEM, T3.CASASDECQTD
 
  ) DEVOLUCAO
 
    ON DEVOLUCAO.ESTAB = NFITEM.ESTAB AND DEVOLUCAO.SEQNOTA = NFITEM.SEQNOTA AND DEVOLUCAO.SEQNOTAITEM = NFITEM.SEQNOTAITEM  
 
  LEFT JOIN (
 
    SELECT
 
      RE.ESTAB, RE.SEQNOTA, RE.SEQNOTAITEM, SUM(PESORETENCAO) PESORETENCAO
 
    FROM RETENPORTO RE
 
    GROUP BY RE.ESTAB, RE.SEQNOTA, RE.SEQNOTAITEM
 
  ) RETENCAO
 
    ON RETENCAO.ESTAB = NFCAB.ESTAB AND RETENCAO.SEQNOTA = NFCAB.SEQNOTA AND RETENCAO.SEQNOTAITEM = NFITEM.SEQNOTAITEM
 
WHERE %0:s
 
	AND (COALESCE(DEVOLUCAO.QUANTIDADE, 0) - COALESCE(EXP_ORIGEM.QUANTIDADE, 0)  > 0)
 
AND EXISTS (
 
      SELECT 1
 
      FROM NFITEMAPARTIRDE T1
 
      INNER JOIN NFCAB T2 ON T2.ESTAB = T1.ESTAB AND T2.SEQNOTA = T1.SEQNOTA
 
      INNER JOIN NFCFG T3 ON T3.NOTACONF = T2.NOTACONF
 
      INNER JOIN NATOPERACAO T4 ON T4.NATUREZADAOPERACAO = T3.NATUREZADAOPERACAO AND T4.ENTRADASAIDA = T3.ENTRADASAIDA
 
      WHERE T3.NOTACONF IN (395, 389)
 
        AND T1.ESTABORIGEM = NFCAB.ESTAB
 
        AND T1.SEQNOTAORIGEM = NFCAB.SEQNOTA
 
        AND T1.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
 
    )
 
)
 
SELECT
 
  DADOS.ESTAB,
 
  DADOS.NOTACONF,
 
  DADOS.NOTACONF_DESCRICAO,
 
  DADOS.SEQNOTA,
 
  DADOS.SEQNOTAITEM,
 
  DADOS.SERIE,
 
  DADOS.NOTA,
 
  DADOS.DTEMISSAO,
 
  DADOS.ITEM,
 
  DADOS.DESCRICAO,
 
  DADOS.CNPJF,
 
  DADOS.NUMEROCM,
 
  DADOS.NOME,
 
  DADOS.QUANTIDADE,
 
  DADOS.CHNFE,
 
  DADOS.CONTRATO,
 
  DADOS.SAFRA,
 
  DADOS.PESSOA_ENTREGA,
 
  DADOS.ENDERECO_ENTREGA,
 
  DADOS.PESSOA_RETIRADA,
 
  DADOS.ENDERECO_RETIRADA,
 
  DADOS.QTDBAIXAR,
 
  DADOS.SALDO,
 
    case when dados.saldo > 0 then dados.saldo else (
 
    SELECT SUM(X.QUANTIDADE)
 
 
    FROM NFITEMAPARTIRDE X
    
    INNER JOIN NFCAB ON NFCAB.ESTAB=X.ESTAB
             AND NFCAB.SEQNOTA = X.SEQNOTA
 
    WHERE X.ESTABORIGEM = DADOS.ESTAB
 
      AND X.SEQNOTAORIGEM = DADOS.SEQNOTA
 
      AND X.SEQNOTAITEMORIGEM = DADOS.SEQNOTAITEM
      AND NFCAB.NOTACONF NOT IN (383)
      --HUH - AJUTASDO PARA IGNORAR O SALDO DA QUEBRA DA QUANTIDADE DE RETORNO
      
 
  )end AS QTD_RETORNADA  
 
FROM DADOS