create or replace TRIGGER OS_CONTRATOITE_DELETE 
BEFORE DELETE OR UPDATE ON CONTRATOITE FOR EACH ROW 
DECLARE 
nNUMEROCM INTEGER;
USUARIO VARCHAR(50);
EMISSAO DATE;
nTIPO VARCHAR(1);
nCONF INTEGER;
BEGIN 
    IF :NEW.ESTAB IS NOT NULL THEN 
        nTIPO := 'A'; 
        IF ABS(NVL(:NEW.QUANTIDADE, 0) - NVL(:OLD.QUANTIDADE, 0)) > 0.0001 THEN
        --IF :NEW.QUANTIDADE <> :OLD.QUANTIDADE THEN 
            SELECT NUMEROCM, USERID, DTEMISSAO, contconf 
                INTO nNUMEROCM, USUARIO, EMISSAO, nCONF 
            FROM (
                SELECT 
                    CONTRATO.NUMEROCM, COALESCE(LOGCONTRATO.USERID,CONTRATO.USERID) AS USERID, CONTRATO.DTEMISSAO, contrato.contconf 
                FROM CONTRATO 
                LEFT JOIN LOGCONTRATO 
                    ON LOGCONTRATO.ESTAB = CONTRATO.ESTAB 
                    AND LOGCONTRATO.CONTRATO = CONTRATO.CONTRATO 
                WHERE CONTRATO.ESTAB = :OLD.ESTAB
                    AND CONTRATO.CONTRATO = :OLD.CONTRATO 
                ORDER BY LOGCONTRATO.DATA DESC, LOGCONTRATO.HORA DESC
            ) 
            WHERE ROWNUM = 1;
            INSERT INTO U_CONTRNOTA_ALTER 
            (TABELA,SEQUENCIA,ACAO,USERID,"DATA",HORA,COLUNANEW,CONTEUDONEW,COLUNAOLD,CONTEUDOOLD,ESTAB,DOCUMENTO,SEQITEM,DATAALT,NUMEROCM,ITEM, DTEMISSAO, CONF) 
            VALUES ('CONTRATOITE','2',nTIPO,USUARIO,CURRENT_DATE,SYSTIMESTAMP,'QUANTIDADE',:NEW.QUANTIDADE,'QUANTIDADE',
            :old.QUANTIDADE,:old.ESTAB,:old.CONTRATO,:old.SEQITEM,SYSTIMESTAMP,nNUMEROCM,:old.ITEM, EMISSAO, nCONF); 
        END IF;
    ELSE 
        nTIPO := 'E'; 
        SELECT CONTRATO.NUMEROCM, CONTRATO.USERID, CONTRATO.DTEMISSAO, contrato.contconf
                  INTO nNUMEROCM, USUARIO, EMISSAO, nCONF  
                  FROM CONTRATO
                  WHERE CONTRATO.ESTAB = :OLD.ESTAB
                    AND CONTRATO.CONTRATO = :OLD.CONTRATO;
        INSERT INTO U_CONTRNOTA_ALTER 
        (TABELA,SEQUENCIA,ACAO,USERID,"DATA",HORA,COLUNANEW,CONTEUDONEW,COLUNAOLD,CONTEUDOOLD,ESTAB,DOCUMENTO,SEQITEM,DATAALT,NUMEROCM,ITEM, DTEMISSAO, CONF) 
        VALUES ('CONTRATOITE','2',nTIPO,USUARIO,CURRENT_DATE,SYSTIMESTAMP,'QUANTIDADE',:NEW.QUANTIDADE,'QUANTIDADE',
        :old.QUANTIDADE,:old.ESTAB,:old.CONTRATO,:old.SEQITEM,SYSTIMESTAMP,nNUMEROCM,:old.ITEM, EMISSAO, nCONF);
    END IF;    
   EXCEPTION
   WHEN NO_DATA_FOUND THEN
   NULL;
   END;