SELECT
    "ESTAB","REDUZIDO","CNPJ","PEDIDO","CONFIG",
    "DTEMISSAO","VENCIMENTO","USERID","DESCRICAO","TIPO_PROD",
    CASE WHEN
        DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'N' AND 
        DADOS.DESCRICAO LIKE ('ALX%')
        THEN 'E'
         WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('AT%')
        THEN 'E'
         WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('TRANSP%')
        THEN 'E'
        WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('FAT%') THEN 'FAT'
        ELSE
        DADOS.CHAVCHAVENF END ERROCHAVENFE,
    CASE
        WHEN TIPO_PROD = 'S' and PEDIDOCONF = 58 THEN 980
        WHEN TIPO_PROD = 'P' and PEDIDOCONF = 58 THEN 981
        WHEN NOME_PROD LIKE 'AFGR%' THEN 799
        WHEN NOME_PROD LIKE 'FAT - AT%' THEN 825
        WHEN NOME_PROD LIKE 'FAT%' THEN 800
        WHEN DADOS.NOME_PROD LIKE 'UC -%' THEN 27
        WHEN DADOS.NOME_PROD LIKE 'AT -%' THEN 37
        WHEN DADOS.NOME_PROD LIKE 'ALX -%' THEN 44
        WHEN DADOS.NOME_PROD LIKE 'TRANSP -%' OR DADOS.NOME_PROD LIKE 'TRANSP. %' THEN 502
        WHEN regexp_like(SUBSTR(NOME_PROD,0,2), '[0-9]') then 34
    END REGRA_NOTACONF,
    
    CHAVCHAVENF,
        CASE 
        WHEN PEDIDOCONF = 67 THEN 'A'
        WHEN DADOS.CHAVEBOLETO IS NOT NULL THEN 'B'
        WHEN DADOS.PIX IS NOT NULL THEN 'P'
        WHEN DADOS.BANCO IS NOT NULL AND DADOS.AGENCIA IS NOT NULL AND DADOS.CONTA IS NOT NULL THEN 'D'
        ELSE 'E' END AS TIPOPGTO,
        
      CHAVEBOLETO,BANCO,AGENCIA,CONTA,PIX
FROM(

    SELECT
        FILIAL.ESTAB,
        FILIAL.REDUZIDO,
        FILIAL.CNPJ,
        PEDCAB.SERIE||'-'||PEDCAB.NUMERO AS PEDIDO,
        PEDCFG.PEDIDOCONF||'-'||PEDCFG.DESCRICAO AS CONFIG,
        PEDCFG.PEDIDOCONF,
        TO_CHAR(PEDCAB.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
        TO_CHAR(COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO),'DD/MM/YYYY') AS VENCIMENTO,
        PEDCAB.USERID AS USERID,        -- <<<<<< CORRIGIDO AQUI
        PGRUPOS.DESCRICAO,
        CASE WHEN ITEMAGRO.SERVICO = 'S' THEN 'S' ELSE 'P' END TIPO_PROD,
        PEDCAB_U.CHAVCHAVENF,
        PEDCAB_U.CHAVEBOLETO,
        PEDCAB_U.BANCO,
        PEDCAB_U.AGENCIA,
        PEDCAB_U.CONTA,
        PEDCAB_U.PIX,
        ITEMAGRO.DESCRICAO AS NOME_PROD
    
    FROM PEDCAB
    
        INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF
    
        INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB
    
        INNER JOIN NOTIFICAESTRATEGIA N ON
            N.ESTAB = PEDCAB.ESTAB
            AND N.SERIE = PEDCAB.SERIE
            AND N.NUMERO = PEDCAB.NUMERO
    
        LEFT JOIN (
            SELECT ESTAB, SERIE, NUMERO, MAX(PRAZOPAGAMENTO) AS PRAZO
            FROM PEDCABPGTO
            GROUP BY ESTAB, SERIE, NUMERO
        ) MAXPRAZO ON
            MAXPRAZO.ESTAB = PEDCAB.ESTAB
            AND MAXPRAZO.SERIE = PEDCAB.SERIE
            AND MAXPRAZO.NUMERO = PEDCAB.NUMERO
    
        LEFT JOIN (
            SELECT
                NN.ESTAB, NN.SERIE, NN.NUMERO,
                NN.IDGRPAPROVADORES, NN.USERID, NN.IDNOTIFICA AS NOTIFICA,
                NN.PENDENTEAPROV
            FROM NOTIFICAESTRATEGIA NN
            INNER JOIN (
                SELECT ESTAB, SERIE, NUMERO, MAX(IDNOTIFICA) NOTIFICA
                FROM NOTIFICAESTRATEGIA
                GROUP BY ESTAB, SERIE, NUMERO
            ) MAXIMO ON MAXIMO.ESTAB = NN.ESTAB
                  AND MAXIMO.SERIE = NN.SERIE
                  AND MAXIMO.NUMERO = NN.NUMERO
                  AND MAXIMO.NOTIFICA = NN.IDNOTIFICA
        ) NOTIFICAESTRATEGIA ON 
            NOTIFICAESTRATEGIA.ESTAB = PEDCAB.ESTAB
            AND NOTIFICAESTRATEGIA.SERIE = PEDCAB.SERIE
            AND NOTIFICAESTRATEGIA.NUMERO = PEDCAB.NUMERO
        LEFT JOIN NOTIFICAESTRADET ON NOTIFICAESTRADET.IDNOTIFICA = NOTIFICAESTRATEGIA.NOTIFICA
        LEFT JOIN PUSUARIO ON PUSUARIO.USERID = NOTIFICAESTRATEGIA.USERID
        LEFT JOIN PGRUPOS ON PGRUPOS.CODIGO = PUSUARIO.GRUPO
        LEFT JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
            AND PEDITEM.SERIE = PEDCAB.SERIE
            AND PEDITEM.NUMERO = PEDCAB.NUMERO
            AND PEDITEM.SEQPEDITE = 1
        LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
        LEFT JOIN PEDCAB_U ON PEDCAB_U.ESTAB=PEDCAB.ESTAB
                           AND PEDCAB_U.SERIE=PEDCAB.SERIE
                           AND PEDCAB_U.NUMERO=PEDCAB.NUMERO
        LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    WHERE
        NOTIFICAESTRATEGIA.PENDENTEAPROV = 0
        AND PEDCAB.STATUS NOT IN ('B','C')
        AND PEDCAB.PEDIDOCONF IN (54,57,58,72,80,82,85)
        --AND EXTRACT(YEAR FROM PEDCAB.DTEMISSAO) >= EXTRACT(YEAR FROM CURRENT_DATE) - 2

   /* UNION  

    SELECT
        FILIAL.ESTAB,
        FILIAL.REDUZIDO,
        FILIAL.CNPJ,
        PEDCAB.SERIE || '-' || PEDCAB.NUMERO AS PEDIDO,
        PEDCFG.PEDIDOCONF || '-' || PEDCFG.DESCRICAO AS CONFIG,
        PEDCFG.PEDIDOCONF,
        TO_CHAR(PEDCAB.DTEMISSAO, 'DD/MM/YYYY') AS DTEMISSAO,
        TO_CHAR(COALESCE(MAXPRAZO.PRAZO, PEDCAB.DTPRAZOPAGTO), 'DD/MM/YYYY') AS VENCIMENTO,
        PEDCAB.USERID AS USERID,
        PGRUPOS.DESCRICAO AS DESCRICAO,
        CASE WHEN ITEMAGRO.SERVICO = 'S' THEN 'S' ELSE 'P' END TIPO_PROD,
        PEDCAB_U.CHAVCHAVENF,
        PEDCAB_U.CHAVEBOLETO,
        PEDCAB_U.BANCO,
        PEDCAB_U.AGENCIA,
        PEDCAB_U.CONTA,
        PEDCAB_U.PIX,
        ITEMAGRO.DESCRICAO AS NOME_PROD
    
    FROM PEDCAB
    
        INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF
        INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB
        LEFT JOIN (
            SELECT ESTAB, SERIE, NUMERO, MAX(PRAZOPAGAMENTO) AS PRAZO
            FROM PEDCABPGTO
            GROUP BY ESTAB, SERIE, NUMERO
        ) MAXPRAZO ON
            MAXPRAZO.ESTAB = PEDCAB.ESTAB
            AND MAXPRAZO.SERIE = PEDCAB.SERIE
            AND MAXPRAZO.NUMERO = PEDCAB.NUMERO
        LEFT JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
            AND PEDITEM.SERIE = PEDCAB.SERIE
            AND PEDITEM.NUMERO = PEDCAB.NUMERO
            AND PEDITEM.SEQPEDITE = 1
        LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
        LEFT JOIN PUSUARIO ON PUSUARIO.USERID = PEDCAB.USERID
        LEFT JOIN PGRUPOS ON PGRUPOS.CODIGO = PUSUARIO.GRUPO
        LEFT JOIN PEDCAB_U ON PEDCAB_U.ESTAB=PEDCAB.ESTAB
                           AND PEDCAB_U.SERIE=PEDCAB.SERIE
                           AND PEDCAB_U.NUMERO=PEDCAB.NUMERO
        LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO
    WHERE
        PEDCAB.PEDIDOCONF IN (67)
        AND PEDCAB.STATUS NOT IN ('B', 'C')
       -- AND EXTRACT(YEAR FROM PEDCAB.DTEMISSAO) >= EXTRACT(YEAR FROM CURRENT_DATE) - 2
       */ 
) DADOS