WITH MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        LOCAL,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO
    WHERE
    codigosaldo in (1,14,30,2,4,6,23,27,11)
    AND (TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) <= CURRENT_DATE
    -- 2,4,6,23,27: fisico
    -- 1: disponivel
    -- 14,30: fixar
    -- 11: VF
  GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO,LOCAL
),
BASE AS (
    SELECT
    ITEMSALDO.CODIGOSALDO,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    ITEMAGROESTAB.ESTAB,
    ITEMSALDO.LOCAL,
    (ITEMSALDO.SALDOQUANTIDADE) as SALDO
    FROM ITEMAGROESTAB
    
    LEFT JOIN ITEMSALDO ON 
        ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM 
        AND ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ITEMSALDO.ITEM 
        AND MD.ESTAB = ITEMSALDO.ESTAB 
        AND MD.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND MD.LOCAL = ITEMSALDO.LOCAL
        AND TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    LEFT JOIN FILIAL ON FILIAL.ESTAB = ITEMAGROESTAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN ITEMAGRO  ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM 
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID=ITEMAGRO_U.U_AGRPRODGR_ID

    WHERE
    ITEMSALDO.CODIGOSALDO in (1,14,30,2,4,6,23,27,11)
    and U_AGRPRODGR.U_AGRPRODGR_ID <=50
    and U_TEMPRESA.GRAOS='S'
    --AND MD.DATA_MAX <= CURRENT_DATE
    AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
    and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) and FILIAL.ESTAB <> 800
    AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))    
),
BASE_VF AS (
    SELECT
    ITEMSALDO.ESTAB,
    ITEMSALDO.LOCAL,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    0 AS saldodisp,
    0 AS SALDOFIS,
    0 AS DEPOSTOPROD,
    0 AS QTDSALDO,
    0 AS QTDSALDOCF,
    0 AS QTDSALDOVD,
    0 AS QTDSALDOVF,
    0 AS SALDOROMA,
    0 AS SALDOFIXAR,
    0 PEDIDO,
    SUM(ARREDONDAR(DIVIDE(ITEMSALDO.SALDOQUANTIDADE*ITEMAGRO.PESOLIQUIDO,60),0)) AS SALDOVF
    FROM ITEMAGROESTAB
    
    LEFT JOIN ITEMSALDO ON 
        ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM 
        AND ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ITEMSALDO.ITEM 
        AND MD.ESTAB = ITEMSALDO.ESTAB 
        AND MD.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND MD.LOCAL = ITEMSALDO.LOCAL
        AND TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    LEFT JOIN FILIAL ON FILIAL.ESTAB = ITEMAGROESTAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN ITEMAGRO  ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM 

    LEFT JOIN ITEMCOMPOS ON ITEMCOMPOS.ESTAB = ITEMAGROESTAB.ESTAB
                AND ITEMCOMPOS.ITEM = ITEMAGROESTAB.ITEM
                
    LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMCOMPOS.ITEMMATERIAPRIMA                
    
    LEFT JOIN ITEMAGRO_U AGRO_U ON AGRO_U.ITEM = ITEMAGRO.ITEM
    
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID= CASE WHEN ITEMAGRO_U.ITEM = 7 THEN 13 ELSE COALESCE(ITEMAGRO_U.U_AGRPRODGR_ID,AGRO_U.U_AGRPRODGR_ID) END   
    
    WHERE
    MD.CODIGOSALDO = 11
    AND U_AGRPRODGR.U_AGRPRODGR_ID <=50
    AND U_TEMPRESA.Graos='S'
    AND ITEMAGRO.ITEM <> 41
    AND MD.DATA_MAX <= CURRENT_DATE
    AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
    and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) and FILIAL.ESTAB <> 800
    AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
    GROUP BY ITEMSALDO.ESTAB,ITEMSALDO.LOCAL,U_AGRPRODGR.U_AGRPRODGR_ID
),
DISPONIVEL AS (
    SELECT
    ESTAB,
    ITEM,
    LOCAL,
    SUM(SALDODISP)SALDODISP,
    0 SALDOFIS,
    0 DEPOSTOPROD,
    0 QTDSALDO,
    0 QTDSALDOCF,
    0 QTDSALDOVD,
    0 QTDSALDOVF,
    0 SALDOROMA,
    0 SALDOFIXAR,
    0 PEDIDO,
    0 SALDOVF

    FROM(
        SELECT 
        ESTAB,
        U_AGRPRODGR_ID AS ITEM,
        LOCAL,
        QUANTIDADE*-1 SALDODISP
        FROM U_AJLOCALEST
        WHERE DATAMOV >= CURRENT_DATE
        UNION ALL
        SELECT
        ESTAB,
        ITEM,
        LOCAL,
        SALDO AS SALDODISP
        FROM BASE
        WHERE
        CODIGOSALDO = 1
    )DADOS
    GROUP BY ESTAB,ITEM,LOCAL
),
FISICO AS (
    SELECT
    ESTAB,
    ITEM,
    LOCAL,
    0 SALDODISP,
    SUM(SALDOFIS)SALDOFIS,
    0 DEPOSTOPROD,
    0 QTDSALDO,
    0 QTDSALDOCF,
    0 QTDSALDOVD,
    0 QTDSALDOVF,
    0 SALDOROMA,
    0 SALDOFIXAR,
    0 PEDIDO,
    0 SALDOVF

    FROM(
        SELECT 
        ESTAB,
        U_AGRPRODGR_ID AS ITEM,
        LOCAL,
        QUANTIDADE*-1 SALDOFIS
        FROM U_AJLOCALEST
        WHERE DATAMOV >= CURRENT_DATE
        UNION ALL
        SELECT
        ESTAB,
        ITEM,
        LOCAL,
        SALDO AS SALDOFIS
        FROM BASE
        WHERE
        CODIGOSALDO NOT IN (1,14,30,11)
    )DADOS
    GROUP BY ESTAB,ITEM,LOCAL
),
FIXAR AS (
    SELECT
    ESTAB,
    ITEM,
    LOCAL,
    0 SALDODISP,
    0 SALDOFIS,
    0 DEPOSTOPROD,
    0 QTDSALDO,
    0 QTDSALDOCF,
    0 QTDSALDOVD,
    0 QTDSALDOVF,
    0 SALDOROMA,
    SUM(SALDO) AS SALDOFIXAR,
    0 PEDIDO,
    0 SALDOVF
    FROM BASE
    WHERE CODIGOSALDO IN (14,30)
    GROUP BY ESTAB,ITEM,LOCAL
)
select
ESTAB,
ESTADO,
DESCESTAB,
ITEM,
DESCITEM,
QTDSALDOCF-QTDSALDOVF AS SALDOFUTURO,
QTDSALDO AS CTR_EM_CAMPO,
SALDODISP AS COMPRADO_EMPRESA,
QTDSALDOVD AS VENDIDO_A_ENTREGAR,
SALDOFIXAR AS VENDIDO_A_FIXAR,
PEDIDO AS SALDO_PED,
(SALDODISP+SALDOFIXAR)-QTDSALDOVD+PEDIDO AS DISPONIVEL_VENDA
FROM(
SELECT 'O'as TIPO,
        DADOS.ESTAB,
        CASE WHEN cidade.uf='SP' AND DADOS.ESTAB = 5 THEN 'SP - VJ'
            WHEN DADOS.ESTAB = 79 THEN 'TR'
            WHEN CIDADE.UF='MG' AND DADOS.ESTAB = 81 THEN 'MG - VJ' 
        ELSE  cidade.uf END AS ESTADO,
        FILIAL.REDUZIDO AS DESCESTAB,
       DADOS.ITEM,
       DADOS.ITEM||'-'||u_agrprodgr.descagrupa as DESCITEM,
       --DADOS.LOCAL,
      -- DADOS.LOCAL||'-'||LOCALEST.DESCRICAO AS DESCLOCAL,
       SUM((DADOS.SALDODISP)/60)SALDODISP,
       SUM((DADOS.SALDOFIS)/60)SALDOFIS,
       SUM((DADOS.DEPOSTOPROD)/60)DEPOSTOPROD,
       SUM((DADOS.QTDSALDO)/60)QTDSALDO,
       SUM((DADOS.QTDSALDOCF)/60)QTDSALDOCF,
       (SUM((DADOS.QTDSALDOVD)/60)+SUM(DADOS.SALDOVF))QTDSALDOVD,
       SUM((DADOS.QTDSALDOVF)/60)QTDSALDOVF,
       SUM((DADOS.SALDOROMA)/60)SALDOROMA,
       SUM((DADOS.SALDOFIXAR)/60)SALDOFIXAR,
       SUM(DADOS.PEDIDO)PEDIDO



FROM (

SELECT DISPONIVEL.* FROM DISPONIVEL

UNION ALL

SELECT FISICO.* FROM  FISICO

UNION ALL

SELECT BI_SALDODEPOSITO.* FROM BI_SALDODEPOSITO
INNER JOIN FILIAL ON FILIAL.ESTAB = BI_SALDODEPOSITO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE  = FILIAL.CIDADE
WHERE
(BI_SALDODEPOSITO.ITEM  IN (:ITEM) OR 0 IN (:ITEM))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND FILIAL.ESTAB <> 800

UNION ALL

SELECT FIXAR.* FROM FIXAR

UNION ALL

SELECT
       CONTRATO.ESTAB,
       u_agrprodgr.u_agrprodgr_id AS ITEM,
       localest.local,
       0 AS SALDODISP,
       0 AS SALDOFIS,
        0 DEPOSTOPROD,
       sum(CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))) AS QTDSALDO,
       0 QTDSALDOCF,
       0 QTDSALDOVD,
       0 QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF


FROM CONTRATO
      LEFT OUTER JOIN FILIAL ON
     (FILIAL.ESTAB = CONTRATO.ESTAB)

     INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

      LEFT OUTER JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

      LEFT OUTER JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

      LEFT OUTER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
      AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

      INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=CONTRATOITE.ITEM

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

      LEFT JOIN localest on localest.estab = contratoite.estab
                        and localest.local = contratoite.local

    LEFT JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)

    inner join cidade on CIDADE.cidade = filial.cidade
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id
where  u_tempresa.graos='S'
--and contrato.contconf in (1,2,6,50) and PSALDO.NQTDSALDO > 0
and u_tipoctr.u_tipoctr_id in (2,7,12) and PSALDO.NQTDSALDO > 0
AND contrato.dtmovsaldo <= last_day(current_date)
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

group by  CONTRATO.ESTAB,
       u_agrprodgr.u_agrprodgr_id,
       localest.local

UNION ALL
-----------------------------------------------------------------
SELECT
       CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id AS ITEM,
       localest.local,
       0 AS SALDODISP,
       0 AS SALDOFIS,
       0 DEPOSTOPROD,
        0 AS QTDSALDO,
      sum(CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))) AS QTDSALDOCF,
       0 QTDSALDOVD,
       0 QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF


FROM CONTRATO
      LEFT OUTER JOIN FILIAL ON
     (FILIAL.ESTAB = CONTRATO.ESTAB)

     INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

      LEFT OUTER JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

      LEFT OUTER JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

      LEFT OUTER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
      AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

         INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=CONTRATOITE.ITEM

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

      LEFT JOIN localest on localest.estab = contratoite.estab
                        and localest.local = contratoite.local

    LEFT JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)

inner join cidade on CIDADE.cidade = filial.cidade
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id
where  u_tempresa.graos='S'
--and contrato.contconf in (1,2,6,50) and PSALDO.NQTDSALDO > 0
and u_tipoctr.u_tipoctr_id in (2,7,12)and PSALDO.NQTDSALDO > 0
and contrato.dtmovsaldo > last_day(current_date)
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

group by  CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id,
       localest.local

UNION ALL

SELECT
       CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id AS ITEM,
       localest.local,
       0 AS SALDODISP,
       0 AS SALDOFIS,
       0 DEPOSTOPROD,
        0 AS QTDSALDO,
      sum(CAST(COALESCE(u_ajlocalest.quantidade,0)
          AS DECIMAL(18,2))) AS QTDSALDOCF,
       0 QTDSALDOVD,
       0 QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF


FROM CONTRATO

     INNER JOIN FILIAL ON
     (FILIAL.ESTAB = CONTRATO.ESTAB)

     INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

      INNER  JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

      INNER  JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

      INNER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
      AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

         INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=CONTRATOITE.ITEM

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

      INNER JOIN localest on localest.estab = contratoite.estab
                        and localest.local = contratoite.local


inner join u_ajlocalest on  u_ajlocalest.estab = contrato.estab
                            and u_ajlocalest.contrato = contrato.contrato

                              and datamov >= last_day(current_date)

inner join cidade on CIDADE.cidade = filial.cidade
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id

where  u_tempresa.graos='S'
--and contrato.contconf in (1,2,6,50)
and u_tipoctr.u_tipoctr_id in (2,7,12)
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
--and contrato.dtmovsaldo > last_day(current_date)

group by  CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id,
       localest.local


--------------------------------------------------------------------
union all

SELECT
       CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id AS ITEM,
       localest.local,
       0 as SALDODISP,
        0 AS SALDOFIS,
       

       0 DEPOSTOPROD,
          0 AS QTDSALDO,
       0 AS  QTDSALDOCF,
	   sum(CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))) QTDSALDOVD,
      -- SUM (case when contratocfg.contconf = 22 then CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))* -1 ELSE CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2)) END) QTDSALDOVD,
       0 QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF




FROM CONTRATO
        INNER JOIN FILIAL ON
     (FILIAL.ESTAB = CONTRATO.ESTAB)

     INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

        INNER JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

      INNER JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

        INNER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
      AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

         INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=CONTRATOITE.ITEM

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

        INNER JOIN localest on localest.estab = contratoite.estab
                        and localest.local = contratoite.local

    INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id
inner join cidade on CIDADE.cidade = filial.cidade
where  u_tempresa.graos='S'
--and contrato.contconf in (20,21,22,24,51,25) and PSALDO.NQTDSALDO > 0
and u_tipoctr.u_tipoctr_id in (1,3,8,9,13) and PSALDO.NQTDSALDO > 0
AND contrato.dtmovsaldo <= last_day(current_date)
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

group by  CONTRATO.ESTAB,
        u_agrprodgr.u_agrprodgr_id,
       localest.local
       
UNION ALL

SELECT
NFCAB.ESTAB,
        u_agrprodgr.u_agrprodgr_id AS ITEM,
       localest.local,
              0 as SALDODISP,
        0 AS SALDOFIS,


       0 DEPOSTOPROD,
       0 AS QTDSALDO,
       0 AS  QTDSALDOCF,
       SUM((NFITEM.QUANTIDADE) - COALESCE(APARTIRDE.BX,0))*-1 AS QTDSALDOVD,
       
	--   0 QTDSALDOVD,
      -- SUM (case when contratocfg.contconf = 22 then CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))* -1 ELSE CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2)) END) QTDSALDOVD,
       0 QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF


FROM NFCAB

INNER JOIN NFITEM ON
    NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    
LEFT JOIN LOCALEST ON
    LOCALEST.ESTAB = NFITEM.ESTAB
    AND LOCALEST.LOCAL = NFITEM.LOCAL
    
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=NFITEM.ITEM
INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id
    
LEFT JOIN (
    SELECT
    ESTABORIGEM,
    SEQNOTAORIGEM,
    SEQNOTAITEMORIGEM,
    SUM(QUANTIDADE) AS BX
    FROM NFITEMAPARTIRDE
    
    GROUP BY ESTABORIGEM,SEQNOTAORIGEM,SEQNOTAITEMORIGEM
)APARTIRDE ON
    APARTIRDE.ESTABORIGEM = NFITEM.ESTAB
    AND APARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA
    AND APARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM


INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

WHERE 
COALESCE(NFCAB.STATUS,'X') <> 'C'
AND NFCAB.NOTACONF IN (388,394)
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

GROUP BY
NFCAB.ESTAB,
u_agrprodgr.u_agrprodgr_id,
APARTIRDE.BX,
 localest.local
 
 having SUM((NFITEM.QUANTIDADE) - COALESCE(APARTIRDE.BX,0)) > 0


union all

select
dados7.estab,
dados7.item,
dados7.local,
0 SALDODISP,
0 saldofis,
0 DEPOSTOPROD,
0 AS QTDSALDO,
0 AS  QTDSALDOCF,
0 QTDSALDOVD,
-- sum(CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))) QTDSALDOVF,
SUM(DADOS7.QTDSALDOVF) AS QTDSALDOVF,
0 SALDOROMA,
0 SALDOFIXAR,
0 PEDIDO,
0 SALDOVF

from (SELECT
       CONTRATO.ESTAB,
       u_agrprodgr.u_agrprodgr_id AS ITEM,
      localest.local,
        0 AS SALDOFIS,
       0 as SALDODISP,

        0 DEPOSTOPROD,
          0 AS QTDSALDO,
       0 AS  QTDSALDOCF,
       0 QTDSALDOVD,
      -- sum(CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))) QTDSALDOVF,
	   case when contratocfg.contconf = 22 then CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2))* 0 ELSE CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2)) END QTDSALDOVF,
       0 SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF


FROM CONTRATO
       INNER JOIN FILIAL ON
     (FILIAL.ESTAB = CONTRATO.ESTAB)

     INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

        INNER JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

        INNER JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

       INNER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
      AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

         INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM=CONTRATOITE.ITEM

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

      INNER JOIN localest on localest.estab = contratoite.estab
                        and localest.local = contratoite.local

    INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
    
    inner join cidade on CIDADE.cidade = filial.cidade
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON u_tipoctr.u_tipoctr_id = contratocfg_u.u_tipoctr_id
where  u_tempresa.graos='S'
--and contrato.contconf in (20,21,22,23,24,51,25) and PSALDO.NQTDSALDO > 0
and u_tipoctr.u_tipoctr_id in (1,3,6,8,9,13) and PSALDO.NQTDSALDO > 0
and contrato.dtmovsaldo > last_day(current_date)
   AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

--group by  CONTRATO.ESTAB,
--        u_agrprodgr.u_agrprodgr_id,
--       localest.local
)dados7
       
GROUP BY 
DADOS7.ITEM,
DADOS7.ESTAB,
DADOS7.LOCAL

UNION ALL

SELECT DADOS2.ESTAB,
       DADOS2.ITEM,
       DADOS2.LOCAL,
       0 SALDODISP,
       0 SALDOFIS,
       0 DEPOSTOPROD,
       0 QTDSALDO,
       0 QTDSALDOCF,
       0 QTDSALDOVD,
       0 QTDSALDOVF,
       SUM(DADOS2.ROMAABERTO)SALDOROMA,
       0 SALDOFIXAR,
       0 PEDIDO,
       0 SALDOVF



FROM (
SELECT

    FILIAL.ESTAB,

     u_agrprodgr.u_agrprodgr_id AS ITEM,
    LOCALEST.LOCAL,

    ITEMAGRO.DESCRICAO AS PRODUTO,

    ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0)))) AS ROMAABERTO


FROM ROMA
    INNER JOIN FILIAL ON
    FILIAL.ESTAB    = ROMA.ESTAB

    INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

    INNER JOIN ROMACFG ON
    ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
    ROMACFG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
    ROMACFG.ENTRADASAIDA    = 'E'

    INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB         = ROMA.ESTAB AND
    ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
    ROMACLASS.PERCENTUAL    > 0

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL THEN ROMA.ITEM ELSE ROMACLASS.ITEM END


      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

    INNER JOIN LOCALEST ON
    LOCALEST.ESTAB      = ROMA.ESTAB AND
    LOCALEST.LOCAL      = ROMA.LOCAL

inner join cidade on cidade.cidade = filial.cidade


    WHERE NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
        WHERE NFCABROMA.ESTAB         = ROMACLASS.ESTAB
          AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
          AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
          AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM)
          --AND NFCABROMA.CLASSIFICACAO = ROMACLASS.CLASSIFICACAO)
          AND ROMA.ESTORNADO            = 'N'
          AND u_tempresa.graos='S'
          AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

GROUP BY
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,
  --  ROMA.ROMANEIO,
    LOCALEST.LOCAL,
     u_agrprodgr.u_agrprodgr_id,
    ITEMAGRO.DESCRICAO

UNION ALL

SELECT

    FILIAL.ESTAB,

     u_agrprodgr.u_agrprodgr_id AS ITEM,
    LOCALEST.LOCAL,

    ITEMAGRO.DESCRICAO AS PRODUTO,

    ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0))))*-1 AS ROMAABERTO

FROM ROMA
    INNER JOIN FILIAL ON
    FILIAL.ESTAB    = ROMA.ESTAB

    INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

    INNER JOIN ROMACFG ON
    ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
    ROMACFG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
    ROMACFG.ENTRADASAIDA    = 'S'

    INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB         = ROMA.ESTAB AND
    ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
    ROMACLASS.PERCENTUAL    > 0

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL THEN ROMA.ITEM ELSE ROMACLASS.ITEM END

      INNER JOIN itemagro_u on itemagro_u.item = itemagro.item

    INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id

    INNER JOIN LOCALEST ON
    LOCALEST.ESTAB      = ROMA.ESTAB AND
    LOCALEST.LOCAL      = ROMA.LOCAL
    
    inner join cidade on cidade.cidade = filial.cidade

    WHERE NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
        WHERE NFCABROMA.ESTAB         = ROMACLASS.ESTAB
          AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
          AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
          AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM)
          --AND NFCABROMA.CLASSIFICACAO = ROMACLASS.CLASSIFICACAO)
          AND ROMA.ESTORNADO            = 'N'
          AND u_tempresa.graos='S'
          AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

GROUP BY
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,
  --  ROMA.ROMANEIO,
    LOCALEST.LOCAL,
     u_agrprodgr.u_agrprodgr_id,
    ITEMAGRO.DESCRICAO )DADOS2

     GROUP BY DADOS2.ESTAB,
       DADOS2.ITEM,
       DADOS2.LOCAL


UNION ALL

SELECT
DADOS4.ESTAB,
DADOS4.ITEM,
DADOS4.LOCAL,
0 SALDODISP,
0 SALDOFIS,
0 DEPOSTOPROD,
0 QTDSALDO,
0 QTDSALDOCF,
0 QTDSALDOVD,
0 QTDSALDOVF,
0 SALDOROMA,
0 SALDOFIXAR,
SUM(DADOS4.SALDOSC) AS PEDIDO,
0 SALDOVF
FROM
(
SELECT
'PEDIDO VENDA' TIPO,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
PEDITEM.NUMERO,
PEDITEM.LOCAL,
--ITEMAGRO.ITEM,
u_agrprodgr.u_agrprodgr_id AS ITEM,
ITEMAGRO.PESOLIQUIDO AS KGLT,
ITEMAGRO.DESCRICAO AS PRODUTO,
PEDITEM.QUANTIDADE*-1 AS QUANTIDADE,
COALESCE(PEDBX.QTD,0) AS QTDBX,
(   (PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0))SALDO,
ARREDONDAR(DIVIDE((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0))*ITEMAGRO.PESOLIQUIDO,60),2)QTDSC,
ARREDONDAR(DIVIDE(COALESCE(PEDBX.QTD,0)*ITEMAGRO.PESOLIQUIDO,60),2)BXSC,
ARREDONDAR(DIVIDE(((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0))*ITEMAGRO.PESOLIQUIDO,60),2)* -1 AS SALDOSC
FROM PEDCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

INNER JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
                AND PEDITEM.SERIE = PEDCAB.SERIE
                AND PEDITEM.NUMERO = PEDCAB.NUMERO

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
--AND ITEMAGRO.ITEM = 8137
LEFT JOIN ITEMCOMPOS ON ITEMCOMPOS.ESTAB = PEDITEM.ESTAB
                AND ITEMCOMPOS.ITEM = PEDITEM.ITEM
                
LEFT JOIN itemagro_u on itemagro_u.item = ITEMCOMPOS.ITEMMATERIAPRIMA

LEFT JOIN itemagro_u AGRO_U ON AGRO_U.ITEM = ITEMAGRO.ITEM

INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id= CASE WHEN PEDITEM.ITEM = 7 THEN 13 ELSE COALESCE(itemagro_u.u_agrprodgr_id,AGRO_U.u_agrprodgr_id) END   


LEFT JOIN 
(
SELECT
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE,
SUM(PEDITEMNFITEM.QUANTIDADE)QTD
FROM PEDITEMNFITEM
INNER JOIN PEDCAB ON PEDITEMNFITEM.ESTAB = PEDCAB.ESTAB
                AND PEDITEMNFITEM.SERIE = PEDCAB.SERIE
                AND PEDITEMNFITEM.NUMERO = PEDCAB.NUMERO
WHERE PEDCAB.PEDIDOCONF IN (250)

GROUP BY
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE

)PEDBX
ON PEDBX.ESTAB = PEDITEM.ESTAB
AND PEDBX.SERIE = PEDITEM.SERIE
AND PEDBX.NUMERO = PEDITEM.NUMERO
AND PEDBX.SEQPEDITE = PEDITEM.SEQPEDITE


LEFT JOIN LOCALEST ON LOCALEST.ESTAB = PEDITEM.ESTAB
                AND LOCALEST.LOCAL = PEDITEM.LOCAL
      
      INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE          

WHERE U_TEMPRESA.GRAOS = 'S'
AND PEDCAB.PEDIDOCONF IN (250)
AND ITEMAGRO.ITEM <> 41
AND ((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0))  - COALESCE(PEDBX.QTD,0)) > 0	
AND COALESCE(PEDCAB.STATUS,'N') <> 'C'
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800
	
UNION ALL

SELECT
'VENDA' TIPO,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
PEDITEM.NUMERO,
PEDITEM.LOCAL,
--ITEMAGRO.ITEM,
u_agrprodgr.u_agrprodgr_id AS ITEM,
ITEMAGRO.PESOLIQUIDO AS KGLT,
ITEMAGRO.DESCRICAO AS PRODUTO,
PEDITEM.QUANTIDADE*-1 AS QUANTIDADE,
COALESCE(PEDBX.QTD,0) AS QTDBX,
(   (PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0))SALDO,
ARREDONDAR(DIVIDE((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0))*ITEMAGRO.PESOLIQUIDO,60),2)QTDSC,
ARREDONDAR(DIVIDE(COALESCE(PEDBX.QTD,0)*ITEMAGRO.PESOLIQUIDO,60),2)BXSC,
ARREDONDAR(DIVIDE(((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0))*ITEMAGRO.PESOLIQUIDO,60),2)*-1 AS SALDOSC
FROM PEDCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

INNER JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
                AND PEDITEM.SERIE = PEDCAB.SERIE
                AND PEDITEM.NUMERO = PEDCAB.NUMERO

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
--AND ITEMAGRO.ITEM = 8137
LEFT JOIN ITEMCOMPOS ON ITEMCOMPOS.ESTAB = PEDITEM.ESTAB
                AND ITEMCOMPOS.ITEM = PEDITEM.ITEM
                
LEFT JOIN itemagro_u on itemagro_u.item = ITEMCOMPOS.ITEMMATERIAPRIMA

LEFT JOIN itemagro_u AGRO_U ON AGRO_U.ITEM = ITEMAGRO.ITEM

INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id= CASE WHEN PEDITEM.ITEM = 7 THEN 13 ELSE COALESCE(itemagro_u.u_agrprodgr_id,AGRO_U.u_agrprodgr_id) END   


LEFT JOIN 
(
SELECT
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE,
SUM(PEDITEMNFITEM.QUANTIDADE)QTD
FROM PEDITEMNFITEM

WHERE PEDITEMNFITEM.SERIE IN ('PV','SV')

GROUP BY
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE

)PEDBX
ON PEDBX.ESTAB = PEDITEM.ESTAB
AND PEDBX.SERIE = PEDITEM.SERIE
AND PEDBX.NUMERO = PEDITEM.NUMERO
AND PEDBX.SEQPEDITE = PEDITEM.SEQPEDITE


LEFT JOIN LOCALEST ON LOCALEST.ESTAB = PEDITEM.ESTAB
                AND LOCALEST.LOCAL = PEDITEM.LOCAL
                
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

WHERE U_TEMPRESA.GRAOS = 'S'
AND PEDCAB.SERIE IN ('PV','SV')
AND PEDCAB.PEDIDOCONF NOT IN (250)
AND ITEMAGRO.ITEM <> 41
AND ((PEDITEM.QUANTIDADE-COALESCE(PEDITEM.CANCELADO,0))  - COALESCE(PEDBX.QTD,0)) > 0
AND COALESCE(PEDCAB.STATUS,'N') <> 'C'
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800

UNION ALL

SELECT
'COMPRA' TIPO,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
PEDITEM.NUMERO,
--U_LOGPEDCTR.CONTRATO,
--PEDITEM.DTEMISSAO,
PEDITEM.LOCAL,
--ITEMAGRO.ITEM AS COD,
--CASE WHEN ITEMAGRO.ITEM > 50 THEN ITEMCOMPOS.ITEMMATERIAPRIMA 
--ELSE ITEMAGRO.ITEM END ITEM,
u_agrprodgr.u_agrprodgr_id AS ITEM,
ITEMAGRO.PESOLIQUIDO AS KGLT,
ITEMAGRO.DESCRICAO AS PRODUTO,
(PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) AS QUANTIDADE,
COALESCE(PEDBX.QTD,0) AS QTDBX,
((PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0))SALDO,
ARREDONDAR(DIVIDE( (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0))*ITEMAGRO.PESOLIQUIDO,60),2)QTDSC,
ARREDONDAR(DIVIDE( COALESCE(PEDBX.QTD,0)*ITEMAGRO.PESOLIQUIDO,60),2)QTDSC_BX,
ARREDONDAR(DIVIDE(  ((PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0)),60),2)SALDOSC
FROM PEDCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

INNER JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
                AND PEDITEM.SERIE = PEDCAB.SERIE
                AND PEDITEM.NUMERO = PEDCAB.NUMERO

LEFT JOIN U_LOGPEDCTR ON U_LOGPEDCTR.ESTAB = PEDCAB.ESTAB
                    AND U_LOGPEDCTR.PEDIDO = PEDCAB.NUMERO
                    AND PEDCAB.SERIE ='SC'
                
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM

LEFT JOIN ITEMCOMPOS ON ITEMCOMPOS.ESTAB = PEDITEM.ESTAB
                AND ITEMCOMPOS.ITEM = PEDITEM.ITEM
                
LEFT JOIN itemagro_u on itemagro_u.item = ITEMCOMPOS.ITEMMATERIAPRIMA

LEFT JOIN itemagro_u AGRO_U ON AGRO_U.ITEM = ITEMAGRO.ITEM

INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id= CASE WHEN PEDITEM.ITEM = 7 THEN 13 ELSE COALESCE(itemagro_u.u_agrprodgr_id,AGRO_U.u_agrprodgr_id) END   
/*INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
INNER JOIN itemagro_u on itemagro_u.item = itemagro.item
INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=itemagro_u.u_agrprodgr_id*/

LEFT JOIN LOCALEST ON LOCALEST.ESTAB = PEDITEM.ESTAB
                AND LOCALEST.LOCAL = PEDITEM.LOCAL
                
LEFT JOIN 
(
SELECT
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE,
SUM(PEDITEMNFITEM.QUANTIDADE)QTD
FROM PEDITEMNFITEM

WHERE PEDITEMNFITEM.SERIE IN ('SC','PC')

GROUP BY
PEDITEMNFITEM.ESTAB,
PEDITEMNFITEM.SERIE,
PEDITEMNFITEM.NUMERO,
PEDITEMNFITEM.SEQPEDITE

)PEDBX

ON PEDBX.ESTAB = PEDITEM.ESTAB
AND PEDBX.SERIE = PEDITEM.SERIE
AND PEDBX.NUMERO = PEDITEM.NUMERO
AND PEDBX.SEQPEDITE = PEDITEM.SEQPEDITE

INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

WHERE U_TEMPRESA.GRAOS = 'S'
AND PEDCAB.SERIE IN ('SC','PC')
--AND U_LOGPEDCTR.CONTRATO IS NULL
AND (PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) > 0
AND ((PEDITEM.QUANTIDADE - COALESCE(PEDITEM.CANCELADO,0)) - COALESCE(PEDBX.QTD,0)) > 0
AND COALESCE(PEDCAB.STATUS,'N') <> 'C'
and (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF)) 
and (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) AND filial.estab <> 800

)DADOS4
GROUP BY 
DADOS4.ESTAB,
DADOS4.ITEM,
DADOS4.LOCAL
  
UNION ALL


SELECT BASE_VF.*  FROM BASE_VF
  
  
  
   )DADOS

inner join FILIAL ON FILIAL.ESTAB=DADOS.ESTAB

inner join cidade on cidade.cidade=filial.cidade

INNER JOIN u_tempresa ON u_tempresa.estab=FILIAL.ESTAB

INNER JOIN u_agrprodgr ON u_agrprodgr.u_agrprodgr_id=dados.item

LEFT JOIN localest on localest.estab = DADOS.estab
                 and localest.local =DADOS.local


WHERE 0=0

       GROUP BY DADOS.ESTAB,
       FILIAL.REDUZIDO,
       DADOS.ITEM,
      descagrupa,
      cidade.uf


HAVING  SUM(DADOS.SALDODISP)<> 0
       OR SUM(DADOS.SALDOFIS)<> 0
       OR SUM(DADOS.DEPOSTOPROD)<> 0
       OR SUM(DADOS.QTDSALDO)<> 0
       OR SUM(DADOS.QTDSALDOCF)<> 0
       OR SUM(DADOS.QTDSALDOVD)<> 0
       OR SUM(DADOS.QTDSALDOVF)<> 0
       OR SUM(DADOS.SALDOROMA)<> 0
       OR SUM(DADOS.SALDOFIXAR) <> 0
        OR SUM(DADOS.PEDIDO) <> 0
        OR SUM(DADOS.SALDOVF) <> 0


ORDER BY 5,3,2

)DADOSX