SELECT
    DADOS.TIP,
    CASE WHEN DADOS.TIPO = 99 THEN 0 ELSE DADOS.TIPO END TIPO, 
    DADOS.ESTAB, 
    FILIAL.REDUZIDO,
    DADOS.CLASSIFICACAO, 
    DADOS.DESCRICAOCLASSIFICACAO, 
    DADOS.ITEM, 
    DADOS.PRODUTO, 
    DADOS.IDCONFIG, 
    DADOS.OPERACAO, 
    DADOS.NUMEROCM, 
    DADOS.PESSOA,
    COALESCE(DADOS.IDENDERECO, 0) AS IDENDERECO, 
    DADOS.ENDERECO, 
    DADOS.DTEMISSAO, 
    DADOS.ROMANEIO, 
    coalesce(moegas.descricao,'Sem Area/Pilha') as AREAPILHA,
    DADOS.OFF, 
    DADOS.SEQDESMEMBRADO, 
    DADOS.PLACA, 
    DADOS.PBRUTO,
    DADOS.PH AS PH, 
    DADOS.FN AS FN, 
    DIVIDE(DADOS.IMP,100) AS IMP, 
    DIVIDE(DADOS.UMID,100) AS UMID, 
    DIVIDE(DADOS.ARD,100) AS ARD,
    DIVIDE(DADOS.QUEB,100) AS QUEB,
    DIVIDE(DADOS.ESVER,100) AS ESVER,
    DIVIDE(DADOS.AVAR,100) AS AVAR,
    DIVIDE(DADOS.QUEI,100) AS QUEI,
    DIVIDE(DADOS.MOF,100) AS MOF,
    DIVIDE(DADOS.OUT,100) AS OUT,
    DIVIDE(DADOS.CARUN,100) AS CARUN,
    DIVIDE(DADOS.DESCONTO,100) AS DESCONTO,
    ARREDONDAR(DIVIDE( (DIVIDE(COALESCE(DADOS.DESCONTO,0),100)*COALESCE(DADOS.PBRUTO,0))   +   COALESCE(ROMADESC.PESOCALCULADO,0), COALESCE(DADOS.PBRUTO,0)),4)AS DESCONT,
    (DADOS.LIQUIDO + DADOS.SECAGEMDESC)LIQUIDO,
    DADOS.FRETE, DADOS.PESOFRETE, DADOS.REACOBFINLEITURA,
    (DADOS.SECAGEMKG+DADOS.SECAGEMDESC) AS SECAGEMKG, 
    DADOS.ARMAZ, 
    DADOS.TOTALSERV, 
    DADOS.NOTA, 
    DADOS.SEQNOTA, 
    DADOS.DTNF,
    DADOS.COMPRAS, 
    DADOS.DEVOLUCAO, 
    DADOS.TRANSFCEDIDA,
    DADOS.FIXACAO, 
    DADOS.SALDO, 
    DADOS.SALDOLIQ, 
    DADOS.NFPRODUTOR, 
    DADOS.AREACAMPO, 
    DADOS.DESCAMPO, 
    DADOS.QTDEPAGO,
    ARREDONDAR(DADOS.SECAGEMNF,2) AS VLRSECAGEM,
    ARREDONDAR(DADOS.SECAGEMNF,2) AS SECAGEMNF,
    ARREDONDAR((DADOS.FRETE) + (CASE WHEN DADOS.SECAGEMKG <> 0 THEN 0 ELSE DADOS.SECAGEMNF END) + DADOS.ARMAZ,2) AS TSERVICO,
    DADOS.QUEBQTD,
    CASE WHEN CONTAMOV.SEXO = 'J' THEN 'S' ELSE 'N' END SEXO,
       CASE WHEN CONTAMOV.INDOPFUNRURAL = 1 THEN 'Funrural - Sobre Comercialização.'
       ELSE 'Funrural - Sobre Folha de Pagto.' END FUN,
       COALESCE(DADOS.PH,1) * DADOS.LIQUIDO AS MEDTRIGO,
       COALESCE(DADOS.FN,1) * DADOS.LIQUIDO AS MEDFN,
       DIVIDE(DADOS.UMID,100)*DADOS.PBRUTO AS DESC_UMID,
      DIVIDE(DADOS.IMP,100)*DADOS.PBRUTO AS DESC_IMP
FROM (
  SELECT 
    * 
  FROM OS_ROMPEND
  WHERE OS_ROMPEND.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
    AND $X{IN,OS_ROMPEND.ESTAB,ESTAB} 
    AND $X{IN,OS_ROMPEND.NUMEROCM,NUMEROCM} 
    AND $X{IN,OS_ROMPEND.ITEM,ITEM}
    AND $X{IN,OS_ROMPEND.TIPO,TIPO}
  
    
  UNION ALL
  
  SELECT 
    * 
  FROM OS_NOTASF
  WHERE OS_NOTASF.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
    AND $X{IN,OS_NOTASF.ESTAB,ESTAB} 
    AND $X{IN,OS_NOTASF.NUMEROCM,NUMEROCM} 
    AND $X{IN,OS_NOTASF.ITEM,ITEM}
    AND $X{IN,OS_NOTASF.TIPO,TIPO}
  
  UNION ALL
  
  SELECT 
    * 
  FROM OS_NOTASCD
  
  WHERE OS_NOTASCD.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
    AND $X{IN,OS_NOTASCD.ESTAB,ESTAB} 
    AND $X{IN,OS_NOTASCD.NUMEROCM,NUMEROCM} 
    AND $X{IN,OS_NOTASCD.ITEM,ITEM}
    AND $X{IN,OS_NOTASCD.TIPO,TIPO}

) DADOS 
INNER JOIN FILIAL 
	ON FILIAL.ESTAB = DADOS.ESTAB 
INNER JOIN CONTAMOV 
	ON CONTAMOV.NUMEROCM = DADOS.NUMEROCM 
	LEFT JOIN ROMADESC ON ROMADESC.ESTAB = DADOS.ESTAB
                    AND ROMADESC.ROMANEIO = DADOS.ROMANEIO
                    AND ROMADESC.NUMEROCM  = DADOS.NUMEROCM
                    AND ROMADESC.ROMADESC = 4
                    
left join roma on roma.estab = dados.estab
			and roma.romaneio = dados.romaneio
			and roma.numerocm = dados.numerocm
		
left join moegas on moegas.moega = roma.moega                  
                    
WHERE 0=0 
AND (DADOS.IDENDERECO = $P{SEQENDERECO} OR -1 = $P{SEQENDERECO})
AND DADOS.ITEM BETWEEN 1 AND 50 AND DADOS.ITEM <> 37
ORDER BY (CASE WHEN DADOS.TIPO = 99 THEN 0 ELSE NVL(DADOS.TIPO,0) END ),DADOS.DTEMISSAO