WITH CTRNOTA AS
    (SELECT
        CONTRATONFITE.ESTAB,
        CONTRATONFITE.CONTRATO,
        CONTRATONFITE.SEQITEM,
        CASE
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
        END BAIXADO,
        CASE
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
        END DEVOLIDO,
        CASE
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
        END CANCELADO
    FROM CONTRATONFITE
        INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
        INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
        INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
        INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
        INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
        INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
        INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
        LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
        LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
        LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
        LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE U_TIPOCTR.TIPOCTR in ('CTR-C') AND CONTRATOITE.ITEM = 2
    AND $X{IN,CONTRATO.NUMEROCM,NUMEROCM} 
    AND $X{IN,CONTRATO.ESTAB,ESTAB} 
    AND CONTRATO.DTMOVSALDO BETWEEN $P{DTINI} AND $P{DTFIM}
    ),

BAIXAS AS
    (SELECT
        ESTAB,
        CONTRATO,
        SEQITEM,
        SUM(BAIXADO) AS BAIXADO,
        SUM(DEVOLIDO) AS DEVOLIDO,
        SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY
        ESTAB,
        CONTRATO,
        SEQITEM
    ),

CANC AS
    (SELECT
        CONTRATOCANC.ESTAB,
        CONTRATOCANC.CONTRATO,
        CONTRATOCANC.SEQITEM,
        SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
        INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
        INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
        INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
        LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
    WHERE U_TIPOCTR.TIPOCTR in ('CTR-C')
    GROUP BY
        CONTRATOCANC.ESTAB,
        CONTRATOCANC.CONTRATO,
        CONTRATOCANC.SEQITEM
    ),

SALDO_MANUAL AS
    (SELECT
        FILIAL.ESTAB,
        CONTAMOV.NUMEROCM,
        CONTRATO.ENDALTERNATIVO AS SEQENDERECO,
        CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
        ITEMAGRO.ITEM,
        sum(ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0)) AS CONTRATO,
        0 AS TIPO,
        0 AS ROMANEIOE,
        0 AS ROMANEIOS,
        0 AS DEPOSITO
    FROM CONTRATO
        INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
        INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
        LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
        INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
        INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
        INNER JOIN CONTAMOV ON
        CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
        INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
        INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
        INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATO.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
        LEFT JOIN BAIXAS ON
        BAIXAS.ESTAB = CONTRATOITE.ESTAB
        AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO
        AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM
        LEFT JOIN CANC ON
        CANC.ESTAB = CONTRATOITE.ESTAB
        AND CANC.CONTRATO = CONTRATOITE.CONTRATO
        AND CANC.SEQITEM = CONTRATOITE.SEQITEM
        INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    WHERE
        CONTRATO.NUMEROCM IS NOT NULL
        AND CONTRATO.DTMOVSALDO BETWEEN $P{DTINI} AND $P{DTFIM}
        AND $X{IN,CONTRATO.NUMEROCM,NUMEROCM} 
        AND $X{IN,CONTRATO.ESTAB,ESTAB} 
        AND CONTRATOITE.ITEM = 2
        AND U_TIPOCTR.TIPOCTR IN ('CTR-C')
        --AND U.GRAOS = 'S'
        AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
    GROUP BY
        FILIAL.ESTAB,
        CONTAMOV.NUMEROCM,
        CONCEITO.CONCEITO,CONCEITO.DESCRICAO,
        ITEMAGRO.ITEM,
        contrato.endalternativo
    ),
SALDOPROD AS (
SELECT *
FROM
    (SELECT
        DADOS.ESTAB,
        DADOS.NUMEROCM,
        NVL(dados.seqendereco,0) AS seqendereco,
        DADOS.ITEM,
        COALESCE(DADOS.TIPO,0) AS TIPO,
        SUM(DADOS.ROMANEIOE) AS ROMANEIOE,
        SUM(DADOS.ROMANEIOS) AS ROMANEIOS,
        SUM(DADOS.DEPOSITO) AS DEPOSITO,
        ((((COALESCE(SUM(DADOS.ROMANEIOE),0) + COALESCE(SUM(DADOS.DEPOSITO),0)))- COALESCE(SUM(DADOS.ROMANEIOS),0))) SALDOPROD,
        SUM(DADOS.CONTRATO) AS CONTRATO,
        (((COALESCE(SUM(DADOS.ROMANEIOE),0) + COALESCE(SUM(DADOS.DEPOSITO),0)) - (SUM(DADOS.CONTRATO)+ COALESCE(SUM(DADOS.ROMANEIOS),0)))) AS SALDOFIS
    FROM
        (
        -------------------------------------
        /*RETORNA ROMANEIO EM ABERTOS*/
        SELECT
            FILIAL.ESTAB,
            CONTAMOV.NUMEROCM,
            ROMA.SEQENDERECO,
            CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
            ITEMAGRO.ITEM,
            0 AS CONTRATO,
            CASE WHEN ROMA.TIPO IS NULL THEN 0 ELSE ROMA.TIPO END TIPO,
            CASE WHEN ROMACFG.entradasaida='E'
                 THEN SUM(COALESCE(ROMA.PESOLIQUIDO,0)) - SUM(COALESCE(RTXPG.QTDEPAGO_TOTAL,0))
                 ELSE 0 END AS ROMANEIOE,
            CASE WHEN ROMACFG.entradasaida='S'
                 THEN SUM(COALESCE(ROMA.PESOLIQUIDO,0)) - SUM(COALESCE(RTXPG.QTDEPAGO_TOTAL,0))
                 ELSE 0 END AS ROMANEIOS,
            0 AS DEPOSITO   
        FROM ROMA
            INNER JOIN FILIAL ON
            FILIAL.ESTAB            = ROMA.ESTAB
            INNER JOIN PEMPRESA ON
            PEMPRESA.EMPRESA        = FILIAL.EMPRESA
            INNER JOIN CIDADE FILCID ON
            FILCID.CIDADE           = FILIAL.CIDADE
            INNER JOIN ROMACFG ON
            ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG
            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM       = ROMA.NUMEROCM
            INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
            INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
            LEFT JOIN ENDERECO ON
            ENDERECO.NUMEROCM       = ROMA.NUMEROCM AND
            ENDERECO.SEQENDERECO    = ROMA.SEQENDERECO
            LEFT JOIN PPESSPRE ON
            PPESSPRE.PRESTADOR      = ROMA.PRESTADOR
            INNER JOIN ROMACLASS ON
            ROMACLASS.ESTAB         = ROMA.ESTAB AND
            ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
            ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
            ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
            ROMACLASS.PERCENTUAL    > 0
            INNER JOIN ROMACLASSNOME ON
            ROMACLASSNOME.CLASSIFICACAO = ROMACLASS.CLASSIFICACAO
            INNER JOIN ITEMAGRO ON
            ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL or (ROMACLASS.ITEM = 0) THEN ROMA.ITEM ELSE ROMACLASS.ITEM END
            LEFT JOIN NFCABROMA ON
            NFCABROMA.ESTAB         = ROMACLASS.ESTAB AND
            NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO AND
            NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA AND
            NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM
            LEFT JOIN NFCAB ON
            NFCAB.ESTAB             = NFCABROMA.ESTAB AND
            NFCAB.SEQNOTA           = NFCABROMA.SEQNOTA
            /* mesma consolidação da v1: 1 LEFT JOIN pré-agregado no lugar
               das 2 subconsultas correlacionadas idênticas */
            LEFT JOIN (
                SELECT
                    ESTAB, ROMANEIO, ENTRADASAIDA, NUMEROCM,
                    SUM(COALESCE(QTDEPAGO,0)) AS QTDEPAGO_TOTAL
                FROM ROMATXSERVICOPG
                GROUP BY ESTAB, ROMANEIO, ENTRADASAIDA, NUMEROCM
            ) RTXPG ON
            RTXPG.ESTAB           = ROMA.ESTAB AND
            RTXPG.ROMANEIO        = ROMA.ROMANEIO AND
            RTXPG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
            RTXPG.NUMEROCM        = ROMA.NUMEROCM
        WHERE
                NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
                            WHERE
                                    NFCABROMA.ESTAB         = ROMACLASS.ESTAB
                                AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
                                AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
                                AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM
                            )
            AND ROMA.ESTORNADO            = 'N'
            AND ROMA.ITEM = 2
            AND roma.dtemissao BETWEEN $P{DTINI} AND $P{DTFIM}
            AND $X{IN,ROMA.NUMEROCM,NUMEROCM} 
            AND $X{IN,ROMA.ESTAB,ESTAB} 
        
        GROUP BY
            FILIAL.ESTAB,
            ROMACFG.entradasaida,
            CONTAMOV.NUMEROCM,
            ITEMAGRO.ITEM,
            CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO,
            ROMA.TIPO,ROMA.SEQENDERECO
        
        UNION ALL
        
        SELECT *
        FROM SALDO_MANUAL
        
        -------------------------------------
        /*RETORNA DADOS DE DEPOSITO*/
        UNION ALL
        
        SELECT
            DADOS.ESTAB,
            DADOS.NUMEROCM,
            dados.seqendereco,
            DADOS.CONCEITO,
            DADOS.ITEM,
            DADOS.CONTRATO,
            COALESCE(DADOS.TIPO,0) AS TIPO,
            DADOS.ROMANEIOE,
            DADOS.ROMANEIOS,
            SUM(DADOS.DEPOSITO) AS DEPOSITO
        FROM
            (
            SELECT
                FILIAL.ESTAB,
                CONTAMOV.NUMEROCM,
                NFCAB.SEQENDERECO,
                CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
                ITEMAGRO.ITEM,
                0 AS CONTRATO,
                NFITEM.FINATIPOROMA AS TIPO,
                0 AS ROMANEIOE,
                0 AS ROMANEIOS,
                NFITEM.QUANTIDADE -
                COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                INNER JOIN NFITEM NFI ON
                NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
                INNER JOIN NFCAB NFDV ON
                NFDV.ESTAB = NFI.ESTAB AND
                NFDV.SEQNOTA = NFI.SEQNOTA
                INNER JOIN NFCFG NFCFGDV ON
                NFCFGDV.NOTACONF = NFDV.NOTACONF /*AND
                NFCFGDV.NOTACONF IN (207,208,221,233,259) */
                INNER JOIN NATOPERACAO NATDV ON
                NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                NATDV.TIPODCTO = 'D'
                WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                ),0) -
                COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                INNER JOIN NFITEM NFI ON
                NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
                INNER JOIN NFCAB NFDV ON
                NFDV.ESTAB = NFI.ESTAB AND
                NFDV.SEQNOTA = NFI.SEQNOTA
                INNER JOIN NFCFG NFCFGDV ON
                NFCFGDV.NOTACONF = NFDV.NOTACONF
                INNER JOIN NATOPERACAO NATDV ON
                NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                NATDV.TIPODCTO = 'X'
                WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                ),0) AS DEPOSITO
            FROM NFCAB
                INNER JOIN FILIAL ON
                FILIAL.ESTAB            = NFCAB.ESTAB
                INNER JOIN CIDADE CIDFIL ON
                CIDFIL.CIDADE           = FILIAL.CIDADE
                INNER JOIN NFCFG ON
                NFCFG.NOTACONF          = NFCAB.NOTACONF AND
                NFCFG.ENTRADASAIDA      = 'E'
                INNER JOIN NATOPERACAO ON
                NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
                NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
                NATOPERACAO.TIPODCTO            = 'A'
                INNER JOIN CONTAMOV ON
                CONTAMOV.NUMEROCM       = NFCAB.NUMEROCM
                INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
                INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
                LEFT JOIN ENDERECO ON
                ENDERECO.NUMEROCM       = NFCAB.NUMEROCM AND
                ENDERECO.SEQENDERECO    = NFCAB.SEQENDERECO
                LEFT JOIN CIDADE ON
                CIDADE.CIDADE           = CASE WHEN NFCAB.SEQENDERECO IS NOT NULL AND NFCAB.SEQENDERECO > 0 THEN ENDERECO.CIDADE ELSE CONTAMOV.CIDADE END
                INNER JOIN NFITEM ON
                NFITEM.ESTAB            = NFCAB.ESTAB AND
                NFITEM.SEQNOTA          = NFCAB.SEQNOTA
                INNER JOIN ITEMAGRO ON
                ITEMAGRO.ITEM           = NFITEM.ITEM
            WHERE
                    NFCAB.DTEMISSAO BETWEEN $P{DTINI} AND $P{DTFIM}
                AND $X{IN,NFCAB.NUMEROCM,NUMEROCM} 
                AND $X{IN,NFCAB.ESTAB,ESTAB}
                AND NFITEM.ITEM = 2
            ) DADOS
        GROUP BY
            DADOS.ESTAB,
            DADOS.NUMEROCM,
            DADOS.CONCEITO,
            DADOS.ITEM,
            DADOS.CONTRATO,
            DADOS.ROMANEIOE,
            DADOS.ROMANEIOS,
            DADOS.TIPO,dados.seqendereco
        HAVING SUM(ARREDONDAR(DADOS.DEPOSITO,0)) > 0
        ) DADOS
    GROUP BY
        DADOS.ESTAB,
        DADOS.NUMEROCM,
        dados.seqendereco,
        DADOS.CONCEITO,
        DADOS.ITEM,
        DADOS.TIPO
    ) DADOS1

WHERE
        (ARREDONDAR(DADOS1.DEPOSITO,0)) <> 0
    OR  (ARREDONDAR(DADOS1.SALDOFIS,0)) <> 0
    OR  (ARREDONDAR(DADOS1.ROMANEIOE,0)) <> 0
    OR  (ARREDONDAR(DADOS1.ROMANEIOS,0)) <> 0
    OR  (ARREDONDAR(DADOS1.CONTRATO,0)) <> 0
    OR  (ARREDONDAR(DADOS1.SALDOPROD,0)) <> 0
)
select
r.estab,
filial.reduzido,
r.placa,
r.romaneio,
r.numerocm,u
contamov.nome,
nvl(r.seqendereco,0) as seqendereco,
nvl(endereco.endereco,contamov.endereco) as endereco,
r.dtemissao,
r.PESOTOTAL - nvl(r.tara,0) as pesobruto,
r.pesoliquido,
r.ph,
r.fn,
r.tipo,
NVL(f.descricao,'S/CLASSIF') as desctipo,
p.saldoprod,
p.saldofis
from roma r
left join FINALIDADETIPO f on f.FINALIDADEID = r.tipo
left join filial on filial.estab = r.estab
left join saldoprod p on
    p.estab = r.estab
    and p.item = r.item
    and p.numerocm = r.numerocm
    and p.tipo = r.tipo
inner join contamov on contamov.numerocm = r.numerocm
left join endereco on
    endereco.numerocm = r.numerocm
    and endereco.seqendereco = r.seqendereco
where r.dtemissao between $P{DTINI} and $P{DTFIM}
AND $X{IN,r.NUMEROCM,NUMEROCM} 
AND $X{IN,r.ESTAB,ESTAB}
and r.romaneioconfig = 2

order by r.estab,r.numerocm,nvl(r.seqendereco,0),nvl(r.tipo,0),r.dtemissao