WITH /*+ MATERIALIZE */ NOTAS AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCAB.NOTACONF,
    NFCAB.NUMEROCM,
    CONTAMOV.REACOBFINLEITURA
    FROM NFCAB
    INNER JOIN FILIAL ON
    FILIAL.ESTAB                    = NFCAB.ESTAB

    INNER JOIN CIDADE ON
    CIDADE.CIDADE                   = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF                  = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA              = 'E'
    and nfcfg.notaconf in (
    -- compra futura
    200,201,258,221,234,237,414,334,335,336,337,338)

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO             IN ('A','N')

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM               = NFCAB.NUMEROCM

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM               = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO            = NFCAB.SEQENDERECO
    
    WHERE
    EXISTS (
        SELECT
        1
        FROM NFCABROMA
        INNER JOIN ROMACLASS ON
        ROMACLASS.ESTAB                 = NFCABROMA.ESTAB AND
        ROMACLASS.ROMANEIO              = NFCABROMA.ROMANEIO AND
        ROMACLASS.ENTRADASAIDA          = NFCABROMA.ENTRADASAIDA AND
        ROMACLASS.NUMEROCM              = NFCABROMA.NUMEROCM AND
        ROMACLASS.CLASSIFICACAO         = NFCABROMA.CLASSIFICACAO 
    
        INNER JOIN ROMA ON
        ROMA.ESTAB                      = ROMACLASS.ESTAB AND
        ROMA.ROMANEIO                   = ROMACLASS.ROMANEIO AND
        ROMA.ENTRADASAIDA               = ROMACLASS.ENTRADASAIDA AND
        ROMA.NUMEROCM                   = ROMACLASS.NUMEROCM AND
        ROMA.ESTORNADO <> 'S'
        
        WHERE NFCABROMA.ESTAB = NFCAB.ESTAB AND
        NFCABROMA.SEQNOTA= NFCAB.SEQNOTA
    )
),
PARTIRDE AS (
    SELECT
    N.ESTABORIGEM,
    N.SEQNOTAORIGEM,
    N.SEQNOTAITEMORIGEM,
    SUM(CASE
        WHEN NATOPERACAO.TIPODCTO = 'D' AND NFCFG.NOTACONF NOT IN (205,250,251) THEN N.QUANTIDADE
        ELSE 0 
    END) QTD_DEVOL,
    SUM(CASE WHEN NATOPERACAO.TIPODCTO = 'X' THEN N.QUANTIDADE ELSE 0 END) QTD_FIX,
    SUM(CASE
        WHEN NATOPERACAO.TIPODCTO = 'D' AND NFCFG.NOTACONF IN (205,250,251) THEN N.QUANTIDADE
        ELSE 0 
    END) QTD_QUEBRA
    FROM NFITEMAPARTIRDE N
    INNER JOIN NOTAS ON
        NOTAS.ESTAB = N.ESTABORIGEM
        AND NOTAS.SEQNOTA = N.SEQNOTAORIGEM
    INNER JOIN NFCAB NF ON
        NF.ESTAB = N.ESTAB
        AND NF.SEQNOTA = N.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NF.NOTACONF
    INNER JOIN NATOPERACAO ON
        NATOPERACAO.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO
        AND NATOPERACAO.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    WHERE
    NF.STATUS <> 'C'
    GROUP BY N.ESTABORIGEM,N.SEQNOTAORIGEM,N.SEQNOTAITEMORIGEM

),
ROMA_ABERTO /*+ MATERIALIZE */  AS (
    SELECT
    ROMA.ESTAB,
    ROMA.ROMANEIO,
    ROMA.ENTRADASAIDA,
    ROMA.NUMEROCM,
    ROMA.ITEM,
    ROMA.DTEMISSAO,
    ROMA.ROMANEIOCONFIG,
    ROMA.PESOLIQUIDO,
    ROMA.PESOTOTAL,
    ROMA.TARA,
    CONTAMOV.REACOBFINLEITURA
    FROM ROMA
    
    INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = ROMA.NUMEROCM
    
    INNER JOIN ROMACFG ON
        ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
        ROMACFG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
        ROMACFG.ENTRADASAIDA    = 'E'
    
    INNER JOIN ROMACLASS ON
        ROMACLASS.ESTAB                 = ROMA.ESTAB AND
        ROMACLASS.ROMANEIO              = ROMA.ROMANEIO AND
        ROMACLASS.ENTRADASAIDA          = ROMA.ENTRADASAIDA AND
        ROMACLASS.NUMEROCM              = ROMA.NUMEROCM AND
        romaclass.percentual            > 0

    WHERE NOT EXISTS (
        SELECT 1 FROM NFCABROMA
        WHERE NFCABROMA.ESTAB = ROMA.ESTAB
        AND NFCABROMA.ROMANEIO = ROMA.ROMANEIO
        AND NFCABROMA.ENTRADASAIDA = ROMA.ENTRADASAIDA
        AND NFCABROMA.NUMEROCM = ROMA.NUMEROCM
    )
    AND ROMA.ESTORNADO <> 'S'
),
UMIDADE_ROMA /*+ MATERIALIZE */ AS (
    SELECT
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM,
        SUM(TABUMISERVITEM.VALOR) AS VALOR_UMIDADE
    FROM ROMATXSERVICO
        INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM
        INNER JOIN CONTAMOV ON
                CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM
                 AND CONTAMOV.REACOBFINLEITURA  = 0
        INNER JOIN ROMADESC ON
                ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
                ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
                ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
                ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
                ROMADESC.ROMADESC                   = 2
        INNER JOIN TABUMISERVCAB ON
                TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV
        INNER JOIN TABUMISERVITEM ON
                TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
                ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN
              
        INNER JOIN ROMA_ABERTO ON
            ROMA_ABERTO.ESTAB = ROMASERV.ESTAB
            AND ROMA_ABERTO.NUMEROCM = ROMASERV.NUMEROCM
            AND ROMA_ABERTO.ROMANEIO = ROMASERV.ROMANEIO
            AND ROMA_ABERTO.ENTRADASAIDA = ROMASERV.ENTRADASAIDA   
            
    WHERE ROMATXSERVICO.SERVICO = 30
      AND ROMATXSERVICO.STATUS <> 'C'
    GROUP BY
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM
),
PAGAMENTOS_ROMA /*+ MATERIALIZE */  AS (
    SELECT
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM,
        SUM(QTDEPAGO) AS QTDEPAGO
    FROM ROMATXSERVICOPG
        INNER JOIN ROMA_ABERTO ON
            ROMA_ABERTO.ESTAB = ROMATXSERVICOPG.ESTAB
            AND ROMA_ABERTO.NUMEROCM = ROMATXSERVICOPG.NUMEROCM
            AND ROMA_ABERTO.ROMANEIO = ROMATXSERVICOPG.ROMANEIO
            AND ROMA_ABERTO.ENTRADASAIDA = ROMATXSERVICOPG.ENTRADASAIDA
    GROUP BY
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM
),
TRANSF /*+ MATERIALIZE */ AS (
    SELECT
    ROMATRANSF.ESTAB,ROMATRANSF.ROMANEIO,ROMATRANSF.ENTRADASAIDA,ROMATRANSF.NUMEROCM,SUM(ROMATRANSF.QUANTIDADE) AS QTD_TRANSF
    FROM ROMATRANSF
    INNER JOIN ROMA_ABERTO ON
            ROMA_ABERTO.ESTAB = ROMATRANSF.ESTAB
            AND ROMA_ABERTO.NUMEROCM = ROMATRANSF.NUMEROCM
            AND ROMA_ABERTO.ROMANEIO = ROMATRANSF.ROMANEIO
            AND ROMA_ABERTO.ENTRADASAIDA = ROMATRANSF.ENTRADASAIDA
    GROUP BY ROMATRANSF.ESTAB,ROMATRANSF.ROMANEIO,ROMATRANSF.ENTRADASAIDA,ROMATRANSF.NUMEROCM
),
SALDO_FINAL AS (
---------- ROMANEIO EM ABERTO
SELECT
'ROMA PENDENTE' AS TIPO,
R.ESTAB,
0 AS SEQNOTA,
0 AS NOTACONF,
R.NUMEROCM,
R.ITEM,
R.ROMANEIO,
ITEMAGROESTAB.COTACAO,
ITEMCOTITE.FIXACAO,
(R.PESOLIQUIDO - NVL(TRANSF.QTD_TRANSF,0)) - 
        CASE
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) > 0 THEN PAGAMENTOS_ROMA.QTDEPAGO
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) = 0 THEN
            DIVIDE(    
                DIVIDE(
                    (NVL(R.PESOTOTAL,0) - NVL(R.TARA,0)) * NVL(UMIDADE_ROMA.VALOR_UMIDADE,0),
                    60),
            ITEMCOTITE.FIXACAO
            )*60
        ELSE 0 END
 AS SALDO
    
FROM ROMA_ABERTO R

LEFT JOIN UMIDADE_ROMA ON
    R.ESTAB = UMIDADE_ROMA.ESTAB
    AND R.NUMEROCM = UMIDADE_ROMA.NUMEROCM
    AND R.ROMANEIO = UMIDADE_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = UMIDADE_ROMA.ENTRADASAIDA

LEFT JOIN PAGAMENTOS_ROMA ON
    R.ESTAB = PAGAMENTOS_ROMA.ESTAB
    AND R.NUMEROCM = PAGAMENTOS_ROMA.NUMEROCM
    AND R.ROMANEIO = PAGAMENTOS_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = PAGAMENTOS_ROMA.ENTRADASAIDA
    
LEFT JOIN TRANSF ON
    R.ESTAB = TRANSF.ESTAB
    AND R.NUMEROCM = TRANSF.NUMEROCM
    AND R.ROMANEIO = TRANSF.ROMANEIO
    AND R.ENTRADASAIDA = TRANSF.ENTRADASAIDA

LEFT JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = R.ESTAB AND
    ITEMAGROESTAB.ITEM              = R.ITEM

LEFT JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

LEFT JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    R.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
UNION ALL
--- COMPRA FUTURA E COMPRA DIRETA
SELECT
'FUTURO' AS TIPO,
NOTAS.ESTAB,
NOTAS.SEQNOTA,
NOTAS.NOTACONF,
NOTAS.NUMEROCM,
NFITEM.ITEM,
0 AS ROMANEIO, 
ITEMAGROESTAB.COTACAO,
ITEMCOTITE.FIXACAO,
NFITEM.QUANTIDADE - NVL(PARTIRDE.QTD_DEVOL,0) - NVL(PARTIRDE.QTD_FIX,0) - NVL(PARTIRDE.QTD_QUEBRA,0) AS SALDO
FROM NOTAS

INNER JOIN NFITEM ON
    NFITEM.ESTAB = NOTAS.ESTAB
    AND NFITEM.SEQNOTA = NOTAS.SEQNOTA
    
INNER JOIN ROMA ON
    ROMA.ESTAB = NFITEM.ESTAB
    AND ROMA.ROMANEIO = NFITEM.ROMANEIO

INNER JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = NFITEM.ESTAB AND
    ITEMAGROESTAB.ITEM              = NFITEM.ITEM

INNER JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

INNER JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
LEFT JOIN PARTIRDE ON
    PARTIRDE.ESTABORIGEM = NFITEM.ESTAB
    AND PARTIRDE.SEQNOTAORIGEM = NFITEM.SEQNOTA
    AND PARTIRDE.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM
),
COTACOES /*+ MATERIALIZE */  AS (
    SELECT
    ITEMCOTITE.ESTAB,
    ITEMCOTITE.COTACAO,
    ITEMCOTITE.FIXACAO,
    ITEMCOTITE.DTCOTACAO,
    ITEMCOTITE.DTCOTACAOFIN,
    ROW_NUMBER() OVER (
        PARTITION BY ITEMCOTITE.ESTAB,ITEMCOTITE.COTACAO
        ORDER BY ITEMCOTITE.DTCOTACAOFIN DESC
    ) AS RN
    FROM ITEMCOTITE
    INNER JOIN U_TEMPRESA T ON T.ESTAB = ITEMCOTITE.ESTAB
    
    WHERE
    T.GRAOS = 'S'
)
SELECT
*
FROM SALDO_FINAL