WITH MAX_DATA AS (
    SELECT /*+ MATERIALIZE */
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        LOCAL,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO
    INNER JOIN FILIAL ON FILIAL.ESTAB = ISALDO.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ISALDO.ESTAB
    WHERE
    ISALDO.codigosaldo in (1)
    AND ISALDO.LOCAL = 1
    AND U_TEMPRESA.GRAOS = 'S'
    --AND ISALDO.ESTAB = 10
    --AND ISALDO.ITEM = 1
    AND (0 IN (:ESTAB) OR ISALDO.ESTAB IN (:ESTAB))
    AND (0 IN (:ITEM) OR ISALDO.ITEM IN (:ITEM))
    AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
    AND (TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) <= CURRENT_DATE
  GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO,LOCAL
),
BASE_SALDO AS (
    SELECT /*+ MATERIALIZE */
    ITEMSALDO.CODIGOSALDO,
    ITEMAGROESTAB.ITEM AS ITEM,
    ITEMAGROESTAB.ESTAB,
    ITEMSALDO.LOCAL,
    (ITEMSALDO.SALDOQUANTIDADE) as SALDO
    FROM ITEMAGROESTAB

    LEFT JOIN ITEMSALDO ON
        ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM
        AND ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB

    INNER JOIN MAX_DATA MD
        ON MD.ITEM = ITEMSALDO.ITEM
        AND MD.ESTAB = ITEMSALDO.ESTAB
        AND MD.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND MD.LOCAL = ITEMSALDO.LOCAL
        AND TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    INNER JOIN ITEMAGRO  ON ITEMAGRO.ITEM = ITEMAGROESTAB.ITEM
    INNER JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID=ITEMAGRO_U.U_AGRPRODGR_ID

    WHERE
    ITEMSALDO.CODIGOSALDO in (1)
    AND ITEMSALDO.LOCAL = 1
    and U_AGRPRODGR.U_AGRPRODGR_ID <=50
    and ITEMSALDO.SALDOQUANTIDADE > 0
),
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE
        WHEN (NAT.TIPODCTO IN ('N','X','A','T') and NFCFG.NOTACONF not IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN (NAT.TIPODCTO = 'D' OR NFCFG.NOTACONF IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATOITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    LEFT JOIN CONTRATO_U ON
        CONTRATO_U.ESTAB = CONTRATO.ESTAB
        AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO
    WHERE CONTRATOITE.LOCAL = 1
    AND (
        (U_TIPOCTR.TIPOCTR IN ('CTR-C') AND CONTRATOCFG.ENTRADASAIDA IN ('E'))
        OR
        (CONTRATO.CONTCONF NOT IN (24, 25, 51, 23, 52) AND CONTRATOCFG.ENTRADASAIDA IN ('S') AND CONTRATO_U.TIPOFRETES = 'FOB')
    )
    AND (0 IN (:ESTAB) OR CONTRATONFITE.ESTAB IN (:ESTAB))
    AND (0 IN (:ESTAB) OR CONTRATOITE.ITEM IN (:ESTAB))
),
BAIXAS AS (
    SELECT /*+ MATERIALIZE */
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT /*+ MATERIALIZE */
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
    WHERE CONTRATOCFG.ENTRADASAIDA IN ('E') AND U_TIPOCTR.TIPOCTR IN ('CTR-C')
    AND (0 IN (:ESTAB) OR CONTRATOCANC.ESTAB IN (:ESTAB))
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
SALDO_MANUAL AS (
SELECT
    CONTRATO.ESTAB,
    FILIAL.REDUZIDO,
    CONTRATO.CONTRATO,
    CONTRATOCFG.ENTRADASAIDA,
    LOCALEST_U.NUMEROCM,
    CONTRATO.DTLIMENTIMP as limitent,
    CONTRATO.DTMOVSALDO,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEMAGR,
    CONTRATOITE.ITEM,
    ITEMAGRO.DESCRICAO,
    CONTRATOITE.QUANTIDADE,
    NVL(BAIXAS.BAIXADO,0) AS BAIXADO,
    NVL(BAIXAS.CANCELADO,0) + NVL(CANC.CANC,0) AS CANCELADO,
    NVL(BAIXAS.DEVOLIDO,0) DEVOLIDO,
    ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) QTDSALDO
FROM CONTRATO
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE
LEFT JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

LEFT JOIN CONTRATO_U ON
    CONTRATO_U.ESTAB = CONTRATO.ESTAB
    AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO

LEFT JOIN CONTRATOITE ON
    CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO

LEFT JOIN LOCALEST ON
    LOCALEST.ESTAB = CONTRATOITE.ESTAB
    AND LOCALEST.LOCAL = CONTRATOITE.LOCAL

LEFT JOIN LOCALEST_U ON
    LOCALEST.ESTAB = LOCALEST_U.ESTAB
    AND LOCALEST.LOCAL = LOCALEST_U.LOCAL

LEFT JOIN BAIXAS ON
    BAIXAS.ESTAB = CONTRATOITE.ESTAB
    AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO
    AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN CANC ON
    CANC.ESTAB = CONTRATOITE.ESTAB
    AND CANC.CONTRATO = CONTRATOITE.CONTRATO
    AND CANC.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID

WHERE
CONTRATOITE.LOCAL = 1
AND (
    (U_TIPOCTR.TIPOCTR IN ('CTR-C') AND CONTRATOCFG.ENTRADASAIDA IN ('E'))
    OR
    (CONTRATO.CONTCONF NOT IN (24, 25, 51, 23, 52) AND CONTRATOCFG.ENTRADASAIDA IN ('S') AND CONTRATO_U.TIPOFRETES = 'FOB')
    )
AND (0 IN (:ESTAB) OR CONTRATO.ESTAB IN (:ESTAB))
AND (0 IN (:ITEM) OR CONTRATOITE.ITEM IN (:ITEM))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
AND CONTRATO.DTMOVSALDO <= LAST_DAY(CURRENT_DATE)
AND U.GRAOS='S'
AND FILIAL.INATIVA = 'N'
AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) >= 0
/* v2: filtro antecipado (equivalente ao INNER JOIN final com BASE_SALDO) */
AND (CONTRATOITE.ESTAB, CONTRATOITE.ITEM) IN (SELECT BS.ESTAB, BS.ITEM FROM BASE_SALDO BS)
),
SALDO_FOB AS (
    select /*+ MATERIALIZE */
    a.numerocm,
    a.item,
    sum(QTDSALDO) as saldo_fob
    FROM SALDO_MANUAL a
    where a.entradasaida = 'S' and a.numerocm is not null
    group by a.numerocm, a.item
),
ESTOQUE AS (
    SELECT
    d.estab,
    d.item,
    d.saldo,
    nvl(f.saldo_fob,0) as saldo_fob,
    d.saldo - nvl(f.saldo_fob,0) as saldoreal
    FROM BASE_SALDO d
    left join SALDO_FOB f on
        f.numerocm = d.estab      /* pendência de negócio - ver observação no cabeçalho */
        and f.item = d.item
    where (d.saldo - nvl(f.saldo_fob,0)) > 0
),
RESULTADO AS (
    SELECT
    s.estab,
    s.reduzido,
    s.contrato,
    s.limitent,
    s.item,
    s.descricao,
    s.quantidade,
    s.baixado,
    s.cancelado,
    s.devolido,
    s.qtdsaldo,
    s.quantidade - s.cancelado AS qtd_a_debitar,
    e.saldo as saldo_estoque,
    e.saldo_fob,
    e.saldoreal,
    e.saldoreal - SUM(s.quantidade - s.cancelado) OVER (
                    PARTITION BY s.estab, s.item
                    ORDER BY s.limitent DESC, s.contrato
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                  ) AS saldo_corrente
    from saldo_manual s
    inner join base_saldo b on
        b.estab = s.estab
        and b.item = s.item
    left join ESTOQUE e on
        e.estab = s.estab
        and e.item = s.item
    where s.quantidade <>  s.qtdsaldo
    and s.quantidade <> s.cancelado
    and s.entradasaida = 'E'
),
RESULTADO2 AS (
    /* v8: marca se alguma linha ANTERIOR (mesma partição/ordem de débito)
       já tinha saldo_corrente <= 0. ROWS ... AND 1 PRECEDING exclui a
       própria linha atual - por isso a primeira linha <= 0 ainda entra
       (nenhuma anterior a ela ficou <= 0), e as seguintes não entram. */
    SELECT
        r.*,
        NVL(MAX(CASE WHEN r.saldo_corrente <= 0 THEN 1 ELSE 0 END) OVER (
                PARTITION BY r.estab, r.item
                ORDER BY r.limitent DESC, r.contrato
                ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
            ), 0) AS TEVE_NEGATIVO_ANTES
    FROM RESULTADO r
)
SELECT
    r.estab,
    r.reduzido,
    r.contrato,
    r.limitent,
    r.item,
    r.descricao,
    arredondar(r.quantidade,2) as quantidade,
    arredondar(r.baixado,2) as baixado,
    arredondar(r.cancelado,2) as cancelado,
    arredondar(r.devolido,2) as devolido,
    arredondar(r.qtdsaldo,2) as saldoctr,
    arredondar(r.saldo_estoque,2) as saldo_estoque,
    arredondar(r.qtd_a_debitar,2) as qtd_a_debitar,
    arredondar(r.saldo_corrente,2) as saldo_corrente
FROM RESULTADO2 r
WHERE r.TEVE_NEGATIVO_ANTES = 0
ORDER BY
    r.estab,
    r.item,
    r.limitent DESC,
    r.contrato