WITH /*+ MATERIALIZE */ NOTAS AS (
    SELECT
    NFCAB.ESTAB,
    NFCAB.SEQNOTA,
    NFCAB.NOTACONF,
    NFCAB.NUMEROCM,
    NFCABROMA.ROMANEIO,
    NFCABROMA.ENTRADASAIDA,
    NFCABROMA.CLASSIFICACAO,
    CONTAMOV.REACOBFINLEITURA
    FROM NFCAB
    INNER JOIN FILIAL ON
    FILIAL.ESTAB                    = NFCAB.ESTAB

    INNER JOIN CIDADE ON
    CIDADE.CIDADE                   = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF                  = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA              = 'E'
    and nfcfg.notaconf in (
    -- compra futura
    200,201,258,221,234,237,414,334,335,336,337,338,
    --- compra direta
    202,203,278
    )

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO             IN ('A','N')

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM               = NFCAB.NUMEROCM

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM               = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO            = NFCAB.SEQENDERECO

    INNER JOIN NFCABROMA ON
    NFCABROMA.ESTAB                 = NFCAB.ESTAB AND
    NFCABROMA.SEQNOTA               = NFCAB.SEQNOTA
),
ROMA_ABERTO /*+ MATERIALIZE */  AS (
    SELECT
    ROMA.ESTAB,
    ROMA.ROMANEIO,
    ROMA.ENTRADASAIDA,
    ROMA.NUMEROCM,
    ROMA.ITEM,
    ROMA.DTEMISSAO,
    ROMA.ROMANEIOCONFIG,
    ROMA.PESOLIQUIDO,
    ROMA.PESOTOTAL,
    ROMA.TARA,
    CONTAMOV.REACOBFINLEITURA
    FROM ROMA
    
    INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = ROMA.NUMEROCM
    
    INNER JOIN ROMACFG ON
        ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
        ROMACFG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
        ROMACFG.ENTRADASAIDA    = 'E'
    
    INNER JOIN ROMACLASS ON
        ROMACLASS.ESTAB                 = ROMA.ESTAB AND
        ROMACLASS.ROMANEIO              = ROMA.ROMANEIO AND
        ROMACLASS.ENTRADASAIDA          = ROMA.ENTRADASAIDA AND
        ROMACLASS.NUMEROCM              = ROMA.NUMEROCM AND
        romaclass.percentual            > 0

    WHERE NOT EXISTS (
        SELECT 1 FROM NFCABROMA
        WHERE NFCABROMA.ESTAB = ROMA.ESTAB
        AND NFCABROMA.ROMANEIO = ROMA.ROMANEIO
        AND NFCABROMA.ENTRADASAIDA = ROMA.ENTRADASAIDA
        AND NFCABROMA.NUMEROCM = ROMA.NUMEROCM
    )
    AND ROMA.ESTORNADO <> 'S'
),
UMIDADE /*+ MATERIALIZE */ AS (
    SELECT
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM,
        SUM(TABUMISERVITEM.VALOR) AS VALOR_UMIDADE
    FROM ROMATXSERVICO
        INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM
        INNER JOIN CONTAMOV ON
                CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM
                 AND CONTAMOV.REACOBFINLEITURA  = 0
        INNER JOIN ROMADESC ON
                ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
                ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
                ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
                ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
                ROMADESC.ROMADESC                   = 2
        INNER JOIN TABUMISERVCAB ON
                TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV
        INNER JOIN TABUMISERVITEM ON
                TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
                ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN
                
        INNER JOIN NOTAS ON
            NOTAS.ESTAB = ROMASERV.ESTAB
            AND NOTAS.NUMEROCM = ROMASERV.NUMEROCM
            AND NOTAS.ROMANEIO = ROMASERV.ROMANEIO
            AND NOTAS.ENTRADASAIDA = ROMASERV.ENTRADASAIDA
            
    WHERE ROMATXSERVICO.SERVICO = 30
      AND ROMATXSERVICO.STATUS <> 'C'
    GROUP BY
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM
),
UMIDADE_ROMA /*+ MATERIALIZE */ AS (
    SELECT
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM,
        SUM(TABUMISERVITEM.VALOR) AS VALOR_UMIDADE
    FROM ROMATXSERVICO
        INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM
        INNER JOIN CONTAMOV ON
                CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM
                 AND CONTAMOV.REACOBFINLEITURA  = 0
        INNER JOIN ROMADESC ON
                ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
                ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
                ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
                ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
                ROMADESC.ROMADESC                   = 2
        INNER JOIN TABUMISERVCAB ON
                TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV
        INNER JOIN TABUMISERVITEM ON
                TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
                ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN
              
        INNER JOIN ROMA_ABERTO ON
            ROMA_ABERTO.ESTAB = ROMASERV.ESTAB
            AND ROMA_ABERTO.NUMEROCM = ROMASERV.NUMEROCM
            AND ROMA_ABERTO.ROMANEIO = ROMASERV.ROMANEIO
            AND ROMA_ABERTO.ENTRADASAIDA = ROMASERV.ENTRADASAIDA   
            
    WHERE ROMATXSERVICO.SERVICO = 30
      AND ROMATXSERVICO.STATUS <> 'C'
    GROUP BY
        ROMATXSERVICO.ESTAB,
        ROMATXSERVICO.ROMANEIO,
        ROMATXSERVICO.ENTRADASAIDA,
        ROMATXSERVICO.NUMEROCM
),
NOTAS_ITEM /*+ MATERIALIZE */  AS (
    SELECT DISTINCT
    NFITEM.ESTAB,NFITEM.SEQNOTA,NFITEM.ITEM,NFITEM.ROMANEIO FROM NOTAS
    INNER JOIN NFITEM ON
        NFITEM.ESTAB = NOTAS.ESTAB
        AND NFITEM.SEQNOTA = NOTAS.SEQNOTA
    WHERE NFITEM.ROMANEIO IS NOT NULL
),
PAGAMENTOS /*+ MATERIALIZE */  AS (
    SELECT
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM,
        SUM(QTDEPAGO) AS QTDEPAGO
    FROM ROMATXSERVICOPG
        INNER JOIN NOTAS ON
            NOTAS.ESTAB = ROMATXSERVICOPG.ESTAB
            AND NOTAS.NUMEROCM = ROMATXSERVICOPG.NUMEROCM
            AND NOTAS.ROMANEIO = ROMATXSERVICOPG.ROMANEIO
            AND NOTAS.ENTRADASAIDA = ROMATXSERVICOPG.ENTRADASAIDA
    GROUP BY
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM
),
PAGAMENTOS_ROMA /*+ MATERIALIZE */  AS (
    SELECT
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM,
        SUM(QTDEPAGO) AS QTDEPAGO
    FROM ROMATXSERVICOPG
        INNER JOIN ROMA_ABERTO ON
            ROMA_ABERTO.ESTAB = ROMATXSERVICOPG.ESTAB
            AND ROMA_ABERTO.NUMEROCM = ROMATXSERVICOPG.NUMEROCM
            AND ROMA_ABERTO.ROMANEIO = ROMATXSERVICOPG.ROMANEIO
            AND ROMA_ABERTO.ENTRADASAIDA = ROMATXSERVICOPG.ENTRADASAIDA
    GROUP BY
        ROMATXSERVICOPG.ESTAB,
        ROMATXSERVICOPG.ROMANEIO,
        ROMATXSERVICOPG.ENTRADASAIDA,
        ROMATXSERVICOPG.NUMEROCM
)
---------- ROMANEIO EM ABERTO
SELECT
'ROMA PENDENTE' AS TIPO,
R.ESTAB,
0 AS SEQNOTA,
0 AS NOTACONF,
R.NUMEROCM,
R.ROMANEIO,
R.ROMANEIOCONFIG,
R.ENTRADASAIDA,
ITEMCOTITE.FIXACAO,
R.PESOLIQUIDO,
PAGAMENTOS_ROMA.QTDEPAGO,
R.REACOBFINLEITURA,
R.PESOLIQUIDO - 
        CASE
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) > 0 THEN PAGAMENTOS_ROMA.QTDEPAGO
            WHEN R.REACOBFINLEITURA = 0 AND NVL(PAGAMENTOS_ROMA.QTDEPAGO,0) = 0 THEN
            DIVIDE(    
                DIVIDE(
                    (NVL(R.PESOTOTAL,0) - NVL(R.TARA,0)) * NVL(UMIDADE_ROMA.VALOR_UMIDADE,0),
                    60),
            ITEMCOTITE.FIXACAO
            )*60
        ELSE 0 END
 AS SALDO
    
FROM ROMA_ABERTO R

LEFT JOIN UMIDADE_ROMA ON
    R.ESTAB = UMIDADE_ROMA.ESTAB
    AND R.NUMEROCM = UMIDADE_ROMA.NUMEROCM
    AND R.ROMANEIO = UMIDADE_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = UMIDADE_ROMA.ENTRADASAIDA

LEFT JOIN PAGAMENTOS_ROMA ON
    R.ESTAB = PAGAMENTOS_ROMA.ESTAB
    AND R.NUMEROCM = PAGAMENTOS_ROMA.NUMEROCM
    AND R.ROMANEIO = PAGAMENTOS_ROMA.ROMANEIO
    AND R.ENTRADASAIDA = PAGAMENTOS_ROMA.ENTRADASAIDA

LEFT JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = R.ESTAB AND
    ITEMAGROESTAB.ITEM              = R.ITEM

LEFT JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

LEFT JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    R.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
    
UNION ALL
--- COMPRA FUTURA E COMPRA DIRETA
SELECT
CASE WHEN NOTAS.NOTACONF IN (200,201,258,221,234,237,414,334,335,336,337,338) THEN 'FUTURO' ELSE 'DIRETO' END TIPO,
NOTAS.ESTAB,
NOTAS.SEQNOTA,
NOTAS.NOTACONF,
NOTAS.NUMEROCM,
NOTAS.ROMANEIO,
ROMA.ROMANEIOCONFIG,
NOTAS.ENTRADASAIDA,
ITEMCOTITE.FIXACAO,
ROMA.PESOLIQUIDO,
PAGAMENTOS.QTDEPAGO,
NOTAS.REACOBFINLEITURA,
CASE 
    --- VALIDAÇÃO COMPRA DIRETA
    WHEN  NOTAS.NOTACONF IN (202,203,278) AND ROMA.ROMANEIOCONFIG = 9 THEN 0
    WHEN NOTAS.NOTACONF IN (202,203,278) AND ROMA.ROMANEIOCONFIG <> 9 THEN
        ROMA.PESOLIQUIDO - (CASE WHEN NOTAS.REACOBFINLEITURA = 0 THEN NVL(PAGAMENTOS.QTDEPAGO,0) ELSE 0 END)
    --- VALIDAÇÃO COMPRA FUTURA
    WHEN ROMA.ROMANEIOCONFIG = 52 THEN ROMA.PESOORIGEM 
    ELSE ROMA.PESOLIQUIDO - 
        CASE
            WHEN NOTAS.REACOBFINLEITURA = 0 AND PAGAMENTOS.QTDEPAGO > 0 THEN PAGAMENTOS.QTDEPAGO
            WHEN NOTAS.REACOBFINLEITURA = 0 AND PAGAMENTOS.QTDEPAGO = 0 THEN
            DIVIDE(    
                DIVIDE(
                    (NVL(ROMA.PESOTOTAL,0) - NVL(ROMA.TARA,0)) * NVL(UMIDADE.VALOR_UMIDADE,0),
                    60),
            ITEMCOTITE.FIXACAO
            )*60
        ELSE 0 END
    END AS SALDO
FROM NOTAS
INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB                 = NOTAS.ESTAB AND
    ROMACLASS.ROMANEIO              = NOTAS.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA          = NOTAS.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM              = NOTAS.NUMEROCM AND
    ROMACLASS.CLASSIFICACAO         = NOTAS.CLASSIFICACAO /*AND
    ROMACLASS.PERCENTUAL            > 0                         */

INNER JOIN ROMA ON
    ROMA.ESTAB                      = ROMACLASS.ESTAB AND
    ROMA.ROMANEIO                   = ROMACLASS.ROMANEIO AND
    ROMA.ENTRADASAIDA               = ROMACLASS.ENTRADASAIDA AND
    ROMA.NUMEROCM                   = ROMACLASS.NUMEROCM AND
    ROMA.ESTORNADO <> 'S'

INNER JOIN NOTAS_ITEM ON
    NOTAS_ITEM.ESTAB                    = NOTAS.ESTAB AND
    NOTAS_ITEM.SEQNOTA                  = NOTAS.SEQNOTA AND
    NOTAS_ITEM.ROMANEIO                 = NOTAS.ROMANEIO
    
LEFT JOIN UMIDADE ON
    NOTAS.ESTAB = UMIDADE.ESTAB
    AND NOTAS.NUMEROCM = UMIDADE.NUMEROCM
    AND NOTAS.ROMANEIO = UMIDADE.ROMANEIO
    AND NOTAS.ENTRADASAIDA = UMIDADE.ENTRADASAIDA
    
LEFT JOIN PAGAMENTOS ON
    NOTAS.ESTAB = PAGAMENTOS.ESTAB
    AND NOTAS.NUMEROCM = PAGAMENTOS.NUMEROCM
    AND NOTAS.ROMANEIO = PAGAMENTOS.ROMANEIO
    AND NOTAS.ENTRADASAIDA = PAGAMENTOS.ENTRADASAIDA

INNER JOIN ITEMAGROESTAB ON
    ITEMAGROESTAB.ESTAB             = NOTAS_ITEM.ESTAB AND
    ITEMAGROESTAB.ITEM              = NOTAS_ITEM.ITEM

INNER JOIN ITEMCOTCAB ON
    ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
    ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

INNER JOIN ITEMCOTITE ON
    ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
    ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
    ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN
