
WITH
  -- 0) Lista de pedidos por NF (usando LISTAGG) e materializada
  PedidosPorNF AS (
    SELECT /*+ MATERIALIZE */
      NF.ESTAB AS ESTAB_NF,
      NF.SEQNOTA AS SEQNOTA_NF,
      LISTAGG(
        DISTINCT (PI.SERIE || '-' || TO_CHAR(PI.NUMERO)), 
        ', '
      ) WITHIN GROUP (ORDER BY PI.SERIE, PI.NUMERO) AS PEDIDOS
    FROM NFCAB NF
    JOIN NFITEM NI 
      ON NI.ESTAB = NF.ESTAB 
      AND NI.SEQNOTA = NF.SEQNOTA
    JOIN PEDITEMNFITEM PI 
      ON PI.ESTABNOTA = NI.ESTAB 
      AND PI.SEQNOTA = NI.SEQNOTA 
      AND PI.SEQNOTAITEM = NI.SEQNOTAITEM
    GROUP BY 
      NF.ESTAB, 
      NF.SEQNOTA
  ),
  
  -- 1) Base de PDUPPAGA já filtrada (reduz o volume)
  PD_Base AS (
    SELECT 
      PD.EMPRESA,
      PD.DUPPAG,
      PD.FORNECEDOR,
      PD.DTVENCTO,
      PD.DTEMISSAO,
      PD.NRODOCTOORIGEM,
      PD.HISTORICO,
      PD.VALOR AS VLRDUP
    FROM PDUPPAGA PD
    WHERE (PD.DEPOSITAR IS NULL OR PD.DEPOSITAR = 'N')
      AND PD.QUITADA = 'N'
      AND PD.CENTROCUS IS NOT NULL
  ),
 
  -- 2) Grupo do usuário logado
  UsuarioGrupo AS (
    SELECT IDGRPAPROVADORES
    FROM GRUPOUSUARIO
    WHERE USERID = :usuario_logado
  ),
 
  -- 3) Regras do grupo de aprovação
  RegrasDoGrupo AS (
    SELECT EG.IDREGRA
    FROM ESTRATEGIAGRUPO EG
    JOIN UsuarioGrupo UG 
      ON UG.IDGRPAPROVADORES = EG.IDGRPAPROVADORES
  ),
 
  -- 4) Regras com faixa de valor e estabelecimento
  RegrasComFiltro AS (
    SELECT 
      R.IDREGRA,
      R.VLRINICIAL AS VALORMINIMO,
      R.VLRFINAL AS VALORMAXIMO,
      R.IDESTAB AS ESTAB
    FROM ESTRATEGIAREGRA R
    JOIN ESTRATEGIAPEDIDO EP 
      ON R.IDESTRATEGIA = EP.IDESTRATEGIA 
      AND EP.IDESTRATEGIA IN (427, 431, 433)
    JOIN RegrasDoGrupo RG 
      ON RG.IDREGRA = R.IDREGRA
  ),
 
  -- 5) Centros de custo válidos permitidos para a regra
  CentrosValidos AS (
    SELECT 
      EC.IDREGRA,
      EC.CENTROCUS AS CENTROCUSTO
    FROM ESTRATEGIACENCUSTO EC
    JOIN RegrasDoGrupo RG 
      ON RG.IDREGRA = EC.IDREGRA
  ),
 
  -- 6) Notas pendentes
  NotasPendentes AS (
    SELECT 
      CAST(0 AS INTEGER) AS APROVAR,
      CAST(0 AS INTEGER) AS CANCELAR,
      NF.DTEMISSAO,
      PDB.HISTORICO AS OBS_PEDIDO,
      CM.NOME AS PESSOANOME,
      NF.CENCUSCOD,
      NF.CENTROCUS,
      NF.NOTA,
      NF.NUMEROCM AS FORNECEDOR,
      NF.ESTAB,
      FL.REDUZIDO,
      PDB.DUPPAG,
      PDB.DTVENCTO,
      PDB.VLRDUP AS VLRAUTPAGAR,
      NVL(PNF.PEDIDOS, '') AS PEDIDOS
    FROM PD_Base PDB
    JOIN AGRFINDUPPAG AF 
      ON PDB.EMPRESA = AF.ESTAB 
      AND PDB.DUPPAG = AF.DUPPAG
    JOIN NFCABAGRFIN NA 
      ON AF.SEQPAGAMENTO = NA.SEQPAGAMENTO 
      AND AF.ESTAB = NA.ESTAB 
      AND AF.FORNECEDOR = PDB.FORNECEDOR
    JOIN NFCAB NF 
      ON NF.ESTAB = NA.ESTAB 
      AND NF.SEQNOTA = NA.SEQNOTA
    JOIN FILIAL FL 
      ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM 
      ON CM.NUMEROCM = NF.NUMEROCM
    LEFT JOIN PedidosPorNF PNF 
      ON PNF.ESTAB_NF = NF.ESTAB 
      AND PNF.SEQNOTA_NF = NF.SEQNOTA
    INNER JOIN RegrasComFiltro RF
      ON RF.ESTAB = NF.ESTAB
      AND NF.VALOR BETWEEN RF.VALORMINIMO AND RF.VALORMAXIMO
    INNER JOIN CentrosValidos CV
      ON CV.IDREGRA = RF.IDREGRA
      AND NF.CENTROCUS = CV.CENTROCUSTO
  ),

  -- 7) Notas pendentes (via movimento)
  NotasPendentesMov AS (
    SELECT 
      CAST(0 AS INTEGER) AS APROVAR,
      CAST(0 AS INTEGER) AS CANCELAR,
      NF.DTEMISSAO,
      PDB.HISTORICO AS OBS_PEDIDO,
      CM.NOME AS PESSOANOME,
      NF.CENCUSCOD,
      NF.CENTROCUS,
      NF.NOTA,
      NF.NUMEROCM AS FORNECEDOR,
      NF.ESTAB,
      FL.REDUZIDO,
      PDB.DUPPAG,
      PDB.DTVENCTO,
      PDB.VLRDUP AS VLRAUTPAGAR,
      NVL(PNF.PEDIDOS, '') AS PEDIDOS
    FROM PD_Base PDB
    JOIN CONTAMOVLAN CML 
      ON CML.ESTAB = PDB.EMPRESA 
      AND CML.NUMEROCM = PDB.FORNECEDOR 
      AND CML.DTMOVTO = PDB.DTEMISSAO 
      AND PDB.NRODOCTOORIGEM = TO_CHAR(CML.ESTAB || '||' || CML.NUMEROCM || '||' || CML.SEQCM)
    JOIN AGRFINCTAMOV AFM 
      ON AFM.ESTAB = CML.ESTAB 
      AND AFM.SEQCM = CML.SEQCM 
      AND AFM.NUMEROCM = CML.NUMEROCM
    JOIN NFCABAGRFIN NAF 
      ON NAF.ESTAB = AFM.ESTAB 
      AND NAF.SEQPAGAMENTO = AFM.SEQPAGAMENTO
    JOIN NFCAB NF 
      ON NF.ESTAB = NAF.ESTAB 
      AND NF.SEQNOTA = NAF.SEQNOTA 
      AND NF.NUMEROCM = AFM.NUMEROCM
    JOIN FILIAL FL 
      ON FL.ESTAB = NF.ESTAB
    JOIN CONTAMOV CM 
      ON CM.NUMEROCM = NF.NUMEROCM
    LEFT JOIN PedidosPorNF PNF 
      ON PNF.ESTAB_NF = NF.ESTAB 
      AND PNF.SEQNOTA_NF = NF.SEQNOTA
    INNER JOIN RegrasComFiltro RF
      ON RF.ESTAB = NF.ESTAB
      AND NF.VALOR BETWEEN RF.VALORMINIMO AND RF.VALORMAXIMO
    INNER JOIN CentrosValidos CV
      ON CV.IDREGRA = RF.IDREGRA
      AND NF.CENTROCUS = CV.CENTROCUSTO
  )

-- 8) Resultado final
SELECT 
  APROVAR,
  CANCELAR,
  ESTAB,
  ESTAB||'-'||REDUZIDO AS FILIAL,
  DTEMISSAO,
  PEDIDOS AS PEDIDO,
  NOTA,
  PESSOANOME||'-'||FORNECEDOR AS FORNECEDOR,
  CENTROCUS,
  DUPPAG,
  DTVENCTO,
  VLRAUTPAGAR,
  OBS_PEDIDO
FROM NotasPendentes

UNION ALL

SELECT 
  APROVAR,
  CANCELAR,
  ESTAB,
  ESTAB||'-'||REDUZIDO AS FILIAL,
  DTEMISSAO,
  PEDIDOS AS PEDIDO,
  NOTA,
  PESSOANOME||'-'||FORNECEDOR AS FORNECEDOR,
  CENTROCUS,
  DUPPAG,
  DTVENCTO,
  VLRAUTPAGAR,
  OBS_PEDIDO
FROM NotasPendentesMov
