SELECT DADOS.* FROM(

SELECT DISTINCT
        'CHQ' AS TIPODOC,
        PDUPREC.EMPRESA AS OSESTAB,
   
        NFCAB.NOTA,
    
        REPRE.NUMEROCM AS OSRTV,
        PDUPREC.CLIENTE AS NUMEROCM,
  
        PRDURECH.DTLANCA AS DTEMISSAO,
     
        pduprec.dtvencto AS DTVENCTO,
        ITEMAGRO.ITEM AS OSPRODUTO,              
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,
     
        SUM(PRDURECH.VLRCHEQREC) AS VALOR,
        SUM(PRDURECH.VLRCHEQREC) AS SALDO,

     DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100)  as VALORLIQ,

       
       0 RECEBIDO,

       ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) AS MARGEM,
       
       CASE WHEN ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) BETWEEN 0 AND 19.99 
                    THEN ARREDONDAR((DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.05,2)
       WHEN ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) BETWEEN 20 AND 24.99 
                    THEN ARREDONDAR((DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.08,2)
       ELSE ARREDONDAR((DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.1,2) END PROVISAOLIQ,
       
       
       
        NFITEM.CUSTOCMVP
        
   FROM PCHEQREC
   
   INNER JOIN PRDURECH
    ON PRDURECH.EMPRESA = PCHEQREC.EMPRESA
    AND PRDURECH.CLIENTE = PCHEQREC.CLIENTE
    AND PRDURECH.NROCHEQUE = PCHEQREC.NROCHEQUE
    AND PCHEQREC.DTLANCA IS NULL 
    
      INNER JOIN PRDUPREC ON
    PRDUPREC.EMPRESA = PRDURECH.EMPRESA
    AND PRDUPREC.DUPREC = PRDURECH.DUPREC
    AND PRDUPREC.SEQRECBTO = PRDURECH.SEQRECBTO
   
   INNER JOIN PDUPREC
    ON PRDUPREC.EMPRESA = PDUPREC.EMPRESA
    --AND PRDUPREC.CLIENTE = PDUPREC.CLIENTE
    AND PRDUPREC.DUPREC = PDUPREC.DUPREC
    
       INNER JOIN CONTAMOV
            ON (PDUPREC.CLIENTE = CONTAMOV.NUMEROCM)
       LEFT JOIN CONTAMOV REPRE
            ON (PDUPREC.REPRESENT = REPRE.NUMEROCM)
       LEFT JOIN AGRFINDUPREC
            ON (PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB)
            AND (PDUPREC.DUPREC = AGRFINDUPREC.DUPREC)
       LEFT JOIN NFCABAGRFIN
            ON (AGRFINDUPREC.ESTAB = NFCABAGRFIN.ESTAB)
       AND (AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO)
       LEFT JOIN NFITEM
            ON (NFCABAGRFIN.ESTAB = NFITEM.ESTAB)
            AND (NFCABAGRFIN.SEQNOTA = NFITEM.SEQNOTA)
       LEFT JOIN ITEMAGRO
            ON (NFITEM.ITEM = ITEMAGRO.ITEM)
       LEFT JOIN NFCAB
            ON (NFCAB.ESTAB = NFCABAGRFIN.ESTAB)
            AND (NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA)
       LEFT JOIN PREPRESE
            ON (PDUPREC.REPRESENT = PREPRESE.REPRESENT)
            AND (PREPRESE.EMPRESA = PDUPREC.EMPRESA)

       LEFT JOIN ITEMGRUPO
            ON (ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO)
    
  WHERE
  PCHEQREC.EMPRESA <> 5
 AND  PCHEQREC.DTLANCA IS NULL 
  and PCHEQREC.VALOR > 0

 AND PRDUPREC.DTRECBTO <= CURRENT_DATE


AND REPRE.NUMEROCM > 100




GROUP BY     PDUPREC.EMPRESA,      
       NFCAB.NOTA,   
        REPRE.NUMEROCM,
        PDUPREC.CLIENTE,  
        PRDURECH.DTLANCA,      
        pduprec.dtvencto,
        ITEMAGRO.ITEM,              
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,PDUPREC.VALOR,
        NFITEM.CUSTOCMVP

HAVING SUM(PRDURECH.VLRCHEQREC) > 0

UNION ALL

SELECT DISTINCT
      'DUP' AS TIPODOC,
        PDUPREC.EMPRESA AS OSESTAB,
        nfcab.nota,
     
        REPRE.NUMEROCM AS OSRTV,
        PDUPREC.CLIENTE AS NUMEROCM,
   
        PDUPREC.DTEMISSAO,
        NFCAB.PRAZOPAGTO DTVENCTO,
        ITEMAGRO.ITEM AS OSPRODUTO,
       
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,
     
       (SUM(VDUPREC.VALOR))VALOR,
        (SUM(VDUPREC.VALOR)+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) )) SALDO,
    
       ARREDONDAR((nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )),2)   AS VALORLIQ,
       
      
      SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) AS RECEBIDO,
       ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) AS MARGEM,
      
       CASE WHEN  ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) BETWEEN 0 AND 19.99
                    THEN ARREDONDAR((ARREDONDAR((nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )),2)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.05,2)
                    
       WHEN  ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) BETWEEN 20 AND 24.99 
                      THEN ARREDONDAR((ARREDONDAR((nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )),2)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.08,2)
                      
       ELSE ARREDONDAR((ARREDONDAR((nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )),2)*DIVIDE(ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2),100))*0.1,2) END PROVISAOLIQ,
        
        
   
        NFITEM.CUSTOCMVP
        
   FROM PDUPREC
    
      INNER JOIN VDUPREC ON VDUPREC.EMPRESA=PDUPREC.EMPRESA
                        AND VDUPREC.DUPREC=PDUPREC.DUPREC
                        AND VDUPREC.CLIENTE=PDUPREC.CLIENTE
                        AND VDUPREC.ESTABCLIENTE=PDUPREC.ESTABCLIENTE
    
    
       INNER JOIN CONTAMOV
            ON (PDUPREC.CLIENTE = CONTAMOV.NUMEROCM)
       LEFT JOIN CONTAMOV REPRE
            ON (PDUPREC.REPRESENT = REPRE.NUMEROCM)
       LEFT JOIN AGRFINDUPREC
            ON (PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB)
            AND (PDUPREC.DUPREC = AGRFINDUPREC.DUPREC)
       LEFT JOIN NFCABAGRFIN
            ON (AGRFINDUPREC.ESTAB = NFCABAGRFIN.ESTAB)
       AND (AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO)
       LEFT JOIN NFITEM
            ON (NFCABAGRFIN.ESTAB = NFITEM.ESTAB)
            AND (NFCABAGRFIN.SEQNOTA = NFITEM.SEQNOTA)
       LEFT JOIN ITEMAGRO
            ON (NFITEM.ITEM = ITEMAGRO.ITEM)
       LEFT JOIN NFCAB
            ON (NFCAB.ESTAB = NFCABAGRFIN.ESTAB)
            AND (NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA)
       LEFT JOIN PREPRESE
            ON (PDUPREC.REPRESENT = PREPRESE.REPRESENT)
            AND (PREPRESE.EMPRESA = PDUPREC.EMPRESA)
       LEFT JOIN PPESCLI
            ON (PPESCLI.CLIENTE = CONTAMOV.NUMEROCM)
            AND (PPESCLI.EMPRESA = PDUPREC.ESTABCLIENTE)
       LEFT JOIN ITEMGRUPO
            ON (ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO)
      LEFT JOIN TABLE (PBAIXASDUPREC(PDUPREC.EMPRESA, PDUPREC.DUPREC,CURRENT_DATE,'01/01/2000')) PBAIXASDUPREC
         ON (0=0)      


  WHERE
  PDUPREC.EMPRESA <> 5
 
AND PDUPREC.DTEMISSAO <= CURRENT_DATE



AND REPRE.NUMEROCM > 100


GROUP BY  PDUPREC.EMPRESA,
        nfcab.nota,       
        REPRE.NUMEROCM,
        PDUPREC.CLIENTE,
        PDUPREC.DTEMISSAO,
        NFCAB.PRAZOPAGTO,
        ITEMAGRO.ITEM,
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,

        NFITEM.CUSTOCMVP
        
        
        
   HAVING (SUM(VDUPREC.VALOR)+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) )) > 0
   
UNION ALL    
  SELECT DISTINCT
        'CHQ' AS TIPODOC,
        PDUPREC.EMPRESA AS OSESTAB,
  
        NFCAB.NOTA,
 
        REPRE.NUMEROCM AS OSRTV,
        PDUPREC.CLIENTE AS NUMEROCM,

        PRDURECH.DTLANCA AS DTEMISSAO,
     
        pduprec.dtvencto AS DTVENCTO,
        ITEMAGRO.ITEM AS OSPRODUTO,              
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,
     
        SUM(PRDURECH.VLRCHEQREC) AS VALOR,
        SUM(PRDURECH.VLRCHEQREC) AS SALDO,
  
     DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100)  as VALORLIQ,
 
       
       0 RECEBIDO,
     
       ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) AS MARGEM,
       
      CASE WHEN PREPRESE.COMISCONF = 9 THEN  ARREDONDAR(DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100) *0.05,2)
              WHEN PREPRESE.COMISCONF = 10 THEN  ARREDONDAR(DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100) *0.03,2)
              WHEN PREPRESE.COMISCONF = 11 THEN  ARREDONDAR(DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100) *0.05,2)
              ELSE  ARREDONDAR(DIVIDE(SUM(PRDURECH.VLRCHEQREC) * (DIVIDE(NFITEM.VALORTOTAL,SUM(PRDURECH.VLRCHEQREC))*100),100) *0.05,2) END PROVISAOLIQ,
       
        NFITEM.CUSTOCMVP
        
   FROM PCHEQREC
   
   INNER JOIN PRDURECH
    ON PRDURECH.EMPRESA = PCHEQREC.EMPRESA
    AND PRDURECH.CLIENTE = PCHEQREC.CLIENTE
    AND PRDURECH.NROCHEQUE = PCHEQREC.NROCHEQUE
    AND PCHEQREC.DTLANCA IS NULL 
    
      INNER JOIN PRDUPREC ON
    PRDUPREC.EMPRESA = PRDURECH.EMPRESA
    AND PRDUPREC.DUPREC = PRDURECH.DUPREC
    AND PRDUPREC.SEQRECBTO = PRDURECH.SEQRECBTO
   
   INNER JOIN PDUPREC
    ON PRDUPREC.EMPRESA = PDUPREC.EMPRESA
 
    AND PRDUPREC.DUPREC = PDUPREC.DUPREC
    
       INNER JOIN CONTAMOV
            ON (PDUPREC.CLIENTE = CONTAMOV.NUMEROCM)
       LEFT JOIN CONTAMOV REPRE
            ON (PDUPREC.REPRESENT = REPRE.NUMEROCM)
       LEFT JOIN AGRFINDUPREC
            ON (PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB)
            AND (PDUPREC.DUPREC = AGRFINDUPREC.DUPREC)
       LEFT JOIN NFCABAGRFIN
            ON (AGRFINDUPREC.ESTAB = NFCABAGRFIN.ESTAB)
       AND (AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO)
       LEFT JOIN NFITEM
            ON (NFCABAGRFIN.ESTAB = NFITEM.ESTAB)
            AND (NFCABAGRFIN.SEQNOTA = NFITEM.SEQNOTA)
       LEFT JOIN ITEMAGRO
            ON (NFITEM.ITEM = ITEMAGRO.ITEM)
       LEFT JOIN NFCAB
            ON (NFCAB.ESTAB = NFCABAGRFIN.ESTAB)
            AND (NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA)
       LEFT JOIN PREPRESE
            ON (PDUPREC.REPRESENT = PREPRESE.REPRESENT)
            AND (PREPRESE.EMPRESA = PDUPREC.EMPRESA)

       LEFT JOIN ITEMGRUPO
            ON (ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO)
    
  WHERE
  PCHEQREC.EMPRESA = 5
 AND  PCHEQREC.DTLANCA IS NULL 
  and PCHEQREC.VALOR > 0

 AND PRDUPREC.DTRECBTO <= CURRENT_DATE


AND REPRE.NUMEROCM > 100




GROUP BY     PDUPREC.EMPRESA,      
       NFCAB.NOTA,   
        REPRE.NUMEROCM,
        PREPRESE.COMISCONF,
        PDUPREC.CLIENTE,  
        PRDURECH.DTLANCA,      
        pduprec.dtvencto,
        ITEMAGRO.ITEM,              
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,PDUPREC.VALOR,
        NFITEM.CUSTOCMVP

HAVING SUM(PRDURECH.VLRCHEQREC) > 0

UNION ALL

SELECT DISTINCT
      'DUP' AS TIPODOC,
        PDUPREC.EMPRESA AS OSESTAB,
        nfcab.nota,

        REPRE.NUMEROCM AS OSRTV,
        PDUPREC.CLIENTE AS NUMEROCM,

        PDUPREC.DTEMISSAO,
        NFCAB.PRAZOPAGTO DTVENCTO,
        ITEMAGRO.ITEM AS OSPRODUTO,
       
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,
     
       (SUM(VDUPREC.VALOR))VALOR,
        (SUM(VDUPREC.VALOR)+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) )) SALDO,
    
       ARREDONDAR((nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )),2)   AS VALORLIQ,
     
      SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) AS RECEBIDO,
       ARREDONDAR( DIVIDE((NFITEM.VALORTOTAL) - (NFITEM.QUANTIDADE* NFITEM.CUSTOCMVP), (NFITEM.VALORTOTAL)) *100,2) AS MARGEM,
      
      CASE WHEN  PREPRESE.COMISCONF = 9 THEN ARREDONDAR( (nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )) *0.05    ,2)
            WHEN  PREPRESE.COMISCONF = 10 THEN ARREDONDAR( (nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )) *0.03    ,2)
            WHEN  PREPRESE.COMISCONF = 11 THEN ARREDONDAR( (nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )) *0.1    ,2)
            ELSE ARREDONDAR( (nfitem.valortotal+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (DIVIDE(NFITEM.VALORTOTAL,  SUM(VDUPREC.VALOR)) * SUM(PNRECEBIDODUPREC)  )) *0.05  ,2)END PROVISAOLIQ,
   
        NFITEM.CUSTOCMVP
        
   FROM PDUPREC
    
      INNER JOIN VDUPREC ON VDUPREC.EMPRESA=PDUPREC.EMPRESA
                        AND VDUPREC.DUPREC=PDUPREC.DUPREC
                        AND VDUPREC.CLIENTE=PDUPREC.CLIENTE
                        AND VDUPREC.ESTABCLIENTE=PDUPREC.ESTABCLIENTE
    
    
       INNER JOIN CONTAMOV
            ON (PDUPREC.CLIENTE = CONTAMOV.NUMEROCM)
       LEFT JOIN CONTAMOV REPRE
            ON (PDUPREC.REPRESENT = REPRE.NUMEROCM)
       LEFT JOIN AGRFINDUPREC
            ON (PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB)
            AND (PDUPREC.DUPREC = AGRFINDUPREC.DUPREC)
       LEFT JOIN NFCABAGRFIN
            ON (AGRFINDUPREC.ESTAB = NFCABAGRFIN.ESTAB)
       AND (AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO)
       LEFT JOIN NFITEM
            ON (NFCABAGRFIN.ESTAB = NFITEM.ESTAB)
            AND (NFCABAGRFIN.SEQNOTA = NFITEM.SEQNOTA)
       LEFT JOIN ITEMAGRO
            ON (NFITEM.ITEM = ITEMAGRO.ITEM)
       LEFT JOIN NFCAB
            ON (NFCAB.ESTAB = NFCABAGRFIN.ESTAB)
            AND (NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA)
       LEFT JOIN PREPRESE
            ON (PDUPREC.REPRESENT = PREPRESE.REPRESENT)
           -- AND (PREPRESE.EMPRESA = PDUPREC.EMPRESA)
       LEFT JOIN PPESCLI
            ON (PPESCLI.CLIENTE = CONTAMOV.NUMEROCM)
            AND (PPESCLI.EMPRESA = PDUPREC.ESTABCLIENTE)
       LEFT JOIN ITEMGRUPO
            ON (ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO)
      LEFT JOIN TABLE (PBAIXASDUPREC(PDUPREC.EMPRESA, PDUPREC.DUPREC,CURRENT_DATE,'01/01/2000')) PBAIXASDUPREC
         ON (0=0)      


  WHERE
  PDUPREC.EMPRESA = 5

AND PDUPREC.DTEMISSAO <= CURRENT_DATE



AND REPRE.NUMEROCM > 100


GROUP BY  PDUPREC.EMPRESA,
        nfcab.nota,       
        REPRE.NUMEROCM,
        PREPRESE.COMISCONF,
        PDUPREC.CLIENTE,
        PDUPREC.DTEMISSAO,
        NFCAB.PRAZOPAGTO,
        ITEMAGRO.ITEM,
        NFITEM.QUANTIDADE,
        NFITEM.VALORUNITARIO,
        NFITEM.VALORTOTAL,
        NFITEM.CUSTOCMVP
        
        
        
   HAVING (SUM(VDUPREC.VALOR)+SUM(PBAIXASDUPREC.PNJUROS)-SUM(PBAIXASDUPREC.PNDESCONTOS) - (SUM(PBAIXASDUPREC.PNRECEBIDODUPREC) )) > 0 
   
   
    ) DADOS
WHERE DADOS.PROVISAOLIQ >0