WITH CONVERSAO AS (
    SELECT 
    *
    FROM 
    (
        SELECT moedaval.*,
               ROW_NUMBER() OVER (PARTITION BY moeda ORDER BY data DESC) AS rn
        FROM moedaval
    )dados
    -- WHERE rn = 1
),
FLUXO AS (
    SELECT
    ESTAB,
    CONTRATO,
    MAX(DTVENCTO) AS DTVENCTO
    FROM CONTRATODTVENCTO
    GROUP BY ESTAB,CONTRATO
),
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND CONTRATONFITE.TIPOBAIXA IN ('A','V') AND NFCAB.NOTACONF NOT IN (291) AND (P.TIPOOP NOT IN ('RP') OR P.TIPOOP IS NULL) THEN CONTRATONFITE.valor
       --WHEN  NAT.TIPODCTO IN ('N','X','A','T') AND CONTRATONFITE.TIPOBAIXA IN ('V') AND P.TIPOOP ='VF' THEN CONTRATONFITE.valor
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND CONTRATONFITE.TIPOBAIXA IN ('A','V') THEN CONTRATONFITE.valor
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND CONTRATONFITE.TIPOBAIXA IN ('A','V') AND NFCFG.NOTACONF IN (291) THEN CONTRATONFITE.valor
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN NFITEM ON NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    WHERE CONTRATOCFG.entradasaida = 'S'--U_TIPOCTR.TIPOCTR IN ('CTR-C')
),
BAIXAS AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.VALOR) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE CONTRATOCFG.entradasaida = 'S'--U_TIPOCTR.TIPOCTR IN ('CTR-C')
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
)

SELECT 
contrato.estab,
contrato.contrato,
(CONTRATOITE.VALORTOTAL * COALESCE(CONVERSAO.VALOR,C1.VALOR,1)) as valortotal,
COALESCE(BAIXAS.BAIXADO,0)BAIXADO,
COALESCE(BAIXAS.CANCELADO,0)CANCELADO,
COALESCE(BAIXAS.DEVOLIDO,0)DEVOLIDO,
COALESCE(CANC.CANC,0)CANC,
ARREDONDAR( (CONTRATOITE.VALORTOTAL * COALESCE(CONVERSAO.VALOR,C1.VALOR,1)) - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) saldo
FROM CONTRATO

INNER JOIN CONTRATOITE ON CONTRATOITE.ESTAB = CONTRATO.ESTAB AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF

LEFT JOIN BAIXAS ON BAIXAS.ESTAB = CONTRATOITE.ESTAB AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM
LEFT JOIN CANC ON CANC.ESTAB = CONTRATOITE.ESTAB AND CANC.CONTRATO = CONTRATOITE.CONTRATO AND CANC.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN FLUXO ON
    FLUXO.ESTAB = CONTRATO.ESTAB
    AND FLUXO.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN CONVERSAO 
    ON CONVERSAO.MOEDA = CONTRATO.MOEDA
    AND CONVERSAO.DATA = CONTRATO.DTVENCTO
    
LEFT JOIN CONVERSAO C1 ON
    C1.MOEDA = CONTRATO.MOEDA
    AND C1.RN = 1


WHERE 
contratocfg.entradasaida = 'S'
and contrato.ativo = 'A'
AND CONTRATO.DTEMISSAO BETWEEN '01/01/2025' AND '30/07/2025' 
AND CONTRATO.ESTAB <> 26 
AND CONTRATO.NUMEROCM > 90 --and contrato.contrato = 3322 and contrato.estab = 31
