WITH 
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN (NAT.TIPODCTO IN ('N','X','A','T') and NFCFG.NOTACONF not IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN (NAT.TIPODCTO = 'D' OR NFCFG.NOTACONF IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE CONTRATOCFG.ENTRADASAIDA IN ('E','S')
),
BAIXAS AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE CONTRATOCFG.ENTRADASAIDA IN ('E','S')
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
VENCTO AS (
    SELECT
    ESTAB,
    CONTRATO,
    MAX(DTVENCTO) AS DTVENCTO
    FROM CONTRATODTVENCTO C
    GROUP BY ESTAB,CONTRATO
),
SALDO_MANUAL AS (
SELECT 
    CONTRATO.ESTAB,
    CONTRATO.CONTRATO,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    LOCALEST.LOCAL,
    ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) QTDSALDO
FROM CONTRATO
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = CONTRATO.NUMEROCM
    AND ENDERECO.SEQENDERECO =  CONTRATO.ENDALTERNATIVO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
LEFT JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

LEFT JOIN CONTRATOITE ON 
    CONTRATOITE.ESTAB = CONTRATO.ESTAB 
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN LOCALEST ON 
    LOCALEST.ESTAB = CONTRATOITE.ESTAB
    AND LOCALEST.LOCAL = CONTRATOITE.LOCAL
    
LEFT JOIN BAIXAS ON 
    BAIXAS.ESTAB = CONTRATOITE.ESTAB 
    AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
    AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN CANC ON 
    CANC.ESTAB = CONTRATOITE.ESTAB 
    AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
    AND CANC.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID

WHERE 
CONTRATOCFG.ENTRADASAIDA IN ('E','S')
AND U.GRAOS='S'
AND FILIAL.INATIVA = 'N'
AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
)

SELECT * FROM SALDO_MANUAL 