create or replace FUNCTION PCUSTO (
  I_PNESTAB INTEGER
  , I_PNITEM INTEGER
  , I_PNCODIGOCUSTO INTEGER
  , I_PDDATA DATE
  , I_PHORA VARCHAR
  , I_CONSIDERARNFBONIF_CUSTOZERO INTEGER := 1)
  RETURN NUMBER
IS
  O_NCUSTO    NUMBER;
  V_CUSTO     NUMBER;
  V_DATA      DATE;                                                      
  V_CUSTOREAJ NUMBER;
  V_DATAREAJ  DATE;
  V_CUSTOPROD NUMBER;
  V_DATAPROD  DATE;
  V_MES       INTEGER;                                                    
  V_ANO       INTEGER;
  V_HORA      VARCHAR (15);
  V_HORA_NOTA VARCHAR (10);
  V_HORA_PRODUCAO  VARCHAR (10);                                            
  V_HORAREAJ  VARCHAR (10);
  V_DATAPAR   DATE;
  V_CPVMEN    INTEGER;  
  V_DATACTRC  DATE;
  V_HORA_CTRC VARCHAR (10);
  V_CUSTOCTRC NUMBER;
  V_CMP       VARCHAR2(1);
  V_WHERE_NOTA VARCHAR2(100);

  V_NOTABONIFICACAO INTEGER := 0;

  TYPE TPCURSOR  IS REF CURSOR;
  CCURSOR  TPCURSOR;
  CSQL VARCHAR2(31000);

  NAO CONSTANT INTEGER := 0;
  SIM CONSTANT INTEGER := 1;
BEGIN
  /***************************************************************************
   PROCEDURE UTILIZADA PARA BUSCAR O CUSTO RETROATIVO DO ITEM, OU SEJA, BUSCA
   O CUSTO EM FUNCAO DA DATA PASSADA POR PARAMETRO. CASO A DATA SEJA PASSA COMO
   NULL, SERA RETORNADO O VALOR ATUAL DO CUSTO.
   @AUTOR: RONALDO CESAR BIM
  ****************************************************************************/
  V_CUSTO          := 0;                        
  V_DATA           := NULL;
  V_HORA           := NULL;                                   
  V_CUSTOREAJ      := 0;
  V_DATAREAJ       := NULL;
  O_NCUSTO         := NULL;
  /*SOMENTE ENTRA APURA O CUSTO DA NFITEMCUSTO SE FOR PASSADA UMA DATA E ESTA NAO SEJA A DATA ATUAL OU DE FIM DE MES,
    DESDE QUE NAO TENHA SIDO PASSADO A HORA*/
  BEGIN                                 
    SELECT USACUSTOCPV INTO  V_CPVMEN        
      FROM PCONFPAD WHERE EMPRESA = I_PNESTAB;
  END;
  IF (V_CPVMEN = 1) THEN 
    IF (I_PDDATA IS NULL) THEN
      V_DATAPAR := SYSDATE;
    ELSE
      V_DATAPAR := I_PDDATA; 
    END IF;
    V_MES := TO_CHAR (V_DATAPAR, 'MM');
    V_ANO := TO_CHAR (V_DATAPAR, 'YYYY');

    CSQL :=
      'SELECT VALORUNITARIO ' ||
      '  FROM U_CPVMEN ' ||
      ' WHERE ESTAB = :ESTAB ' ||
      '   AND ITEM = :ITEM ' ||
      '   AND ANO = :ANO ' ||
      '   AND MES = :MES ' ||
      '   AND (EXISTS (SELECT * FROM U_CONFIGCPV WHERE CODIGOCUSTO = :CODIGOCUSTO)) ';

    OPEN CCURSOR FOR CSQL USING I_PNESTAB, I_PNITEM, V_ANO, V_MES, I_PNCODIGOCUSTO;      
    LOOP
      FETCH CCURSOR INTO O_NCUSTO;        
        EXIT WHEN CCURSOR%NOTFOUND;
    END LOOP;
  END IF;

  IF (O_NCUSTO IS NULL) THEN
    V_CPVMEN := 0;
    O_NCUSTO := 0;
  END IF;
  V_HORA := I_PHORA;
  IF (I_PHORA IS NULL) THEN
    V_HORA := '23:59:59';
  END IF;
  V_WHERE_NOTA := 'NFITEM.HORA <= :DHORA ';
  IF LENGTH(V_HORA) > 10 THEN
    V_WHERE_NOTA := 'COALESCE(NFITEM.HORA_CUSTO, NFITEM.HORA) <= :DHORA ' ;
  END IF;
  SELECT CMP INTO V_CMP FROM ITEMCUSTO WHERE CODIGOCUSTO = I_PNCODIGOCUSTO;
  IF (V_CMP = 'G') AND (I_PDDATA IS NOT NULL) THEN -- G = GERAL PARA TODOS     
    CSQL := '
    SELECT NCUSTO FROM (
        SELECT * FROM (
            SELECT ITEMCMPNOTA.CUSTO AS NCUSTO,                                              
                   NFITEM.DTEMISSAO AS DTEMISSAO,
                   NFITEM.HORA AS HORA,
                   NFITEM.HORA_CUSTO AS HORA_CUSTO,
                   2 AS PRIORIDADE
              FROM NFITEM
             INNER JOIN ITEMCMPNOTA
                ON (ITEMCMPNOTA.ESTABNOTA = NFITEM.ESTAB)
               AND (ITEMCMPNOTA.SEQNOTA = NFITEM.SEQNOTA)
               AND (ITEMCMPNOTA.SEQNOTAITEM = NFITEM.SEQNOTAITEM)
             WHERE (ITEMCMPNOTA.ITEM = :NITEM)
               AND (ITEMCMPNOTA.ESTAB = :NESTAB)
               AND ((NFITEM.DTEMISSAO < :DDATA) OR ((NFITEM.DTEMISSAO = :DDATA) AND ('|| V_WHERE_NOTA || ')))               
             UNION ALL                     
            SELECT ITEMCUSTOREAJ.VLRNOVOCUSTO AS NCUSTO,
                   ITEMCUSTOREAJ.DTREAJUSTE AS DTEMISSAO,
                   ITEMCUSTOREAJ.HORAREAJUSTE AS HORA,
                   ITEMCUSTOREAJ.HORAREAJUSTE AS HORA_CUSTO,
                   1 AS PRIORIDADE
              FROM ITEMCUSTOREAJ 
             WHERE (ITEMCUSTOREAJ.CODIGOCUSTO = :NCODIGOCUSTO)
               AND (ITEMCUSTOREAJ.ITEM = :NITEM)
               AND (ITEMCUSTOREAJ.ESTAB = :NESTAB) 
               AND ((ITEMCUSTOREAJ.DTREAJUSTE < :DDATA) OR ((ITEMCUSTOREAJ.DTREAJUSTE = :DDATA) AND (ITEMCUSTOREAJ.HORAREAJUSTE  <= :DHORA))) 
        )
          ORDER BY DTEMISSAO DESC, HORA DESC, PRIORIDADE ASC, HORA_CUSTO DESC)
     WHERE ROWNUM = 1';                                          
                                  
    OPEN CCURSOR FOR CSQL USING I_PNITEM, I_PNESTAB, I_PDDATA, I_PDDATA, V_HORA, I_PNCODIGOCUSTO, I_PNITEM, I_PNESTAB, I_PDDATA, I_PDDATA, V_HORA;
    FETCH CCURSOR INTO O_NCUSTO;                                                                                                                 

    RETURN O_NCUSTO;
  END IF;

  IF (COALESCE(V_CPVMEN, 0) = 0) THEN
    /* ALIMENTA AS VARIAVEIS DE MES E ANO */
    V_MES := TO_CHAR (I_PDDATA, 'MM');
    V_ANO := TO_CHAR (I_PDDATA, 'YYYY');
    V_WHERE_NOTA := 'NFITEMCUSTO.HORA <= :DHORA ';
    IF LENGTH(V_HORA) > 10 THEN
      V_WHERE_NOTA := 'COALESCE(NFITEMCUSTO.HORA_CUSTO, NFITEMCUSTO.HORA) <= :DHORA ' ;
    END IF;

    CSQL := 'SELECT CUSTO, DATA, HORA, COALESCE(ITEMBONIFICADO, 0 ) AS CUSTOBONIFICACAO
            FROM NFITEMCUSTO 
            WHERE (NFITEMCUSTO.ESTAB = :NESTAB)
              AND (NFITEMCUSTO.ITEM = :NITEM)
              AND (NFITEMCUSTO.CODIGOCUSTO = :NCODIGOCUSTO)
              AND (NFITEMCUSTO.DATA < :DDATA OR (NFITEMCUSTO.DATA = :DDATA AND '|| V_WHERE_NOTA || '))
              AND EXISTS (SELECT 0 FROM NFCAB WHERE NFCAB.ESTAB= NFITEMCUSTO.ESTAB AND NFCAB.SEQNOTA = NFITEMCUSTO.SEQNOTA 
                            AND(NFCAB.ME_SITUACAO IS NULL OR NFCAB.ME_SITUACAO IN (50,53,55,80)))
            ORDER BY NFITEMCUSTO.DATA DESC, NFITEMCUSTO.HORA DESC, NFITEMCUSTO.HORA_CUSTO DESC, NFITEMCUSTO.SEQNOTA DESC, NFITEMCUSTO.SEQNOTAITEM DESC';
    OPEN CCURSOR FOR CSQL USING I_PNESTAB, I_PNITEM, I_PNCODIGOCUSTO, I_PDDATA, I_PDDATA, V_HORA;
    LOOP
        FETCH CCURSOR INTO V_CUSTO, V_DATA, V_HORA_NOTA, V_NOTABONIFICACAO;
        EXIT;
    END LOOP;
    IF LENGTH(V_HORA) > 10 THEN
      V_HORA := SUBSTR(V_HORA, 1, 8);
    END IF;  
    IF (V_CUSTO IS NULL) THEN
      V_CUSTO          := 0;
    END IF;
    IF (V_DATA IS NULL) THEN
      V_DATA           := TO_DATE ('01.01.0001', 'DD.MM.YYYY');
    END IF;
    IF (V_HORA_NOTA IS NULL) THEN
      V_HORA_NOTA           := '00:00:00';
    END IF;
    /* PEGA O CUSTO DA PRODUC:2O */
    BEGIN
      FOR I IN (SELECT CUSTO, DATA, HORA, CODIGOCUSTO 
        FROM ITEMPRODINTCUSTO
        WHERE (ITEMPRODINTCUSTO.ESTAB = I_PNESTAB)
          AND (ITEMPRODINTCUSTO.ITEM = I_PNITEM)
          AND (ITEMPRODINTCUSTO.CODIGOCUSTO = I_PNCODIGOCUSTO)
          AND (ITEMPRODINTCUSTO.DATA < I_PDDATA OR (ITEMPRODINTCUSTO.DATA = I_PDDATA) AND (ITEMPRODINTCUSTO.HORA <= V_HORA))
        ORDER BY ITEMPRODINTCUSTO.DATA DESC, ITEMPRODINTCUSTO.HORA DESC, ITEMPRODINTCUSTO.SEQUENCIA DESC)
      LOOP
        V_CUSTOPROD := I.CUSTO;
        V_DATAPROD := I.DATA;
        V_HORA_PRODUCAO := I.HORA;
        EXIT;
      END LOOP;
    END;
    IF (V_CUSTOPROD IS NULL) THEN
      V_CUSTOPROD := 0;
    END IF;
    IF (V_DATAPROD IS NULL) THEN
      V_DATAPROD := TO_DATE ('01.01.0001', 'DD.MM.YYYY');  
    END IF;
    IF (V_HORA_PRODUCAO IS NULL) THEN
      V_HORA_PRODUCAO := '00:00:00';
    END IF;
    /* PEGA O CUSTO DO CTRC */
    BEGIN
      FOR I IN (SELECT CUSTO, DATA, HORA, CODIGOCUSTO 
        FROM CTRCNFCABCUSTO
        WHERE (CTRCNFCABCUSTO.ESTAB = I_PNESTAB)
          AND (CTRCNFCABCUSTO.ITEM = I_PNITEM)
          AND (CTRCNFCABCUSTO.CODIGOCUSTO = I_PNCODIGOCUSTO)
          AND (CTRCNFCABCUSTO.DATA < I_PDDATA OR (CTRCNFCABCUSTO.DATA = I_PDDATA) AND (CTRCNFCABCUSTO.HORA <= V_HORA))
        ORDER BY CTRCNFCABCUSTO.DATA DESC, CTRCNFCABCUSTO.HORA DESC, CTRCNFCABCUSTO.SEQCTRCNFCAB DESC)
      LOOP
        V_CUSTOCTRC := I.CUSTO;
        V_DATACTRC := I.DATA;
        V_HORA_CTRC := I.HORA;
        EXIT;
      END LOOP;
    END;
    IF (V_CUSTOCTRC IS NULL) THEN
      V_CUSTOCTRC := 0;
    END IF;
    IF (V_DATACTRC IS NULL) THEN
      V_DATACTRC := TO_DATE ('01.01.0001', 'DD.MM.YYYY');  
    END IF;
    IF (V_HORA_CTRC IS NULL) THEN
      V_HORA_CTRC := '00:00:00';
    END IF;
    /* PEGA O VALOR DO ULTIMO REAJUSTE  */
    BEGIN
      SELECT VLRNOVOCUSTO,
             DTREAJUSTE,
             HORAREAJUSTE
        INTO V_CUSTOREAJ,
             V_DATAREAJ,
             V_HORAREAJ
      FROM (
        SELECT   VLRNOVOCUSTO,
                 DTREAJUSTE, 
                 HORAREAJUSTE
            FROM ITEMCUSTOREAJ
           WHERE (ITEMCUSTOREAJ.ESTAB = I_PNESTAB)
                 AND (ITEMCUSTOREAJ.ITEM = I_PNITEM)
                 AND (ITEMCUSTOREAJ.CODIGOCUSTO = I_PNCODIGOCUSTO)
                 AND ((ITEMCUSTOREAJ.DTREAJUSTE < I_PDDATA) 
                  OR ((ITEMCUSTOREAJ.DTREAJUSTE = I_PDDATA) AND (ITEMCUSTOREAJ.HORAREAJUSTE <= V_HORA)))
           ORDER BY ITEMCUSTOREAJ.DTREAJUSTE DESC, ITEMCUSTOREAJ.HORAREAJUSTE DESC)
      WHERE (ROWNUM = 1);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        NULL;
    END;
    IF (V_CUSTOREAJ IS NULL) THEN
      V_CUSTOREAJ := 0;
    END IF;
    IF (V_DATAREAJ IS NULL) THEN
      V_DATAREAJ := TO_DATE ('01.01.0001', 'DD.MM.YYYY');  
    END IF;
    /*PRIMEIRO COMPARA O ULTIMO CUSTO DAS NOTAS COM O ULTIMO CUSTO DA PRODUCAO, SE A DATA DO ULTIMO CUSTO
      DA PRODUCAO FOR MAIOR OU IGUAL A DATA DO ULTIMO CUSTO DA NOTA. PREVALECE O CUSTO DA PRODUCAO*/
    V_HORA := V_HORA_NOTA;
    IF (V_DATAPROD > V_DATA) OR
       ((V_DATAPROD = V_DATA) AND (V_HORA_PRODUCAO >= V_HORA)) THEN
       V_DATA := V_DATAPROD;
       V_CUSTO := V_CUSTOPROD;
       V_HORA := V_HORA_PRODUCAO;
       V_NOTABONIFICACAO := NAO;
    END IF;
    /*COMPARA O ULTIMO CUSTO DAS NOTAS COM O ULTIMO CUSTO DO CTRC, SE A DATA DO ULTIMO CUSTO
      DO CTRC FOR MAIOR OU IGUAL A DATA DO ULTIMO CUSTO DA NOTA. PREVALECE O CUSTO DO CTRC*/
    IF (V_DATACTRC > V_DATA) OR
       ((V_DATACTRC = V_DATA) AND (V_HORA_CTRC >= V_HORA)) THEN
       V_DATA := V_DATACTRC;
       V_CUSTO := V_CUSTOCTRC;
       V_HORA := V_HORA_CTRC;
       V_NOTABONIFICACAO := NAO;
    END IF;
    /* SE A DATA DO ULTIMO REAJUSTE FOR MAIOR IGUAL A AO ULTIMO CUSTO DAS NOTAS,
       ENTAO CONSIDERA O CUSTO DO REAJUSTE */
    IF ((V_DATAREAJ > V_DATA) OR 
      ((V_DATAREAJ = V_DATA) AND (V_HORAREAJ >= V_HORA))) THEN
      O_NCUSTO := COALESCE (V_CUSTOREAJ, 0);
      V_NOTABONIFICACAO := NAO;
    ELSE
      O_NCUSTO := COALESCE (V_CUSTO, 0);
    END IF;
    /* SE MESMO ASSIM O CUSTO ESTIVER ZERADO, TENTA BUSCAR O CUSTO MENSAL ATUAL
      DO ITEM, POIS PODE HAVER EXPORTACAO DO SISTEMA DOS */
    IF (I_PDDATA IS NULL) THEN
      V_MES := TO_CHAR (SYSDATE, 'MM');
      V_ANO := TO_CHAR (SYSDATE, 'YYYY');    
    ELSE
      V_MES := TO_CHAR (I_PDDATA, 'MM');
      V_ANO := TO_CHAR (I_PDDATA, 'YYYY');
    END IF;
    IF (O_NCUSTO = 0) AND ((V_NOTABONIFICACAO = NAO ) OR (I_CONSIDERARNFBONIF_CUSTOZERO = NAO)) THEN
      IF ((I_PDDATA IS NOT NULL) AND ((I_PDDATA <> TO_DATE(CURRENT_DATE) AND (TO_CHAR(I_PDDATA, 'DD') <> TO_CHAR(ULTDIAMESDATA(I_PDDATA), 'DD'))) OR (I_PHORA IS NOT NULL)))THEN
        BEGIN
          SELECT CUSTO
            INTO O_NCUSTO
          FROM (
            SELECT   ITEMCUSTOMEN.CUSTO
                FROM ITEMCUSTOMEN
               WHERE (ITEMCUSTOMEN.ESTAB = I_PNESTAB)
                     AND (ITEMCUSTOMEN.ITEM = I_PNITEM)
                     AND ((ITEMCUSTOMEN.ANO < V_ANO)
                          OR ((ITEMCUSTOMEN.ANO = V_ANO) AND (ITEMCUSTOMEN.MES < V_MES)))
                     AND (ITEMCUSTOMEN.CODIGOCUSTO = I_PNCODIGOCUSTO)
            ORDER BY ITEMCUSTOMEN.ANO DESC, ITEMCUSTOMEN.MES DESC)
          WHERE (ROWNUM = 1);
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            NULL;
        END;
      ELSE
        BEGIN
          SELECT CUSTO
            INTO O_NCUSTO
          FROM (
            SELECT   ITEMCUSTOMEN.CUSTO
                FROM ITEMCUSTOMEN
               WHERE (ITEMCUSTOMEN.ESTAB = I_PNESTAB)
                     AND (ITEMCUSTOMEN.ITEM = I_PNITEM)
                     AND ((ITEMCUSTOMEN.ANO < V_ANO)
                          OR ((ITEMCUSTOMEN.ANO = V_ANO) AND (ITEMCUSTOMEN.MES <= V_MES)))
                     AND (ITEMCUSTOMEN.CODIGOCUSTO = I_PNCODIGOCUSTO)
            ORDER BY ITEMCUSTOMEN.ANO DESC, ITEMCUSTOMEN.MES DESC)
          WHERE (ROWNUM = 1);
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            NULL;
        END;
      END IF;

      IF (O_NCUSTO IS NULL) THEN
        O_NCUSTO := 0;
      END IF;
    END IF;                                                                                                           
  END IF;

  RETURN O_NCUSTO;
END;