WITH 
ESTABORI AS 
(
SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.CONTAMOVLAN CONTAMOVLAN
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.CONTRATO CONTRATO
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.CTRC CTRC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.NFCAB NFCAB
WHERE IDCTB IS NOT NULL AND COALESCE(NFCAB.STATUS,'X') <> 'C'

UNION ALL

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PDUPPAGA PDUPPAGA
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PDUPPAGA PDUPPAGA
WHERE IDCTB IS NOT NULL

UNION ALL

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PDUPREC PDUPREC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.PDUPRECREAJ PDUPRECREAJ
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PLANCA PLANCA
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PPDUPPAG PPDUPPAG
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
EMPRESA AS ESTAB,
IDCTB
FROM
VIASOFT.PRDUPREC PRDUPREC
WHERE IDCTB IS NOT NULL

UNION ALL 

SELECT DISTINCT
ESTAB,
IDCTB
FROM
VIASOFT.ROMA ROMA
WHERE IDCTB IS NOT NULL
),

ESTABORI_UNIF AS (

SELECT 
LISTAGG(DISTINCT FILIAL.ESTAB, ', ') WITHIN GROUP (ORDER BY FILIAL.ESTAB) AS ESTAB,
LISTAGG(DISTINCT FILIAL.REDUZIDO, ', ') WITHIN GROUP (ORDER BY FILIAL.ESTAB) AS FILIAL,
IDCTB AS IDORIGEM
FROM ESTABORI

LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = ESTABORI.ESTAB
GROUP BY IDCTB
),

DEBITO_CREDITO AS 
(
    SELECT
        'DEBITO' AS DEBCRED,
    
   /* CASE 
        WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
        ELSE FILIAL.ESTAB 
    END AS ESTAB, 

    CASE 
        WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
        ELSE FILIAL.REDUZIDO 
    END AS FILIAL,*/

        LANCOCAB.DATALANC,
        LANCOCAB.LANCTO AS LACTOCTB,
        LANCON.COMPLEM AS COMPLEMENTO,
        LANCON.VALOR AS CONTABILDEB,
        0 AS CONTABILCRED,
        LANCOCAB.IDORIGEM AS IDCTB,
        DEBITO.DESCRICAO,
        LANCON.DEBITO AS CONTA,
        CENCUSCE.CENTROCUS,
CASE 
    WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
    ELSE FILIAL_CC.ESTAB 
END  AS ESTAB2,
CASE 
    WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
    ELSE FILIAL_CC.REDUZIDO
END AS FILIAL2,
        CENCUSCE.DESCRICAO AS DESC_CC,
        GRUPO7.DESCRICAO AS DESC_CONTA,
        CONTAMOV.NUMEROCM,
        CONTAMOV.NOME,
        COALESCE(NFCAB.USERID,LANCOCAB.USERID) AS USERID,
        NFCAB.ESTAB AS ESTAB_NOTA,
        NFCAB.SEQNOTA,
        CIDADE.UF AS UF,
        ITEM.DESCRICAO AS ITENS_NOTA,
        NFCAB_U.NRTICKET 
    FROM lancocab
    LEFT JOIN LANCON ON LANCON.ESTAB = LANCOCAB.ESTAB AND LANCON.LANCTO = LANCOCAB.LANCTO
    LEFT JOIN LANCTOAUX ON LANCTOAUX.ESTAB = LANCON.ESTAB AND LANCTOAUX.LANCTO = LANCON.LANCTO AND LANCTOAUX.SEQUENCIA = LANCON.SEQUENCIA
    LEFT JOIN PLACONAN DEBITO ON DEBITO.PLANO = 1 AND DEBITO.REDUZIDA = LANCON.DEBITO
    LEFT JOIN CENCUSCE ON CENCUSCE.CENTROCUS = LANCON.CENCUSDEB AND CENCUSCE.CENCUSCOD = 2
    LEFT JOIN PLACONSI ON PLACONSI.REDSINT = DEBITO.REDSINT AND PLACONSI.PLANO = DEBITO.PLANO
    LEFT JOIN PLACONSI GRUPO7 ON SUBSTR(PLACONSI.CONTABIL, 1, 9) = GRUPO7.CONTABIL AND PLACONSI.PLANO = GRUPO7.PLANO
    LEFT JOIN VIASOFT.NFCAB NFCAB ON NFCAB.IDCTB = LANCOCAB.IDORIGEM  AND COALESCE(NFCAB.STATUS,'X') <> 'C'
  --  LEFT JOIN ESTABORI ON ESTABORI.IDCTB = LANCOCAB.IDORIGEM
  --  LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = COALESCE(ESTABORI.ESTAB,TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0'))) 
    LEFT JOIN VIASOFT.FILIAL FILIAL_CC  ON FILIAL_CC.ESTAB = TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0')) 
    LEFT JOIN VIASOFT.CIDADE CIDADE ON CIDADE.CIDADE = FILIAL_CC.CIDADE
    LEFT JOIN VIASOFT.NFITEM NFITEM ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA AND LANCON.SEQUENCIA = NFITEM.SEQNOTAITEM
    LEFT JOIN VIASOFT.ITEMAGRO ITEM ON ITEM.ITEM = NFITEM.ITEM
    LEFT JOIN VIASOFT.CONTAMOV CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
    LEFT JOIN VIASOFT.NFCAB_U NFCAB_U ON NFCAB_U.ESTAB = NFCAB.ESTAB AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
    
    WHERE 
        (0 IN (:CONTACONTABIL) OR LANCON.DEBITO IN (:CONTACONTABIL))
        AND LANCOCAB.ESTAB = 1
  --AND COALESCE(NFCAB.STATUS, 'X') <> 'C'
        AND LANCOCAB.DATALANC BETWEEN :DTINI AND :DTFIM    
        AND ('T' IN (:GRUPO) OR PLACONSI.GRUPO IN (:GRUPO))
       AND (0 IN (:ESTAB) OR FILIAL_CC.ESTAB IN (:ESTAB) )
        --AND (0 IN (:ESTAB) OR CAST(CENCUSCE.CENTROPAI AS NUMBER) IN (:ESTAB))
         AND ( 'X' IN (:UF) OR CIDADE.UF IN (:UF))
  AND CENCUSDEB IS NOT NULL

        
    UNION ALL
    
    SELECT
        'CREDITO' AS DEBCRED, 
   /* CASE 
        WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
        ELSE FILIAL.ESTAB 
    END AS ESTAB, 
    CASE 
        WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
        ELSE FILIAL.REDUZIDO 
    END AS FILIAL,*/
        LANCOCAB.DATALANC,
        LANCOCAB.LANCTO AS LACTOCTB,
        LANCON.COMPLEM AS COMPLEMENTO,
        0 AS CONTABILDEB,
        LANCON.VALOR AS CONTABILCRED,
        LANCOCAB.IDORIGEM AS IDCTB,
        CREDITO.DESCRICAO,
        LANCON.CREDITO AS CONTA,
        CENCUSCE.CENTROCUS,
CASE 
    WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 1001 
    ELSE FILIAL_CC.ESTAB 
END  AS ESTAB2,
CASE 
    WHEN CAST(CENCUSCE.CENTROPAI AS NUMBER) = 999 THEN 'OS MATRIZ II - SP' 
    ELSE FILIAL_CC.REDUZIDO
END AS FILIAL2,
        CENCUSCE.DESCRICAO AS DESC_CC,
        GRUPO7.DESCRICAO AS DESC_CONTA,
        CONTAMOV.NUMEROCM,
        CONTAMOV.NOME,
        COALESCE(NFCAB.USERID,LANCOCAB.USERID) AS USERID,
        NFCAB.ESTAB AS ESTAB_NOTA,
        NFCAB.SEQNOTA,
        CIDADE.UF AS UF,
        ITEM.DESCRICAO AS ITENS_NOTA,
        NFCAB_U.NRTICKET 
    FROM lancocab
    LEFT JOIN LANCON ON LANCON.ESTAB = LANCOCAB.ESTAB AND LANCON.LANCTO = LANCOCAB.LANCTO
    LEFT JOIN LANCTOAUX ON LANCTOAUX.ESTAB = LANCON.ESTAB AND LANCTOAUX.LANCTO = LANCON.LANCTO AND LANCTOAUX.SEQUENCIA = LANCON.SEQUENCIA
    LEFT JOIN PLACONAN CREDITO ON CREDITO.PLANO = 1 AND CREDITO.REDUZIDA = LANCON.CREDITO
   LEFT JOIN CENCUSCE ON CENCUSCE.CENTROCUS = LANCON.CENCUSCRED AND CENCUSCE.CENCUSCOD = 2
    LEFT JOIN PLACONSI ON PLACONSI.REDSINT = CREDITO.REDSINT AND PLACONSI.PLANO = CREDITO.PLANO
    LEFT JOIN PLACONSI GRUPO7 ON SUBSTR(PLACONSI.CONTABIL, 1, 9) = GRUPO7.CONTABIL AND PLACONSI.PLANO = GRUPO7.PLANO
    LEFT JOIN VIASOFT.NFCAB NFCAB ON NFCAB.IDCTB = LANCOCAB.IDORIGEM AND COALESCE(NFCAB.STATUS,'X') <> 'C'
   -- LEFT JOIN ESTABORI ON ESTABORI.IDCTB = LANCOCAB.IDORIGEM
    --LEFT JOIN VIASOFT.FILIAL FILIAL ON FILIAL.ESTAB = COALESCE(ESTABORI.ESTAB,TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0'))) --CAST(CENCUSCE.CENTROPAI AS NUMBER)
    LEFT JOIN VIASOFT.FILIAL FILIAL_CC ON FILIAL_CC.ESTAB = TO_NUMBER(LTRIM(SUBSTR(CENCUSCE.CENTROCUS, 1, 3), '0')) 
    LEFT JOIN VIASOFT.CIDADE CIDADE ON CIDADE.CIDADE = FILIAL_CC.CIDADE
    LEFT JOIN VIASOFT.NFITEM NFITEM ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA AND LANCON.SEQUENCIA = NFITEM.SEQNOTAITEM
    LEFT JOIN VIASOFT.ITEMAGRO ITEM ON ITEM.ITEM = NFITEM.ITEM
    LEFT JOIN VIASOFT.CONTAMOV CONTAMOV ON CONTAMOV.NUMEROCM = NFCAB.NUMEROCM
    LEFT JOIN VIASOFT.NFCAB_U NFCAB_U ON NFCAB_U.ESTAB = NFCAB.ESTAB AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
    
    WHERE 
        (0 IN (:CONTACONTABIL) OR LANCON.CREDITO IN (:CONTACONTABIL))
        AND LANCOCAB.ESTAB = 1
 -- AND COALESCE(NFCAB.STATUS, 'X') <> 'C'
        AND LANCOCAB.DATALANC BETWEEN :DTINI AND :DTFIM    
        AND ('T' IN (:GRUPO) OR PLACONSI.GRUPO IN (:GRUPO))
    AND (0 IN (:ESTAB) OR FILIAL_CC.ESTAB IN (:ESTAB) )
       -- AND (0 IN (:ESTAB) OR CAST(CENCUSCE.CENTROPAI AS NUMBER) IN (:ESTAB))
         AND ( 'X' IN (:UF) OR CIDADE.UF IN (:UF))
  AND  CENCUSCRED IS NOT NULL
),

LANCAMENTOS AS (

    SELECT
    ESTABORI_UNIF.ESTAB,
    ESTABORI_UNIF.FILIAL,
    DEBITO_CREDITO.*
    FROM DEBITO_CREDITO
    
    LEFT JOIN ESTABORI_UNIF ON ESTABORI_UNIF.IDORIGEM = DEBITO_CREDITO.IDCTB
),

HISTORICO_CTE AS (
    SELECT
        NFCABAGRFIN.ESTAB,
        NFCABAGRFIN.SEQNOTA,
        COALESCE(PDUPPAGA.HISTORICO, PDUPREC.HISTORICO, CONTAMOVLAN.HISTORICO) AS HISTORICO,
        ROW_NUMBER() OVER (PARTITION BY NFCABAGRFIN.ESTAB, NFCABAGRFIN.SEQNOTA ORDER BY COALESCE(PDUPPAGA.HISTORICO, PDUPREC.HISTORICO, CONTAMOVLAN.HISTORICO)) AS RN
    FROM 
        VIASOFT.NFCABAGRFIN NFCABAGRFIN
    JOIN VIASOFT.NFCAB NFCAB ON NFCAB.ESTAB = NFCABAGRFIN.ESTAB AND NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA 
    LEFT JOIN VIASOFT.AGRFINDUPREC AGRFINDUPREC ON AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.PDUPREC PDUPREC ON PDUPREC.EMPRESA = AGRFINDUPREC.ESTAB AND PDUPREC.DUPREC = AGRFINDUPREC.DUPREC
    LEFT JOIN VIASOFT.AGRFINDUPPAG AGRFINDUPPAG ON AGRFINDUPPAG.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.PDUPPAGA PDUPPAGA ON PDUPPAGA.EMPRESA = AGRFINDUPPAG.ESTAB AND PDUPPAGA.DUPPAG = AGRFINDUPPAG.DUPPAG AND PDUPPAGA.FORNECEDOR = AGRFINDUPPAG.FORNECEDOR
    LEFT JOIN VIASOFT.AGRFINCTAMOV AGRFINCTAMOV ON AGRFINCTAMOV.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    LEFT JOIN VIASOFT.CONTAMOVLAN CONTAMOVLAN ON CONTAMOVLAN.ESTAB = AGRFINCTAMOV.ESTAB AND CONTAMOVLAN.NUMEROCM = AGRFINCTAMOV.NUMEROCM AND CONTAMOVLAN.SEQCM = AGRFINCTAMOV.SEQCM
    WHERE
        NFCAB.DTENTSAI BETWEEN :DTINI AND :DTFIM    
        AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
       -- AND ( 'X' IN (:UF) OR CIDADE.UF IN (:UF))
),

ITENS AS (
    SELECT 
        NFCAB.ESTAB,
        NFCAB.SEQNOTA,
        LISTAGG(DISTINCT U_GESTOQUE.DESCRICAO, ', ') WITHIN GROUP (ORDER BY U_GESTOQUE.DESCRICAO) AS DESCRICOES
    FROM
        VIASOFT.NFITEM NFITEM
    JOIN VIASOFT.ITEMAGRO ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM
    JOIN VIASOFT.ITEMGRUPO_U ITEMGRUPO_U ON ITEMGRUPO_U.GRUPO = ITEMAGRO.GRUPO
    JOIN VIASOFT.U_GESTOQUE U_GESTOQUE ON U_GESTOQUE.U_GESTOQUE_ID = ITEMGRUPO_U.U_GESTOQUE_ID
    JOIN VIASOFT.NFCAB NFCAB ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA   
    WHERE
        NFCAB.DTENTSAI BETWEEN :DTINI AND :DTFIM    
        AND (0 IN (:ESTAB) OR NFCAB.ESTAB IN (:ESTAB))
        -- AND ( 'X' IN (:UF) OR CIDADE.UF IN (:UF))
    GROUP BY 
        NFCAB.ESTAB,
        NFCAB.SEQNOTA
),

DEPARA AS (
    SELECT DISTINCT
        U_PCC.REDUZIDA AS DEPARA,
        U_PCC.CONTA AS DESC_DE_PARA,
        U_TIPONAT.DESCRICAO AS NATUREZA,
        U_TIPOUNIDADE.DESCRICAO AS UNIDADE
    FROM
        U_PCC
    LEFT JOIN U_TIPONAT ON U_TIPONAT.U_TIPONAT_ID = U_PCC.U_TIPONAT_ID
    LEFT JOIN U_TIPOUNIDADE ON U_TIPOUNIDADE.U_TIPOUNIDADE_ID = U_PCC.U_TIPOUNIDADE_ID
    WHERE 
        OSPLANO = '1#1'
)

SELECT
    DADOS.DEBCRED, 
    DADOS.ESTAB,
    DADOS.FILIAL,
    DADOS.UF,
    DADOS.DATALANC,
    DADOS.LACTOCTB,
    DADOS.COMPLEMENTO,
   SUM( (TO_NUMBER(DADOS.CONTABILDEB) - TO_NUMBER(DADOS.CONTABILCRED)) )AS VALOR,
    DADOS.IDCTB,
    DEPARA.DESC_DE_PARA,
    DADOS.CONTA,
    DADOS.CENTROCUS,
    DADOS.ESTAB2,
    DADOS.FILIAL2,
    DADOS.DESC_CC,
    DADOS.DESC_CONTA,
    DADOS.NUMEROCM,
    DADOS.NOME,
   'Tkt-'||NRTICKET||' '||HISTORICO.HISTORICO as HISTORICO,
   -- HISTORICO.HISTORICO,
  --  NRTICKET,
    DADOS.USERID,
    ITENS.DESCRICOES AS DES_ITENS,
    DEPARA.UNIDADE,
    DEPARA.NATUREZA
    
FROM (
    SELECT * FROM LANCAMENTOS
) DADOS
LEFT JOIN (
    SELECT ESTAB, SEQNOTA, HISTORICO
    FROM HISTORICO_CTE
    WHERE RN = 1
) HISTORICO ON HISTORICO.ESTAB = DADOS.ESTAB_NOTA AND HISTORICO.SEQNOTA = DADOS.SEQNOTA
LEFT JOIN ITENS ON ITENS.ESTAB = DADOS.ESTAB_NOTA AND ITENS.SEQNOTA = DADOS.SEQNOTA
LEFT JOIN DEPARA ON TO_CHAR(DEPARA.DEPARA) = TO_CHAR(DADOS.CONTA)

WHERE
    (DADOS.CONTA <> 0)
    --AND DADOS.COMPLEMENTO <> 'Transferência de Resultado de Exercício'
GROUP BY 
    DADOS.DEBCRED, 
    DADOS.ESTAB,
    DADOS.FILIAL,
    DADOS.UF,
    DADOS.DATALANC,
    DADOS.LACTOCTB,
    DADOS.COMPLEMENTO,
   -- DADOS.CONTABILDEB,
 --   DADOS.CONTABILCRED,
    DADOS.IDCTB,
    DADOS.DESCRICAO,
    DADOS.CONTA,
    DADOS.CENTROCUS,
    DADOS.ESTAB2,
    DADOS.FILIAL2,
    DADOS.DESC_CC,
    DADOS.DESC_CONTA,
    DADOS.NUMEROCM,
    DADOS.NOME,
    HISTORICO.HISTORICO,
    DADOS.USERID,
    ITENS.DESCRICOES,
    DEPARA.NATUREZA,
    DEPARA.UNIDADE,
    DEPARA.DESC_DE_PARA,
    NRTICKET
