create or replace TRIGGER "VIASOFT"."OS_ALTIPOTR" 
BEFORE INSERT 
ON VIASOFT.U_TIPOTRIGO FOR EACH ROW

DECLARE 
DTINVENTARIO DATE;



BEGIN

        IF INSERTING THEN 
        
        SELECT dtinventarioestoque INTO DTINVENTARIO FROM PCONFPAD WHERE PCONFPAD.EMPRESA=:NEW.ESTAB;
    
        UPDATE PCONFPAD SET PCONFPAD.dtinventarioestoque=NULL WHERE PCONFPAD.EMPRESA=:NEW.ESTAB;

        UPDATE NFITEM SET nfitem.finatiporoma = :NEW.TIPO WHERE NFITEM.ESTAB=:NEW.ESTAB AND NFITEM.SEQNOTA=:NEW.SEQNOTA AND NFITEM.SEQNOTAITEM=:NEW.SEQNOTAITEM;
        UPDATE ROMA SET ROMA.TIPO =:NEW.TIPO WHERE ROMA.ESTAB=:NEW.ESTAB AND ROMA.ROMANEIO=:NEW.ROMANEIO;
        
        UPDATE PCONFPAD SET PCONFPAD.dtinventarioestoque=DTINVENTARIO WHERE PCONFPAD.EMPRESA=:NEW.ESTAB;
        

        END IF;

        EXCEPTION
        WHEN NO_DATA_FOUND THEN
        NULL;

END;
