create or replace TRIGGER OS_ADIANTAMENTO_CTR
BEFORE UPDATE OR UPDATE
ON VIASOFT.CONTRATO_U FOR EACH ROW

DECLARE
V_HIST VARCHAR2(80);
V_PESSOA NUMBER;
V_CHAVE VARCHAR2(50);
V_CONTADOR NUMBER;
V_TIPO VARCHAR2(10);
V_DEBCRED VARCHAR(5);
V_VALOR NUMBER;
V_VENCTO DATE;
V_USER VARCHAR2(60);
V_VALIDACTR NUMBER;
V_BANCO VARCHAR2(20); 
V_AGENCIA VARCHAR2(20); 
V_CONTA VARCHAR2(20);
V_PIX VARCHAR2(20); 
BEGIN

    V_HIST := 'Gerado via Trigger: CTR:'|| :NEW.CONTRATO ||' Estab:'|| :NEW.ESTAB;

    BEGIN
        SELECT DISTINCT
        1 INTO V_VALIDACTR
        FROM CONTAMOVLAN
        WHERE 
        CONTAMOVLAN.HISTORICO = V_HIST;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        V_VALIDACTR := 0;
    END;

    IF ((:NEW.OS_STATUS_AD = 'PENDENTE PAGAMENTO' AND NVL(:OLD.OS_STATUS_AD,'N') <> 'PENDENTE PAGAMENTO')
        OR (:NEW.OS_STATUS_AD = 'RECEBIMENTO PENDENTE' AND NVL(:OLD.OS_STATUS_AD,'N') <> 'RECEBIMENTO PENDENTE'))
        AND V_VALIDACTR = 0
    THEN

        -- VALIDAR TIPO DE CONTAMOVIMENTO
        IF :NEW.OS_STATUS_AD = 'PENDENTE PAGAMENTO' THEN 
            V_TIPO := 'AFG'; 
            V_DEBCRED := 'D';
        ELSE V_TIPO := 'ACB';
        V_DEBCRED := 'C';
        END IF;

        -- BUSCANDO COD PESSOA E VENCIMENTO
        SELECT NUMEROCM
        INTO V_PESSOA
        FROM CONTRATO WHERE
        CONTRATO.CONTRATO = :NEW.CONTRATO
        AND CONTRATO.ESTAB = :NEW.ESTAB;

        -- PEGAR INFO DO ADIANTAMENTO
        BEGIN
            SELECT PIX, BANCO, AGENCIA, CONTA, VALOR, NVL(USERID_ALT,USERID), DT_VENCTO
                INTO V_PIX, V_BANCO, V_AGENCIA, V_CONTA, V_VALOR, V_USER,V_VENCTO
            FROM U_ADIANTAMENTOS
            WHERE U_ADIANTAMENTOS.ESTAB = :NEW.ESTAB
            AND U_ADIANTAMENTOS.CONTRATO = :NEW.CONTRATO;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    V_BANCO := NULL;
                    V_AGENCIA := NULL;
                    V_CONTA := NULL;
                    V_PIX := NULL;
                    V_VALOR := NULL;
                    V_USER  := NULL;
            END;

        -- VERIFICAR SE TEM PRIMARY KEY PARA CONTAMOVLAN
        V_CHAVE := 'NUMEROCM=' || V_PESSOA || ';ESTAB=' || :NEW.ESTAB;
        BEGIN
            SELECT ID_INT
            INTO V_CONTADOR
            FROM SEQPRIMARYKEY
            WHERE CHAVEVALOR = V_CHAVE
            AND TABELA = 'CONTAMOVLAN';
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
            V_CONTADOR := 0;
        END;

        IF V_CONTADOR = 0 THEN
            INSERT INTO SEQPRIMARYKEY (TABELA,CHAVEVALOR,ID_INT) VALUES ('CONTAMOVLAN',V_CHAVE,1);
            V_CONTADOR := 1;
        ELSE
            UPDATE SEQPRIMARYKEY 
                SET ID_INT = ID_INT + 1 
            WHERE CHAVEVALOR = V_CHAVE
            AND TABELA = 'CONTAMOVLAN'
            RETURNING ID_INT INTO V_CONTADOR;
        END IF;

        INSERT INTO CONTAMOVLAN (NUMEROCM,ESTAB,SEQCM,DTMOVTO,TIPO,DEBCRED,MOEDA,VALOR,VENCIMENTO,SITUACAO,HISTORICO,USERID)
            VALUES (V_PESSOA,:NEW.ESTAB,V_CONTADOR,TRUNC(CURRENT_DATE),V_TIPO,V_DEBCRED,0,V_VALOR,TRUNC(V_VENCTO),'P',
            'Gerado via Trigger: CTR:'|| :NEW.CONTRATO ||' Estab:'|| :NEW.ESTAB,V_USER
            );

        INSERT INTO CONTAMOVLAN_U (NUMEROCM,ESTAB,SEQCM,BANCO,OS_AGENCIA,OS_CONTA,PIX,VLRPAGO)
            VALUES (V_PESSOA,:NEW.ESTAB,V_CONTADOR,V_BANCO,V_AGENCIA,V_CONTA,V_PIX,V_VALOR);


    END IF;


END;