create or replace TRIGGER OS_INSEREDPLCM 
BEFORE INSERT ON CONTAMOVLAN FOR EACH ROW
DECLARE
V_DOC VARCHAR2(20);
V_VALOR NUMBER;
BEGIN

IF (:NEW.TIPO = 'AFGR') THEN

    V_DOC := 'AFGR-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR
    )

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S'
    );

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );

   END IF;

   IF (:NEW.TIPO = 'AFLG') THEN

   V_DOC := 'AFLG-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );

   END IF;


  IF (:NEW.TIPO = 'AFI') THEN

  V_DOC := 'AFI-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );


   END IF;

IF (:NEW.TIPO = 'AFG') THEN

V_DOC := 'AFG-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,426, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );


   END IF;

   IF (:NEW.TIPO = 'AFGC') THEN

V_DOC := 'AFGC-'||(GEN_ADTOCM.nextval);

  BEGIN
    SELECT VALOR INTO V_VALOR FROM U_CONTAMOVLAN_AD
    WHERE U_CONTAMOVLAN_AD.ESTAB = :NEW.ESTAB
    AND U_CONTAMOVLAN_AD.SEQCM = :NEW.SEQCM
    AND U_CONTAMOVLAN_AD.NUMEROCM = :NEW.NUMEROCM
    AND U_CONTAMOVLAN_AD.TIPO = 'AFGC'
    ORDER BY ID DESC
    FETCH FIRST 1 ROW ONLY;
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
            V_VALOR := 0;
  END;

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,V_VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,V_VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,520, 14, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    V_VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    V_VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );


   END IF;

     IF (:NEW.TIPO = 'DJRE') THEN

     V_DOC := 'DJRE-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,445, 2, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );


   END IF;  

    IF (:NEW.TIPO = 'ACT') THEN

    V_DOC := 'ACT-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,420, 31, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );


   END IF;

   IF  (:NEW.TIPO = 'ADG') THEN

   V_DOC := 'ADG-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,429, 19, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );

     END IF;

   IF  (:NEW.TIPO = 'ACC') THEN
   INSERT INTO PDUPREC
    (PDUPREC.EMPRESA, PDUPREC.ESTABCLIENTE,PDUPREC.CLIENTE,PDUPREC.DUPREC,
    PDUPREC.DTEMISSAO, PDUPREC.VALOR, PDUPREC.ANOCOMPET,PDUPREC.MESCOMPET,
    PDUPREC.INCMANUT, PDUPREC.MOEDA,PDUPREC.DTVENCTO,PDUPREC.FATURA,PDUPREC.VALORFATURA, 
    PDUPREC.HISTORICO,PDUPREC.ANALITICA,PDUPREC.SITUACAO,PDUPREC.QUITADA,
    PDUPREC.USERID, PDUPREC.DTBASEJUROS,PDUPREC.ESTABANALITICA,PDUPREC.CONTABILIZAR,PDUPREC.NRODOCTOORIGEM )

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'ACC-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACC-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,4, 30, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF;  

     IF  (:NEW.TIPO = 'ACGC') THEN

     BEGIN
      SELECT VALOR INTO V_VALOR FROM U_CONTAMOVLAN_AD
      WHERE U_CONTAMOVLAN_AD.ESTAB = :NEW.ESTAB
      AND U_CONTAMOVLAN_AD.SEQCM = :NEW.SEQCM
      AND U_CONTAMOVLAN_AD.NUMEROCM = :NEW.NUMEROCM
      AND U_CONTAMOVLAN_AD.TIPO = 'ACGC'
      ORDER BY ID DESC
      FETCH FIRST 1 ROW ONLY;
      EXCEPTION
              WHEN NO_DATA_FOUND THEN
              V_VALOR := 0;
    END;

   INSERT INTO PDUPREC
    (PDUPREC.EMPRESA, PDUPREC.ESTABCLIENTE,PDUPREC.CLIENTE,PDUPREC.DUPREC,
    PDUPREC.DTEMISSAO, PDUPREC.VALOR, PDUPREC.ANOCOMPET,PDUPREC.MESCOMPET,
    PDUPREC.INCMANUT, PDUPREC.MOEDA,PDUPREC.DTVENCTO,PDUPREC.FATURA,PDUPREC.VALORFATURA, 
    PDUPREC.HISTORICO,PDUPREC.ANALITICA,PDUPREC.SITUACAO,PDUPREC.QUITADA,
    PDUPREC.USERID, PDUPREC.DTBASEJUROS,PDUPREC.ESTABANALITICA,PDUPREC.CONTABILIZAR,PDUPREC.NRODOCTOORIGEM )

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'ACGC-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    V_VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACGC-'||(GEN_ADTOCM.nextval),V_VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,523, 30, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF;

   IF  (:NEW.TIPO = 'PCLD') THEN
   INSERT INTO PDUPREC
    (PDUPREC.EMPRESA, PDUPREC.ESTABCLIENTE,PDUPREC.CLIENTE,PDUPREC.DUPREC,
    PDUPREC.DTEMISSAO, PDUPREC.VALOR, PDUPREC.ANOCOMPET,PDUPREC.MESCOMPET,
    PDUPREC.INCMANUT, PDUPREC.MOEDA,PDUPREC.DTVENCTO,PDUPREC.FATURA,PDUPREC.VALORFATURA, 
    PDUPREC.HISTORICO,PDUPREC.ANALITICA,PDUPREC.SITUACAO,PDUPREC.QUITADA,
    PDUPREC.USERID, PDUPREC.DTBASEJUROS,PDUPREC.ESTABANALITICA,PDUPREC.CONTABILIZAR,PDUPREC.NRODOCTOORIGEM )

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, 'PCLD-'||(GEN_ADTOCM.nextval), :NEW.DTMOVTO,
    :NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,'ACC-'||(GEN_ADTOCM.nextval),:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,337, 12, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM );
     END IF;

  IF (:NEW.TIPO = 'CCPR') THEN

  V_DOC := 'CCPR-'||(GEN_ADTOCM.nextval);

   INSERT INTO PDUPPAGA
    (PDUPPAGA.EMPRESA, PDUPPAGA.ESTABFORNECEDOR,PDUPPAGA.FORNECEDOR,PDUPPAGA.DUPPAG,
    PDUPPAGA.DTEMISSAO,PDUPPAGA.DTENTRADA, PDUPPAGA.VALOR, PDUPPAGA.ANOCOMPET,PDUPPAGA.MESCOMPET,
    PDUPPAGA.INCMANUT, PDUPPAGA.MOEDA,PDUPPAGA.DTVENCTO,PDUPPAGA.FATURA,PDUPPAGA.VALORFATURA, 
    PDUPPAGA.HISTORICO,PDUPPAGA.ANALITICA, PDUPPAGA.SITUACAO,PDUPPAGA.QUITADA,
    PDUPPAGA.USERID, PDUPPAGA.DTBASEJUROS,PDUPPAGA.ESTABANALITICA,PDUPPAGA.CONTABILIZAR,PDUPPAGA.NRODOCTOORIGEM,
    PDUPPAGA.VLRAUTPAGAR,PDUPPAGA.DTPREVPAGTO,PDUPPAGA.USERIDAUTPAG,PDUPPAGA.DTULTAUTPAG,PDUPPAGA.DEPOSITAR)

    VALUES(:NEW.ESTAB, 1, :NEW.NUMEROCM, V_DOC, :NEW.DTMOVTO,
    :NEW.DTMOVTO,:NEW.VALOR, 19,11,'N',:NEW.MOEDA, :NEW.VENCIMENTO,V_DOC,:NEW.VALOR,
    'REF:'||:NEW.HISTORICO||''||:NEW.HISTORICO2,510, 2, 'N',:NEW.USERID, :NEW.VENCIMENTO,1,'N',:NEW.ESTAB||:NEW.NUMEROCM||:NEW.SEQCM,
    :NEW.VALOR, :NEW.VENCIMENTO, :NEW.USERID,:NEW.VENCIMENTO,'S');

    INSERT INTO AUTDUPPAGA 
    (IDAUT,DTAUT,ESTAB,DUPPAG,ESTABFORNECEDOR,FORNECEDOR,VALORAUT,USERIDAUT,TEMSALDOAUT,USERIDULTALT,DTULTALT) 
    VALUES 
    (GEN_AUTDUPPAGA_IDAUT.nextval,
    CURRENT_TIMESTAMP,
    :NEW.ESTAB,
    V_DOC,
    1,
    :NEW.NUMEROCM,
    :NEW.VALOR,
    :NEW.USERID,
    'S',
    :NEW.USERID,
    CURRENT_TIMESTAMP
    );

   END IF;

END;