create or replace TRIGGER "VIASOFT"."OS_NFITEMTXSERVICO" 
BEFORE INSERT OR UPDATE ON VIASOFT.NFITEMTXSERVICO FOR EACH ROW
DECLARE
TCOB NUMBER;
V_TAB NUMBER := 0;
BEGIN

    SELECT REACOBFINLEITURA INTO TCOB FROM NFCAB

                INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM=NFCAB.NUMEROCM

                WHERE NFCAB.ESTAB=:NEW.ESTAB AND NFCAB.SEQNOTA=:NEW.SEQNOTA;

                 TCOB := COALESCE(TCOB,0);

    
    IF :NEW.ITEM IN (1,6) AND :NEW.ESTAB IN (36,37,66) AND TCOB=0 AND :NEW.SERVICO=30 THEN 
    :NEW.SITUACAO:='C';
    END IF;
    
    IF :NEW.ITEM IN (1,3,6,24)AND :NEW.ESTAB NOT IN (36,37,66) AND TCOB=0 AND :NEW.SERVICO=30 THEN   
    :NEW.SITUACAO:='C';
    END IF;
    
    IF :NEW.ITEM IN (40) AND TCOB=0 AND :NEW.SERVICO=30 THEN    
    :NEW.SITUACAO:='C';
    
    END IF;
    
    IF :NEW.SERVICO = 30 THEN
    
        BEGIN
        SELECT OS_TABUMIDADE
        INTO V_TAB
        FROM NFITEM
        INNER JOIN NFCAB ON
            NFCAB.ESTAB = NFITEM.ESTAB
            AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
        INNER JOIN CONTRATOROMAITE ON
            NFITEM.ESTAB = CONTRATOROMAITE.ESTABROMA
            AND NFITEM.ROMANEIO = CONTRATOROMAITE.ROMANEIO
            AND NFCAB.NUMEROCM = CONTRATOROMAITE.NUMEROCM
        INNER JOIN CONTRATO_U ON
            CONTRATO_U.ESTAB = CONTRATOROMAITE.ESTAB
            AND CONTRATO_U.CONTRATO = CONTRATOROMAITE.CONTRATO
        WHERE 
            NFITEM.ESTAB = :NEW.ESTAB
            AND NFITEM.SEQNOTA = :NEW.SEQNOTA
            AND NFITEM.SEQNOTAITEM = :NEW.SEQNOTAITEM;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_TAB := 0;
        END;
        
        
        IF INSERTING THEN
        
            IF V_TAB <> 0 AND NVL(:NEW.TABUMISERV,0) <> V_TAB THEN
                :NEW.TABUMISERV := V_TAB;
            END IF;
        
        ELSIF UPDATING THEN
        
            IF V_TAB <> 0 AND NVL(:NEW.TABUMISERV,0) <> V_TAB AND V_TAB <> NVL(:OLD.TABUMISERV,0) THEN
                :NEW.TABUMISERV := V_TAB;
            END IF;
    
        END IF;
    END IF;

     EXCEPTION
           WHEN NO_DATA_FOUND THEN
        NULL;
    END;