SELECT DISTINCT
'ROMANEIOS PENDENTE' AS TIP,
FILIAL.ESTAB,
ROMACLASSNOME.CLASSIFICACAO,
CASE WHEN ROMA.ITEM = 2 THEN ROMACLASSNOME.descricaoclassificacao ELSE ITEMAGRO.DESCRICAO END AS DESCRICAOCLASSIFICACAO,
ITEMAGRO.ITEM,
ITEMAGRO.DESCRICAO PRODUTO,
ROMACFG.ROMANEIOCONFIG AS IDCONFIG,
'ROMANEIOS' AS OPERACAO,

CONTAMOV.NUMEROCM,
ROMA.NUMEROCM||' - '||CONTAMOV.NOME AS PESSOA,
CASE WHEN ROMA.SEQENDERECO IS NOT NULL THEN ROMA.SEQENDERECO ELSE 0 END AS IDENDERECO,
CASE WHEN ROMA.SEQENDERECO IS NOT NULL THEN ROMA.SEQENDERECO||' - '||ENDERECO.ENDERECO ELSE 0||' - '||CONTAMOV.ENDERECO END AS ENDERECO,
ROMA.DTEMISSAO AS DTEMISSAO,
ROMA.ROMANEIO AS ROMANEIO,
ROMA.SEQDESMEMBRADO,
COALESCE(ROMA.ROMAONOFF,0) AS OFF,

ROMA.PLACA AS PLACA,
(COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) AS PBRUTO,
COALESCE(ROMA.PH,0) AS PH,
COALESCE(ROMA.FN,0) AS FN,
COALESCE(SUM((SELECT SUM(IMP.REFTABELA) FROM ROMADESC IMP
                WHERE IMP.ESTAB        = ROMA.ESTAB
                  AND IMP.ROMANEIO     = ROMA.ROMANEIO
                  AND IMP.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND IMP.NUMEROCM     = ROMA.NUMEROCM
                  AND IMP.ROMADESC     IN (1,13))),0) AS IMP,

COALESCE(SUM((SELECT SUM(UMID.REFTABELA) FROM ROMADESC UMID
                WHERE UMID.ESTAB        = ROMA.ESTAB
                  AND UMID.ROMANEIO     = ROMA.ROMANEIO
                  AND UMID.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND UMID.NUMEROCM     = ROMA.NUMEROCM
                  AND UMID.ROMADESC     = 2)),0) AS UMID,

COALESCE(SUM((SELECT SUM(ARD.REFTABELA) FROM ROMADESC ARD
                WHERE ARD.ESTAB        = ROMA.ESTAB
                  AND ARD.ROMANEIO     = ROMA.ROMANEIO
                  AND ARD.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND ARD.NUMEROCM     = ROMA.NUMEROCM
                  AND ARD.ROMADESC     = 3)),0) AS ARD,

COALESCE(SUM((SELECT SUM(QUEB.REFTABELA) FROM ROMADESC QUEB
                WHERE QUEB.ESTAB        = ROMA.ESTAB
                  AND QUEB.ROMANEIO     = ROMA.ROMANEIO
                  AND QUEB.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND QUEB.NUMEROCM     = ROMA.NUMEROCM
                  AND QUEB.ROMADESC     = 4)),0) AS QUEB,

COALESCE(SUM((SELECT SUM(ESVER.REFTABELA) FROM ROMADESC ESVER
                WHERE ESVER.ESTAB        = ROMA.ESTAB
                  AND ESVER.ROMANEIO     = ROMA.ROMANEIO
                  AND ESVER.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND ESVER.NUMEROCM     = ROMA.NUMEROCM
                  AND ESVER.ROMADESC     = 5)),0) AS ESVER,

COALESCE(SUM((SELECT SUM(AVAR.REFTABELA) FROM ROMADESC AVAR
                WHERE AVAR.ESTAB        = ROMA.ESTAB
                  AND AVAR.ROMANEIO     = ROMA.ROMANEIO
                  AND AVAR.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND AVAR.NUMEROCM     = ROMA.NUMEROCM
                  AND AVAR.ROMADESC     = 6)),0) AS AVAR,

COALESCE(SUM((SELECT SUM(QUEI.REFTABELA) FROM ROMADESC QUEI
                WHERE QUEI.ESTAB        = ROMA.ESTAB
                  AND QUEI.ROMANEIO     = ROMA.ROMANEIO
                  AND QUEI.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND QUEI.NUMEROCM     = ROMA.NUMEROCM
                  AND QUEI.ROMADESC     = 7)),0) AS QUEI,

COALESCE(SUM((SELECT SUM(MOF.REFTABELA) FROM ROMADESC MOF
                WHERE MOF.ESTAB        = ROMA.ESTAB
                  AND MOF.ROMANEIO     = ROMA.ROMANEIO
                  AND MOF.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND MOF.NUMEROCM     = ROMA.NUMEROCM
                  AND MOF.ROMADESC     = 8)),0) AS MOF,

COALESCE(SUM((SELECT SUM(OUT.REFTABELA) FROM ROMADESC OUT
                WHERE OUT.ESTAB        = ROMA.ESTAB
                  AND OUT.ROMANEIO     = ROMA.ROMANEIO
                  AND OUT.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND OUT.NUMEROCM     = ROMA.NUMEROCM
                  AND OUT.ROMADESC     IN (6,3,5,9))),0) AS OUT,

COALESCE(SUM((SELECT SUM(CARUN.REFTABELA) FROM ROMADESC CARUN
                WHERE CARUN.ESTAB        = ROMA.ESTAB
                  AND CARUN.ROMANEIO     = ROMA.ROMANEIO
                  AND CARUN.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND CARUN.NUMEROCM     = ROMA.NUMEROCM
                  AND CARUN.ROMADESC     = 10)),0) AS CARUN,

(COALESCE(SUM((SELECT SUM(IMP.PERCENTUAL) FROM ROMADESC IMP
                WHERE IMP.ESTAB        = ROMA.ESTAB
                  AND IMP.ROMANEIO     = ROMA.ROMANEIO
                  AND IMP.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND IMP.NUMEROCM     = ROMA.NUMEROCM
                  AND IMP.ROMADESC     IN(1,13))),0) +
COALESCE(SUM((SELECT SUM(UMID.PERCENTUAL) FROM ROMADESC UMID
                WHERE UMID.ESTAB        = ROMA.ESTAB
                  AND UMID.ROMANEIO     = ROMA.ROMANEIO
                  AND UMID.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND UMID.NUMEROCM     = ROMA.NUMEROCM
                  AND UMID.ROMADESC     = 2)),0)) +
COALESCE(SUM((SELECT SUM(OUT.PERCENTUAL) FROM ROMADESC OUT
                WHERE OUT.ESTAB        = ROMA.ESTAB
                  AND OUT.ROMANEIO     = ROMA.ROMANEIO
                  AND OUT.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND OUT.NUMEROCM     = ROMA.NUMEROCM
                  AND OUT.ROMADESC     IN (6,3,5,9))),0) AS DESCONTO,

ROMA.PESOLIQUIDO AS LIQUIDO,

COALESCE(ROMA.FRETE,0) AS FRETE,

COALESCE(ROMA.PESOFRETE,0) AS PESOFRETE,

CONTAMOV.REACOBFINLEITURA,

CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *
COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMATXSERVICO
            INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM

            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM AND
            CONTAMOV.REACOBFINLEITURA           = 0

            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMATXSERVICO.ESTAB           = ROMA.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMA.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C')),0)),60)AS NUMERIC(14,2)) AS SECAGEM,


CASE WHEN ROMATXSERVICOPG.QTDEPAGO > 0 THEN QTDEPAGO ELSE (CAST((DIVIDE(CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *
COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMATXSERVICO
            INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM
            
            

            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM AND
            CONTAMOV.REACOBFINLEITURA  = 0

            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMATXSERVICO.ESTAB           = ROMA.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMA.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C')),0)),60)AS NUMERIC(14,2)) , SUM(ITEMCOTITE.FIXACAO)) * 60) AS NUMERIC(14,0)))END AS SECAGEMKG,
              
                case when filial.estab=6 then  COALESCE(SUM((SELECT SUM(SECDESC.pesocalculado) FROM ROMADESC SECDESC
                WHERE SECDESC.ESTAB        = ROMA.ESTAB
                  AND SECDESC.ROMANEIO     = ROMA.ROMANEIO
                  AND SECDESC.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND SECDESC.NUMEROCM     = ROMA.NUMEROCM
                  AND SECDESC.ROMADESC     IN (11))),0)else 0 end SECAGEMDESC,

            CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *
          COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMATXSERVICO
            INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM

            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM AND
            CONTAMOV.REACOBFINLEITURA           = 1

            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMATXSERVICO.ESTAB           = ROMA.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMA.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C')),0)),60)AS NUMERIC(14,2)) +

CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *

COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMA ROMASERV


            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM


            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN ROMACFG ON ROMACFG.ROMANEIOCONFIG=ROMASERV.ROMANEIOCONFIG

            INNER JOIN u_cobfinroma ON u_cobfinroma.estab = romaserv.estab
                                    and u_cobfinroma.romaneioconfig=romaserv.romaneioconfig

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = u_cobfinroma.tabela

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMASERV.ESTAB           = ROMA.ESTAB
              AND ROMASERV.ROMANEIO        = ROMA.ROMANEIO
              AND ROMASERV.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMASERV.NUMEROCM        = ROMA.NUMEROCM
              AND NOT EXISTS( SELECT * FROM ROMATXSERVICO
              WHERE ROMATXSERVICO.ESTAB           = ROMASERV.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMASERV.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMASERV.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMASERV.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C'))),0)),60)AS NUMERIC(14,2)) AS SECAGEMNF,
0 AS ARMAZ,
    0  AS QUEBQTD,

    CAST (0.0 AS DECIMAL(6,4)) AS TOTALSERV,
    CAST (0.0 AS NUMERIC(14))AS  NOTA,
    CAST (0.0 AS NUMERIC(14)) AS SEQNOTA,
    ROMA.DTEMISSAO AS DTNF,
    ROMA.PESOLIQUIDO AS ENTRADAS,
    CAST (0.0 AS DECIMAL(6,4)) AS COMPRAS,
    CAST (0.0 AS DECIMAL(6,4)) AS  DEVOLUCAO,
    
    
    COALESCE((SUM((SELECT SUM(ROMATRANSF.QUANTIDADE) FROM ROMATRANSF
            WHERE ROMATRANSF.ESTAB           = ROMA.ESTAB
              AND ROMATRANSF.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATRANSF.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATRANSF.NUMEROCM        = ROMA.NUMEROCM)) *-1),0) AS TRANSFCEDIDA,
    CAST (0.0 AS DECIMAL(6,4)) AS FIXACAO,

ROMA.PESOLIQUIDO - CASE WHEN CONTAMOV.REACOBFINLEITURA = 0 AND ROMATXSERVICOPG.QTDEPAGO > 0 THEN ROMATXSERVICOPG.QTDEPAGO
  WHEN  CONTAMOV.REACOBFINLEITURA = 0 AND COALESCE(ROMATXSERVICOPG.QTDEPAGO,0) =0 THEN (CAST((DIVIDE(CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *
COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMATXSERVICO
            INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM

            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM AND
            CONTAMOV.REACOBFINLEITURA  = 0

            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMATXSERVICO.ESTAB           = ROMA.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMA.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C')),0)),60)AS NUMERIC(14,2)) , SUM(ITEMCOTITE.FIXACAO)) * 60) AS NUMERIC(14,0))) ELSE 0 END AS SALDO,

(ROMA.PESOLIQUIDO - COALESCE(SUM((SELECT SUM(ROMATRANSF.QUANTIDADE) FROM ROMATRANSF
            WHERE ROMATRANSF.ESTAB           = ROMA.ESTAB
              AND ROMATRANSF.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATRANSF.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATRANSF.NUMEROCM        = ROMA.NUMEROCM)),0)) - CASE WHEN CONTAMOV.REACOBFINLEITURA = 0  AND ROMATXSERVICOPG.QTDEPAGO > 0 THEN ROMATXSERVICOPG.QTDEPAGO 
            WHEN  CONTAMOV.REACOBFINLEITURA = 0 AND COALESCE(ROMATXSERVICOPG.QTDEPAGO,0) =0
              THEN (CAST((DIVIDE(CAST(DIVIDE(((COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) *

COALESCE(SUM((SELECT TABUMISERVITEM.VALOR FROM ROMATXSERVICO
            
              /*LEFT JOIN ROMATXSERVICOPG ON
ROMATXSERVICO.ESTAB            = ROMATXSERVICOPG.ESTAB AND
ROMATXSERVICO.ROMANEIO         = ROMATXSERVICOPG.ROMANEIO AND
ROMATXSERVICO.ENTRADASAIDA     = ROMATXSERVICOPG.ENTRADASAIDA AND
ROMATXSERVICO.NUMEROCM         = ROMATXSERVICOPG.NUMEROCM*/
            
            INNER JOIN ROMA ROMASERV ON
            ROMASERV.ESTAB                      = ROMATXSERVICO.ESTAB AND
            ROMASERV.ROMANEIO                   = ROMATXSERVICO.ROMANEIO AND
            ROMASERV.ENTRADASAIDA               = ROMATXSERVICO.ENTRADASAIDA AND
            ROMASERV.NUMEROCM                   = ROMATXSERVICO.NUMEROCM

            INNER JOIN CONTAMOV ON
            CONTAMOV.NUMEROCM                   = ROMASERV.NUMEROCM AND
            CONTAMOV.REACOBFINLEITURA  = 0

            INNER JOIN ROMADESC ON
            ROMADESC.ESTAB                      = ROMASERV.ESTAB AND
            ROMADESC.ROMANEIO                   = ROMASERV.ROMANEIO AND
            ROMADESC.ENTRADASAIDA               = ROMASERV.ENTRADASAIDA AND
            ROMADESC.NUMEROCM                   = ROMASERV.NUMEROCM AND
            ROMADESC.ROMADESC                   = 2

            INNER JOIN TABUMISERVCAB ON
            TABUMISERVCAB.TABELA                = ROMATXSERVICO.TABUMISERV

            INNER JOIN TABUMISERVITEM ON
            TABUMISERVITEM.TABELA               = TABUMISERVCAB.TABELA AND
            ROMADESC.REFTABELA                  BETWEEN TABUMISERVITEM.UMIDADEINI AND TABUMISERVITEM.UMIDADEFIN

            WHERE ROMATXSERVICO.ESTAB           = ROMA.ESTAB
              AND ROMATXSERVICO.ROMANEIO        = ROMA.ROMANEIO
              AND ROMATXSERVICO.ENTRADASAIDA    = ROMA.ENTRADASAIDA
              AND ROMATXSERVICO.NUMEROCM        = ROMA.NUMEROCM
              AND ROMATXSERVICO.SERVICO         = 30
              AND ROMATXSERVICO.STATUS          <> 'C')),0)),60)AS NUMERIC(14,2)) , SUM(ITEMCOTITE.FIXACAO)) * 60) AS NUMERIC(14,0))) ELSE 0 END AS SALDOLIQ,

    ROMA.NFPRODUTOR,
    ROMA.AREACAMPO,
    AREACAMPO.DESCRICAO AS DESCAMPO,

    (SELECT DISTINCT COALESCE(SUM(ROMATXSERVICOPG.QTDEPAGO),0) FROM ROMATXSERVICOPG
                              WHERE (ROMATXSERVICOPG.ESTAB             = ROMATXSERVICO.ESTAB)
                                  AND(ROMATXSERVICOPG.ROMANEIO         = ROMATXSERVICO.ROMANEIO)
                                  AND(ROMATXSERVICOPG.ENTRADASAIDA     = ROMATXSERVICO.ENTRADASAIDA)
                                  AND(ROMATXSERVICOPG.NUMEROCM         = ROMATXSERVICO.NUMEROCM)
                                  AND(ROMATXSERVICOPG.SEQUENCIA         = ROMATXSERVICO.SEQUENCIA)) AS QTDEPAGO,
                                  
  COALESCE(roma.tipo,99)TIPO                               

FROM ROMA

INNER JOIN FILIAL ON
FILIAL.ESTAB                    = ROMA.ESTAB

INNER JOIN ROMACFG ON
ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG AND
ROMACFG.ENTRADASAIDA    = ROMA.ENTRADASAIDA AND
ROMACFG.ENTRADASAIDA    = 'E'

INNER JOIN CONTAMOV ON
CONTAMOV.NUMEROCM               = ROMA.NUMEROCM

LEFT JOIN ENDERECO ON
ENDERECO.NUMEROCM               = ROMA.NUMEROCM AND
ENDERECO.SEQENDERECO            = ROMA.SEQENDERECO

INNER JOIN ROMACLASS ON
ROMACLASS.ESTAB                 = ROMA.ESTAB AND
ROMACLASS.ROMANEIO              = ROMA.ROMANEIO AND
ROMACLASS.ENTRADASAIDA          = ROMA.ENTRADASAIDA AND
ROMACLASS.NUMEROCM              = ROMA.NUMEROCM AND
romaclass.percentual            > 0 AND
NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
                    WHERE NFCABROMA.ESTAB          = ROMA.ESTAB
                      AND NFCABROMA.ROMANEIO       = ROMA.ROMANEIO
                      AND NFCABROMA.ENTRADASAIDA   = ROMA.ENTRADASAIDA
                      AND NFCABROMA.NUMEROCM       = ROMA.NUMEROCM)

INNER JOIN ROMACLASSNOME ON
ROMACLASSNOME.CLASSIFICACAO     = ROMACLASS.CLASSIFICACAO

LEFT JOIN AREACAMPO ON
AREACAMPO.CODIGO = ROMA.AREACAMPO

LEFT JOIN ITEMAGRO ON
ITEMAGRO.ITEM       = ROMACLASS.ITEM

LEFT JOIN ROMATXSERVICO ON
ROMATXSERVICO.ESTAB            = ROMA.ESTAB AND
ROMATXSERVICO.ROMANEIO         = ROMA.ROMANEIO AND
ROMATXSERVICO.ENTRADASAIDA     = ROMA.ENTRADASAIDA AND
ROMATXSERVICO.NUMEROCM         = ROMA.NUMEROCM

LEFT JOIN ROMATXSERVICOPG ON
ROMATXSERVICO.ESTAB            = ROMATXSERVICOPG.ESTAB AND
ROMATXSERVICO.ROMANEIO         = ROMATXSERVICOPG.ROMANEIO AND
ROMATXSERVICO.ENTRADASAIDA     = ROMATXSERVICOPG.ENTRADASAIDA AND
ROMATXSERVICO.NUMEROCM         = ROMATXSERVICOPG.NUMEROCM

LEFT JOIN ITEMAGRO ITEM_ROMANEIO ON
ROMATXSERVICO.ITEM             = ITEM_ROMANEIO.ITEM

LEFT JOIN ITEMAGROESTAB ITEMAGROESTAB_ROMANEIO ON
ITEMAGROESTAB_ROMANEIO.ESTAB   = ROMATXSERVICO.ESTAB AND
ROMACLASS.ITEM                 = ITEMAGROESTAB_ROMANEIO.ITEM

LEFT JOIN ITEMCOTCAB ON
ITEMCOTCAB.ESTAB                = ITEMAGROESTAB_ROMANEIO.ESTAB AND
ITEMCOTCAB.COTACAO              = ITEMAGROESTAB_ROMANEIO.COTACAO

LEFT JOIN ITEMCOTITE ON
ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN

WHERE ROMA.ESTORNADO <> 'S'
-- AND ROMA.NUMEROCM=8014 AND ROMA.ITEM=3 AND ROMA.ROMANEIO=14657
GROUP BY
FILIAL.ESTAB,
ROMA.ROMANEIO,
ROMA.SEQDESMEMBRADO,
ROMA.ROMAONOFF,
CONTAMOV.NUMEROCM,
ROMA.PLACA,
ROMA.PESOTOTAL,
ROMA.TARA,
ROMA.PESOLIQUIDO,
ROMA.PH,
ROMA.PESOFRETE,
ROMA.PESOTOTAL,
ROMA.FN,
ROMA.AREACAMPO,
AREACAMPO.DESCRICAO,
ROMA.FRETE,
ROMA.PESOFRETE,
ROMACLASS.CLASSIFICACAO,
ITEMAGRO.DESCRICAO,
ITEMAGRO.ITEM,
ROMA.ITEM,
CONTAMOV.REACOBFINLEITURA,
ROMATXSERVICOPG.QTDEPAGO,
ITEMAGRO.DESCRICAO,
ROMACFG.ROMANEIOCONFIG,
ROMACFG.DESCRICAO,
ROMA.NFPRODUTOR,
ROMA.NUMEROCM,
ROMA.SEQENDERECO,
ENDERECO.ENDERECO,
CONTAMOV.ENDERECO,
CONTAMOV.NOME ,
ROMACLASSNOME.CLASSIFICACAO,
ROMATXSERVICO.ESTAB,
ITEMAGROESTAB_ROMANEIO.COTACAO,
ITEMAGRO.DESCRICAO,
ROMACLASSNOME.DESCRICAOCLASSIFICACAO,
ITEMAGRO.ITEM,
ITEMAGRO.DESCRICAO,
ITEMAGRO.UNIDADE,
ROMA.DTEMISSAO,
ROMA.PESOLIQUIDO,
ROMATXSERVICO.ESTAB,
ROMATXSERVICO.ROMANEIO,
ROMATXSERVICO.ENTRADASAIDA,
ROMATXSERVICO.NUMEROCM,
ROMATXSERVICO.SEQUENCIA,
roma.tipo;