WITH
BAIXAS_DUPPAG AS 
(
    SELECT
    EMPRESA,
    DUPPAG,
    FORNECEDOR,
    SUM(VALOR) AS VLR,
    SUM(PPDUPPAG.VALOR * CASE WHEN PPDUPPAG.TIPOPAG IN ('P','J') THEN 1 ELSE -1 END) AS PAGO
    FROM PPDUPPAG

    WHERE TIPOPAG = 'P'
    AND (PPDUPPAG.DTPAGTO) <= :DTRECBTO
    AND (IDCTB IS NOT NULL OR TIPOACERTO = 'DP')
    
    GROUP BY EMPRESA,DUPPAG,FORNECEDOR
),

BAIXAS_CONTAMOV AS 
(
    SELECT
    ESTABACERTADO,
    SEQACERTADA,
    NUMEROCM,
    SUM(VALOR) AS VLR
    FROM CONTAMOVLANAC

    WHERE TIPO = 'B'
    AND (CONTAMOVLANAC.DTACERTO) <= :DTRECBTO
    GROUP BY ESTABACERTADO,SEQACERTADA,NUMEROCM
),
DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VALOR) AS VALOR FROM PRDUPRED
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,(VLRCHEQREC) AS VALOR FROM PRDURECH
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREDUP
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECAR 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDUREOUT 
    UNION ALL
    SELECT EMPRESA,DUPREC,SEQRECBTO,VALOR FROM PRDURECM WHERE TROCO = 'N'
),
BAIXAS_DPL AS (
    SELECT EMPRESA,DUPREC,SEQRECBTO,SUM(VALOR) AS VALOR FROM DPL
    GROUP BY EMPRESA,DUPREC,SEQRECBTO
),
BAIXAS_DUPREC AS 
(
SELECT
    PRDUPREC.EMPRESA,
    PRDUPREC.DUPREC,
    SUM(CASE WHEN PRDUPREC.TIPOREC IN ('D') THEN BAIXAS_DPL.VALOR ELSE 0 END) DESCONTO,
    SUM(CASE WHEN PRDUPREC.TIPOREC IN ('J') THEN BAIXAS_DPL.VALOR ELSE 0 END) JUROS,
    SUM(CASE WHEN PRDUPREC.TIPOREC IN ('R') THEN BAIXAS_DPL.VALOR ELSE 0 END) VLR,
    SUM(
        CASE 
            WHEN PRDUPREC.TIPOREC IN ('R') THEN BAIXAS_DPL.VALOR 
            WHEN PRDUPREC.TIPOREC IN ('D') THEN BAIXAS_DPL.VALOR*-1
            ELSE 0 END
    ) TOTAL_CDESC
    FROM PRDUPREC
    
    INNER JOIN BAIXAS_DPL ON 
        BAIXAS_DPL.EMPRESA = PRDUPREC.EMPRESA
        AND BAIXAS_DPL.DUPREC = PRDUPREC.DUPREC
        and BAIXAS_DPL.SEQRECBTO= PRDUPREC.SEQRECBTO

    WHERE TIPOREC IN ('R','J','D')
    AND (PRDUPREC.DTRECBTO) <= :DTRECBTO
   
    GROUP BY PRDUPREC.EMPRESA,PRDUPREC.DUPREC
) 
SELECT 
DADOS1.EMPRESA,
DADOS1.TIPO,
DADOS1.TIPODOC,
DADOS1.DTEMISSAO,
DADOS1.DOC,
CASE WHEN TIPODOC NOT IN ('DPL','SUPPLIER','FARMTECH') THEN DADOS1.TIPODOC ELSE PSITUACA.DESCRICAO END DESC_SITUA,
DADOS1.OBS,
DADOS1.GRUPOCM,
DADOS1.NOME,
DADOS1.CONCEITO,
DADOS1.CELULAR,
DADOS1.DTPROXCONTATO,
DADOS1.DTPROVAVELPAGAMENTO,
DADOS1.DTCONTATO,
DADOS1.DTVENCTO,
DADOS1.DTCALCJUROS,
DADOS1.DIAS,
DADOS1.VALOR,
DADOS1.JUROS,
DADOS1.DESCTO,
DADOS1.RECEBIDO,
DADOS1.SALDOCORR
FROM 
(
    SELECT DADOS.*,
               ocorrenciafinan.dtcontato,
               OCORRENCIAFINAN.DTPROXCONTATO,
                OCORRENCIAFINAN.DTPROVAVELPAGAMENTO,
            CAST( OCORRENCIAFINAN.OBS AS VARCHAR(200))OBS
FROM(
SELECT
        '1 - DUPLICATA - A RECEBER' TIPO,
        'DPL' TIPODOC,
        'N' AS FRED_FRETE,
        PDUPREC.EMPRESA,
        PDUPREC.DUPREC DOC,
        TO_DATE(:DTRECBTO)DTCOB,
        PDUPREC.DTEMISSAO,
        PDUPREC.DTVENCTO,
        COALESCE(PDUPREC.DTCALCJUROS,PDUPREC.DTVENCTO)DTCALCJUROS,
        (CURRENT_DATE - PDUPREC.DTVENCTO) DIAS,
        PDUPREC.CLIENTE,
        CONTAMOV.GRUPOCM,
        CONTAMOV.NOME||' - '|| PDUPREC.CLIENTE  NOME,
        CONCEITO.DESCRICAO AS CONCEITO,
        PDUPREC.SITUACAO,
        '' AS ITEM_DESC,
        NFCAB.SEQNOTA,
        CONTAMOV.CELULAR,
        COALESCE(NFCAB_U.VENDAORBIA,'N') AS ORBIA,
        CASE WHEN PDUPREC.SEQENDERECO > 0 THEN ENDERECO.ENDERECO||', NRº '||ENDERECO.NUMEROEND||' - '||CIDEND.NOME||' - '||CIDEND.UF ELSE
        CONTAMOV.ENDERECO||', NRº '||CONTAMOV.ENDERECO||' - '||CIDPES.NOME||' - '||CIDPES.UF END AS ENDERECO,
        PDUPREC.VALOR,

         CASE WHEN CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)) = 0 THEN 0
             ELSE CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2))
        END AS "JUR%",

        CASE WHEN CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) = 0 THEN 0
        ELSE CAST(NVLF0(REPLACE(NVL(:DESCTO,0), ',', '.')) AS NUMERIC(14,2))
        END AS "DESC%",

       --  CAST(COALESCE((PDUPREC.VALOR - (PDUPREC.VALOR - COALESCE(PDUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) -COALESCE(PDUPREC.DESCONTO,0) ),0)AS NUMERIC(14,2)) RECEBIDO, 
         CAST(NVL(BAIXAS_DUPREC.TOTAL_CDESC,0) AS NUMERIC(14,2)) RECEBIDO,
        --(PDUPREC.VALOR - COALESCE(PDUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS SALDO,
          (PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.VLR,0)) AS SALDO,
          
        CASE WHEN COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))-COALESCE(BAIXAS_DUPREC.DESCONTO,0),0) < 0 THEN
        CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
        CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
        COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS)
        ELSE 
        CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))/*-COALESCE(PDUPREC.DESCONTO,0)*/ AS NUMERIC(14,2))),
        CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
        COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS) END JUROS,

         COALESCE(BAIXAS_DUPREC.desconto,0)+(CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                           CASE WHEN CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) = 0 THEN 0
                           ELSE CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) END,
         TO_DATE(:DTRECBTO), COALESCE(PDUPREC.DTVENCTO,PDUPREC.DTBASEJUROS), PCONFPAD.TIPOJUROS)) DESCTO,

        (--CALCULO SALDO DPL AJUSTADO--
        
        COALESCE(PDUPREC.VALOR,0) + 
        
            --JUROS--
            COALESCE(CASE WHEN COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))-COALESCE(BAIXAS_DUPREC.DESCONTO,0),0) < 0 THEN
                CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS)
                ELSE 
                CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))/*-COALESCE(PDUPREC.DESCONTO,0)*/ AS NUMERIC(14,2))),
                CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS) END,0)
            --JUROS--
                    
                -
                    
            --DESC--        
                COALESCE(COALESCE(BAIXAS_DUPREC.DESCONTO,0)+(CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                                   CASE WHEN CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) = 0 THEN 0
                                   ELSE CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) END,
                 TO_DATE(:DTRECBTO), COALESCE(PDUPREC.DTVENCTO,PDUPREC.DTBASEJUROS), PCONFPAD.TIPOJUROS)),0)
            --DESC--
            
                
                -
            --RECEBIDO--    
            CAST(NVL(BAIXAS_DUPREC.TOTAL_CDESC,0) AS NUMERIC(14,2))
            --CAST(COALESCE((PDUPREC.VALOR - (PDUPREC.VALOR - COALESCE(PDUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) -COALESCE(PDUPREC.DESCONTO,0) ),0)AS NUMERIC(14,2)) --COALESCE(PBAIXASDUPREC.PNRECEBIDODUPREC,0)    
            --RECEBIDO--
        
        --CALCULO SALDO DPL AJUSTADO--
        ) AS SALDOCORR,

        CASE WHEN CURRENT_DATE >= PDUPREC.DTVENCTO  AND (COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))-COALESCE(BAIXAS_DUPREC.DESCONTO,0),0)) < 0  THEN

        ((CAST(COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))/*-COALESCE(PDUPREC.DESCONTO,0)*/,0)AS NUMERIC(14,2)) +

       CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                                  CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                                  COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS)-

                                 CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                                 CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                                 TO_DATE(:DTRECBTO), COALESCE(PDUPREC.DTVENCTO,PDUPREC.DTBASEJUROS), PCONFPAD.TIPOJUROS)))
                when CURRENT_DATE >= PDUPREC.DTVENCTO  AND (COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))-COALESCE(BAIXAS_DUPREC.DESCONTO,0),0)) > 0 then
                ((CAST(COALESCE((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0))-COALESCE(BAIXAS_DUPREC.DESCONTO,0),0)AS NUMERIC(14,2)) +

       CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                                  CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                                  COALESCE(PDUPREC.DTBASEJUROS,PDUPREC.DTVENCTO),TO_DATE(:DTRECBTO), PCONFPAD.TIPOJUROS)-

                                 CALCULAJURO(NVLF0(CAST((PDUPREC.VALOR - COALESCE(BAIXAS_DUPREC.DESCONTO,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) AS NUMERIC(14,2))),
                                 CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                                 TO_DATE(:DTRECBTO), COALESCE(PDUPREC.DTVENCTO,PDUPREC.DTBASEJUROS), PCONFPAD.TIPOJUROS)))
                 else 0 
                 END AS SALDOVENCO,
                 OCORRENCIADUPREC.IDOCORRENCIA,
                 (
                 select distinct
                 LISTAGG(distinct nfitem.romaneio, '; ') WITHIN GROUP (ORDER BY nfitem.estab,nfitem.seqnota)
                 from nfitem
                 
                 where
                 nfitem.estab = nfcab.estab
                 and nfitem.seqnota = nfcab.seqnota
                 ) romaneio

    FROM PDUPREC

        INNER JOIN CONTAMOV ON
        CONTAMOV.NUMEROCM = PDUPREC.CLIENTE

        LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM

        LEFT JOIN CONCEITO ON CONCEITO.CONCEITO=CONCEITOPESSOA.CONCEITO

        LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM   = PDUPREC.CLIENTE AND
        ENDERECO.SEQENDERECO    = PDUPREC.SEQENDERECO

        LEFT JOIN CIDADE CIDEND ON
        CIDEND.CIDADE   = ENDERECO.CIDADE

        LEFT JOIN CIDADE CIDPES ON
        CIDPES.CIDADE   = CONTAMOV.CIDADE

        INNER JOIN PCONFPAD ON
        PCONFPAD.EMPRESA = PDUPREC.EMPRESA


        LEFT JOIN ( SELECT  OCORRENCIADUPREC.ESTAB,
                           OCORRENCIADUPREC.DUPREC,
                           MAX(OCORRENCIADUPREC.IDOCORRENCIA)IDOCORRENCIA
                           
     

         FROM OCORRENCIADUPREC

        INNER JOIN OCORRENCIAFINAN ON ocorrenciafinan.idocorrencia = ocorrenciaduprec.idocorrencia

        GROUP BY OCORRENCIADUPREC.ESTAB,OCORRENCIADUPREC.DUPREC

        ) OCORRENCIADUPREC

                                  ON OCORRENCIADUPREC.ESTAB = PDUPREC.EMPRESA
                                    AND OCORRENCIADUPREC.duprec = PDUPREC.DUPREC
                                    
      LEFT JOIN AGRFINDUPREC AGR ON AGR.ESTAB = PDUPREC.EMPRESA
                                AND AGR.DUPREC = PDUPREC.DUPREC
                                
        LEFT JOIN NFCABAGRFIN NFAGR ON NFAGR.ESTAB = AGR.ESTAB
                                    AND NFAGR.SEQPAGAMENTO = AGR.SEQPAGAMENTO
                                    
        LEFT JOIN NFCAB ON NFCAB.ESTAB = NFAGR.ESTAB
          								AND NFCAB.SEQNOTA = NFAGR.SEQNOTA
        
        LEFT JOIN NFCAB_U ON NFCAB_U.ESTAB = NFCAB.ESTAB
                        AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
                        
        LEFT JOIN BAIXAS_DUPREC ON
		BAIXAS_DUPREC.EMPRESA = PDUPREC.EMPRESA
		AND BAIXAS_DUPREC.DUPREC = PDUPREC.DUPREC

        INNER JOIN FILIAL ON FILIAL.ESTAB = PDUPREC.EMPRESA

    WHERE 
       (PDUPREC.VALOR - COALESCE(PDUPREC.DESCONTO,0) - NVL(PDUPREC.DESCPEND,0) - COALESCE(BAIXAS_DUPREC.VLR,0)) > 0
    	AND PDUPREC.EMPRESA < 800
        AND FILIAL.INATIVA = 'N'
        AND PDUPREC.DTEMISSAO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
        AND PDUPREC.DTVENCTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

        <#if ESTAB?has_content>
        and PDUPREC.EMPRESA IN (:ESTAB)
          </#if>

      <#if CLIENTE?has_content>
        and PDUPREC.CLIENTE IN (:CLIENTE)
          </#if>

       <#if CONCEITO?has_content>
        and CONCEITO.CONCEITO IN (:CONCEITO)
          </#if>

        <#if GRUPOCM?has_content>
        and CONTAMOV.GRUPOCM IN (:GRUPOCM)
          </#if>

        <#if SITUACAO?has_content>
        and PDUPREC.SITUACAO IN (:SITUACAO)
          </#if>

        <#if TIPOS?has_content>
        and 1 IN (:TIPOS)
          </#if> 
        
        )DADOS

LEFT JOIN OCORRENCIAFINAN ON ocorrenciafinan.idocorrencia = DADOS.idocorrencia

UNION ALL

 SELECT
         '2 - CONTA MOVIMENTO - A RECEBER' TIPO,
        CONTAMOVLAN.TIPO as  TIPODOC,
        CASE WHEN CONTAMOVLAN.TIPO IN ('FRED','FRET') THEN 'S' ELSE 'N' END FRED_FRETE,
        CONTAMOVLAN.ESTAB EMPRESA,
        COALESCE(CONTAMOVLAN.NRODOCTO,'0') DOC,
        TO_DATE(:DTRECBTO)DTCOB,
        CONTAMOVLAN.DTMOVTO DTEMISSAO,
         CONTAMOVLAN.VENCIMENTO DTVENCTO,
        COALESCE(CONTAMOVLAN.DTJURO,CONTAMOVLAN.VENCIMENTO) DTJURO,
        (TO_DATE(:DTRECBTO) - contamovlan.dtjuro) DIAS,
        CONTAMOVLAN.NUMEROCM CLIENTE,
        CONTAMOV.GRUPOCM,
        CONTAMOV.NOME||' - '||CONTAMOVLAN.NUMEROCM NOME,
        CONCEITO.DESCRICAO AS CONCEITO,
        NFCABAGRFIN.FORMAPGTO AS SITUACAO,
        ITEMAGRO.DESCRICAO AS ITEM_DESC,
        COALESCE(NFCAB.SEQNOTA,0)AS SEQNOTA,
        CONTAMOV.CELULAR,
        'N' AS ORBIA,
        '' ENDERECO,
        CONTAMOVLAN.VALOR,
        CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)) AS JUR,
        CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) AS DESCTO,

        COALESCE(CONTAMOVLAN.VALOR - (CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0)
         AS RECEBIDO,

        COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) SALDO,

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                          CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                          CONTAMOVLAN.DTJURO,
                          COALESCE(TO_DATE(:DTRECBTO),contamovlan.dtjuro), 'S') JUROS,

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                           CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                           TO_DATE(:DTRECBTO), contamovlan.dtjuro, 'S') DESCTO,


       (COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) +

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                          CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                          CONTAMOVLAN.DTJURO,
                          COALESCE(TO_DATE(:DTRECBTO),contamovlan.dtjuro), 'S') -

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                           CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                           TO_DATE(:DTRECBTO), contamovlan.dtjuro, 'S')) SALDOCORR,

       CASE WHEN  CURRENT_DATE >= CONTAMOVLAN.VENCIMENTO THEN

       (COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) +

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                          CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                          CONTAMOVLAN.DTJURO,
                          COALESCE(TO_DATE(:DTRECBTO),contamovlan.dtjuro), 'S') -

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                           CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                           TO_DATE(:DTRECBTO), contamovlan.dtjuro, 'S'))

        ELSE 0 END SALDOVENCO,
        0 idocorrencia,
        case when contamovlan.tipo in ('FRED','FRET') then  contamovlan.nrodocto else null end romaneio,
        CURRENT_DATE AS DTCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        '' OBS


    FROM CONTAMOVLAN

        INNER JOIN CONTAMOV ON
        CONTAMOV.NUMEROCM   = CONTAMOVLAN.NUMEROCM AND
        CONTAMOVLAN.DEBCRED = 'D'


       LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM

       LEFT JOIN CONCEITO ON CONCEITO.CONCEITO=CONCEITOPESSOA.CONCEITO
       
       LEFT JOIN AGRFINCTAMOV ON AGRFINCTAMOV.ESTAB = CONTAMOVLAN.ESTAB
                            AND AGRFINCTAMOV.NUMEROCM = CONTAMOVLAN.NUMEROCM
                            AND AGRFINCTAMOV.SEQCM = CONTAMOVLAN.SEQCM
                            
       LEFT JOIN NFCABAGRFIN ON NFCABAGRFIN.ESTAB = AGRFINCTAMOV.ESTAB
                        AND NFCABAGRFIN.SEQPAGAMENTO = AGRFINCTAMOV.SEQPAGAMENTO
                        
        LEFT JOIN NFCAB ON NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
                        AND NFCAB.ESTAB = NFCABAGRFIN.ESTAB

       LEFT JOIN ROMA ON ROMA.ESTAB = CONTAMOVLAN.ESTAB 
                      AND ROMA.NUMEROCM = CONTAMOVLAN.NUMEROCM   
                      AND TO_CHAR(ROMA.ROMANEIO) = CONTAMOVLAN.NRODOCTO
                 
       LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = ROMA.ITEM 
       
       LEFT JOIN BAIXAS_CONTAMOV ON
        BAIXAS_CONTAMOV.ESTABACERTADO = CONTAMOVLAN.ESTAB
        AND BAIXAS_CONTAMOV.SEQACERTADA = CONTAMOVLAN.SEQCM
        AND BAIXAS_CONTAMOV.NUMEROCM = CONTAMOVLAN.NUMEROCM
       

INNER JOIN FILIAL ON FILIAL.ESTAB = CONTAMOVLAN.ESTAB

    WHERE (CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)) > 0
      AND CONTAMOVLAN.ESTAB < 800
      AND FILIAL.INATIVA = 'N'
      AND CONTAMOVLAN.TIPO NOT IN ('ACT','TACT','ACCR')
      AND CONTAMOVLAN.DTMOVTO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
      AND CONTAMOVLAN.VENCIMENTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

    <#if ESTAB?has_content>
        and CONTAMOVLAN.ESTAB IN (:ESTAB)
          </#if>

      <#if CLIENTE?has_content>
        and CONTAMOVLAN.NUMEROCM IN (:CLIENTE)
          </#if>

        <#if CONCEITO?has_content>
        and CONCEITO.CONCEITO IN (:CONCEITO)
          </#if>


        <#if GRUPOCM?has_content>
        and CONTAMOV.GRUPOCM IN (:GRUPOCM)
          </#if>


        <#if TIPOS?has_content>
        and 2 IN (:TIPOS)
          </#if> 

UNION ALL

SELECT  '3 - DUPLICATA - A PAGAR' TIPO,
        'DPL' TIPODOC,
        'N' AS FRED_FRETE,
        PDUPPAGA.EMPRESA,
        PDUPPAGA.DUPPAG DOC,
       TO_DATE(:DTRECBTO)DTCOB,
        pduppaga.DTEMISSAO,
        pduppaga.DTVENCTO,
        COALESCE(pduppaga.DTCALCJUROS,pduppaga.DTVENCTO)DTCALCJUROS,
        (CURRENT_DATE - pduppaga.DTVENCTO) DIAS,
        pduppaga.fornecedor,
         CONTAMOV.GRUPOCM,
        CONTAMOV.NOME||' - '||pduppaga.FORNECEDOR NOME,
        CONCEITO.DESCRICAO AS CONCEITO,
        PDUPPAGA.SITUACAO AS SITUACAO,
        '' AS ITEM_DESC,
        NFCAB.SEQNOTA,
       CONTAMOV.CELULAR,
       COALESCE(NFCAB_U.VENDAORBIA,'N') AS ORBIA,
        CASE WHEN pduppaga.SEQENDERECO > 0 THEN ENDERECO.ENDERECO||', NRº '||ENDERECO.NUMEROEND||' - '||CIDEND.NOME||' - '||CIDEND.UF ELSE
        CONTAMOV.ENDERECO||', NRº '||CONTAMOV.ENDERECO||' - '||CIDPES.NOME||' - '||CIDPES.UF END AS ENDERECO,
        pduppaga.VALOR *-1,

         CASE WHEN CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)) = 0 THEN 0
             ELSE CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2))
        END AS "JUR%",

        CASE WHEN CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)) = 0 THEN 0
        ELSE CAST(NVLF0(REPLACE(NVL(:DESCTO,0), ',', '.')) AS NUMERIC(14,2))
        END AS "DESC%",

        CAST(COALESCE(PDUPPAGA.VALOR - (PDUPPAGA.VALOR - COALESCE(PDUPPAGA.DESCONTOS,0) - COALESCE(BAIXAS_DUPPAG.VLR,0)),0)AS NUMERIC(14,2)) RECEBIDO,
        CAST(COALESCE((PDUPPAGA.VALOR - COALESCE(PDUPPAGA.DESCONTOS,0) - COALESCE(BAIXAS_DUPPAG.VLR,0))*-1,0)AS NUMERIC(14,2)) SALDO,
        0 JUROS,
        0 DESCTO,
        (PDUPPAGA.VALOR - COALESCE(PDUPPAGA.DESCONTOS,0) - COALESCE(BAIXAS_DUPPAG.VLR,0))*-1 as SALDOCORR,
          CASE WHEN CURRENT_DATE >= pduppaga.DTVENCTO THEN

        (CAST(COALESCE((PDUPPAGA.VALOR - COALESCE(PDUPPAGA.DESCONTOS,0) - COALESCE(BAIXAS_DUPPAG.VLR,0))*-1,0)AS NUMERIC(14,2)))
                ELSE
                0 END AS SALDOVENCO,
        0 idocorrencia,
        NULL romaneio,
        CURRENT_DATE AS DTCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        '' OBS

         FROM pduppaga

         INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM=pduppaga.fornecedor


       LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM

       LEFT JOIN CONCEITO ON CONCEITO.CONCEITO=CONCEITOPESSOA.CONCEITO

        LEFT JOIN ENDERECO ON
        ENDERECO.NUMEROCM   = pduppaga.fornecedor AND
        ENDERECO.SEQENDERECO    = pduppaga.SEQENDERECO

        LEFT JOIN CIDADE CIDEND ON
        CIDEND.CIDADE   = ENDERECO.CIDADE

        LEFT JOIN CIDADE CIDPES ON
        CIDPES.CIDADE   = CONTAMOV.CIDADE

        INNER JOIN PCONFPAD ON
        PCONFPAD.EMPRESA = pduppaga.EMPRESA
        
         LEFT JOIN AGRFINDUPPAG AGR ON AGR.ESTAB = pduppaga.EMPRESA
                                AND AGR.DUPPAG = pduppaga.DUPPAG
                                AND AGR.FORNECEDOR = pduppaga.FORNECEDOR
                                
        LEFT JOIN NFCABAGRFIN NFAGR ON NFAGR.ESTAB = AGR.ESTAB
                                    AND NFAGR.SEQPAGAMENTO = AGR.SEQPAGAMENTO
                                    
        LEFT JOIN NFCAB_U ON NFCAB_U.ESTAB = NFAGR.ESTAB
                        AND NFCAB_U.SEQNOTA = NFAGR.SEQNOTA
                        
          LEFT JOIN NFCAB ON NFCAB.ESTAB = NFCAB_U.ESTAB
          								AND NFCAB.SEQNOTA = NFCAB_U.SEQNOTA

           LEFT JOIN BAIXAS_DUPPAG ON
			BAIXAS_DUPPAG.EMPRESA = PDUPPAGA.EMPRESA
			AND BAIXAS_DUPPAG.DUPPAG = PDUPPAGA.DUPPAG
			AND BAIXAS_DUPPAG.FORNECEDOR = PDUPPAGA.FORNECEDOR
            
            INNER JOIN FILIAL ON FILIAL.ESTAB = PDUPPAGA.EMPRESA

           WHERE (PDUPPAGA.VALOR - COALESCE(PDUPPAGA.DESCONTOS,0) - COALESCE(BAIXAS_DUPPAG.VLR,0)) > 0
           AND PDUPPAGA.EMPRESA < 800
           AND FILIAL.INATIVA = 'N'
        AND PDUPPAGA.DTEMISSAO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
        AND PDUPPAGA.DTVENCTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

        <#if ESTAB?has_content>
        and PDUPPAGA.EMPRESA IN (:ESTAB)
          </#if>

       <#if CLIENTE?has_content>
        and PDUPPAGA.FORNECEDOR IN (:CLIENTE)
          </#if>

        <#if CONCEITO?has_content>
        and CONCEITO.CONCEITO IN (:CONCEITO)
          </#if>

        <#if GRUPOCM?has_content>
        and CONTAMOV.GRUPOCM IN (:GRUPOCM)
          </#if>
        
        
        <#if SITUACAO?has_content>
        and PDUPPAGA.SITUACAO IN (:SITUACAO)
          </#if>

          
        <#if TIPOS?has_content>
        and 3 IN (:TIPOS)
          </#if> 
        

UNION ALL

SELECT
CASE WHEN CONTRATOCFG.ENTRADASAIDA = 'E' THEN '7 - CONTRATO - A PAGAR' ELSE '7 - CONTRATO - A RECEBER' END TIPO,
CASE WHEN CONTRATOCFG.ENTRADASAIDA = 'E' THEN 'CTR - C' else 'CTR - V' END TIPODOC,
'N' AS FRED_FRETE,
CONTRATO.ESTAB AS EMPRESA,
CAST(CONTRATO.CONTRATO AS VARCHAR(20) ) AS  DOC,
TO_DATE(:DTRECBTO)DTCOB,
CONTRATO.DTEMISSAO,
CONTRATO.DTVENCTO AS DTVENCTO,
CONTRATO.DTVENCTO AS DTCALCJUROS,
( TO_DATE(:DTRECBTO) - CONTRATO.DTVENCTO ) DIAS,
CONTRATO.NUMEROCM AS CLIENTE,
CONTAMOV.GRUPOCM,
CONTAMOV.NOME||' - '||CONTRATO.NUMEROCM AS NOME,
CONCEITO.DESCRICAO AS CONCEITO,
CONTRATO.CONTCONF AS SITUACAO,
'' AS ITEM_DESC,
0 AS SEQNOTA,
CONTAMOV.CELULAR,
NULL AS ORBIA,
'' AS ENDERECO,
CONTRATOITE.VALORTOTAL,
0 AS JUR,
0 AS "DESC",
PSALDO.NVLRBX AS RECEBIDO,
PSALDO.NVLRSALDO AS SALDO,
0 AS JUROS,
0 AS DESCTO,
PSALDO.NVLRSALDO AS SALDOCORR,
CASE WHEN CURRENT_DATE >= CONTRATO.DTVENCTO AND ARREDONDAR(NVLRSALDO,0) > 0 THEN NVLRSALDO ELSE 0 END SALDOVENCO,
NULL AS IDOCORRENCIA,
NULL AS ROMANEIO,
null AS DTCONTATO,
null AS DTPROXCONTATO,
null AS DTPROVAVELPAGAMENTO,
'' AS OBS
FROM CONTRATO
INNER JOIN FILIAL ON FILIAL.ESTAB  = CONTRATO.ESTAB
INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
INNER JOIN CONTRATOCFG_U C ON C.CONTCONF = CONTRATOCFG.CONTCONF
LEFT JOIN U_TIPOCTR U ON U.U_TIPOCTR_ID = C.U_TIPOCTR_ID
INNER JOIN CONTRATOITE ON 
    CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO

INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 :DTRECBTO, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO ON (0=0)

INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM = CONTAMOV.NUMEROCM
INNER JOIN CONCEITO ON CONCEITO.CONCEITO = CONCEITOPESSOA.CONCEITO
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = CONTRATO.NUMEROCM
    AND ENDERECO.SEQENDERECO = CONTRATO.ENDALTERNATIVO
LEFT JOIN CIDADE ON CIDADE.CIDADE = NVL(ENDERECO.CIDADE,CONTAMOV.CIDADE)
WHERE
FILIAL.INATIVA = 'N'
AND ARREDONDAR(NVLRSALDO,0) > 0
and contrato.ativo = 'A'
AND U.TIPOCTR NOT IN ('CTR-CT','CTR-VT','CTR-TF','CTR-LB','CTR-BMF-C','CTR-BMF-V','CTR-O','CTR-FL')
AND CONTRATO.DTEMISSAO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
AND CONTRATO.DTVENCTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

<#if ESTAB?has_content>
    and CONTRATO.ESTAB IN (:ESTAB)
</#if>

<#if CLIENTE?has_content>
    and CONTRATO.NUMEROCM IN (:CLIENTE)
</#if>


<#if CONCEITO?has_content>
    and CONCEITO.CONCEITO IN (:CONCEITO)
</#if>


<#if GRUPOCM?has_content>
    and CONTAMOV.GRUPOCM IN (:GRUPOCM)
</#if>


<#if TIPOS?has_content>
    and 7 IN (:TIPOS)
</#if> 


union all
SELECT
'6 - SUPPLIER/FARMTECH' AS TIPO,
CASE WHEN PSITUACA.DESCRICAO LIKE '%FARMTECH%' THEN 'FARMTECH' ELSE 'SUPPLIER' END AS TIPODOC,
'N' AS FRED_FRETE,
F.ESTAB AS EMPRESA,
I.DUPREC AS DOC,
TO_DATE(:DTRECBTO)DTCOB,
PDUPREC.DTEMISSAO,
I.DT_VENCTO AS DTVENCTO,
I.DT_VENCTO AS DTCALCJUROS,
( TO_DATE(:DTRECBTO) - I.DT_VENCTO ) DIAS,
PDUPREC.CLIENTE AS CLIENTE,
CONTAMOV.GRUPOCM,
CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS NOME,
CONCEITO.DESCRICAO AS CONCEITO,
PDUPREC.SITUACAO AS SITUACAO,
'' AS ITEM_DESC,
0 AS SEQNOTA,
CONTAMOV.CELULAR,
NULL AS ORBIA,
'' AS ENDERECO,
I.VALOR,
0 AS JUR,
0 AS "DESC",
I.VALOR AS RECEBIDO,
I.VALOR AS SALDO,
0 AS JUROS,
0 AS DESCTO,
I.VALOR AS SALDOCORR,
CASE WHEN CURRENT_DATE >= I.DT_VENCTO THEN I.VALOR ELSE 0 END SALDOVENCO,
NULL AS IDOCORRENCIA,
NULL AS ROMANEIO,
null AS DTCONTATO,
null AS DTPROXCONTATO,
null AS DTPROVAVELPAGAMENTO,
'' AS OBS
FROM U_FAT_SUPPLIER F-- CABEÇALHO
INNER JOIN U_FAT_ITEM_SUPPLIER I ON I.COD_TRANSACAO = F.COD_TRANSACAO
INNER JOIN PDUPREC ON
    PDUPREC.EMPRESA = I.EMPRESA
    AND PDUPREC.DUPREC = I.DUPREC
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = PDUPREC.CLIENTE
INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM = CONTAMOV.NUMEROCM
INNER JOIN CONCEITO ON CONCEITO.CONCEITO = CONCEITOPESSOA.CONCEITO
LEFT JOIN PSITUACA ON PSITUACA.SITUACAO = PDUPREC.SITUACAO
WHERE
F.VALOR_AR <> 0
AND UPPER(F.STATUS) NOT IN ('CANCELADA')
AND PDUPREC.DTEMISSAO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
AND I.DT_VENCTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

<#if ESTAB?has_content>
    and F.ESTAB IN (:ESTAB)
</#if>

<#if CLIENTE?has_content>
    and PDUPREC.CLIENTE IN (:CLIENTE)
</#if>


<#if CONCEITO?has_content>
    and CONCEITO.CONCEITO IN (:CONCEITO)
</#if>

<#if GRUPOCM?has_content>
    and CONTAMOV.GRUPOCM IN (:GRUPOCM)
</#if>


<#if TIPOS?has_content>
    and 6 IN (:TIPOS)
</#if> 

UNION ALL

 SELECT
        '5 - CONTA MOVIMENTO - A PAGAR' TIPO,
        CONTAMOVLAN.TIPO as  TIPODOC,
        CASE WHEN CONTAMOVLAN.TIPO IN ('FRED','FRET') THEN 'S' ELSE 'N' END FRED_FRETE,
        CONTAMOVLAN.ESTAB EMPRESA,
        COALESCE(CONTAMOVLAN.NRODOCTO,'0') DOC,
        TO_DATE(:DTRECBTO)DTCOB,
        CONTAMOVLAN.DTMOVTO DTEMISSAO,
        CONTAMOVLAN.VENCIMENTO DTVENCTO,
       COALESCE(CONTAMOVLAN.DTJURO,CONTAMOVLAN.VENCIMENTO),
        ( TO_DATE(:DTRECBTO) - contamovlan.dtjuro) DIAS,
        CONTAMOVLAN.NUMEROCM CLIENTE,
         CONTAMOV.GRUPOCM,
        CONTAMOV.NOME||' - '||CONTAMOVLAN.NUMEROCM NOME,
         CONCEITO.DESCRICAO AS CONCEITO,
         NFCABAGRFIN.FORMAPGTO AS SITUACAO,
         ITEMAGRO.DESCRICAO AS ITEM_DESC,
         COALESCE(NFCAB.SEQNOTA,0) AS SEQNOTA,
       CONTAMOV.CELULAR,
       'N' AS ORBIA,
        '' ENDERECO,
        CONTAMOVLAN.VALOR *-1,
        CAST (NVL(:JUROS,0) AS NUMERIC(14,2)) AS JUR,
        CAST (NVL(:DESCTO,0) AS NUMERIC(14,2)) AS DESCTO,
        COALESCE(CONTAMOVLAN.VALOR - (CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0)
         AS RECEBIDO,
        COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0)*-1 SALDO,
        0 AS JUROS,
        0 AS DESCONTO,
         COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0)*-1  AS CORRIDO,
         CASE WHEN  CURRENT_DATE >= CONTAMOVLAN.VENCIMENTO THEN

       (COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) +

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                          CAST(NVLF0(REPLACE(NVL(:JUROS,0), ',', '.')) AS NUMERIC(14,2)),
                          CONTAMOVLAN.DTJURO,
                          COALESCE(TO_DATE(:DTRECBTO),contamovlan.dtjuro), 'S') -

        CALCULAJURO(NVLF0(CAST(COALESCE((CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)),0) AS NUMERIC(14,2))),
                           CAST(REPLACE(NVL(:DESCTO,0), ',', '.') AS NUMERIC(14,2)),
                           TO_DATE(:DTRECBTO), contamovlan.dtjuro, 'S'))

        ELSE 0 END SALDOVENCO,
        0 idocorrencia,
        case when contamovlan.tipo in ('FRED','FRET') then  contamovlan.nrodocto else null end romaneio,
        CURRENT_DATE AS DTCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        CURRENT_DATE AS DTPROXCONTATO,
        ''OBS

    FROM CONTAMOVLAN
        INNER JOIN CONTAMOV ON
        CONTAMOV.NUMEROCM   = CONTAMOVLAN.NUMEROCM AND
        CONTAMOVLAN.DEBCRED = 'C'

       LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM

       LEFT JOIN CONCEITO ON CONCEITO.CONCEITO=CONCEITOPESSOA.CONCEITO
       
        LEFT JOIN AGRFINCTAMOV ON AGRFINCTAMOV.ESTAB = CONTAMOVLAN.ESTAB
                            AND AGRFINCTAMOV.NUMEROCM = CONTAMOVLAN.NUMEROCM
                            AND AGRFINCTAMOV.SEQCM = CONTAMOVLAN.SEQCM
                            
       LEFT JOIN NFCABAGRFIN ON NFCABAGRFIN.ESTAB = AGRFINCTAMOV.ESTAB
                        AND NFCABAGRFIN.SEQPAGAMENTO = AGRFINCTAMOV.SEQPAGAMENTO
                        
        LEFT JOIN NFCAB ON NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA
                        AND NFCAB.ESTAB = NFCABAGRFIN.ESTAB

       LEFT JOIN ROMA ON ROMA.ESTAB = CONTAMOVLAN.ESTAB 
                      AND ROMA.NUMEROCM = CONTAMOVLAN.NUMEROCM   
                      AND TO_CHAR(ROMA.ROMANEIO) = CONTAMOVLAN.NRODOCTO
                 
       LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = ROMA.ITEM      
       
       LEFT JOIN BAIXAS_CONTAMOV ON
        BAIXAS_CONTAMOV.ESTABACERTADO = CONTAMOVLAN.ESTAB
        AND BAIXAS_CONTAMOV.SEQACERTADA = CONTAMOVLAN.SEQCM
        AND BAIXAS_CONTAMOV.NUMEROCM = CONTAMOVLAN.NUMEROCM

        INNER JOIN FILIAL ON FILIAL.ESTAB = CONTAMOVLAN.ESTAB

    WHERE (CONTAMOVLAN.VALOR - COALESCE(CONTAMOVLAN.DESCONTO,0) - COALESCE(BAIXAS_CONTAMOV.VLR,0)) > 0
    AND CONTAMOVLAN.ESTAB < 800
    AND FILIAL.INATIVA = 'N'
    AND CONTAMOVLAN.TIPO NOT IN ('ACDB')
      AND CONTAMOVLAN.DTMOVTO BETWEEN NVL(:DTEMIINI,'01/01/2001') AND NVL(:DTEMIFIM,'31/12/2099')
        AND CONTAMOVLAN.VENCIMENTO  BETWEEN NVL(:DTINI,'01/01/2001') AND NVL(:DTFIM,'31/12/2099')

    <#if ESTAB?has_content>
        and CONTAMOVLAN.ESTAB IN (:ESTAB)
    </#if>

   <#if CLIENTE?has_content>
        and CONTAMOVLAN.NUMEROCM IN (:CLIENTE)
    </#if>

    <#if CONCEITO?has_content>
        and CONCEITO.CONCEITO IN (:CONCEITO)
    </#if>

    <#if GRUPOCM?has_content>
        and CONTAMOV.GRUPOCM IN (:GRUPOCM)
    </#if>


    <#if TIPOS?has_content>
        and 6 IN (:TIPOS)
    </#if> 
        

ORDER BY 11,12,1 asc ,9

) DADOS1
LEFT JOIN PSITUACA ON PSITUACA.SITUACAO = DADOS1.SITUACAO

order by dados1.CLIENTE, dados1.GRUPOCM, dados1.TIPO asc,dados1.DTVENCTO