WITH  NFCAB_FILTRADA AS (
    SELECT ESTAB,SERIE,NOTA,NUMEROCM,CHAVEACESSONFE,USERID,DTEMISSAO,SEQENDERECO,VALOR,CLIENTEIMP,SEQNOTA,NOTACONF
    FROM NFCAB
    WHERE DTENTSAI BETWEEN :DTINICIAL AND :DTFINAL
      AND STATUS <> 'C'
),

SIEG AS (
    SELECT
        dtemissao,
        CHAVEACESSONFE,
  STATUS,
        CASE 
            WHEN SERIE = '001' THEN '1'
            WHEN SERIE = '002' THEN '2'
            ELSE SERIE
        END AS SERIE,
        ESTAB,
        NOTA,
        CNPJ_EMITENTE,
        IE,
        CMUN,
        SUM(VNF) AS VNF
    FROM U_NOTASSIEG
    GROUP BY
        dtemissao,
        CHAVEACESSONFE,
        SERIE,
        ESTAB,
        NOTA,
        CNPJ_EMITENTE,
        IE,
        CMUN,  STATUS
),

CIDADES AS (
    SELECT
    CIDADE,
    (CASE 
    WHEN LENGTH(cidade.IBGE) = 3 THEN UF.CODIGO||'00'||cidade.IBGE 
    WHEN LENGTH(cidade.IBGE) = 4 THEN UF.CODIGO||'0'||cidade.IBGE
    WHEN LENGTH(cidade.IBGE) = 2 THEN UF.CODIGO||'000'||cidade.IBGE 
    WHEN LENGTH(cidade.IBGE) = 1 THEN UF.CODIGO||'0000'||cidade.IBGE            
    ELSE UF.CODIGO||''||cidade.IBGE 
    END) CODCID
    FROM CIDADE
    LEFT JOIN UF ON UF.UF = CIDADE.UF
),

SIEG_ITENS AS (
    SELECT
    ESTAB,
    CHAVE,
    SEQNOTAITEM,
    CFOP,
    UNIDADE,
    LPAD(NCM,4) AS NCM,
    (CASE WHEN LENGTH(icmscdcst) >=4 THEN '9999' ELSE icmscdcst END) CST_ICMS,
 --   icmscdcst AS CST_ICMS,
    icmsbase,
    icmstaxa AS ALIQUOTA_ICMS,
    piscdcst AS CST_PIS,
    pistaxa AS ALIQUOTA_PIS,
    cofinscdcst AS CST_COFINS,
    cofinstaxa AS ALIQUOTA_COFINS,
    PISVALOR,
    COFINSVALOR,
  (
    CASE 
        WHEN CODSITUACAO IS NOT NULL THEN 9999 
        WHEN LENGTH(icmscdcst) >= 4 THEN 9999
        ELSE CAST(icmscdcst AS NUMBER) 
    END) as CODSITUACAO,
    
   CAST(
    CASE WHEN LENGTH(icmscdcst) >=4 THEN '0' ELSE piscdcst END 
    AS NUMBER
    ) CSTITENS
    FROM U_NOTASSIEG_ITENS 
    
),

PRODUTOR AS (
    SELECT
        NUMEROCM,
        CIDADE,
        inscestad,
        CASE WHEN PRODUTOR = 'S' THEN 'PRODUTOR' ELSE 'EMPRESA' END AS TIPO
    FROM CONTAMOV
),

ENDERECOS AS (
    SELECT
        NUMEROCM,
        SEQENDERECO,
        CIDADE,
        credencialagro,
        CASE WHEN PRODUTORend = 'S' THEN 'PRODUTOR' ELSE 'EMPRESA' END AS TIPO
    FROM ENDERECO
),
/*
IMPOSTOS AS (
    SELECT
    ESTAB,
    SEQNOTA,
    SEQNOTAITEM,
    MAX(CASE WHEN IMPOSTO = 1 THEN CST END) CST_ICMS,
    MAX(CASE WHEN IMPOSTO = 4 THEN CST END) CST_PIS,
    MAX(CASE WHEN IMPOSTO = 5 THEN CST END) CST_COFINS,
    MAX(CASE WHEN IMPOSTO = 4 THEN ALIQUOTA END) ALIQUOTA_PIS,
    MAX(CASE WHEN IMPOSTO = 5 THEN ALIQUOTA  END) ALIQUOTA_COFINS,
    MAX(CASE WHEN IMPOSTO = 1 THEN ALIQUOTA END) ALIQUOTA_ICMS
    FROM NFITEMIMPOSTO

    WHERE
    imposto in (1,4,5)

    GROUP BY
    ESTAB,
    SEQNOTA,
    SEQNOTAITEM
),*/

ICMS AS (
    SELECT
    ESTAB,
    SEQNOTA,
    SEQNOTAITEM,
    IMPOSTO,
    CST,
    ALIQUOTA,
    BASETRIBUTADA,
    VALORIMPOSTO
    FROM NFITEMIMPOSTO
    WHERE IMPOSTO = 1
),

PIS AS (
    SELECT
    ESTAB,
    SEQNOTA,
    SEQNOTAITEM,
    IMPOSTO,
    CST,
    ALIQUOTA,
    BASETRIBUTADA,
    VALORIMPOSTO
    FROM NFITEMIMPOSTO
    WHERE IMPOSTO = 4
),

COFINS AS (
    SELECT
    ESTAB,
    SEQNOTA,
    SEQNOTAITEM,
    IMPOSTO,
    CST,
    ALIQUOTA,
    BASETRIBUTADA,
    VALORIMPOSTO
    FROM NFITEMIMPOSTO
    WHERE IMPOSTO = 5
),

ITENS_MARCADOS AS (
    SELECT distinct
        ITEM,
        1 AS FLAG_REGRADO
    FROM U_REGRAS_NOTA
),

NCM_MARCADOS AS (
    SELECT DISTINCT
    NCM,
    1 AS FLAG_REGRADO
    FROM U_REGRAS_NOTA
),

NFCABPRODUTOR_AJUSTADO AS (
    SELECT
    ESTAB,
    SEQNOTA,
    NFPRODUTOR,
    CHAVEACESSONFP,
    CASE WHEN SUBSTR(SERIENFPRODUTOR,0,1) = '0' AND LENGTH(SERIENFPRODUTOR) > 1 THEN substr(serienfprodutor,2,length(serienfprodutor)) ELSE serienfprodutor END serienfprodutor
    FROM NFCABPRODUTOR
)

select DISTINCT
*
from(

SELECT --DISTINCT
coalesce(ENDE.TIPO,MOV.TIPO) as tipo,
--R.UF AS UF_2,
CID.UF,
NFCAB.ESTAB,
NFCAB.NOTA,
  null as STATUS,
--  CASE WHEN NVL(SIEG.STATUS,100) = 101 THEN 'CANCELADA' ELSE 'OK' END STATUS,
COALESCE(NFCAB_U.USER_ORIGEM,NFCAB.USERID) AS USUARIO,
  case when NFCABPRODUTOR.NFPRODUTOR is null then 'N'
  	WHEN NFCABPRODUTOR.NFPRODUTOR <> sieg.NOTA THEN 'S'
  ELSE 'N' END DIF_NOTA_REF,
  case when coalesce(nf.dtemissao,nfcab.dtemissao) <> sieg.dtemissao then 'S' ELSE 'N' end dif_emissao,
  CASE 
  WHEN coalesce(ENDE.TIPO,MOV.TIPO) = 'PRODUTOR' THEN 'N'	
  WHEN NFCAB.ESTAB <> coalesce(SIEG.ESTAB,0) THEN 'S' ELSE 'N' END DIFESTAB,
  NFCFG.NOTACONF||'-'||NFCFG.DESCRICAO AS CONFIG,
  COALESCE(NF.SERIE,NFCAB.SERIE) AS SERIE,
  SIEG.SERIE AS SERIE_FISCALIO,
NFCAB.CHAVEACESSONFE,
NFCABPRODUTOR.CHAVEACESSONFP AS CHAVE_PRODUTOR,
--NF.SEQNOTA,
NFCAB.NUMEROCM,
COALESCE(NFCAB.SEQENDERECO,0)SEQENDERECO,
--nfcab.notaconf,
--ITEMAGRO.ITEM,
LPAD(ITEMAGRO.NCM,4) AS NCM_NOTA,
SIEG_ITENS.NCM AS NCM_FISCALIO,
----- valida cfop
SIEG_ITENS.CFOP AS CFOP_FISCALIO,
NFITEM.CFOP as CFOP_NOTA,
cfopos as CFOP_REGRA,
CASE
        when R.UF is null then 'S' 
        WHEN INSTR(',' || REPLACE(cfopos, ' ', '')|| ',', ',' || TO_CHAR(NFITEM.CFOP) || ',') > 0 THEN 'N'
        ELSE 'S'
    END AS DIF_CFOP,
---- valida cst icms
SIEG_ITENS.CST_ICMS AS CST_ICMS_FISCALIO,
cast(ICMS.CST as number) AS CST_ICMS_NOTA,
cast(R.CSTOS as number) AS CST_REGRA,
CASE WHEN R.CSTOS IS NULL THEN 'S'
    when cast(R.CSTOS as number) <> cast(ICMS.CST as number) THEN 'S' 
    ELSE 'N' END DIF_CST,
CASE
    when R.UF is null then 'S' 
    WHEN SUBSTR(ICMS.CST,-2) IN ('00','20') and coalesce(icmsbase,0) <> icms.basetributada then 'S'
    ELSE 'N'
end DIF_BASE_CST,
 CASE
   -- when R.UF is null then NULL 
    WHEN SUBSTR(ICMS.CST,-2) IN ('00','20') and coalesce(icmsbase,0) <> icms.basetributada then coalesce(icmsbase,0) - coalesce(icms.basetributada,0)
end VLR_DIF_BASE_CST,
------ valida cst piscofins
SIEG_ITENS.CST_PIS AS CST_PIS_FISCALIO,
SIEG_ITENS.CST_COFINS AS CST_COFINS_FISCALIO,
pis.CST as CST_PIS_NOTA,
COFINS.CST as CST_COFINS_NOTA,
R.CSTPISCOFINSOS as REGRA_CST_PISCOFINS,
CASE when R.UF is null then 'S' 
    when  R.CSTPISCOFINSOS is null or R.CSTPISCOFINSOS is null then 'S'
    WHEN R.CSTPISCOFINSOS <> PIS.CST OR R.CSTPISCOFINSOS <> COFINS.CST THEN 'S' 
ELSE 'N' END DIF_CST_PISCONFIS,
----- VALIDA CALCULO PISCONFIS CST 50
PIS.ALIQUOTA AS ALIQUOTA_PIS_NOTA,
COFINS.ALIQUOTA AS ALIQUOTA_COFINS_NOTA,
CASE
    when R.UF is null then 'S' 
    WHEN (PIS.CST <> '50' OR COFINS.CST <> '50') THEN 'N'
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) = PIS.VALORIMPOSTO THEN 'N'
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) <> PIS.VALORIMPOSTO THEN 'S'
END DIF_CST_50_PISCOFINS,
 CASE
  --  when R.UF is null then NULL
    WHEN (PIS.CST <> '50' OR COFINS.CST <> '50') THEN NULL
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) = PIS.VALORIMPOSTO THEN NULL
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) <> PIS.VALORIMPOSTO THEN (PIS.BASETRIBUTADA * 0.0925) - PIS.VALORIMPOSTO 
END VLR_CST_50_PISCOFINS,
---- VALIDA VALOR PIS COFINS
CASE 
    --when R.UF is null then 'S' 
    WHEN COALESCE(SIEG_ITENS.COFINSVALOR,0) <> COALESCE(COFINS.VALORIMPOSTO,0)  THEN 'S'
    WHEN COALESCE(SIEG_ITENS.PISVALOR,0) <> COALESCE(PIS.VALORIMPOSTO,0) THEN 'S'
    ELSE 'N'
END DIF_VLR_PISCOFINS,
CASE 
   -- when R.UF is null then NULL
    WHEN COALESCE(SIEG_ITENS.COFINSVALOR,0) <> COALESCE(COFINS.VALORIMPOSTO,0)  THEN COALESCE(SIEG_ITENS.COFINSVALOR,0) - COALESCE(COFINS.VALORIMPOSTO,0)
    WHEN COALESCE(SIEG_ITENS.PISVALOR,0) <>  COALESCE(PIS.VALORIMPOSTO,0)  THEN COALESCE(SIEG_ITENS.PISVALOR,0)  - COALESCE(PIS.VALORIMPOSTO,0)
END VLRS_PISCOFINS,
----- valida valor
case when coalesce(arredondar(nfcab.valor,2),arredondar(nf.valor,2) ) <> arredondar(SIEG.VNF,2) then 'S' else 'N' end dif_valor,
coalesce(arredondar(nfcab.valor,2),arredondar(nf.valor,2) ) - arredondar(SIEG.VNF,2) as valor_diferenca,
------- valida cidade
CASE WHEN NFCAB.clienteimp is not null THEN CIDS.CODCID ELSE CIDADES.CODCID END cidade_nota,
SIEG.CMUN as cidade_fiscalio, 
CASE 
    when NFCAB.clienteimp is not null and CIDS.CODCID = SIEG.CMUN THEN 'N'
    WHEN CIDADES.CODCID <> SIEG.CMUN THEN 'S' ELSE 'N' END DIF_CID,
----- valida inscrição estudal
CASE WHEN NFCAB.clienteimp IS NOT NULL THEN filial.INSCEST ELSE coalesce(trim(ende.credencialagro),trim(MOV.inscestad)) END IE_NOTA,
(SIEG.ie) AS IE_FISCALIO,
--case when coalesce(trim(ende.credencialagro),trim(MOV.inscestad)) <> cast(SIEG.ie as number) then 'S' ELSE 'N' end dif_ie,
CASE
    WHEN TRANSLATE(filial.INSCEST, '0123456789', '0000000000') = filial.INSCEST
         AND TRANSLATE(SIEG.ie, '0123456789', '0000000000') = SIEG.ie
         AND TO_NUMBER(filial.INSCEST) = TO_NUMBER(SIEG.ie)
         AND NFCAB.clienteimp < 100
    THEN 'N'

    WHEN TRANSLATE(coalesce(trim(ende.credencialagro), trim(MOV.inscestad)),
                   '0123456789', '0000000000')
         = coalesce(trim(ende.credencialagro), trim(MOV.inscestad))
         AND TRANSLATE(SIEG.ie, '0123456789', '0000000000') = SIEG.ie
         AND TO_NUMBER(coalesce(trim(ende.credencialagro), trim(MOV.inscestad)))
               <> TO_NUMBER(SIEG.ie)
         AND COALESCE(NFCAB.clienteimp,101) < 100
    THEN 'S'

    ELSE 'N'
END AS DIF_IE
/*,
nfcab.chaveacessonfe,
nf.chaveacessonfe as chave_2,
NFCABPRODUTOR.CHAVEACESSONFP*/
FROM NFCAB_FILTRADA NFCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN CIDADE CID ON CID.CIDADE = FILIAL.CIDADE
LEFT JOIN CIDADES CIDS ON CIDS.CIDADE = FILIAL.CIDADE
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

INNER JOIN NFITEM ON
    NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    
LEFT JOIN NFCAB_U ON
    NFCAB_U.ESTAB = NFCAB.ESTAB
    AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM

INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.FISCAL = 'S'
            AND NFCFG.ENTRADASAIDA = 'E'

INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF

INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID

----- TUDO EM RELAÇÃO A NOTA DO PRODUTOR
LEFT JOIN NFCABPRODUTOR_AJUSTADO NFCABPRODUTOR ON
    NFCABPRODUTOR.ESTAB = NFCAB.ESTAB
    AND NFCABPRODUTOR.SEQNOTA = NFCAB.SEQNOTA

LEFT JOIN NFCAB NF ON NF.ESTAB = NFCABPRODUTOR.ESTAB
            AND CAST(NF.NOTA AS VARCHAR(15))= NFCABPRODUTOR.NFPRODUTOR
            AND NF.NUMEROCM = NFCAB.NUMEROCM

LEFT JOIN NFITEM NFI ON 
    NFI.ESTAB = NF.ESTAB
    AND NFI.SEQNOTA = NF.SEQNOTA

LEFT JOIN NFCFG CFG ON CFG.NOTACONF = NFCAB.NOTACONF

LEFT JOIN PRODUTOR MOV ON MOV.NUMEROCM = NFCAB.NUMEROCM

LEFT JOIN ENDERECOS ENDE ON ENDE.NUMEROCM = NFCAB.NUMEROCM
                    AND ENDE.SEQENDERECO = NFCAB.SEQENDERECO

LEFT JOIN CIDADES ON CIDADES.CIDADE = COALESCE(ENDE.CIDADE,MOV.CIDADE)

LEFT JOIN SIEG ON --SIEG.ESTAB = NFCAB.ESTAB
                   -- AND SIEG.NOTA = NF.NOTA
                     SIEG.CHAVEACESSONFE = COALESCE(NFCABPRODUTOR.CHAVEACESSONFP,NFCAB.CHAVEACESSONFE)
                    AND SIEG.SERIE = coalesce(NFCABPRODUTOR.serienfprodutor,NFCAB.SERIE)
  	and SIEG.ESTAB = coalesce(nf.estab,NFCAB.ESTAB)

LEFT JOIN ICMS ON
    ICMS.ESTAB = NFITEM.ESTAB
    AND ICMS.SEQNOTA = NFITEM.SEQNOTA
    AND ICMS.SEQNOTAITEM = NFITEM.SEQNOTAITEM

LEFT JOIN PIS ON
    PIS.ESTAB = NFITEM.ESTAB
    AND PIS.SEQNOTA = NFITEM.SEQNOTA
    AND PIS.SEQNOTAITEM = NFITEM.SEQNOTAITEM

LEFT JOIN COFINS ON
    COFINS.ESTAB = NFITEM.ESTAB
    AND COFINS.SEQNOTA = NFITEM.SEQNOTA
    AND COFINS.SEQNOTAITEM = NFITEM.SEQNOTAITEM

INNER JOIN SIEG_ITENS ON
   -- NFITEM.ESTAB = SIEG_ITENS.ESTAB
       COALESCE(NFCABPRODUTOR.CHAVEACESSONFP,NFCAB.CHAVEACESSONFE) = SIEG_ITENS.CHAVE

LEFT JOIN ITENS_MARCADOS MARC ON MARC.ITEM = COALESCE(NFITEM.ITEM,NFI.ITEM)
LEFT JOIN NCM_MARCADOS NCM_MARC ON NCM_MARC.NCM = SIEG_ITENS.NCM

LEFT JOIN OS_REGRA_NOTA_2 R ON
    R.UF = CID.UF
    AND R.ITEM = COALESCE(MARC.ITEM,0)
    AND R.CFOPFORNECEDOR = SIEG_ITENS.CFOP
    AND R.NCM = COALESCE(NCM_MARC.NCM,'0')--SIEG_ITENS.NCM
    AND CAST(R.CSTFORNECEDOR AS NUMBER) = SIEG_ITENS.CODSITUACAO--(CASE WHEN SIEG_ITENS.CODSITUACAO IS NOT NULL THEN 9999 ELSE CAST(SIEG_ITENS.CST_ICMS AS NUMBER) END)
    AND TRIM(R.ORIGEM) = TRIM(coalesce(ENDE.TIPO,MOV.TIPO))
    AND CAST(R.CSTPISCOFIS AS NUMBER) =  SIEG_ITENS.CSTITENS--CAST(CASE WHEN LENGTH(SIEG_ITENS.CST_ICMS)>=4 THEN '0' ELSE (SIEG_ITENS.CST_PIS) END AS NUMBER)
    and R.ORIGEM  IN ('EMPRESA','PRODUTOR')

WHERE
U_TEMPRESA.GRAOS = 'S'
-- AND NOT (CID.UF = 'MG' and (coalesce(nf.notaconf,0) = 320 OR coalesce(NFCAB.NOTACONF,0) = 320))
AND NOT (CID.UF = 'MG' and (coalesce(NFCAB.NOTACONF,0) = 320))
  AND (NFCAB.ESTAB IN (:ESTAB) OR 0 IN (:ESTAB))
AND (CID.UF IN (:UF) OR 'X' IN (:UF))

and nfcab.notaconf in (200,201,202,203,214,216,217,220,221,225,232,234,237,243,244,247,252,254,255,261,268,269,270,272,274,275,278,280,282,283,284,285,286,287,289,290,292,293,304,307,312,314,315,316,317,318,319,320,321,323,324,325,329,334,335,337,338,339,357,383,384,385,387,389,391,392,393,395,396,397,398,1017,1020,1023,1037,1038,1039,1041,1044)
and nfcab.estab not in (5,81)

UNION ALL


SELECT --DISTINCT
coalesce(ENDE.TIPO,MOV.TIPO) as tipo,
--R.UF AS UF_2,
CID.UF,
NFCAB.ESTAB,
NFCAB.NOTA,
  null as STATUS,
  --  CASE WHEN NVL(SIEG.STATUS,100) = 101 THEN 'CANCELADA' ELSE 'OK' END STATUS,
COALESCE(NFCAB_U.USER_ORIGEM,NFCAB.USERID) AS USUARIO,
    case when NFCABPRODUTOR.NFPRODUTOR is null then 'N'
  	WHEN NFCABPRODUTOR.NFPRODUTOR <> sieg.NOTA THEN 'S'
  ELSE 'N' END DIF_NOTA_REF,
  case when coalesce(nf.dtemissao,nfcab.dtemissao) <> sieg.dtemissao then 'S' ELSE 'N' end dif_emissao,
    CASE 
  WHEN coalesce(ENDE.TIPO,MOV.TIPO) = 'PRODUTOR' THEN 'N'	
  WHEN NFCAB.ESTAB <> SIEG.ESTAB THEN 'S' ELSE 'N' END DIFESTAB,
  NFCFG.NOTACONF||'-'||NFCFG.DESCRICAO AS CONFIG,
  COALESCE(NF.SERIE,NFCAB.SERIE) AS SERIE,
  SIEG.SERIE AS SERIE_FISCALIO,
NFCAB.CHAVEACESSONFE,
NFCABPRODUTOR.CHAVEACESSONFP AS CHAVE_PRODUTOR,
--NF.SEQNOTA,
NFCAB.NUMEROCM,
COALESCE(NFCAB.SEQENDERECO,0) SEQENDERECO,
--nfcab.notaconf,
--ITEMAGRO.ITEM,
LPAD(ITEMAGRO.NCM,4) AS NCM_NOTA,
SIEG_ITENS.NCM AS NCM_FISCALIO,
----- valida cfop
 SIEG_ITENS.CFOP AS CFOP_FISCALIO,
NFI.CFOP as CFOP_NOTA,
'1949' as CFOP_REGRA,
CASE
        when NFI.CFOP <> '1949' THEN 'S'
        ELSE 'N'
    END AS DIF_CFOP,
---- valida cst icms
SIEG_ITENS.CST_ICMS AS CST_ICMS_FISCALIO,
cast(ICMS.CST as number) AS CST_ICMS_NOTA,
90 AS CST_REGRA,
CASE 
    when 90 <> cast(ICMS.CST as number) THEN 'S' 
    ELSE 'N' END DIF_CST,
    
CASE
    WHEN SUBSTR(SIEG_ITENS.CST_ICMS,-2) IN ('00','20') and coalesce(icmsbase,0) <> icms.basetributada then 'S'
    ELSE 'N'
end DIF_BASE_CST,
CASE

    WHEN SUBSTR(ICMS.CST,-2) IN ('00','20') and coalesce(icmsbase,0) <> icms.basetributada then icmsbase - icms.basetributada
end VLR_DIF_BASE_CST,
------ valida cst piscofins
SIEG_ITENS.CST_PIS AS CST_PIS_FISCALIO,
SIEG_ITENS.CST_COFINS AS CST_COFINS_FISCALIO,
pis.CST as CST_PIS_NOTA,
COFINS.CST as CST_COFINS_NOTA,
'98' as REGRA_CST_PISCOFINS,
CASE 
    WHEN 98 <> TO_NUMBER(PIS.CST) OR TO_NUMBER(COFINS.CST) <> 98 THEN 'S' 
ELSE 'N' END DIF_CST_PISCONFIS,
----- VALIDA CALCULO PISCONFIS CST 50
PIS.ALIQUOTA AS ALIQUOTA_PIS_NOTA,
COFINS.ALIQUOTA AS ALIQUOTA_COFINS_NOTA,
CASE
    WHEN (PIS.CST <> '50' OR COFINS.CST <> '50') THEN 'N'
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) = PIS.VALORIMPOSTO THEN 'N'
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) <> PIS.VALORIMPOSTO THEN 'S'
END DIF_CST_50_PISCOFINS,
CASE
    WHEN (PIS.CST <> '50' OR COFINS.CST <> '50') THEN NULL
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) = PIS.VALORIMPOSTO THEN NULL
    WHEN (PIS.CST = '50' OR COFINS.CST = '50') AND (PIS.BASETRIBUTADA * 0.0925) <> PIS.VALORIMPOSTO THEN (PIS.BASETRIBUTADA * 0.0925) - PIS.VALORIMPOSTO 
END VLR_CST_50_PISCOFINS,
---- VALIDA VALOR PIS COFINS
CASE 
    --when R.UF is null then 'S' 
    WHEN COALESCE(SIEG_ITENS.COFINSVALOR,0) <> COALESCE(COFINS.VALORIMPOSTO,0)  THEN 'S'
    WHEN COALESCE(SIEG_ITENS.PISVALOR,0) <> COALESCE(PIS.VALORIMPOSTO,0) THEN 'S'
    ELSE 'N'
END DIF_VLR_PISCOFINS,
CASE 
   -- when R.UF is null then NULL
    WHEN COALESCE(SIEG_ITENS.COFINSVALOR,0) <> COALESCE(COFINS.VALORIMPOSTO,0)  THEN COALESCE(SIEG_ITENS.COFINSVALOR,0) - COALESCE(COFINS.VALORIMPOSTO,0)
    WHEN COALESCE(SIEG_ITENS.PISVALOR,0) <>  COALESCE(PIS.VALORIMPOSTO,0)  THEN COALESCE(SIEG_ITENS.PISVALOR,0)  - COALESCE(PIS.VALORIMPOSTO,0)
END VLRS_PISCOFINS,
----- valida valor
case when arredondar(nf.valor,2) <> arredondar(SIEG.VNF,2) then 'S' else 'N' end dif_valor,
arredondar(nf.valor,2) - arredondar(SIEG.VNF,2) as valor_diferenca,
------- valida cidade
CIDADES.CODCID AS cidade_nota,
SIEG.CMUN as cidade_fiscalio, 
CASE WHEN CIDADES.CODCID <> SIEG.CMUN THEN 'S' ELSE 'N' END DIF_CID,
----- valida inscrição estudal
coalesce(trim(ende.credencialagro),trim(MOV.inscestad)) as IE_NOTA,
(SIEG.ie)  AS IE_FISCALIO,
CASE
  WHEN REGEXP_LIKE(coalesce(trim(ende.credencialagro), trim(MOV.inscestad)), '^\d+$') 
       AND REGEXP_LIKE(SIEG.ie, '^\d+$')
       AND TO_NUMBER(coalesce(trim(ende.credencialagro), trim(MOV.inscestad))) <> TO_NUMBER(SIEG.ie)
  THEN 'S'
  ELSE 'N'
END AS DIF_IE
/*,
--case when cast(coalesce(trim(ende.credencialagro),trim(MOV.inscestad)) as number) <> cast(SIEG.ie as number) then 'S' ELSE 'N' end dif_ie,
nfcab.chaveacessonfe,
nf.chaveacessonfe as chave_2,
NFCABPRODUTOR.CHAVEACESSONFP*/
FROM NFCAB_FILTRADA NFCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN CIDADE CID ON CID.CIDADE = FILIAL.CIDADE
INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

INNER JOIN NFITEM ON
    NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
    
LEFT JOIN NFCAB_U ON
    NFCAB_U.ESTAB = NFCAB.ESTAB
    AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM

INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
            AND NFCFG.FISCAL = 'S'
            AND NFCFG.ENTRADASAIDA = 'E'

INNER JOIN NFCFG_U ON NFCFG_U.NOTACONF = NFCFG.NOTACONF

INNER JOIN U_TIPOOP ON U_TIPOOP.U_TIPOOP_ID = NFCFG_U.U_TIPOOP_ID

----- TUDO EM RELAÇÃO A NOTA DO PRODUTOR
LEFT JOIN NFCABPRODUTOR_AJUSTADO NFCABPRODUTOR ON
  NFCABPRODUTOR.ESTAB = NFCAB.ESTAB
     AND CAST(NFCAB.NOTA AS VARCHAR(15))= NFCABPRODUTOR.NFPRODUTOR
  --  NFCABPRODUTOR.ESTAB = NFCAB.ESTAB
    --AND NFCABPRODUTOR.SEQNOTA = NFCAB.SEQNOTA

INNER JOIN NFCAB NF ON NF.ESTAB = NFCABPRODUTOR.ESTAB
            AND CAST(NF.NOTA AS VARCHAR(15))= NFCABPRODUTOR.NFPRODUTOR
            AND NF.NUMEROCM = NFCAB.NUMEROCM

INNER JOIN NFITEM NFI ON 
    NFI.ESTAB = NF.ESTAB
    AND NFI.SEQNOTA = NF.SEQNOTA

LEFT JOIN NFCFG CFG ON CFG.NOTACONF = NF.NOTACONF

LEFT JOIN PRODUTOR MOV ON MOV.NUMEROCM = NF.NUMEROCM

LEFT JOIN ENDERECOS ENDE ON ENDE.NUMEROCM = NF.NUMEROCM
                    AND ENDE.SEQENDERECO = NF.SEQENDERECO

LEFT JOIN CIDADES ON CIDADES.CIDADE = COALESCE(ENDE.CIDADE,MOV.CIDADE)

INNER JOIN SIEG ON /*SIEG.ESTAB = NF.ESTAB
                    AND*/ SIEG.NOTA = NF.NOTA
                    AND SIEG.CHAVEACESSONFE = COALESCE(NFCABPRODUTOR.CHAVEACESSONFP,NFCAB.CHAVEACESSONFE)--,NF.CHAVEACESSONFE)
                    AND SIEG.SERIE = coalesce(NFCABPRODUTOR.serienfprodutor,NFCAB.SERIE)

LEFT JOIN ICMS ON
    ICMS.ESTAB = NFI.ESTAB
    AND ICMS.SEQNOTA = NFI.SEQNOTA
    AND ICMS.SEQNOTAITEM = NFI.SEQNOTAITEM

LEFT JOIN PIS ON
    PIS.ESTAB = NFI.ESTAB
    AND PIS.SEQNOTA = NFI.SEQNOTA
    AND PIS.SEQNOTAITEM = NFI.SEQNOTAITEM

LEFT JOIN COFINS ON
    COFINS.ESTAB = NFI.ESTAB
    AND COFINS.SEQNOTA = NFI.SEQNOTA
    AND COFINS.SEQNOTAITEM = NFI.SEQNOTAITEM

INNER JOIN SIEG_ITENS ON
   -- NFI.ESTAB = SIEG_ITENS.ESTAB
     /*coalesce(*/NFCABPRODUTOR.CHAVEACESSONFP/*,NF.CHAVEACESSONFE)*/ = SIEG_ITENS.CHAVE

LEFT JOIN ITENS_MARCADOS MARC ON MARC.ITEM = NFI.ITEM
LEFT JOIN NCM_MARCADOS NCM_MARC ON NCM_MARC.NCM = SIEG_ITENS.NCM

WHERE
U_TEMPRESA.GRAOS = 'S'
--AND  (CID.UF = 'MG' and (coalesce(nf.notaconf,0) = 320 OR coalesce(NFCAB.NOTACONF,0) = 320))
AND NFCAB.NOTACONF = 320
  AND (NFCAB.ESTAB IN (:ESTAB) OR 0 IN (:ESTAB))
AND (CID.UF IN (:UF) OR 'X' IN (:UF))
AND coalesce(ENDE.TIPO,MOV.TIPO) = 'PRODUTOR'
and nfcab.estab not in (5,81)

)

WHERE
DIF_CFOP = 'S'
OR 
DIF_CST = 'S'
OR
DIF_BASE_CST = 'S'
OR
DIF_CST_PISCONFIS = 'S'
OR
DIF_CST_50_PISCOFINS = 'S'
OR
DIF_VLR_PISCOFINS = 'S'
OR
dif_valor = 'S'
OR
DIF_CID = 'S'
OR
DIF_IE = 'S' --OR STATUS = 101