SELECT
*
FROM(
SELECT
FILIAL.ESTAB,
FILIAL.REDUZIDO,
PEDCAB.SERIE||'-'||PEDCAB.NUMERO AS PEDIDO,
PEDCFG.PEDIDOCONF||'-'||PEDCFG.DESCRICAO AS CONFIG,
TO_CHAR(PEDCAB.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
TO_CHAR(COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO),'DD/MM/YYYY') AS VENCIMENTO
FROM PEDCAB

INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF

INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

INNER JOIN NOTIFICAESTRATEGIA N ON
    N.ESTAB = PEDCAB.ESTAB
    AND N.SERIE = PEDCAB.SERIE
    AND N.NUMERO = PEDCAB.NUMERO

INNER JOIN NOTIFICAESTRADET DET ON
    DET.IDNOTIFICA = N.IDNOTIFICA

LEFT JOIN (
    SELECT
    ESTAB,
    SERIE,
    NUMERO,
    MAX(PRAZOPAGAMENTO) AS PRAZO
    FROM PEDCABPGTO
    GROUP BY
    ESTAB,SERIE,NUMERO
    )MAXPRAZO ON
    MAXPRAZO.ESTAB = PEDCAB.ESTAB
    AND MAXPRAZO.SERIE = PEDCAB.SERIE
    AND MAXPRAZO.NUMERO = PEDCAB.NUMERO

  LEFT JOIN 
    (
    SELECT
    ESTAB,
    SERIE,
    NUMERO,
    IDGRPAPROVADORES,
    USERID,
    MAX(IDNOTIFICA)NOTIFICA
    FROM NOTIFICAESTRATEGIA
    GROUP BY
    ESTAB,
    SERIE,
    NUMERO,
    IDGRPAPROVADORES,
    USERID
    )NOTIFICAESTRATEGIA ON 
    NOTIFICAESTRATEGIA.ESTAB = PEDCAB.ESTAB
    AND NOTIFICAESTRATEGIA.SERIE = PEDCAB.SERIE
    AND NOTIFICAESTRATEGIA.NUMERO = PEDCAB.NUMERO

LEFT JOIN NOTIFICAESTRADET ON NOTIFICAESTRADET.IDNOTIFICA =  NOTIFICAESTRATEGIA.NOTIFICA
  
WHERE
DET.STATUSAPROVACAO = 2
AND PEDCAB.STATUS NOT IN ('B','C')
AND PEDCAB.PEDIDOCONF IN (54, 57, 80, 82, 66, 81,67)
  and NOTIFICAESTRADET.STATUSAPROVACAO = 2
/*
<#if CONFIG?has_content>
         AND PEDCFG.PEDIDOCONF IN (:CONFIG)
          </#if>*/

/*
<#if ESTAB?has_content>
        AND FILIAL.ESTAB IN (:ESTAB)
          </#if>
          */
and PEDCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
--AND COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO) BETWEEN :DTINI AND :DTFIM
/*
UNION 

SELECT
FILIAL.ESTAB,
FILIAL.REDUZIDO,
PEDCAB.SERIE||'-'||PEDCAB.NUMERO AS PEDIDO,
PEDCFG.PEDIDOCONF||'-'||PEDCFG.DESCRICAO AS CONFIG,
TO_CHAR(PEDCAB.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
TO_CHAR(COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO),'DD/MM/YYYY') AS VENCIMENTO
FROM PEDCAB

INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF

INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

LEFT JOIN APRVPEDCABHIST ON 
    APRVPEDCABHIST.ESTAB = PEDCAB.ESTAB
    AND APRVPEDCABHIST.SERIE = PEDCAB.SERIE
    AND APRVPEDCABHIST.NUMERO = PEDCAB.NUMERO

LEFT JOIN (
    SELECT
    ESTAB,
    SERIE,
    NUMERO,
    MAX(PRAZOPAGAMENTO) AS PRAZO
    FROM PEDCABPGTO
    GROUP BY
    ESTAB,SERIE,NUMERO
    )MAXPRAZO ON
    MAXPRAZO.ESTAB = PEDCAB.ESTAB
    AND MAXPRAZO.SERIE = PEDCAB.SERIE
    AND MAXPRAZO.NUMERO = PEDCAB.NUMERO
    
WHERE
PEDCAB.PEDIDOCONF IN (54, 57, 80, 82, 66, 81,67,85)
--AND APRVPEDCABHIST.ETAPA IN (4)
AND PEDCAB.STATUS NOT IN ('B','C')
--AND COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO) BETWEEN :DTINI AND :DTFIM
and PEDCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
  */
)DADOS

ORDER BY CAST(VENCIMENTO AS DATE) DESC
