SELECT
  DADOS.*,
  CASE 
    WHEN (DADOS.MOTDESICMS = 7) OR (COALESCE(DADOS.VICMSDESON, 0) > 0)
    THEN '1'
    ELSE ''
  END AS INDDEDUZDESON
FROM (
  SELECT  
    NFITEM_IMP.ESTAB,
    NFITEM_IMP.SEQNOTA,
    NFITEM_IMP.SEQNOTAITEM,     
    NFITEM_IMP.CFOP, 
     PEMPRESA.CRT, 
     PEMPRESA.MSGSIMPLES,
     NFITEM_IMP.ITEM,
     NFITEM_IMP.VALORTOTAL AS VPROD,
     NFITEM_IMP.QUANTIDADE,
     COALESCE(COALESCE(INFORMACAOIBPT.VLRTRIBFEDERAL, 0) 
       + COALESCE(INFORMACAOIBPT.VLRTRIBESTADUAL,0) 
       + COALESCE(INFORMACAOIBPT.VLRTRIBMUNICIPAL,0), 0) AS VTOTTRIB,                    
     /*ICMS*/ 
     CST_ICMS.ORIGEM,
     ITEMAGRO.SERVICO,
     NFITEMIMPOSTO_ICMS.CALCAUXIMPDISP,
     NFITEMIMPOSTO_ICMS.CST,
     NFITEMIMPOSTO_ICMS.BASETRIBUTADA AS VBC,
     NFITEMIMPOSTO_ICMS.ALIQUOTA AS PICMS,
     NFITEMIMPOSTO_ICMS.ALIQUOTACALC AS PICMS_CALC,       
     NFITEMIMPOSTO_ICMS.VALORIMPOSTO AS VICMS,
     NFITEMIMPOSTO_ICMS.BASEST AS VBCST,
     NFITEMIMPOSTO_ICMS.ALIQUOTAST AS PICMSST,
     NFITEMIMPOSTO_ICMS.VALORSUBSTITUICAO AS VICMSST,
     NFITEMIMPOSTO_ICMS.BASESTRET AS VBCSTRET,
     NFITEMIMPOSTO_ICMS.VLRICMSSTRET AS VICMSSTRET,
  
     NFITEMIMPOSTO_ICMS.QBCMONO,
     NFITEMIMPOSTO_ICMS.ALIQICMSREAIS AS ADREMICMS,
     NFITEMIMPOSTO_ICMS.VICMSMONO,
     NFITEMIMPOSTO_ICMS.QBCMONORET,
     NFITEMIMPOSTO_ICMS.ALIQICMSRETREAIS AS ADREMICMSRET,
     NFITEMIMPOSTO_ICMS.VICMSMONORET,
  
     COALESCE(NFITEMIMPOSTO_ICMS.DESCFINTRIBISENT, ICMS.INATIVO_CALCAUXIMPDISP) AS DESCFINTRIBISENT,
     CASE WHEN COALESCE(NFITEMIMPOSTO_ICMS.MODBCST, 4) = 4 THEN
       CASE WHEN (NFITEMIMPOSTO_ICMS.PMVAST > 0 ) THEN
          NFITEMIMPOSTO_ICMS.PMVAST
       ELSE
          NFITEMIMPOSTO_ICMS.PERCBST
       END   
     ELSE 
       0 -- Qdo o MODBCST <> 4, manda zero no PMVAST (AGRO-9738)      
     END PMVAST,
     NFITEMIMPOSTO_ICMS.PERCBSTRED AS PREDBCST,
     COALESCE(NFITEMIMPOSTO_ICMS.MOTDESICMS, CFOP.MOTIVODESONICMS,
      CASE COALESCE(CID_END.INCENTSUFRAMA, CIDADE.INCENTSUFRAMA)
      WHEN 'S' THEN 7 ELSE 0 END) AS MOTDESICMS,
     NFITEMIMPOSTO_ICMS.VALORDESONERACAO AS VICMSDESON,
     NFITEMIMPOSTO_ICMS.MSGSUFRAMA,
     NFITEMIMPOSTO_ICMS.REDBASECALCICMS AS PREDBC, 
     NFITEMIMPOSTO_ICMS.ALIQUOTA AS PCREDSN,
     NFITEMIMPOSTO_ICMS.VALORIMPOSTO AS VCREDICMSSN,
     NFITEMIMPOSTO_ICMS.ISENTA,
     NFITEMIMPOSTO_ICMS.VALORTRIBISENTAS,
     (SELECT
         CODINFAD
      FROM NFITEMIMPSPED 
      WHERE (NFITEMIMPOSTO_ICMS.ESTAB       = NFITEMIMPSPED.ESTAB)
        AND (NFITEMIMPOSTO_ICMS.SEQNOTA     = NFITEMIMPSPED.SEQNOTA)
        AND (NFITEMIMPOSTO_ICMS.SEQNOTAITEM = NFITEMIMPSPED.SEQNOTAITEM)   
        AND (NFITEMIMPOSTO_ICMS.IMPOSTO     = NFITEMIMPSPED.IMPOSTO)
        AND (COALESCE(NFITEMIMPSPED.RBC, 0) = 1)     
        AND (ROWNUM = 1)
     ) AS CBENEFRBC,
     CASE (SELECT RETORNA_UTILIZA_ICMS51RESUMIDO(NFCAB.ESTAB , NFCAB.SEQNOTA) FROM dual)
       WHEN 'S' THEN NFITEMIMPOSTO_ICMS.BASETRIBUTADA
       ELSE (
           NFITEMIMPOSTO_ICMS.BASETRIBUTADA + 
           NFITEMIMPOSTO_ICMS.ISENTA + 
           DECODE (COALESCE(NFCFG.PERMREDBASECOMDIFICMS, 0), 0, NFITEMIMPOSTO_ICMS.OUTRA, (NFITEMIMPOSTO_ICMS.OUTRA - NFITEMIMPOSTO_ICMS.VLRBASECALCICMS * NFITEMIMPOSTO_ICMS.PDIF / 100)))
     END AS VBCOP51,  
     
     NFITEMIMPOSTO_ICMS.VIMPOSTOOP AS VICMSOP,
     NFITEMIMPOSTO_ICMS.PDIF,
     NFITEMIMPOSTO_ICMS.VIMPOSTODIF AS VICMSDIF, 
     3 AS MODBC,     --Gravar valor pauta NfItemImposto
     COALESCE(NFITEMIMPOSTO_ICMS.MODBCST, 4) AS MODBCST,   --Gravar valor pauta NfItemImposto
      --4=Margem Valor Agregado (%);
      --5=Pauta (valor);
      --se tributou por Pauta manda 5 senão 4
     '  ' AS UFST,  
     0.0 AS PBCOP, 
     0.0 AS VBCSTDEST,  --Informar o valor da BC do ICMS ST da UF destino (v2.0)
     0.0 AS VICMSSTDEST,--Informar o valor do ICMS ST da UF destino (v2.0) 
     NFITEMIMPOSTO_ICMS.VBCUFDEST,  
     NFITEMIMPOSTO_ICMS.PICMSUFDEST,
     NFITEMIMPOSTO_ICMS.PICMSINTER,
     NFITEMIMPOSTO_ICMS.PICMSINTERPART,
     NFITEMIMPOSTO_ICMS.VICMSUFDEST,
     NFITEMIMPOSTO_ICMS.VICMSUFREMET,
     NFITEMIMPOSTO_ICMS.PFCPUFDEST, 
     NFITEMIMPOSTO_ICMS.VFCPUFDEST,  
     NFITEMIMPOSTO_ICMS.vBCFCPUFDest,    
     CASE          
         -- SOMENTE CST 060 E 500
         WHEN (NFITEMIMPOSTO_ICMS.CST IN ('060', '500')) 
         -- QUANDO O TIPO DA NOTA FOR NOTA, TRANSFERENCIA OU DEVOLUCAO
         AND ( (SELECT N.TIPODCTO 
                  FROM NATOPERACAO N          
                 WHERE NFCFG.NATUREZADAOPERACAO = N.NATUREZADAOPERACAO
                   AND NFCFG.ENTRADASAIDA = N.ENTRADASAIDA) IN ('N', 'T', 'D') )
         THEN (      
           (SELECT RETORNA_ULTIMO_VLR_ICMS_SUBS(NFITEM_IMP.ESTAB, NFITEM_IMP.ITEM, NFITEM_IMP.IMPOSTOICMS) FROM DUAL)
         ) 
         ELSE 0.0
     END VICMSSUBSTITUTO,   
     --Alíquota suportada pelo Consumidor Final ()
     NFITEMIMPOSTO_ICMS.PST AS pST,
     --FCP Normal
     NFITEMIMPOSTO_ICMS.BASETRIBUTADA AS vBCFCP,
     NFITEMIMPOSTO_ICMS.PFCPUFDEST AS pFCP,
     NFITEMIMPOSTO_ICMS.VFCP AS VFCP,
     --FCP ST
     NFITEMIMPOSTO_ICMS.BASEST AS vBCFCPST,
     NFITEMIMPOSTO_ICMS.PFCPST AS pFCPST,
     NFITEMIMPOSTO_ICMS.VFCPST AS VFCPST,
     --FCP ST RETIDO   
     NFITEMIMPOSTO_ICMS.BASESTRET AS vBCFCPSTRet,
     NFITEMIMPOSTO_ICMS.PFCPST    AS pFCPSTRet, 
     NFITEMIMPOSTO_ICMS.VFCPSTRET AS VFCPSTRET, 
     NFITEMIMPOSTO_ICMS.ALIQSTRET AS ALIQSTRET,  
              
     --ICMS EFETIVO       
     NFITEMIMPOSTO_ICMS.VBCEFET    AS VBCEFET,          
     NFITEMIMPOSTO_ICMS.PICMSEFET  AS PICMSEFET,        
     NFITEMIMPOSTO_ICMS.VICMSEFET  AS VICMSEFET,        
     NFITEMIMPOSTO_ICMS.PREDBCEFET AS PREDBCEFET,
     /*ISSQN*/
     NFITEMIMPOSTO_ISS.BASETRIBUTADA AS VBCISS,
     NFITEMIMPOSTO_ISS.ALIQUOTA AS VALIQISS,
     NFITEMIMPOSTO_ISS.VALORIMPOSTO AS VISSQN,
     ITEMAGRO.LISTSERV AS CLISTSERV,
     'N' AS CSITTRIB,
     NFITEMIMPOSTO_ISS.ISENTA AS VDEDUCAO,
     NFITEMIMPOSTO_ISS.OUTRA AS VOUTRO,
     0 AS VDESCINCOND,
     0.0 AS INDISSRET,
     0.0 AS VISSRET,
     1 AS INDISS,
     ITEMAGRO.LISTSERV AS CSERVICO,  
     CAST(NULL AS INTEGER) AS CMUN,   
     CAST(NULL AS INTEGER) AS CPAIS, 
     NULL AS NPROCESSO,
     1 AS INDINCENTIVO,
     0.0 AS VDESCCOND,  
     /*IPI*/
     NFITEMIMPOSTO_IPI.CST AS CSTIPI,
     '' AS CLENQ,
     '' AS CNPJPROD,
     '' AS CSELO,
     0 AS QSELO,
     NFITEMIMPOSTO_IPI.CODENQIPI AS CENQ,  
     NFITEMIMPOSTO_IPI.BASETRIBUTADA AS  VBCIPI,
     0 AS QUNID,
     0 AS VUNID,
     NFITEMIMPOSTO_IPI.ALIQUOTA AS PIPI,
     NFITEMIMPOSTO_IPI.VALORIMPOSTO AS VIPI,
     NFCFG.NACIMPEXP,
     NFCFG.ENTRADASAIDA,
     /*IOF*/
     NFITEMIMPOSTO_II.BASETRIBUTADA AS VBCII,
     (SELECT SUM(NFITEMIMPADICAO.DESCDI) FROM NFITEMIMPADICAO
       WHERE (NFITEMIMPADICAO.ESTAB = NFITEM_IMP.ESTAB)
         AND (NFITEMIMPADICAO.SEQNOTA = NFITEM_IMP.SEQNOTA)
         AND (NFITEMIMPADICAO.SEQNOTAITEM = NFITEM_IMP.SEQNOTAITEM)) AS VDESPADU,
     NFITEMIMPOSTO_II.VALORIMPOSTO AS VII,
     NFITEMIMPOSTO_IOF.VALORIMPOSTO AS VIOF,
     /*PIS*/
     NFITEMIMPOSTO_PIS.CST AS CSTPIS,
     NFITEMIMPOSTO_PIS.BASETRIBUTADA AS VBCPIS,
     NFITEMIMPOSTO_PIS.ALIQUOTA AS PPIS,
     NFITEMIMPOSTO_PIS.VALORIMPOSTO AS VPIS,
     NFITEMIMPOSTO_PIS.ALIQUOTA AS VALIQPRODPIS,
     NFITEM_IMP.QUANTIDADE AS QBCPROD,
     /*COFINS*/
     NFITEMIMPOSTO_COFINS.CST AS CSTCOFINS,
     NFITEMIMPOSTO_COFINS.BASETRIBUTADA AS VBCCOFINS,
     NFITEMIMPOSTO_COFINS.ALIQUOTA AS PCOFINS,
     NFITEMIMPOSTO_COFINS.VALORIMPOSTO AS VCOFINS,
     NFITEMIMPOSTO_COFINS.ALIQUOTA AS ALIQREAISCOFINS,
     NFITEMIMPOSTO_COFINS.ALIQUOTA AS VALIQPRODCOFINS,
     'VBC,VBCOP51,VICMS,VBCIPI,VIPI,VBCPIS,VPIS,VBCCOFINS,VCOFINS,VBCII,VII,VIOF,VBCEFET,VICMSEFET,VBCISS,VISSQN,VBCFCPSTRET,VFCPSTRET,VBCFCPST,VBCFCPST,VBCFCP,VFCP' AS RATEARIMPOSTOS 
   FROM 
   (SELECT NFITEM.*, 
         CONFAGROE.IMPOSTOICMS,
         CONFAGROE.IMPOSTOIPI,
         CONFAGROE.IMPOSTOPIS,
         CONFAGROE.IMPOSTOCOFINS, 
         CONFAGROE.IMPOSTOII,
         CONFAGROE.IMPOSTOIOF,
         CONFAGROE.IMPOSTOISS
       FROM CONFAGROE 
       INNER JOIN NFITEM ON (CONFAGROE.ESTAB = NFITEM.ESTAB)) NFITEM_IMP
    , CFOP, NFCAB, NFCFG, ITEMAGRO, PEMPRESA, CONTAMOV, CIDADE, ENDERECO
    , CIDADE CID_END, NFITEMIMPOSTO NFITEMIMPOSTO_ICMS, IMPOSTO ICMS, CST CST_ICMS
    , NFITEMIMPOSTO NFITEMIMPOSTO_IPI,  NFITEMIMPOSTO NFITEMIMPOSTO_PIS
    , NFITEMIMPOSTO NFITEMIMPOSTO_COFINS, NFITEMIMPOSTO NFITEMIMPOSTO_II
    , NFITEMIMPOSTO NFITEMIMPOSTO_IOF, NFITEMIMPOSTO NFITEMIMPOSTO_ISS
    , INFORMACAOIBPT
  WHERE (NFITEM_IMP.ESTAB = :ESTAB)
    AND (NFITEM_IMP.SEQNOTA = :IDNOTA)
    
    --INNER JOIN NFITEM_IMP
    AND (NFCAB.ESTAB = NFITEM_IMP.ESTAB)
    AND (NFCAB.SEQNOTA = NFITEM_IMP.SEQNOTA)
    --INNER JOIN CFOP
    AND (NFITEM_IMP.CFOP = CFOP.CFOP) 
    --LEFT JOIN INFORMACAOIBPT
    AND (NFITEM_IMP.ESTAB = INFORMACAOIBPT.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = INFORMACAOIBPT.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = INFORMACAOIBPT.SEQNOTAITEM(+))
    --INNER JOIN NFCFG
    AND (NFCAB.NOTACONF = NFCFG.NOTACONF)
    --INNER JOIN ITEMAGRO
    AND (ITEMAGRO.ITEM = NFITEM_IMP.ITEM)
    --INNER JOIN PEMPRESA
     AND (NFITEM_IMP.ESTAB = PEMPRESA.EMPRESA)
    --INNER JOIN CONTAMOV
     AND (CONTAMOV.NUMEROCM = NFCAB.NUMEROCM)
    --LEFT JOIN CIDADE
     AND (CONTAMOV.CIDADE = CIDADE.CIDADE(+))
    --LEFT JOIN ENDERECO
     AND (NFCAB.NUMEROCM = ENDERECO.NUMEROCM(+))
     AND (NFCAB.SEQENDERECO = ENDERECO.SEQENDERECO(+))
    --LEFT JOIN CIDADE CID_END
     AND (ENDERECO.CIDADE = CID_END.CIDADE(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_ICMS
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_ICMS.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_ICMS.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_ICMS.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOICMS = NFITEMIMPOSTO_ICMS.IMPOSTO(+))
    --LEFT JOIN IMPOSTO ICMS
    AND (NFITEMIMPOSTO_ICMS.IMPOSTO = ICMS.IMPOSTO(+))
    --LEFT JOIN CST CST_ICMS
     AND (NFITEMIMPOSTO_ICMS.CST = CST_ICMS.CST(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_IPI
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_IPI.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_IPI.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_IPI.SEQNOTAITEM(+))
    AND NFITEM_IMP.IMPOSTOIPI = (NFITEMIMPOSTO_IPI.IMPOSTO(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_PIS
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_PIS.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_PIS.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_PIS.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOPIS = NFITEMIMPOSTO_PIS.IMPOSTO(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_COFINS
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_COFINS.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_COFINS.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_COFINS.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOCOFINS = NFITEMIMPOSTO_COFINS.IMPOSTO(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_II
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_II.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_II.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_II.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOII = NFITEMIMPOSTO_II.IMPOSTO(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_IOF
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_IOF.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_IOF.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_IOF.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOIOF = NFITEMIMPOSTO_IOF.IMPOSTO(+))
    --LEFT JOIN NFITEMIMPOSTO NFITEMIMPOSTO_ISS
    AND (NFITEM_IMP.ESTAB = NFITEMIMPOSTO_ISS.ESTAB(+))
    AND (NFITEM_IMP.SEQNOTA = NFITEMIMPOSTO_ISS.SEQNOTA(+))
    AND (NFITEM_IMP.SEQNOTAITEM = NFITEMIMPOSTO_ISS.SEQNOTAITEM(+))
    AND (NFITEM_IMP.IMPOSTOISS = NFITEMIMPOSTO_ISS.IMPOSTO(+))
    
  ORDER BY NFITEM_IMP.SEQNOTAITEM

) DADOS
WHERE 0=0