SELECT
'NOTAS COMPRA DIRETA' AS TIP,
FILIAL.ESTAB,
ROMACLASSNOME.CLASSIFICACAO,
CASE WHEN ROMA.ITEM = 2 THEN ROMACLASSNOME.descricaoclassificacao ELSE ITEMAGRO.DESCRICAO END AS DESCRICAOCLASSIFICACAO,
ITEMAGRO.ITEM,
ITEMAGRO.DESCRICAO PRODUTO,
NFCFG.NOTACONF AS IDCONFIG,
NFCFG.NOTACONF||' - '||NFCFG.DESCRICAO OPERACAO,
CONTAMOV.NUMEROCM,
CONTAMOV.NUMEROCM||' - '||CONTAMOV.NOME PESSOA,
NFCAB.SEQENDERECO AS IDENDERECO,
NFCAB.SEQENDERECO||' - '||ENDERECO.ENDERECO AS ENDERECO,

ROMA.DTEMISSAO,
ROMA.ROMANEIO,
ROMA.SEQDESMEMBRADO,
COALESCE(ROMA.ROMAONOFF,0) AS OFF,
ROMA.PLACA,
(COALESCE(ROMA.PESOTOTAL,0) - COALESCE(ROMA.TARA,0)) AS PBRUTO,
  ROMA.PH,
  ROMA.FN,
/*RETORNA DADOS DE CLASSIIFICAÇÃO DE ROMANEIO*/
  COALESCE(SUM((SELECT SUM(IMP.REFTABELA) FROM ROMADESC IMP
                WHERE IMP.ESTAB        = ROMA.ESTAB
                  AND IMP.ROMANEIO     = ROMA.ROMANEIO
                  AND IMP.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND IMP.NUMEROCM     = ROMA.NUMEROCM
                  AND IMP.ROMADESC     = 1)),0) AS IMP,
COALESCE(SUM((SELECT SUM(UMID.REFTABELA) FROM ROMADESC UMID
                WHERE UMID.ESTAB        = ROMA.ESTAB
                  AND UMID.ROMANEIO     = ROMA.ROMANEIO
                  AND UMID.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND UMID.NUMEROCM     = ROMA.NUMEROCM
                  AND UMID.ROMADESC     = 2)),0) AS UMID,

COALESCE(SUM((SELECT SUM(ARD.REFTABELA) FROM ROMADESC ARD
                WHERE ARD.ESTAB        = ROMA.ESTAB
                  AND ARD.ROMANEIO     = ROMA.ROMANEIO
                  AND ARD.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND ARD.NUMEROCM     = ROMA.NUMEROCM
                  AND ARD.ROMADESC     = 3)),0) AS ARD,

COALESCE(SUM((SELECT SUM(QUEB.REFTABELA) FROM ROMADESC QUEB
                WHERE QUEB.ESTAB        = ROMA.ESTAB
                  AND QUEB.ROMANEIO     = ROMA.ROMANEIO
                  AND QUEB.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND QUEB.NUMEROCM     = ROMA.NUMEROCM
                  AND QUEB.ROMADESC     = 4)),0) AS QUEB,

COALESCE(SUM((SELECT SUM(ESVER.REFTABELA) FROM ROMADESC ESVER
                WHERE ESVER.ESTAB        = ROMA.ESTAB
                  AND ESVER.ROMANEIO     = ROMA.ROMANEIO
                  AND ESVER.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND ESVER.NUMEROCM     = ROMA.NUMEROCM
                  AND ESVER.ROMADESC     = 5)),0) AS ESVER,

COALESCE(SUM((SELECT SUM(AVAR.REFTABELA) FROM ROMADESC AVAR
                WHERE AVAR.ESTAB        = ROMA.ESTAB
                  AND AVAR.ROMANEIO     = ROMA.ROMANEIO
                  AND AVAR.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND AVAR.NUMEROCM     = ROMA.NUMEROCM
                  AND AVAR.ROMADESC     = 6)),0) AS AVAR,

COALESCE(SUM((SELECT SUM(QUEI.REFTABELA) FROM ROMADESC QUEI
                WHERE QUEI.ESTAB        = ROMA.ESTAB
                  AND QUEI.ROMANEIO     = ROMA.ROMANEIO
                  AND QUEI.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND QUEI.NUMEROCM     = ROMA.NUMEROCM
                  AND QUEI.ROMADESC     = 7)),0) AS QUEI,

COALESCE(SUM((SELECT SUM(MOF.REFTABELA) FROM ROMADESC MOF
                WHERE MOF.ESTAB        = ROMA.ESTAB
                  AND MOF.ROMANEIO     = ROMA.ROMANEIO
                  AND MOF.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND MOF.NUMEROCM     = ROMA.NUMEROCM
                  AND MOF.ROMADESC     = 8)),0) AS MOF,

COALESCE(SUM((SELECT SUM(OUT.REFTABELA) FROM ROMADESC OUT
                WHERE OUT.ESTAB        = ROMA.ESTAB
                  AND OUT.ROMANEIO     = ROMA.ROMANEIO
                  AND OUT.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND OUT.NUMEROCM     = ROMA.NUMEROCM
                  AND OUT.ROMADESC     IN (6,3,5,9))),0) AS OUT,

COALESCE(SUM((SELECT SUM(CARUN.REFTABELA) FROM ROMADESC CARUN
                WHERE CARUN.ESTAB        = ROMA.ESTAB
                  AND CARUN.ROMANEIO     = ROMA.ROMANEIO
                  AND CARUN.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND CARUN.NUMEROCM     = ROMA.NUMEROCM
                  AND CARUN.ROMADESC     = 10)),0) AS CARUN,

(COALESCE(SUM((SELECT SUM(IMP.PERCENTUAL) FROM ROMADESC IMP
                WHERE IMP.ESTAB        = ROMA.ESTAB
                  AND IMP.ROMANEIO     = ROMA.ROMANEIO
                  AND IMP.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND IMP.NUMEROCM     = ROMA.NUMEROCM
                  AND IMP.ROMADESC     = 1)),0) +
COALESCE(SUM((SELECT SUM(UMID.PERCENTUAL) FROM ROMADESC UMID
                WHERE UMID.ESTAB        = ROMA.ESTAB
                  AND UMID.ROMANEIO     = ROMA.ROMANEIO
                  AND UMID.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND UMID.NUMEROCM     = ROMA.NUMEROCM
                  AND UMID.ROMADESC     = 2)),0)) +
COALESCE(SUM((SELECT SUM(OUT.PERCENTUAL) FROM ROMADESC OUT
                WHERE OUT.ESTAB        = ROMA.ESTAB
                  AND OUT.ROMANEIO     = ROMA.ROMANEIO
                  AND OUT.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND OUT.NUMEROCM     = ROMA.NUMEROCM
                  AND OUT.ROMADESC     IN (6,3,5,9))),0) AS DESCONTO,

  ROMA.PESOLIQUIDO AS LIQUIDO,
  COALESCE(ROMA.FRETE,0)AS FRETE,
  COALESCE(ROMA.PESOFRETE,0) AS PESOFRETE,
  CONTAMOV.REACOBFINLEITURA,

/*RETORNA VALORES DE TAXA DE SECAGEM GERADA NO ROMANEIO JA COBRADO*/
COALESCE(SUM((SELECT SUM(NFITEM.VALORTOTAL) FROM NFITEM
            INNER JOIN ROMATXSERVICOPG ON
            ROMATXSERVICOPG.ESTAB       = NFITEM.ESTAB AND
            ROMATXSERVICOPG.SEQNOTA     = NFITEM.SEQNOTA AND
            ROMATXSERVICOPG.SEQNOTAITEM = NFITEM.SEQNOTAITEM

            INNER JOIN ROMATXSERVICO ON
            ROMATXSERVICO.ESTAB         = ROMATXSERVICOPG.ESTAB AND
            ROMATXSERVICO.ROMANEIO      = ROMATXSERVICOPG.ROMANEIO AND
            ROMATXSERVICO.ENTRADASAIDA  = ROMATXSERVICOPG.ENTRADASAIDA AND
            ROMATXSERVICO.NUMEROCM      = ROMATXSERVICOPG.NUMEROCM AND
            ROMATXSERVICO.SEQUENCIA     = ROMATXSERVICOPG.SEQUENCIA

            WHERE ROMA.ESTAB            = ROMATXSERVICO.ESTAB
              AND ROMA.ROMANEIO         = ROMATXSERVICO.ROMANEIO
              AND ROMA.ENTRADASAIDA     = ROMATXSERVICO.ENTRADASAIDA
              AND ROMA.NUMEROCM         = ROMATXSERVICO.NUMEROCM)),0) AS SECAGEM,

/*RETORNA DADOS DE TAXA DE SERVÇOS CALCULADAS NO ROMANEIO*/
COALESCE(SUM((SELECT SUM(ROMATXSERVICOPG.QTDEPAGO) FROM ROMATXSERVICOPG
            INNER JOIN ROMATXSERVICO ON
            ROMATXSERVICO.ESTAB         = ROMATXSERVICOPG.ESTAB AND
            ROMATXSERVICO.ROMANEIO      = ROMATXSERVICOPG.ROMANEIO AND
            ROMATXSERVICO.ENTRADASAIDA  = ROMATXSERVICOPG.ENTRADASAIDA AND
            ROMATXSERVICO.NUMEROCM      = ROMATXSERVICOPG.NUMEROCM AND
            ROMATXSERVICO.SEQUENCIA     = ROMATXSERVICOPG.SEQUENCIA

            WHERE ROMA.ESTAB            = ROMATXSERVICO.ESTAB
              AND ROMA.ROMANEIO         = ROMATXSERVICO.ROMANEIO
              AND ROMA.ENTRADASAIDA     = ROMATXSERVICO.ENTRADASAIDA
              AND ROMA.NUMEROCM         = ROMATXSERVICO.NUMEROCM)),0) AS SECAGEMKG,
              
                case when filial.estab=6 then  COALESCE(SUM((SELECT SUM(SECDESC.pesocalculado) FROM ROMADESC SECDESC
                WHERE SECDESC.ESTAB        = ROMA.ESTAB
                  AND SECDESC.ROMANEIO     = ROMA.ROMANEIO
                  AND SECDESC.ENTRADASAIDA = ROMA.ENTRADASAIDA
                  AND SECDESC.NUMEROCM     = ROMA.NUMEROCM
                  AND SECDESC.ROMADESC     IN (11))),0)else 0 end SECAGEMDESC,


0 AS SECAGEMNF,

/*RETORNA DADOS DE ARMAZENAGEM (FALTA IDENTIFICA QUAIS DADOS CORRETOS A SEREM RETORNADO)*/
0 AS ARMAZ,
    COALESCE(SUM((SELECT SUM(COALESCE(NFITEMTXSERVICOPG.VLRTOTALPG,QTDPAGO)) FROM NFITEMTXSERVICOPG
            INNER JOIN NFITEMTXSERVICO ON
            NFITEMTXSERVICO.ESTAB               = NFITEMTXSERVICOPG.ESTAB and
            NFITEMTXSERVICO.SEQNOTA             = NFITEMTXSERVICOPG.SEQNOTA AND
            NFITEMTXSERVICO.SEQNOTAITEM         = NFITEMTXSERVICOPG.SEQNOTAITEM AND
            NFITEMTXSERVICO.SERVICO             in (32) AND
            NFITEMTXSERVICOPG.SEQUENCIA         = NFITEMTXSERVICO.SEQUENCIA

        WHERE NFITEMTXSERVICOPG.ESTAB           = NFITEM.ESTAB
          AND NFITEMTXSERVICOPG.SEQNOTA         = NFITEM.SEQNOTA
          AND NFITEMTXSERVICOPG.SEQNOTAITEM     = NFITEM.SEQNOTAITEM)),0) AS QUEBQTD,
  CAST (0.0 AS DECIMAL(6,4)) AS TOTALSERV,
  NFCAB.NOTA,
  NFCAB.SEQNOTA,
  NFCAB.DTEMISSAO AS DTNF,
  COALESCE(NFITEM.QUANTIDADE,ROMA.PESOLIQUIDO) AS ENTRADAS,

/*RETORNA DADOS DE COMPRAS, CONFIGURAÇÃO DE NOTAS 203*/
(COALESCE(NFITEM.QUANTIDADE,0)*-1) AS  COMPRAS,

/*RETORNA DADOS DE DEVOLUÇÃO DE DEPOSITO E COMPRA A FIXAR, CONFIGURAÇÃO DE NOTAS 206,259,231*/
  (SUM((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                    INNER JOIN NFITEM NFI ON
                                    NFI.ESTAB                = NFITEMAPARTIRDE.ESTAB AND
                                    NFI.SEQNOTA              = NFITEMAPARTIRDE.SEQNOTA AND
                                    NFI.SEQNOTAITEM          = NFITEMAPARTIRDE.SEQNOTAITEM

                                    INNER JOIN NFCAB NFDV ON
                                    NFDV.ESTAB               = NFI.ESTAB AND
                                    NFDV.SEQNOTA             = NFI.SEQNOTA

                                    INNER JOIN NFCFG NFCFGDV ON
                                    NFCFGDV.NOTACONF         = NFDV.NOTACONF AND
                                    NFCFGDV.NOTACONF         NOT IN (206)

                                    INNER JOIN NATOPERACAO NATDV ON
                                    NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                    NATDV.ENTRADASAIDA       = NFCFGDV.ENTRADASAIDA AND
                                    NATDV.TIPODCTO           = 'D'

                                    WHERE NFITEM.ESTAB       = NFITEMAPARTIRDE.ESTABORIGEM
                                      AND NFITEM.SEQNOTA     = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                      AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM))*-1)  AS DEVOLUCAO,


/*RETORNA DADOS DE TRNSFERENCIA CEDIDA PARA PRODUTORES, OPERAÇÃO DE NOTA*/
SUM((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                    INNER JOIN NFITEM NFI ON
                                    NFI.ESTAB                = NFITEMAPARTIRDE.ESTAB AND
                                    NFI.SEQNOTA              = NFITEMAPARTIRDE.SEQNOTA AND
                                    NFI.SEQNOTAITEM          = NFITEMAPARTIRDE.SEQNOTAITEM

                                    INNER JOIN NFCAB NFDV ON
                                    NFDV.ESTAB               = NFI.ESTAB AND
                                    NFDV.SEQNOTA             = NFI.SEQNOTA

                                    INNER JOIN NFCFG NFCFGDV ON
                                    NFCFGDV.NOTACONF         = NFDV.NOTACONF AND
                                    NFCFGDV.NOTACONF         IN (233)

                                    INNER JOIN NATOPERACAO NATDV ON
                                    NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                    NATDV.ENTRADASAIDA       = NFCFGDV.ENTRADASAIDA AND
                                    NATDV.TIPODCTO           = 'D'

                                    WHERE NFITEM.ESTAB       = NFITEMAPARTIRDE.ESTABORIGEM
                                      AND NFITEM.SEQNOTA     = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                      AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM))*-1 AS TRANSFCEDIDA,

SUM((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                    INNER JOIN NFITEM NFI ON
                                    NFI.ESTAB                = NFITEMAPARTIRDE.ESTAB AND
                                    NFI.SEQNOTA              = NFITEMAPARTIRDE.SEQNOTA AND
                                    NFI.SEQNOTAITEM          = NFITEMAPARTIRDE.SEQNOTAITEM

                                    INNER JOIN NFCAB NFDV ON
                                    NFDV.ESTAB               = NFI.ESTAB AND
                                    NFDV.SEQNOTA             = NFI.SEQNOTA

                                    INNER JOIN NFCFG NFCFGDV ON
                                    NFCFGDV.NOTACONF         = NFDV.NOTACONF

                                    INNER JOIN NATOPERACAO NATDV ON
                                    NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                    NATDV.ENTRADASAIDA       = NFCFGDV.ENTRADASAIDA AND
                                    NATDV.TIPODCTO           = 'O'

                                    WHERE NFITEM.ESTAB       = NFITEMAPARTIRDE.ESTABORIGEM
                                      AND NFITEM.SEQNOTA     = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                      AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM)) AS FIXACAO,
/*RETORNA SALDO*/
    ROMA.PESOLIQUIDO - CASE WHEN CONTAMOV.REACOBFINLEITURA = 0 THEN COALESCE(SUM((SELECT SUM(ROMATXSERVICOPG.QTDEPAGO) FROM ROMATXSERVICOPG
            INNER JOIN ROMATXSERVICO ON
            ROMATXSERVICO.ESTAB         = ROMATXSERVICOPG.ESTAB AND
            ROMATXSERVICO.ROMANEIO      = ROMATXSERVICOPG.ROMANEIO AND
            ROMATXSERVICO.ENTRADASAIDA  = ROMATXSERVICOPG.ENTRADASAIDA AND
            ROMATXSERVICO.NUMEROCM      = ROMATXSERVICOPG.NUMEROCM AND
            ROMATXSERVICO.SEQUENCIA     = ROMATXSERVICOPG.SEQUENCIA

            WHERE ROMA.ESTAB            = ROMATXSERVICO.ESTAB
              AND ROMA.ROMANEIO         = ROMATXSERVICO.ROMANEIO
              AND ROMA.ENTRADASAIDA     = ROMATXSERVICO.ENTRADASAIDA
              AND ROMA.NUMEROCM         = ROMATXSERVICO.NUMEROCM)),0) ELSE 0 END AS SALDO,

/*RETORNA SALDO*/
0 AS SALDOLIQ,

ROMA.NFPRODUTOR,
ROMA.AREACAMPO, AREACAMPO.DESCRICAO AS DESCAMPO,
(SELECT COALESCE(SUM(ROMATXSERVICOPG.QTDEPAGO),0) FROM ROMATXSERVICOPG
                                  WHERE (ROMATXSERVICOPG.ESTAB           = ROMATXSERVICO.ESTAB)
                                    AND(ROMATXSERVICOPG.ROMANEIO        = ROMATXSERVICO.ROMANEIO)
                                    AND(ROMATXSERVICOPG.ENTRADASAIDA    = ROMATXSERVICO.ENTRADASAIDA)
                                    AND(ROMATXSERVICOPG.NUMEROCM        = ROMATXSERVICO.NUMEROCM)
                                    AND(ROMATXSERVICOPG.SEQUENCIA       = ROMATXSERVICO.SEQUENCIA)) AS QTDEPAGO,
                                    
                                    COALESCE(NFITEM.FINATIPOROMA,0)TIPO
                                    
FROM NFCAB
INNER JOIN FILIAL ON
FILIAL.ESTAB                    = NFCAB.ESTAB

INNER JOIN CIDADE ON
CIDADE.CIDADE                   = FILIAL.CIDADE

INNER JOIN NFCFG ON
NFCFG.NOTACONF                  = NFCAB.NOTACONF AND
NFCFG.ENTRADASAIDA              = 'E' AND
NFCAB.NOTACONF                  IN (202,203,278)/*INFORMAR TODAS AS CONFIGURAÇÃO DE NOTA UTILIZADO PARA COMPRA DIRETA, SEM DEPOSITO*/

INNER JOIN NATOPERACAO ON
NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
NATOPERACAO.TIPODCTO            IN ('N')

INNER JOIN CONTAMOV ON
CONTAMOV.NUMEROCM               = NFCAB.NUMEROCM

LEFT JOIN ENDERECO ON
ENDERECO.NUMEROCM               = NFCAB.NUMEROCM AND
ENDERECO.SEQENDERECO            = NFCAB.SEQENDERECO

INNER JOIN NFCABROMA ON
NFCABROMA.ESTAB                 = NFCAB.ESTAB AND
NFCABROMA.SEQNOTA               = NFCAB.SEQNOTA

INNER JOIN ROMACLASS ON
ROMACLASS.ESTAB                 = NFCABROMA.ESTAB AND
ROMACLASS.ROMANEIO              = NFCABROMA.ROMANEIO AND
ROMACLASS.ENTRADASAIDA          = NFCABROMA.ENTRADASAIDA AND
ROMACLASS.NUMEROCM              = NFCABROMA.NUMEROCM AND
ROMACLASS.CLASSIFICACAO         = NFCABROMA.CLASSIFICACAO AND
ROMACLASS.PERCENTUAL            > 0

INNER JOIN ROMACLASSNOME ON
ROMACLASSNOME.CLASSIFICACAO     = ROMACLASS.CLASSIFICACAO

INNER JOIN ROMA ON
ROMA.ESTAB                      = ROMACLASS.ESTAB AND
ROMA.ROMANEIO                   = ROMACLASS.ROMANEIO AND
ROMA.ENTRADASAIDA               = ROMACLASS.ENTRADASAIDA AND
ROMA.NUMEROCM                   = ROMACLASS.NUMEROCM
AND ROMA.ROMANEIOCONFIG <> 9
AND ROMA.ESTORNADO <> 'S'

INNER JOIN NFITEM ON
NFITEM.ESTAB                    = NFCAB.ESTAB AND
NFITEM.SEQNOTA                  = NFCAB.SEQNOTA AND
NFITEM.ROMANEIO                 = NFCABROMA.ROMANEIO

LEFT JOIN AREACAMPO ON
AREACAMPO.CODIGO = ROMA.AREACAMPO

INNER JOIN ITEMAGRO ON
ITEMAGRO.ITEM                   = NFITEM.ITEM

INNER JOIN ITEMAGROESTAB ON
ITEMAGROESTAB.ESTAB             = NFITEM.ESTAB AND
ITEMAGROESTAB.ITEM              = ITEMAGRO.ITEM

LEFT JOIN ROMATXSERVICO ON
ROMATXSERVICO.ESTAB            = ROMA.ESTAB AND
ROMATXSERVICO.ROMANEIO         = ROMA.ROMANEIO AND
ROMATXSERVICO.ENTRADASAIDA     = ROMA.ENTRADASAIDA AND
ROMATXSERVICO.NUMEROCM         = ROMA.NUMEROCM

LEFT JOIN ITEMAGRO ITEM_ROMANEIO ON
ROMATXSERVICO.ITEM             = ITEM_ROMANEIO.ITEM OR
ROMATXSERVICO.GRUPOITEM        = ITEM_ROMANEIO.GRUPO

LEFT JOIN ITEMAGROESTAB ITEMAGROESTAB_ROMANEIO ON
ITEMAGROESTAB_ROMANEIO.ESTAB   = ROMATXSERVICO.ESTAB AND
ITEMAGROESTAB_ROMANEIO.ITEM    = CASE WHEN ROMACLASS.ITEM IS NULL THEN ROMA.ITEM ELSE ROMACLASS.ITEM END


INNER JOIN ITEMCOTCAB ON
ITEMCOTCAB.ESTAB                = ITEMAGROESTAB.ESTAB AND
ITEMCOTCAB.COTACAO              = ITEMAGROESTAB.COTACAO

INNER JOIN ITEMCOTITE ON
ITEMCOTITE.ESTAB                = ITEMCOTCAB.ESTAB AND
ITEMCOTITE.COTACAO              = ITEMCOTCAB.COTACAO AND
ROMA.DTEMISSAO                  BETWEEN ITEMCOTITE.DTCOTACAO AND ITEMCOTITE.DTCOTACAOFIN

--WHERE ROMA.ESTAB=10 AND ROMA.NUMEROCM=813 AND ROMA.ITEM=6

GROUP BY
FILIAL.ESTAB,
NATOPERACAO.NATUREZADAOPERACAO,
NATOPERACAO.TIPODCTO,
ROMA.PESOLIQUIDO,
NFCFG.NOTACONF,
NFCFG.NOTACONF,
NFCFG.DESCRICAO,CONTAMOV.REACOBFINLEITURA,
NFCAB.SEQNOTA,
NFCAB.NOTA,
NFCAB.DTEMISSAO,
CONTAMOV.NUMEROCM,
CONTAMOV.NOME,
ROMACLASSNOME.CLASSIFICACAO,
ITEMAGRO.DESCRICAO,
ROMACLASSNOME.DESCRICAOCLASSIFICACAO,
ITEMAGRO.ITEM,
ROMA.ITEM,
ITEMAGRO.DESCRICAO, ENDERECO.ENDERECO, NFCAB.SEQENDERECO,
ITEMAGRO.UNIDADE, ROMA.NFPRODUTOR,ROMATXSERVICO.ESTAB, ITEMAGROESTAB_ROMANEIO.COTACAO,
ROMA.DTEMISSAO,
ROMA.ROMANEIO,ROMA.SEQDESMEMBRADO, ROMA.ROMAONOFF, ROMA.AREACAMPO, AREACAMPO.DESCRICAO,
ROMA.PLACA,
ROMA.PESOTOTAL, ROMA.DTEMISSAO, ROMA.PESOLIQUIDO,
ROMA.TARA,  NATOPERACAO.TIPODCTO , NFITEM.QUANTIDADE, NFITEM.QUANTIDADE ,
ROMA.PH,
ROMA.PHORIGINAL,  ROMA.PESOLIQUIDO ,
ROMA.FRETE,
ROMA.PESOFRETE,
ROMA.FN,
ROMA.FRETE,ROMATXSERVICO.ESTAB,
ROMATXSERVICO.ROMANEIO,
ROMATXSERVICO.ENTRADASAIDA,
ROMATXSERVICO.NUMEROCM,
ROMATXSERVICO.SEQUENCIA,
NFITEM.FINATIPOROMA;