SELECT "ESTAB","CNPJ","REDUZIDO","SERIE","NUM_PED","PEDIDO","FORNECEDOR","CONCEITO","CNPJF_FORNECEDOR","IE_FORNECEDOR","COD_CONFIG","CONFIG","DTEMISSAO_PD","VENCIMENTO","VALORTOTAL","USERID","PLACA","FRETE_PED","TIPOFRETESEMENTES","SOMA_TIPOFRETESEMENTES","DESCRICAO","TIPO_PROD","ERROCHAVENFE","REGRA_NOTACONF","CHAVCHAVENF","TIPOPGTO","CHAVEBOLETO","BANCO","AGENCIA","CONTA","PIX","DTEMISSAO_NF","CNPJ_EMITENTE_NF","CNPJ_DESTIN","CFOP","VAL_CFOP","VFRETE","VPROD","VNF", "DIF_VALOR", "VAL_VALOR_NF", "VAL_BOLETO", "VAL_CNPJ" FROM (
SELECT
    "ESTAB","CNPJ","REDUZIDO",
    SERIE,
    NUM_PED,
    "PEDIDO",
    FORNECEDOR,
    CASE WHEN CONCEITO IN (95,97,98,102) THEN 'ERRO' ELSE 'OK' END AS CONCEITO,
    CNPJF_FORNECEDOR, 
    IE_FORNECEDOR,
    COD_CONFIG,
    "CONFIG",
    "DTEMISSAO_PD","VENCIMENTO",VALORTOTAL,"USERID", "PLACA","FRETE_PED","TIPOFRETESEMENTES","SOMA_TIPOFRETESEMENTES", "DESCRICAO","TIPO_PROD",
    CASE WHEN DADOS.CHAVCHAVENF='77777777777777777777777777777777777777777777'
        THEN 'E'
        WHEN DADOS.CHAVCHAVENF='00000000000000000000000000000000000000000000'
        THEN 'E'
        WHEN DADOS.CHAVCHAVENF='00000000000000000000000000000000000000000000000000'
        THEN 'E'
        WHEN
        DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('ALX%')
        THEN 'E'
         WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('AT%')
        THEN 'E'
         WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('TRANSP%')
        THEN 'E'
        WHEN DADOS.CHAVCHAVENF IS NULL AND  DADOS.TIPO_PROD = 'P' AND 
        DADOS.DESCRICAO LIKE ('FAT%') THEN 'FAT'
        ELSE
        DADOS.CHAVCHAVENF END ERROCHAVENFE,
    CASE
        WHEN TIPO_PROD = 'S' and PEDIDOCONF = 58 THEN 980
        WHEN TIPO_PROD = 'P' and PEDIDOCONF = 58 THEN 981
        WHEN NOME_PROD LIKE 'AFGR%' THEN 799
        WHEN NOME_PROD LIKE 'FAT - AT%' THEN 825
        WHEN NOME_PROD LIKE 'FAT%' THEN 800
        WHEN DADOS.NOME_PROD LIKE 'UC -%' THEN 27
        WHEN DADOS.NOME_PROD LIKE 'AT -%' THEN 37
        WHEN DADOS.NOME_PROD LIKE 'ALX -%' THEN 44
        WHEN DADOS.NOME_PROD LIKE 'TRANSP -%' OR DADOS.NOME_PROD LIKE 'TRANSP. %' THEN 502
        WHEN regexp_like(SUBSTR(NOME_PROD,0,2), '[0-9]') then 34
    END REGRA_NOTACONF,
    
    CHAVCHAVENF,
        CASE 
        WHEN PEDIDOCONF = 67 THEN 'A'
        WHEN DADOS.CHAVEBOLETO IS NOT NULL THEN 'B'
        WHEN DADOS.PIX IS NOT NULL THEN 'P'
        WHEN DADOS.BANCO IS NOT NULL AND DADOS.AGENCIA IS NOT NULL AND DADOS.CONTA IS NOT NULL THEN 'D'
        ELSE 'E' END AS TIPOPGTO,
        CASE 
        WHEN DADOS.CHAVEBOLETO IS NOT NULL THEN
        CASE 
            WHEN ROUND(
                CASE 
                    WHEN LENGTH(DADOS.CHAVEBOLETO) = 44 THEN 
                        TO_NUMBER(SUBSTR(DADOS.CHAVEBOLETO, 10, 10)) / 100
                    WHEN LENGTH(DADOS.CHAVEBOLETO) = 47 THEN 
                        TO_NUMBER(SUBSTR(DADOS.CHAVEBOLETO, 38, 10)) / 100
                END
            , 2) = ROUND(DADOS.VALORTOTAL, 2)
            THEN 'OK' 
            ELSE 'ERRO'
        END
        ELSE NULL
        END AS VAL_BOLETO,
        CHAVEBOLETO,BANCO,AGENCIA,CONTA,PIX,DTEMISSAO_NF,CNPJ_EMITENTE_NF,CNPJ_DESTIN,CFOP,VFRETE,VPROD,VNF,
        (VNF - VPROD) AS DIF_VALOR,
        DADOS.VAL_VALOR_NF,
        DADOS.VAL_CFOP,
        DADOS.VAL_CNPJ
FROM(

    SELECT
        FILIAL.ESTAB,
        FILIAL.REDUZIDO,
        FILIAL.CNPJ,
        PEDCAB.SERIE,
        PEDCAB.NUMERO AS NUM_PED,
        PEDCAB.PESSOA AS FORNECEDOR,

        CONCEITOPESSOA.CONCEITO,


        COALESCE(ENDERECO.CNPJF, CONTAMOV.CNPJF) AS CNPJF_FORNECEDOR, 
        CASE WHEN PEDCAB.SEQENDERECO > 0 THEN REPLACE(ENDERECO.CREDENCIALAGRO,'.','')
        ELSE REPLACE(CONTAMOV.INSCESTAD,'.','') END AS IE_FORNECEDOR,
        PEDCAB.SERIE||'-'||PEDCAB.NUMERO AS PEDIDO,
        PEDCFG.PEDIDOCONF AS COD_CONFIG,
        PEDCFG.PEDIDOCONF||'-'||PEDCFG.DESCRICAO AS CONFIG,
        PEDCFG.PEDIDOCONF,
        TO_CHAR(PEDCAB.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO_PD,
        TO_CHAR(COALESCE(MAXPRAZO.PRAZO,PEDCAB.DTPRAZOPAGTO),'DD/MM/YYYY') AS VENCIMENTO,
        PEDCAB.VALORMERCADORIA AS VALORTOTAL,
        PEDCAB.USERID AS USERID,        -- <<<<<< CORRIGIDO AQUI
        PEDCAB.PLACA,
        COALESCE (PEDCAB.VLRFRETESEMENTES,0) AS FRETE_PED,
        PEDCAB.TIPOFRETESEMENTES,
        CASE WHEN COALESCE (PEDCAB.VLRFRETESEMENTES,0) > 0 AND PEDCAB.TIPOFRETESEMENTES NOT IN ('G','D','C','A') THEN 'EF' ELSE 'FC' END AS SOMA_TIPOFRETESEMENTES,
        CASE WHEN PEDCAB.VALORMERCADORIA <> U_NOTASSIEG.VNF THEN 'EV' ELSE 'VC' END AS VAL_VALOR_NF,
        PGRUPOS.DESCRICAO,
        CASE WHEN ITEMAGRO.SERVICO = 'S' THEN 'S' ELSE 'P' END TIPO_PROD,
        PEDCAB_U.CHAVCHAVENF,
        PEDCAB_U.CHAVEBOLETO,
        PEDCAB_U.BANCO,
        PEDCAB_U.AGENCIA,
        PEDCAB_U.CONTA,
        PEDCAB_U.PIX,
        U_NOTASSIEG.DTEMISSAO AS DTEMISSAO_NF,
        U_NOTASSIEG.CNPJ_EMITENTE AS CNPJ_EMITENTE_NF,
        U_NOTASSIEG.CNPJ_DESTIN,
        CASE WHEN FILIAL.CNPJ = U_NOTASSIEG.CNPJ_DESTIN THEN 'OK' ELSE 'ERRO' END AS VAL_CNPJ,
        U_NOTASSIEG.CFOP,
        CASE WHEN U_NOTASSIEG.CFOP IN (5922, 6922)
            OR SUBSTR(TRIM(TO_CHAR(U_NOTASSIEG.CFOP)), 1, 1) IN ('1', '2')
            THEN 'ERRO'
            ELSE 'OK'
        END AS VAL_CFOP,
        U_NOTASSIEG.VFRETE,
        U_NOTASSIEG.VPROD,
        U_NOTASSIEG.VNF,
        ITEMAGRO.DESCRICAO AS NOME_PROD

    FROM PEDCAB

        INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM=PEDCAB.PESSOA


    LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM = PEDCAB.PESSOA



        LEFT JOIN ENDERECO ON ENDERECO.NUMEROCM=PEDCAB.PESSOA
                          AND ENDERECO.SEQENDERECO=PEDCAB.SEQENDERECO

        INNER JOIN PEDCFG ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF

        INNER JOIN FILIAL ON FILIAL.ESTAB = PEDCAB.ESTAB

        INNER JOIN NOTIFICAESTRATEGIA N ON
            N.ESTAB = PEDCAB.ESTAB
            AND N.SERIE = PEDCAB.SERIE
            AND N.NUMERO = PEDCAB.NUMERO

        LEFT JOIN (
            SELECT ESTAB, SERIE, NUMERO, MAX(PRAZOPAGAMENTO) AS PRAZO
            FROM PEDCABPGTO
            GROUP BY ESTAB, SERIE, NUMERO
        ) MAXPRAZO ON
            MAXPRAZO.ESTAB = PEDCAB.ESTAB
            AND MAXPRAZO.SERIE = PEDCAB.SERIE
            AND MAXPRAZO.NUMERO = PEDCAB.NUMERO

        LEFT JOIN (
            SELECT
                NN.ESTAB, NN.SERIE, NN.NUMERO,
                NN.IDGRPAPROVADORES, NN.USERID, NN.IDNOTIFICA AS NOTIFICA,
                NN.PENDENTEAPROV
            FROM NOTIFICAESTRATEGIA NN
            INNER JOIN (
                SELECT ESTAB, SERIE, NUMERO, MAX(IDNOTIFICA) NOTIFICA
                FROM NOTIFICAESTRATEGIA
                GROUP BY ESTAB, SERIE, NUMERO
            ) MAXIMO ON MAXIMO.ESTAB = NN.ESTAB
                  AND MAXIMO.SERIE = NN.SERIE
                  AND MAXIMO.NUMERO = NN.NUMERO
                  AND MAXIMO.NOTIFICA = NN.IDNOTIFICA
        ) NOTIFICAESTRATEGIA ON 
            NOTIFICAESTRATEGIA.ESTAB = PEDCAB.ESTAB
            AND NOTIFICAESTRATEGIA.SERIE = PEDCAB.SERIE
            AND NOTIFICAESTRATEGIA.NUMERO = PEDCAB.NUMERO
            AND NOTIFICAESTRATEGIA.NOTIFICA = N.IDNOTIFICA
        ---LEFT JOIN NOTIFICAESTRADET ON NOTIFICAESTRADET.IDNOTIFICA = NOTIFICAESTRATEGIA.NOTIFICA
        LEFT JOIN (
            SELECT
            MAX(IDESTRADET), 
            IDNOTIFICA
            FROM NOTIFICAESTRADET 
            GROUP BY IDNOTIFICA
        )NOTIFICADET ON NOTIFICADET.IDNOTIFICA = NOTIFICAESTRATEGIA.NOTIFICA
        LEFT JOIN PUSUARIO ON PUSUARIO.USERID = NOTIFICAESTRATEGIA.USERID
        LEFT JOIN PGRUPOS ON PGRUPOS.CODIGO = PUSUARIO.GRUPO
        LEFT JOIN PEDITEM ON PEDITEM.ESTAB = PEDCAB.ESTAB
            AND PEDITEM.SERIE = PEDCAB.SERIE
            AND PEDITEM.NUMERO = PEDCAB.NUMERO
            AND PEDITEM.SEQPEDITE = 1
        LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
                          --and itemagro.servico='P'
        LEFT JOIN PEDCAB_U ON PEDCAB_U.ESTAB=PEDCAB.ESTAB
                           AND PEDCAB_U.SERIE=PEDCAB.SERIE
                           AND PEDCAB_U.NUMERO=PEDCAB.NUMERO
        LEFT JOIN ITEMGRUPO ON ITEMGRUPO.GRUPO = ITEMAGRO.GRUPO

    LEFT JOIN U_NOTASSIEG ON PEDCAB_U.CHAVCHAVENF = U_NOTASSIEG.CHAVEACESSONFE


    WHERE
        NOTIFICAESTRATEGIA.PENDENTEAPROV = 0
        AND PEDCAB.STATUS NOT IN ('B','C')
        AND PEDCAB.PEDIDOCONF IN (54,57,58,76,77,78,79,80,82,85,90,91,92,93,94,95,96,97,102)
       -- AND U_NOTASSIEG.VNF <> 0

) DADOS)DADOS1 WHERE
DADOS1.REGRA_NOTACONF NOT IN (799,800,825)
  AND TIPO_PROD='P' 
  AND ((DADOS1.PLACA NOT IN 'RAT5I00') OR (DADOS1.PLACA IS NULL))