WITH
/* Join pesado (via NOTIFICAESTRATEGIA), calculado UMA vez para a lista
   ampla de PEDIDOCONF -- que já inclui o 72. Mantém ENDERECO.CNPJF e
   CONTAMOV.CNPJF como colunas separadas (não resolvidas), porque a
   fórmula final de CNPJF_FORNECEDOR muda dependendo de qual bloco de
   saída consome esse dado. */
RAW_NOTIFICA AS (
    SELECT /*+ MATERIALIZE */
        FILIAL.ESTAB,
        FILIAL.REDUZIDO,
        FILIAL.CNPJ,
        PEDCAB.SERIE,
        PEDCAB.NUMERO AS NUM_PED,
        PEDCAB.PESSOA AS FORNECEDOR,
        CASE
            WHEN CONCEITOPESSOA.CONCEITO IN (95, 97, 98, 102) THEN 'ERRO'
            ELSE 'OK'
        END AS CONCEITO,
        ENDERECO.CNPJF AS ENDERECO_CNPJF,
        CONTAMOV.CNPJF AS CONTAMOV_CNPJF,
        CASE
            WHEN PEDCAB.SEQENDERECO > 0 THEN REPLACE(ENDERECO.CREDENCIALAGRO, '.', '')
            ELSE REPLACE(CONTAMOV.INSCESTAD, '.', '')
        END AS IE_FORNECEDOR,
        PEDCAB.SERIE || '-' || PEDCAB.NUMERO AS PEDIDO,
        PEDCFG.PEDIDOCONF AS COD_CONFIG,
        PEDCFG.PEDIDOCONF || '-' || PEDCFG.DESCRICAO AS CONFIG,
        PEDCFG.PEDIDOCONF,
        TO_CHAR(PEDCAB.DTEMISSAO, 'DD/MM/YYYY') AS DTEMISSAO,
        TO_CHAR(COALESCE(MAXPRAZO.PRAZO, PEDCAB.DTPRAZOPAGTO), 'DD/MM/YYYY') AS VENCIMENTO,
        PEDCAB.VALORMERCADORIA AS VALORTOTAL,
        PEDCAB.USERID AS USERID,
        PEDCAB.PLACA,
        PGRUPOS.DESCRICAO,
        CASE
            WHEN ITEMAGRO.SERVICO = 'S' THEN 'S'
            ELSE 'P'
        END AS TIPO_PROD,
        PEDCAB_U.CHAVCHAVENF,
        PEDCAB_U.CHAVEBOLETO,
        PEDCAB_U.BANCO,
        PEDCAB_U.AGENCIA,
        PEDCAB_U.CONTA,
        PEDCAB_U.PIX,
        ITEMAGRO.DESCRICAO AS NOME_PROD
    FROM PEDCAB
        LEFT JOIN CONCEITOPESSOA
            ON CONCEITOPESSOA.NUMEROCM = PEDCAB.PESSOA
        INNER JOIN CONTAMOV
            ON CONTAMOV.NUMEROCM = PEDCAB.PESSOA
        LEFT JOIN ENDERECO
            ON ENDERECO.NUMEROCM = PEDCAB.PESSOA
           AND ENDERECO.SEQENDERECO = PEDCAB.SEQENDERECO
        INNER JOIN PEDCFG
            ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF
        INNER JOIN FILIAL
            ON FILIAL.ESTAB = PEDCAB.ESTAB
        INNER JOIN NOTIFICAESTRATEGIA N
            ON N.ESTAB = PEDCAB.ESTAB
           AND N.SERIE = PEDCAB.SERIE
           AND N.NUMERO = PEDCAB.NUMERO
        LEFT JOIN (
            SELECT
                ESTAB, SERIE, NUMERO,
                MAX(PRAZOPAGAMENTO) AS PRAZO,
                COUNT(*) AS QTD_PARCELAS
            FROM PEDCABPGTO
            GROUP BY ESTAB, SERIE, NUMERO
        ) MAXPRAZO
            ON MAXPRAZO.ESTAB = PEDCAB.ESTAB
           AND MAXPRAZO.SERIE = PEDCAB.SERIE
           AND MAXPRAZO.NUMERO = PEDCAB.NUMERO
        LEFT JOIN (
            SELECT
                NN.ESTAB, NN.SERIE, NN.NUMERO,
                NN.IDGRPAPROVADORES, NN.USERID,
                NN.IDNOTIFICA AS NOTIFICA, NN.PENDENTEAPROV
            FROM NOTIFICAESTRATEGIA NN
            INNER JOIN (
                SELECT ESTAB, SERIE, NUMERO, MAX(IDNOTIFICA) AS NOTIFICA
                FROM NOTIFICAESTRATEGIA
                GROUP BY ESTAB, SERIE, NUMERO
            ) MAXIMO
                ON MAXIMO.ESTAB = NN.ESTAB
               AND MAXIMO.SERIE = NN.SERIE
               AND MAXIMO.NUMERO = NN.NUMERO
               AND MAXIMO.NOTIFICA = NN.IDNOTIFICA
        ) NOTIFICAESTRATEGIA
            ON NOTIFICAESTRATEGIA.ESTAB = PEDCAB.ESTAB
           AND NOTIFICAESTRATEGIA.SERIE = PEDCAB.SERIE
           AND NOTIFICAESTRATEGIA.NUMERO = PEDCAB.NUMERO
           AND NOTIFICAESTRATEGIA.NOTIFICA = N.IDNOTIFICA
        LEFT JOIN PUSUARIO
            ON PUSUARIO.USERID = NOTIFICAESTRATEGIA.USERID
        LEFT JOIN PGRUPOS
            ON PGRUPOS.CODIGO = PUSUARIO.GRUPO
        LEFT JOIN PEDITEM
            ON PEDITEM.ESTAB = PEDCAB.ESTAB
           AND PEDITEM.SERIE = PEDCAB.SERIE
           AND PEDITEM.NUMERO = PEDCAB.NUMERO
           AND PEDITEM.SEQPEDITE = 1
        LEFT JOIN ITEMAGRO
            ON ITEMAGRO.ITEM = PEDITEM.ITEM
        LEFT JOIN PEDCAB_U
            ON PEDCAB_U.ESTAB = PEDCAB.ESTAB
           AND PEDCAB_U.SERIE = PEDCAB.SERIE
           AND PEDCAB_U.NUMERO = PEDCAB.NUMERO
    WHERE
        NOTIFICAESTRATEGIA.PENDENTEAPROV = 0
        AND PEDCAB.STATUS NOT IN ('B', 'C')
        AND PEDCAB.PEDIDOCONF IN (
            54, 57, 58, 72, 76, 77, 78, 79, 80, 82, 85,
            90, 91, 92, 93, 94, 95, 96, 97, 102
        )
        AND TRUNC(COALESCE(MAXPRAZO.PRAZO, PEDCAB.DTPRAZOPAGTO)) >= TRUNC(SYSDATE)
        AND NVL(MAXPRAZO.QTD_PARCELAS, 0) <= 1
        AND NOT EXISTS (
            SELECT 1
            FROM PEDITEM PEDITEM_VALIDACAO
            WHERE PEDITEM_VALIDACAO.ESTAB = PEDCAB.ESTAB
              AND PEDITEM_VALIDACAO.SERIE = PEDCAB.SERIE
              AND PEDITEM_VALIDACAO.NUMERO = PEDCAB.NUMERO
              AND PEDITEM_VALIDACAO.SEQPEDITE > 1
        )
),
CALC_NOTIFICA AS (
    /* ERROCHAVENFE e REGRA_NOTACONF são idênticos nos dois blocos
       originais que consomem esse join -- por isso é seguro calculá-los
       uma única vez aqui. TIPOPGTO e CNPJF_FORNECEDOR NÃO entram aqui,
       pois a fórmula difere conforme o bloco de saída. */
    SELECT
        RAW_NOTIFICA.*,
        CASE
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'N' AND DESCRICAO LIKE 'ALX%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'AT%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'TRANSP%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'FAT%' THEN 'FAT'
            ELSE CHAVCHAVENF
        END AS ERROCHAVENFE,
        CASE
            WHEN TIPO_PROD = 'S' AND PEDIDOCONF = 58 THEN 980
            WHEN TIPO_PROD = 'P' AND PEDIDOCONF = 58 THEN 981
            WHEN NOME_PROD LIKE 'AFGR%' THEN 799
            WHEN NOME_PROD LIKE 'FAT - AT%' THEN 825
            WHEN NOME_PROD LIKE 'FAT%' THEN 800
            WHEN NOME_PROD LIKE 'UC -%' THEN 27
            WHEN NOME_PROD LIKE 'AT -%' THEN 37
            WHEN NOME_PROD LIKE 'ALX -%' THEN 44
            WHEN NOME_PROD LIKE 'TRANSP -%' OR NOME_PROD LIKE 'TRANSP. %' THEN 502
            WHEN REGEXP_LIKE(SUBSTR(NOME_PROD, 0, 2), '[0-9]') THEN 34
        END AS REGRA_NOTACONF
    FROM RAW_NOTIFICA
),
/* Join do bloco PEDIDOCONF = 67 -- estrutura própria (sem NOTIFICAESTRATEGIA),
   com a validação de CFOP corrigida (comparação direta, sem REGEXP). */
RAW_67 AS (
    SELECT
        FILIAL.ESTAB,
        FILIAL.REDUZIDO,
        FILIAL.CNPJ,
        PEDCAB.SERIE,
        PEDCAB.NUMERO AS NUM_PED,
        PEDCAB.PESSOA AS FORNECEDOR,
        CASE
            WHEN CONCEITOPESSOA.CONCEITO IN (95, 97, 98, 102) THEN 'ERRO'
            ELSE 'OK'
        END AS CONCEITO,
        CONTAMOV.CNPJF AS CONTAMOV_CNPJF,
        CASE
            WHEN PEDCAB.SEQENDERECO > 0 THEN REPLACE(ENDERECO.CREDENCIALAGRO, '.', '')
            ELSE REPLACE(CONTAMOV.INSCESTAD, '.', '')
        END AS IE_FORNECEDOR,
        PEDCAB.SERIE || '-' || PEDCAB.NUMERO AS PEDIDO,
        PEDCFG.PEDIDOCONF AS COD_CONFIG,
        PEDCFG.PEDIDOCONF || '-' || PEDCFG.DESCRICAO AS CONFIG,
        PEDCFG.PEDIDOCONF,
        TO_CHAR(PEDCAB.DTEMISSAO, 'DD/MM/YYYY') AS DTEMISSAO,
        TO_CHAR(COALESCE(MAXPRAZO.PRAZO, PEDCAB.DTPRAZOPAGTO), 'DD/MM/YYYY') AS VENCIMENTO,
        PEDCAB.VALORMERCADORIA AS VALORTOTAL,
        PEDCAB.USERID AS USERID,
        PEDCAB.PLACA,
        PGRUPOS.DESCRICAO,
        CASE
            WHEN ITEMAGRO.SERVICO = 'S' THEN 'S'
            ELSE 'P'
        END AS TIPO_PROD,
        PEDCAB_U.CHAVCHAVENF,
        PEDCAB_U.CHAVEBOLETO,
        PEDCAB_U.BANCO,
        PEDCAB_U.AGENCIA,
        PEDCAB_U.CONTA,
        PEDCAB_U.PIX,
        ITEMAGRO.DESCRICAO AS NOME_PROD
    FROM PEDCAB
        LEFT JOIN CONCEITOPESSOA
            ON CONCEITOPESSOA.NUMEROCM = PEDCAB.PESSOA
        INNER JOIN CONTAMOV
            ON CONTAMOV.NUMEROCM = PEDCAB.PESSOA
        LEFT JOIN ENDERECO
            ON ENDERECO.NUMEROCM = PEDCAB.PESSOA
           AND ENDERECO.SEQENDERECO = PEDCAB.SEQENDERECO
        INNER JOIN PEDCFG
            ON PEDCFG.PEDIDOCONF = PEDCAB.PEDIDOCONF
        INNER JOIN FILIAL
            ON FILIAL.ESTAB = PEDCAB.ESTAB
        LEFT JOIN (
            SELECT
                ESTAB, SERIE, NUMERO,
                MAX(PRAZOPAGAMENTO) AS PRAZO,
                COUNT(*) AS QTD_PARCELAS
            FROM PEDCABPGTO
            GROUP BY ESTAB, SERIE, NUMERO
        ) MAXPRAZO
            ON MAXPRAZO.ESTAB = PEDCAB.ESTAB
           AND MAXPRAZO.SERIE = PEDCAB.SERIE
           AND MAXPRAZO.NUMERO = PEDCAB.NUMERO
        LEFT JOIN PEDITEM
            ON PEDITEM.ESTAB = PEDCAB.ESTAB
           AND PEDITEM.SERIE = PEDCAB.SERIE
           AND PEDITEM.NUMERO = PEDCAB.NUMERO
           AND PEDITEM.SEQPEDITE = 1
        LEFT JOIN ITEMAGRO
            ON ITEMAGRO.ITEM = PEDITEM.ITEM
        LEFT JOIN PUSUARIO
            ON PUSUARIO.USERID = PEDCAB.USERID
        LEFT JOIN PGRUPOS
            ON PGRUPOS.CODIGO = PUSUARIO.GRUPO
        LEFT JOIN PEDCAB_U
            ON PEDCAB_U.ESTAB = PEDCAB.ESTAB
           AND PEDCAB_U.SERIE = PEDCAB.SERIE
           AND PEDCAB_U.NUMERO = PEDCAB.NUMERO
    WHERE
        PEDCAB.PEDIDOCONF IN (67)
        AND PEDCAB.STATUS NOT IN ('B', 'C')
        AND TRUNC(COALESCE(MAXPRAZO.PRAZO, PEDCAB.DTPRAZOPAGTO)) >= TRUNC(SYSDATE)
        AND NVL(MAXPRAZO.QTD_PARCELAS, 0) <= 1
        AND NOT EXISTS (
            SELECT 1
            FROM U_NOTASSIEG
            WHERE U_NOTASSIEG.CHAVEACESSONFE = PEDCAB_U.CHAVCHAVENF
              AND U_NOTASSIEG.CFOP IN ('5922', '6922')
        )
        AND NOT EXISTS (
            SELECT 1
            FROM PEDITEM PEDITEM_VALIDACAO
            WHERE PEDITEM_VALIDACAO.ESTAB = PEDCAB.ESTAB
              AND PEDITEM_VALIDACAO.SERIE = PEDCAB.SERIE
              AND PEDITEM_VALIDACAO.NUMERO = PEDCAB.NUMERO
              AND PEDITEM_VALIDACAO.SEQPEDITE > 1
        )
),
CALC_67 AS (
    SELECT
        RAW_67.*,
        CASE
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'N' AND DESCRICAO LIKE 'ALX%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'AT%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'TRANSP%' THEN 'E'
            WHEN CHAVCHAVENF IS NULL AND TIPO_PROD = 'P' AND DESCRICAO LIKE 'FAT%' THEN 'FAT'
            ELSE CHAVCHAVENF
        END AS ERROCHAVENFE,
        CASE
            WHEN TIPO_PROD = 'S' AND PEDIDOCONF = 58 THEN 980
            WHEN TIPO_PROD = 'P' AND PEDIDOCONF = 58 THEN 981
            WHEN NOME_PROD LIKE 'AFGR%' THEN 799
            WHEN NOME_PROD LIKE 'FAT - AT%' THEN 825
            WHEN NOME_PROD LIKE 'FAT%' THEN 800
            WHEN NOME_PROD LIKE 'UC -%' THEN 27
            WHEN NOME_PROD LIKE 'AT -%' THEN 37
            WHEN NOME_PROD LIKE 'ALX -%' THEN 44
            WHEN NOME_PROD LIKE 'TRANSP -%' OR NOME_PROD LIKE 'TRANSP. %' THEN 502
            WHEN REGEXP_LIKE(SUBSTR(NOME_PROD, 0, 2), '[0-9]') THEN 34
        END AS REGRA_NOTACONF
    FROM RAW_67
)
/* ---- Bloco 1: equivalente ao primeiro UNION original (72 + 67),
   sem filtro de REGRA_NOTACONF, TIPOPGTO com a regra "PEDIDOCONF IN (67)". ---- */
SELECT
    ESTAB, CNPJ, REDUZIDO, SERIE, NUM_PED, PEDIDO, FORNECEDOR, CONCEITO,
    COALESCE(ENDERECO_CNPJF, CONTAMOV_CNPJF) AS CNPJF_FORNECEDOR,
    IE_FORNECEDOR, COD_CONFIG, CONFIG, DTEMISSAO, VENCIMENTO, VALORTOTAL,
    USERID, PLACA, DESCRICAO, TIPO_PROD, ERROCHAVENFE, REGRA_NOTACONF, CHAVCHAVENF,
    CASE
        WHEN PEDIDOCONF IN (67) THEN 'A'
        WHEN CHAVEBOLETO IS NOT NULL THEN 'B'
        WHEN PIX IS NOT NULL THEN 'P'
        WHEN BANCO IS NOT NULL AND AGENCIA IS NOT NULL AND CONTA IS NOT NULL THEN 'D'
        ELSE 'ERRO'
    END AS TIPOPGTO,
    CHAVEBOLETO, BANCO, AGENCIA, CONTA, PIX
FROM CALC_NOTIFICA
WHERE PEDIDOCONF = 72

UNION

SELECT
    ESTAB, CNPJ, REDUZIDO, SERIE, NUM_PED, PEDIDO, FORNECEDOR, CONCEITO,
    CONTAMOV_CNPJF AS CNPJF_FORNECEDOR,
    IE_FORNECEDOR, COD_CONFIG, CONFIG, DTEMISSAO, VENCIMENTO, VALORTOTAL,
    USERID, PLACA, DESCRICAO, TIPO_PROD, ERROCHAVENFE, REGRA_NOTACONF, CHAVCHAVENF,
    CASE
        WHEN PEDIDOCONF IN (67) THEN 'A'
        WHEN CHAVEBOLETO IS NOT NULL THEN 'B'
        WHEN PIX IS NOT NULL THEN 'P'
        WHEN BANCO IS NOT NULL AND AGENCIA IS NOT NULL AND CONTA IS NOT NULL THEN 'D'
        ELSE 'ERRO'
    END AS TIPOPGTO,
    CHAVEBOLETO, BANCO, AGENCIA, CONTA, PIX
FROM CALC_67

UNION ALL

/* ---- Bloco 2: equivalente ao UNION ALL original com a lista ampla,
   filtrado por REGRA_NOTACONF/TIPO_PROD, TIPOPGTO com a regra
   "PEDIDOCONF IN (67, 72)". Reaproveita o mesmo CALC_NOTIFICA já
   materializado -- não refaz o join. ---- */
SELECT
    ESTAB, CNPJ, REDUZIDO, SERIE, NUM_PED, PEDIDO, FORNECEDOR, CONCEITO,
    CONTAMOV_CNPJF AS CNPJF_FORNECEDOR,
    IE_FORNECEDOR, COD_CONFIG, CONFIG, DTEMISSAO, VENCIMENTO, VALORTOTAL,
    USERID, PLACA, DESCRICAO, TIPO_PROD, ERROCHAVENFE, REGRA_NOTACONF, CHAVCHAVENF,
    CASE
        WHEN PEDIDOCONF IN (67, 72) THEN 'A'
        WHEN CHAVEBOLETO IS NOT NULL THEN 'B'
        WHEN PIX IS NOT NULL THEN 'P'
        WHEN BANCO IS NOT NULL AND AGENCIA IS NOT NULL AND CONTA IS NOT NULL THEN 'D'
        ELSE 'ERRO'
    END AS TIPOPGTO,
    CHAVEBOLETO, BANCO, AGENCIA, CONTA, PIX
FROM CALC_NOTIFICA
WHERE REGRA_NOTACONF IN (800, 825)
  AND TIPO_PROD = 'P'