SELECT
dados.estab,
dados.seqnota,
dados.item,
dados.nota,
dados.total,
dados.nomeprestador,
(SELECT COUNT(SEQNOTA) FROM CTRCNFCAB WHERE ESTAB = DADOS.ESTAB AND SEQNOTA = DADOS.SEQNOTA) AS qtdcte,
dados.NROCTRC,
dados.SEQCTRC,
TO_CHAR (dados.dtentrada,'DD/MM/YYYY')DTENTRADA
from(
SELECT DISTINCT
       CTRC.ESTAB,
       nfcab.seqnota,
       ctrcnfcab.seqctrc,
       nfitem.item,
       NFCAB.NOTA,
       CTRC.TOTAL,
       CTRCNFCAB.NOMEPRESTADOR,
       CTRC.NROCTRC,
       CTRC.DTENTRADA
FROM NFCAB

INNER JOIN CTRCNFCAB
ON CTRCNFCAB.ESTAB = NFCAB.ESTAB
AND CTRCNFCAB.SEQNOTA = NFCAB.SEQNOTA

LEFT JOIN CTRC
ON CTRC.ESTAB = CTRCNFCAB.ESTAB
AND CTRC.SEQCTRC = ctrcnfcab.SEQCTRC

INNER JOIN NFITEM
ON NFITEM.ESTAB = NFCAB.ESTAB
AND NFITEM.SEQNOTA = NFCAB.SEQNOTA
and nfitem.item<=50


LEFT JOIN U_TEMPRESA
ON U_TEMPRESA.ESTAB = CTRCNFCAB.ESTAB

WHERE 
U_TEMPRESA.GRAOS = 'S'
AND CTRCNFCAB.TIPOCTRC = 0
--AND CTRC.CODIGOCFG NOT IN (17,19)
  
ORDER BY
    CTRC.ESTAB
    
    )dados

LEFT JOIN U_DATA_ORION ON 0 = 0

where 
((0 IN (:ESTAB)) OR (DADOS.ESTAB IN (:ESTAB)))	  
AND NOT EXISTS (SELECT * FROM u_audcte WHERE  u_audcte.SEQCTRC = DADOS.SEQCTRC AND u_audcte.ESTAB = DADOS.ESTAB)

group by 
dados.estab,
dados.seqnota,
dados.item,
dados.nota,
dados.total,
dados.nomeprestador,
dados.NROCTRC,
DADOS.SEQCTRC,
dados.dtentrada

HAVING
(SELECT COUNT(CTRCNFCAB.SEQNOTA) FROM CTRCNFCAB WHERE CTRCNFCAB.ESTAB = DADOS.ESTAB AND CTRCNFCAB.SEQNOTA = DADOS.SEQNOTA AND CTRCNFCAB.TIPOCTRC = 0) > 1