SELECT
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
NFCFG.DESCRICAO||' - '||NFCFG.NOTACONF AS DESCRICAO,
U_AGRPRODGR.DESCAGRUPA AS PRODUTO,
ARREDONDAR(COALESCE(SUM(NFITEM.QUANTIDADE),0),2)QUANTIDADE

FROM NFCAB

INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

INNER JOIN NFITEM ON NFITEM.ESTAB = NFCAB.ESTAB
                AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM

LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM

LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID


WHERE NFCFG.NOTACONF IN (205,250,251,248)

AND NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM

AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))

AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB)) 
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))

GROUP BY
FILIAL.ESTAB,
FILIAL.REDUZIDO,
NFCFG.DESCRICAO,
U_AGRPRODGR.DESCAGRUPA,NFCFG.NOTACONF
