WITH CTRNOTA AS (
    SELECT /*+ 
        QB_NAME(CTRNOTA_QB)
        MATERIALIZE
        NO_MERGE
        USE_HASH(NAT NATAPARTIRDE NFCFG)
        USE_NL(CONTRATONFITE NFCAB)
        INDEX(CONTRATONFITE IDX_FK_CONTITE_CONTRATONFITE)
        INDEX(NFCAB NFCAB01)
    */
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END BAIXADO_VLR,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END DEVOLIDO_VLR,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','V') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.VALOR
        ELSE 0
    END CANCELADO_VLR
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATOITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE U_TIPOCTR.TIPOCTR IN ('CTR-V','CTR-VF')
    AND CONTRATO.DTEMISSAO BETWEEN :DTINIEMI AND :DTFIMEMI
    AND CONTRATO.DTLIMENTIMP BETWEEN :DTMINI AND :DTMFIM
),
BAIXAS AS (
    SELECT 
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO,
    SUM(BAIXADO_VLR) AS BAIXADO_VLR,
    SUM(DEVOLIDO_VLR) AS DEVOLIDO_VLR,
    SUM(CANCELADO_VLR) AS CANCELADO_VLR
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC,
    SUM(CONTRATOCANC.VALOR) AS VLR_CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE U_TIPOCTR.TIPOCTR IN ('CTR-V','CTR-VF')
    AND CONTRATO.DTEMISSAO BETWEEN :DTINIEMI AND :DTFIMEMI
    AND CONTRATO.DTLIMENTIMP BETWEEN :DTMINI AND :DTMFIM
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
SALDO_MANUAL AS (
    SELECT 
    CONTRATO.ESTAB,
    SUBSTR(FILIAL.REDUZIDO,13,400)as REDUZIDO,
    CONTRATOCFG.ENTRADASAIDA ES,
    CONTRATO.CONTCONF,CONTRATOCFG.DESCRICAO,
    CONTRATO.NUMEROCM, 
    SUBSTR(CONTAMOV.NOME,0,10)AS NOME,
    CONTRATO.CONTRATO,
    CONTRATO.NUMCOMPRADOR,
    CONTRATO.NUMINTERMEDIARIO,
    TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY')DTEMISSAO,
    TO_CHAR(CONTRATO.DTVENCTO,'DD/MM/YYYY') AS DTVENCTO,
    TO_CHAR(CONTRATO.DTLIMENTIMP,'DD/MM/YYYY') AS DTLIMITE,
    TO_CHAR(CONTRATO.DTLIMENTIMP, 'MM')||'-'||TO_CHAR(CONTRATO.DTLIMENTIMP, 'MON')MESENT,
    CONTRATO.SAFRA,
    CONTRATO.DTMOVSALDO,
    CONTRATOITE.ITEM,
    CONTRATOITE.LOCAL,
    COALESCE(CIDEND.NOME,CID.NOME)CIDENTREGA,
    CONTRATO.PESSENTREGA,
    CONTRATO.PESSRETIRADA,
    CONTRATO_U.STATUSASS,
    CONTRATO_U.STATUSAPROV,
    CONTRATO_U.STATUSFAT,
    CONTRATO.USERID,
    ARREDONDAR(DIVIDE(CONTRATOITE.QUANTIDADE,60),0) AS QTDCONTRATO,
    CONTRATOITE.VALORUNIT,
    CONTRATOITE.VALORTOTAL,
    ARREDONDAR(DIVIDE(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0),60), 0) AS QTDSALDO,
    ARREDONDAR(NVL(DIVIDE(BAIXAS.DEVOLIDO,60),0),0) AS QTDDEV,
    ARREDONDAR(NVL(DIVIDE(BAIXAS.CANCELADO,60),0)+NVL(DIVIDE(CANC.CANC,60),0),0) AS QTDCANC,
    ARREDONDAR(NVL(BAIXAS.DEVOLIDO,0),0) AS QTDDEV_KG, 
    ARREDONDAR(DIVIDE(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0),60), 0) AS SALDOLIQ,
    ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) AS SALDOLIQ_KG,
    ARREDONDAR(DIVIDE(CONTRATOITE.VALORTOTAL - NVL(BAIXAS.BAIXADO_VLR,0) - NVL(BAIXAS.CANCELADO_VLR,0) + NVL(BAIXAS.DEVOLIDO_VLR,0) - NVL(CANC.VLR_CANC,0),60), 0) AS VLRSALDO,
   ARREDONDAR(DIVIDE(CONTRATOITE.QUANTIDADE - 
   (
        (NVL(CANC.CANC,0) + NVL(BAIXAS.CANCELADO,0))
        +
        (CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0))
   ),60),0) SALDOENT,
     
    ARREDONDAR(CONTRATOITE.QUANTIDADE - 
   (
        (NVL(CANC.CANC,0) + NVL(BAIXAS.CANCELADO,0))
        +
        (CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0))
   ),0)  SALDOENT_KG
    
    FROM CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
    INNER JOIN CIDADE ON CIDADE.CIDADE=FILIAL.CIDADE
    INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
    INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
    
    INNER JOIN CONTRATO_U ON
        CONTRATO_U.ESTAB = CONTRATO.ESTAB
        AND CONTRATO_U.CONTRATO = CONTRATO.CONTRATO

    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATO.ESTAB 
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
    LEFT JOIN BAIXAS ON 
        BAIXAS.ESTAB = CONTRATOITE.ESTAB 
        AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
        AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM
    
    LEFT JOIN CANC ON 
        CANC.ESTAB = CONTRATOITE.ESTAB 
        AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
        AND CANC.SEQITEM = CONTRATOITE.SEQITEM
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = CONTRATOITE.ITEM
    LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID=ITEMAGRO_U.U_AGRPRODGR_ID
    
    LEFT JOIN CONTAMOV PESSRET ON PESSRET.NUMEROCM = CONTRATO.PESSENTREGA
    LEFT JOIN CIDADE CID ON CID.CIDADE = PESSRET.CIDADE
    LEFT JOIN ENDERECO ON 
        ENDERECO.NUMEROCM = CONTRATO.PESSENTREGA
        AND ENDERECO.SEQENDERECO = CONTRATO.SEQENDENTREGA                
    LEFT JOIN CIDADE CIDEND ON CIDEND.CIDADE = ENDERECO.CIDADE
    
    WHERE 
    U_TIPOCTR.TIPOCTR IN ('CTR-V','CTR-VF')
    AND U.GRAOS = 'S'
    --AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
    AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
    AND CONTRATO.DTEMISSAO BETWEEN :DTINIEMI AND :DTFIMEMI
    AND CONTRATO.DTLIMENTIMP BETWEEN :DTMINI AND :DTMFIM
    AND CONTRATO.ESTAB <> 800
    AND (
        (0 IN (:ITEM))
        OR
        (9999 IN (:ITEM) AND U_AGRPRODGR.U_AGRPRODGR_ID <> 998)
        OR
        (U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
    )
)


SELECT /*+ 
    LEADING(CONTRATO)
*/
S.*,
ARREDONDAR(DIVIDE(((S.SALDOLIQ_KG +S.QTDDEV_KG)- S.SALDOENT_KG),60),0) AS SALDOAENT,
CASE 
    WHEN S.PESSENTREGA IS NOT NULL THEN SUBSTR(S.NOME,0,10)||' - '||S.CIDENTREGA
    WHEN S.PESSENTREGA IS NULL AND S.pessretirada IS NOT NULL THEN 'FOB'
    ELSE 'S/Local' 
END LOCALRET,            
CASE 
    WHEN S.CIDENTREGA = 'Guarujá' OR S.CIDENTREGA = 'Paranaguá' or S.CIDENTREGA = 'Santos' THEN '1'
    WHEN S.PESSENTREGA IS NULL AND S.pessretirada IS NOT NULL THEN '1'
    WHEN S.CIDENTREGA IS NULL THEN '1'
    ELSE '0' 
END ELOCAL 
FROM SALDO_MANUAL S