WITH PEDIDOS AS
(
SELECT DISTINCT
PEDCAB.ESTAB,
 PEDCAB.MOEDA,
PEDCAB.SERIE,
PEDCAB.NUMERO,
PEDCAB.PESSOA,
PEDCAB.SEQENDERECO,
PEDCAB.REPRESENT,
PEDCAB.PEDIDOCONF,
PEDCAB.ETAPA,
TO_CHAR(PEDCAB.OBS) AS OBS,
PEDCAB.DTPREVISAO,
PEDCAB.DTVALIDADE,
PEDCAB.DTEMISSAO,
PEDCAB.HORAEMISSAO,
PEDCAB.KMFRETE,
PEDCAB.SEQENDENTREGA,
PEDCAB.PESSENTREGA,
PEDCAB.SEQENDRETIRADA,
PEDCAB.PESSRETIRADA,
PEDCAB.CANALDEVENDA,
PEDCAB.STATUS,
PEDCAB.SAFRA
FROM PEDCAB
INNER JOIN FILIAL F ON F.ESTAB = PEDCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = F.CIDADE
--INNER JOIN U_TEMPRESA ON PEDCAB.ESTAB = U_TEMPRESA.ESTAB
WHERE PEDCAB.PEDIDOCONF IN (200,201,202,203,250,204)
 AND PEDCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM  
 AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))
 --AND U_TEMPRESA.FARMACIA = 'S'
 --AND U_TEMPRESA.GRAOS = 'S'
 AND PEDCAB.STATUS <> 'C'
      AND PEDCAB.STATUS <> 'B' 
      AND (PEDCAB.ESTAB IN (:ESTAB) OR 0 IN (:ESTAB))
),

CONVERSAO AS (
    SELECT 
    *
    FROM 
    (
        SELECT moedaval.*,
               ROW_NUMBER() OVER (PARTITION BY moeda ORDER BY data DESC) AS rn
        FROM moedaval
    )dados
    WHERE rn = 1
),

DTPAGTO_CALC AS (
    SELECT 
        P.ESTAB, 
        P.SERIE, 
        P.NUMERO,
        MAX(DTPAG.NUMDIASPAGTO) AS NUMDIASPAGTO,
        MAX(
            (PGTO.PRAZOPAGAMENTO)--+ P.DTEMISSAO)
        ) AS DTPAGTO
    FROM PEDCAB P
    LEFT JOIN PEDCABPGTO PGTO ON P.ESTAB = PGTO.ESTAB 
                             AND P.SERIE = PGTO.SERIE 
                             AND P.NUMERO = PGTO.NUMERO
    LEFT JOIN PEDCABDTPAGTO DTPAG ON P.ESTAB = DTPAG.ESTAB 
                                 AND P.SERIE = DTPAG.SERIE 
                                 AND P.NUMERO = DTPAG.NUMERO
    WHERE P.PEDIDOCONF IN (200,201,202,203,250,204)
    AND P.DTEMISSAO BETWEEN :DTINI AND :DTFIM  
    AND P.STATUS <> 'C'
      AND P.STATUS <> 'B' 
      AND P.ETAPA IN (:ETAPA)                             
    GROUP BY P.ESTAB, P.SERIE, P.NUMERO
),

ANAL_FINANCEIRO AS 
(
    SELECT
    APRVPEDCABHIST.ESTAB,
    APRVPEDCABHIST.SERIE,
    APRVPEDCABHIST.NUMERO,
    'Análise Financeira' as ETAPA,
    (SELECT TO_CHAR(MAX(
               CASE 
                 WHEN LENGTH(I.HORAALTERACAO) = 5 THEN TO_TIMESTAMP(I.DTALTERACAO || ' ' || I.HORAALTERACAO, 'DD/MM/YY HH24:MI:SS')
                 WHEN LENGTH(I.HORAALTERACAO) = 8 THEN TO_TIMESTAMP(I.DTALTERACAO || ' ' || I.HORAALTERACAO, 'DD/MM/YY HH24:MI:SS')
                 ELSE NULL
               END), 'DD/MM/YYYY HH24:MI:SS') 
     FROM APRVPEDCABHIST I 
     WHERE I.ETAPA = 1 
       AND I.NUMERO = APRVPEDCABHIST.NUMERO 
       AND APRVPEDCABHIST.ESTAB = I.ESTAB 
       AND APRVPEDCABHIST.SERIE = I.SERIE) AS COMERCIAL,
    (SELECT TO_CHAR(MAX(
               CASE 
                 WHEN LENGTH(I.HORAALTERACAO) = 5 THEN TO_TIMESTAMP(I.DTALTERACAO || ' ' || I.HORAALTERACAO, 'DD/MM/YY HH24:MI:SS')
                 WHEN LENGTH(I.HORAALTERACAO) = 8 THEN TO_TIMESTAMP(I.DTALTERACAO || ' ' || I.HORAALTERACAO, 'DD/MM/YY HH24:MI:SS')
                 ELSE NULL
               END), 'DD/MM/YYYY HH24:MI:SS') 
     FROM APRVPEDCABHIST I 
     WHERE I.ETAPA = 2 
       AND I.NUMERO = APRVPEDCABHIST.NUMERO 
       AND APRVPEDCABHIST.ESTAB = I.ESTAB 
       AND APRVPEDCABHIST.SERIE = I.SERIE) AS FINANCEIRA
    FROM 
    APRVPEDCABHIST
    INNER JOIN PEDIDOS ON 
    PEDIDOS.ESTAB = APRVPEDCABHIST.ESTAB
	AND PEDIDOS.SERIE = APRVPEDCABHIST.SERIE
	AND PEDIDOS.NUMERO = APRVPEDCABHIST.NUMERO
    WHERE APRVPEDCABHIST.ETAPA IN (1,2) AND APRVPEDCABHIST.ACAO IS NOT NULL
    GROUP BY 
    APRVPEDCABHIST.ESTAB,
    APRVPEDCABHIST.SERIE,
    APRVPEDCABHIST.NUMERO
),

SALDO AS 
(
SELECT
    DADOS.ESTAB,
    DADOS.NUMEROCM AS PESSOA,
    DADOS.ITEM,
    ((((COALESCE(SUM(DADOS.ROMANEIOE),0) + COALESCE(SUM(DADOS.DEPOSITO),0)))- COALESCE(SUM(DADOS.ROMANEIOS),0))) SALDOPROD

FROM (
-------------------------------------
/*RETORNA ROMANEIO EM ABERTOS*/
SELECT
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,
    CONTAMOV.NUMEROCM,
    CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS PESSOA,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO PRODUTO,
    0 AS CONTRATO,
    CASE WHEN ROMA.TIPO IS NULL THEN 0 ELSE ROMA.TIPO END TIPO,
    CASE WHEN ROMACFG.entradasaida='E' THEN ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0)))) ELSE 0 END AS ROMANEIOE,
                              
   CASE WHEN ROMACFG.entradasaida='S' THEN ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0)))) ELSE 0 END AS ROMANEIOS,                           
    0 AS DEPOSITO   
    

FROM ROMA
    
    INNER JOIN PEDIDOS ON PEDIDOS.PESSOA = ROMA.NUMEROCM AND    
                          PEDIDOS.ESTAB  = ROMA.ESTAB  
    
    INNER JOIN FILIAL ON
    FILIAL.ESTAB            = ROMA.ESTAB

    INNER JOIN PEMPRESA ON
    PEMPRESA.EMPRESA        = FILIAL.EMPRESA

    INNER JOIN CIDADE FILCID ON
    FILCID.CIDADE           = FILIAL.CIDADE

    INNER JOIN ROMACFG ON
    ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM       = ROMA.NUMEROCM

    INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
    
    INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
    
    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM       = ROMA.NUMEROCM AND
    ENDERECO.SEQENDERECO    = ROMA.SEQENDERECO

    LEFT JOIN PPESSPRE ON
    PPESSPRE.PRESTADOR      = ROMA.PRESTADOR

    INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB         = ROMA.ESTAB AND
    ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
    ROMACLASS.PERCENTUAL    > 0

    INNER JOIN ROMACLASSNOME ON
    ROMACLASSNOME.CLASSIFICACAO = ROMACLASS.CLASSIFICACAO

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL or (ROMACLASS.ITEM = 0) THEN ROMA.ITEM ELSE ROMACLASS.ITEM END

    LEFT JOIN NFCABROMA ON
    NFCABROMA.ESTAB         = ROMACLASS.ESTAB AND
    NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO AND
    NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA AND
    NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM

    LEFT JOIN NFCAB ON
    NFCAB.ESTAB             = NFCABROMA.ESTAB AND
    NFCAB.SEQNOTA           = NFCABROMA.SEQNOTA


    WHERE NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
        WHERE NFCABROMA.ESTAB         = ROMACLASS.ESTAB
          AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
          AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
          AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM)
         AND ROMA.ESTORNADO            = 'N'
          AND ('X' IN (:UF) OR FILCID.UF IN (:UF))
        /* AND ((0 IN (:ESTAB)) OR (ROMA.ESTAB IN (:ESTAB)))
         AND roma.dtemissao BETWEEN :DTINI AND :DTFIM
        -- AND (0 IN (:NUMEROCM) or (ROMA.NUMEROCM  IN (:NUMEROCM)))
         AND (0 IN (:ITEM)     or (ROMA.ITEM      IN (:ITEM)))*/
   
   GROUP BY  FILIAL.ESTAB,
    FILIAL.REDUZIDO, 
    ROMACFG.entradasaida,
    CONTAMOV.NUMEROCM,
    CONTAMOV.NOME,CONTAMOV.NUMEROCM,    
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO,
    ROMA.TIPO
/*RETORNA DADOS DE DEPOSITO*/
UNION ALL

SELECT  DADOS.ESTAB,
        DADOS.REDUZIDO,
        DADOS.NUMEROCM,
         DADOS.PESSOA,
        DADOS.CONCEITO,       
        DADOS.ITEM,
        DADOS.PRODUTO,
        DADOS.CONTRATO,
        COALESCE(DADOS.TIPO,0)TIPO,
        DADOS.ROMANEIOE,
        DADOS.ROMANEIOS,
        SUM(DADOS.DEPOSITO)DEPOSITO

FROM(
SELECT
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,   
    CONTAMOV.NUMEROCM,
    CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS PESSOA,  
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO PRODUTO,
    0 AS CONTRATO,
    NFITEM.FINATIPOROMA AS TIPO,
    0 AS ROMANEIOE,
    0 AS ROMANEIOS,
    NFITEM.QUANTIDADE -
    COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                       INNER JOIN NFITEM NFI ON
                                       NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                                       NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                                       NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM

                                       INNER JOIN NFCAB NFDV ON
                                       NFDV.ESTAB = NFI.ESTAB AND
                                       NFDV.SEQNOTA = NFI.SEQNOTA

                                       INNER JOIN NFCFG NFCFGDV ON
                                       NFCFGDV.NOTACONF = NFDV.NOTACONF /*AND
                                       NFCFGDV.NOTACONF IN (207,208,221,233,259) */

                                       INNER JOIN NATOPERACAO NATDV ON
                                       NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                       NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                                       NATDV.TIPODCTO = 'D'

                                       WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                                         AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                         AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                                       ),0) -
    COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                       INNER JOIN NFITEM NFI ON
                                       NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                                       NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                                       NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM

                                       INNER JOIN NFCAB NFDV ON
                                       NFDV.ESTAB = NFI.ESTAB AND
                                       NFDV.SEQNOTA = NFI.SEQNOTA

                                       INNER JOIN NFCFG NFCFGDV ON
                                       NFCFGDV.NOTACONF = NFDV.NOTACONF

                                       INNER JOIN NATOPERACAO NATDV ON
                                       NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                       NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                                       NATDV.TIPODCTO = 'X'

                                       WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                                         AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                         AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                                       ),0) AS DEPOSITO
FROM NFCAB
    INNER JOIN PEDIDOS ON PEDIDOS.PESSOA = NFCAB.NUMEROCM AND    
                          PEDIDOS.ESTAB  = NFCAB.ESTAB   
     
    INNER JOIN FILIAL ON
    FILIAL.ESTAB            = NFCAB.ESTAB

    INNER JOIN CIDADE CIDFIL ON
    CIDFIL.CIDADE           = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF          = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA      = 'E'

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO            = 'A'

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM       = NFCAB.NUMEROCM
    
    INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
    
    INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM       = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO    = NFCAB.SEQENDERECO

    LEFT JOIN CIDADE ON
    CIDADE.CIDADE           = CASE WHEN NFCAB.SEQENDERECO IS NOT NULL AND NFCAB.SEQENDERECO > 0 THEN ENDERECO.CIDADE ELSE CONTAMOV.CIDADE END

    INNER JOIN NFITEM ON
    NFITEM.ESTAB            = NFCAB.ESTAB AND
    NFITEM.SEQNOTA          = NFCAB.SEQNOTA

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = NFITEM.ITEM

    WHERE  ('X' IN (:UF) OR CIDFIL.UF IN (:UF))
/*WHERE NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
  AND (0 IN (:ESTAB)    or (NFCAB.ESTAB     IN (:ESTAB)))
 -- AND (0 IN (:NUMEROCM) or (NFCAB.NUMEROCM  IN (:NUMEROCM)))
  AND (0 IN (:ITEM)     or (NFITEM.ITEM     IN (:ITEM)))*/
  )DADOS
  
  GROUP BY DADOS.ESTAB,
        DADOS.REDUZIDO,
        DADOS.NUMEROCM,
        DADOS.PESSOA,
        DADOS.CONCEITO,
        DADOS.ITEM,
        DADOS.PRODUTO,
        DADOS.CONTRATO,
        DADOS.ROMANEIOE,
        DADOS.ROMANEIOS,
        DADOS.TIPO
        
     HAVING   SUM(ARREDONDAR(DADOS.DEPOSITO,2))>0

)DADOS

GROUP BY

DADOS.ESTAB, DADOS.NUMEROCM,DADOS.ITEM
),


BLOQ AS 
(
SELECT
    DADOS.ESTAB,
    DADOS.CEDENTE,
    DADOS.ITEM,
    ARREDONDAR((SUM(DADOS.TRANSF)),2) AS TRANSF
FROM
(
SELECT
    NFITEMTRANSF_1.ESTAB,
    NFITEMTRANSF_1.CEDENTE,
    NFITEM_1.ITEM,

    CASE
        WHEN ( NFITEMTRANSFDET.DATALIBERADA IS NOT NULL
               OR NFITEMTRANSFDET.TIPODOCTO IS NOT NULL ) THEN
            0
        ELSE
            ARREDONDAR((COALESCE(
                SUM(NFITEMTRANSF_1.QTDETRANSF),
                0
            ) - COALESCE(
                SUM(NFITEMTRANSFDET.QTDETRANSF),
                0
            )) * -1,
                       2)
    END TRANSF

FROM
NFITEMTRANSF NFITEMTRANSF_1
    INNER JOIN PEDIDOS ON PEDIDOS.ESTAB = NFITEMTRANSF_1.ESTAB AND 
                          PEDIDOS.PESSOA = NFITEMTRANSF_1.CEDENTE
    INNER JOIN CONTAMOV     CONTAMOV_1 ON ( CONTAMOV_1.NUMEROCM = NFITEMTRANSF_1.CEDENTE )
    INNER JOIN CONTAMOV     CONTAMOV_2 ON ( CONTAMOV_2.NUMEROCM = NFITEMTRANSF_1.DESTINATARIO )
    INNER JOIN NFITEM       NFITEM_1 ON ( NFITEM_1.ESTAB = NFITEMTRANSF_1.ESTAB )
                                  AND ( NFITEM_1.SEQNOTA = NFITEMTRANSF_1.SEQNOTA )
                                  AND ( NFITEM_1.SEQNOTAITEM = NFITEMTRANSF_1.SEQNOTAITEM )
    INNER JOIN ITEMAGRO     ITEMAGRO_1 ON ( ITEMAGRO_1.ITEM = NFITEM_1.ITEM )
    LEFT JOIN NFITEMTRANSF NFITEMTRANSFDET ON NFITEMTRANSFDET.CEDENTE = CONTAMOV_2.NUMEROCM
                                              AND NFITEMTRANSFDET.DESTINATARIO = CONTAMOV_1.NUMEROCM
                                              AND NFITEMTRANSFDET.SEQNOTA = NFITEMTRANSF_1.SEQNOTA
                                              AND NFITEMTRANSFDET.NROCARTADEP = NFITEMTRANSFDET.NROCARTADEP
WHERE
    NFITEMTRANSF_1.NROCARTADEP <> 0

GROUP BY
    NFITEMTRANSF_1.ESTAB,
    NFITEMTRANSF_1.CEDENTE,
    NFITEMTRANSF_1.DATALIBERADA,
    NFITEMTRANSFDET.DATALIBERADA,
    NFITEMTRANSFDET.TIPODOCTO,
    NFITEM_1.ITEM
)DADOS
               
GROUP BY 
DADOS.ESTAB,
DADOS.CEDENTE,
DADOS.ITEM
)

select
*
from (      

SELECT DISTINCT
 CASE 
    WHEN TRUNC(DTPAGTO_CALC.DTPAGTO) - TRUNC(PEDIDOS.DTEMISSAO) <= 2 THEN 'Alta'
    WHEN TRUNC(DTPAGTO_CALC.DTPAGTO) - TRUNC(PEDIDOS.DTEMISSAO) <= 7 THEN 'Média'
    WHEN TRUNC(DTPAGTO_CALC.DTPAGTO) - TRUNC(PEDIDOS.DTEMISSAO) > 10 THEN 'Baixa'
    ELSE 'Sem Prioridade'
END AS PRIORIDADE,
CASE
    WHEN (PEDIDOS.ETAPA = 1) THEN '1 - Comercial'
    WHEN (PEDIDOS.ETAPA = 2) THEN '2 - Financeira'
    WHEN (PEDIDOS.ETAPA = 3) THEN '3 - Faturamento'
    WHEN (PEDIDOS.ETAPA = 4) THEN '4 - Pedido Liberado'
    WHEN (PEDIDOS.ETAPA = 5) THEN '5 - Pedido Atendido'
    ELSE 'Sem Etapa' 
END ETAPA,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
PEDIDOS.DTEMISSAO,
PEDIDOS.HORAEMISSAO,
PEDIDOS.PESSOA,
CONTAMOV.NOME AS CLIENTE,
CLASSPESSOA.CDCLASSPESSOA AS COD_CLASSPESSOA,
CLASSPESSOA.DESCRICAO AS DESC_CLASSPESSOA,
PEDIDOS.NUMERO AS PEDIDO,
PEDIDOS.SAFRA,
PEDIDOS.PEDIDOCONF,
CASE 
    WHEN PEDIDOS.PEDIDOCONF = 201 THEN 'LIVRE' 
    WHEN PEDIDOS.PEDIDOCONF = 250 THEN 'VENDA'  
    ELSE 'BRUTO' 
END CONFIG,
CASE 
    WHEN CONTAMOV.INDOPFUNRURAL = 2 THEN '2 - Sobre a folha de pagamento'
    WHEN CONTAMOV.INDOPFUNRURAL = 1 THEN ' 1 - Sobre a comercialização da sua produção'
    ELSE '0' 
END FUNRURAL,
PEDCAB_U.CONTCONF || ' - ' || COALESCE(CONTRATOCFG.DESCRICAO,'VAZIO') AS CONTRATO_CONF, 
U_AGRPRODGR.DESCAGRUPA AS PRODUTO,
COALESCE(PEDCAB_U.QTRIGO,'EM BRANCO')TPTRIGO,
PEDIDOS.DTPREVISAO AS DTINI,
PEDIDOS.DTVALIDADE AS DTFIM,
CASE WHEN DTPAGTO_CALC.DTPAGTO IS NULL THEN  TO_CHAR(DTPAGTO_CALC.NUMDIASPAGTO) ELSE TO_CHAR(DTPAGTO_CALC.DTPAGTO, 'DD/MM/YYYY') END DTPAGTO,
COALESCE(PEDCAB_U.TIPOPGTO,'Em Branco')TIPOPGTO,
COALESCE(PEDCAB_U.CESSAOCREDI,'EM BRANCO')CESSAOCREDITO,
COALESCE(PEDCAB_U.NRTICKET,'EM BRANCO')TICKET, 
COALESCE(PEDCAB_U.TIPOFRETES,'EM BRANCO')TPFRETE,
COALESCE(PEDCAB_U.TIPOPESSOA,'EM BRANCO')TIPOPESSOA,
COALESCE(PEDCAB_U.OS_TIPOENTREGA,'EM BRANCO')TPENTREGA,
CASE WHEN PEDIDOS.PEDIDOCONF = 250 THEN NULL ELSE LOCALEST_U.TIPOOP END TIPO_LOCAL,
CASE 
    WHEN PEDIDOS.PEDIDOCONF = 250 THEN COALESCE(END_ENT.SEQENDERECO,0)||' - '||COALESCE(END_ENT.ENDERECO,END_ENT2.ENDERECO) 
    ELSE LOCALEST.LOCAL||' - '||LOCALEST.DESCRICAO 
END LOCAL,
PESSOARESP.NUMEROCM||' - '||PESSOARESP.NOME AS PESSOARESP,
FUNC.NOME AS CONSULTOR,
CORRETOR_1.NOME AS CORRETOR_1,
CASE 
    WHEN PEDCAB_U.VLRCORRETOR1 IS NOT NULL THEN 'R$ ' || TO_CHAR(PEDCAB_U.VLRCORRETOR1/* * 0.01*/, 'FM999999990D00', 'NLS_NUMERIC_CHARACTERS='',.''')
    WHEN PEDCAB_U.percentual1 IS NOT NULL THEN '%' || TO_CHAR(PEDCAB_U.percentual1, 'FM999999990D00', 'NLS_NUMERIC_CHARACTERS='',.''')
    ELSE NULL 
END AS COMISS_1,
CORRETOR_2.NOME AS CORRETOR_2,
CASE 
    WHEN PEDCAB_U.VLRCORRETOR2 IS NOT NULL THEN 'R$ ' || TO_CHAR(PEDCAB_U.VLRCORRETOR2 /* * 0.01*/, 'FM999999990D00', 'NLS_NUMERIC_CHARACTERS='',.''')
    WHEN PEDCAB_U.percentual2 IS NOT NULL THEN '%' || TO_CHAR(PEDCAB_U.percentual2, 'FM999999990D00', 'NLS_NUMERIC_CHARACTERS='',.''')
    ELSE NULL
END AS COMISS_2,
TO_CHAR(PEDIDOS.OBS) as OBS, 
COALESCE(BLOQ.TRANSF,0) AS BLOQUEADO,
COALESCE(SALDO.SALDOPROD,0)SALDOPROD,
PEDITEM.QUANTIDADE AS KG,
ARREDONDAR(DIVIDE(PEDITEM.QUANTIDADE,60),0)QTDSC,
ARREDONDAR((DIVIDE(PEDITEM.VALOR,PEDITEM.QUANTIDADE)*60),2)VALORUNITARIO,
PEDITEM.VALOR * COALESCE(CONVERSAO.VALOR,1) AS VALOR,
CASE 
	WHEN PEDCFG.ENTRADASAIDA = 'S' THEN NULL
	WHEN U_LOGPEDCTR.ESTAB IS NULL THEN 'Aguardando emissão de contrato'
	WHEN CONTRATO.ATIVO = 'I' THEN 'Aguardando documentação'
	WHEN CONTRATO.ATIVO = 'A' THEN 'Processo finalizado' END VALIDACAO_DOC
FROM
PEDIDOS
LEFT JOIN
        (SELECT
            NOME,
            NUMEROCM,
            SEQENDERECO,
            CDCLASSPESSOA
        FROM ENDERECO
        UNION ALL
        SELECT
            NOME,
            NUMEROCM,
            CAST(0 AS NUMBER(38)) AS SEQENDERECO,
            CDCLASSPESSOA
        FROM CONTAMOV
        ) CONTAMOV_CLASSPESS
        ON  PEDIDOS.PESSOA = CONTAMOV_CLASSPESS.NUMEROCM
        AND PEDIDOS.SEQENDERECO = CONTAMOV_CLASSPESS.SEQENDERECO
        LEFT JOIN CLASSPESSOA
            ON CONTAMOV_CLASSPESS.CDCLASSPESSOA = CLASSPESSOA.CDCLASSPESSOA
--
LEFT JOIN PEDCFG on PEDCFG.PEDIDOCONF = PEDIDOS.PEDIDOCONF
INNER JOIN FILIAL ON FILIAL.ESTAB = PEDIDOS.ESTAB
LEFT JOIN PEDCAB_U ON PEDCAB_U.ESTAB = PEDIDOS.ESTAB
                AND PEDCAB_U.SERIE = PEDIDOS.SERIE
                AND PEDCAB_U.NUMERO = PEDIDOS.NUMERO
LEFT JOIN PEDITEM ON PEDITEM.ESTAB = PEDIDOS.ESTAB
                AND PEDITEM.SERIE = PEDIDOS.SERIE
                AND PEDITEM.NUMERO = PEDIDOS.NUMERO                
LEFT JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = PEDCAB_U.CONTCONF 
LEFT JOIN PPESCLI ON PPESCLI.CLIENTE = PEDIDOS.PESSOA
LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = PEDIDOS.PESSOA
LEFT JOIN CONCEITOPESSOA CONPESS ON CONPESS.NUMEROCM = CONTAMOV.NUMEROCM
LEFT JOIN CONCEITO CONCEITOP ON CONCEITOP.CONCEITO = CONPESS.CONCEITO
LEFT JOIN SALDO ON SALDO.ESTAB = PEDIDOS.ESTAB AND 
                   SALDO.PESSOA = PEDIDOS.PESSOA AND
                   SALDO.ITEM = PEDITEM.ITEM
LEFT JOIN BLOQ ON BLOQ.ESTAB = PEDIDOS.ESTAB AND 
                  BLOQ.CEDENTE = PEDIDOS.PESSOA AND
                  BLOQ.ITEM = PEDITEM.ITEM   
LEFT JOIN ENDERECO END_ENT ON END_ENT.NUMEROCM = COALESCE(PEDIDOS.PESSENTREGA, PEDIDOS.PESSRETIRADA)
                           AND END_ENT.SEQENDERECO = COALESCE(PEDIDOS.SEQENDENTREGA,PEDIDOS.SEQENDRETIRADA)
                           AND ((PEDIDOS.SEQENDENTREGA IS NOT NULL) or (PEDIDOS.SEQENDRETIRADA IS NOT NULL))                         
LEFT JOIN CONTAMOV END_ENT2 ON END_ENT2.NUMEROCM = COALESCE(PEDIDOS.PESSENTREGA, PEDIDOS.PESSRETIRADA) 
                                                 AND PEDIDOS.SEQENDENTREGA IS NULL 
                                                 AND PEDIDOS.SEQENDRETIRADA IS NULL      
LEFT JOIN LOCALEST ON LOCALEST.LOCAL = PEDITEM.LOCAL
                AND LOCALEST.ESTAB = PEDITEM.ESTAB
LEFT JOIN LOCALEST_U ON LOCALEST_U.ESTAB = LOCALEST.ESTAB
                AND LOCALEST_U.LOCAL = LOCALEST.LOCAL       
LEFT JOIN CONTAMOV PESSOARESP ON PESSOARESP.NUMEROCM = CASE WHEN PEDIDOS.PEDIDOCONF = 250 THEN COALESCE(PEDIDOS.PESSENTREGA, PEDIDOS.PESSRETIRADA) ELSE LOCALEST_U.NUMEROCM END          
LEFT JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM = PESSOARESP.NUMEROCM
LEFT JOIN CONCEITO ON CONCEITO.CONCEITO = CONCEITOPESSOA.CONCEITO
LEFT JOIN CONTAMOV FUNC ON FUNC.NUMEROCM = PEDIDOS.REPRESENT
LEFT JOIN CONTAMOV CORRETOR ON CORRETOR.NUMEROCM = PEDIDOS.CANALDEVENDA
LEFT JOIN CONTAMOV CORRETOR_1 ON CORRETOR_1.NUMEROCM = PEDCAB_U.CORRETOR1
LEFT JOIN CONTAMOV CORRETOR_2 ON CORRETOR_2.NUMEROCM = PEDCAB_U.CORRETOR2
LEFT JOIN ANAL_FINANCEIRO ON ANAL_FINANCEIRO.ESTAB = PEDIDOS.ESTAB AND 
                             ANAL_FINANCEIRO.SERIE = PEDIDOS.SERIE AND
                             ANAL_FINANCEIRO.NUMERO = PEDIDOS.NUMERO
INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = PEDITEM.ITEM
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID   
LEFT JOIN U_LOGPEDCTR ON U_LOGPEDCTR.ESTAB = PEDIDOS.ESTAB AND U_LOGPEDCTR.PEDIDO = PEDIDOS.NUMERO
LEFT JOIN CONTRATO ON CONTRATO.ESTAB = U_LOGPEDCTR.ESTAB AND
                      CONTRATO.CONTRATO = U_LOGPEDCTR.CONTRATO AND
                      CONTRATO.CONTCONF = U_LOGPEDCTR.CONFCTR
LEFT JOIN DTPAGTO_CALC ON DTPAGTO_CALC.ESTAB = PEDIDOS.ESTAB
                       AND DTPAGTO_CALC.SERIE = PEDIDOS.SERIE
                       AND DTPAGTO_CALC.NUMERO = PEDIDOS.NUMERO  
                       
LEFT JOIN CONVERSAO ON
        CONVERSAO.MOEDA = PEDIDOS.MOEDA
  )dados
  