WITH NOTAS_NAVIO AS (
    SELECT
    --NFCAB_U.NAVIO,
    NFCAB.EXPNAVIO AS NAVIO,
    NFCAB.NOTA,
    NFCAB.VALOR
    FROM NFCAB
    
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NFCAB_U ON 
        NFCAB_U.ESTAB = NFCAB.ESTAB
        AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
        
    WHERE
    NFCAB.NOTACONF NOT IN (381) AND NFCFG.FISCAL = 'S'
),

CANC AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(QUANTIDADE) CANC
    FROM CONTRATOCANC

    GROUP BY ESTAB,CONTRATO,SEQITEM
    
),
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND CONTRATONFITE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND CONTRATONFITE.TIPOBAIXA IN ('A','Q') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND CONTRATONFITE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN NFITEM ON NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = NFITEM.ESTAB AND NFCAB.SEQNOTA = NFITEM.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    WHERE CONTRATOCFG.CONTCONF = 26
),
BAIXAS_CTR AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
DPL AS (
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    (VALOR) AS VALOR
    FROM PRDUPRED

    UNION ALL
    
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    (VLRCHEQREC) AS VALOR
    FROM PRDURECH
    
    
    UNION ALL
    
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    VALOR
    FROM PRDUREDUP
    
    UNION ALL
    
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    VALOR
    FROM PRDURECAR
    
    UNION ALL
    
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    VALOR
    FROM PRDUREOUT
    
    UNION ALL
    
    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    VALOR
    FROM PRDURECM
    WHERE TROCO = 'N'
    
),

BAIXAS_DPL AS (

    SELECT
    EMPRESA,
    DUPREC,
    SEQRECBTO,
    SUM(VALOR) AS VALOR
    FROM DPL

    GROUP BY EMPRESA,DUPREC,SEQRECBTO

), 

BAIXAS AS (
    SELECT
    PRDUPREC.EMPRESA,
    AGRFINDUPREC.SEQPAGAMENTO,
    PDUPREC.VALOR - SUM(BAIXAS_DPL.VALOR) SALDO
    FROM PRDUPREC
    
    INNER JOIN BAIXAS_DPL ON 
        BAIXAS_DPL.EMPRESA = PRDUPREC.EMPRESA
        AND BAIXAS_DPL.DUPREC = PRDUPREC.DUPREC
        and BAIXAS_DPL.SEQRECBTO= PRDUPREC.SEQRECBTO
        
    INNER JOIN PDUPREC ON
        PDUPREC.EMPRESA = PRDUPREC.EMPRESA
        AND PDUPREC.DUPREC = PRDUPREC.DUPREC

    INNER JOIN AGRFINDUPREC ON
        AGRFINDUPREC.ESTAB = PDUPREC.EMPRESA
        AND AGRFINDUPREC.DUPREC = PDUPREC.DUPREC
    
    WHERE TIPOREC IN ('R')
   
    GROUP BY PRDUPREC.EMPRESA,AGRFINDUPREC.SEQPAGAMENTO,PDUPREC.VALOR
)

SELECT
*
FROM(
SELECT DISTINCT
CONTRATO.NUMCOMPRADOR AS BOLETA,
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
CONTRATO.CONTRATO,
ITEMAGRO.DESCRICAO AS PRODUTO,
TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
CONTRATOITE.VALORUNIT,
CONTRATONFITE.SEQNOTAITEM AS SEQITEM,
NAVIOS.DESCRICAO AS NAVIO,
NFCAB.NOTA AS NOTA_GERENCIAL,
BAIXAS.SALDO AS SALDO_DPL_GERENCIAL,
CONTRATONFITE.VALOR AS VALOR_GERENCIAL,
--NFCAB.VALOR AS VALOR_GERENCIAL,
TO_CHAR(CONTRATO.DTVENCTO,'DD/MM/YYYY') AS PRAZOPAGTO,
NOTAS_NAVIO.NOTA AS NOTAS_VENDA,
NOTAS_NAVIO.VALOR AS VALOR_VENDA,
CONTRATOITE.QUANTIDADE - COALESCE(CANC.CANC,0) as QTDECTR,
CONTRATONFITE.QUANTIDADE AS QTDENF,
--NFITEM.QUANTIDADE AS QTDENF,
--PSALDO.NQTDSALDO AS SALDO
ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS_CTR.BAIXADO,0) - COALESCE(BAIXAS_CTR.CANCELADO,0) + COALESCE(BAIXAS_CTR.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 2) AS SALDO
FROM CONTRATO

INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB

INNER JOIN CONTRATOITE ON
    CONTRATOITE.ESTAB = CONTRATO.ESTAB
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN BAIXAS_CTR ON
    BAIXAS_CTR.ESTAB  = CONTRATOITE.ESTAB
    AND BAIXAS_CTR.CONTRATO = CONTRATOITE.CONTRATO
    AND BAIXAS_CTR.SEQITEM = CONTRATOITE.SEQITEM
    
LEFT JOIN CONTRATONFITE ON
    CONTRATONFITE.ESTAB = CONTRATOITE.ESTAB
    AND CONTRATONFITE.CONTRATO = CONTRATOITE.CONTRATO
    AND CONTRATONFITE.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN NFITEM ON
    NFITEM.ESTAB = CONTRATONFITE.ESTABNOTA
    AND NFITEM.SEQNOTA = CONTRATONFITE.SEQNOTA
    AND NFITEM.SEQNOTAITEM = CONTRATONFITE.SEQNOTAITEM
    
LEFT JOIN NFCAB ON
    NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA
    AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA

LEFT JOIN NFCABAGRFIN ON
    NFCABAGRFIN.ESTAB = NFCAB.ESTAB
    AND NFCABAGRFIN.SEQNOTA = NFCAB.SEQNOTA

LEFT JOIN BAIXAS ON
    BAIXAS.EMPRESA = NFCABAGRFIN.ESTAB
    AND BAIXAS.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO
    
LEFT JOIN NFCAB_U ON
    NFCAB_U.ESTAB = NFCAB.ESTAB
    AND NFCAB_U.SEQNOTA = NFCAB.SEQNOTA
    
LEFT JOIN NAVIOS ON NAVIOS.NAVIO = NFCAB_U.NAVIO_OS

LEFT JOIN NOTAS_NAVIO ON NOTAS_NAVIO.NAVIO = NAVIOS.NAVIO

LEFT JOIN CANC ON
    CANC.ESTAB = CONTRATOITE.ESTAB
    AND CANC.CONTRATO = CONTRATOITE.CONTRATO
    AND CANC.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM

LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON u_agrprodgr.u_agrprodgr_id = ITEMAGRO_U.U_AGRPRODGR_ID


WHERE CONTCONF = 26
AND COALESCE(CONTRATO.ATIVO,'X') <> 'C'
AND (0 IN (:NAVIO) OR NAVIOS.NAVIO IN (:NAVIO))
AND (0 IN (:ITEM) OR u_agrprodgr.u_agrprodgr_id IN (:ITEM))

)DADOS

-- ORDER BY NAVIO
