WITH MAX_DATA AS (
    SELECT 
        ISALDO.ITEM,
        ISALDO.ESTAB,
        CODIGOSALDO,
        MAX(TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY')) AS DATA_MAX
    FROM ITEMSALDO ISALDO
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = ISALDO.ESTAB
    WHERE
    CODIGOSALDO in (1)
    AND U_TEMPRESA.GRAOS = 'S'
    AND TO_DATE('01/' || LPAD(COALESCE(ISALDO.MES, 1), 2, '0') || '/' || COALESCE(ISALDO.ANO, 1), 'DD/MM/YYYY') <= TO_DATE(SYSDATE,'DD/MM/YYYY')
  GROUP BY ISALDO.ITEM, ISALDO.ESTAB,CODIGOSALDO
),
BASE AS (
    SELECT
    ITEMAGROESTAB.ESTAB,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    U_AGRPRODGR.DESCAGRUPA,
    SUM(ITEMSALDO.SALDOQUANTIDADE) as SALDO
    FROM ITEMAGROESTAB
    
    LEFT JOIN ITEMSALDO ON 
        ITEMSALDO.ITEM = ITEMAGROESTAB.ITEM 
        AND ITEMSALDO.ESTAB = ITEMAGROESTAB.ESTAB 

    INNER JOIN MAX_DATA MD 
        ON MD.ITEM = ITEMSALDO.ITEM 
        AND MD.ESTAB = ITEMSALDO.ESTAB 
        AND MD.CODIGOSALDO = ITEMSALDO.CODIGOSALDO
        AND TO_DATE('01/' || LPAD(COALESCE(ITEMSALDO.MES, 1), 2, '0') || '/' || COALESCE(ITEMSALDO.ANO, 1), 'DD/MM/YYYY') = MD.DATA_MAX

    LEFT JOIN FILIAL ON FILIAL.ESTAB = ITEMAGROESTAB.ESTAB
    INNER JOIN U_TEMPRESA ON U_TEMPRESA.ESTAB = FILIAL.ESTAB

    LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGROESTAB.ITEM
    INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
    INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

    WHERE
    ITEMSALDO.CODIGOSALDO in (1)
    AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))

    GROUP BY
    ITEMAGROESTAB.ESTAB,
    U_AGRPRODGR.U_AGRPRODGR_ID,
    U_AGRPRODGR.DESCAGRUPA
)
SELECT
FILIAL.ESTAB,
FILIAL.REDUZIDO AS FILIAL,
U_AGRPRODGR.U_AGRPRODGR_ID AS IDAGR,
U_AGRPRODGR.DESCAGRUPA AS PRODUTO,
NFCFG.ENTRADASAIDA,
NFCFG.DESCRICAO||' - '||NFCFG.NOTACONF AS DESCRICAO,
SUM(
    CASE 
        WHEN NFCFG.ENTRADASAIDA = 'S' THEN (NFITEM.QUANTIDADE)*-1
        ELSE (NFITEM.QUANTIDADE) 
    END
) QUANTIDADE,
BASE.SALDO AS DISPONIVEL
FROM NFCAB

INNER JOIN NFITEM ON 
    NFITEM.ESTAB = NFCAB.ESTAB
    AND NFITEM.SEQNOTA = NFCAB.SEQNOTA

INNER JOIN FILIAL ON FILIAL.ESTAB = NFCAB.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

INNER JOIN U_TEMPRESA ON 
    U_TEMPRESA.ESTAB = FILIAL.ESTAB
    AND U_TEMPRESA.GRAOS = 'S'

INNER JOIN NFCFG ON 
    NFCFG.NOTACONF = NFCAB.NOTACONF
    AND NFCFG.NOTACONF IN (219,220,305,306,307,322,323,325,382,385,383,399,1031,1026,1027,1029,1030,1032,1035,1036,1012)

INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = NFITEM.ITEM

LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
INNER JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID
LEFT JOIN BASE ON
    BASE.ESTAB = NFCAB.ESTAB
    AND BASE.ITEM = U_AGRPRODGR.U_AGRPRODGR_ID

WHERE
NFCAB.STATUS <> 'C'
AND NFCAB.DTENTSAI BETWEEN :DTINI AND :DTFIM
AND (0 IN (:ITEM) OR U_AGRPRODGR.U_AGRPRODGR_ID IN (:ITEM))
AND (0 IN (:ESTAB) OR FILIAL.ESTAB IN (:ESTAB))
AND ('X' IN (:UF) OR CIDADE.UF IN (:UF))

GROUP BY
FILIAL.ESTAB,
FILIAL.REDUZIDO,
U_AGRPRODGR.U_AGRPRODGR_ID,
U_AGRPRODGR.DESCAGRUPA,
NFCFG.ENTRADASAIDA,
NFCFG.DESCRICAO,
NFCFG.NOTACONF,
BASE.SALDO