WITH 
CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN (NAT.TIPODCTO IN ('N','X','A','T') and NFCFG.NOTACONF not IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'E' AND CONTRATOCFG.ENTRADASAIDA = 'E' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN NAT.TIPODCTO IN ('D') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NAT.ENTRADASAIDA = 'S' AND CONTRATOCFG.ENTRADASAIDA = 'S' AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN 0
        WHEN (NAT.TIPODCTO = 'D' OR NFCFG.NOTACONF IN (1041)) AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE CONTRATOCFG.ENTRADASAIDA IN ('E','S')
),
BAIXAS AS (
    SELECT
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE CONTRATOCFG.ENTRADASAIDA IN ('E','S')
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
VENCTO AS (
    SELECT
    ESTAB,
    CONTRATO,
    MAX(DTVENCTO) AS DTVENCTO
    FROM CONTRATODTVENCTO C
    GROUP BY ESTAB,CONTRATO
),
SALDO_MANUAL AS (
SELECT 
    CONTRATO.ESTAB,
    CONTRATO.CONTRATO,
    U_AGRPRODGR.U_AGRPRODGR_ID AS ITEM,
    LOCALEST.LOCAL,
    CONTRATO.NUMEROCM,
    CONTRATO.SAFRA,
    ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0) QTDSALDO
FROM CONTRATO
LEFT JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID
LEFT JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM = CONTRATO.NUMEROCM
    AND ENDERECO.SEQENDERECO =  CONTRATO.ENDALTERNATIVO
INNER JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM
LEFT JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
INNER JOIN CIDADE ON CIDADE.CIDADE = FILIAL.CIDADE

LEFT JOIN CONTRATOITE ON 
    CONTRATOITE.ESTAB = CONTRATO.ESTAB 
    AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
LEFT JOIN LOCALEST ON 
    LOCALEST.ESTAB = CONTRATOITE.ESTAB
    AND LOCALEST.LOCAL = CONTRATOITE.LOCAL
    
LEFT JOIN BAIXAS ON 
    BAIXAS.ESTAB = CONTRATOITE.ESTAB 
    AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
    AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN CANC ON 
    CANC.ESTAB = CONTRATOITE.ESTAB 
    AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
    AND CANC.SEQITEM = CONTRATOITE.SEQITEM

LEFT JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
LEFT JOIN ITEMAGRO_U ON ITEMAGRO_U.ITEM = ITEMAGRO.ITEM
LEFT JOIN U_AGRPRODGR ON U_AGRPRODGR.U_AGRPRODGR_ID = ITEMAGRO_U.U_AGRPRODGR_ID

--LEFT JOIN CONTAMOV ON CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM

WHERE 
CONTRATOCFG.ENTRADASAIDA IN ('E','S')
AND U.GRAOS='S'
AND FILIAL.INATIVA = 'N'
--AND CONTAMOV.NUMEROCM = 162945
AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
),
PAGTO AS (
    SELECT
        ESTAB,
        SEQNOTA,
        SEQNOTAITEM,
        SEQUENCIA,
        SUM(NDIASPAGO) NDIASPAGO,
        SUM(QTDPAGO) QTDPG
    FROM NFITEMTXSERVICOPG
    GROUP BY
        ESTAB,
        SEQNOTA,
        SEQNOTAITEM,
        SEQUENCIA
)
SELECT 
    DADOS.*,
   DADOS.NDIASPAGO - DADOS.NDIASDEP  AS DIAS

FROM(
  SELECT 
    NFITEM_DEP.ESTAB,
    FILIAL.reduzido        AS DESC_ESTAB,
    NFITEM_DEP.SEQNOTA     AS SEQNOTADEP,
    NFITEM_DEP.SEQNOTAITEM AS SEQNOTAITEMDEP,
    NFCAB_DEP.NOTA,
    NFITEM_DEP.ROMANEIO,
    TO_CHAR(NFITEM_DEP.DTEMISSAO, 'DD/MM/YYYY') AS DTEMISSAO,
    NFCAB_DEP.NUMEROCM,
    NFCAB_DEP.NUMEROCM ||' - ' || CONTAMOV.NOME AS PESSOA,
CASE
    WHEN EXISTS (
        SELECT 1
        FROM SALDO_MANUAL SM
        WHERE
            SM.ESTAB    = NFITEM_DEP.ESTAB
        AND SM.LOCAL    = NFITEM_DEP.LOCAL
       -- AND SM.SAFRA    = NFITEM_DEP.SAFRA
        AND SM.ITEM     = ITEMAGRO_U_NF.U_AGRPRODGR_ID
        AND SM.NUMEROCM = NFCAB_DEP.NUMEROCM
        AND SM.QTDSALDO > 0
    )
    THEN 'SIM'
    ELSE 'NAO'
END AS TEM_CONTRATO,
    NFCAB_DEP.SEQENDERECO,
    COALESCE(ENDERECO.ENDERECO, CONTAMOV.ENDERECO) AS ENDERECO,
    NFITEMTXSERVICO.SERVICO,
    NFITEMTXSERVICO.SERVICO ||' - ' || ITEMAGRO_SERVICO.DESCRICAO AS DESCSERVICO,
    NFITEM_DEP.ITEM,
    NFITEM_DEP.ITEM ||' - ' || ITEMAGRO_NFITEM.DESCRICAO AS NOMEITEM,
    COALESCE(CASE
      WHEN (NFITEMTXSERVICO.CALCULASOBRE = 'F')
      OR (NFITEMTXSERVICO.CALCULASOBRE   = 'B')
      THEN TABPERSERVCAB.NDIACARENCIA
      WHEN (NFITEMTXSERVICO.CALCULASOBRE = 'I')
      OR (NFITEMTXSERVICO.CALCULASOBRE   = 'R')
      THEN TABPRCSERVCAB.NDIACARENCIA
    END, 0) AS NDIASCARENCIA,
    COALESCE(CASE
      WHEN (NFITEMTXSERVICO.TABPRCSERV > 0)
      THEN (NUMDIASDEPSERVICO(NFITEMTXSERVICO.DATADEP, :DTDEP, TABPRCSERVCAB.DTVIGENCIAINI, TABPRCSERVCAB.DTVIGENCIAFIN))
      WHEN (NFITEMTXSERVICO.TABPERSERV > 0)
      THEN (NUMDIASDEPSERVICO(NFITEMTXSERVICO.DATADEP, :DTDEP, TABPERSERVCAB.DTVIGENCIAINI, TABPERSERVCAB.DTVIGENCIAFIN))
      ELSE (NUMDIASDEPSERVICO(NFITEMTXSERVICO.DATADEP, :DTDEP, NULL, NULL))
    END, 0) AS NDIASDEP,
    TO_CHAR(NFITEMTXSERVICO.DATADEP, 'DD/MM/YYYY') AS DATADEP, 
    COALESCE(PAGTO.NDIASPAGO,0) AS NDIASPAGO,
    PAGTO.QTDPG AS QTD_PG
FROM NFITEMTXSERVICO 
  INNER JOIN NFITEM NFITEM_DEP 
    ON NFITEM_DEP.ESTAB = NFITEMTXSERVICO.ESTAB
    AND NFITEM_DEP.SEQNOTA = NFITEMTXSERVICO.SEQNOTA
    AND NFITEM_DEP.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
  INNER JOIN NFCAB NFCAB_DEP
    ON NFCAB_DEP.ESTAB   = NFITEM_DEP.ESTAB
    AND NFCAB_DEP.SEQNOTA = NFITEM_DEP.SEQNOTA
  INNER JOIN FILIAL 
    ON FILIAL.ESTAB = NFCAB_DEP.ESTAB
  INNER JOIN CONTAMOV 
    ON CONTAMOV.NUMEROCM = NFCAB_DEP.NUMEROCM
  INNER JOIN ITEMAGRO ITEMAGRO_NFITEM 
    ON ITEMAGRO_NFITEM.ITEM = NFITEM_DEP.ITEM
  LEFT JOIN ITEMAGRO_U ITEMAGRO_U_NF
    ON ITEMAGRO_U_NF.ITEM = NFITEM_DEP.ITEM  
    
  LEFT JOIN ENDERECO 
    ON ENDERECO.NUMEROCM = NFCAB_DEP.NUMEROCM
    AND ENDERECO.SEQENDERECO = NFCAB_DEP.SEQENDERECO
  LEFT JOIN ITEMAGRO ITEMAGRO_SERVICO 
    ON ITEMAGRO_SERVICO.ITEM = NFITEMTXSERVICO.SERVICO
  LEFT JOIN NFCABROMA 
    ON NFCABROMA.ESTAB = NFITEM_DEP.ESTAB
    AND NFCABROMA.SEQNOTA = NFITEM_DEP.SEQNOTA
    AND NFCABROMA.ROMANEIO = NFITEM_DEP.ROMANEIO
  LEFT JOIN ROMA 
    ON ROMA.ESTAB = NFCABROMA.ESTAB
    AND ROMA.ROMANEIO = NFCABROMA.ROMANEIO
    AND ROMA.NUMEROCM = NFCABROMA.NUMEROCM
    AND ROMA.ENTRADASAIDA = NFCABROMA.ENTRADASAIDA
  LEFT JOIN RETENPORTO 
    ON RETENPORTO.ESTAB = NFITEM_DEP.ESTAB
    AND RETENPORTO.SEQNOTA = NFITEM_DEP.SEQNOTA
    AND RETENPORTO.SEQNOTAITEM = NFITEM_DEP.SEQNOTAITEM
    AND RETENPORTO.ITEM = NFITEM_DEP.ITEM
    AND RETENPORTO.TRANSACAO = 'E'
  LEFT JOIN TABPERSERVCAB 
    ON TABPERSERVCAB.TABELA = NFITEMTXSERVICO.TABPERSERV
  LEFT JOIN TABPRCSERVCAB
    ON TABPRCSERVCAB.TABELA = NFITEMTXSERVICO.TABPRCSERV
  LEFT JOIN CONTAMOV CONTAMOV_TER 
    ON CONTAMOV_TER.NUMEROCM = NFITEM_DEP.TERCEIRO
 LEFT JOIN PAGTO
    ON PAGTO.ESTAB = NFITEMTXSERVICO.ESTAB
   AND PAGTO.SEQNOTA = NFITEMTXSERVICO.SEQNOTA
   AND PAGTO.SEQNOTAITEM = NFITEMTXSERVICO.SEQNOTAITEM
   AND PAGTO.SEQUENCIA = NFITEMTXSERVICO.SEQUENCIA
  WHERE ('C' = :SITUACAO OR 'T' = :SITUACAO) 
  
    --AND NFITEMTXSERVICO.DATADEP BETWEEN :DTINI AND :DTFIM  
    AND CURRENT_DATE BETWEEN COALESCE(COALESCE(TABPRCSERVCAB.DTVIGENCIAINI, TABPERSERVCAB.DTVIGENCIAINI), CURRENT_DATE)  AND COALESCE(COALESCE(TABPRCSERVCAB.DTVIGENCIAFIN, TABPERSERVCAB.DTVIGENCIAFIN), CURRENT_DATE)
    AND NFITEMTXSERVICO.SITUACAO = 'P'
    <#if ESTAB ? has_content>
      AND NFCAB_DEP.ESTAB IN (:ESTAB) 
   </#if>
   <#if SERVICO ? has_content>
      AND NFITEMTXSERVICO.SERVICO IN (:SERVICO) 
   </#if>
   <#if ITEM ? has_content>
    AND ITEMAGRO_NFITEM.ITEM IN (:ITEM) 
 </#if>
      AND (
            (case when NFITEMTXSERVICO.CALCULASOBRE = 'R' then 'I' ELSE NFITEMTXSERVICO.CALCULASOBRE END) = :CALCULASOBRE 
            OR 'A' = :CALCULASOBRE
        )
    AND ((((NFITEMTXSERVICO.COBUNICA = 'S') or (NFITEMTXSERVICO.COBUNICA = 'C')) 
          and roma.romaneioconfig not in (10)
    AND NOT EXISTS
      (SELECT *
      FROM NFITEMPGSERVICO
      WHERE (NFITEMPGSERVICO.ESTAB        = NFITEMTXSERVICO.ESTAB)
      AND (NFITEMPGSERVICO.SEQNOTADEP     = NFITEMTXSERVICO.SEQNOTA)
      AND (NFITEMPGSERVICO.SEQNOTAITEMDEP = NFITEMTXSERVICO.SEQNOTAITEM)
      AND (NFITEMPGSERVICO.SEQUENCIA      = NFITEMTXSERVICO.SEQUENCIA)
      )
  )
    OR (NFITEMTXSERVICO.COBUNICA = 'N') )
    AND (
      CASE
        WHEN NFITEMTXSERVICO.COBUNICA = 'S'
        THEN
          CASE
            WHEN (NFITEMTXSERVICO.CALCULASOBRE = 'B')
            OR (NFITEMTXSERVICO.CALCULASOBRE   = 'R')
            THEN (ROMA.PESOTOTAL - ROMA.TARA)
            ELSE ROMA.PESOLIQUIDO
          END    
        ELSE (
          (SELECT (NFITEM.QUANTIDADE + COALESCE(
            (SELECT SUM(NFITEMTRANSF_TR.QTDETRANSF)
            FROM NFITEMTRANSF NFITEMTRANSF_TR
            WHERE (NFITEMTRANSF_TR.ESTAB      = NFITEM.ESTAB)
            AND (NFITEMTRANSF_TR.SEQNOTA      = NFITEM.SEQNOTA)
            AND (NFITEMTRANSF_TR.SEQNOTAITEM  = NFITEM.SEQNOTAITEM)
            AND (NFITEMTRANSF_TR.DESTINATARIO = NFCAB_A.NUMEROCM)
            AND (NOT EXISTS
              (SELECT NFITEMAPARTIRDE_TR.*
              FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_TR
              WHERE (NFITEMAPARTIRDE_TR.ESTABORIGEM     = NFITEMTRANSF_TR.ESTAB)
              AND (NFITEMAPARTIRDE_TR.SEQNOTAORIGEM     = NFITEMTRANSF_TR.SEQNOTA)
              AND (NFITEMAPARTIRDE_TR.SEQNOTAITEMORIGEM = NFITEMTRANSF_TR.SEQNOTAITEM)
              AND (NFITEMAPARTIRDE_TR.SEQTRANSF         = NFITEMTRANSF_TR.SEQTRANSF)
              AND (NFITEMAPARTIRDE_TR.SEQTRANSF        <> 0)
              ))
            ),0)
            ) - ( COALESCE(
            (SELECT SUM(NFITEMAPARTIRDE_X.QUANTIDADE)
            FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_X,
              NFCAB NFCAB_X,
              NFCFG NFCFG_X,
              NATOPERACAO NATOPERACAO_X
            WHERE (NFCAB_X.ESTAB(+) = NFITEMAPARTIRDE_X.ESTAB)
            AND (NFCAB_X.SEQNOTA(+) = NFITEMAPARTIRDE_X.SEQNOTA)
            AND (NFCFG_X.NOTACONF(+) = NFCAB_X.NOTACONF)
            AND (NATOPERACAO_X.NATUREZADAOPERACAO(+) = NFCFG_X.NATUREZADAOPERACAO)
            AND (NATOPERACAO_X.ENTRADASAIDA(+)       = NFCFG_X.ENTRADASAIDA)
            AND (NFITEMAPARTIRDE_X.ESTABORIGEM       = NFITEM.ESTAB)
            AND (NFITEMAPARTIRDE_X.SEQNOTAORIGEM     = NFITEM.SEQNOTA)
            AND (NFITEMAPARTIRDE_X.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
            AND (NFITEMAPARTIRDE_X.SEQTRANSF         = 0)
            AND (NFCAB_X.NUMEROCM                    = NFCAB_A.NUMEROCM)
            AND (NATOPERACAO_X.TIPODCTO             IN ('X','N') )
            ),0)
                                                      + COALESCE(
            (SELECT SUM(NFITEMAPARTIRDE_X.QUANTIDADE) + SUM(NVLF0(NFITEMAPARTIRDE_X.QTDEARMAZENAGEM)) + SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOSEGURO)) + SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOQUEBRA)) + SUM
    (NVLF0(NFITEMAPARTIRDE_X.DESCTOEXPED))+ SUM(NVLF0(NFITEMAPARTIRDE_X.DESCTOFINALIDADE))
            FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_X,
              NFCAB NFCAB_X,
              NFCFG NFCFG_X,
              NATOPERACAO NATOPERACAO_X
            WHERE (NFCAB_X.ESTAB(+) = NFITEMAPARTIRDE_X.ESTAB)
            AND (NFCAB_X.SEQNOTA(+) = NFITEMAPARTIRDE_X.SEQNOTA)
            AND (NFCFG_X.NOTACONF(+) = NFCAB_X.NOTACONF)
            AND (NATOPERACAO_X.NATUREZADAOPERACAO(+) = NFCFG_X.NATUREZADAOPERACAO)
            AND (NATOPERACAO_X.ENTRADASAIDA(+)       = NFCFG_X.ENTRADASAIDA)
            AND (NFITEMAPARTIRDE_X.ESTABORIGEM       = NFITEM.ESTAB)
            AND (NFITEMAPARTIRDE_X.SEQNOTAORIGEM     = NFITEM.SEQNOTA)
            AND (NFITEMAPARTIRDE_X.SEQNOTAITEMORIGEM = NFITEM.SEQNOTAITEM)
            AND (NFITEMAPARTIRDE_X.SEQTRANSF         = 0)
            AND (NATOPERACAO_X.TIPODCTO              = 'D')
            ),0)
            + COALESCE(
            (SELECT SUM(NFITEMTRANSF_TC.QTDETRANSF)
            FROM NFITEMTRANSF NFITEMTRANSF_TC,
              NFCAB NFCAB_X,
              NFCFG NFCFG_X,
              NATOPERACAO NATOPERACAO_X
            WHERE (NFCAB_X.ESTAB(+) = NFITEMTRANSF_TC.ESTAB)
            AND (NFCAB_X.SEQNOTA(+) = NFITEMTRANSF_TC.SEQNOTA)
            AND (NFCFG_X.NOTACONF(+) = NFCAB_X.NOTACONF)
            AND (NATOPERACAO_X.NATUREZADAOPERACAO(+) = NFCFG_X.NATUREZADAOPERACAO)
            AND (NATOPERACAO_X.ENTRADASAIDA(+)       = NFCFG_X.ENTRADASAIDA)
            AND (NFITEMTRANSF_TC.ESTAB               = NFITEM.ESTAB)
            AND (NFITEMTRANSF_TC.SEQNOTA             = NFITEM.SEQNOTA)
            AND (NFITEMTRANSF_TC.SEQNOTAITEM         = NFITEM.SEQNOTAITEM)
            AND (NFITEMTRANSF_TC.CEDENTE             = NFCAB_A.NUMEROCM)
            AND (NOT EXISTS
              (SELECT NFITEMAPARTIRDE_TC.*
              FROM NFITEMAPARTIRDE NFITEMAPARTIRDE_TC
              WHERE (NFITEMAPARTIRDE_TC.ESTABORIGEM     = NFITEMTRANSF_TC.ESTAB)
              AND (NFITEMAPARTIRDE_TC.SEQNOTAORIGEM     = NFITEMTRANSF_TC.SEQNOTA)
              AND (NFITEMAPARTIRDE_TC.SEQNOTAITEMORIGEM = NFITEMTRANSF_TC.SEQNOTAITEM)
              AND (NFITEMAPARTIRDE_TC.SEQTRANSF         = NFITEMTRANSF_TC.SEQTRANSF)
              AND (NFITEMAPARTIRDE_TC.SEQTRANSF        <> 0)
              AND (NATOPERACAO_X.TIPODCTO               = 'D')
              ))
            ),0)
            ) AS SALDO
          FROM NFCAB NFCAB_A,
            NFITEM,
            NFCFG NFCFG_NOTA,
            NATOPERACAO,
            ITEMAGRO,
            CONTAMOV,
            ITEMAGROESTAB
          WHERE (NFITEM.ESTAB(+) = NFCAB_A.ESTAB)
          AND (NFITEM.SEQNOTA(+) = NFCAB_A.SEQNOTA)
          AND (NFCFG_NOTA.NOTACONF(+) = NFCAB_A.NOTACONF)
          AND (NATOPERACAO.NATUREZADAOPERACAO(+) = NFCFG_NOTA.NATUREZADAOPERACAO)
          AND (NATOPERACAO.ENTRADASAIDA(+)       = NFCFG_NOTA.ENTRADASAIDA)
          AND (ITEMAGRO.ITEM(+) = NFITEM.ITEM)
          AND (CONTAMOV.NUMEROCM(+) = NFCAB_A.NUMEROCM)
          AND (ITEMAGROESTAB.ESTAB(+) = NFITEM.ESTAB)
          AND (ITEMAGROESTAB.ITEM(+)  = NFITEM.ITEM)
          AND
            (COALESCE(NFCAB_A.STATUS, 'N') <> 'C')
          AND (NFCFG_NOTA.ENTRADASAIDA      = 'E')
          AND (NFCAB_A.NUMEROCM             = NFCAB_DEP.NUMEROCM)
          AND (NFITEM.ESTAB                 = NFITEM_DEP.ESTAB )
          AND (NFITEM.SEQNOTA               = NFITEM_DEP.SEQNOTA)
          AND (NFITEM.SEQNOTAITEM           = NFITEM_DEP.SEQNOTAITEM)
          )- COALESCE(RETENPORTO.PESORETENCAO,0) )
      END > 0) 
) DADOS 