-- ### NOTAS QUE NÃO DEVEM SER CONSIDERAS
WITH NOTAS_EXCLUIDENTES AS (
   SELECT
    NFITEMAPARTIRDE.ESTABORIGEM,
    NFITEMAPARTIRDE.SEQNOTAORIGEM,
    NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
    FROM
    NFITEMAPARTIRDE
    
    INNER JOIN NFITEM NFI ON 
        NFI.ESTAB = NFITEMAPARTIRDE.ESTAB
        AND NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA
        AND NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM
    
    INNER JOIN NFCAB NFDV ON 
        NFDV.ESTAB = NFI.ESTAB
        AND NFDV.SEQNOTA = NFI.SEQNOTA
    
    INNER JOIN NFCFG NFCFGDV ON 
        NFCFGDV.NOTACONF = NFDV.NOTACONF
        AND NFCFGDV.NOTACONF IN (271)
    LEFT JOIN CTRCNFCAB CTRCNFCABDV ON 
        CTRCNFCABDV.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
        AND CTRCNFCABDV.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
    
    LEFT JOIN CTRC CTRCDV ON ( CTRCDV.SEQCTRC = CTRCNFCABDV.SEQCTRC )
    LEFT JOIN CTRCCFG CTRCCFGDV ON 
        ( CTRCCFGDV.ESTAB = CTRCDV.ESTAB )
        AND ( CTRCCFGDV.CODIGOCFG = CTRCDV.CODIGOCFG )
    
    INNER JOIN NATOPERACAO NATDV ON 
        NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO
        AND NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA
),

---- ## DUPLICATAS DOS CONTRATOS DE VENDA
BAIXAS AS (
    SELECT
    EMPRESA,
    DUPREC,
    --SUM(VALOR) AS VLR,
    SUM(PRDUPREC.VALOR * CASE WHEN PRDUPREC.TIPOREC IN ('R','J') THEN 1 ELSE -1 END) AS PAGO
    FROM PRDUPREC

    WHERE TIPOREC = 'R'
    AND IDCTB IS NOT NULL
    
    GROUP BY EMPRESA,DUPREC
),

DUPLICATAS AS (
    SELECT
    CONTRATO.ESTAB,
    CONTRATO.CONTRATO,
    BAIXAS.PAGO
    FROM CONTRATONFITE

    INNER JOIN NFCAB
    ON (NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA)
    AND (NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA)
    AND (NFCAB.STATUS <> 'C')
    
    inner join nfitem on nfitem.estab=nfcab.estab
                    and nfitem.seqnota=nfcab.seqnota
    
    INNER JOIN CONTRATO
    ON  (CONTRATO.ESTAB    = CONTRATONFITE.ESTAB)
    AND (CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO) 
    
    inner JOIN NFCABAGRFIN
    ON (NFCAB.ESTAB = NFCABAGRFIN.ESTAB)
    AND (NFCAB.SEQNOTA = NFCABAGRFIN.SEQNOTA)
    
    inner JOIN AGRFINDUPREC
    ON (AGRFINDUPREC.ESTAB = NFCABAGRFIN.ESTAB)
    AND (AGRFINDUPREC.SEQPAGAMENTO = NFCABAGRFIN.SEQPAGAMENTO)
    
    LEFT JOIN BAIXAS ON
    BAIXAS.EMPRESA = AGRFINDUPREC.ESTAB
    AND BAIXAS.DUPREC = AGRFINDUPREC.DUPREC
    
    WHERE NOT exists (
        SELECT 
        1 
        FROM NOTAS_EXCLUIDENTES
        WHERE NFITEM.ESTAB = NOTAS_EXCLUIDENTES.ESTABORIGEM
        AND NFITEM.SEQNOTA = NOTAS_EXCLUIDENTES.SEQNOTAORIGEM
        AND NFITEM.SEQNOTAITEM = NOTAS_EXCLUIDENTES.SEQNOTAITEMORIGEM
        )
),

--- #### RETEN PORTO
RETPORTO AS (
    SELECT
    NFITEM.CONTRATO,
    NFITEM.ESTAB,
    SUM(RETENPORTO.PESODESCARREGAMENTO)PESODESCARREGAMENTO,
    SUM(RETENPORTO.PESORETENCAO)  PESORETENCAO
    FROM NFITEM

    INNER JOIN RETENPORTO ON  
        RETENPORTO.ESTAB=NFITEM.ESTAB
        AND   RETENPORTO.SEQNOTA=NFITEM.SEQNOTA
        AND   RETENPORTO.SEQNOTAITEM=NFITEM.SEQNOTAITEM

    WHERE NOT EXISTS (
        SELECT 1
        FROM NOTAS_EXCLUIDENTES
        WHERE NFITEM.ESTAB = NOTAS_EXCLUIDENTES.ESTABORIGEM
        AND NFITEM.SEQNOTA = NOTAS_EXCLUIDENTES.SEQNOTAORIGEM
        AND NFITEM.SEQNOTAITEM = NOTAS_EXCLUIDENTES.SEQNOTAITEMORIGEM
    )
    
    GROUP BY NFITEM.CONTRATO, NFITEM.ESTAB
)
---- ########### SALDO CONTRATOS
SELECT
CONTRATO.ESTAB,
CONTRATOCFG.ENTRADASAIDA ES,
CONTRATO.CONTCONF,CONTRATOCFG.DESCRICAO,
CONTRATO.NUMEROCM, CONTAMOV.NOME,
CONTRATO.CONTRATO,
CONTRATO.NUMCOMPRADOR,
CONTRATO.SAFRA,
CONTRATO.NUMINTERMEDIARIO,
TO_CHAR(CONTRATO.DTEMISSAO,'DD/MM/YYYY') AS DTEMISSAO,
TO_CHAR(CONTRATO.DTVENCTO,'DD/MM/YYYY') AS DTVENCTO,
TO_CHAR(CONTRATO.DTLIMENTIMP,'DD/MM/YYYY') AS LIMENT,    
TO_CHAR(CONTRATO.DTMOVSALDO,'DD/MM/YYYY') AS DTMOVSALDO,
CONTRATOITE.ITEM,
CONTRATOITE.LOCAL,
CONTRATO_U.QTDORI AS QTDORIGINAL,
CONTRATOITE.QUANTIDADE AS QTDCONTRATO,
CONTRATO_U.QTDORI *  CONTRATOITE.VALORUNIT/60 AS VLRORIGINAL,
CONTRATOITE.VALORUNIT,
CONTRATOITE.VALORTOTAL,
CAST(COALESCE(PSALDO.NQTDSALDO,0)AS DECIMAL(18,2)) AS QTDSALDO,
COALESCE(PSALDO.NQTDDEV,0) AS QTDDEV,
ARREDONDAR(COALESCE(PSALDO.NQTDCANC,0),2) AS QTDCANC,
(COALESCE(PSALDO.NQTD,0) - (COALESCE(PSALDO.NQTDCANC,0) + COALESCE(PSALDO.NQTDSALDO,0)))SALDOENT,
COALESCE(PSALDO.NVLRSALDO,0) AS VLRSALDO,
CONTRATO_U.STATUSASS,
CONTRATO_U.STATUSAPROV,
CONTRATO_U.STATUSFAT,
CONTRATO.USERID,  
CASE WHEN CONTRATO.SAFRA >=2223 THEN (RETPORTO.PESODESCARREGAMENTO) ELSE  (RETPORTO.PESODESCARREGAMENTO) - (PSALDO.NQTDDEV) END PESODESCARREGAMENTO,
CASE WHEN CONTRATO.SAFRA >= 2223 THEN (RETPORTO.PESORETENCAO) ELSE (RETPORTO.PESORETENCAO) - (PSALDO.NQTDDEV) END PESORETENCAO,
COALESCE(DUPLICATAS.PAGO,0) AS VLR_RECEBIDO

    FROM CONTRATO

      INNER JOIN FILIAL ON
      (FILIAL.ESTAB = CONTRATO.ESTAB)

      INNER JOIN CONTAMOV ON
     (CONTAMOV.NUMEROCM = CONTRATO.NUMEROCM)

      INNER JOIN CONTRATOCFG ON
     (CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF)

     LEFT JOIN CONTRATO_U ON CONTRATO_U.ESTAB=CONTRATO.ESTAB
                        AND CONTRATO_U.CONTRATO=CONTRATO.CONTRATO
                        
    INNER JOIN U_TEMPRESA ON (U_TEMPRESA.ESTAB = CONTRATO.ESTAB)
    
      INNER JOIN CONTRATOITE ON
     (CONTRATOITE.ESTAB = CONTRATO.ESTAB)
     AND (CONTRATOITE.CONTRATO = CONTRATO.CONTRATO)

    INNER JOIN TABLE (PCONTRATOSALDO( CONTRATO.ESTAB,
                 CURRENT_DATE, CONTRATO.CONTRATO, CONTRATO.CONTRATO,
                 CONTRATOITE.SEQITEM, CONTRATOITE.SEQITEM, NULL, NULL, NULL,
                 NULL, NULL)) PSALDO
    ON (0=0)
    
    LEFT JOIN RETPORTO ON
        RETPORTO.ESTAB = CONTRATO.ESTAB
        AND RETPORTO.CONTRATO = CONTRATO.CONTRATO
        
    LEFT JOIN DUPLICATAS ON
        DUPLICATAS.ESTAB = CONTRATO.ESTAB
        AND DUPLICATAS.CONTRATO = CONTRATO.CONTRATO
    
where
CONTRATOITE.ITEM IN(1,3,2,6)

AND U_TEMPRESA.EXVENDA = 'S'
    
AND U_TEMPRESA.GRAOS = 'S'

AND CONTRATO.CONTCONF IN(20,21,23)

AND CONTRATO.DTMOVSALDO > ='01/01/2021' 