WITH CTRNOTA AS (
    SELECT
    CONTRATONFITE.ESTAB,
    CONTRATONFITE.CONTRATO,
    CONTRATONFITE.SEQITEM,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A','T') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCAB.NOTACONF NOT IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END BAIXADO,
    CASE 
        WHEN NAT.TIPODCTO = 'D' AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END DEVOLIDO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO,
    CASE 
        WHEN NAT.TIPODCTO IN ('N','X','A') AND NATAPARTIRDE.TIPOBAIXA IN ('A','Q') AND NFCFG.NOTACONF IN (291) AND NATAPARTIRDE.OPERACAO NOT IN ('N','R') THEN CONTRATONFITE.QUANTIDADE
        ELSE 0
    END CANCELADO_CALC
    FROM CONTRATONFITE
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATONFITE.ESTAB AND CONTRATO.CONTRATO = CONTRATONFITE.CONTRATO
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATONFITE.ESTAB
        AND CONTRATOITE.CONTRATO = CONTRATONFITE.CONTRATO
        AND CONTRATONFITE.SEQITEM = CONTRATONFITE.SEQITEM
    INNER JOIN NFCAB ON NFCAB.ESTAB = CONTRATONFITE.ESTABNOTA AND NFCAB.SEQNOTA = CONTRATONFITE.SEQNOTA
    INNER JOIN NFCFG ON NFCFG.NOTACONF = NFCAB.NOTACONF
    INNER JOIN NATOPERACAO NAT ON NAT.NATUREZADAOPERACAO = NFCFG.NATUREZADAOPERACAO AND NAT.ENTRADASAIDA = NFCFG.ENTRADASAIDA 
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID  
    LEFT JOIN NFCFG_U U ON U.NOTACONF = NFCFG.NOTACONF
    LEFT JOIN U_TIPOOP P ON U.U_TIPOOP_ID = P.U_TIPOOP_ID
    LEFT JOIN NATAPARTIRDE ON
        NATAPARTIRDE.NATUREZADAOPERACAO = NAT.NATUREZADAOPERACAO
        AND NATAPARTIRDE.ENTRADASAIDA = NAT.ENTRADASAIDA
        AND NATAPARTIRDE.NATOPERORIGEM = CONTRATOCFG.NATUREZA
        AND NATAPARTIRDE.ENTRADASAIDAORIGEM = CONTRATOCFG.ENTRADASAIDA
    WHERE U_TIPOCTR.TIPOCTR in ('CTR-C')
),
BAIXAS AS (
    SELECT 
    ESTAB,
    CONTRATO,
    SEQITEM,
    SUM(BAIXADO) AS BAIXADO,
    SUM(DEVOLIDO) AS DEVOLIDO,
    SUM(CANCELADO) AS CANCELADO
    FROM CTRNOTA
    GROUP BY ESTAB, CONTRATO, SEQITEM
),
CANC AS (
    SELECT
    CONTRATOCANC.ESTAB,
    CONTRATOCANC.CONTRATO,
    CONTRATOCANC.SEQITEM,
    SUM(CONTRATOCANC.QUANTIDADE) AS CANC
    FROM CONTRATOCANC
    INNER JOIN CONTRATO ON CONTRATO.ESTAB = CONTRATOCANC.ESTAB AND CONTRATO.CONTRATO = CONTRATOCANC.CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF    
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    WHERE U_TIPOCTR.TIPOCTR in ('CTR-C')
    GROUP BY CONTRATOCANC.ESTAB, CONTRATOCANC.CONTRATO, CONTRATOCANC.SEQITEM
),
SALDO_MANUAL AS (
    SELECT 
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,   
    CONTAMOV.NUMEROCM,
    contamov.cnpjf as cnpjf,
    CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS PESSOA, 
    CASE WHEN CONTAMOVGRUPO.GRUPOCM IS NULL THEN 'S/GRUPO'||' - '||CONTAMOV.NOME ELSE CONTAMOVGRUPO.GRUPOCM||' - '||CONTAMOVGRUPO.DESCRICAO END GRFAMILIA,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO PRODUTO,
    sum(ARREDONDAR(CONTRATOITE.QUANTIDADE - NVL(BAIXAS.BAIXADO,0) - NVL(BAIXAS.CANCELADO,0) + NVL(BAIXAS.DEVOLIDO,0) - NVL(CANC.CANC,0), 0)) AS CONTRATO,
    CONTRATOITE.LOCAL,
    0 AS TIPO,
    0 AS ROMANEIOE,
    0 AS ROMANEIOS,
    0 AS DEPOSITO
    FROM CONTRATO
    INNER JOIN CONTRATOCFG ON CONTRATOCFG.CONTCONF = CONTRATO.CONTCONF
    INNER JOIN CONTRATOCFG_U ON CONTRATOCFG_U.CONTCONF = CONTRATO.CONTCONF
    LEFT JOIN U_TIPOCTR ON U_TIPOCTR.U_TIPOCTR_ID = CONTRATOCFG_U.U_TIPOCTR_ID 
    INNER JOIN FILIAL ON FILIAL.ESTAB = CONTRATO.ESTAB
    INNER JOIN U_TEMPRESA U ON U.ESTAB = CONTRATO.ESTAB
    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM       = CONTRATO.NUMEROCM
    LEFT JOIN CONTAMOVGRUPO ON
    CONTAMOVGRUPO.GRUPOCM = CONTAMOV.GRUPOCM
    INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
    INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
    
    INNER JOIN CONTRATOITE ON 
        CONTRATOITE.ESTAB = CONTRATO.ESTAB 
        AND CONTRATOITE.CONTRATO = CONTRATO.CONTRATO
    
    LEFT JOIN BAIXAS ON 
        BAIXAS.ESTAB = CONTRATOITE.ESTAB 
        AND BAIXAS.CONTRATO = CONTRATOITE.CONTRATO 
        AND BAIXAS.SEQITEM = CONTRATOITE.SEQITEM
    
    LEFT JOIN CANC ON 
        CANC.ESTAB = CONTRATOITE.ESTAB 
        AND CANC.CONTRATO = CONTRATOITE.CONTRATO 
        AND CANC.SEQITEM = CONTRATOITE.SEQITEM
    
    INNER JOIN ITEMAGRO ON ITEMAGRO.ITEM = CONTRATOITE.ITEM
    WHERE 
    CONTRATO.NUMEROCM IS NOT NULL
    AND CONTRATO.DTMOVSALDO BETWEEN :DTINI AND :DTFIM
    AND (0 IN (:ESTAB)    or (CONTRATO.ESTAB     IN (:ESTAB)))
    AND (0 IN (:ITEM)     or (CONTRATOITE.ITEM   IN (:ITEM)))
    AND (0 IN (:SAFRA)    or (CONTRATO.SAFRA     IN (:SAFRA)))
    AND U_TIPOCTR.TIPOCTR IN ('CTR-C')
    --AND U.GRAOS = 'S'
    AND ARREDONDAR(CONTRATOITE.QUANTIDADE - COALESCE(BAIXAS.BAIXADO,0) - COALESCE(BAIXAS.CANCELADO,0) + COALESCE(BAIXAS.DEVOLIDO,0) - COALESCE(CANC.CANC,0), 0) > 0
    GROUP BY
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,  
    CONTAMOV.NUMEROCM,
    CONTAMOV.NOME,CONTAMOV.NUMEROCM, 
    CONCEITO.CONCEITO,CONCEITO.DESCRICAO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO,
     CONTRATOITE.LOCAL, CONTAMOVGRUPO.GRUPOCM ,CONTAMOVGRUPO.DESCRICAO,
  contamov.cnpjf
)
SELECT 
*
FROM(
SELECT
    DADOS.ESTAB, DADOS.REDUZIDO, DADOS.NUMEROCM, dados.cnpjf,DADOS.PESSOA,DADOS.GRFAMILIA,DADOS.CONCEITO, DADOS.ITEM, DADOS.PRODUTO,COALESCE(DADOS.TIPO,0)TIPO,  
    SUM(DADOS.ROMANEIOE) AS ROMANEIOE,
    SUM(DADOS.ROMANEIOS) AS ROMANEIOS,
    SUM(DADOS.DEPOSITO) AS DEPOSITO,
    ((((COALESCE(SUM(DADOS.ROMANEIOE),0) + COALESCE(SUM(DADOS.DEPOSITO),0)))- COALESCE(SUM(DADOS.ROMANEIOS),0))) SALDOPROD,
     SUM(DADOS.CONTRATO) AS CONTRATO,
     DADOS.LOCAL,
    (((COALESCE(SUM(DADOS.ROMANEIOE),0) + COALESCE(SUM(DADOS.DEPOSITO),0)) - (SUM(DADOS.CONTRATO)+ COALESCE(SUM(DADOS.ROMANEIOS),0)))) AS SALDOFIS
FROM (
-------------------------------------
/*RETORNA ROMANEIO EM ABERTOS*/
SELECT
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,
    CONTAMOV.NUMEROCM,
  contamov.cnpjf as cnpjf,
    CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS PESSOA,
    CASE WHEN CONTAMOVGRUPO.GRUPOCM IS NULL THEN 'S/GRUPO'||' - '||CONTAMOV.NOME ELSE CONTAMOVGRUPO.GRUPOCM||' - '||CONTAMOVGRUPO.DESCRICAO END GRFAMILIA,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO PRODUTO,
    0 AS CONTRATO,
    ROMA.LOCAL,
    CASE WHEN ROMA.TIPO IS NULL THEN 0 ELSE ROMA.TIPO END TIPO,
    CASE WHEN ROMACFG.entradasaida='E' THEN ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0)))) ELSE 0 END AS ROMANEIOE,
                              
   CASE WHEN ROMACFG.entradasaida='S' THEN ((SUM(COALESCE(ROMA.PESOLIQUIDO,0)) -
    SUM(COALESCE((SELECT SUM(COALESCE(ROMATXSERVICOPG.QTDEPAGO,0)) FROM ROMATXSERVICOPG
                            WHERE ROMATXSERVICOPG.ESTAB         = ROMA.ESTAB
                              AND ROMATXSERVICOPG.ROMANEIO      = ROMA.ROMANEIO
                              AND ROMATXSERVICOPG.ENTRADASAIDA  = ROMA.ENTRADASAIDA
                              AND ROMATXSERVICOPG.NUMEROCM      = ROMA.NUMEROCM),0)))) ELSE 0 END AS ROMANEIOS,                           
    0 AS DEPOSITO   
    

FROM ROMA
    INNER JOIN FILIAL ON
    FILIAL.ESTAB            = ROMA.ESTAB

    INNER JOIN PEMPRESA ON
    PEMPRESA.EMPRESA        = FILIAL.EMPRESA

    INNER JOIN CIDADE FILCID ON
    FILCID.CIDADE           = FILIAL.CIDADE

    INNER JOIN ROMACFG ON
    ROMACFG.ROMANEIOCONFIG  = ROMA.ROMANEIOCONFIG

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM       = ROMA.NUMEROCM
    
    LEFT JOIN CONTAMOVGRUPO ON
    CONTAMOV.GRUPOCM = CONTAMOVGRUPO.GRUPOCM

    INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
    
    INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO
    
    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM       = ROMA.NUMEROCM AND
    ENDERECO.SEQENDERECO    = ROMA.SEQENDERECO

    LEFT JOIN PPESSPRE ON
    PPESSPRE.PRESTADOR      = ROMA.PRESTADOR

    INNER JOIN ROMACLASS ON
    ROMACLASS.ESTAB         = ROMA.ESTAB AND
    ROMACLASS.ROMANEIO      = ROMA.ROMANEIO AND
    ROMACLASS.ENTRADASAIDA  = ROMA.ENTRADASAIDA AND
    ROMACLASS.NUMEROCM      = ROMA.NUMEROCM AND
    ROMACLASS.PERCENTUAL    > 0

    INNER JOIN ROMACLASSNOME ON
    ROMACLASSNOME.CLASSIFICACAO = ROMACLASS.CLASSIFICACAO

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = CASE WHEN ROMACLASS.ITEM IS NULL or (ROMACLASS.ITEM = 0) THEN ROMA.ITEM ELSE ROMACLASS.ITEM END

    LEFT JOIN NFCABROMA ON
    NFCABROMA.ESTAB         = ROMACLASS.ESTAB AND
    NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO AND
    NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA AND
    NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM

    LEFT JOIN NFCAB ON
    NFCAB.ESTAB             = NFCABROMA.ESTAB AND
    NFCAB.SEQNOTA           = NFCABROMA.SEQNOTA


    WHERE NOT EXISTS (SELECT ROMA.ROMANEIO FROM NFCABROMA
        WHERE NFCABROMA.ESTAB         = ROMACLASS.ESTAB
          AND NFCABROMA.ROMANEIO      = ROMACLASS.ROMANEIO
          AND NFCABROMA.ENTRADASAIDA  = ROMACLASS.ENTRADASAIDA
          AND NFCABROMA.NUMEROCM      = ROMACLASS.NUMEROCM)
         AND ROMA.ESTORNADO            = 'N'
         AND ((0 IN (:ESTAB)) OR (ROMA.ESTAB IN (:ESTAB)))
  	     AND (0 IN (:SAFRA)    or (ROMA.SAFRA     IN (:SAFRA)))
         AND roma.dtemissao BETWEEN :DTINI AND :DTFIM
        -- AND (0 IN (:NUMEROCM) or (ROMA.NUMEROCM  IN (:NUMEROCM)))
         AND (0 IN (:ITEM)     or (ROMA.ITEM      IN (:ITEM)))
   
   GROUP BY  FILIAL.ESTAB,
    FILIAL.REDUZIDO, 
    ROMACFG.entradasaida,
    CONTAMOV.NUMEROCM,
    CONTAMOV.NOME,CONTAMOV.NUMEROCM,    
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO, CONTAMOVGRUPO.GRUPOCM ,CONTAMOVGRUPO.DESCRICAO,
    ROMA.TIPO,ROMA.LOCAL,contamov.cnpjf

UNION ALL

SELECT
    *
FROM SALDO_MANUAL
    
  
/*RETORNA DADOS DE DEPOSITO*/
UNION ALL

SELECT  DADOS.ESTAB,
        DADOS.REDUZIDO,
        DADOS.NUMEROCM,
  dados.cnpjf,
         DADOS.PESSOA,
         DADOS.GRFAMILIA,
        DADOS.CONCEITO,       
        DADOS.ITEM,
        DADOS.PRODUTO,
        DADOS.CONTRATO,
        DADOS.LOCAL,
        COALESCE(DADOS.TIPO,0)TIPO,
        DADOS.ROMANEIOE,
        DADOS.ROMANEIOS,
        SUM(DADOS.DEPOSITO)DEPOSITO

FROM(
SELECT
    FILIAL.ESTAB,
    FILIAL.REDUZIDO,   
    CONTAMOV.NUMEROCM,
  contamov.cnpjf as cnpjf,
    CONTAMOV.NOME||' - '||CONTAMOV.NUMEROCM AS PESSOA,
    CASE WHEN CONTAMOVGRUPO.GRUPOCM IS NULL THEN 'S/GRUPO'||' - '||CONTAMOV.NOME ELSE CONTAMOVGRUPO.GRUPOCM||' - '||CONTAMOVGRUPO.DESCRICAO END GRFAMILIA,
    CONCEITO.CONCEITO||'-'||CONCEITO.DESCRICAO AS CONCEITO,
    ITEMAGRO.ITEM,
    ITEMAGRO.DESCRICAO PRODUTO,
    NFITEM.LOCAL,
    0 AS CONTRATO,
    NFITEM.FINATIPOROMA AS TIPO,
    0 AS ROMANEIOE,
    0 AS ROMANEIOS,
    NFITEM.QUANTIDADE -
    COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                       INNER JOIN NFITEM NFI ON
                                       NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                                       NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                                       NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM

                                       INNER JOIN NFCAB NFDV ON
                                       NFDV.ESTAB = NFI.ESTAB AND
                                       NFDV.SEQNOTA = NFI.SEQNOTA

                                       INNER JOIN NFCFG NFCFGDV ON
                                       NFCFGDV.NOTACONF = NFDV.NOTACONF /*AND
                                       NFCFGDV.NOTACONF IN (207,208,221,233,259) */

                                       INNER JOIN NATOPERACAO NATDV ON
                                       NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                       NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                                       NATDV.TIPODCTO = 'D'

                                       WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                                         AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                         AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                                       ),0) -
    COALESCE((SELECT COALESCE(SUM(NFITEMAPARTIRDE.QUANTIDADE),0) FROM NFITEMAPARTIRDE
                                       INNER JOIN NFITEM NFI ON
                                       NFI.ESTAB = NFITEMAPARTIRDE.ESTAB AND
                                       NFI.SEQNOTA = NFITEMAPARTIRDE.SEQNOTA AND
                                       NFI.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEM

                                       INNER JOIN NFCAB NFDV ON
                                       NFDV.ESTAB = NFI.ESTAB AND
                                       NFDV.SEQNOTA = NFI.SEQNOTA

                                       INNER JOIN NFCFG NFCFGDV ON
                                       NFCFGDV.NOTACONF = NFDV.NOTACONF

                                       INNER JOIN NATOPERACAO NATDV ON
                                       NATDV.NATUREZADAOPERACAO = NFCFGDV.NATUREZADAOPERACAO AND
                                       NATDV.ENTRADASAIDA = NFCFGDV.ENTRADASAIDA AND
                                       NATDV.TIPODCTO = 'X'

                                       WHERE NFITEM.ESTAB = NFITEMAPARTIRDE.ESTABORIGEM
                                         AND NFITEM.SEQNOTA = NFITEMAPARTIRDE.SEQNOTAORIGEM
                                         AND NFITEM.SEQNOTAITEM = NFITEMAPARTIRDE.SEQNOTAITEMORIGEM
                                       ),0) AS DEPOSITO
FROM NFCAB
    INNER JOIN FILIAL ON
    FILIAL.ESTAB            = NFCAB.ESTAB

    INNER JOIN CIDADE CIDFIL ON
    CIDFIL.CIDADE           = FILIAL.CIDADE

    INNER JOIN NFCFG ON
    NFCFG.NOTACONF          = NFCAB.NOTACONF AND
    NFCFG.ENTRADASAIDA      = 'E'

    INNER JOIN NATOPERACAO ON
    NATOPERACAO.NATUREZADAOPERACAO  = NFCFG.NATUREZADAOPERACAO AND
    NATOPERACAO.ENTRADASAIDA        = NFCFG.ENTRADASAIDA AND
    NATOPERACAO.TIPODCTO            = 'A'

    INNER JOIN CONTAMOV ON
    CONTAMOV.NUMEROCM       = NFCAB.NUMEROCM
    
    LEFT JOIN CONTAMOVGRUPO ON
    CONTAMOVGRUPO.GRUPOCM = CONTAMOV.GRUPOCM
    
    INNER JOIN CONCEITOPESSOA ON CONCEITOPESSOA.NUMEROCM=CONTAMOV.NUMEROCM
    
    INNER JOIN CONCEITO ON conceito.conceito = CONCEITOPESSOA.CONCEITO

    LEFT JOIN ENDERECO ON
    ENDERECO.NUMEROCM       = NFCAB.NUMEROCM AND
    ENDERECO.SEQENDERECO    = NFCAB.SEQENDERECO

    LEFT JOIN CIDADE ON
    CIDADE.CIDADE           = CASE WHEN NFCAB.SEQENDERECO IS NOT NULL AND NFCAB.SEQENDERECO > 0 THEN ENDERECO.CIDADE ELSE CONTAMOV.CIDADE END

    INNER JOIN NFITEM ON
    NFITEM.ESTAB            = NFCAB.ESTAB AND
    NFITEM.SEQNOTA          = NFCAB.SEQNOTA

    INNER JOIN ITEMAGRO ON
    ITEMAGRO.ITEM           = NFITEM.ITEM
WHERE NFCAB.DTEMISSAO BETWEEN :DTINI AND :DTFIM
  AND (0 IN (:ESTAB)    or (NFCAB.ESTAB     IN (:ESTAB)))
    AND (0 IN (:SAFRA)    or (NFCAB.SAFRA     IN (:SAFRA)))
 -- AND (0 IN (:NUMEROCM) or (NFCAB.NUMEROCM  IN (:NUMEROCM)))
  AND (0 IN (:ITEM)     or (NFITEM.ITEM     IN (:ITEM)))
  
  )DADOS
  
  GROUP BY DADOS.ESTAB,
        DADOS.REDUZIDO,
        DADOS.NUMEROCM,
        DADOS.PESSOA,
        DADOS.CONCEITO,
        DADOS.ITEM,
        DADOS.PRODUTO,
        DADOS.CONTRATO,
        DADOS.LOCAL,
        DADOS.ROMANEIOE,
        DADOS.ROMANEIOS,
        DADOS.TIPO,DADOS.GRFAMILIA,dados.cnpjf
        
    HAVING   SUM(ARREDONDAR(DADOS.DEPOSITO,0))>0
  	

)DADOS

GROUP BY

DADOS.ESTAB, DADOS.REDUZIDO, DADOS.NUMEROCM, dados.cnpjf,DADOS.PESSOA,DADOS.CONCEITO, DADOS.ITEM, DADOS.PRODUTO, DADOS.TIPO, DADOS.LOCAL,DADOS.GRFAMILIA
  
  )DADOS1
  
  WHERE   (ARREDONDAR(DADOS1.DEPOSITO,0)) <> 0 
  OR (ARREDONDAR(DADOS1.SALDOFIS,0)) <> 0 
  OR (ARREDONDAR(DADOS1.ROMANEIOE,0)) <> 0 
  OR (ARREDONDAR(DADOS1.ROMANEIOS,0)) <> 0 
  OR (ARREDONDAR(DADOS1.SALDOPROD,0)) <> 0 
  OR (ARREDONDAR(DADOS1.CONTRATO,0)) <> 0 
  
 /* HAVING SUM(ARREDONDAR(DADOS1.DEPOSITO,0)) <> 0 
  OR SUM(ARREDONDAR(DADOS1.SALDOFIS,0)) <> 0 
  OR SUM(ARREDONDAR(DADOS1.ROMANEIOE,0)) <> 0 
  OR SUM(ARREDONDAR(DADOS1.ROMANEIOS,0)) <> 0 
  OR SUM(ARREDONDAR(DADOS1.SALDOPROD,0)) <> 0 
  OR SUM(ARREDONDAR(DADOS1.CONTRATO,0)) <> 0 */
