SELECT  FILIAL.ESTAB AS ESTABORIGEM,
        LOCALEST.LOCAL AS LOCALORIGEM,
        LOCEQUI_U.ESTAB AS ESTABDESTINO,
        LOCEQUI_U.LOCAL AS LOCALDESTINO,    
        ITEMAGRO.DESCRICAO||' - '||FILIAL.ESTAB||'-'||LOCALEST.DESCRICAO||' / '||LOCEQUI.ESTAB||'-'||LOCEQUI.DESCRICAO AS LOCALXLOCAL,        
        SALDOITEM(LOCALEST.ESTAB, ITEMAGROESTAB.ITEM, :CODIGOSALDO, LOCALEST.LOCAL, LOCALEST.LOCAL,:DATA,NULL,NULL,NULL,NULL) AS SALDOORIGEM,
        SALDOITEM(LOCEQUI_U.ESTAB, ITEMAGROESTAB.ITEM, :CODIGOSALDO, LOCEQUI_U.LOCAL, LOCEQUI_U.LOCAL,:DATA,NULL,NULL,NULL,NULL) AS SALDOEQUIVALENTE
FROM FILIAL
INNER JOIN LOCALEST
  ON FILIAL.ESTAB = LOCALEST.ESTAB
INNER JOIN LOCALEST_U
  ON LOCALEST.ESTAB = LOCALEST_U.ESTAB
  AND LOCALEST.LOCAL = LOCALEST_U.LOCAL
INNER JOIN LOCALEST_U LOCEQUI_U
  ON LOCALEST_U.ESTAB = LOCEQUI_U.NUMEROCM
  AND LOCALEST_U.NUMEROCM = LOCEQUI_U.ESTAB
  AND LOCEQUI_U.ESTAB <> LOCALEST.ESTAB
INNER JOIN LOCALEST LOCEQUI
  ON LOCEQUI_U.ESTAB = LOCEQUI.ESTAB
  AND LOCEQUI_U.LOCAL = LOCEQUI.LOCAL
INNER JOIN ITEMAGROESTAB
  ON ITEMAGROESTAB.ESTAB = FILIAL.ESTAB
INNER JOIN ITEMAGRO
  ON ITEMAGROESTAB.ITEM = ITEMAGRO.ITEM
LEFT JOIN ITEMGRUPO
  ON ITEMAGRO.GRUPO = ITEMGRUPO.GRUPO
WHERE 0=0
  <#if ESTABORIGEM?has_content>
    AND FILIAL.ESTAB IN ( :ESTABORIGEM )
  </#if>
  <#if ESTABDESTINO?has_content>
    AND LOCEQUI_U.ESTAB IN ( :ESTABDESTINO )
  </#if>
  <#if GRUPO?has_content>
    AND ITEMAGRO.GRUPO IN ( :GRUPO )
  </#if>
  <#if MARCA?has_content>
    AND ITEMAGRO.MARCA IN ( :MARCA )
  </#if>
  <#if GRUPOCONTABIL?has_content>
    AND ITEMGRUPO.GRUPOCONTABIL IN ( :GRUPOCONTABIL )
  </#if>
  <#if ITEM?has_content>
    AND ITEMAGRO.ITEM IN ( :ITEM)
  </#if>