create or replace TRIGGER OS_ATPRECOVDA
BEFORE INSERT OR UPDATE ON ITEMAGROESTAB
FOR EACH ROW
DECLARE
    V_EXISTE NUMBER;
BEGIN

    SELECT 1
      INTO V_EXISTE
      FROM U_TEMPRESA
     WHERE INSUMOS = 'S'
       AND EXVENDA = 'S'
       AND ESTAB = :NEW.ESTAB;

     IF (:NEW.MARGEMLUCRO <> 0 AND :NEW.CUSTOGERENCIAL <> 0 AND V_EXISTE = 1) THEN  

    :NEW.PRECOVENDA:=((:NEW.CUSTOGERENCIAL)/((100-:NEW.MARGEMLUCRO)))*100;

     END IF;

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;

END;